### ISSUE TITLE
rename getFacilityV2 to getAllFacilities; Cleanup getFacility in Redux Actions

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#1818]
Cleanup and remove one of getFacility or getFacilityV2 if both are not needed

**Comment by Apurva-Nagar** [comment]
They both hit different endpoints. 

- getFacility calls the /facility endpoint.
- getFacilityV2 calls the /getallfacilities endpoint (which is used to get a list of all facilities without user role level restrictions, this is being used atleast in the filters)

So, I think we need them both @gigincg

**Comment by gigincg** [comment]
@Apurva-Nagar It's fine to have them both, you could rename one to "getAllFacilities" or so. This causes unnecessary confusion. I merged 2 PRs where somebody mixed it up and was later on fixing it.
