### ISSUE TITLE
Add date and time on sample test history 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#1823]
Add "date & time"  sample test history card in the patient dashboard. 

* logged in as staff (hospital)
* selected a particular patient 
* Generated  a request for sample test to concerned laboratories.
see url - https://care.coronasafe.in/facility/997c7f30-8e2f-4d62-8b58-2a8771e658d6/patient/feb507b6-f843-442b-95f7-6edf3283e7a9
Now the generated request will visible as sample test history with which facility and what kind of testing is requested etc.
 On the sample test card the missing info are ;
- date and time of request generated/updated
- user that created/updated the request.

see the attached file,

![image](https://user-images.githubusercontent.com/75214902/133618825-1e97c5ca-af4e-4c43-8c3b-dcdca74511e6.png)

Add the missing info;
follow format of update log on consultation history card.

**Comment by shaileshaanand** [comment]
The fields are not present in sample api, need backend changes for this.
