### ISSUE TITLE
Add "District_labadmin" user type to "District_admin" login

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#1828]
District_labadmin user type is only visible to State_admin.

- Add the user type "District_Lab_admin"  under  District_admin, by then only a district admin can create or edit laboratory users.

**Comment by Sandra3657** [comment]
Can the "district_lab_admin" create or edit "district_admin"? @samholics

**Comment by samholics** [comment]
No, Only distric_admin should edit or create district_lab_admin @Sandra3657
