### ISSUE TITLE
Remove the badge " Assigned_to" when clear the filter 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#1830]
"Assigned _to" badge is still exists even when the same filter value is cleared nor if we click "clear all " in the shifting module.

* logged in as district admin
* open shifting
* select  filters
* select any value in the field " assigned_ to" and apply
*again select filters and remove the value in "assigned_to" and submit
*The data came back to unfiltered and the badge for above remains 
* even if we click "clear all" in the filter, badge still remains 

![image](https://user-images.githubusercontent.com/75214902/133896433-649caa3d-db30-423a-9ef6-256974105c27.png)
@khavinshankar

**Comment by khavinshankar** [comment]
Resolved in #1820
