### ISSUE TITLE
MISSING    "sample_test _type"  in request cards in sample test !!!

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#1832]
At present there is no way to find out which test should be done in a particular lab by requests received in their sample test module.

*logged in as lab user (staff)
*selected sample test 
*opened a request to process

https://care.coronasafe.in/sample/1d87f74b-a1c3-4cb1-b8fd-cca584f1d2a9

- Add sample test type in sample details page.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/52771399/134027417-89883f9f-3dd0-4065-a1a6-1302a1e916f3.png)

@samholics 
I see sample test type(in bottom-most in screenshot) is shown in patient details section rather than on sample test details section. Should it be inside sample test details?

**Comment by ghost** [comment]
Oh is it sample type or test type? 🤔

**Comment by samholics** [comment]
oh yes its there.
but its not noticeble if its in the patient details. so can you move to the sample details.?
its like sample test type. @abhinandanarya06
