### ISSUE TITLE
(Incomplete issue) Add antenatal field in Exported Patient list (excel) 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#1839]
Add a field for Antenatal yes/no column in the exporting patient list.

For example if we download the live list as excel sheet there is no such field present "Is the patient  Antenatal"  

More missing fields in export, all these fields to be mapped by @samholics DONOT TAKE THE ISSUE NOW

**Comment by gigincg** [comment]
@samholics Feel free to reopen if you get the information required to make the issue Complete!
