### ISSUE TITLE
Accept Daily Rounds with and without Critical Care Data

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#1843]
The Critical Care data makes the data entry overwhelming operationally. Considering that most hospitals don't use this, build an selection at the beginning of the Consultation Update Form that hides/shows the Critical Care Input based on whether the user wants to input Critical Care Data or Not.

**Comment by Sandra3657** [comment]
![image](https://user-images.githubusercontent.com/62461536/134453652-ce2a1915-df8e-45c7-b1d4-2a0f29ad48d7.png)

Are these the fields that need to be hidden, along with the ones that are in PR #1720?
@gigincg

**Comment by gigincg** [comment]
@Sandra3657 No, this issue is for DailyRounds/Consultation Update. We need to remove the Critical Care Components(Vitals) Based on a Selection early on in the form that asks whether they are entering vitals or not.

**Comment by nihal467** [comment]
@gigincg is this issue a wishlist or relevant

**Comment by gigincg** [comment]
@nihal467 This has been solved with "Regular" Rounds
