### ISSUE TITLE
Changes in Log Update : Consultation Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#1863]
![,s;,df](https://user-images.githubusercontent.com/57055998/134971419-4f8cf307-da29-42f5-b492-2fc42bd4da9b.PNG)

when we are selecting Round Type as Normal we want to list  :
1.  Hemodynamic Parameter (Vitals)
2.  SPO2

in the same page and, when the round type is Critical Care, then only, we need to be redirected to the whole critical care sections

**Comment by nihal467** [comment]
@bodhish @Sandra3657 @gigincg @aparnacoronasafe

**Comment by Sandra3657** [comment]
For both the rounds types, it should finally be redirected to critical care sections? Or is it only for the 'critical care' round type?
