### ISSUE TITLE
Redirecting to patient list when a patient card opened and click "back" from 'shifting' module.

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#1866]
when a patient card opened from shifing request, after opened consultation details and click back the page redirecting to patient list.

* logged in as district admin
* selected shifting
* open any shifting request from the shifting module

![image](https://user-images.githubusercontent.com/75214902/135051788-c4a64e55-9e16-4c11-a64f-5c2e6a69f301.png)

* click on Patient Name from the shifting details page

![image](https://user-images.githubusercontent.com/75214902/135051993-be3e698d-3f4d-497c-8c47-8eb068af9a8d.png)

* open consultations of the patient and go back to patient card

* click back from patient card 

* now the page goes to whole patient list  instead of  "shifting_details" page.

This bug is very difficult when trying to shift a patient. Mainly shifting control room is using this path and now they have to spend more time on click shifting and find that particular patient from the whole shifting module once again for further updations. if any more queries comes up regarding this issue pls ping me

**Comment by shaileshaanand** [comment]
PR #1867 Should fix this
