### ISSUE TITLE
Error Notification Poping Up and Not able to Opening Care

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#1890]
![photo_2021-10-07_16-19-42](https://user-images.githubusercontent.com/57055998/136370295-0fedd1fa-7f25-4999-8dcb-79609b21499e.jpg)

when we are opening care from iPhone google chrome mobile browser, this error keep on popping up and unable to operate care

**Comment by Apurva-Nagar** [comment]
iOS native applications do not support Push Notifications as of now (https://stackoverflow.com/questions/43994660/push-notifications-on-ios-from-web-app). @gigincg any thoughts on what we can do to improve the experience for iPhone users?

**Comment by gigincg** [comment]
@Apurva-Nagar This is an old question, iOS does have improved support for push notification these days. @nihal467 @aparnacoronasafe notifications were working on iOS before right?

**Comment by Apurva-Nagar** [comment]
@gigincg
[WebKit -  Feature Request: Add support for the ServiceWorkerRegistration's PushManager interface](https://bugs.webkit.org/show_bug.cgi?id=182566)
And Webkit Browser Engine, powers Mobile Safari and all other browsers on iOS including Chrome and Firefox for iOS.

**Comment by nihal467** [comment]
#1909

**Comment by gigincg** [comment]
@nihal467 is this still an issue

**Comment by nihal467** [comment]
the issue is resolved
