### ISSUE TITLE
Export Button Malfunction : External Results

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#1894]
![ojeofjweopfw](https://user-images.githubusercontent.com/57055998/136423437-329be3e5-f605-4890-a247-057a37c1b196.PNG)

when we click on export button, the screen goes white

**Comment by Apurva-Nagar** [comment]
@nihal467 I tried replicating the issue on staging. Everything seems to be working fine for me
https://www.loom.com/share/b203fb1a527f46bf9324c639e64cc6dc

**Comment by nihal467** [comment]
@Apurva-Nagar after hard-refreshing, the button is started working for me. so can you close this issue!
