### ISSUE TITLE
File Preview not Working

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#1897]
![asmcsa](https://user-images.githubusercontent.com/57055998/136448010-01c12d65-dca3-4fcd-9446-5114ccd3c87d.PNG)

File preview function is not working in consultation, patient files after uploading a .jpg file

**Comment by arpancodes** [comment]
@tomahawk-pilot another CSP error
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/42417893/136668388-89cd75a3-262c-4878-927c-ecd8531d64d9.png">

**Comment by aeswibon** [comment]
Fixed with issue #2297
