### ISSUE TITLE
info : Consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#1899]
![apfoeaofp](https://user-images.githubusercontent.com/57055998/136449401-71d7d715-244d-4854-bfe2-70353cb2e359.PNG)

the data of height, weight, and body surface area are been given as three cards,  in consultation update, can we make it in one odd card ?

**Comment by Apurva-Nagar** [comment]
@nihal467 I'm taking care of this in the missing fields PR (https://github.com/coronasafe/care_fe/pull/1720)
