### ISSUE TITLE
Rearrange Parameters when selecting "Normal_care" In Consultation updates.

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#1910]
rearrange the parameters when selecting Normal_care in Daily rounds (Consultation Updates)
the issue regarding PR #1873 

Also please refer below attached file for more idea, vitals has to be simple and looks the same size as existing parameters in the form. 

[consultation normal concept (1).pdf](https://github.com/coronasafe/care_fe/files/7323808/consultation.normal.concept.1.pdf)

@gigincg @Sandra3657 @nihal467

**Comment by Sandra3657** [comment]
Could you elaborate this "Instead of scroll bar in a separate bar , add the minimum _max values in the box as scrolldown
and also avail typing."? @samholics
