### ISSUE TITLE
Contact phone number for Asset is required but not marked

### ISSUE THREAD

**Issue by shaileshaanand** [coronasafe/care_fe#1914]
**Describe the bug**
When an asset is created or updated, `Contact phone number` field for support is required but the form can be submitted without filling the field and an error is shown.

**To Reproduce**

1. Go to 'https://care.coronasafe.in/facility/01810c32-ec26-494a-9e65-40e5547a7746/assets/new'
2. Fill the required fields except "Contact Phone Number"
3. Click on 'CREATE'

**Expected behavior**
The form should not submit, an error should appear below the field.

**Screenshots**

![Screenshot from 2021-10-14 21-22-26](https://user-images.githubusercontent.com/26682202/137353291-6000cb17-eaf4-4946-b1d3-b41a11e607d3.png)

**Comment by pallavipriya4321** [comment]
Please assign this issue to me. I want to contribute for hacktoberfest.

**Comment by pallavipriya4321** [comment]
I have created a Pull Request for this issue. Please Review it.
