### ISSUE TITLE
Shifting Filter Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#1927]
https://user-images.githubusercontent.com/57055998/138724923-0f8a4809-16f3-48d8-96e0-6189a956c471.mp4

the pre-applied filters are been auto-selected in shifting

**Comment by gigincg** [comment]
@khavinshankar do note that filters should not be cleared when you open a shifting card and come back. This was a feature built before.

**Comment by khavinshankar** [comment]
@nihal467 this is not a bug, this is expected behavior (feature).

**Comment by khavinshankar** [comment]
@nihal467 @gigincg  To make things easier for the users we can add a `Clear All Filters` badge. what's your opinion?

**Comment by gigincg** [comment]
@khavinshankar it's surely a good feature to have!
