### ISSUE TITLE
Fix Spacing : Discharge Pop-Up

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#1935]
![dvfreveve](https://user-images.githubusercontent.com/57055998/139189511-9adfce17-913f-4c80-bbae-81581305ee0a.png)

make the spacing and alignement in between the radio button proper

**Comment by shaileshaanand** [comment]
I can't reproduce this.

![Screenshot from 2021-11-01 14-20-19](https://user-images.githubusercontent.com/26682202/139646307-b7886360-daf1-4dd5-97bf-30d4ad0fe525.png)

@nihal467

**Comment by ProCode2** [comment]
@nihal467 Can't reproduce this on my end. Are you still seeing this issue?

**Comment by gigincg** [comment]
Can't Reproduce; Closing
