### ISSUE TITLE
Investigation : Alignment Issue

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#1938]
![rgergrg](https://user-images.githubusercontent.com/57055998/139192142-7572c8d3-1978-46d1-ae9c-2311d7c78421.png)

the heading is not aligned

**Comment by shaileshaanand** [comment]
I have found the same issue on 4 more pages:

![Screenshot from 2021-11-01 14-03-10](https://user-images.githubusercontent.com/26682202/139644759-36368595-5e1c-4109-aac0-f525ed93f07d.png)
![Screenshot from 2021-11-01 14-02-44](https://user-images.githubusercontent.com/26682202/139644767-18a979e9-f92b-437c-93f3-e0e549a4ec39.png)
![Screenshot from 2021-11-01 14-00-37](https://user-images.githubusercontent.com/26682202/139644770-f44bf0fd-363c-4b5d-beab-11a76ef6cef2.png)
![Screenshot from 2021-11-01 14-00-32](https://user-images.githubusercontent.com/26682202/139644773-3eb68516-ba58-487c-be36-a20f53109720.png)

I am fixing all of them.
