### ISSUE TITLE
Create UI for Camera Feed

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#1939]
The Camera Feed has been added to the "teleicu" branch. The Icons and the Buttons need to be added next

Reference Design:

![image](https://user-images.githubusercontent.com/13028584/139192257-e775ed60-e13a-4bd0-bbce-8b24b653c674.png)

**Comment by Apurva-Nagar** [comment]
Made the required changes 99f0920bbc110634ee36021dad2611b3e291ebcc in branch `teleicu`
