### ISSUE TITLE
Create Camera Setup UI in Assets

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#1960]
In the Asset Page, Create a button to Configure the Asset if the Asset is a Camera

![image](https://user-images.githubusercontent.com/13028584/142007278-90ad7a37-0ee8-4b0f-8e76-0a5544ff1300.png)

Create the Configure Camera Asset Form with the Camera IP Address, the hospital hostname(middleware) etc (To be stored in the metadata JSON)

![image](https://user-images.githubusercontent.com/13028584/142007446-1cc3e434-d27b-46e2-adbb-0e4be79495cd.png)

Add the Camera Preview (When Type of Asset is Camera) and add the buttons for Pan, Zoom etc and in addition, buttons to set the current Pan/Zoom as a Preset. (The Presets would be stored as an array in the metadata JSON)

Disclaimer: The APIs for these are not yet complete. Requires the teleicu_middleware project to be up.

**Comment by peeyush14goyal** [comment]
So we just have to build the UI for now?
