### ISSUE TITLE
Intubation and Exhumation using Admitted to

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#1972]
The dates "Intubated on" and "exhumated on" in the should be based on Admission to Invasive Ventilator and Moving out of Invasive Ventilator

**Comment by khavinshankar** [comment]
@gigincg can you please elaborate on the above description

**Comment by gigincg** [comment]
@khavinshankar @arpancodes 
There is no need to collect the dates for intubated on or exhumated on. If an entry is made where the patient is admitted to invasive ventilator, the date/time of that entry(ConsultationUpdate/DailyRound) would be the date the patient is intubated on. The opposite would be the date when they're exhumated on. 

Need to check on where these dates are currently visualized, this issue is to remove the said fields (intubated and exhumated) and use the date of the first consultationUpdate with Admitted to as Invasive Ventilator to visualize this.

**Comment by arpancodes** [comment]
got it... will check where they are being used.

**Comment by khavinshankar** [comment]
@arpancodes are you working on this issue?

**Comment by arpancodes** [comment]
Yes! @khavinshankar will work on it during the weekend 😄

**Comment by gigincg** [comment]
@arpancodes Did you get to work on this? Can you clear this out?

**Comment by nihal467** [comment]
@gigincg is this a wishlist or a relevant issue right now

**Comment by gigincg** [comment]
@aparnacoronasafe This is still needed right?

Cc: @nihal467

**Comment by nihal467** [comment]
@aparnacoronasafe can you comment on this issue

**Comment by aparnacoronasafe** [comment]
@gigincg Losing context here. Right now, we are not capturing the intubation exhumation dates. All we have is the date of log update filed with the info. 

What was the requirement here again?

**Comment by nihal467** [comment]
@gigincg it is blocked dependent on events

**Comment by aparnacoronasafe** [comment]
Requirement:

- [ ] The Respiratory support Tab on patient dashboard (https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/dbc8c312-3700-4fd5-915e-f53cc28e092a/consultation/8ecb4c49-49d6-4216-87c0-7dc6408d9788/ventilator)

to show a timeline of respiratory support provided to the patient. It could be a table showing:

Type of respiratory support.        |           Date and time of start        |        Date and time of end
O2                                                       DD/MM/YYYY, HH:MM AM/PM.    DD/MM/YYYY, HH:MM AM/PM


At 1 time there can only be 1 type of respiratory support given to the patient. 


- [ ] Going ahead we will also require the start date and time and type of respiratory support to be plotted on the graphs in the respiratory support tab as vertical lines (start and end).

**Comment by aparnacoronasafe** [comment]
This is covered in #8256 

@gigincg please confirm is this can be closed
