### ISSUE TITLE
Attach Critical Care patients to Beds of the facility

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#1987]
For Consultation Update entries, add a field to receive the Bed the patient is assigned to. Backend changes are done.

**Comment by khavinshankar** [comment]
@gigincg, 
 1. should it be added to the DailyRounds form?
![image](https://user-images.githubusercontent.com/29787772/146517290-33ae5ed5-8936-4c63-bc0b-69912d1c66a8.png)

 2.  and about the input type, it should be a dropdown or just text input?

**Comment by gigincg** [comment]
Fixed by #2001
