### ISSUE TITLE
Focus Button for Camera Live Feed

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#1994]
Create button to Focus Far and Focus Near along with the Zoom buttons

**Comment by shaileshaanand** [comment]
The [onvif](https://www.npmjs.com/package/onvif) library does have an API for focus.
[Documentation](https://agsh.github.io/onvif/)

**Comment by nihal467** [comment]
@gigincg is it still required ?

**Comment by gigincg** [comment]
So far in our testing, focus is not possible over the ONVIF library we are using
