### ISSUE TITLE
Validation for `Contact with confirmed Covid patient`  is missing in PatientForm

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#2005]
**Describe the bug**
In the patient form `Contact with confirmed Covid patient?` is set to `No` but `Estimate date of contact` and `Name / Cluster of Contact` are still shown in the patient dashboard.

**To Reproduce**

1. Go to `Patients`
2. Select a random Patient
3. Click on `Update Details`
4. Scroll down to the `Health Details` section
5. Select the 'yes' option for `Contact with confirmed Covid patient?` 
6. Select a random date for `Estimate date of contact` and a random name for `Name / Cluster of Contact`
7. Now select the 'no' option for `Contact with confirmed Covid patient?`
8. Click on 'Save Details' to submit the form
9. Now on the Patient page scroll down to see `Testing` details
10. In there you can see that `Estimate date of contact` and `Name / Cluster of Contact` is having the selected date and set name
11. See the error

**Expected behavior**
`Estimated Contact Date` and `Contact Name / Cluster` should be empty (`-`)

**Screenshots**
![image](https://user-images.githubusercontent.com/29787772/148319841-153992dd-ee3b-47b0-9e97-77ab35e6e5d8.png)

![image](https://user-images.githubusercontent.com/29787772/148318962-fd66e703-0ba4-494c-80a1-945d18a99103.png)

**Comment by nihal467** [comment]
test approved
