### ISSUE TITLE
Improve Patient Dashboard for Critical Care

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2008]
A lot of space in the Patient Page is currently consumed by COVID specific details, such as Testing, Location etc. The needs to be changed to improve the experience for Caregivers treating non-COVID patients.

The dashboard should contain:
 - A flag on the top right if the Patient has some Allergies
 - Vitals from Last Consultation Update (The Last Consultation Update will be Joined with consultation update) -> BE Pending
 - Move Address/Location to Header Area, along with the Name of the Patient
 
> Note: Do not delete the existing Patient Page. We might need to use the same for COVID Patients.

**Comment by sam9111** [comment]
Also remove status of Frontline Worker (Not Relevant for Outside Kerala/Non-COVID) and Medical Worker
