### ISSUE TITLE
Presets for Infusion/Output

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2011]
Preset(default) values for "Infusions" and "Outputs" under I/O Balance editor can be set.

**Comment by gigincg** [comment]
This would work like a set of buttons with the common infusions and outputs. If the count is too big to be listed, we'd have to use a searchable dropdown

**Comment by aparnacoronasafe** [comment]
@gigincg what is intended here?

**Comment by gigincg** [comment]
@aparnacoronasafe Need to reconfirm with Dr. Athul, the issue is not descriptive enough.

**Comment by aparnacoronasafe** [comment]
Cant make sense of this either. Closing this issue
