### ISSUE TITLE
Rework in Consultation Module to support Non-COVID patients

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2012]
Here are some fields irrelevant for non-COVID Patients:
- IP Number
- State Test ID
- Category

**Comment by aeswibon** [comment]
Apart from IP number and State Test Id, what other fields shouldn't be there? 
(I don't know what you mean by mentioning the **Category** field?)

**Comment by aeswibon** [comment]
The __Category__ field has already been removed and __IP number__ shouldn't be removed.
