### ISSUE TITLE
Text Change for Travel history

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2013]
In patient register page, change text from 28 days to 14 days.

**Comment by sam9111** [comment]
Need to be changed in backend as well.

**Comment by sam9111** [comment]
https://github.com/coronasafe/care/issues/661

**Comment by gigincg** [comment]
What needs to be changed in Backend? @sam9111

**Comment by sam9111** [comment]
> What needs to be changed in Backend? @sam9111

just noticed the verbose name for the past_travel attribute has the line "Travelled to Any Foreign Countries in the last 28 Days"...thought it could be changed to avoid confusion in the future
