### ISSUE TITLE
UI change in Medical History

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2014]
In Medical History section of "Add Details of Covid Suspect / Patient" page, change "Any Medical History" question to a dropdown with OTHER as custom fill option.

**Comment by sam9111** [comment]
Get  ICDS compliance/NDHM code list from Aparna

**Comment by aparnacoronasafe** [comment]
There are more changes required in medical history than simply adding ICD-11. it is explained in https://github.com/coronasafe/care_fe/issues/2218.

Track it in #2218

**Comment by aparnacoronasafe** [comment]
Redundant issue.
