### ISSUE TITLE
Introducing ICD-11 for diagnosis

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2016]
Make the "Diagnosis" section as a dropdown with OTHER as a custom fill option.

**Comment by sam9111** [comment]
Get ICDS compliance/NDHM code list from @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
@khavinshankar @sam9111 Please proceed with the ICDS Index.

**Comment by aparnacoronasafe** [comment]
The "Diagnosis" field must be a text field. This text field must allow the user to type and search through any disease in ICD-11 (Internal Classification of diseases available at https://icd.who.int/en . The user must be able to find the right disease and select it. We need to also have an "Others" option here for when the user is not sure about the ICD category. The other option must allow the user the type and enter any text.
