### ISSUE TITLE
Pain Scale for Basic editor

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2019]
Add a pain scale in the "Others" editor of the critical care module.

Pain Scale from 0 to 10
0 (No Pain)
1-3 (Minute
4-7 (Moderate)
8-10 Severe

**Comment by sam9111** [comment]
@gigincg is the "pain" attribute added to the backend? I cant seem to find it in the API docs

**Comment by sam9111** [comment]
Front-end is done for this....need a field to be added to the backend in daily_rounds

**Comment by shaileshaanand** [comment]
@sam9111  Could you link to the PR/commit where it was added?

**Comment by sam9111** [comment]
> @sam9111 Could you link to the PR/commit where it was added?

I haven't created a PR for it yet. 

<img width="1512" alt="Screenshot 2022-01-17 at 5 56 57 PM" src="https://user-images.githubusercontent.com/60708693/149769343-6959c040-11ac-43f6-9e34-e9dae8ef4cbe.png">
