### ISSUE TITLE
HBA1C parameter

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2020]
HBA1C is a parameter of the patient that can be used as a reference to compare their current blood sugar values. Its their average blood sugar in the last 3 months. It would be a good parameter to compare the blood sugar graph with.

**Comment by sam9111** [comment]
to be entered while creating a consultation

**Comment by sam9111** [comment]
Front-end is done...need HBA1C parameter to be added to the backend to the consultation model.

**Comment by sam9111** [comment]
Need to remove HBA1C parameter from consultation model and add it to the investigation model in the backend.

**Comment by aparnacoronasafe** [comment]
HBA1C must be added to the seeded data in investigations. 
details in row 134 of https://docs.google.com/spreadsheets/d/1hN13p-BDbb1Pkl3a8tcVdWFsFxncju2QPfeOEkKh51E/edit?usp=sharing

**Comment by nihal467** [comment]
it is resolved
