### ISSUE TITLE
Update log is Lengthy

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2024]
https://user-images.githubusercontent.com/57055998/148782752-e5e30ec9-2c4d-4b18-8605-566204178681.mp4

we need to scroll down a lot to see the button for going to the next page

**Comment by khavinshankar** [comment]
@nihal467 currently 14 updates are shown on one page, is it ok if we reduced the number to 8? what's your opinion on it?

**Comment by khavinshankar** [comment]
@nihal467  
or we can also have something like this,
![image](https://user-images.githubusercontent.com/29787772/148874460-f0c5cccd-8de4-4ff1-8a31-0fd616b6a779.png)

**Comment by nihal467** [comment]
@khavinshankar this screenshot looks fine for me, take a opinion from @gigincg as well
