### ISSUE TITLE
Add Booster dose option 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#2037]
add "Booster Dose" / "Precautionary Dose" option in vaccination dose's field
right now there is only 2 option as 1st and 2nd dose.

**Comment by sam9111** [comment]
@samholics will the booster dose be considered as the third dose?

**Comment by samholics** [comment]
@sam9111 yeah we can go with the 3rd dose for now

**Comment by sam9111** [comment]
<img width="1512" alt="Screenshot 2022-01-25 at 11 19 58 PM" src="https://user-images.githubusercontent.com/60708693/151032017-b454e801-ab5f-458b-8ae5-dd602ad6bc43.png">

**Comment by khushbooag4** [comment]
@sam9111 @samholics Can I work on this??

**Comment by sam9111** [comment]
> @sam9111 @samholics Can I work on this??
yes!
