### ISSUE TITLE
suggestion for Non_covid or  Covid Patient card

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#2038]
-1 How to differentiate non_covid and covid patients 
-2  what are the changes to be made in the patient creation form
-3 what are the changes to be shown in patient card (patient dashboard)

-1) How to differentiate non_covid and covid patients

When a patient is admitted in an icu, medical staffs need to easily identify the patient is whether covid or non_covid without opening each patient cards,,, so for that;
*  change existing Positve/negative status flag to Covid Positive/Covid Negative  in the Patient list.
* Change the flag's  position  near  to the Name in the place  of "review missed" alarm notification...(change the review missed notification to the right side and constant...)
 for eg:) 

![image](https://user-images.githubusercontent.com/75214902/150744552-b9033671-5a6c-4909-a26d-ccea1b8efd81.png)

-2)   what are the changes to be made in the patient creation form
 
When creating a patient card,
* change the "covid disease" status as first option in the health details instead of "Covid test type"
* also change "Covid Disease Status " to "Disease Status" 
* change to Covid Positive/Covid negative/Covid Suspected in the status dropdown
* Add Non_covid or any other relevant option in the "covid disease status" dropdown
* when selecting the Non_covid from the disease status, there is no need to avail covid related questions
* only avail * Covid disease status, * Vaccination field, * Blood group as default fields 
* only allow  the options such as test type,date,declared,contact details etc  when selecting covid disease status Positive or Negative or suspected.

for eg:)

when selecting Non-covid or Default 
![image](https://user-images.githubusercontent.com/75214902/150748484-7bf1d11f-e901-4f21-a13b-23f5f5089406.png)

when selecting Positive for Covid
![image](https://user-images.githubusercontent.com/75214902/150749893-de65f93c-705f-417f-920b-bd396b772468.png)

-3)  what are the changes to be shown in patient card (patient dashboard)

Change "Covid Disease status" to "Disease Status" 
also show the patient status as "Non_Covid or Covid Positive or Covid Negative or Covid Suspected" 
(as per changes added in the Health details fields)

**Comment by aparnacoronasafe** [comment]
@samholics @khavinshankar Please block this issue. To add COVID and other disease categorizations, some planning needs to be done with Gigin's lead.

**Comment by nihal467** [comment]
@aparnacoronasafe is this issue still relevant

**Comment by bodhish** [comment]
Closing this as it no longer required; 
CC @aparnacoronasafe
