### ISSUE TITLE
Alignment Issue : Consultation Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2044]
![set 1](https://user-images.githubusercontent.com/57055998/151157600-440d7c2d-1479-4df8-95c7-7bc6a7359f9a.jpg)

https://care.coronasafe.in/facility/7a560e62-6aae-4293-8f1a-0ba840e3449f/patient/192fdee9-397f-49bd-833a-10f700416da8/consultation/d794ba54-da42-4238-8ba9-0b628ca60069

- 2 years ago and the date is overlapping
- spacing under the log update button

**Comment by aparnacoronasafe** [comment]
redundant
