### ISSUE TITLE
Patient Consultation Form UI Change

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2046]
![pdewkodkew](https://user-images.githubusercontent.com/57055998/151175713-ac2c4a38-0aaa-44e3-87cd-ddd464e2fae1.jpg)

- the UI is center aligned and waste a lot of white space on both sides
- the form is really lengthy

**Comment by shivankacker** [comment]
Issue resolved in [https://github.com/coronasafe/care_fe/pull/2315](https://github.com/coronasafe/care_fe/pull/2315)
Whitespace can be removed but from design and responsiveness perspective I think it is better as is.
