### ISSUE TITLE
Nil History in Pressure Sore : Consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2049]
![ajoepfjae](https://user-images.githubusercontent.com/57055998/151189038-edfa6fdb-3194-4178-ad5f-31d88eb1581f.jpg)

we are having a lot of pressure sore history in the drop list, and most of them are nil. So, it is hard to tell, which log have pressure sore data or not

**Comment by khavinshankar** [comment]
@nihal467 so can we filter the nil pressure sore in the dropdown list?

**Comment by nihal467** [comment]
@khavinshankar take a suggestion from @gigincg
