### ISSUE TITLE
Enabling Doctor-Doctor Communication (TeleICU) | Integrate with Livekit

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2051]
Identify an existing (ideally opensource) tool to connect doctors at Spoke to Doctor at Hub to enable the TeleCommunication.

The tool should allow the computer at hub/spoke to connect with the computer at the spoke with the following features.
- Audio
- Chat
- Video (Advanced)
- Screen sharing (Advanced) 
- The interface connecting doctors must allow the doctors to browse through the patient records while in a call.

A few relevant points to note are:
1) The assumption is the computer at hubs and spokes will not change
2) Utilising an existing technology like Gmeet/Discord will save effort. However, the integration with the communication tech must be seamless, at the click of one button.
3) One hub will be connected to as many as 20-40 spokes. In the initial phase, the number of spokes will be limited to 10 for each hub. For the pilot, 1 computer per spoke is installed at the hub.
4) The feature should work in low bandwidth setting as well will at least minimum audio and chat features.
5) The feature must not increase the server cost too much.
6) Small cost of 10-20K per year to subscript to any third party tooling/service may be considered if it is necessary. However, a free solution would be preferred.

Hoping the whole team gets together to brainstorm on this one. 
@gigincg

**Comment by sam9111** [comment]
Here are some solutions I thought were pretty cool: 
https://www.100ms.live/ --> @Deep-Codes works here!
https://jitsi.org/ -> Open-Source and Free
https://www.twilio.com/video-api

**Comment by Deep-Codes** [comment]
> Here are some solutions I thought were pretty cool: https://www.100ms.live/ --> @Deep-Codes works here! https://jitsi.org/ -> Open-Source and Free https://www.twilio.com/video-api

Would be happy to help out and aid in integration!

100ms fits perfectly into the feature list, it can be integrated in under a week.

**Comment by sam9111** [comment]
Would love to take this issue up once everything is fixed! @gigincg @aparnacoronasafe

**Comment by gigincg** [comment]
@Deep-Codes is there an open-source or non-profit plan for 100ms ?

**Comment by Deep-Codes** [comment]
> @Deep-Codes is there an open-source or non-profit plan for 100ms ?

We have something that fits into this, let me get back to you on slack.

**Comment by gigincg** [comment]
We can consider doing this using https://livekit.io/

**Comment by khavinshankar** [comment]
Feature added in https://github.com/ohcnetwork/care_fe/pull/8660

cc: @gigincg
