### ISSUE TITLE
Asset UI is Bulky

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2064]
![erkfrop](https://user-images.githubusercontent.com/57055998/152693638-0b3e7d16-2db7-4083-807c-c75076999ee9.jpg)

- there are lots of project in this page and it seem bulky
- having the badges in between the data are not looking good, relocate it

**Comment by arpancodes** [comment]
Hey @nihal467, could you specify which all properties should be shown on this page? I will remove the rest

**Comment by nihal467** [comment]
@arpancodes every data in this have to be displayed, nothing to be removed, can you rearrange the existing  data and make a better UI
