### ISSUE TITLE
Shifting & Resource Dashboard : Assigned to Function Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2067]
![ejpfwepofwe](https://user-images.githubusercontent.com/57055998/152766803-b63eaa64-d254-4e9c-9c16-d39fdcdc0709.jpg)

Assigned to function in shifting & Resource dashboard is showing all the users in the care, so change the user list to people linked to the particular shifting facility

**Comment by sam9111** [comment]
Should it filter according to shift approving facility or facility the patient being assigned to? @nihal467

**Comment by nihal467** [comment]
@sam9111 people in the shifting approving facility list only should be coming in it
