### ISSUE TITLE
PDF Preview not Working : Sample Test 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2070]
Step 1: Create a Sample Test
step 2: Sample test is marked result as positive and mark it as completed
step 3: Again take the sample card
step 4: Scroll down to the bottom

![oiejwfi](https://user-images.githubusercontent.com/57055998/152779197-5fffabf8-8285-4ced-b5fc-c0e841db9cc6.jpg)

step 5: 
[2019 Dec. CS401-C - ktu qbank.pdf](https://github.com/coronasafe/care_fe/files/8014763/2019.Dec.CS401-C.-.ktu.qbank.pdf)

upload the file with the sample file name

step 6: check the uploaded file preview, it is not working

tested patient file: https://care.coronasafe.in/sample/37be931a-6bc4-4cd2-af00-31f4b9a69e24

**Comment by sam9111** [comment]
@nihal467 could u recheck this?
<img width="1512" alt="Screenshot 2022-02-14 at 8 22 08 PM" src="https://user-images.githubusercontent.com/60708693/153886966-aa19da72-7b1c-43a6-8c3c-f7839200f7aa.png">

**Comment by nihal467** [comment]
@sam9111 

![eofjeif](https://user-images.githubusercontent.com/57055998/154252759-8a9ac221-adda-4eb7-8f3a-e37887c4bb0c.jpg)

**Comment by aparnacoronasafe** [comment]
working fine now. closing issue
