### ISSUE TITLE
Swap bulky packages with a better alternative

### ISSUE THREAD

**Issue by arpancodes** [coronasafe/care_fe#2079]
We are using a lot of bulky packages one of which is `moment`
![image](https://user-images.githubusercontent.com/42417893/153039130-ba62a8e3-41db-47a1-b5ac-cc6f7a7c7f55.png)

Alternative can be used as: https://day.js.org/

(more packages to be scanned and added)

**Comment by aparnacoronasafe** [comment]
@arpancodes let's clear out all stale issues. Close it/work on it/ unassign so that someone else works on it

**Comment by nihal467** [comment]
@khavinshankar can you check this issue !

**Comment by khavinshankar** [comment]
new more detailed issues will be created
