### ISSUE TITLE
Tele ICU Issues

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2086]
Need to address right now

- once we discharge a patient, we shouldn't be able to see the patients feed
- feed is blinking after a bit
- Once we turn off the camera using the stop button, we have no button to turn it on again

Suggestion to add an extra feature

- Remove the breadcrumbs under the live feed heading
- Preset buttons are working but the Selected button can't be identified, make the selected button darker is colour
- Screenshot facility
- Recording feature of the live feed and access the previous files

**Comment by aparnacoronasafe** [comment]
- Patients feed is disabled for discharged patients.
- blinking is resolved
- https://github.com/coronasafe/care_fe/issues/2753
- Breadcrumbs removed
- must NOT encourage users to take screenshots. to promote more privacy-sensitive behavior
- same
