### ISSUE TITLE
Clarification on oxygen table: Facility page

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2096]
<img width="691" alt="Screenshot 2022-02-14 at 12 03 14 AM" src="https://user-images.githubusercontent.com/67050716/153769425-eba2b7b1-5695-44ad-b9e7-2f1621b05075.png">
https://care.coronasafe.in/facility/6e401539-e27f-4aff-a626-c9d42427ffd7

Add a header above the table stating "Information on Oxygen"

Also, in the table change "Expected" to "Daily Expected Consumption"

@gigincg

**Comment by nihal467** [comment]
@sam9111 @aparnacoronasafe @developedBySJ  we are having a PR already on it: #2078
