### ISSUE TITLE
Have a brand color

### ISSUE THREAD

**Issue by yohix** [coronasafe/care_fe#210]
**Is your feature request related to a problem? Please describe.**

It would be great if the platform has a brand color!

Currently, the site is using default color for all Input boxes and buttons

![Screenshot](https://user-images.githubusercontent.com/61746440/78502517-24318b00-777f-11ea-8a1e-9100bde83cbf.png)

It would be cool if the button is applied with some brand color!

**Comment by bodhish** [comment]
@yohix it would be great if you can work on fixing the styling.
The UI/UX is just minimal as we are shipping out more and more features everyday. 

We are currenlty switching to [Tailwind CSS](https://tailwindcss.com), If you have time do refactor and fix the styling with tailwind :smile:

**Comment by yohix** [comment]
@bodhish Yes, of course, I will do PR tomorrow on this Issue

**Comment by yohix** [comment]
It seems like `#B21E35` this is our primary brand color!

**Comment by SandeepThomas** [comment]
@yohix we are using tailwind css as well. can you make both material and tailwind use similar color theme?

**Comment by yohix** [comment]
@SandeepThomas It seems like the site is using tailwind using CDN (https://github.com/coronasafe/care_fe/blob/master/src/index.html#L27), we cannot use the same configuration for it.

But we can configure it in `index.scss` file.

**Comment by SandeepThomas** [comment]
@yohix can you configure that as well so we dont have two different themes within the app?

**Comment by yohix** [comment]
@SandeepThomas I couldn't find where tailwind is used! Can you show me some example files in this repo, so I can work on it!

**Comment by yohix** [comment]
@SandeepThomas I found it! But it seems like very minimal usage!
