### ISSUE TITLE
TeleICU Patients Page

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2106]
Create a Page that represents the TeleICU Live Patients of a Spoke Hospital(Facility)

The page would be at /teleicu/facilities/{facility_id}/

Here the Patient Image should be ignored, instead the bed number can be kept on the right side of the card.

Here's a reference Image:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/13028584/154435278-28ef7e42-aca6-45d0-a2bb-ae4209777227.png">

**Comment by bodhish** [comment]
This screen should be redesigned without an image for the patient
