### ISSUE TITLE
TeleICU Hub Patient Page

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2108]
There needs to be a separate page for a hub to monitor a certain Patient

Here's a reference wireframe:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/13028584/154487160-373706c1-ff72-4b0f-ae9e-6e3bc620819a.png">

The Diagnosis can be a separate Card on the right hand side and the Medical History can be cloned from the existing Medical History Component in the Patient Registration Page

**Comment by shrihari689** [comment]
### ⌛ Progress 🎨
🧰 UI Prototype: https://play.tailwindcss.com/Ivw59SNfQ4?layout=preview
