### ISSUE TITLE
Facility Images

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2131]
Add a field for adding a Facility Image. There are existing helpers for Uploading Images. 

> Backend changes required

**Comment by rithviknishad** [comment]
@mathew-alex can the environment variable be set as required by https://github.com/coronasafe/care/pull/1056

**Comment by mathew-alex** [comment]
> @mathew-alex can the environment variable be set as required by [coronasafe/care#1056](https://github.com/coronasafe/care/pull/1056)

@rithviknishad - env variable added in staging. can you check if the image URL in the API response is as required?

**Comment by rithviknishad** [comment]
@mathew-alex The API response is now as expected, yay!! :) 

it just started working as soon as I ran `yarn start` on the feature branch 😅 
![image](https://user-images.githubusercontent.com/25143503/195033885-549d7967-9a69-410a-a9e1-c8c3814d2b3b.png)
