### ISSUE TITLE
Assigned Doctor WhatsApp Video Call Button Crashes

### ISSUE THREAD

**Issue by shrihari689** [coronasafe/care_fe#2137]
## 📢 Description

Assigned Doctor WhatsApp Video Call Button in the Patient Page crashes because of API Status 403
**Associated File:** https://github.com/coronasafe/care_fe/blob/03dec879d0a73323b0c37303abc8ee603dc914c2/src/Components/Patient/AssignedDoctor.tsx#L5 

## 🔭 To Reproduce

- Sign in as `devdistrictadmin`
- Go to a patient. (Eg:  http://localhost:4000/facility/79da39d7-8533-4dbc-8db6-6e401b223f8e/patient/df274051-e0ba-47e9-ad10-a3e0d1c31866)
- You can see API call fails because of Authorization.

## 🤔 Expected Behavior

To get the details of Doctor by looking up using `username`

## 🎨 Screenshots

![image](https://user-images.githubusercontent.com/57325503/155837517-2a6210d4-2b5d-489e-9c26-149dd58943e4.png)

![image](https://user-images.githubusercontent.com/57325503/155837550-2e199dbe-b978-482b-b040-07621348a0a7.png)

**Comment by aparnacoronasafe** [comment]
@gigincg is this good to close?
