### ISSUE TITLE
Modify Oxygen Table : Facility Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2140]
![wi3jr3](https://user-images.githubusercontent.com/57055998/155889707-ba4c13d9-b184-48f3-92c4-90e0a12927e0.jpg)

- Make 'Daily Expected Consumption' from two-line to one line
- Make Liquid, B, C, D as center-aligned from right-aligned

**Comment by developedBySJ** [comment]
Pull Request #2156
