### ISSUE TITLE
Reimagining bedtypes

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2151]
Currently, the list of bedtypes in CARE is very confusing for the users. 

A few of their issues are:
- Ventilator is never a bed type. It is only an add on the device used on patients occupying ICU Beds. So ICU beds with ventilators will keep changing as per the usage of the ventilator as a device.
- COVID /Non-COVID categorisation may keep changing. this is not essentially a bedtype.
- KASP is only relevant in Kerala. This again is a tag given to a patient and not to a bed.

**Suggested solution**
1) **Bed types** need to be only
Ordinery/Oxygen/ICU

2) **Devices:  ** There are various device that may be linked to the patient and hence the bed, Like ventilator, BiPAP etc. These should be an add-on to the bed.

3) **Other tags**: Beds may be reserved for COVID patients (if the bed is in COVID ward), for underprivileged patients (in case of KASP) and also for Gynac patients (if the bed is in the labour room etc. The tag may also include "Isolation" for certain kind of disease management like Nipah.

These 3 functions need to be separately identified. 

@gigincg @bodhish @vigneshhari

**Comment by gigincg** [comment]
Action Plan
 - Remove Admitted To
 - Remove KASP (Soft Hide)
 - Add ConsultationBed Through Table
 - Modify ConsultationAPI to make ConsultationBed Record
 - Remove DailyRound -> Bed Relation


Post Release
 - BedFlag ThroughTable
 - ConsultationBed-Asset ThroughTable

**Comment by aparnacoronasafe** [comment]
Only building flags for beds remains

**Comment by gigincg** [comment]
Remaining Issues moved to separate thread
