### ISSUE TITLE
Add Asset Type Multipara Monitor

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2159]
Add Asset Type Multipara Monitor

Optimize Multipara Monitor to load data form middleware/getObservation?device_ip on the TeleICU patient page

**Comment by aparnacoronasafe** [comment]
Asset type covered in #2212

**Comment by iamsdas** [comment]
seems like a duplicate of #657

**Comment by rithviknishad** [comment]
*correction: coronasafe/care#657

**Comment by nihal467** [comment]
issue is resolved
