### ISSUE TITLE
Patrol Mode for Cameras

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2160]

**Comment by rithviknishad** [comment]
@gigincg I'm thinking of taking this up.

Two approaches can be there.

### 1. Client Side
Where each preset is traversed and selected at an interval controlled by the client side.
However in this method the middleware will not be aware whether a client is using patrol mode or not, and hence other clients who might access the same camera will also not be aware of this. Set preset requests may conflict the order if more than one client accesses it.

### 2. Server side
An endpoint for the camera can be exposed to enable patrol mode, and also status response can include whether the resource is in patrol mode or not. Hence every client will be aware whether it's in patrol mode or not. Presets are traversed and selected by the middleware/backend, hence order is maintained regardless of multiple clients accessing the resource. Preset traverse interval can be optionally adjusted by client.

**Comment by bodhish** [comment]
Not sure if we have an application for this anymore.
