### ISSUE TITLE
Improve Asset Management

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2166]
Improve Asset Management. Switch to more dropdowns using Products (Django admin managed Model)

- Create a new Model in coronasafe/care for Managing Products
- Assets would have a nullable relation to Products
- UI: Assets with Product Relation, would use the Product.* as the placeholder in forms, and use `Product.* ?? Asset.*` in Asset List Page & Asset View Page

- Building UI for the Products is a low priority 

@aparnacoronasafe Can you list the fields that we need prefilled? Listing a list of my own to get started
- Asset Name
- Asset Description
- Customer Support Phone Number
- Customer Support Email
- Vendor Name
- Manufacturer

**Comment by nihal467** [comment]
anyone taking up the issue, discuss about the approach in EOD call, upon confirmation only start working on it

**Comment by gigincg** [comment]
Needs to be covered under Assets/Inventory in HMIS
