### ISSUE TITLE
Medical Imaging

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2167]
Support for viewing DICOM imaging using OHIF Viewer https://github.com/OHIF/Viewers The React Viewer UI can be found at https://github.com/OHIF/Viewers/tree/master/platform/ui

Need to look into getting sample DICOM files to test. This should be a part of the Patient Files/File Upload

**Comment by nihal467** [comment]
@developedBySJ unassigning you from the issue due to inactivity more than a year now

**Comment by gigincg** [comment]
Part of the larger Radiology Requirements
