### ISSUE TITLE
All the Icons in the side bar : Invisible

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2173]
https://user-images.githubusercontent.com/57055998/158384380-4b8b52c4-3c4b-4eff-9d59-9795862c38c5.mp4

When we are login into care, and check all the sidebar icons, everything is invisible, and once we hard-fresh the page (Ctrl+F5), the icon will be visible and again we refresh the page ( Ctrl +R), all the icons become invisible

**Comment by gigincg** [comment]
CSP Issue, Removed CSP For now
