### ISSUE TITLE
Add empty state for Tele-ICU page

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care_fe#2174]
**Describe the bug**
Handle the empty state for `tele-icu` page. Also, ensure that the title for the page would make sense for other users who don't have a connected digital ICU infra. 

![image](https://user-images.githubusercontent.com/14979190/158451578-be358636-c47b-4750-b81f-5bf3c17d5433.png)

**Comment by aparnacoronasafe** [comment]
Redundant issue
