### ISSUE TITLE
Overlapping Issue : Consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2195]
![Screenshot 2022-03-31 164137](https://user-images.githubusercontent.com/57055998/161042482-289b709a-346e-4bbb-9f78-58cea49b5a4d.png)

- the 2 days and the date is been overlapping
- the spacing of the box is also irregular, lot of space wasted in the bottom of the box

**Comment by arpancodes** [comment]
Closing this.
cc @gigincg

**Comment by nihal467** [comment]
the issue is not relevant anymore
