### ISSUE TITLE
File Upload Error : Consultation Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2196]
When i upload a file in the consultation page, to see the uploaded file, i need to manually refresh the page to see it

https://www.loom.com/share/5ff7c88ffd624e0ab109abf22437aff5

**Comment by arpancodes** [comment]
@tomahawk-pilot csp issue 
<img width="712" alt="image" src="https://user-images.githubusercontent.com/42417893/161246544-7baf87e6-ae56-4ba5-b890-648635cba1e1.png">

**Comment by aeswibon** [comment]
Fixed with issue #2297
