### ISSUE TITLE
Marking is missing in graph : Consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2199]
![opewfke](https://user-images.githubusercontent.com/57055998/161048005-6a7de45d-1255-4087-bd9d-b9773c05011c.png)

the graphs are showing the data is lines, but the button's are not showing any indication it is selected, as we are having two button to swap the graph to lines and bars

**Comment by aparnacoronasafe** [comment]
Already fixed. tested in staging
