### ISSUE TITLE
Bed Revision V1

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2208]
Solves #2151 

Action Plan
 - Remove Admitted To from Consultation form
 - Add ConsultationBed Through Table
 - Modify ConsultationAPI to make ConsultationBed Record
 - Remove DailyRound -> Bed Relation
 - Add Button to "Switch Beds" in Consultation page 
 https://care.coronasafe.in/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095/patient/e45b93eb-4b1a-4f91-9b6f-3533b719e9a6/consultation/008e06f1-20fa-44a1-b665-bb1d9b21d04e.

**Comment by gigincg** [comment]
@arpancodes Breaking this down:

- [x] Remove: 
   - AdmittedTo in Consultation
   - AdmittedTo in DailyRound
   - Bed in DailyRound

- [x] Add Beds in Consultation
   - Add the Bed Relation (ConsultationBed Through Table)
   - Modify ConsultationAPI to make ConsultationBed Record
   - UI Changes for the same

- [x] Switch Beds UI/API
   - API to Switch Beds of a Consultation 
   - UI Changes for Switch Bed

**Comment by gigincg** [comment]
Closed with https://github.com/coronasafe/care_fe/pull/2273
