### ISSUE TITLE
Bed Revision V2

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2209]
- [x] https://github.com/coronasafe/care_fe/issues/6086
- [x] #8235

KASP is removed from Bed Type. The requirement going ahead is to build "Flags" for beds. These flags could be to reserve the beds for only a certain category of patients. (eg: Patients covered under PMJAY, female patients etc)

**Comment by gigincg** [comment]
@sainak Can you verify if all of these pieces are already built as part of different issues?

**Comment by sainak** [comment]
> @sainak Can you verify if all of these pieces are already built as part of different issues?

The consultationBed-Asset table is built,
the Bed flag is remaining https://github.com/coronasafe/care_fe/issues/8235

**Comment by gigincg** [comment]
Closing Issue, as #8235 is well set up.
