### ISSUE TITLE
Modify COVID Category

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2210]
Modify COVID Category to Patient Category
- Comfort Care (White color)
- Stable (Blue color)
- Slightly Abnormal (yellow color)
- Critical Case (Red color)

The category is to be a mandatory field. 

Once categorized the patient card must have the respective color. Including when viewing as list.

**Comment by rithviknishad** [comment]
@aparnacoronasafe Did you mean these to be mapped with the respective colors?
![image](https://user-images.githubusercontent.com/25143503/174941496-7fe99d78-6c77-474c-abc0-2e37f72608fd.png)

**Comment by aparnacoronasafe** [comment]
Yes. But we need to change the drop-down with the above 5 options. 

@gigincg please confirm that we are reusing the COVID category for this categorisation

**Comment by rithviknishad** [comment]
@nihal467 can the patient category colors be tested
