### ISSUE TITLE
Asset Registration V.2.0

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2212]
The asset module needs to be revamped as per the UI Diagram below:
[Asset Registration FlowV4.pdf](https://github.com/coronasafe/care_fe/files/8937948/Asset.Registration.FlowV4.pdf)

The data validations for the fields are mentioned here: https://docs.google.com/spreadsheets/d/14mZrU2LhRRBrRhI3MLaUtDkc9ux0CbXrl2C3W_SidI8/edit?usp=sharing

**Comment by gigincg** [comment]
- [x] Link QR Code while creating Asset
- [ ] Create Devices Table/Asset Relation

**Comment by aparnacoronasafe** [comment]
In the revised asset registration page, also add a field below warranty date for "AMC valid till" - input field (date- DD/MM/YYYY), added to the UI wireframe

**Comment by aparnacoronasafe** [comment]
@developedBySJ I have made some changes to simplify the module. In the earlier design we were registering if the asset was a 10bedicu asset and if yet, there were a lot of fields to be auto-filled. I have taken out all that and simplified the design a bit. 

Now, we need to only record if the asset is an external/internal asset like we have now and then record all the fields as in the design. Please feel free to get in touch if there is any confusion.

**Comment by aparnacoronasafe** [comment]
I am revising this requirement and breaking down the same to smaller issues

**Comment by nihal467** [comment]
@gigincg the training module, uploading related files to the asset detail page will be a good add-on

**Comment by bodhish** [comment]
Can we update the issue with what needs to be done here? @nihal467

**Comment by gigincg** [comment]
Not Applicable anymore. The Core Issue here was to enable the QR Workflow for Asset Trackign which has been completed. No depth available to continue working on it
