### ISSUE TITLE
Move Health Details to Consulation Form

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2234]
As a new collapsable section to the consultation form on top. This section will contain all the health details of the Patient.

Changes to be made:

- [ ] The first field is "Allergy"- YES/NO. If YES, a short text box for details. (the text field already exists in the patient registration form. the same may be migrated)
- [ ] The second field will be "Vaccinations". The user must be able to select multiple inputs from the options. The Options would be: COVID (1 dose, 2 doses), Hep B, Hep A. (The field for COVID Vaccinationa already exists in patient registration form)
- [ ] "Blood Group" With dropdown. (The field already exists in the patient registration form and may be migrated here)
- [ ] The field for "Weight" and "Height" existing at the bottom of the consultation form may be moved up to the top after the blood group.
- [ ] Add a Long Text Field for "Family Details"

**Comment by aparnacoronasafe** [comment]
already covered in #2218
