### ISSUE TITLE
link the generated QR and assigned QR on assets page

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#2241]
Currently there are two seperate QR codes on an asset 
1. the uuid qr code that is generated automatically
2. the numeric qr_code_id that has been added to the backend https://github.com/coronasafe/care/pull/720
this need to be fixed

**Comment by nihal467** [comment]
@vigneshhari is this issue still relevant and what we should do further

**Comment by Ashesh3** [comment]
The UUID QR code that is generated automatically has been removed. The issue can be closed.
