### ISSUE TITLE
CARE: Prep for Manipur launch

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2246]
The following changes needs to be made before Manipur launch.

_**Priority 1**_

- [x] Get the Icons for capacity, camera, internet and user online to work <img width="471" alt="Screenshot 2022-04-24 at 1 05 57 PM" src="https://user-images.githubusercontent.com/60708693/164965554-74c89637-fe60-4900-81f2-dca1fc46eeec.png">

- [x] Remove graph image for vitals
Add diagnosis below basic patient info
Doctor's Note button to be linked to https://care.plexusindia.in/facility/fd9f27dd-7e38-499d-9992-1270701633f0/patient/3323dbf3-6853-401d-b725-88a2c422a2a3/notes/ for the time being. 
Disable 5 para monitor button 
<img width="448" alt="Screenshot 2022-04-24 at 1 08 14 PM" src="https://user-images.githubusercontent.com/60708693/164965644-dff396f4-c5ff-461e-a73b-5b417b3f20a8.png">

- [x] Asset Management: Add option to link a QR Code to the asset while registering <img width="367" alt="Screenshot 2022-04-24 at 1 09 22 PM" src="https://user-images.githubusercontent.com/60708693/164965684-25354d26-2a19-4834-b5c8-fb52d8032ab2.png">

- [x] [Patient Registration Form](https://care.plexusindia.in/facility/fd9f27dd-7e38-499d-9992-1270701633f0/patient/3b786d92-2432-42a6-a2fb-ea673bf23899/update)
Remove Fields for Frontline worker, Medical worker, Guest worker
Health details: remove all fields except blood group
Remove field for No. of aged dependents, No. of chronically ill dependents

- [x] Consultation page:
Remove the following:
Category
State test ID
KASP
Operation

- [x] [Consultation update (basic editor)](https://care.plexusindia.in/facility/fd9f27dd-7e38-499d-9992-1270701633f0/patient/3b786d92-2432-42a6-a2fb-ea673bf23899/consultation/2911a3bd-9864-4d64-9724-02fcb928808c/daily-rounds/0fbfb0d9-56c4-4b1c-b5c1-31e1837418d7/update)
Remove the following Category, Current Health

- [x] [Patient Page](https://care.plexusindia.in/facility/fd9f27dd-7e38-499d-9992-1270701633f0/patient/3323dbf3-6853-401d-b725-88a2c422a2a3)
Remove COVID Status
Remove “Tracing” and “testing” sections

_**Priority 3**_

- [x] When the Weight and Height are not entered, the fields should come filled with “-” rather than 0. <img width="490" alt="Screenshot 2022-04-24 at 1 06 08 PM" src="https://user-images.githubusercontent.com/60708693/164965561-d6458dab-4666-4cb8-89be-11c366bece96.png">

---

**CARE: Issues (staging)**

- [x] A staff logged in is unable to create user type of “Doctor” <img width="506" alt="Screenshot 2022-04-24 at 1 13 19 PM" src="https://user-images.githubusercontent.com/60708693/164965829-05a14613-b38a-4688-a532-8794034bfcb4.png">

- [x] Remove “is the facility KASP empanelled” from ​​https://care.coronasafe.in/facility/create
  KASP is now a flippable feature, will be disabled for other deployments

- [x] https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/bed 
all the old bedtypes appear in add capacity details form

- [x] INVENTORY- https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/inventory
No minimum quantity is saved, still PPE with 20 items in stock shows as Low stock. <img width="608" alt="Screenshot 2022-04-24 at 1 16 11 PM" src="https://user-images.githubusercontent.com/60708693/164965939-ef898bf8-a606-4d91-842b-42eb27d14321.png">

- [x] From [Add Location form](https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/location/add) redirect straight to [Manage Beds form](https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/location/8bd8a011-917c-4391-9657-6cd800b2d5e1/beds/add)

- [x] Add bed form https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/location/8bd8a011-917c-4391-9657-6cd800b2d5e1/beds/add. Description to be a NON mandatory field

- [x] Asset registration form (https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/assets/new) needs option to link QR Code

- [x] Customer support phone number in asset registration form (https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/assets/new) to be NON mandatory

- [x] Patient registration form to be revised to remove covid specific details (point 5 in the above table)

- [x] Edit consultation to remove covid specific fields (point 6 in the above table)

- [x] The graph for FiO2 does not appear even after adding value in Log update. FIO2 input is also not getting saved in the log update.FIO2 is only getting saved when ventilator parameters is set at NONE and oxygen modality is set at HFNC

- [x] Download a summary of investigation reports, 

- [x] Consultation files (https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/patient/e09d92d0-42c6-402c-af5c-8ba6e23f18a4/consultation/3d475f4e-885f-4be3-bd24-849badab088a/files) once files are uploaded, no success notification comes. There is a delay in uploaded file showing up too. Same issue with audio recording.

- [x] Consultation files (https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/patient/e09d92d0-42c6-402c-af5c-8ba6e23f18a4/consultation/3d475f4e-885f-4be3-bd24-849badab088a/files) once files are uploaded,the preview function does not work. There is no option to download either.Same issue with audio recording.

- [x] In the form to enter IO Balance (https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/patient/e09d92d0-42c6-402c-af5c-8ba6e23f18a4/consultation/3d475f4e-885f-4be3-bd24-849badab088a/daily_rounds/31abb872-8df6-4f75-b2b7-82277b036cbd/update) - input for all input and output types can be entered. Data validation barring negative inputs to be added.

- [x] Insulin intake frequency is coming up wrong on the insulin graph (https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/patient/e09d92d0-42c6-402c-af5c-8ba6e23f18a4/consultation/3d475f4e-885f-4be3-bd24-849badab088a/summary)

- [x] Changes to TeleICU Page (https://care.coronasafe.in/teleicu/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/patient/e09d92d0-42c6-402c-af5c-8ba6e23f18a4) Docotr’s Note button to be linked to https://care.plexusindia.in/facility/fd9f27dd-7e38-499d-9992-1270701633f0/patient/3323dbf3-6853-401d-b725-88a2c422a2a3/notes/ and other points in point 3 in the above table.

- [x] Remove the discharge pop up window. <img width="573" alt="Screenshot 2022-04-24 at 1 20 24 PM" src="https://user-images.githubusercontent.com/60708693/164966066-e60d06d0-4173-4082-b830-d3afa17c35fb.png">

**Comment by aparnacoronasafe** [comment]
#2759 , #2760, #2761 , #2762, #2764, #2765
