### ISSUE TITLE
Landing Page Error : consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2249]
After creating a patient, the landing page of the consultation page is middle of the page

![epkofewpo](https://user-images.githubusercontent.com/57055998/164980778-1015da41-1ae6-4287-b57e-067fcf84993c.jpg)
![wepofw](https://user-images.githubusercontent.com/57055998/164981143-61ed8a74-e5c7-4dff-90f9-8129886b2b27.jpg)

**Comment by developedBySJ** [comment]
Fixed in #2371
