### ISSUE TITLE
Glasgow Coma Scale : Misalignment

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2255]
![peowkfowep](https://user-images.githubusercontent.com/57055998/164985098-48b766c0-7868-421b-b89a-f5d71bdc5a29.jpg)

![poefkoepwf](https://user-images.githubusercontent.com/57055998/164985191-f1e214ed-c2a8-4f2d-b802-22820ab8ac3c.jpg)

all the fields are not properly aligned to the data, for example, the time, time heading is below the time data

**Comment by shivankacker** [comment]
Looks like issue has been solved, closing.
