### ISSUE TITLE
Graph Showing Green : Arterial Blood Gas Analysis

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2257]
![error 1](https://user-images.githubusercontent.com/57055998/164986034-dafb0552-4054-4b93-b95d-5cca851365ff.jpg)

Even though I haven't touched base excess field, the graph is showing green

**Comment by aeswibon** [comment]
@nihal467 Can you provide the link where this issue is there?

**Comment by rithviknishad** [comment]
@cp-Coder [here](http://localhost:4000/facility/05980e8f-8860-4460-b863-fefdff1d187b/patient/e45b93eb-4b1a-4f91-9b6f-3533b719e9a6/consultation/008e06f1-20fa-44a1-b665-bb1d9b21d04e/daily_rounds/72e37048-f117-4c23-aed2-6c77558b09f1/update) inside ABG Analaysis.

**Comment by aeswibon** [comment]
Thanks @rithviknishad

**Comment by siddnikh** [comment]
Can you please tell how to recreate the issue?
