### ISSUE TITLE
Rhythm description is lengthy

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2258]
![wpfoewkfop](https://user-images.githubusercontent.com/57055998/164986874-19223f40-04ce-40ca-813a-6fa1b25cf73b.jpg)

the rhythm description is lengthy, can we change the UI to something else

**Comment by shivankacker** [comment]
Solved in https://github.com/coronasafe/care_fe/pull/2313
![image](https://user-images.githubusercontent.com/23238460/167841316-2e5a8754-a8b1-4151-81cd-fa576de41c22.png)
