### ISSUE TITLE
Others Section is Missing in Consultation

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2260]
![image](https://user-images.githubusercontent.com/57055998/202403260-ed3954de-0bfc-49d2-8f8a-5b00f38bd518.png)

![oeiwjde](https://user-images.githubusercontent.com/57055998/164987992-1ba5ead8-dbbf-4aae-a0dc-679ad636d893.jpg)

we are having two fields being captured in the others section 
1. Bilateral Air Flow
2. EtCO2

we are having no data about bilateral air flow is been shown in the summary and the EtCO2 data's are been shown in the ventilator parameters summary

**Comment by arpancodes** [comment]
@gigincg @nihal467 should these be moved to a new `Others` tab?

**Comment by siddnikh** [comment]
can you please tell how to reproduce this issue?

**Comment by aparnacoronasafe** [comment]
@nihal467 Please test again, if resolved close issue

**Comment by gigincg** [comment]
@aparnacoronasafe What's the right place to show Bilateral Air Flow?

**Comment by aparnacoronasafe** [comment]
Add these 2 fields as the first fields in "Respiratory support" section in Log Update

**Comment by nihal467** [comment]
Along with @aparnacoronasafe above comment, work on the pointers I mentioned too 

![image](https://user-images.githubusercontent.com/57055998/231486494-69a68abc-825e-4262-9ad4-196f631b7368.png)

- [ ]  Remove the entire other section from critical care

![image](https://user-images.githubusercontent.com/57055998/231486743-42823ebc-6663-4b32-822a-3d25693dc953.png)

- [ ] rename "Ventilator" to "Respiratory Support' on the patient consultation page
- [ ] Add a card to show Bilateral air entry field data in the respiratory support tab of the consultation 

note: EtCO2 is already present in the respiratory support tab, so don't need to add a card to reflect its data
