### ISSUE TITLE
Summary is not working : Normal Care

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2261]
![ewpofke](https://user-images.githubusercontent.com/57055998/164988463-30516a12-50c4-402e-845e-a222cce1ba70.jpg)

1. data's entered in all the fields in normal care are not been reflecting in the summary graph or anywhere
2. when we select copy previous data, all fields except systolic and diastolic are coming pre-filled

**Comment by arpancodes** [comment]
@nihal 
1. I am able to see the values of normal care in both the update tab and the summary graph.
