### ISSUE TITLE
Asset QR Code linking

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2279]
When a QR Code is linked to the asset accidentally, and the user wants to wipe the QR Code, the same is not possible. 

While trying to update asset details by clearing the QR code number and saving it, a "Something went wrong" error shows up.

**Comment by sainak** [comment]
fixed in https://github.com/coronasafe/care/commit/dcc419cd0d3090f80816b8d353d7296301dbf3d9
