### ISSUE TITLE
UI of patient page

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2283]
The UI of the patient page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce/dialysis), the top section with patients basic information, is not consistent when the user changes the Tabs (update, summery, medicine, investigation, ABG etc)

**Comment by Pranshu1902** [comment]
It seems to be consistent for me

**Comment by Ritesh-Aggarwal** [comment]
I also couldn't reproduce the issue

> It seems to be consistent for me

**Comment by rabilrbl** [comment]
@aparnacoronasafe Can you please post an image or video producing this error?

**Comment by arpancodes** [comment]
Closing this issue.
cc @aparnacoronasafe @gigincg

**Comment by aparnacoronasafe** [comment]
@arpancodes this is also resolved. Thank you
