### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2285]
In user list page (http://care.mn.gov.in/users) , on each user card, also show the user that has created that particular user

**Comment by Pranshu1902** [comment]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/70687348/167727237-4760501c-daa3-435b-9416-677a31f0ecc1.png">

How do I access who created the particular user, there is no such field?

**Comment by rabilrbl** [comment]
@Pranshu1902 Adding the feature to backend is required.

**Comment by Pragati1610** [comment]
Can I take up this issue?

**Comment by Pragati1610** [comment]
#2435 has been closed and the PR for it has the piece of code that is required for this issue.

So this issue can also be closed
