### ISSUE TITLE
Delete option for Consultation Files

### ISSUE THREAD

**Issue by mathew-alex** [coronasafe/care_fe#2288]
Add an option to soft delete files on the Consultation Files page

<img width="1680" alt="Screenshot 2022-04-29 at 3 28 03 PM" src="https://user-images.githubusercontent.com/22002072/165923767-df7104bb-85fc-4a08-bd37-f37a32da6825.png">

**Comment by patelaryan7751** [comment]
![image](https://user-images.githubusercontent.com/59426397/167759027-0933c584-9917-4c18-9ecc-7fb945056f48.png)

Hey @gigincg there is no api for files deletion shall i make a issue in the backend care repo ?

**Comment by Marmik2003** [comment]
I can work for backend to create this API... which users can delete the file? @mathew-alex @gigincg

**Comment by patelaryan7751** [comment]
yeah sure @Marmik2003 :) tell me when you are done.

**Comment by Marmik2003** [comment]
Added soft delete API endpoint PR: https://github.com/coronasafe/care/pull/740

**Comment by patelaryan7751** [comment]
@Marmik2003 is the delete API endpoint has been maid?

**Comment by Marmik2003** [comment]
@patelaryan7751 Yes, it is made but not working

**Comment by patelaryan7751** [comment]
This issue is no longer valid we would be having option to archive the file.
