### ISSUE TITLE
!!! Voice Recording option in consultation files is not working.

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#2296]
When recording voice instructions in consultation files, it's not saved in the Consultation files.
Only shows information that a voice recording is updated without any file including.

![image](https://user-images.githubusercontent.com/75214902/166664447-74bd30a1-aab8-4fd1-8f06-e802536ee6b1.png)

**Comment by aparnacoronasafe** [comment]
@gigincg @patelaryan7751 This is a priority.

Please report updates and the expected date of delivery on this. @samholics is engaged with users and needs to plan accordingly

**Comment by patelaryan7751** [comment]
@aparnacoronasafe This is a Content Security Policy issue . This issue might not be present in the production . I had a word with @gigincg regarding this. Further more as this was a priority i have fixed the unresponsive behaviour of the audio bar in this  [Pull Request](https://github.com/coronasafe/care_fe/pull/2346)

**Comment by patelaryan7751** [comment]
The issue has been resolved
