### ISSUE TITLE
Vitals: store data and plot on graphs

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2302]
The vital parameters coming from the 5-para monitor needs to be stored and plotted in the graphs in Summary Tab.

@gigincg

**Comment by gigincg** [comment]
care_be issue tracked at https://github.com/coronasafe/care/issues/671 closed by https://github.com/coronasafe/care/pull/811

middleware issue tracked at https://github.com/coronasafe/teleicu_middleware/issues/32

Parent Issue https://github.com/coronasafe/care/issues/694

**Comment by nihal467** [comment]
issue is resolved
