### ISSUE TITLE
Discharge and Discharge Summary 

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2316]
The "Discharge Summary" and "Discharge from CARE" buttons on the Patients details page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0) needs to move to the patient dashboard (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0)

The arrangements of the components may be altered to look like the below:
<img width="917" alt="Screenshot 2022-05-12 at 10 55 24 AM" src="https://user-images.githubusercontent.com/67050716/167997997-a8145812-8866-4b75-b5c8-3f32d238b23e.png">

**Comment by shivankacker** [comment]
Solved in [https://github.com/coronasafe/care_fe/pull/2322](https://github.com/coronasafe/care_fe/pull/2322)
