### ISSUE TITLE
Move "Other Symptoms" 

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2317]
Currently, on a patient dashboard (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0) 
The symptoms appear as a section below Vitals, while "other symptoms" appear above diagnosis. This may be confusing to the user.

Move "Other Symptoms" inside the Symptoms Section Below Vitals.

Ideal placement is as below:
<img width="307" alt="Screenshot 2022-05-12 at 11 02 38 AM" src="https://user-images.githubusercontent.com/67050716/167998791-bfb1cba9-9e13-4b28-a7bf-cf24366f48dd.png">

**Comment by shivankacker** [comment]
Solved in [https://github.com/coronasafe/care_fe/pull/2322](https://github.com/coronasafe/care_fe/pull/2322)
