### ISSUE TITLE
!!! Change title

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#2326]
Change the Title for the Consultation Page to "Patient Dashboard" instead of Patient Details.

https://care.coronasafe.in/facility/c22c97bb-167d-40a2-b9c6-68c75bb30900/patient/dde20dee-a577-4a89-9be8-4076054be289/consultation/4d61b654-952f-43b1-a652-e67147202c02

![image](https://user-images.githubusercontent.com/75214902/168097162-7083a79c-5ead-4caf-a0b4-864e8431b55e.png)

**Comment by aparnacoronasafe** [comment]
Cant see this change in CARE. @gigincg
