### ISSUE TITLE
Preview not available for sample report

### ISSUE THREAD

**Issue by Ritesh-Aggarwal** [coronasafe/care_fe#2348]
**Describe the bug**
Unhandled Rejection (TypeError) , when preview file is clicked on Sample page

**To Reproduce**

1. Go to https://care.coronasafe.in/sample/37be931a-6bc4-4cd2-af00-31f4b9a69e24
2. Scroll down to View sample report
3. Click on Preview File
4. See error (In development mode it shows type error, in deployment error is logged in console)

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/57039447/168418653-5f2bafb2-8e64-45ed-a7d7-e45ccf742229.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/57039447/168418669-2c9ffd99-f1eb-4d31-a435-864674a6d408.png">

**Comment by aeswibon** [comment]
Duplicate of issue #2297
