### ISSUE TITLE
Logging in does not indicate a loading symbol

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#2349]
If you are on a slow internet and login, you will not see any progress bar or loading symbol to indicate the request has been initiated.
It may appear to be "stuck" to users.

**Comment by ishanExtreme** [comment]
Issue already added and made PR
https://github.com/coronasafe/care_fe/issues/2338

**Comment by shivankacker** [comment]
> Issue already added and made PR #2338

Great, closing
