### ISSUE TITLE
Gravatar Implementation

### ISSUE THREAD

**Issue by yohix** [coronasafe/care_fe#236]
**Is your feature request related to a problem? Please describe.**

Currently, the user card looks weird!

![Screenshot](https://user-images.githubusercontent.com/61746440/78854717-ac45b800-7a3f-11ea-81e0-4fd68a943134.png)

**Describe the solution you'd like**

It would be great if the card consists of useful details like,

- Gravatar
- Full Name
- Username
- Email

**Comment by SandeepThomas** [comment]
Out of scope.
