### ISSUE TITLE
Overlapping buttons in mobile view

### ISSUE THREAD

**Issue by anuran-roy** [coronasafe/care_fe#2361]
**Description**
Buttons are overlapping in mobile view of care_fe in patients mobile view.

**Screenshots**
![Overlapping buttons illustration](https://user-images.githubusercontent.com/76481787/168470052-f72c9cf1-6e8a-443c-b28a-3d28d8aa0683.png)

**Comment by patelaryan7751** [comment]
@anuran-roy  i am currently working on this issue https://github.com/coronasafe/care_fe/issues/2347 :)
