### ISSUE TITLE
Mention password requirements to user in User Creation Form

### ISSUE THREAD

**Issue by anuran-roy** [coronasafe/care_fe#2365]
**Description:**
Password also needs a help text explaining the default validation, like: "minimum 1 uppercase, lowercase, numeric and non-alphanumeric character required", "minimum 8 characters required", etc.

**Comment by aeswibon** [comment]
![image](https://user-images.githubusercontent.com/77210185/168969325-65adb3cc-800d-46c5-865e-4536fd4f385f.png)
@anuran-roy  There is already a validation text to assist the user in creating a password.

**Comment by cp-Coder** [comment]
![image](https://user-images.githubusercontent.com/77210185/168969709-c0d6bf38-4443-47b8-9966-30559fe931a6.png)
Do you want something like this?
