### ISSUE TITLE
Facility Cover Image Upload Feature

### ISSUE THREAD

**Issue by Marmik2003** [coronasafe/care_fe#2366]
Currently the Facility Form has a URL field to store cover image URL, We need,
1. An Upload Facility Image Button 
2. After Uploading the name of image to /api/v1/facility/<facility_external_id>/cover_image/ API, signed_url will be returned back in case of successful response, then upload image to that URL with multipart.   

Ref: https://github.com/coronasafe/care/issues/737

**Comment by Ashesh3** [comment]
@khavinshankar Isn't this issue resolved since we now have Facility covers?

**Comment by khavinshankar** [comment]
@Ashesh3 @nihal467 this issue is resolved and can be closed
