### ISSUE TITLE
URL does not change when redirected to login

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#2376]
After session is expired, you are shown the login page but the URL is not updated to /login

**Comment by gigincg** [comment]
@skks1212 This behaviour preserves the page that the user is at when they log back in. If we solve this, we might have to preserve the previous page (Maybe in localstorage/sessionstorage) in order to redirect them back to the page.

**Comment by shivankacker** [comment]
> @skks1212 This behaviour preserves the page that the user is at when they log back in. If we solve this, we might have to preserve the previous page (Maybe in localstorage/sessionstorage) in order to redirect them back to the page.

I think the best preservation technique would be to have a ?ref query param in the url containing the url of the page to redirect to after logging in. I have seen many websites do this.

ex. https://care.coronasafe.in/login?ref=/patients
