### ISSUE TITLE
Update react-qr-reader; breaking changes

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#2378]
Current version has peer dependency issues with react, the[ latest beta version](https://www.npmjs.com/package/react-qr-reader/v/3.0.0-beta-1) fixes this issue but it has some breaking changes

**Comment by aeswibon** [comment]
There are some issues with the latest version of react-qr-reader like [Problem with t.selectBestPatterns](https://github.com/react-qr-reader/react-qr-reader/issues/244)

**Comment by aeswibon** [comment]
Will open this issue again once the issues related to package are fixed
