### ISSUE TITLE
Replace react-dates with material ui date picker

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#2380]
replace with mui; https://mui.com/x/react-date-pickers/date-range-picker/#main-content

**Comment by developedBySJ** [comment]
@sainAk This component requires a commercial license of material UI.

**Comment by gigincg** [comment]
@developedBySJ 

We can use https://www.npmjs.com/package/@mui/x-date-pickers

**Comment by rithviknishad** [comment]
Closing this as we have custom-built `DateFormField` and `DateRangeFormField` using tailwind as of now.
