### ISSUE TITLE
"Add Patient": Patient Registration

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2393]
The patient registration form at https://care.coronasafe.in/facility/df1a22fb-1875-4949-af85-15d1917b8bfd/patient

has "Add COVID Suspect/Patient" button to save details. Rename this button to "Add Patient"

**Comment by GokulramGHV** [comment]
Should the page heading also be renamed to "Add Patient" ?

![image](https://user-images.githubusercontent.com/40627011/168822108-c4668a54-b05f-4756-a8a6-d39abfeff2cf.png)
