### ISSUE TITLE
Add floating Notification Icon

### ISSUE THREAD

**Issue by rabilrbl** [coronasafe/care_fe#2399]
Currently, notifications can only be viewed by clicking `Notifications`  on the navbar. Provide a floating notification icon at the bottom right part of the screen with a total count of unread notifications.

**Comment by aparnacoronasafe** [comment]
When there are unread notifications, let's have a red icon with the number of notifications appear near "Notifications" on the sidebar. When the sidebar is collapsed, a red dot near the notifications icon would suffice.
