### ISSUE TITLE
Change badge text color in user profile section

### ISSUE THREAD

**Issue by ishanExtreme** [coronasafe/care_fe#2410]
Text inside badges in the profile section is not clearly visible changing it to white makes it clear

![Screenshot from 2022-05-18 10-55-01](https://user-images.githubusercontent.com/39593226/168965755-28a586e9-f6e3-418f-84cb-125cac0f9ac5.png)
.

**Comment by Parthan-Akon** [comment]
Resolved this issue by adding text color white important.

**Comment by ishanExtreme** [comment]
fixed: https://github.com/coronasafe/care_fe/pull/2413
