### ISSUE TITLE
Creating a new asset throws an error

### ISSUE THREAD

**Issue by naman114** [coronasafe/care_fe#2422]
**Describe the bug**
Creating a new asset with the required fields throws an internal server error

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/caaab916-e877-4153-a0a4-d0afc69f4c1a/assets/new
2. Fill in the required fields

**Screenshots**

![image](https://user-images.githubusercontent.com/57593654/169062849-782361d6-af13-47c8-b881-41ce7ffa2742.png)

**Comment by rabilrbl** [comment]
#### Backend is giving 500 error!

![image](https://user-images.githubusercontent.com/63334479/169093200-af0446d8-f5d4-4f51-bdbb-f630f49390e6.png)

**Comment by sainak** [comment]
@gigincg this is not reproduceable locally

**Comment by sainak** [comment]
This issue is caused because `Asset QR Code ID` is sending blank string which causes integrity error
@rabilrbl do you want to take up this issue to handle it on the FE?

**Comment by rabilrbl** [comment]
> This issue is caused because `Asset QR Code ID` is sending blank string which causes integrity error
> @rabilrbl do you want to take up this issue to handle it on the FE?

Sure 👍
