### ISSUE TITLE
Improving Asset Integration

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2430]
Currently, the Asset Integrations/Configuration doesn't provide the best UI/UX. Nor is it represented best in the backend. Cleaning this up requires a set of issues which are listed below:

- [x] #2431
- [x] #2432
- [x] #2809
- [x] Migrate camera_address to local_ip_address (In care_fe)
- [x] #2810
- [x] #2811

The backend changes for the revamp is tracked at https://github.com/coronasafe/care/issues/757

> Do not Assign the issue to yourself! The subissues will be created when the blockers for them are complete!

**Comment by aparnacoronasafe** [comment]
Align with #2212

**Comment by aeswibon** [comment]
#2809 is already tracked in #2649. Related PR #2654 has already been opened.

**Comment by nihal467** [comment]
issue is resolved
