### ISSUE TITLE
Inventory Summary Malfunction 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2437]
![owjfe](https://user-images.githubusercontent.com/57055998/169257516-1b45aca2-907b-46d2-8130-580288a00fd1.jpg)

i haven't set any quantity minimum requirement for the PPE kit, still, it is by default is showing low stock

**Comment by sainak** [comment]
related to coronasafe/care#725

**Comment by aparnacoronasafe** [comment]
Review required

**Comment by nihal467** [comment]
the new issue will be created with more depth, currently it is not a relevant feature, so closing the issue
