### ISSUE TITLE
Validation: New Bed Assignment should be newer than oldest start time

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2451]
In the UI to Switch Beds, only dates that are newer than the start_time of the current bed should be allowed. Other dates should be disabled

**Comment by kunatastic** [comment]
@gigincg 

Did you meant to only show the newer beds on the shifting page ??

URL - https://care.coronasafe.in/shifting

**Comment by arpancodes** [comment]
@kunatastic no, this refers to the switch bed UI, on the consultation page.

Sample URL: https://care.coronasafe.in/facility/fdad4400-bd11-49dd-9da1-5be0e79fa14e/patient/8f60acc8-4c55-4c77-af6f-2b9125ad4d5f/consultation/71bb4eec-6969-4c93-a1e9-6895945eead4

Disable the dates before `start_time` of the current bed.

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/42417893/169947360-4ac4d4fd-46c9-4df1-bdfc-2353503bcc46.png">

**Comment by aparnacoronasafe** [comment]
The issue seemed resolved in staging
