### ISSUE TITLE
Download options in patient section not working

### ISSUE THREAD

**Issue by ishanExtreme** [coronasafe/care_fe#2452]
**Describe the bug**
Both download options in the patient section of care are throwing error notifications. And the server is giving error code 500.

**To Reproduce**

1. Go to the [patient](https://care.coronasafe.in/patients) section
2. Go to advance filter and filter out **Date of  results** for more than 7 days period for example may-13th to may-20 and click apply
3. Now **Download Live Test** and **Download All Patients** will be available, click and it will throw an error notification.

**Expected behavior**
Clicking the download buttons should download the respective CSV file

**Screenshots**
![Screenshot from 2022-05-20 13-16-01](https://user-images.githubusercontent.com/39593226/169481649-883470e7-f150-4ec2-9175-8929b6591f71.png)

**Comment by sainak** [comment]
Regression from coronasafe/care#715
