### ISSUE TITLE
Add loader to external results section

### ISSUE THREAD

**Issue by ishanExtreme** [coronasafe/care_fe#2454]
The external results section shows "Np result found" until the data is fetched from the server, the other section shows a coronasafe loader. Add the corona safe loader to external results section.

![Screenshot from 2022-05-20 16-20-04](https://user-images.githubusercontent.com/39593226/169512844-0769c3dd-6848-47f4-b642-04448f055e50.png)

**Comment by Pragati1610** [comment]
Can I be assigned this issue?

**Comment by patelaryan7751** [comment]
@Pragati1610 you can take up any issue and assign it to yourself.

**Comment by Pragati1610** [comment]
can @coronasafe/care-fe-code-reviewers review the PR associated with this issue?

**Comment by nihal467** [comment]
@khavinshankar can you give it a look

**Comment by khavinshankar** [comment]
@ishanExtreme this doesn't seem relevant anymore, if the issue persists, feel free to reopen it or create a new issue
