### ISSUE TITLE
Add Option to change role of Existing  User

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2460]
Add an option to change the role of a user by a higher user. For example: District Admin can change the role of user under him like staff, volunteer, etc....

**Comment by gigincg** [comment]
@kunatastic I see you've assigned this, have you created a backend issue for this? Isn't an  API change needed for this?

**Comment by siddnikh** [comment]
@Ritesh-Aggarwal can I work on this?

**Comment by Ritesh-Aggarwal** [comment]
@siddnikh This issue is waiting for backend  , I have done the frontend part.

**Comment by bodhish** [comment]
Rewamp as part of RBAC
