### ISSUE TITLE
Error Messages for Camera Feed

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2497]
In the Patient Camera Feed View, a request is made to use the absoluteMove API of the middleware to move the camera.

Show an error message stating that the camera is unreachable if the `absoluteMove` API fails with the following error response

![image](https://user-images.githubusercontent.com/13028584/169820876-b99f25cf-a11b-4da4-83a6-a2a1624c631b.png)

**Comment by gigincg** [comment]
@rabilrbl Any update on this?

**Comment by rabilrbl** [comment]
@gigincg Last time I worked on this, I was unable to reproduce the error. Will check again and get back to you.
