### ISSUE TITLE
Doctor Video Menu

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2515]
On the patient dashboard (https://care.coronasafe.in/facility/3fec5944-e6b4-4c56-bd01-95f32813578d/patient/f0a1f32a-22fd-4514-b266-9d8ffc670fb5/consultation/1b0dabc7-e641-417f-83d3-032f6285a99e)

when the user clicked on "Doctor Video" a menu on the right side opens up with all the doctors contacts. 

Even when there are more than 5 doctors registered, only 5 items on top of the list shows up. The rest is available only upton scrolling.

Change this and use the entire length of the screen to show the list of doctors.
<img width="405" alt="Screenshot 2022-05-25 at 7 40 36 PM" src="https://user-images.githubusercontent.com/67050716/170283893-cfcdbafb-af6d-4643-bfb0-76a59af17d4f.png">

**Comment by bodhish** [comment]
This list now shows users other than doctors, we should limit it to doctors / have another listing for others. 

@aparnacoronasafe
