### ISSUE TITLE
Edit page header: Patient details

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2519]
https://care.coronasafe.in/facility/3fec5944-e6b4-4c56-bd01-95f32813578d/patient/f0a1f32a-22fd-4514-b266-9d8ffc670fb5/update
<img width="599" alt="Screenshot 2022-05-25 at 8 06 46 PM" src="https://user-images.githubusercontent.com/67050716/170288347-f38237b5-7510-489b-ac62-8ad57d7c81ab.png">

remove "COVID Suspect" from the header. The page header must read as "Update Patient Details"

**Comment by GokulramGHV** [comment]
This issue is already fixed in #2398
