### ISSUE TITLE
Page Header- Patient registration

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2520]
https://care.coronasafe.in/facility/647bdc75-9e41-4199-a3cb-b6eae6d7a976/patient

Remove "COVID SUSPECT" from page header. The page header must be "Add Details of Patient"
<img width="595" alt="Screenshot 2022-05-25 at 8 09 14 PM" src="https://user-images.githubusercontent.com/67050716/170288871-b0fae6d2-9c0e-4a95-ab67-b50db7e235f3.png">

**Comment by GokulramGHV** [comment]
This is already fixed in #2398
