### ISSUE TITLE
Same number of card decks irrespective of zoom in Shifting Page

### ISSUE THREAD

**Issue by anuran-roy** [coronasafe/care_fe#2544]
**Describe the bug**
There are 4 decks displayed in the screen at a time irrespective of zoom.

**To Reproduce**
Zoom in and zoom out (Using Ctrl/+ and Ctrl/- respectively)

**Expected behavior**
When zooming out, more cards should get displayed.

**Screenshots**

_Card Deck at 100% screen zoom:_
![image](https://user-images.githubusercontent.com/76481787/170593135-27dc4f3c-fe25-4cc1-91b6-2161b419c17b.png)

_Card Deck at 67% zoom:_
![image](https://user-images.githubusercontent.com/76481787/170593211-c069f97a-0725-4e26-8d73-eca0e2186ba2.png)

**Comment by nihal467** [comment]
the issue is not relevant anymore
