### ISSUE TITLE
Add responsiveness on mobile view for Patients page

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#2547]
http://localhost:4000/patients
<img width="239" alt="image" src="https://user-images.githubusercontent.com/70687348/170635604-75c10289-fd33-478f-9cf7-510af594e0e8.png">

**Comment by patelaryan7751** [comment]
Hey @Pranshu1902 I have already made a Pull Request on this issue https://github.com/coronasafe/care_fe/pull/2493
