### ISSUE TITLE
add: show minimum item in inventory

### ISSUE THREAD

**Issue by kunatastic** [coronasafe/care_fe#2549]
A physical number of the minimum items would be great for UX

<img width="555" alt="Untitled" src="https://user-images.githubusercontent.com/57055998/212257584-e4815bdb-7126-4cae-8d54-9548f2591275.png">

**Comment by nihal467** [comment]
@kunatastic what is the status of this issue, unable to under the issue, can you add more info on this issue or a mock-up design, regarding the approach

**Comment by Yash12Bansal** [comment]
@rithviknishad @mathew-alex @kunatastic 
I would like to work on this issue. please assign this to me

**Comment by rithviknishad** [comment]
You can set min. qty for stocks if u go to set min. quantity page. that data should be reflected in a new column here.

**Comment by nihal467** [comment]
@Yash12Bansal unassigning you from the issue, due to inactivity for almost two months now

**Comment by kshitijv256** [comment]
@nihal467 @rithviknishad  I would like to work on this issue

**Comment by nihal467** [comment]
@kshitijv256 removing you from this issue due to inactivity

**Comment by nihal467** [comment]
Closing this issue as a detail new issue has been created
