### ISSUE TITLE
Required Fields can be submitted empty in some forms

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#2557]
## When updating the shift request form we can submit the form being the "reason for shift" field empty which is a required field.

https://user-images.githubusercontent.com/59426397/170803421-08803e06-4fe1-47aa-aa44-d1f5dee4383b.mp4

## When updating the facility details form we can submit the form being the "address" field empty. The form does not post the details but it should prevent from submitting the form by displaying an error msg that the field is empty.

https://user-images.githubusercontent.com/59426397/170803591-3c0c7061-7236-4f38-ac2b-e37cc0e7f13a.mp4

## When updating the resource request form we can submit the form being the "Description for Request" field empty. 

https://user-images.githubusercontent.com/59426397/170803698-1085718e-effc-4e37-a603-23e81be756bc.mp4

**Comment by aparnacoronasafe** [comment]
Make all the above fields manadatory.
