### ISSUE TITLE
Blank spaces is accepted as comment on shifting page

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#2559]
https://care.coronasafe.in/shifting/9627fed5-1dee-47f2-88cf-227ba04887b5

https://www.loom.com/share/3b8f18555ab84a919dc9ff35213e15ba

**Comment by patelaryan7751** [comment]
Hey @Pranshu1902 i have mentioned this bug in this issue https://github.com/coronasafe/care_fe/issues/2557

**Comment by patelaryan7751** [comment]
https://github.com/coronasafe/care_fe/pull/2525 this issue has been fixed by @Ashesh3
