### ISSUE TITLE
Unintended additional border in text fields

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#2560]
Example screenshots...

![image](https://user-images.githubusercontent.com/25143503/170826680-7ce8d45d-cd67-4cde-be8e-a0e601e8d12b.png)

![image](https://user-images.githubusercontent.com/25143503/170826766-c22ed9ed-73de-44fb-81a1-e795f37d16f1.png)

**Comment by developedBySJ** [comment]
@rithviknishad Can you elaborate?

**Comment by rithviknishad** [comment]
@developedBySJ 
The text fields seems to have additional unintended border when focused.
Also it strikes through the labels.

![image](https://user-images.githubusercontent.com/25143503/171101828-7c89f319-cb89-43ff-8d56-3552ec448915.png)

**Comment by developedBySJ** [comment]
@rithviknishad I am not able to reproduce the issue on chrome/brave/firefox.
Can you add steps to reduce the issue?

**Comment by rithviknishad** [comment]
**Steps to reproduce:**

```sh
git checkout develop
git fetch upstream
git pull upstream develop
yarn start
```
On firefox 100.0.2
![image](https://user-images.githubusercontent.com/25143503/171105319-368a8c7d-67be-454e-b659-7eb96a1f5408.png)

**Comment by rithviknishad** [comment]
@developedBySJ 
Tried to trace where the issue is coming from, but no clue...
Was able to reproduce this issue when reviewing `cra-5` branch #2527 
Pretty sure, it didn't exist before that.

**Comment by rabilrbl** [comment]
on Edge (chromium)

![image](https://user-images.githubusercontent.com/63334479/171319010-a158b767-e8d2-4dba-abec-dd3bd42f07e8.png)

**Comment by patelaryan7751** [comment]
@rithviknishad 

I am also having this issue in the Chrome browser

![image](https://user-images.githubusercontent.com/59426397/171413635-d66b5e22-88c5-4d7b-b720-daab8ed2af18.png)

**Comment by rithviknishad** [comment]
@developedBySJ it becomes visible in staging deploy once empty cache and hard reload is done.

**Comment by rithviknishad** [comment]
part of #2616
