### ISSUE TITLE
Ending Backslashes missing in api paths

### ISSUE THREAD

**Issue by Marmik2003** [coronasafe/care_fe#2580]
missing backslashes sometimes give error while testing in local machine

**Comment by gigincg** [comment]
@Marmik2003 Can you add a bit more depth to this? Are you talking about missing / in the React Routes, or for API calls?

**Comment by Marmik2003** [comment]
it is missing in API calls, just for some routes, thus gives 500s while developing locally with proxy of localhost

**Comment by gigincg** [comment]
@Marmik2003 I think it was fixed. Can you recheck?

**Comment by Marmik2003** [comment]
yes, it was fixed by https://github.com/coronasafe/care_fe/pull/2395, I did not have attention to this PR... is working fine now
