### ISSUE TITLE
Add Occupation field

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2588]
Add "Occupation" field to the patient registration form ( https://care.coronasafe.in/facility/6e401539-e27f-4aff-a626-c9d42427ffd7/patient ).
 Add the short text field right after the "Gender" field.

[part of #2218 ]

**Comment by aeswibon** [comment]
@aparnacoronasafe Is there a need of this field right now? If not then we can just close the issue.

**Comment by PranshuNayak** [comment]
hi is this issue open ?

**Comment by nihal467** [comment]
@aparnacoronasafe is it relevant in field now

**Comment by Keshav-0907** [comment]
@nihal467 I want to work on this, can you please assign this to me

**Comment by rithviknishad** [comment]
Closing as duplicate of #6945

@Keshav-0907 feel free to pickup other issues!

**Comment by Keshav-0907** [comment]
@rithviknishad Yeah Sure, will pickup another Issue
