### ISSUE TITLE
User Generation: Phone Number: Bug

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2593]
While creating user, if the whatsapp number is not as the phone number, then while typing whatsapp numbers, the input dissappears.

The bug may be an effect of the addition of the new checkbox to mark phone number as whatsapp numbere as the same.

https://user-images.githubusercontent.com/67050716/171157798-f83360f3-1bf7-4324-8744-f1527b885828.mov

**Comment by gigincg** [comment]
@cp-Coder This is an issue in the field. Will you be able to make a PR ASAP?

@rabilrbl @nihal467
