### ISSUE TITLE
Critical Care Index- Copy previous value

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2598]
Currently, the Critical Care Index (https://care.coronasafe.in/facility/3fec5944-e6b4-4c56-bd01-95f32813578d/patient/c3fdb48c-7178-4197-9ed2-01392d2b04d1/consultation/6e209006-972e-4552-a206-0458ed1ed601/daily_rounds/a13929c4-93ba-48fe-a99c-8d55cdf2faaf/update) Comprises of 12 separate forms. These forms are filled out as and when relevant.

Additionally, there is a feature to copy previously saved values (https://care.coronasafe.in/facility/3fec5944-e6b4-4c56-bd01-95f32813578d/patient/c3fdb48c-7178-4197-9ed2-01392d2b04d1/consultation/6e209006-972e-4552-a206-0458ed1ed601/daily-rounds). The intention behind this is to make data entry easy for nurses, since now they wont have to type everything, but only those values that have changed. 

**Problem**: currently, the data is getting polluted, since when you mark "copy previous values" there is no mechanism to ensure the user goes through the saved values and reviews them. Most likely a lot of entries are made without the knowledge of the user. 

**Possible Solution**

- make the critical care section (all 12 forms) into a single form with collapsable 12 sections. Where ever there is value copied from the previous log, those open up as default and the remaining stays closed. This way the user will have to browse through all the opened section and click on save, ensuring that the user has reviews all entries. 

- Another maybe simpler way is to keep the critical care index as is, i.e. with 12 separate form. When the user selects "copy previous values", A badge must appear in the critical care index against the headings were there are pre-filled values. When the user opens the section, the values must be pre-filled, the user reviews and clicks on save in the particular form, only then the data gets saved. Any form that is not opened by the user and saved by clicking on the save button, the values do not get saved. 

@bodhish @vigneshhari @gigincg

**Comment by aparnacoronasafe** [comment]
@gigincg lets finalise on the changes and move ahead. you were to discuss with Vignesh and come back on this @vigneshhari

**Comment by aparnacoronasafe** [comment]
The log update form is to be bifurcated.



- Periodic monitoring, like vitals
- Events- nursing care, Dialysis
- Investigation

**Comment by khavinshankar** [comment]
@aparnacoronasafe is this issue still relevant?

**Comment by nihal467** [comment]
@aparnacoronasafe is the issue still relevant

**Comment by aparnacoronasafe** [comment]
yes. this is still relevant

**Comment by nihal467** [comment]
@aparnacoronasafe did you complete filling the issue, if yes, can you unassign yourself

**Comment by nihal467** [comment]
@gigincg can you look into it

**Comment by gigincg** [comment]
This will not be relevant post FHIR Forms.
