### ISSUE TITLE
File Upload: Audio not working

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2611]
https://care.coronasafe.in/facility/3fec5944-e6b4-4c56-bd01-95f32813578d/patient/c3fdb48c-7178-4197-9ed2-01392d2b04d1/consultation/6e209006-972e-4552-a206-0458ed1ed601/files

In the file upload feature, the audio is getting recorded, but the same is not getting saved.

**Comment by ishanExtreme** [comment]
Its an issue with S3 bucket CORS rules, I am getting CORS error while uploading file(Same error from care official domain as well).
![Screenshot from 2022-06-01 18-00-31](https://user-images.githubusercontent.com/39593226/171405171-35d748bf-6a1f-4524-85ba-e84cff9ef4ac.png)

![Screenshot from 2022-06-01 18-01-23](https://user-images.githubusercontent.com/39593226/171405188-56291578-abf6-4ff2-beed-119b779cc65c.png)

@gigincg

**Comment by aeswibon** [comment]
Duplicate of #2296 and similar to #2297

**Comment by cp-Coder** [comment]
Tracked in #2296
