### ISSUE TITLE
Issues with the tailwind update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2616]
![1](https://user-images.githubusercontent.com/57055998/171427927-832ec32a-b55b-427c-9809-001077696137.png)

- [x]  Blue border-box along all the boxes across the platform

![2](https://user-images.githubusercontent.com/57055998/171428022-a38b0ad3-8766-4660-a38c-45f399381027.png)

- [x] inside the facilities page, and many other pages there is a blue box inside the typing area of the box

![3](https://user-images.githubusercontent.com/57055998/171428146-0796d624-c538-48fc-b45f-301ec6605142.png)

- [ ] Splitting lines are missing in the patient tab.

![4](https://user-images.githubusercontent.com/57055998/171428223-cbf2928f-9c48-4c7b-a9fe-f277f3c16fa1.png)

- [ ]  patient detail page alignment is off
- [ ]  all the critical summary heading are misaligned like summary, update etc.. buttons

![5](https://user-images.githubusercontent.com/57055998/171428411-792d2005-f219-470f-a560-e52c90c14c6c.png)

- [x] when we are hovering along with the sample details button, in the sample test tab, there is no effect showing, like the one showing when we are hovering over the update sample test status button

![6](https://user-images.githubusercontent.com/57055998/171428525-e6bcf622-ac13-4f45-afa2-143f27f53aa0.png)

- [x] The shifting page and resource page details are so conjusted, it is having no gap in between the lines

![7](https://user-images.githubusercontent.com/57055998/171428606-ecbd3e74-f4e0-4584-b526-74a7db87ceef.png)

- [x] All the page filters are utilizing a lot of white space on the right side

![8](https://user-images.githubusercontent.com/57055998/171428982-bc6c057f-a567-4270-b7ee-fa090bd5b1ab.png)

- [x] user profile details page are so conjusted without space.

![9](https://user-images.githubusercontent.com/57055998/171429083-0fc399d8-e7a9-4143-a005-bb96786f91ab.png)

- [x] The data's in the notification panel are conjusted.

**Comment by rabilrbl** [comment]
@nihal467 the conjusted UI may be fixed with [#2570](https://github.com/coronasafe/care_fe/pull/2570)

**Comment by patelaryan7751** [comment]
I think the patient details page is already fixed @nihal467 :thinking: 

![image](https://user-images.githubusercontent.com/59426397/171566780-6bb0946f-a216-42fc-bbf4-1bbcee09465d.png)

**Comment by nihal467** [comment]
@patelaryan7751 @gigincg can you check this URL

https://care.coronasafe.in/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/e98d561a-0944-4a01-b461-232d2609045f/consultation/7ecb3689-6c84-4901-ac17-6efdf10f4c8a

it is having an issue

**Comment by nihal467** [comment]
@rabilrbl  the conjusted UI have be fixed with #2570 PR

**Comment by shivankacker** [comment]
>all the critical summary heading are misaligned like summary, update etc.. buttons

fixed in #2639

**Comment by shivankacker** [comment]
> patient detail page alignment is off

will be fixed in #2563

**Comment by aeswibon** [comment]
Closing this issue as all the tasks and their PRs have been completed
