### ISSUE TITLE
Patient list filter "Last Admitted" fails

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#2642]
Applying the filter `Last Admitted to (Bed Type)` fails the search, erroring out as follows:

```
File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/query.py", line 1243, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
django.core.exceptions.FieldError: Related Field got invalid lookup: admitted_to
```

![image](https://user-images.githubusercontent.com/3626859/171723799-435bcdc0-9c6e-431c-9c69-94161944085c.png)

**Comment by aparnacoronasafe** [comment]
The bed types in the advanced filter option needs to sync with the updated bedtypes. taken care of in #2752
