### ISSUE TITLE
Enhancement: Service Work Errors need not be show to Users

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2646]
There isn't a lot of value that a user receives by seeing a "Service Worker" Related Alert. Let's switch the Service Worker Errors to be shown in the console and Reported via Sentry

cc: @bodhish

**Comment by anuran-roy** [comment]
@gigincg can I take up the issue?

**Comment by gigincg** [comment]
@anuran-roy Is this in Progress?

**Comment by anuran-roy** [comment]
Yes Gigin, I'll push it by tomorrow

**Comment by nihal467** [comment]
issue is resolved
