### ISSUE TITLE
Image Processing to capture Vitals Periodically

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2655]
Build software capability for the PTZ network Camera to periodically capture the vitals of the patients by gathering the vitals from the 5 para monitor.

The camera must pan and zoom to the monitor (preset already built in CARE) and process the image to capture vitals. The same must be done at preset periods. Default may be set at every 1 hour. However for critical patients, the users may want to edit this to half and hour or every 15 min

The 5-para monitor reading will look like below:
![Livefeed monitor](https://user-images.githubusercontent.com/67050716/172168115-e01c13b0-367c-4675-9ae7-43453c6f2bc3.jpeg)

The 5 parameters to be captured are:
1) Temp: Appearing in the  image in bottom right in pink colour, 24.4 degree celsius 
2) Pulse Rate : Appearing on top right corner in yellow, 95
3) Respiratory Rate: Appears right above the temperature in blue, --
4) SPO2: Below BP in Yellow
5) BP: Below Pulse rate in Orange 

Adding a few more images of 5-para monitors
<img width="1440" alt="Screenshot 2022-05-01 at 11 30 03 PM" src="https://user-images.githubusercontent.com/67050716/172871730-dc1111b6-71b3-45a9-8dc0-4a747816ee0d.png">

<img width="1439" alt="Screenshot 2022-06-09 at 8 00 42 PM" src="https://user-images.githubusercontent.com/67050716/172873717-30b30f34-1161-4d57-adb8-79d371720b67.png">

<img width="1435" alt="Screenshot 2022-06-09 at 8 01 03 PM" src="https://user-images.githubusercontent.com/67050716/172873723-c1526848-6842-4241-b28a-1fb750e19d38.png">

<img width="1413" alt="Screenshot 2022-06-09 at 8 02 19 PM" src="https://user-images.githubusercontent.com/67050716/172873753-c7ca7e4b-18b4-4662-aceb-034d63ac1094.png">

<img width="1437" alt="Screenshot 2022-06-09 at 8 02 44 PM" src="https://user-images.githubusercontent.com/67050716/172873759-d63fb465-c53c-4d64-b41d-5bbd21a2bea6.png">

<img width="1013" alt="Screenshot 2022-06-09 at 8 03 17 PM" src="https://user-images.githubusercontent.com/67050716/172873765-49757d3a-ae49-40ac-916c-da1d18894d47.png">

**Comment by ishanExtreme** [comment]
API made on starlette is deployed: http://139.59.33.255:8000/api/predict

Working on CRON job.

**Comment by gigincg** [comment]
Currently Tracked in https://github.com/coronasafe/care_ocr

**Comment by nihal467** [comment]
@ishanExtreme any update on this issue 

CC: @gigincg is it okay to close this issue, as it is been tracked in another repo

**Comment by bodhish** [comment]
Closing this as its addressed.
