### ISSUE TITLE
Longitude value doesnot accepts more than 90 and less than -90

### ISSUE THREAD

**Issue by ishanExtreme** [coronasafe/care_fe#2656]
### Overview
Facility page has input option for latitude and longitude but longitude is wrongly set to take value between [-90, 90]. *Longitude range is between [-180, 180]

### Steps to reproduce

1. Select a facility
2. Go to update facilitty
3. Longitude doesnot accept value beyond 90 or less than -90

### Expected Behaviour
Longitude should accept value in range [-180, 180] (including)

**Comment by aparnacoronasafe** [comment]
Done in #2741
