### ISSUE TITLE
After a patient is discharged from CARE the switch bed option should be hidden

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#2673]
# Bugs 

## After a patient is discharged from CARE the switch bed option should be hidden
![kli](https://user-images.githubusercontent.com/59426397/173092391-c776b664-a6fd-41b0-8695-d3158452f453.png)

**Comment by aparnacoronasafe** [comment]
Similar to #847 where PR is submitted for review. Please note @patelaryan7751
