### ISSUE TITLE
Camera UI button is missing

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2683]
![ewd](https://user-images.githubusercontent.com/57055998/173191262-afad4c9d-3e97-4aec-bda6-c23f994481fa.jpg)

the camera UI button is missing

**Comment by aparnacoronasafe** [comment]
Comes up properly now. The issue seems resolved. Reopen issue if the issue persists @nihal467

**Comment by shivankacker** [comment]
@aparnacoronasafe issue persists with screens of smaller sizes. 😅
fixed in #2758
