### ISSUE TITLE
Auto reload failed : Consultation File

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2685]
![pwekof](https://user-images.githubusercontent.com/57055998/173191337-b0812ea5-9018-4000-9493-b0c4af99e3a5.jpg)

after the files are uploaded in the consultation of a patient, the page is not auto reloaded

**Comment by aeswibon** [comment]
@skks1212 since issue #2297 has been fixed, now the page is auto-reloading with every upload.

**Comment by shivankacker** [comment]
@cp-Coder Is it? my instance is working fine. Can you share a screen recording?

**Comment by aeswibon** [comment]
@skks1212 I think I didn't convey my thoughts correctly. I was saying that now with every upload, it is successfully reloading the page. So this issue has been fixed.
