### ISSUE TITLE
Bug in assiging to a volunter

### ISSUE THREAD

**Issue by kunatastic** [coronasafe/care_fe#2695]
URL: http://localhost:4000/facility/7a560e62-6aae-4293-8f1a-0ba840e3449f/patient/192fdee9-397f-49bd-833a-10f700416da8

I am able to click the assign to volunteer option even tho no volunteer are selected
![image](https://user-images.githubusercontent.com/61267953/173280298-f533c3b4-cfa3-4ba4-990e-2e6322dfeeca.png)

Solution could be to add a alert like "Select the volunteer" and disable submit

**Comment by nihal467** [comment]
@kunatastic are you still working on the issue

**Comment by nihal467** [comment]
it is not relevant right now, will be making new issue later
