### ISSUE TITLE
Patient-id overflowing on tranfer/admit patient

### ISSUE THREAD

**Issue by kunatastic** [coronasafe/care_fe#2698]
URL: http://localhost:4000/facility/653c86f1-40be-455b-9499-127210867246/patient?extId=6567

Patient id are overflowing and un-readable

![image](https://user-images.githubusercontent.com/61267953/173328099-4c630dfd-bd97-4d40-8d67-2bd93e3b4849.png)

**Comment by shivankacker** [comment]
@kunatastic this issue has already been taken up and solved with PR #2672 😅
You can add to the PR if you wish to
