### ISSUE TITLE
Asset View: Next page arrow

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2700]
**Describe the bug**
The arrow to navigate to next page (>) or last page (>>>) at the bottom of the view asset page always takes user to 1st page of asset list.

New issue experienced after latest release

**To Reproduce**

1. Go to Facility
2. Click on View Asset
3. Scroll down to end of the page where you have the page numbers and arrows to take you to previous/next page
4. when you click the arrows, the user is taken to the first page of asset list
<img width="456" alt="Screenshot 2022-06-13 at 4 26 59 PM" src="https://user-images.githubusercontent.com/67050716/173339601-ce84cfd8-6d45-48fc-bd0b-afb9854842fd.png">

**Comment by aparnacoronasafe** [comment]
This page navigation issue exists in Patient listing also

**Comment by shivankacker** [comment]
#2702 will fix for all pages
