### ISSUE TITLE
Deleted doctors appear in Doctor Connect 

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2701]
**Describe the bug**
The list appearing for Doctor Connect must only show all doctor linked to the hospital, excluding deleted Doctors. Deleted Doctors also appear in the list.

<img width="400" alt="Screenshot 2022-06-13 at 4 31 58 PM" src="https://user-images.githubusercontent.com/67050716/173340815-189b6d65-5ecc-4fba-ae44-c60d3948bcff.png">

The doctor by the name Aparna Sathianathan with phone number 9745150779 was deleted from the users tab. Still the doctors listing comes up in the patients "Doctor Connect"

**Comment by shivankacker** [comment]
This is a backend issue and will be solved by merging [https://github.com/coronasafe/care/pull/855](https://github.com/coronasafe/care/pull/855).
There are some UI changes which will be addressed in another PR soon
