### ISSUE TITLE
Pain scale- Log Update

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2732]
currently pain scale slider is placed in the Hemodynamic parameters (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0/daily_rounds/1f0a9406-de65-4538-96a6-70f835b378ea/update). This is not right. 

Move it to "Others" (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0/daily_rounds/1f0a9406-de65-4538-96a6-70f835b378ea/update)

[] Move slider in Log update for pain scale from hemodynamic parameters to others 

@aparnacoronasafe to confirm on visualization design from doctors. Issue blacked for lack of clarity

**Comment by gigincg** [comment]
@aparnacoronasafe Can you check on this?

**Comment by aparnacoronasafe** [comment]
This is not relevant anymore. Pain slider is already improved.
