### ISSUE TITLE
Pressing back takes you back, but not where you expect...

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#2737]
To Reproduce:

- Be on any other page other than care.
- Navigate to any care url (eg. https://care.coronasafe.in//facility/551f9e09-04a3-4f52-ade2-1db45588741d/assets/new)
- Press the back button as shown in image.

Observed Behaviour:
- Navigates back to the url outside of care.

Expected Behaviour: 
- Navigates to parent page: Facility Assets Page

![image](https://user-images.githubusercontent.com/25143503/174280096-f2aeba0b-1c8b-4f92-a1a6-a6a90f7323eb.png)

**Comment by anuran-roy** [comment]
@rithviknishad can I take up this issue?

**Comment by rithviknishad** [comment]
@anuran-roy Yup!

**Comment by nihal467** [comment]
@rithviknishad is this issue this happening or resolved

**Comment by nihal467** [comment]
@Pragati1610 
 what is the status of this issue

**Comment by nihal467** [comment]
the PR is ready for testing
