### ISSUE TITLE
Changes to be made in the consultation form : Add Health Details

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#2738]
Part of #2218 
HEALTH DETAILS

 - Add a new collapsable section to the consultation form on top. This section will contain all health details of the Patient.
 - The first field is "Allergy"- YES/NO. If YES, a short text box for details. (the text field already exists in the patient registration form. the same may be migrated)
 - Second field will be for "Vaccinations". The user must be able to select multe inputs from the options. The Options would be: COVID (1 dose, 2 dose), Hep B, Hep A. (The field for COVID Vaccinationa already exists in patient registration form)
 - "Blood Group" With dropdown. (The field already exists in the patient registration form and may be migrated here)
 - Field for "Weight" and "Height" existing at the bottom of the consultation form may be moved up to the top after blood group.
 - Add a Long Text Field for "Familty Details"

**Comment by aparnacoronasafe** [comment]
@vigneshhari Can you prioritize this?

**Comment by vigneshhari** [comment]
@Marmik2003 @skks1212 @Krishna-Sivakumar @sainAk Someone take care of this.

**Comment by shivankacker** [comment]
@vigneshhari https://github.com/coronasafe/care/issues/859 this PR needs to reviewed and merged for this issue

**Comment by aparnacoronasafe** [comment]
@skks1212 @patelaryan7751 @Pragati1610  I have broken this issue down further in the following issues
#3332 Allergies
#3333 Vaccine
#3335 Blood group
#3336 Height weight
#3338 Family details

**Comment by nihal467** [comment]
@cp-Coder Due to inactivity and the existing linked PR is not mergeable, unlinking you from this issue

As per the communication with @aparnacoronasafe , it will be sub-grouped with events module, so for time-being marking the issue as blocked

**Comment by gigincg** [comment]
Closing in Favour of https://github.com/coronasafe/care_fe/issues/8388
