### ISSUE TITLE
"Decision after Consultation" option if changed to "Admission" the consultation form doesnot Update !

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#2747]
# Bug

## "Decision after Consultation" option if changed to "Admission" the consultation form does not Update!
https://user-images.githubusercontent.com/59426397/174426298-854503c4-868c-42ca-83d2-c81d4bf608fa.mp4

**Comment by gigincg** [comment]
@aparnacoronasafe Currently we are not allowing modification of Admission Date. We should either disallow both `Admission Date` and `Decision after Consultation` or allow both. What's your take on this?

**Comment by shivankacker** [comment]
@gigincg @aparnacoronasafe what should be done with this issue?

**Comment by aparnacoronasafe** [comment]
@gigincg . We MUST allow both admission date and decision after consultation. Why would we disallow it?

**Comment by Ashesh3** [comment]
@gigincg any updates regarding what should be done with this issue?

**Comment by gigincg** [comment]
@aparnacoronasafe We're talking only about edits here.

**Comment by aparnacoronasafe** [comment]
Let's keep both editable

**Comment by Ashesh3** [comment]
Seems like the currently both Admission Date and Decision after Consultation are editable fields. I am able to change them without issue on staging. Does this issue still apply? @patelaryan7751 can you check if this is resolved now?
