### ISSUE TITLE
Add Location to list of beds in Update bed

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2751]
The update bed section in consultation form (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/4e339b9d-1547-4f2f-9b80-64b378d9d835/consultation/818c2051-0d2d-4f62-968d-b17787d7a259/update) has table showing history of bed allocation. 
<img width="889" alt="Screenshot 2022-06-18 at 1 49 16 PM" src="https://user-images.githubusercontent.com/67050716/174429369-3df70bd5-9e2e-4ecf-b273-45f9f2a2dc7c.png">

The table must contain the location (like female ward, etc) along with bed. No.

**Comment by cp-Coder** [comment]
@aparnacoronasafe Can you tell which fields to include? \
__Fields__ that can be inserted:
