### ISSUE TITLE
Sync Bed Types in Advanced filter

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2752]
The patient list (https://care.coronasafe.in/patients?district=&lsgBody=&facility=015ad911-39b7-4104-b304-bf8178c33830&facility_type=&date_declared_positive_before=&date_declared_positive_after=&date_of_result_before=&date_of_result_after=&created_date_before=&created_date_after=&modified_date_before=&modified_date_after=&date_of_result=&last_consultation_admission_date_before=&last_consultation_admission_date_after=&last_consultation_discharge_date_before=&last_consultation_discharge_date_after=&ordering=&category=&gender=&disease_status=&age_min=&age_max=&last_consultation_admitted_to_list=2&srf_id=&number_of_doses=&covin_id=&is_kasp=&is_declared_positive=&last_consultation_symptoms_onset_date_before=&last_consultation_symptoms_onset_date_after=&last_vaccinated_date_before=&last_vaccinated_date_after=&last_consultation_is_telemedicine=&is_antenatal=) has advanced filter option. 

The "Last Admitted to bed type" the dropdown list is outdated. 

Sync the bed types to the bed types in Bed management > Location management. 

The options should be 
- Isolation
- ICU
- Bed with oxygen support
- Regular

**Comment by aeswibon** [comment]
@aparnacoronasafe Do you mean `Not admitted` when you mentioned `Regular` option?
