### ISSUE TITLE
Navbar in consultation details page is transparent

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#2756]
![image](https://user-images.githubusercontent.com/25143503/174432513-84daf718-3550-45a0-88a3-ea6e6a89bd50.png)

**Comment by aparnacoronasafe** [comment]
@gigincg is this intentionally made transparent?

**Comment by rithviknishad** [comment]
@gigincg also was this intended to be like navbar in the first place? 
`lg:absolute` with `right-0 top0` seems to have been added for it's div, but that seems to have a different intention.
