### ISSUE TITLE
Add icons to facility listing

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2759]
in facility list (https://care.coronasafe.in/facility), against each facility list, add icons for 
- No. of live patients / Total capacity
- Whether hospital cameras are live (if live green, if offline red and no icon if the hospital doesn't have a server for the camera )
- Whether the hospital server is online
- Whether any user is online from the hospital.
<img width="452" alt="Screenshot 2022-06-18 at 6 27 47 PM" src="https://user-images.githubusercontent.com/67050716/174438832-68101797-8cde-402e-b085-bf920030f6d9.png">

change position and size of icons to fit minimally in the card

**Comment by gigincg** [comment]
@patelaryan7751 Have you filed the Backend Issue for this? Can you link the 2 Issues? Add a reference to the backend Issue Here

**Comment by patelaryan7751** [comment]
Yeah, sure . @gigincg  https://github.com/coronasafe/care/issues/881  this one.

**Comment by sainak** [comment]
@aparnacoronasafe @gigincg is this still needed?

**Comment by nihal467** [comment]
@aparnacoronasafe is the issue still relevant, modify/close this issue

**Comment by bodhish** [comment]
Lets not do it
