### ISSUE TITLE
Insulin frequency : wrong visualisation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2765]
Insuline intake frequency marked [here](https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0/daily_rounds/1f0a9406-de65-4538-96a6-70f835b378ea/update) as choice, is represented on the [graph ](https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0/summary)wrongly as a number.

Find better way to represent the frequency of intake

**Comment by nihal467** [comment]
@cp-Coder what is the status on this issue

**Comment by nihal467** [comment]
@aparnacoronasafe is this issue relevant

**Comment by aeswibon** [comment]
I will open the PR tonight

**Comment by aeswibon** [comment]
Will open a new issue
