### ISSUE TITLE
Assigning patients to a volunteer

### ISSUE THREAD

**Issue by kunatastic** [coronasafe/care_fe#2771]
- [ ] No default Text on invalid search results
![image](https://user-images.githubusercontent.com/61267953/174467003-3057051c-7cd5-43bc-9932-45a0393bc82e.png)

- [ ] Modal is overflowing when list is shown
![image](https://user-images.githubusercontent.com/61267953/174467048-86995a3a-e9a0-4671-bd42-2e5ac1e9a2ef.png)

- [ ] Unwanted outline on inner div
![image](https://user-images.githubusercontent.com/61267953/174467065-a9fda5f9-9fa8-4835-aa71-69608e1cfe3a.png)

- [ ] Improper Whitespace usage 
![image](https://user-images.githubusercontent.com/61267953/174467088-74c12df8-80bf-45ca-92f5-6431769d7d19.png)

All these issues can be resolved under same PR along with #2695

**Comment by nihal467** [comment]
issue is been resolved in current staging
