### ISSUE TITLE
Error in Summary 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#2783]
"Something went wrong" error pops up when click on Summary from Patient dashboard.

![issue github new](https://user-images.githubusercontent.com/75214902/174606355-2e17ea94-4f77-44cf-bf7b-0b4fae051536.png)

**Comment by shivankacker** [comment]
@samholics I am unable to replicate the issue on the latest develop branch, can you send more details?

**Comment by Ashesh3** [comment]
Seems duplicate of https://github.com/coronasafe/care_fe/pull/2715 (Created on June 14th)
