### ISSUE TITLE
Fix inconsistent color palette in Sample Test Page

### ISSUE THREAD

**Issue by thenithinbalaji** [coronasafe/care_fe#2801]
**#3B82F6** and **#1D4ED8** used for buttons in https://care.coronasafe.in/sample 
are inconsistent with **#03543F** used in the menu/nav bar

**Comment by gigincg** [comment]
@thenithinbalaji If you wanted to make a PR for this, I can change the Assignee.

cc: @cp-Coder

**Comment by thenithinbalaji** [comment]
Yes, @gigincg I'll make PR for this!!

**Comment by aeswibon** [comment]
@thenithinbalaji okay, I will assign this issue to you.

**Comment by thenithinbalaji** [comment]
I am really sorry, I don't think I'll be able to do this! 
Sorry for the inconvenience. 
cc: @cp-Coder
