### ISSUE TITLE
Redirected to "Error 404" Page before going to login page when signout is pressed

### ISSUE THREAD

**Issue by thenithinbalaji** [coronasafe/care_fe#2803]
Redirected to "Error 404" Page before going to the login page when signout is pressed. 

1. log in to CARE
2. Click on Sign Out
3. See Error 404 getting displayed before redirecting to the login page

**Comment by aeswibon** [comment]
@thenithinbalaji This issue has already been filed. PR [#2722](https://github.com/coronasafe/care_fe/pull/2722) will fix this issue.
