### ISSUE TITLE
Styling Issue : Droplist : Inventory

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2834]
![11](https://user-images.githubusercontent.com/57055998/175509578-a9124ca1-01d3-4939-92b7-f17703de731e.jpg)

since we are having all rectangle or straight-line design, having a curve of the droplist doesn't look good with UI

**Comment by patelaryan7751** [comment]
Hey, @nihal467 it is a rectangle in my browser. Can you provide the steps to reproduce it?

**Comment by aeswibon** [comment]
@patelaryan7751 I am able to reproduce the error. Try this [url](https://care.coronasafe.in/facility/551f9e09-04a3-4f52-ade2-1db45588741d/inventory/add)

**Comment by patelaryan7751** [comment]
Yeah @cp-Coder , but in my case, the drop list is a rectangle. are you viewing curve drop list?

**Comment by aeswibon** [comment]
> Yeah @cp-Coder , but in my case, the drop list is a rectangle. are you viewing curve drop list?

Yep

**Comment by patelaryan7751** [comment]
Which browser are you using? @cp-Coder

**Comment by aeswibon** [comment]
> Which browser are you using? @cp-Coder

Brave

**Comment by aeswibon** [comment]
@patelaryan7751 Did you able to reproduce the error?

**Comment by patelaryan7751** [comment]
@cp-Coder no :cry:

**Comment by nihal467** [comment]
the new issue will be filled regarding this , for upgrading to new tailwind droplist
