### ISSUE TITLE
Alignment Issue : Bed Management

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2838]
![14](https://user-images.githubusercontent.com/57055998/175514868-a9a560ac-513d-49d2-b9dc-e93d42ed9859.jpg)

**Comment by naman114** [comment]
@nihal467 @cp-Coder I have revamped the Bed Management page entirely in the PR #2903

**Comment by cp-Coder** [comment]
This issue has been completed by PR #2903

**Comment by cp-Coder** [comment]
This issue has been completed by PR #2903

**Comment by aeswibon** [comment]
This issue has been completed by PR #2903
