### ISSUE TITLE
Facility Download Excel Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2844]
![17a](https://user-images.githubusercontent.com/57055998/175528739-8bcecaf5-77a4-4839-9a5c-7bb80b70fe96.jpg)
![18](https://user-images.githubusercontent.com/57055998/175529075-3de4d27e-92df-47af-ab92-bd9584d3abdc.jpg)

all the download files are showing no proper data, check all the generated excel file output

**Comment by nihal467** [comment]
@cp-Coder status of the issue

**Comment by nihal467** [comment]
[facilities-22-07-2022_07_35_47.csv](https://github.com/coronasafe/care_fe/files/9168471/facilities-22-07-2022_07_35_47.csv)

@cp-Coder it is downloaded file

**Comment by aeswibon** [comment]
@nihal467 I have submitted the PR. The problem was if any value has "," (comma) in their value, then the value got split.
