### ISSUE TITLE
Revamp Patient Detail Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2851]
![21](https://user-images.githubusercontent.com/57055998/175655468-ef4bf9ce-8a9e-4408-8fcf-413e6836c512.jpg)
![21a](https://user-images.githubusercontent.com/57055998/175655545-eb57c673-dd19-47c2-bbff-9546c279a47d.jpg)

- [ ] the location is having a lot of white space, revamp the patient detail page to a better UI
- [ ] the heading in the tab is sample test history, change it to patient detail

**Comment by cp-Coder** [comment]
@patelaryan7751 I am able to reproduce the error. Try this [url](https://care.coronasafe.in/facility/551f9e09-04a3-4f52-ade2-1db45588741d/inventory/add)
