### ISSUE TITLE
Revamp Shifting Detail UI

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2856]
![24](https://user-images.githubusercontent.com/57055998/175662855-9b73c0e6-d7c3-44ad-8d53-f076cce90218.jpg)
![24a](https://user-images.githubusercontent.com/57055998/175663182-2285af8b-8240-44a2-ab52-6b19d09a91d4.jpg)

- [ ] Details of the patients in the shifting detail page looks so bulky
- [ ] there is unwanted wait space in the area

**Comment by anuran-roy** [comment]
![image](https://user-images.githubusercontent.com/76481787/176905621-953adc47-13b6-42cd-aa89-5642231d00a4.png)
![image](https://user-images.githubusercontent.com/76481787/176909527-18c167c9-b3c0-406f-83d9-628d02332669.png)


@nihal467 Are these what the changes should look like?

**Comment by nihal467** [comment]
@anuran-roy keep the last updated on and record created at in same line

**Comment by anuran-roy** [comment]
Alright! On it!

**Comment by anuran-roy** [comment]
![image](https://user-images.githubusercontent.com/76481787/177033360-358d013d-b8c1-4ee0-a125-a1218ffcf5e4.png)

**Comment by nihal467** [comment]
![23](https://user-images.githubusercontent.com/57055998/177046862-ae3a4892-efa5-4404-9abf-a0f4dc61d0f8.jpg)

@anuran-roy this one still look bulky, can we do something about it

**Comment by nihal467** [comment]
closing this issue, since, more detailed, issue will be made later
