### ISSUE TITLE
Revamp Sample History Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2879]
![37](https://user-images.githubusercontent.com/57055998/175763523-a23d94a7-8da4-4b50-998b-56796a149b2d.jpg)

the left side look like a mess with lot of data and right side look so empty

**Comment by Ritesh-Aggarwal** [comment]
Would it be okay to render the cards in a grid of 2 columns, and change the card UI accordingly? or is the full length of card necessary?
