### ISSUE TITLE
Shifting Filter's Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2886]
![40](https://user-images.githubusercontent.com/57055998/175766395-aec11d03-9ad0-49c9-a2fc-2009895fa9ea.jpg)

the filter is the shifting side, is showing this type of data

**Comment by gigincg** [comment]
@nihal467 As explained in https://github.com/coronasafe/care_fe/issues/2890 These are actual facilities created for testing
