### ISSUE TITLE
External Results : Issue in Error Message

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2888]
![42](https://user-images.githubusercontent.com/57055998/175766733-dee14de3-bd18-420b-b137-71693afbeb51.jpg)

this error is not understandable from a user perspective, so make it a proper alert

**Comment by aeswibon** [comment]
@nihal467 I am not able to reproduce this issue too. When I try to upload any incorrect file, this error popup appears:
![image](https://user-images.githubusercontent.com/77210185/177512693-3512c5cd-9146-43df-96b3-a7e02020e3d9.png)

**Comment by aeswibon** [comment]
I think this error has been fixed in the latest `develop` branch. Please do a check on your end.

**Comment by aeswibon** [comment]
Closing this issue as the error has been resolved
