### ISSUE TITLE
Drop list Malfunction : Add User

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2890]
![44](https://user-images.githubusercontent.com/57055998/175766935-0597a321-b1a8-48a3-80e7-5c43803cff4a.jpg)

the droplist of facility showing so much codes

**Comment by shivankacker** [comment]
@nihal467 it appears everything is wired correctly. These are facilities belonging to some other districts that dev district admin cannot access, and were remnants of old security checks.
Closing.
