### ISSUE TITLE
Reconcile Pulse rate and heart rate

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2941]

**Comment by shivankacker** [comment]
@aparnacoronasafe is this related to vitals?

**Comment by aparnacoronasafe** [comment]
yes @skks1212 

You are working on this right? 

You had a discussion with gigin the other day right. To rename heart-rate as pulse rate and repurpose it. 

Can you add more details of what exactly you are doing and take it forward?

**Comment by shivankacker** [comment]
@aparnacoronasafe yes I am working on this in PR #2944. Heart rate has been replaced with blood pressure. https://deploy-preview-2944--care-net.netlify.app/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/ec945e61-9336-4f82-a36d-5724e0a76367/consultation/83540278-a1ee-4c79-8f2d-501334a7d12b
