### ISSUE TITLE
Add BP to vitals

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2942]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arpancodes** [comment]
@aparnacoronasafe can we add more details to the description of this issue?

cc @gigincg

**Comment by aparnacoronasafe** [comment]
@arpancodes This is already taken care of. Thanks for bringing this to my notice. Closing the issue
