### ISSUE TITLE
!!!! Consultation Update/ Log update Not Working  !!!!

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#2943]
When trying to add  consultation update/Log update , The page is not saving.

After selecting Date&time and Round Type, The "save" button is not responding and not able to update any Parameters.
![issue in log update](https://user-images.githubusercontent.com/75214902/176437641-cbe12989-cef0-4f6c-ba91-bafd3687c875.png)

**Comment by aparnacoronasafe** [comment]
This is happening for the first log update in a consultation.

Try patient https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/938fd193-fd96-41ab-88d0-439e4d6fcd37/consultation/5c88404b-4fb0-4c01-9a10-116457b7b344
