### ISSUE TITLE
Modify Pop-up Content : Facility Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2967]
![4](https://user-images.githubusercontent.com/57055998/176989628-75ffc87d-8652-4006-9c80-da8eaa3303a0.jpg)

When we are deleting a facility with live patients, it is showing the pop-up. The functioning is proper, just change the pop-up content

**Comment by aeswibon** [comment]
@nihal467 I am not able to reproduce this error. I tried to delete this [facility](https://care.coronasafe.in/facility/baf42ae1-3159-4a53-9f26-72ca9daccc1b) but it shows this error:
![image](https://user-images.githubusercontent.com/77210185/177511054-b9ea0a42-f0a2-4cab-9cce-ca442394715c.png)

**Comment by aeswibon** [comment]
@nihal467 Can you check whether this error is still there or not??

**Comment by aeswibon** [comment]
Closing this issue as the error has been resolved
