### ISSUE TITLE
Log Update : Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2973]
![11](https://user-images.githubusercontent.com/57055998/176993537-b338fd0b-b0e5-4427-aade-73a50f4533ef.jpg)

the users details after the normal log update is missing

**Comment by Marmik2003** [comment]
similar issue: https://github.com/coronasafe/care/issues/879

**Comment by aeswibon** [comment]
@nihal467 Related backend issue has been closed today. I have also tested on this [patient](https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/cc52390c-ac8a-4af5-9806-f3df7ee1795a/consultation/7037609e-3c25-45ed-bfd8-e01c346cbd45). So closing this issue.

**Comment by cp-Coder** [comment]
@nihal467 Related backend issue has been closed today. I have also tested on this [patient](https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/cc52390c-ac8a-4af5-9806-f3df7ee1795a/consultation/7037609e-3c25-45ed-bfd8-e01c346cbd45). So closing this issue.
