### ISSUE TITLE
Inventory Function : Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2975]
![12](https://user-images.githubusercontent.com/57055998/177009931-b76ad66b-ceb2-4e81-bfaa-0e4101b29159.jpg)
![12a](https://user-images.githubusercontent.com/57055998/177009934-313e3af4-e58e-4874-9ca2-611a88657cd0.jpg)

unable to add rice in grams

**Comment by nihal467** [comment]
@patelaryan7751 what is the status ?

**Comment by patelaryan7751** [comment]
@nihal467 yeah i checked on it it's mostly like an issue from the backend let me ask about this to Gigin in today's eod.

**Comment by patelaryan7751** [comment]
I have made an issue in the backend https://github.com/coronasafe/care/issues/925
