### ISSUE TITLE
Revamp : Resource Request Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2976]
![15](https://user-images.githubusercontent.com/57055998/177011110-2d169686-bc19-498c-a19b-8618997fc0de.jpg)

![15a](https://user-images.githubusercontent.com/57055998/177011203-a00a2036-9fdb-4ebd-8a46-8265464b071a.jpg)

- [ ] The category and subcategory box is having a lot of white space
- [ ] sub category is not fully visible
- [ ] change "is this an emergency to" yes or no option to drop list and if possible change question to a more suitable one
- [ ] the drop list is having curve, remove the curve as it doesn't feel good for the UI

**Comment by aeswibon** [comment]
Similar issue #3546 was opened and fixed
