### ISSUE TITLE
Filter Malfunction : Patient Tab

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2981]
![19](https://user-images.githubusercontent.com/57055998/177014768-eb956928-4bcf-4b67-83b8-b970dcee62f4.jpg)

when we apply all the filters, there is a error pop up coming

**Comment by Ashesh3** [comment]
This is happening due to the "Last admitted to" filter.

Related: https://github.com/coronasafe/care_fe/issues/2642

**Comment by nihal467** [comment]
it is getting addressed in the issue #3953
