### ISSUE TITLE
Readmit Malfunction : Patient File

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2984]
![3](https://user-images.githubusercontent.com/57055998/177027522-db4b376f-a61a-4124-996a-9e450fcefc5b.jpg)

Once we readmit a patient to the same facility, the medical history initially entered is missing after readmitting.

**Comment by Ashesh3** [comment]
@nihal467 I am unable to replicate this issue.

1. Discharged patient from facility A,
![image](https://user-images.githubusercontent.com/3626859/184008617-6edf8a0f-297b-48ba-8376-20bda2d4628d.png)

2. Readmitted the patient to facility A,
![image](https://user-images.githubusercontent.com/3626859/184008676-d1fbd1b9-9a0e-44f7-9f2e-8a07ad35f277.png)

The medical history is preserved for me here.

Edit Patient details (after readmitting):

![image](https://user-images.githubusercontent.com/3626859/184008785-405198fd-fa5d-4833-a2fe-53898f9a6200.png)

**Comment by Ashesh3** [comment]
@nihal467 Any info on this?

**Comment by Ashesh3** [comment]
@nihal467 I messaged you on Slack and Zoom regarding this, have you got a chance to look into this issue?

**Comment by nihal467** [comment]
@Ashesh3 sorry, looking it right now

**Comment by nihal467** [comment]
@Ashesh3 the issue seem resolved, you can close it

**Comment by Ashesh3** [comment]
> @Ashesh3 the issue seem resolved, you can close it

Great! Thanks for letting me know.
