### ISSUE TITLE
Discharge Summary : Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2991]
![8](https://user-images.githubusercontent.com/57055998/177032582-fa50fb19-33a7-4cad-a900-91de586f3ea0.jpg)

the discharge summary is not been receiving in the particular mail id

**Comment by kunatastic** [comment]
I am unable to reproduce this issue. Can you provide more details

**Comment by nihal467** [comment]
the issue is been resolved, and the discharge summary is working fine now
