### ISSUE TITLE
Revamp: Discharge Patient UI

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2998]
![19](https://user-images.githubusercontent.com/57055998/177045059-280a54f9-5b76-4d57-bf12-c29244034629.jpg)

the UI looks good when we have the patient live but discharge patient UI looks like a mess, is there a way to revamp the UI only for discharge patient

**Comment by arpancodes** [comment]
@nihal467 are there any special points for this? like any idea how should the UI look like for a discharged patient?

**Comment by nihal467** [comment]
UI looks good now, the issue looks irelevant
