### ISSUE TITLE
Improve consistency of page margins

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#3032]
![image](https://user-images.githubusercontent.com/23238460/177719878-b25345e2-5a19-4adf-9ebc-7d1b4edc4f3a.png)
![image](https://user-images.githubusercontent.com/23238460/177719951-78534ae0-4ccb-4f13-b2da-e47a3d881535.png)

**Comment by aeswibon** [comment]
@skks1212 These changes will be made in PR #2836
