### ISSUE TITLE
features selection : Facility Create Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3041]
https://www.loom.com/share/8eb24900d45742f3b18e7f18a7217045

when we are selecting features, the drop list keep on jumping from top to down

**Comment by shivankacker** [comment]
We will be shifting the form to use Tailwind UI soon, so hopefully the issue will not persist.

**Comment by nihal467** [comment]
@skks1212 when we will be shifting it

**Comment by nihal467** [comment]
it is getting resolved in #3977
