### ISSUE TITLE
Unable to create facility 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3042]
https://www.loom.com/share/73898828da284685bcbdbd8d068923b8

the facility is not getting created, ( Request Approval Center )

**Comment by khavinshankar** [comment]
@nihal467 @cp-Coder  probably a backend issue, when we choose districts other than Ernakulam, this is happening

**Comment by nihal467** [comment]
@cp-Coder any update on this !

**Comment by aeswibon** [comment]
@nihal467 I have figured out the problem and also the solution for it. I just have to confirm one thing with gigin before proceeding.

**Comment by aeswibon** [comment]
Closing this issue as user is now not able to create facility in another district
