### ISSUE TITLE
File Preview : Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3060]
![10](https://user-images.githubusercontent.com/57055998/178016468-616404d9-8f8c-4fae-ab93-2313d6a8ad04.jpg)

when we upload a PDF, the preview doesn't work, we can only download it

**Comment by aeswibon** [comment]
@nihal467 Can you share the URL where this error is occurring?

**Comment by aeswibon** [comment]
I have tested on this [patient](https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/b836f81a-0031-48a3-bb1a-63b6cba35d23/consultation/41ba3258-12c3-444e-b471-6ea53909dd11/files) and there I was able to preview the pdf

**Comment by nihal467** [comment]
@cp-Coder https://care.coronasafe.in/facility/ee6d73a9-ac6e-4b80-a370-abce9e41d159/patient/25ea51b1-fedc-432a-a9df-9071a07862c6/consultation/1999ef08-edcd-455d-91a9-68c401209c3e/files

**Comment by adonisDark** [comment]
@nihal467 The file preview is working fine on the link you provided. 

https://user-images.githubusercontent.com/91700593/193400263-74862ab0-55b1-4e37-a439-c87f3b9add2e.mp4

**Comment by khavinshankar** [comment]
The file preview seems to be working fine
![image](https://user-images.githubusercontent.com/29787772/193401374-11947211-6d31-4594-bd7d-d9ff1ecb6c96.png)

If this issue persists, feel free to create a new issue or reopen this.
