### ISSUE TITLE
Bed Management : Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3076]
![17](https://user-images.githubusercontent.com/57055998/178098506-f5c2a30e-5e5d-4578-9895-1a1df4f58067.jpg)

Unable to update bed management

**Comment by Pranshu1902** [comment]
@nihal467 I am unable to reproduce the error. You have given both the beds the same name, probably that's the reason it's failing.

**Comment by nihal467** [comment]
@Pranshu1902 yeah, it is due to same bed name in same location, you can close this issue
