### ISSUE TITLE
Styling Issue : Hemodynamic Parameters

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3083]
![22](https://user-images.githubusercontent.com/57055998/178100089-0385abcd-5578-4818-bbdd-7509e49cdfae.jpg)

- [ ] make textbox border color from blue to green, when we are clicking it
- [ ] the content is coming in bold, make it a normal text like other text boxes

**Comment by Pranshu1902** [comment]
@nihal467 please share the url

**Comment by aeswibon** [comment]
@Pranshu1902 This is the URL: [Hemodynamic Parameters](https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/c3e588d5-583f-4711-907b-e3d46fb914cf/consultation/b20d8c85-51b6-4835-b729-db216b1e8190/daily_rounds/cc599a99-3e49-4f29-a97c-005d55f463f6/update)
