### ISSUE TITLE
I/O Balance Editor Styling Issue

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3084]
![23](https://user-images.githubusercontent.com/57055998/178100183-10a620ad-1b8d-467e-8fb5-f41626b11def.jpg)

in all the fields under the value, change from blue to green border. and it is coming everywhere else too, in nursing care, etc..., can we globally make all text box is been click in the critical care, rather than blue border, a green border comes up

**Comment by patelaryan7751** [comment]
I am working on this issue it will be completed by this week itself.
