### ISSUE TITLE
File Upload : Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3086]
![24](https://user-images.githubusercontent.com/57055998/178100421-30c6202a-4323-43bf-a109-da65e39f246c.jpg)

the file name is not marked mandatory, and when we submit it, the popup comes in

**Comment by patelaryan7751** [comment]
@nihal467 shall I add a "*" to show it's mandatory or make the "Enter File name" field optional?

**Comment by nihal467** [comment]
@patelaryan7751 add a '*', as it is mandatory and put a validation that, when a person click upload, under the text box, a error statement comes like the field is mandatory or something
