### ISSUE TITLE
Captcha not working : Unable to Login

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3092]
![27](https://user-images.githubusercontent.com/57055998/178101661-5b27aec4-f029-4e2a-9d79-6ed26bb4ab61.jpg)

captcha is not working in staging and unable to login to staging

**Comment by Ashesh3** [comment]
@nihal467 It seems related to https://github.com/coronasafe/care_fe/pull/2946#issuecomment-1172863289

@gigincg Could you or anyone else having the Recaptcha admin account take a look into the Recaptcha Admin panel and check if `care.coronasafe.in` is added as an allowed domain and also make sure that the below sitekey is valid?

The sitekey used is here: https://github.com/coronasafe/care_fe/blob/develop/src/Common/env.tsx#L1

**Comment by Ashesh3** [comment]
@nihal467 This should be fixed in https://github.com/coronasafe/care_fe/commit/63e2ffa0a6f98c9f4fb530ecafd4d509ba36489e

![image](https://user-images.githubusercontent.com/3626859/178362849-42c01541-14dd-4c1a-9bcc-96c4e807bbdf.png)
