### ISSUE TITLE
Discharge not working

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3101]
![5](https://user-images.githubusercontent.com/57055998/178237343-52867842-576b-4654-b0f8-692cfed5f5b6.jpg)

unable to discharge a patient

**Comment by nihal467** [comment]
@Ashesh3 status ?

**Comment by Ashesh3** [comment]
@nihal467 This is due to https://github.com/coronasafe/care_fe/pull/2947 not being merged even though the backend change for the same was recently merged and is live.

Merged backend PR: https://github.com/coronasafe/care/pull/902
