### ISSUE TITLE
Password Reset : Malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3120]
![3](https://user-images.githubusercontent.com/57055998/178906084-27f29b6d-7b00-458b-be69-ea07c9914d3b.jpg)

the link received for resetting a user password at email is not working properly

**Comment by developedBySJ** [comment]
@nihal467 can you elaborate?

**Comment by patelaryan7751** [comment]
@developedBySJ this page is displayed when the password reset link expires so I think he was talking about the UI. Because the reset password functionality is working perfectly.

**Comment by developedBySJ** [comment]
@patelaryan7751 Instead of 404 It should redirect to the login page and display an error message.

@nihal467
