### ISSUE TITLE
Facility become unavailable

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3127]
https://www.loom.com/share/580184ac24904cdfa7ebe4417abba0ab

we save the data without ward, the whole facility becomes unavailable

**Comment by nihal467** [comment]
@cp-Coder @khavinshankar  what is the status?

**Comment by aeswibon** [comment]
@nihal467 In the video, the updated facility district is not the same as the user's district. Currently, the user is only able to view their district's facility. That's why the facility becomes unavailable.

**Comment by cp-Coder** [comment]
I have created a backend PR to prevent saving the form if the updated facility district is not the same as the user's district

**Comment by aeswibon** [comment]
I have created a backend PR to prevent saving the form if the facility district is not the same as the user's district

**Comment by aeswibon** [comment]
Similar to #3042
