### ISSUE TITLE
Resource Page : Badges Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3133]
![image](https://user-images.githubusercontent.com/57055998/179156496-aeb8cbff-0395-47ae-8156-462314b20e1d.png)

after click the clear filters, the badges are not been removed

**Comment by aeswibon** [comment]
@nihal467 I am not able to reproduce this error??

https://user-images.githubusercontent.com/77210185/179167496-ca182844-150b-4dc9-ad26-e05effb3ba15.mp4

**Comment by nihal467** [comment]
@cp-Coder this issue is resolved, you can close this issue

**Comment by aeswibon** [comment]
Closing this issue as the issue has been fixed
