### ISSUE TITLE
Resource & Shifting Page : Revamp List View

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3135]
![image](https://user-images.githubusercontent.com/57055998/179157364-5eaebd5e-448d-4cf8-8601-02a32ae7c8eb.png)

![image](https://user-images.githubusercontent.com/57055998/179157465-29581458-280e-446b-a5bf-4f7e21c3fc93.png)

make the header with active, complete patients and filters, etc. with the same alignment to the list view as it is in the board view for both shift and resource page

**Comment by aeswibon** [comment]
Fixed in #2836
