### ISSUE TITLE
Remove user id from droplist : Patient Creation Form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3140]
![image](https://user-images.githubusercontent.com/57055998/179197961-5e7404f9-fe4f-4022-83c6-1268a99024ca.png)

hide the user id and display only the name

**Comment by aeswibon** [comment]
@nihal467 Can you tell me more details on this issue? Can you record and share the video?

**Comment by aeswibon** [comment]
@nihal467 I was able to find the issue and was able to fix the issue.
