### ISSUE TITLE
modify : bed management

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3144]
![image](https://user-images.githubusercontent.com/57055998/179207597-f4f32e82-0538-4e85-921e-33504529760a.png)

changed the colour of the edit button to the one similar to the location management

![image](https://user-images.githubusercontent.com/57055998/179207969-6852feae-1539-4043-85e3-fd69f2c6ee57.png)

**Comment by naman114** [comment]
@nihal467 The buttons have been updated in PR [#2903](https://github.com/coronasafe/care_fe/pull/2903)
It was merged yesterday. You can hard refresh your browser window to see the changes.

https://care.coronasafe.in/facility/551f9e09-04a3-4f52-ade2-1db45588741d/location/4b9231cf-805d-4fc3-ab23-77e4d8bfba03/beds

![image](https://user-images.githubusercontent.com/57593654/179210372-5f51a847-5610-4024-aa5a-e87631d6f8ea.png)

**Comment by aeswibon** [comment]
@nihal467 The issue has been fixed
