### ISSUE TITLE
Sample Test : Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3147]
https://www.loom.com/share/ad180208a8b645b8a68a81712d6a7a13

when we click the ICMR form, something wrong error popping up

**Comment by Ashesh3** [comment]
Duplicate of https://github.com/coronasafe/care_fe/issues/2440 ?

**Comment by aeswibon** [comment]
@Ashesh3 Yes it was the duplicate of #2440
