### ISSUE TITLE
Hide used bed : Switch function

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3149]
![image](https://user-images.githubusercontent.com/57055998/179217495-08ef0ae3-cb53-4f4b-bfee-525f7d072a26.png)

when we have a bed allotted to a patient, hide it from the switch bed droplist

**Comment by aeswibon** [comment]
Waiting for backend PR coronasafe/care#939 to be merged

**Comment by aeswibon** [comment]
Fixed by coronasafe/care#1082
