### ISSUE TITLE
Expand Facility Type

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3166]
In the facility registration and update form, https://care.coronasafe.in/facility/3447b03d-7522-4525-9e14-58d7628b1e9e/update

There is a field for facility type. Add the options
- Co-operative hospitals
- Autonomous healthcare facility

**Comment by nihal467** [comment]
Removing stale as a PR is already been linked to the issue

**Comment by mathew-alex** [comment]
Working in [deploy preview](https://deploy-preview-4117--care-egov-staging.netlify.app/)

![Screenshot 2022-11-25 at 9 35 41 PM](https://user-images.githubusercontent.com/22002072/204022146-2dfcf409-951b-4c3d-a3c9-45ca688e314c.png)

**Comment by nihal467** [comment]
the issue is resolved
