### ISSUE TITLE
Resource Page : Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3168]
![image](https://user-images.githubusercontent.com/57055998/180003240-f42db607-cb97-4de4-b08a-b290ebe51538.png)
![image](https://user-images.githubusercontent.com/57055998/180003654-835a33fc-d983-4518-9fbe-685fa5a27f03.png)

when we have there is no patient, the resource tab is blank and crashing

**Comment by aeswibon** [comment]
@nihal467 I am not able to reproduce this error?

https://user-images.githubusercontent.com/77210185/180060822-307faa67-2af4-4e37-b60d-4ea98e4e1dd1.mp4

**Comment by Ritesh-Aggarwal** [comment]
Issue is not reproducible 


<img width="1120" alt="image" src="https://user-images.githubusercontent.com/57039447/182864839-ebb4bc06-82b6-4e28-8cdf-ee46f7fd8789.png">

**Comment by gigincg** [comment]
@nihal467 Can you respond to these

**Comment by nihal467** [comment]
@Ritesh-Aggarwal the issue seems resolved, can you close the issue
