### ISSUE TITLE
Adding Procedure to Consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3195]
In the consultation form (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce/update), there needs to be a section for Procedures.

Suggestive design:
<img width="665" alt="Screenshot 2022-07-22 at 5 15 49 PM" src="https://user-images.githubusercontent.com/67050716/180432850-8f783f01-23be-4cff-99ee-96b28d276007.png">

Content:
1. Repetitive: Toggle button for Yes/No
2. If repetitive, field for "Frequency" with dropdown  [ 15 min, 30 min, 1 hr, 6 hrs, 12 hrs, 24 hrs ]
    If not repetitive "Time and Date" to capture the time and date of the procedure
3. Procedure: Text field to accommodate 100 characters to describe the procedure
4. Note: Text field to accommodate 100 characters to add a note

**NOTE:** Earlier we had a simple text field in the consultation form for "Operations". It was later on taken off by https://github.com/coronasafe/care_fe/pull/2900. The same operation field may be used here for the Procedure

This section is to come after the Prescription/PRN Prescription Section

**Comment by Ritesh-Aggarwal** [comment]
this section has to be like prescription section where more than one procedure can be added, right?
