### ISSUE TITLE
Shifting Malfunction : Unable to Update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3263]
![image](https://user-images.githubusercontent.com/57055998/181857518-a419683f-7236-4bf0-9fdb-3fda72abce10.png)

When we are updating KASP as YES and save it, the form is not being getting submitted

**Comment by siddnikh** [comment]
@nihal467 can't reproduce the issue. Can you direct?

**Comment by nihal467** [comment]
issue resolved
