### ISSUE TITLE
Redesign Patient UI

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3268]
![image](https://user-images.githubusercontent.com/57055998/181908908-a4a4fafd-e709-4974-892a-159b0a52365b.png)

it is hard for a normal user to understand the below icons (investigation summary, shift patient, etc... ) are buttons or icons only, so we need to redesign the UI to a normal one 

**Note**: Whoever going to work on this, discuss it on EOD call or slack channel about the idea of design approach going to take and discuss with the team, finalize one and start coding it.

**Comment by nihal467** [comment]
@gigincg can you get a opinion from a designer to revamp the page

**Comment by gigincg** [comment]
@nihal467 This isn't ready for a UI Design Stage right now. @aparnacoronasafe Is discussing with doctors to get input on Product Design, once that information is added to this issue, it can be taken up for UI Design
