### ISSUE TITLE
Assign to Volunteer : Malfunction in Patient Detail

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3272]
![image](https://user-images.githubusercontent.com/57055998/181996990-1171add9-a679-4552-a60a-6bb448c7d033.png)

steps to reproduce 

1. assign a volunteer to a patient and discharge the patient
2. readmit the discharged patient to a new facility, and you can see, that the previously assigned volunteer remains there itself

**Comment by Ashesh3** [comment]
@nihal467 The expected behaviour here would be that  the volunteer is unassigned when the patient is discharged, is that correct?

**Comment by nihal467** [comment]
@Ashesh3 yes, correct
