### ISSUE TITLE
Bed Assign Malfunction : Consultation Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3274]
https://care.coronasafe.in/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/c4c9bddc-8764-463c-a0fd-dc3c6a322e04/consultation/78c3d426-9e2e-477a-9e1a-a17e62953004

![image](https://user-images.githubusercontent.com/57055998/182001781-e8e987df-482c-45ac-81dc-d3f55f0fa4d3.png)

![image](https://user-images.githubusercontent.com/57055998/182001709-3e217279-8ce0-4cb2-ace7-27cb0ae1de2b.png)

- [ ] the patient is already assigned to bed 2, but when we click update consultation details and check it, we can't see the bed in there 
- [ ] when we are submitting the consultation by selecting an already in-use bed in the consultation form, it is getting accepted

**Comment by cp-Coder** [comment]
Opened a backend issue coronasafe/care#1047
