### ISSUE TITLE
Link to new facility Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3276]
![image](https://user-images.githubusercontent.com/57055998/182003563-8a859512-020b-4a28-b2e3-c362877763ce.png)

a district admin of a particular district should be seeing only users of that district, while we are trying to link an ID to a facility

**Comment by patelaryan7751** [comment]
@nihal467  he would be seeing the facilities of that particular district. Right?

**Comment by aeswibon** [comment]
@patelaryan7751 Yes

**Comment by patelaryan7751** [comment]
Issue is resolved in staging
