### ISSUE TITLE
User Creation Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3285]
![image](https://user-images.githubusercontent.com/57055998/182107197-f9b60502-e908-42ab-8c7d-38d40a2838b9.png)

we can't create an id which was once deleted from the care

steps to reproduce:

1.  delete a existing user
2.  try to create a new user with the same user name and this error occurs

**Comment by nihal467** [comment]
@skks1212 it is an expected behavior to show an error when we create a username already been created and deleted from care as we are only soft deleting the user, so can you reconfirm that with @gigincg and revamp the notification, so that the user also understands the username is not available or something which is more meaningful

**Comment by Pragati1610** [comment]
Can we close this issue if it is resolved? @nihal467
