### ISSUE TITLE
Unable to configure camera

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3287]
![image](https://user-images.githubusercontent.com/57055998/182113708-6d47dab7-7dde-45fd-a7af-afd848a40d4d.png)

with staff id, unable to configure a camera

**Comment by Pragati1610** [comment]
@nihal467 could you elaborate on how to reproduce the problem?

**Comment by nihal467** [comment]
@Pragati1610 It is resolved now! You can close it
