### ISSUE TITLE
Redirection is malfunction inside log update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3304]
**Describe the bug**
When we are clicking the back button in the normal round, it is been redirected to critical care

**To Reproduce**

1. Go to consultation page
2. Click on log update button
3. Select `Yes` for copying from the previous log, and click Save.
4. in the bottom, click on the back button
5. See an error

**Expected behavior**

it should be redirecting to consultation page rather than critical care

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/182574515-866bc2a7-4fb7-4aeb-aad8-9a5a74ac1ce7.png)

**Comment by Ashesh3** [comment]
@nihal467 Hey, I am unable to replicate this issue. Could you check if this issue is still present?

![](https://user-images.githubusercontent.com/3626859/182908820-21bb025a-b938-4d01-aef7-ad64c08f1ca5.gif)

**Comment by arpancodes** [comment]
@Ashesh3 the issue is there, I think @nihal467 missed one step, edited the description.
Also, refer to this:
![redirection error](https://user-images.githubusercontent.com/42417893/184260805-580d6ba6-50e1-44ba-89a8-b42122e5c9f9.gif)

**Comment by Ashesh3** [comment]
> @Ashesh3 the issue is there, I think @nihal467 missed one step, edited the description. Also, refer to this: ![redirection error](https://user-images.githubusercontent.com/42417893/184260805-580d6ba6-50e1-44ba-89a8-b42122e5c9f9.gif)

Thanks for the clarification!
