### ISSUE TITLE
Limit District Admin Access in new user page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3308]
**Describe the bug**

currently, the district admin can see all the hospitals in care with no restrictions as the district, state, etc...

**To Reproduce**

Click on the add user, go to facilities, type a name, and you will see the list of all facility

**Expected behavior**

the district admin should be able to see only facilities which are in the district alone. for example, a district admin of Ernakulam should be seeing the facilities which are only in Ernakulam

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/182639587-ad752b15-2fa5-4f4b-b3cf-2dd980790bff.png)

**Comment by nihal467** [comment]
@cp-Coder it is an urgent issue, work on it ASAP

**Comment by aeswibon** [comment]
@nihal467  Okay
