### ISSUE TITLE
Removing "Contact with confirmed carrier" label from patient list

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3325]
Is your feature request related to a problem? Please describe.
Earlier we had a field to collect data on whether a patient has had confirmed contact with a covid patient etc . As the focus shifted from pandemic management to TeleICU, the field was taken off. However, the patient list still has the label "Contact with confirmed carrier"
https://care.coronasafe.in/patients
<img width="1309" alt="Screenshot 2022-08-05 at 12 43 30 PM" src="https://user-images.githubusercontent.com/67050716/183022782-91f7a61f-bc2d-4b2d-9bfb-365ab0a0e01f.png">

Describe the solution you'd like
Remove the label

Describe alternatives you've considered

Additional context

**Comment by Ashesh3** [comment]
@aparnacoronasafe PR https://github.com/coronasafe/care_fe/pull/3318/ already fixes this issue! Linked this issue to said PR.😄

**Comment by gigincg** [comment]
Update based on review.

Instead of removing the badge/label altogether, hide the Negative Badge, Maintain the Badge when the Patient is Positive

**Comment by aparnacoronasafe** [comment]
@gigincg contact tracing for covid has become a thing of the past. Therefore, even though i recommend keeping the covid positive label, i do not support having the label for "contact with confirmed carrier"

**Comment by gigincg** [comment]
@aparnacoronasafe Only the COVID Positive Badge is retained. The following are being removed

 - Contact with confirmed carrier
 - Contact with suspected carrier
 - Recovered
 - Negative

**Comment by Ashesh3** [comment]
> @aparnacoronasafe Only the COVID Positive Badge is retained. The following are being removed
> 
> * Contact with confirmed carrier
> * Contact with suspected carrier
> * Recovered
> * Negative

That's correct, the current PR only retains the COVID Positive Badge.

**Comment by aparnacoronasafe** [comment]
@Ashesh3 That's great.
