### ISSUE TITLE
Unable to delete facility with state admin privileage

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3329]
![image](https://user-images.githubusercontent.com/57055998/183070090-e35e724b-992e-44ef-93e0-07bef421f314.png)

am unable to delete an empty facility that has no patient using a state admin privilege. 

Expected behavior:

State admin should be having the privilege to delete a facility

**Comment by nihal467** [comment]
@cp-Coder what is the update on this !

**Comment by aeswibon** [comment]
I have opened the backend PR regarding this. Waiting for it to be merged.

**Comment by aeswibon** [comment]
The issue has been fixed
