### ISSUE TITLE
Allergies: to be added to health details

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3332]
Note: #3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

- [ ] Health details must contain a toggle button (Yes/NO) for "Allergies".  Default selection to be NO

- [ ] If selected "Yes"- a short text box must appear for description.
NOTE: A short text box for allergies already exists in the Medical History section. The same may be moved and used here. 

This shall be placed as the first field in Health details

- [ ] Wherever allergy is selected to YES, make the allergy details appear on patient dashboard (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0) below diagnosis.

- [ ] Create a label for allergies to appear in the patient list

@gigincg to review
Issue is part of #2218

**Comment by aparnacoronasafe** [comment]
A quick clarification on the content of the Patient registration form and consultation form
<img width="932" alt="Screenshot 2022-08-12 at 5 22 32 PM" src="https://user-images.githubusercontent.com/67050716/184351022-bb886b89-e4b3-45c1-b0e2-6e15148ceccb.png">

**Comment by nihal467** [comment]
@aparnacoronasafe do check this and comment on it

**Comment by nihal467** [comment]
@cp-Coder Due to inactivity and the existing linked PR is not mergeable, unlinking you from this issue

As per the communication with @aparnacoronasafe , it will be sub-grouped with events module, so for time-being marking the issue as blocked

**Comment by gigincg** [comment]
Closing in Favour of #8388
