### ISSUE TITLE
Vaccinations: in Health details

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3333]
Note: https://github.com/coronasafe/care_fe/issues/3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

Add a section for vaccinations. 

- [ ] The first field would be to select the type of Vaccine. The options would be "COVID", "Hep A"  "Hep B". The options may be expanded later. The user should be able to select multiple options. 
- [ ] Once a vaccine in selected, there must be the option for a dose for certain options. In this case for COVID the option of doses are going to be 1,2,and 3. For the other options, the field for dosage will not appear.
- [ ] Date of the last dose- this must appear for all options. The field for the date must accept the exact date (DD/MM/YYYY), Month and year (MM/YYYY) or even just year (YYYY)

The design of the field may mimic the prescription module where one vaccine may be entered along with details, and another row may be added to add a second vaccine. This is only a suggestion, you may use your creativity to come up with better layouts

- [ ] The information thus collected must be shown in the Patient Details Page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326) on the right side of Bloof Group below the Patient Name.

NOTE: 5 fields relating to COVID vaccines already appear in health details. The field are "Is the patient vaccinated against COVID?" "COWIN ID", "No. of doses", "Vaccine Name" and "last date of vaccination". These fields may be repurposed/ removed with this new vaccine section that covers a wider range of vaccines.

@gigincg to review
This is part of #2218

**Comment by gigincg** [comment]
@aparnacoronasafe What about the COWIN ID? We should have that as well.

@vigneshhari Opinion on Making Vaccinations a Separate Entity? Or any other suggestions

**Comment by aparnacoronasafe** [comment]
For medical purposes, COVID ID is not going to be very relevant. I checked it with Dr. Athul as well @gigincg

**Comment by aparnacoronasafe** [comment]
A quick clarification on the content of the Patient registration form and consultation form
<img width="932" alt="Screenshot 2022-08-12 at 5 22 32 PM" src="https://user-images.githubusercontent.com/67050716/184351126-ccc95f45-de80-444f-b9fa-333761255fd3.png">

**Comment by nihal467** [comment]
@cp-Coder  Due to inactivity and the existing linked PR is not mergeable, unlinking you from this issue

As per the communication with @aparnacoronasafe  , it will be sub-grouped with events module, so for time-being marking the issue as blocked

**Comment by gigincg** [comment]
Closing in Favour of https://github.com/coronasafe/care_fe/issues/8388
