### ISSUE TITLE
Height and Weight : Reposition

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3336]
Note: https://github.com/coronasafe/care_fe/issues/3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

The fields for Height and Weight fields exist in consultation.

Move the same to "Health Details"

Part of #2218 
@gigincg please review

**Comment by aparnacoronasafe** [comment]
A quick clarification on the content of the Patient registration form and consultation form
<img width="932" alt="Screenshot 2022-08-12 at 5 22 32 PM" src="https://user-images.githubusercontent.com/67050716/184350480-764cd785-a8ab-49fc-9451-7e620ac779c6.png">

**Comment by nihal467** [comment]
@cp-Coder Due to inactivity and the existing linked PR is not mergeable, unlinking you from this issue

As per the communication with @aparnacoronasafe , it will be sub-grouped with events module, so for time-being marking the issue as blocked

**Comment by gigincg** [comment]
Closing in Favour of https://github.com/coronasafe/care_fe/issues/8388
