### ISSUE TITLE
Family Details- add field in health details

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3338]
Note: https://github.com/coronasafe/care_fe/issues/3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

- [ ] As the last field in "Health Details" add a long text field for "Family Details"
The field will be non-mandatory

- [ ] Show the information in Patient details page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0) as a separate heading "Family Details" below "Medical"
<img width="1371" alt="Screenshot 2022-08-06 at 12 59 03 AM" src="https://user-images.githubusercontent.com/67050716/183147790-a3a7cf89-470e-493f-8d37-1d0eb92db3e7.png">

Issue is part of #2218 
@gigincg please review

**Comment by arpancodes** [comment]
@aparnacoronasafe according to #3341 we are renaming the "Health Details" section to "COVID specific Information", should the `Family History` field go in the same form?

**Comment by aparnacoronasafe** [comment]
@arpancodes 
<img width="932" alt="Screenshot 2022-08-12 at 5 22 32 PM" src="https://user-images.githubusercontent.com/67050716/184348616-eb6513d1-ef10-4a02-8283-0d6d62296893.png">


There are 2 forms:
1: Patient registration form to have personal details of patients and COVID specific details
2: Cnsultation form is to have Medical history, health details, consultation

**Comment by nihal467** [comment]
@cp-Coder Due to inactivity and the existing linked PR is not mergeable, unlinking you from this issue

As per the communication with @aparnacoronasafe , it will be sub-grouped with events module, so for time-being marking the issue as blocked

**Comment by gigincg** [comment]
Closing in Favour of https://github.com/coronasafe/care_fe/issues/8388
