### ISSUE TITLE
Notice Function in the facility page is unresponsive

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3340]
**Describe the bug**

the button in the notice board function is unresponsive

**To Reproduce**

1. Go to Facility page using district admin access
2. click on the notice icon
3. when the pop-up arrives, check the responsiveness

**Expected behavior**

make the pop-up responsive

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/183149012-f8d0d283-3922-4752-9674-1262d8abccb0.png)

**Comment by patelaryan7751** [comment]
https://github.com/coronasafe/care_fe/issues/3238 issue already made.
