### ISSUE TITLE
Move COVID Specific fields in Patient registration form to a section called "COVID specific Information"

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3341]
Note: https://github.com/coronasafe/care_fe/issues/3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

The following fields currently in the "Health Details section" of the Patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) must be retained in the same form at the bottom, under a collapsable section called "COVID specific Information". This section must always be minimized and the user must be able to click on the header to expand it. 

- [ ] COVID Test Type
- [ ] SRFID for COVID Test
- [ ] Is the patient declared covid positive by the state? If yes, the declaration date.
- [ ] Contact with confirmed covid patient, if yes, estimated date of contact and name/cluster of contact.
- [ ] Contact with covid suspect. Remove label for it in patient list (https://care.coronasafe.in/patients) and patient details page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0)
- [ ] COVID Disease status. 
- [ ] Date of Sample given for COVID Test. 
- [ ] Date of Result for COVID Test
- [ ] Number Of Primary Contacts for COVID
- [ ] Number Of Secondary Contacts for COVID
- [ ] Number Of Aged Dependents (Above 60)
- [ ] Number Of Chronic Diseased Dependents

issue is part of #2218 
@gigincg please review

**Comment by gigincg** [comment]
@khavinshankar Unassigned you for now. Need to discuss this first.

@aparnacoronasafe I don't see value in removing these fields. These are Details Relavant to Public Health. It is good to hide these in a collapsible section, but should not be removed. These can be ignored for all Critical Care Patients. We could even consider having a selector (COVID/Non-COVID) Which would hide these. But I'm against removing them altogether.

Let's always choose to build a flexible system with more features, than a system with a very specialized set of features

**Comment by aparnacoronasafe** [comment]
I completely agree with you on the COVID , non covid option. Lets hide it for now. 

I will work on studying the scope of creating various clinical option like covid, non covid and others 

So let's go ahead and hide it for now

**Comment by gigincg** [comment]
@aparnacoronasafe They are already hidden in a collapsible right, shall we switch the name to Public Health Details for now. We can hide them based on a select option when we can come up with that

**Comment by aparnacoronasafe** [comment]
Agreed. Edited issue to call this section "COVID Specific Details"

**Comment by arpancodes** [comment]
@gigincg @aparnacoronasafe I see the section is already collapsed by default and has all the required fields. Do we only need to rename the section?

**Comment by aparnacoronasafe** [comment]
@arpancodes 
Yes, please rename the existing section in patient registration form to "COVID Specific Info"

However, for your clarification please look at the below
<img width="932" alt="Screenshot 2022-08-12 at 5 22 32 PM" src="https://user-images.githubusercontent.com/67050716/184349491-ec8f4ede-cfb0-477e-8029-a6758f9a113e.png">

**Comment by aparnacoronasafe** [comment]
@arpancodes Family details must go to the "Health details in consultation form

**Comment by aparnacoronasafe** [comment]
@nihal467 @khavinshankar I went through the issue. It looks like this is already done. Its safe to close the issue.
