### ISSUE TITLE
Patient page buttons are not properly responsive

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#3358]
![image](https://user-images.githubusercontent.com/23238460/183504275-865ab8b6-8318-4fc0-b390-a1b3894b5722.png)

note : Make it center aligned

**Comment by Prajuwal** [comment]
Hi @skks1212 can I take up this issue if it is not yet resolved?

**Comment by shivankacker** [comment]
@Prajuwal sure you can take it up if issue has not yet been resolved.

**Comment by nihal467** [comment]
existing UI looks good, closing this issue
