### ISSUE TITLE
File Upload: Option to Achieve the file 

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3366]
All users must have the option to Archive a file upload on patients consultation (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/1b63b5b5-e1ba-4e87-878e-9c178996255a/consultation/4516faa0-77cd-4b5e-9c52-1df41fbf9090/files)

A long text field for "Reason for archiving" must appear. This must be a mandatory field.

Once achieved, the saved file must appear faded, with an "Archived" label. The reason for archiving must also appear prominently there.

Any user will have the option to Unarchive a file upload. But such an unarchived file must still have the text "Archived by * username * for *r eason for archiving *"

**Comment by aparnacoronasafe** [comment]
An archived file should not be downloadable

**Comment by patelaryan7751** [comment]
The backend issue https://github.com/coronasafe/care/issues/1051 is tracked here

**Comment by patelaryan7751** [comment]
Filed for adding reason is been tracked here https://github.com/coronasafe/care/issues/1054
