### ISSUE TITLE
Change external results view from table view to card view

### ISSUE THREAD

**Issue by kunatastic** [coronasafe/care_fe#3371]
On mobile devices viewing the table data can be difficult, which can be improved if we use a card view

![image](https://user-images.githubusercontent.com/61267953/183972138-1799ff4a-ec46-442f-bbc0-0d07f715bb62.png)

URL: https://care.coronasafe.in/external_results

**Comment by siddnikh** [comment]
@kunatastic hey, are you working on this?

**Comment by nihal467** [comment]
This seems to be unnecessary from an operational perspective
