### ISSUE TITLE
Setup crowdin for internationalization

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care_fe#3377]
It would be nice to use a tool like crowdin to manage the translations.

**Comment by comradekingu** [comment]
Happy to help if you use Weblate.
Crowdin is a non-starter.

**Comment by khavinshankar** [comment]
done, @comradekingu closing this issue now, feel free to open a new issue

**Comment by comradekingu** [comment]
Just to be clear. The guy downvoting is a Crowdin Maintainer,
that pretends Crowdin is open source. (It isn't.)
![Image](https://github.com/user-attachments/assets/a37afbd5-8a37-4e95-8586-5ef3fec857a0)
