### ISSUE TITLE
Patient search page is not responsive

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#3388]
**Describe the bug**
The "Add Detail" button cuts off from right, on smaller screens.

**To Reproduce**

1. Go to Patients page
2. Set the width to anywhere between 1000px - 1300px
3. The "Add Detail" button is cropped out of the view.

**Expected behavior**
The button should resize or reposition.

**Screenshots**
![image](https://user-images.githubusercontent.com/3626859/184357512-6b207be1-4392-47c0-85b9-eb36b6a3a404.png)

**Comment by GokulramGHV** [comment]
@Ashesh3 This issue is being fixed in #3295
