### ISSUE TITLE
Make the Location Management page in Facility Section responsive

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3391]
**Describe the bug**

the location management bed in a facility page is not responsive

**To Reproduce**

1. Go to any facility page
2. Click on location management and switch to mobile view
3. See an error

**Expected behavior**

make the page responsive

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/184472201-88dd5937-10a4-4a08-96eb-e7450cd1a37b.png)

**Comment by Ashesh3** [comment]
Bed Management has the same issue. 

![image](https://user-images.githubusercontent.com/3626859/184544999-4b6a6b3a-17dc-4a11-b0ed-bc1aaf21e589.png)
