### ISSUE TITLE
Revamp Create Consultations Page

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#3392]
https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation

Improve spacing
![image](https://user-images.githubusercontent.com/70687348/184472368-ad816a2d-a7af-4ff9-bf3c-ad84b05e45d9.png)

![image](https://user-images.githubusercontent.com/70687348/184472374-3cd8f6e0-36b1-4bdd-8175-be8a7a66e23f.png)

**Comment by patelaryan7751** [comment]
duplicate issue https://github.com/coronasafe/care_fe/issues/3148
