### ISSUE TITLE
Camera configuration is not working

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3394]
**Describe the bug**

currently, unable to configure a camera using the staff-id, the below error keeps on popping up and also the camera type field becomes unselected 

**To Reproduce**

1. Go to any facility
2. Click on view assets and click on the configuration
3. Fill out the camera configuration and submit it
4. See the  error

**Expected behavior**

we should be able to configure the asset with camera details

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/184474856-99586cb9-7ac9-4df6-9789-b9c4c24537df.png)

**Comment by gigincg** [comment]
Could not reproduce,

Configured the asset specified in the Screenshot
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/13028584/184476371-c6d52709-8af1-4c1d-80bb-ed914b37181c.png">
