### ISSUE TITLE
Discharge summary pdf file not openning after download

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#3411]
**Describe the bug**
When we try to open discharge summary sent in the mail it displays an error message "Failed to load pdf"

**To Reproduce**

1. Go to any Patient's dashboard
2. Click on discharge summary
3. Enter your email id
4. Recieve the mail and open the attachment
5. see error

**Expected behavior**
The pdf should open

**Screenshots**
![image](https://user-images.githubusercontent.com/59426397/184796683-51f1ddff-8b14-4fff-8db1-7165032a9f7c.png)

**Comment by khavinshankar** [comment]
@patelaryan7751 It seems to be working at my end, maybe can you give the link of the patient for whom it was not working at your end, I'll check it out

![image](https://user-images.githubusercontent.com/29787772/184810638-c51fd866-4323-44e0-8657-d4b325321a09.png)

**Comment by khavinshankar** [comment]
Closing this issue as this seems to be working fine, feel free to reopen or create a new issue if the same exists
