### ISSUE TITLE
Assigning home facility

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3413]
**Is your feature request related to a problem? Please describe.**
We have distributed access to create user in CARE so that a central admin need not be placed to take care of user onboarding. The idea is that The district admins would onboard 1 staff at hospital 01. Subsequently, the staff at hospital 01 would be able to onboard all other users in that hospital. 

Now, that we have introduced the concept of Home Facility, even though the distributed model of onboarding users still works, however, there is need for the district admin to assign home facilities. This goes against the decentralised operation model. 

**Describe the solution you'd like**
Allow users (Staff and doctors) with homes facility access to hospital 01 to give home facility access to other users. 
NOTE: Only the users with home facility access will be able to grant home facility access to that hospital to other users.

**Describe alternatives you've considered**
-

**Additional context**
Currently in our Manipur live deployment, since the number of users is only close to 100, the district admin centrally assigned home facility to all users. That may not be practically possible once the number of users grow

**Comment by aparnacoronasafe** [comment]
@vigneshhari @gigincg

**Comment by gigincg** [comment]
Staff can create users with their own home facility as home facility. Manipur needed District Admin intervention for migration existing users. I don't see the need for such an intervention in the future

**Comment by gigincg** [comment]
@aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
> Staff can create users with their own home facility as home facility. Manipur needed District Admin intervention for migration existing users. I don't see the need for such an intervention in the future

@gigincg tested in staging. Currently staff is unable to assign home facility 
@nihal467 can you please test too

**Comment by nihal467** [comment]
@aparnacoronasafe 

- existing staff can't choose their home facility or assign home facility to another staff user.
- existing staff user with home facility assign to them, can create a new user of same home facility access.

**Comment by aparnacoronasafe** [comment]
Thanks Nihal. 

@gigincg point 1 above

**Comment by Ashesh3** [comment]
@gigincg Seems like intentional behavior. Does this issue still apply?

**Comment by Ashesh3** [comment]
@gigincg Any updates on this?

**Comment by gigincg** [comment]
@aparnacoronasafe Please make a different issue if you need any additional Tweaks :)
