### ISSUE TITLE
Minor UI fixes in mobile view

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#3414]
- Make `Advanced filter` button full width
![image](https://user-images.githubusercontent.com/70687348/184820182-16f456f0-29fb-42ca-b379-bd1760dad558.png)

- Make `Set Configuration` button full width
https://care.coronasafe.in/assets/03410307-ecaa-4db7-b040-a3a4d4dd0b80/configure
![image](https://user-images.githubusercontent.com/70687348/184820303-1d7e238f-bf4e-4568-b8eb-2719e53de877.png)

- Improve spacing between buttons on facilities page
![image](https://user-images.githubusercontent.com/70687348/184820444-c74a6e80-1830-41c5-9d85-7ee5a9dd1971.png)

**Comment by nihal467** [comment]
@Pranshu1902 follows the template while filing an issue!
