### ISSUE TITLE
Working status dropdown menu in create asset form causes page layout to jump

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3424]
**Describe the bug**
On expanding the options of `Working Status` field in Create Asset form, layout keeps jumping as shown in the video.

**To Reproduce**

1. Go to Create Asset form
2. Click on Working Status's drop down button

**Expected behavior**
The drop down should be shown without altering the form layout

**Screenshots**

https://user-images.githubusercontent.com/25143503/185619629-bbc6dfb5-8edf-475f-ae90-66880fac3173.mp4

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser: Firefox
- Version:

**Comment by aeswibon** [comment]
Will be fixed in PR #3266
