### ISSUE TITLE
Hemodynamic Parameters: Enhance content

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3429]
- [ ] Club Pulse(bmp), Rhythm and description fields together in one section. It must be clear to the user that rhythm indicates heartbeat rhythm and the description is to note the description of such rhythm.
- [ ] Club together BP systolic and diastolic in one section called BP.
- [ ] Add SPO2 to this section. SPO2 is currently in the Ventilator parameters Section (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/779a961f-9045-4a1f-b996-d4af459d7c59/update). DO NOT remove it from ventilator parameter. The same field must be mirrored in Vitals also.

**Comment by gigincg** [comment]
@aparnacoronasafe Should we have the same field in both places? Or separate ones.

The Ventilator may provide a value and the 5 Para Monitor would provide another. Both may have different precision. Can you confirm on this?

**Comment by aparnacoronasafe** [comment]
But 2 separate values appearing on a patient file may confuse the user. 

But i get your point that post device integration, CARE will be receiving data from 5-para and ventilator.

After discussing with Dr. Athul, the following suggestion is reached at. 

In that case, the data shown on patient summary must be
1- when only 5 para is connected, 5-para
2- when only ventilator is connected, ventilator
3- when both 5-para and ventilator are connected, show ventilator value. However, have a note appear upon hover to mention that "this value id derived from ventilator"
4- when no device is connected, manually entered SpO2. However, the user must not have option at two places to manually enter. hence, SpO2 field in vitals must be a mirror of the SpO2 field in ventilator parameters. 
@gigincg

**Comment by shivankacker** [comment]
We are phasing out Ventilator SPO2 as discussed on EOD
