### ISSUE TITLE
Pressure Sore: Enhancement (PUSH score)

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3432]
In the pressure sore section (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/779a961f-9045-4a1f-b996-d4af459d7c59/update)

Instead of simply marking the intensity of the pressure sore on a scale of 5, we should introduce the PUSH score to assess a pressure sore. Each pressure sore on the body must be independently evaluated. 

So each selected section must have a separate pop-up window with the PUSH score.

PUSH score is calculated based on 3 parameters:
1 (a): Length (b): Width - Both these parameters will be collected in CMs with decimal places up to 1. 
2. Exudate Amount: Dropdown [ None, Light, Moderate, Heavy]
3. Tissue Type: Dropdown [ Closed, Epithelial tissue, Granulation Tissue, Slough, Necrotic tissue]

Once the user adds these parameters, the system must automatically assign scores to these inputs and calculate a total score to be shown in the UI. 

The scoring will be based on the below table:
<img width="676" alt="Screenshot 2022-08-19 at 8 01 46 PM" src="https://user-images.githubusercontent.com/67050716/185642985-55d4ed66-28e6-4c78-95c5-b78eb028543c.png">

To help the user give better input for the three parameters, The following explanation may be shown near the input fields
<img width="855" alt="Screenshot 2022-08-19 at 8 07 43 PM" src="https://user-images.githubusercontent.com/67050716/185643367-7382fb46-0949-478b-938a-a2139f438be9.png">

There must also be a description field (long text field) to give additional details about each of the pressure sore.

**Comment by arpancodes** [comment]
We may need to think of a redesign to accommodate the popup for a separate body part? @gigincg 
Also @aparnacoronasafe for the total score, all the subscores will be added simply?

**Comment by aparnacoronasafe** [comment]
@arpancodes yes. total score will be sum of all subscores for a particular pressure sore. There will be one score for each of the pressure sores on the body

@gigincg @nihal467 Yes, we need a redesign. I was imagining the OUSH score to appear in a floating window against each selected body part. It would be nice if someone can create a mockup design and we can start a discussion from there.

**Comment by aparnacoronasafe** [comment]
Clarification:

Suggestive design
<img width="734" alt="Screenshot 2022-08-26 at 8 18 31 PM" src="https://user-images.githubusercontent.com/67050716/186932487-3ee4e953-9a67-469d-8abc-ea22122b2e9c.png">

**Comment by gigincg** [comment]
@aparnacoronasafe Can we have a default value for each of these for migrating the existing data?

cc: @iamsdas

**Comment by iamsdas** [comment]
> @aparnacoronasafe Can we have a default value for each of these for migrating the existing data?
> 
> cc: @iamsdas

Right now we have a default value of an empty list. The main question is if there would be any problem deleting the existing data for the `pressure_sore` column (it currently contains a list of entries having `region` and `scale`).
