### ISSUE TITLE
Rename "Create Investigation" button to "Log Lab Result"

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3433]
https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/investigations

<img width="1424" alt="Screenshot 2022-08-19 at 8 21 29 PM" src="https://user-images.githubusercontent.com/67050716/185646216-c70ceef9-ddc9-4fc9-9e9d-515ed3c6d47c.png">

The "create investigation" button must be rnamed as "Log Lab Result"

**Comment by shivankacker** [comment]
@aparnacoronasafe should the page title be changed too?
![image](https://user-images.githubusercontent.com/23238460/185648747-65020ad0-0590-4a14-b036-c31a3fb353b7.png)

**Comment by aparnacoronasafe** [comment]
@skks1212 Yes please!! You can do it in a separate PR, or this one. Whatever is more convinient
