### ISSUE TITLE
Investigation suggestion in consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3435]
**Context**

In CARE, currently, we only have the option to log lab results and other parameters for a patient. 

But currently, a doctor is unable to instruct the nurse (caregiver) to carry out an investigation for the patient. 

This must be added to the consultation form so that the doctor may properly log the treatment plan for the patient which involves instructions for investigation.

**Change required**
<img width="689" alt="Screenshot 2022-08-19 at 8 24 49 PM" src="https://user-images.githubusercontent.com/67050716/185649258-c0c4e3fd-c0a1-4a1c-b3b4-b406c2e8d12c.png">

- [ ] Add an investigation section needs to be added to the consultation. https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/update
- [ ] The description field with accept input of any of the tests we have within the 
a: **investigation**. The text box must be a search field with suggestions appearing as dropdown. 
b: Additionally the user must also be able to suggest any parameters in **Vitals** (Temp., Blood Pressure, Respiratory Rate, Pulse Rate) and
c: **ABG** (PO2, PCO2, PH, HCO3, Base excess, Lactate, Sodium, Potassium)

- [ ] next field must be "Repetitive"- YES/NO
If the repetitive, field for "Frequency" with dropdown [ 15 min, 30 min, 1 hr, 6 hrs, 12 hrs, 24 hrs, 48 hrs ]
If not repetitive "Time and Date" to capture the time and date of the procedure
NOTE: Similar field is already added to the "procedure" section in https://github.com/coronasafe/care_fe/pull/3356. 

- [ ] Add "Note": Text field to accommodate 100 characters to add a note

- [ ] Option to add more than one investigation required with all the above fields

**Comment by shivankacker** [comment]
> The description field with accept input of any of the tests we have within the
a: investigation. The text box must be a search field with suggestions appearing as dropdown.
b: Additionally the user must also be able to suggest any parameters in Vitals (Temp., Blood Pressure, Respiratory Rate, Pulse Rate) and
c: ABG (PO2, PCO2, PH, HCO3, Base excess, Lactate, Sodium, Potassium)

@aparnacoronasafe Can you elaborate more on the investigation field part, probably with an example?
Please also mention the placement of this section in the edit consultation page.

**Comment by aparnacoronasafe** [comment]
The investigation module is currently seeded with a list of tests. Those tests are here at https://docs.google.com/spreadsheets/d/1hN13p-BDbb1Pkl3a8tcVdWFsFxncju2QPfeOEkKh51E/edit?usp=sharing
In investigations, as you can see the tests are also grouped (mentioned in Tab 2 above) It would be great to give user the option to select a group, whereby all tests in the group must come up. This is an advanced feature.

Placement: Above prescriptions in consultation form

@skks1212
