### ISSUE TITLE
Facility page is showing features multiple times

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3447]
**Describe the bug**

The facility page is showing features multiple times

**Expected behavior**

keep the features of the facility reflection only once

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/185758074-4874f51e-b1a0-435c-94bf-c69681bda4c8.png)

**Comment by nihal467** [comment]
@khavinshankar iam having this same issue again !

**Comment by khavinshankar** [comment]
@nihal467 the issue was again caused due to the same reason, from https://github.com/coronasafe/care_fe/pull/3324/files

I'll push the fix immediately

**Comment by nihal467** [comment]
@khavinshankar once the PR is pushed, let me know
