### ISSUE TITLE
notice board is not showing any notification send to the facility

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3449]
**Describe the bug**

- [x] when we are sending a notification to the facility using a district admin access and view the notification received to the facility as a staff user, unable to see the notification received in the notice board
- [x] when we hard refresh ( Ctrl + F5 ) the notice board page, it says no notice available 

**To Reproduce**

1. Go to the facility page using a district admin access
2. Click on any facility, and send a notification to the facility 
3. re-login using a staff id linked to that facility
4. go to the notice board
5. see the error that nothing is been reflected there

**Expected behavior**

the notice sent to the facility using a district admin should appear on the notice board of the staff linked to the facility

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/185777684-494c512c-4a3a-406b-9bbe-46c49de43b25.png)

- above image shows that the notification is sent to the facility

![image](https://user-images.githubusercontent.com/57055998/185777722-2423df2b-15fb-4479-a011-0d37b519d080.png)

- above image shows that the notification is not reflected in the staff login notice board

![image](https://user-images.githubusercontent.com/57055998/185777760-f7c42e95-097a-4561-8163-cb4d6f779a00.png)

- above image shows that after the hard refresh ( Ctrl +F5 ), the notice board become blank

**Comment by nihal467** [comment]
@khavinshankar the first issue is resolved, can you check why the second issue is being caused

**Comment by khavinshankar** [comment]
@nihal467 about the second issue, when I do it in the localhost, it's working fine but when I try the same in the staging server, this issue is happening and also the issue is happening in deploy previews also, might have something to do with deployment

@mathew-alex can you check this out?

**Comment by mathew-alex** [comment]
![Screenshot 2022-08-28 at 3 05 24 PM](https://user-images.githubusercontent.com/22002072/187067708-a48408f0-aa82-4ef2-981d-3124b2534156.png)

The request is not sent when refreshed.

**Comment by nihal467** [comment]
@gigincg @vigneshhari @khavinshankar can you guys have a look on this

**Comment by gigincg** [comment]
@khavinshankar Can you check on this once more and revert during the EOD?

**Comment by nihal467** [comment]
@khavinshankar can you look into it

**Comment by khavinshankar** [comment]
@nihal467 will take care of this issue in the coming week
