### ISSUE TITLE
Medicine: Log Update

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3454]
With the new #3437 , where medicine administration is logged within the I/O balance section.

However, we need a log of changes made to the prescription module in consultation (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/1b63b5b5-e1ba-4e87-878e-9c178996255a/consultation/4516faa0-77cd-4b5e-9c52-1df41fbf9090/update)  and Medince administration record in I/O balance (#3437). 

This log of changes can be kept in the Medicine tab in the patient dadshboard. 

The medicine section in Log Update may be removed

@gigincg @vigneshhari

**Comment by nihal467** [comment]
@aparnacoronasafe can you review this issue and modify/close this issue

**Comment by aparnacoronasafe** [comment]
to be looked at post deployment of events module
