### ISSUE TITLE
Update the Goal for the project in landing page

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care_fe#3455]
From 
```
Our Goal is to defend the Healthcare system from overloading beyond capacity.
```

Tp
```
Our goal is to continuously improve the quality and accessibility of public healthcare services using digital tools.
```

**Comment by rithviknishad** [comment]
@aparnacoronasafe may I get help in translations for the new goal...

- Kannada
- Malayalam
- Marati
- Tamil

**Comment by aparnacoronasafe** [comment]
@rithviknishad let me get help on this.

@rithviknishad this needs to be a customizable component. With each deployment, there must be option to change it. The default will be the above phrase.

**Comment by aparnacoronasafe** [comment]
Malayalm : ഡിജിറ്റൽ ടൂളുകൾ ഉപയോഗിച്ച് പൊതുജനാരോഗ്യ സേവനങ്ങളുടെ ഗുണനിലവാരവും പ്രവേശനക്ഷമതയും തുടർച്ചയായി മെച്ചപ്പെടുത്തുകയാണ് ഞങ്ങളുടെ ലക്ഷ്യം.

**Comment by aparnacoronasafe** [comment]
Marathi: डिजिटल साधनांचा वापर करून सार्वजनिक आरोग्य सेवांची गुणवत्ता आणि सुलभता सतत सुधारणे हे आमचे ध्येय आहे.

**Comment by aparnacoronasafe** [comment]
kannada:
ಡಿಜಿಟಲ್ ಉಪಕರಣಗಳನ್ನು ಬಳಸಿಕೊಂಡು ಸಾರ್ವಜನಿಕ ಆರೋಗ್ಯ ಸೇವೆಗಳ ಗುಣಮಟ್ಟ ಮತ್ತು ಪ್ರವೇಶವನ್ನು ನಿರಂತರವಾಗಿ ಸುಧಾರಿಸುವುದು ನಮ್ಮ ಗುರಿಯಾಗಿದೆ.

**Comment by aparnacoronasafe** [comment]
Tamil: டிஜிட்டல் கருவிகளைப் பயன்படுத்தி பொது சுகாதார சேவைகளின் தரம் மற்றும் அணுகல்தன்மையை தொடர்ந்து மேம்படுத்துவதே எங்கள் குறிக்கோள்.
