### ISSUE TITLE
ICD 11 Filter | Add UI Filter

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#3477]
Along with the backend filter, to improve the experience, show only options that match the search. 

Or in other words

```
options = options.filter(option => option.toLowerCase().includes(search.toLowerCase())
```

**Comment by Ritesh-Aggarwal** [comment]
Hey @khavinshankar , what the status on this issue, can I work on this?

**Comment by khavinshankar** [comment]
@Ritesh-Aggarwal initially we had results from the backend that was not an exact match of the search term but now it has been improved.

I think this issue can be closed, but if there is any improvement you can do to the filter then feel free to try it out.
