### ISSUE TITLE
Asset Management: Log of transaction history with revised QR Code

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3479]
The QR code linked to assets are revised from QR code generated by CARE using asset external id to linking QR code generated outside of CARE.

The log of transaction still works when the QR code generated by CARE using asset external id is scanned. Revise that to work with the QR code generated outside of CARE.

https://care.coronasafe.in/assets/1ecda1ae-de51-4852-be7c-745ecf5e6e8b

**Comment by nihal467** [comment]
@patelaryan7751 what is the status on this issue !

**Comment by Ashesh3** [comment]
Hey @aparnacoronasafe , as per my understanding, you want the QR code generated outside CARE to point to the Transaction History of the asset stored within the CARE deployment, is that accurate? Where are these QR codes generated from?

**Comment by aparnacoronasafe** [comment]
@Ashesh3 That's correct Ashesh. Currently, we are using QR codes provided by Gigin. But there is also a side project to build a QR code generator. 

@gigincg Please give more clarity on QR Codes. 

Attaching eg of a QR code we use
![QR_Code1](https://user-images.githubusercontent.com/67050716/203275120-7d3a1bf5-6230-413e-b84f-255e2c389bf3.png)

**Comment by gigincg** [comment]
@Ashesh3 It is more of making asset transactions work using the qrcode field instead of the externalid field. Ping me to discuss further!

**Comment by aparnacoronasafe** [comment]
This needs to be done. @Ashesh3 why did you unassign yourself.? Can somebody else take it up? @vigneshhari

**Comment by Ashesh3** [comment]
> This needs to be done. @Ashesh3 why did you unassign yourself.? Can somebody else take it up? @vigneshhari

Hey, I unassigned myself as I was occupied for the next 2 weeks (from Jan 3) so I wasn't able to work on this, anyone else feel free to take it up!
