### ISSUE TITLE
Bug: Bed badge allignment

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3497]
On patient list, https://care.coronasafe.in/patients?page=2&limit=12&district=&lsgBody=&facility=&facility_type=&date_declared_positive_before=&date_declared_positive_after=&date_of_result_before=&date_of_result_after=&created_date_before=&created_date_after=&modified_date_before=&modified_date_after=&date_of_result=&last_consultation_admission_date_before=&last_consultation_admission_date_after=&last_consultation_discharge_date_before=&last_consultation_discharge_date_after=&ordering=&category=&gender=&disease_status=&age_min=&age_max=&last_consultation_admitted_to_list=6&srf_id=&number_of_doses=&covin_id=&is_kasp=&is_declared_positive=&last_consultation_symptoms_onset_date_before=&last_consultation_symptoms_onset_date_after=&last_vaccinated_date_before=&last_vaccinated_date_after=&last_consultation_is_telemedicine=&is_antenatal=

Wherever, the bed badge containes Location name, thats long and occupies 2 rows, the allignment of the location is towards the left and Not the centre. Make it centre alligned
<img width="109" alt="Screenshot 2022-08-29 at 10 54 50 AM" src="https://user-images.githubusercontent.com/67050716/187129094-df9fe6d9-6cc0-4698-98e6-59823c26cd78.png">

**Comment by Ritesh-Aggarwal** [comment]
Where can I find such a badge , I am unable to reproduce this error.

**Comment by nihal467** [comment]
@Ritesh-Aggarwal https://care.coronasafe.in/patients?name=Anila+P.R&page=1, check this URL

**Comment by nihal467** [comment]
@Ritesh-Aggarwal 
![image](https://user-images.githubusercontent.com/57055998/187249782-9e906d38-3eb0-4f6c-ae97-083cf2e9f986.png)
