### ISSUE TITLE
BUG: Medicine tab in Patient dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3498]
**Describe the bug**
When user clicks on medicine tab in patient dashboard (https://care.coronasafe.in/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/ffa59df5-ba15-4310-a376-a4c01f0667eb/consultation/81cafbea-af86-4d8a-8c1c-38e0f279ecbb/medicines) redirected to a blank page

**To Reproduce**

1. Go to Patient dashboard https://care.coronasafe.in/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/ffa59df5-ba15-4310-a376-a4c01f0667eb/consultation/81cafbea-af86-4d8a-8c1c-38e0f279ecbb
2. Click on Medicine Tab
3. See blank page

**Expected behavior**
The details in prescription must come up

**Desktop (please complete the following information):**

- OS: [e.g. MacOS]
- Browser [ chrome, ]

**Comment by nihal467** [comment]
https://care.coronasafe.in/facility/273fe202-5325-4d5f-9a20-f7da9cb79e4d/patient/ad190b5d-0fc1-4dc9-b6f4-147507cbde0b/consultation/406c4477-92b5-45ac-ab9d-8d20a209dea3/medicines  ( with data )

https://care.coronasafe.in/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/a2ac87d6-8ea1-4e1a-9923-1c9560823909/consultation/8a673700-acdf-4bb5-8326-96e3a9280d34/medicines ( without data )

@khavinshankar it is working well for me using the above link, can you have a look at this?

**Comment by khavinshankar** [comment]
@nihal467 The default value (initial value) of the prn_prescription was {} (object), but once we changed it or edited it the value changes to [] (empty array or array with presc).

so that initial object was causing the issue.
