### ISSUE TITLE
Bed Name should be limited to keep a uniformity in Patient UI

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3513]
![image](https://user-images.githubusercontent.com/57055998/187719069-17b71776-53b3-40ea-b919-b3f5ac0d4543.png)

Now, the bed name is so long that it is breaking the UI uniformity. So, to ensure that @aparnacoronasafe will be working on conditions to ensure bed numbers have fixed character lengths.

**Comment by Ashesh3** [comment]
@aparnacoronasafe Any updates on this? What should be the ideal length of the name?

**Comment by nihal467** [comment]
issue resolved
