### ISSUE TITLE
APACHE Score for patients

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3522]
APACHE Score can be calculated for all patients newly admitted to the intensive care unit. While it is not mandatory, it is a useful tool for risk stratification and to compare the care received by patients with similar risk characteristics in different units. APACHE Score is only calculated for patients:
- Admitted to the ICU
- 16 yrs of age or above

We are looking to introduce the APACHE score for all patients admitted to ICU above 16 years of Age. This will greatly help the communication between the Hub and Spoke. The hub doctors can derive a lot of value by just looking at the score for any patient.

The APACHE Score must appear as a section in the patient dashboard. A suggestive design is as under:
<img width="887" alt="Screenshot 2022-09-02 at 9 25 54 AM" src="https://user-images.githubusercontent.com/67050716/188056398-753b6a6a-3519-4e9c-90b0-97f800b3c6a0.png">

A) Once a patient is admitted to the ICU (by filing a consultation form), the user is redirected to the patient dashboard. The patient dashboard will have a space on the right for APACHE Score. 
Initially the space will have option to "Calculate APACHE Score"

<img width="268" alt="Screenshot 2022-09-02 at 9 35 10 AM" src="https://user-images.githubusercontent.com/67050716/188056864-3bd76782-d48e-4fad-a608-79c0c51c1c0d.png">

B) Once the user clicks on "Calculate APACHE Score" a pop-up window appears with the following fields. The input given in these fields are added to get the final APACHE Score. Mentioning the scores for each input as well. 
**Header 1: Patient's Characteristics:**
1. **AGE:** <number> years [ allow range of 0-120]
[ 16-44yrs: Score 0, 
  45-54 yrs: Score 2, 
  55-64 yrs: Score 3,
  65-74 yrs: Score 5,
  over 74 yrs: Score 6 ]
We already capture the DOB in the Patient registration form (https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/cc52390c-ac8a-4af5-9806-f3df7ee1795a/update) and the system must automatically calculate the age and populate in the field. 
2. **History of severe organ insufficiency/immunocompromised patient**: Dropdown with the 3 options below
Yes: nonoperative/emergency postoperative patient: Score 5
Yes: elective postoperative patient: Score 2
No: Score 0
3. **Temperature**
[≥41 Celsius : Score 4
 39 to <41 : Score 3
38.5 to <39 : Score  1
36 to < 38.5 : Score  0
34 to <36 :Score  1
32 to <34 :Score  2
30 to <32 : Score  3
<30 : Score  4]
NOTE: The input must be accepted in both Celsius and Fahrenheit. The unit must be changeable with a dropdown.  the conversion formula is (1°C × 9/5) + 32 = 33.8°F. Have Fahrenheit as the default.
It is another parameter within Vitals.  (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce/daily_rounds/2b564baf-64bb-49f6-ae75-757a8dcfe22d/update) If an earlier log update has the parameter, auto-populate the same in the field. If not, have the text space for numeric input.
4. Glasgow Coma Scale: <Input to be numeric between 3-15> 
Have a link to calculate Glasgow Coma Scale[GCS], which will redirect the user to the  Neurological Monitoring within Log Update (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce/daily_rounds/2b564baf-64bb-49f6-ae75-757a8dcfe22d/update)- Open up the Neurological Monitoring within the latest log update, and consider this as an addition made on the latest log update. If the patient has had no log updates, show an error message right by the button in red stating "Create Log Update to calculate the Glasgow Coma Scale".
Score: 15- [Glasgow Coma Scale]
Automatically input the Glasgow Coma Scale if the patient's Log Update has had an entry for the same earlier.
5. **Mean arterial pressure [MAP]** with Unit "mmHg" will have numeric input of 0-250.
It is another parameter within Vitals.  When systolic and diastolic blood pressure is entered in Vitals (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce/daily_rounds/2b564baf-64bb-49f6-ae75-757a8dcfe22d/update) CARE automatically calculates MAP as a parameter under Vitals using formula (MAP) = (SBP + 2 DBP) / 3. 
If the same is available in an earlier Log Update, auto-fill the same in the field. 
If not, give a small button to calculate the MAP. when user clicks on the button they are redirected to "Update Log Update" of the latest log update. If the patient has had no log updates, show an error message right by the button in red stating "Create Log Update to calculate the "Mean arterial pressure".
Scoring for MAP is as below
 More than 159 : Score 4
 More than 129-159 : Score 3
More than 109-129 : Score 2
More than 69-109 : Score 0
More than 49-69 : Score 2
49 or less : Score 4
6. **Heart rate** Unit- beats per minute (bpm) will be a numeric input in the range of 0 to 200. 
It is another parameter within Vitals.  (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce/daily_rounds/2b564baf-64bb-49f6-ae75-757a8dcfe22d/update) If an earlier log update has the parameter, auto-populate the same in the field. If not, have the text space for numeric input.
Scoring:
≥180 | 4
140 to <180 : Score 3
110 to <140 : Score 2
70 to <110 : Score 0
55 to <70 : Score 2
40 to <55 : Score 3
<40 : Score 4
7. **Respiratory rate**, Unit: breaths per minute, Input: numeric value in the range of 0-50.
It is another parameter within Vitals.  (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce/daily_rounds/2b564baf-64bb-49f6-ae75-757a8dcfe22d/update) If an earlier log update has the parameter, auto-populate the same in the field. If not, have the text space for numeric input.
Scoring:
≥50 : Score 4
35 to <50 : Score  3
25 to <35 : Score  1
12 to <25 : Score  0
10 to <12 : Score  1
6 to <10 : Score  2
<6 : Score  4
8. **Oxygenation (FiO2)**- Numeric input, Unit is % and range is 21-60.
9.

**Comment by nihal467** [comment]
@aparnacoronasafe is the issue completed and align with existing field scenario, can you modify/unassign yourself from the issue

**Comment by nihal467** [comment]
non-relevant to current develop
