### ISSUE TITLE
Bed name not centered on Patient Dashboard

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#3532]
The bed name is not centered on the Patient Dashboard page.

![image](https://user-images.githubusercontent.com/3626859/188281764-e9bb5663-7995-4f06-b76c-58031ade09ef.png)

**Comment by nihal467** [comment]
@Ashesh3 PR #3490 is resolving this, can you recheck and confirm it !

**Comment by Ashesh3** [comment]
@nihal467 yep that should resolve it!
