### ISSUE TITLE
Bug : Facility Search is not working

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3552]
**Describe the bug**

when we are searching for a facility by name in the platform, it redirects to a white page

**To Reproduce**

https://care.coronasafe.in/facility?search=nihal

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/188809060-fe1f822c-8e0d-46b7-8e69-d33853870063.png)

**Comment by nihal467** [comment]
@Ashesh3 work on it, ASAP

**Comment by Ashesh3** [comment]
@nihal467 resolved, please test.

**Comment by khavinshankar** [comment]
@nihal467 the issue was due to that, there was a facility that had a feature that was not there in our pre-defined list of features
![image](https://user-images.githubusercontent.com/29787772/188820763-26f017ee-04d4-49ee-92fc-09ad57fcc9ed.png)

**Comment by Ashesh3** [comment]
> @nihal467 the issue was due to that, there was a facility that had a feature that was not there in our pre-defined list of features ![image](https://user-images.githubusercontent.com/29787772/188820763-26f017ee-04d4-49ee-92fc-09ad57fcc9ed.png)

Exactly! Any idea how could an invalid feature was set for this facility?
https://github.com/coronasafe/care_fe/pull/3553#issuecomment-1239032458
