### ISSUE TITLE
Assign to Volunteer pop-up is not responsive

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3571]
**Describe the bug**

Assign a volunteer pop-up in the patient detail is not responsive

**Expected behavior**

make the UI responsive

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/189519082-08352242-cacf-4b47-a1c7-ac4b57152e73.png)

**Comment by Ashesh3** [comment]
This is sad :( I specifically fixed this bug in https://github.com/coronasafe/care_fe/pull/3452 but then someone overwrote my changes? Not sure what happened but the same bug was bought back to life in this commit: https://github.com/coronasafe/care_fe/commit/6268a39ef7d11469925b6e7c905ffedbe6cc8807

**Comment by rithviknishad** [comment]
@Ashesh3 shall I assign it to you then? I didn't make much changes yet.

**Comment by Ashesh3** [comment]
> @Ashesh3 shall I assign it to you then? I didn't make much changes yet.

Sure! I already have the fix with me ready since I fixed the same thing before.. Thanks.
