### ISSUE TITLE
File Preview is not working properly in consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3579]
**Describe the bug**

- [ ] after the file is uploaded, we have to manually reload the page to see the reflection
- [ ] the file preview is not showing the image

**To Reproduce**

https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/cc52390c-ac8a-4af5-9806-f3df7ee1795a/consultation/7037609e-3c25-45ed-bfd8-e01c346cbd45/files

**Expected behavior**

- [ ] after the file is uploaded, the page should be automatically reloading the page
- [ ] the file preview should be showing the image

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/190098289-5b87dadd-cef1-4364-91d1-756eac876a2d.png)

**Comment by nihal467** [comment]
@Ashesh3 work on this, ASAP

**Comment by Ashesh3** [comment]
@nihal467 The linked PR should fix the 1st issue:

- [x] after the file is uploaded, we have to manually reload the page to see the reflection

For the other issue, it seems that there's a misconfiguration from the AWS side of things, Someone with AWS access needs to take a look there. The key seems to have been removed? `NoSuchKey`. @gigincg Can you take a look into this?

**Comment by gigincg** [comment]
@mathew-alex Can you check on this?

**Comment by mathew-alex** [comment]
It was a CORS issue due to a misconfiguration in AWS. I have fixed it. Another problem noted is that even if a file is not uploaded to S3, it shows up in UI as an uploaded file. A preview of that file will not give any results because of that. 
Issue #3582
