### ISSUE TITLE
File upload entry for failed uploads

### ISSUE THREAD

**Issue by mathew-alex** [coronasafe/care_fe#3582]
An entry is added even in the case of a failed file upload. The preview option for the entry under View Consultation Files will not generate a preview because of that.

**Comment by Ashesh3** [comment]
It seems like according to the current workflow, an entry for a file is created before the actual upload takes place. The backend first creates an entry and returns the signed_url which is used on the frontend side to make the actual upload. If the upload fails, the backend has no way of knowing the same and frontend does nothing to remedy that. 

Possible fix: Currently all files have an attribute `upload_completed` which defaults to `False`. Once an upload is actually successful, the frontend can send a separate request to set that to `True`.
The file list on the frontend would then only show files which have `upload_completed = True`.

@vigneshhari What's your take on this?
Edit: Discussed on EOD call.
