### ISSUE TITLE
Make mandatory validation in ONVIF camera and HL7 monitor asset page

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#3585]
**Describe the bug**
The fields in  ONVIF camera and HL7 monitor asset page are not mandatory
**To Reproduce**
Open any asset then configure it you would ssee the fields

**Expected behavior**
It should be validated before being submitted

**Comment by NimbleNitesh** [comment]
Hi @patelaryan7751, Can you assign this issue to me? I want to work on this.

**Comment by nihal467** [comment]
already exist in platform
