### ISSUE TITLE
Users page link to new facilty stretches the card vertically

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#3590]
**Describe the bug**
Users page link to new facilty stretches the card vertically.
**To Reproduce**
Go to Users page and click on linked facility of the user.

**Expected behavior**
Instead the information should be show in a modal with pagination of all linked facility

**Screenshots**
**Before:**
![image](https://user-images.githubusercontent.com/59426397/190215439-5f980f8b-3fb5-4a6c-acb9-4174fa365cae.png)
----------------------------------------------------------------------------------------------------------------------------------------------
**After:**
![image](https://user-images.githubusercontent.com/59426397/190215316-10e8d54f-53f1-4139-ad8b-f19e34ff0082.png)

**Comment by rithviknishad** [comment]
duplicate of #3984
