### ISSUE TITLE
Tailwind Consultation Form

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#3594]
Update Consultation Form (And eventually the other Forms) to Reflect the following

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/13028584/190578076-8a0ca49e-fa9b-4139-b116-baaca2022393.png">

**Comment by gigincg** [comment]
cc: @aparnacoronasafe

**Comment by rithviknishad** [comment]
@gigincg could you link the figma

**Comment by rithviknishad** [comment]
@stale do not close. waiting for #3698 to be merged.
