### ISSUE TITLE
Unable to log update - Patient category none is not a valid choice

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#3602]
![image](https://user-images.githubusercontent.com/23238460/190862259-c9470dde-662c-4ea4-90b5-aa89b9961f6d.png)

**Comment by rithviknishad** [comment]
@skks1212  Hard refresh and try

**Comment by rithviknishad** [comment]
The new mandatory field has been merged

**Comment by shivankacker** [comment]
@rithviknishad my bad! Just saw the field
