### ISSUE TITLE
Frequency dropdown: prescriptions

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3619]
In consultation/Log update, in the prescription section, for Frequencies, there is a dropdown with multiple options. 

Add "Stat" as the first option on top of the dropdown

**Comment by Ashesh3** [comment]
@aparnacoronasafe Do you mean this dropdown in consultation update?
![image](https://user-images.githubusercontent.com/3626859/191691534-52b0977e-685d-4413-be3f-8874dd30d006.png)

**Comment by aparnacoronasafe** [comment]
You are looking at investigation section.

Please look at the prescription

**Comment by Ashesh3** [comment]
> You are looking at investigation section.
> 
> Please look at the prescription

Thanks! It should be this one then, right?

![image](https://user-images.githubusercontent.com/3626859/191697865-a33deb48-f9ae-4171-9c20-e5f2da70b197.png)
