### ISSUE TITLE
Remove Live Data for Discharged Patients

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#3625]
We should hide the Feed Tab and The Live Vitals Section for any Patient who's discharged

**Comment by Ashesh3** [comment]
> We should hide the Feed Tab and The Live Vitals Section for any Patient who's discharged

Hey, what exactly do you mean by the feed tab?

And just to confirm, is this the Live Vitals Section?

![image](https://user-images.githubusercontent.com/3626859/191749578-7fa76c58-0f12-4639-9f8e-913527a1adf6.png)
