### ISSUE TITLE
Search bar focus is lost when search is performed in Assets page.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3626]
**Describe the bug**
Search bar focus is lost when search is performed automatically without pressing enter.

**To Reproduce**

1. Go to Assets Page
2. Type more than 3 characters in the search bar
3. Wait for it to auto search
4. Try continuing to type remaining characters to narrow the search, but is not possible as focus is lost.

**Expected behavior**
Should be able to continue typing and focus from the search field should not be lost.

**Screenshots**

https://user-images.githubusercontent.com/25143503/191722878-eea7528b-735a-408c-81a7-d291b85b1485.mp4

**Desktop (please complete the following information):**

- Device: 
- OS: Ubuntu 22.04
- Browser Firefox
- Version 104

**Comment by khavinshankar** [comment]
@rithviknishad 
It's fixed in https://github.com/coronasafe/care_fe/pull/3577, yet to be merged though

closing this issue, feel free to reopen it if it is not resolved
