### ISSUE TITLE
Minor UI break in the Live Vitals of Patient Consultation page 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3634]
**Describe the bug**

Few datas are not showing fully in the live Vital responsive view

**To Reproduce**

https://care.coronasafe.in/facility/ba2f8df6-20e6-4351-b2a3-065d7886e11a/patient/c2e3ce12-44bb-4db1-bcc8-dcbea9843edc/consultation/215fa91e-80e7-4fd9-bf53-4e841bd5a024/updates

**Expected behavior**

make it responsive

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/192083086-3bfb3990-224a-4c3b-b223-cc6c6666902b.png)

**Comment by Ritesh-Aggarwal** [comment]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/57039447/192085329-43bc0809-238a-4beb-b621-d9924268060c.png">

not able to reproduce the error, @nihal467
