### ISSUE TITLE
Data in graphs in summary page is being hidden in mobile devices

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#3642]
**Describe the bug**
Data in graphs in summary page is being hidden in mobile devices

**To Reproduce**

1. Go to any Patient
2. Click on Summary
3. Scroll down below

**Expected behavior**
The data should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/59426397/192127198-6e6c643f-4e29-4d12-becd-8fc0e74b1346.png)

**Comment by khavinshankar** [comment]
@nihal467 @patelaryan7751 does this issue still persist? I don't see it, can you check it once again?

**Comment by patelaryan7751** [comment]
@khavinshankar yes the issue is still present 
![image](https://user-images.githubusercontent.com/59426397/192617914-10dbf6f1-6c34-41da-a843-c27ea9f46270.png)[
](https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0/summary)
view this in samsung fold refresh the page then view it.
