### ISSUE TITLE
Change Active label to Transfer Status : Active in Asstes Page

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#3646]
**Describe the bug**
Change Active label to Transfer Status : Active in Asstes Page

![image](https://user-images.githubusercontent.com/59426397/192217386-89c25b52-ecb5-42f7-bcc4-aba3b2641855.png)

**Comment by patelaryan7751** [comment]
This issue will be discussed in next eod an resolved.

**Comment by nihal467** [comment]
@patelaryan7751 @khavinshankar  the PR related to this issue is been closed by GitHub action. can you check this issue and update the status here !

**Comment by nihal467** [comment]
@patelaryan7751 post an update on this issue

**Comment by patelaryan7751** [comment]
The issue is not relevant
