### ISSUE TITLE
Minor UI change in the asset page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3671]
**Describe the bug**

- [ ] the space between the filters and the card in the assets are really high
- [ ] currently, we are having 24 cards in a single page, shall we reduce it , discuss it in the EOD before working on this

**To Reproduce**

https://care.coronasafe.in/assets?facility=&asset_type=&status=&location=&search=nihal

**Expected behavior**

- [ ] make the UI more uniform

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/193275388-fe01304a-545e-496e-a3e9-066f9dbdcade.png)

**Comment by nihal467** [comment]
@cp-Coder what is the status on this PR

**Comment by aeswibon** [comment]
@nihal467 I have opened PR #3733 that will fix this issue
