### ISSUE TITLE
Add a loader whille fetching details in the TeleICUPatientVitalsCard instead of showing "No live Data"

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#3674]
**Describe the bug**
Add a loader whille fetching details in the **TeleICUPatientVitalsCard** instead of showing "No live Data"

**To Reproduce**

Go to https://care.coronasafe.in/facility/ba2f8df6-20e6-4351-b2a3-065d7886e11a/patient/c2e3ce12-44bb-4db1-bcc8-dcbea9843edc/consultation/215fa91e-80e7-4fd9-bf53-4e841bd5a024/updates

**Expected behavior**
There shall be a loader to show that it is fetching details.

**Screenshots**
https://www.loom.com/share/b16f93f3e9084202aba0dfc7b8279ad7

**Comment by nihal467** [comment]
@siddnikh Are you working on this

Adding depth, the component should initialize with a loader, and if the request is not successful, fall back to the existing "No Live Data" Text

**Comment by nihal467** [comment]
@gigincg removing stale as @Pragati1610 self-assigned it and will be working on this issue

**Comment by nihal467** [comment]
@Pragati1610 what is the status of this issue

**Comment by nihal467** [comment]
closing this issue, as the entire component got changed, and this doesn't seem relevant now
