### ISSUE TITLE
Patient card size is not consistent when labels overflow.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3712]
![image](https://user-images.githubusercontent.com/25143503/194344491-f0a609b1-c09e-4aaf-a7da-fdc46bd238ed.png)

**Comment by Ashesh3** [comment]
Is this not intentional? Since one of the cards in the last row need more height to display its contents, the rest of the cards in the same row adjust accordingly and have a uniform height, not necessarily in line with the cards in other rows.
Do you have any suggestions for resolving this design?

**Comment by Ashesh3** [comment]
Discussed on EOD. Will just keep the current behavior for now.
