### ISSUE TITLE
Blue color of phone number makes the facility page UI less uniform

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#3713]
**Describe the bug**
Blue color of phone number makes the facility page UI less uniform

**To Reproduce**
 Go to http://localhost:4000/facility/eeb23cb7-1524-479a-825e-660311386b47

**Expected behavior**
Instead we can have a call icon and make the text black in color

**Screenshots**
![image](https://user-images.githubusercontent.com/59426397/194360018-cece19df-d0d7-4472-ab03-2a19b4cc84e6.png)

**Comment by siddnikh** [comment]
So that blue colour comes if the link has already been visited. The default colour is black only. I'll add a small icon and change the visited link colour.

**Comment by nihal467** [comment]
this issue is been getting resolved on the #3819
