### ISSUE TITLE
🛠 Tailwinding Care

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3742]
_do not assign this issue_

This issue is an EPIC to track the progress of making custom tailwind components for care, sub-issues will be created).
Link this issue on pull requests that implement or modify a tailwind component **without a closing keyword**.

### Notes

- Follow the [**Figma design**](https://www.figma.com/file/fqDMgeN2m4TCSz5KobZaKW/CoronaSafe-Network-Care?node-id=1150%3A268) provided when implementing the components.

- Add `redesign` label to related issues / PR.

- When implementing or redesigning an entire form that replaces components with the custom tailwind components, name the branch in the format: **`tailwind/{branch-name}`**, for example: `tailwind/asset-registration` or `tailwind/patient-filters` or `tailwind/patient-consultation`.

- Form field components shall be wrapped by `FormField` so that the design stays consistent across the app and achieves a uniform component API interface.

### Components to be built

- [x] #3744 `TextFormField`
- [x] #3744 `TextAreaFormField`
- [x] #3744 `DatePicker`
- [x] #3744 `DateRangePicker`
- [x] #3744 `SelectMenu`
- [x] #3744 `MultiSelectMenu`
- [x] #3744 `AsyncAutocompleteFormField`
- [x] #3744 `ButtonV2`
- [x] #4463 `AutocompleteSelect`
- [x] #4309 `AutocompleteMultiSelect`
- [x] #3763
- [x] #4740 `RadioFormField`
- [x] `CheckboxFormField`
- [x] #4527 `PhoneNumberFormField`
- [x] `Tabs`
- [x] #4487 `SlideOver`
- [x] #4633 `Form`
- [x] #3908 `Dialog`
- [x] #3908 `ConfirmActionDialog`
- [x] #3872 `Callout`
- [x] #3769 `Note`
- [x] #3769 `PropertyDetail`
- [x] #3769 `ContactDisplay`
- [x] #3769 `FeatureTag`
- [x] #3898 `SearchInput`
- [x] #4649 `RelativeTime`
- [x] `CircularProgress`

We can use [tailwind/headlessui](https://headlessui.com/) for building some of the components

### Other related tasks
- [x] Update Vercel deploy config to use `develop` branch instead of the PR's branch.
- [x] Update README.md with content related to Storybook and add Storybook staging deploy link.
- [x] #5006

### Migrations
- [x] #3594
- [x] #3744
- [x] #4200 
- [x] #4202
- [x] #4203 
- [x] #4277 
- [x] #4317
- [x] #4322 
- [x] #4367
- [x] #4370 
- [x] #4375

cc: @gigincg

**Comment by khavinshankar** [comment]
@rithviknishad do you need any help with this?

**Comment by rithviknishad** [comment]
@khavinshankar definitely!! Could you help tailwind the async autocomplete field in the https://github.com/coronasafe/care_fe/pull/3744 patient filters?

Generally, apart from that, I was thinking of having all the input components have their own validators and also be compliant with form reducers across care since we mostly have only `set_form` and `set_error` only.

so that, the component's API interface would just take in the additional props (validator, reducerProps) [see this](https://github.com/coronasafe/care_fe/pull/3744/files#diff-2c391d69e3a85e37959e9843913cba1d1db5aa23dac46c81625b168a38c78d9cR18-R29).

however, the components API should still be usable when not used with reducers.
So I was just taking time to document it clearly so that it's easily maintainable by everyone and changing the component API interface later would be a hassle.

For example, the text input is composed like this:
https://github.com/coronasafe/care_fe/pull/3744/files#diff-e0e39dd41cb8f0b76d60275fa706cd765c8648107e45183f24781aa0cd51145f
and when used with reducers, the amount of code we write would be so less, but still, it'll render out the errors and field labels without having to write separate components each time.
