### ISSUE TITLE
Patient Search: IP No.

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3749]
Please add the option to search patents by IP No. in the Patient List (https://care.mn.gov.in/patients)

**Comment by Ashesh3** [comment]
@aparnacoronasafe Do you want the field to be in the [1] main page or hidden in the [2] advanced patient filter section? 

![image](https://user-images.githubusercontent.com/3626859/195351548-a15f7072-e21b-4d04-8276-1254beabd11c.png)

Edit: Discussed on an EOD call.
