### ISSUE TITLE
Indicate if bed is already occupied in bed listings, and who is the current occupant

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#3752]
![image](https://user-images.githubusercontent.com/23238460/195541270-fcc8139c-7801-41c4-bde6-bbe909dbfb13.png)
![image](https://user-images.githubusercontent.com/23238460/195541950-f924b679-a0c6-4445-b35c-0c1e89caee58.png)

**Comment by aeswibon** [comment]
@skks1212 there is already a similar issue #3149. I have opened the PR to fix that issue in both frontend and backend.

**Comment by shivankacker** [comment]
> @skks1212 there is already a similar issue #3149. I have opened the PR to fix that issue in both frontend and backend.

Alright! Closing this issue. Do check out the comment I made on your backend PR!
