### ISSUE TITLE
Redesign Facility Home Page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3757]
Tasks / components:

- [x] Update style for `ButtonV2` when `style="secondary"` to match figma.
- [x] `FeatureButton`
- [x] `Menu` (dropdown) https://headlessui.com/react/menu
- [x] `PhoneNumber`
- [x] `Table`
- [x] `SummarySection` which should take in title (string / JSX Element) and options (JSXElement[]), which will be used to compose Oxygen Information section, Bed Capacity section, etc..
- [x] `BedCapacityCard`
- [x] `DoctorTypeCard`

**Comment by joelsajichacko** [comment]
### **Figma Link to inspect the design:**
https://www.figma.com/file/fqDMgeN2m4TCSz5KobZaKW/CoronaSafe-Network-Care?node-id=1553%3A512

<img width="1366" alt="Facilities Page- redesign" src="https://user-images.githubusercontent.com/45791338/196020489-c7652e34-de13-48f7-87ff-a9e895f0aa8d.png">
