### ISSUE TITLE
Configure `eslint-mdx` for .mdx files

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3760]
**Is your feature request related to a problem? Please describe.**
Currently `eslint` throws errors when trying to lint `.mdx` files which is used to make storybook stories.

![image](https://user-images.githubusercontent.com/25143503/195986591-b00c6e16-c439-4aa0-a017-c8a6d0069ca0.png)

**Describe the solution you'd like**
Configure [eslint-mdx](https://github.com/mdx-js/eslint-mdx) to support linting and in lint-staged for .mdx files.

**Describe alternatives you've considered**
Momentarily, in lint-staged, eslint is modified to ignore '*.stories.mdx' files

![image](https://user-images.githubusercontent.com/25143503/195986603-31e03b11-3e96-4c32-966b-ae7527f51aee.png)

**Additional context**
- https://github.com/coronasafe/care_fe/pull/3744/commits/aa20b55e309accb74275a5ea04844d527b9ac069

**Comment by Omkar76** [comment]
Can assign this to me. @rithviknishad
