### ISSUE TITLE
Camera Feed(IOS): `HLS Player` non-functional fullscreen toggle

### ISSUE THREAD

**Issue by rabilrbl** [coronasafe/care_fe#3765]
**Describe the bug**
The fullscreen toggle for HLS Player in IOS devices is not working.

**To Reproduce**
On IOS device, visit this [link](https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/feed) and toggle fullscreen
**Tip**: Use `Browser Stack` to emulate an IOS device.

- OS: IOS
- Browser Safari

**Comment by nihal467** [comment]
a PR is been linked to this issue
