### ISSUE TITLE
Redesign of the Sidebar of CARE

### ISSUE THREAD

**Issue by joelsajichacko** [coronasafe/care_fe#3781]
### Redesigning the sidebar for a better layout with proper spacing between the elements;

Font used; Inter

Link to Figma; https://www.figma.com/file/fqDMgeN2m4TCSz5KobZaKW/CoronaSafe-Network-Care?node-id=1584%3A719

![image](https://user-images.githubusercontent.com/45791338/196351403-ec7884a6-19ba-457e-8e42-1d1a66ba7859.png)

**Comment by rithviknishad** [comment]
@joelsajichacko @gigincg @aparnacoronasafe

How about having a similar background in the recently redesigned warranty card, be also used in the sidebar's background and the login page background? 

#### Warranty Card's Background for reference:
![image](https://user-images.githubusercontent.com/25143503/197549993-a6960311-cafd-4d3b-8aed-2f16a47a1891.png)


#### to be used in:
![image](https://user-images.githubusercontent.com/25143503/197549843-20555f11-35db-48f3-ac3e-b107bcd7cce0.png)

cc: @skks1212

**Comment by joelsajichacko** [comment]
@rithviknishad it's a good idea that the background pattern can be implemented on the login page.

For the sidebar, don't think its a good idea, because normally the sidebars are really made clean without any background patterns

**Comment by shivankacker** [comment]
@rithviknishad make sure you use i tags for importing unicons. It has already been added to care. Syntax is similar to font awesome
somethink like `<i className="uil uil-[icon]"/>`
all Icons can be found on the unicons website

**Comment by gigincg** [comment]
@rithviknishad @skks1212 w.r.t. the Slack Discussion I think we decided not to use uni-icons? Or did we?

**Comment by rithviknishad** [comment]
@gigincg Not to use. I'll be porting pf-icons implementation.
