### ISSUE TITLE
Unable to select a year with `DateInputV2` tailwind component

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3784]
- Follow up of #3744

**Describe the bug**
Suppose I need to enter the date of birth of a 70-year-old person, then it's practically difficult to press the left arrow 70 times to reach the expected year.

**Expected behavior**
The year button should be clickable and grid of years shall be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/196598641-ec258f02-e05f-4ef2-9c41-ee69e01ca0d5.png)

**Comment by Ritesh-Aggarwal** [comment]
fixed by #3744
