### ISSUE TITLE
User filters are not user friendly

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#3795]
- The roles for filtering users on the Users page are not user friendly

![image](https://user-images.githubusercontent.com/3626859/197189755-ec27c639-51e9-4675-8ad0-2ef0160532a5.png)

- The apply button goes out of screen on smaller devices.

![image](https://user-images.githubusercontent.com/3626859/197189828-2cf4dd26-52fb-4703-9e7f-af4a7ef2a4bf.png)

**Comment by rithviknishad** [comment]
@Ashesh3  Use the new tailwind components and FilterButtons component coming via: https://github.com/coronasafe/care_fe/pull/3744

**Comment by Ashesh3** [comment]
> @Ashesh3 Use the new tailwind components and FilterButtons component coming via: #3744

Sure! Thanks for the heads up.

**Comment by rithviknishad** [comment]
Completed via: https://github.com/coronasafe/care_fe/pull/3863
