### ISSUE TITLE
Add "mark as cured" checkbox in new medical history

### ISSUE THREAD

**Issue by aeswibon** [coronasafe/care_fe#3800]
- [ ] Additional Feature (may be separated out as a separate issue)
While viewing saved medical history, For every saved date, ICD and description, there needs to be an option on the right-hand side to "mark as cured". This will allow the system to not only list all the diseases the patient has but also understand which of them is already cured.

Part of #3361

**Comment by nihal467** [comment]
@cp-Coder Due to inactivity, unlinking you from this issue

As per the communication with @aparnacoronasafe , it will be sub-grouped with events module, so for time-being marking the issue as blocked

**Comment by aparnacoronasafe** [comment]
closing. this may be taken up along with #3361
