### ISSUE TITLE
Unable to file log update without setting review time

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3814]
**Describe the bug**

when we are saving, log update without review time, unable to file it.

**To Reproduce**

https://care.coronasafe.in/facility/5092d953-6742-49b0-b1e3-025c53a89e8a/patient/18bc83ce-de77-490b-9ab0-038c416984a8/consultation/3972b37c-760b-4db1-8e5e-150ff6cc7505/daily-rounds

**Expected behavior**

review time is not mandatory

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/197411068-59aab3bf-3cd7-4e28-baba-7522529802c8.png)

**Comment by khavinshankar** [comment]
@nihal467 this has been a recent change in the backend regarding https://github.com/coronasafe/care_fe/issues/1255#issuecomment-1256315589. 

@aparnacoronasafe @gigincg So should I have to make the Review After optional?
