### ISSUE TITLE
Modify Timeout Notification in Care

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3820]
**Describe the bug**

When a user is time-out of the care, the notification is saying 'Invalid token' and signed out of care platform to the login page

**Expected behavior**

Put a proper notification in the care platform, when a user is been timeout !

**Comment by Ashesh3** [comment]
@nihal467 Would something like a "Session expired" popup be more user friendly than the "Invalid Token" popup?

Sample:
![image](https://user-images.githubusercontent.com/3626859/197544340-aaa95c57-44d7-4462-aa15-5ea08260826e.png)

**Comment by nihal467** [comment]
@Ashesh3 this look good to me ! Take a approval from @aparnacoronasafe or @gigincg then only start working on it

**Comment by Ashesh3** [comment]
Discussed on EOD: The user is to be redirected to a separate page (public endpoint) where the "Session Expired" message is shown.
