### ISSUE TITLE
Relevance of Covid Status in the Patient Creation Form and detail Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3856]
![image](https://user-images.githubusercontent.com/57055998/198816569-8ec86daf-caa6-49a1-ac9c-8e6da870b75c.png)
![image](https://user-images.githubusercontent.com/57055998/198816707-68cb2b0c-02ad-47e2-81ad-6173744b22dd.png)

- [ ] Is it mandatory to mark the covid status of a patient and covid test type in the patient creation form,
- [ ] shall we change this covid status in the patient detail page, to something really relevant in the field right now

**Comment by nihal467** [comment]
@aparnacoronasafe can you review the issue and provide an insight

**Comment by aparnacoronasafe** [comment]
remove the covid disease status field altogether from health profile

**Comment by nihal467** [comment]
it will be addressed in the https://github.com/coronasafe/care_fe/issues/7732
