### ISSUE TITLE
Provisional Diagnosis and Diagnosis text box are case sensitive

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3860]
**Describe the bug**

We are having two diagnosis, Provisional Diagnosis and Diagnosis in the consultation form. When we input the data in the text box, the results generated in the droplist are different. Eg : 1A

![image](https://user-images.githubusercontent.com/57055998/198819569-c41d0741-459a-4007-a8f4-82f4bf6c8e92.png)
![image](https://user-images.githubusercontent.com/57055998/198819583-98a90e73-bf86-4c93-9d36-beac24e28d20.png)

Does the results being case-sensitive are intentional behavior ?

**Comment by khavinshankar** [comment]
@nihal467 no, this should be an easy fix at the backend

**Comment by khavinshankar** [comment]
Fixed
