### ISSUE TITLE
User Creation Page droplist malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3871]
**Describe the bug**

when we search a facility in the user creation page, the whole droplist seem stuck and feel like broken, after a facility is been selected

**To Reproduce**

https://care.coronasafe.in/user/add

**Expected behavior**

- when a facility is selected in the droplist, the drop list vanish, and the badge mentioning the facility should come along with cursor come again to text box for typing the next facility name or someother behaviour can be used, whichever is good for better UI

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/198835609-f4fa30dc-6412-4206-8a15-9677db3a64ee.png)

**Comment by nihal467** [comment]
@Ashesh3 can you work on it ASAP

**Comment by Ashesh3** [comment]
> @Ashesh3 can you work on it ASAP

Sure!

**Comment by Ashesh3** [comment]
Hey, it seems to be working here, the only issue being the dropdown (at the right end) is misaligned when facilities are selected. Is that correct? @nihal467
![msedge_mrT8Y3lG08](https://user-images.githubusercontent.com/3626859/198842976-8b835c90-dfd0-452c-9b49-a53fb6641489.gif)

**Comment by nihal467** [comment]
@Ashesh3 yeah, but when we select a facility in the drop list, even though it is getting selected, to close the droplist and type a new facility , we need to click somewhere outside right. Can we have like when a facility is selected , the droplist closes and text box clear and we type in the new facilty name

**Comment by Ashesh3** [comment]
> @Ashesh3 yeah, but when we select a facility in the drop list, even though it is getting selected, to close the droplist and type a new facility , we need to click somewhere outside right. Can we have like when a facility is selected , the droplist closes and text box clear and we type in the new facilty name

Sure, made the PR.
