### ISSUE TITLE
Tailwind Patient Registration

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3872]
Mockup for Forms with Sections and a Sidebar (sidebar like the one in the asset update page) for the patient registration page?

Current Sidebar with Sections in Asset update: https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/assets/d170feb5-8961-41bc-a990-090c6906f35f

**Comment by rithviknishad** [comment]
Will be worked on after #4309 is merged, along with adding the `Form` component.

**Comment by nihal467** [comment]
@rithviknishad what is the status on this issue

**Comment by rithviknishad** [comment]
@nihal467 I've built the form builder, will continue working on it and open a draft PR once other priority issues assigned to me are completed.
