### ISSUE TITLE
Dashboard Redirection to be fixed in platform

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3873]
![image](https://user-images.githubusercontent.com/57055998/198839346-6b5ae224-4bd1-4c84-badb-10f4421e3472.png)

fix the redirection of dashboard

**Comment by nihal467** [comment]
had a conversation with @mathew-alex, he will be working on it with @khavinshankar

**Comment by mathew-alex** [comment]
@nihal467  - Closing this issue since the issue was resolved some time back.
