### ISSUE TITLE
droplist in user creation page is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3876]
**Describe the bug**

- [x] in the droplist of the user management, we can select a facility twice from the droplist and it will cause an error stating, some facility are not available

**To Reproduce**

https://deploy-preview-3874--care-net.netlify.app/user/add

**Expected behavior**

- [x] once a facility is selected in the droplist, we shouldn't be able to select it again from the list
- [ ] make the green background appear similar to the bottom screenshot for all pre-selected facility before a new search occurs

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/198865753-3f5f6c35-4065-40c4-82f8-12f52744db8a.png)
![image](https://user-images.githubusercontent.com/57055998/198865807-fffcb51b-c2ce-44ee-af18-e6984127b31c.png)
![image](https://user-images.githubusercontent.com/57055998/198870294-c0fcf5bf-74fb-4daa-be5c-987a243eb5ac.png)

**Comment by rithviknishad** [comment]
@nihal467 users can be linked to multiple facilities

**Comment by nihal467** [comment]
@rithviknishad 
![image](https://user-images.githubusercontent.com/57055998/198870310-159d91d6-913f-400f-a157-d9fafd68b465.png)

we can select same facility twice and two badges are also coming up due to this issue
