### ISSUE TITLE
Back button malfunction in bed management page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3879]
**Describe the bug**

When we create a 3-4 of bed in bed management page and suddenly want to go back to the location management page, both the back button is not taking me  back to location management page immediately, it only take me to my previously visited page.

**Reproduce**

https://care.coronasafe.in/facility/be6211ba-9057-41eb-9a0d-b1800d76c2e7/location/a07b8cd9-2244-44f6-8f05-a36cff89c6fa/beds

**Expected Behavior**

When we click on the browser back button or the back button in the platform, one should be taking us to the previous visited page and another one take us to the previous page by looking at the page path

**Screenshot**
![image](https://user-images.githubusercontent.com/57055998/198867788-177b7059-8dbb-44b8-b4ed-1c5f14e5e291.png)

**Comment by nihal467** [comment]
@khavinshankar @gigincg is it expected behaviour

**Comment by khavinshankar** [comment]
@nihal467 it is an expected behaviour, similar to chrome's back button.

But i think going back to Location Management makes ux better

**Comment by gigincg** [comment]
@nihal467 Please use all pieces of the issue template.

Describe the bug, Expected Behaviour, Current Behaviour and others

**Comment by nihal467** [comment]
@khavinshankar post the update on this PR

**Comment by khavinshankar** [comment]
Fixed in https://github.com/coronasafe/care_fe/pull/4016
