### ISSUE TITLE
Add Waveform preview in asset configuration page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3890]
**Describe the bug**

We are unable to detect the particular configured vital asset are online or not, since there is no preview available for the  vitals in the asset configuration. To check whether it is working or not, we have to open patient consultation page

**To Reproduce**

https://care.coronasafe.in/assets/2b3731b6-4ccc-438b-a2b4-0303ba4cc909/configure

**Expected behavior**

a preview of vital will enhance the experience during configuring a 5-para monitor

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/198891498-82b75fa0-36f9-4148-a79c-13ab944c02bf.png)

**Comment by gigincg** [comment]
@skks1212 Can you take this up?
