### ISSUE TITLE
We cannot upload files from localhost in FileUpload Page 

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#3895]
**Describe the bug**
We cannot upload files from localhost in FileUpload Page 

**To Reproduce**

1. Go to any Patient in localhost:4000
2. Click on Files Tab
3. Upload any file

**Expected behavior**
A file should be uploadable from Local Host

**Screenshots**
![image](https://user-images.githubusercontent.com/59426397/198968906-b127eb34-a40c-4eb5-817d-13c6d95c80a9.png)

**Comment by patelaryan7751** [comment]
Hey @mathew-alex i think we need to allow localhost.

**Comment by mathew-alex** [comment]
@patelaryan7751 - allowed localhost
