### ISSUE TITLE
Link new facility droplist malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3904]
**Describe the bug**

when we are linking a new facility to a existing user, the droplist of the facility is not fully visible

**To Reproduce**

https://care.coronasafe.in/users#

**Expected behavior**

the droplist should be fully visible

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/199203105-6c20c417-678f-4fbd-950a-d71195bc9441.png)

**Comment by khavinshankar** [comment]
fixed in #3906
