### ISSUE TITLE
Cypress failed Label not working within actions

### ISSUE THREAD

**Issue by rabilrbl** [coronasafe/care_fe#3905]
For failed cypress tests label
![image](https://user-images.githubusercontent.com/63334479/199206432-6be54dc3-bd3f-4bd2-a9a8-3aaadebc7aae.png)

**Comment by rabilrbl** [comment]
Possble solution is by switching cypress workflow trigger from `pull_request` to `pull_request_target`. [Ref](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)

cc: @khavinshankar

**Comment by khavinshankar** [comment]
@rabilrbl is this happening for forks?

**Comment by khavinshankar** [comment]
@rabilrbl can u give a link of the pr or action where this is happening

**Comment by rabilrbl** [comment]
> @rabilrbl can u give a link of the pr or action where this is happening

I tried fixing in a closed PR, here's the action logs https://github.com/coronasafe/care_fe/actions/runs/3368933763/jobs/5588029072
[PR](https://github.com/coronasafe/care_fe/pull/3903)

Another actions log where I caught this issue for the first time [coronasafe/care_fe/actions/runs/3365499308/jobs/5581021902](https://github.com/coronasafe/care_fe/actions/runs/3365499308/jobs/5581021902)
