### ISSUE TITLE
Create custom Modals

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#3908]
**Is your feature request related to a problem? Please describe.**
This is part of moving away from material ui

**Describe the solution you'd like**
Create a custom Modal with tailwind and headlessui and replace the existing mui dialog or modals

cc: @nihal467

**Comment by rithviknishad** [comment]
### Components to be built

- [ ] `Dialog`

```
expected props:
- title
- description (optional)
- children
- onClose (optional)
- show
```

- [ ] `ConfirmActionDialog` (useful for confirm archive/delete or other critical operations)
```
props additional to above:
- action: string (eg. "Delete")
- severity: warning / danger
- onConfirm
- onCancel
- confirmationText
```

example: 
![image](https://user-images.githubusercontent.com/25143503/199214031-c0d8cc26-de3f-4c35-8b73-6f221a52e35e.png)


cc: @khavinshankar @gigincg
