### ISSUE TITLE
Unable to Close droplist of facility pop-up in patient page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3915]
**Describe the bug**

we are unable to close the droplist in the facility pop-up coming up after we click add patient button in the patient page by clicking outside the droplist 

**To Reproduce**

https://care.coronasafe.in/patients

**Expected behavior**

when we click outside the droplist, it should be closing the droplist

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/199281455-619fe70c-7c80-4b29-8d5e-5f36e3c51e20.png)

**Comment by Ashesh3** [comment]
@nihal467 can we merge this with #3886 ?

**Comment by nihal467** [comment]
@Ashesh3 if you can push the PR by tomorrow merge the issues, otherwise don't merge it
