### ISSUE TITLE
Feature : Allow users to add profile picture in care platform

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3924]
**Is your feature request related to a problem? Please describe.**

**Issue : Wishlisted with least priority**

Currently, every user image in a standard icon beside the name in the bottom of the page

**Describe the solution you'd like**

- [ ] allow user to add personalised image by going to their profile page in the care platform
- [ ] if the user doesn't upload any personalised image, the profile picture area should be showing avatars related to there user type

**Additional context**

![image](https://user-images.githubusercontent.com/57055998/199413867-b09ec0d1-3fe4-4e67-9b61-3749ae53a92e.png)

**Comment by ayushjnv1** [comment]
assign to me if this feature we want

**Comment by rithviknishad** [comment]
@ayushjnv1 are you sure? This will require changes in the backend to be made too.

**Comment by nihal467** [comment]
@rithviknishad @ayushjnv1 this is a wishlist item with the very least priority

**Comment by nihal467** [comment]
It's just an idea. If someone decides to work on it, please confirm during the end-of-day call the approach towards the issue. Once approved, proceed with the work.

**Comment by jainvedant392** [comment]
Hey @nihal467, can I get this issue assigned? I discussed about it in the EOD call.

**Comment by nihal467** [comment]
@jainvedant392 Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by jainvedant392** [comment]
@nihal467 sorry for the inactivity due to my assignments and end semester exams, can I get this assigned after I get free from my exams, as I'll be available to work on it then?

**Comment by UdaySagar-Git** [comment]
@rithviknishad can i get this assigned ?
