### ISSUE TITLE
Use Weblate for translations

### ISSUE THREAD

**Issue by comradekingu** [coronasafe/care_fe#3930]
With the recent use of Crowdin, this creates a problem not only its inherent usage and terms of service problems,
and makes avoiding the full scope of them down the road an alluring benefit of moving away.

I suggest https://hosted.weblate.org/hosting

For the full disclosure I have contributed to Weblate, and I have used both extensively.

**Comment by nihal467** [comment]
Since it is recognised as spam, closing this issue

**Comment by comradekingu** [comment]
@nihal467 I was encouraged to open it in https://github.com/coronasafe/care_fe/issues/3377#issuecomment-1299648649
The concerns are sadly very legitimate ones.
