### ISSUE TITLE
Log update category color is not using actual patient category colors

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3932]
**Describe the bug**
Each type of patient category has its own colours respectively. However, the category chip in the log update tile is not using the correct colours.

**To Reproduce**

1. Go to any patient's page that has log updates: https://care.coronasafe.in/facility/01810c32-ec26-494a-9e65-40e5547a7746/patient/9c6a4951-916e-439b-b41a-853b6980fefa/consultation/a8003ba0-9c0a-4d27-95b2-d3bd3139652f

**Expected behavior**
Category color in log update should have correct colours.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/199670262-4d961477-08e9-49e2-b4e7-4ca622cd69ff.png)

**Comment by nihal467** [comment]
@rithviknishad do, always follow the template while filling the issue,
