### ISSUE TITLE
Auto-fill the state and district from the pincode inputted by user

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3940]
**Is your feature request related to a problem? Please describe.**

Currently, user has to fill all the data manually in the facility creation form

**Describe the solution you'd like**

Autofill the state and district in the facility creation form, when user input the particular pincode.

**Additional context**

![image](https://user-images.githubusercontent.com/57055998/199774283-a08ee9d7-7c13-4124-b2f1-94ef9a5b01aa.png)

**Comment by rithviknishad** [comment]
As discussed in EOD, we could make use of http://www.postalpincode.in/Api-Details
