### ISSUE TITLE
Triage old data is getting replaced with new data in facility

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3950]
**Describe the bug**

When we submit multiple triage data entry for a single date in the facility page, the last submitted one will be replacing the old data of the date

**To Reproduce**

https://care.coronasafe.in/facility/c4463366-0e21-45c0-9da3-25457e7413e5

**Expected behavior**

- [ ] when someone submitting a triage data, and if a data already exist for the specific date, a pop-up comes on submission stating "data will be replaced"

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/199972627-d7ec2681-8905-4e22-9f6e-81063b84434d.png)

**Comment by patelaryan7751** [comment]
i am working on it i would be giving a PR this week

**Comment by patelaryan7751** [comment]
I would be working on it and giving a PR soon.
