### ISSUE TITLE
Last admitted to advanced filter on patient tab is not working properly

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3953]
**Describe the bug**

Duplicate of issue : #3482 

When we use the last admitted to advanced filter on patient tab, "Something went wrong" error popping up.

**To Reproduce**

1. Go to patient tab
2. Click on advance filter
3. Scroll down to last admitted to filter and apply it

**Expected behavior**

- [ ] remove the last admitted to (bed type ) filter entirely
- [ ] replace the filter with a new one called " Admitted to ( Bed Type ) "
- [ ] the new filter "Admitted to (Bed Types)" should be having options : 
- isolation,
- ICU
- Bed with oxygen support
- Regular

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/200050035-f172935b-3383-4644-8bcf-c53653902eea.png)

**Comment by nihal467** [comment]
@cp-Coder work on it ASAP

**Comment by aeswibon** [comment]
Sure @nihal467
