### ISSUE TITLE
Illustration for Notice board when no notices available

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3957]
**Is your feature request related to a problem? Please describe.**
Currently, when no notices are there on the notice board, it shows a simple card that says "No notices for you"

![image](https://user-images.githubusercontent.com/25143503/200099450-48f696d9-33b0-4aa2-8fad-2f725e161f9d.png)

**Describe the solution you'd like**
An art like the 404 / session expired page.
Something like: (or any other)
![image](https://user-images.githubusercontent.com/25143503/200099543-54d4da77-afeb-41ce-bd41-3a027bc6936b.png)

**Comment by nikhilagastya** [comment]
@Pragati1610  @rithviknishad @mathew-alex  can i work on this issue !

**Comment by rithviknishad** [comment]
yes

**Comment by nikhilagastya** [comment]
hey @Pragati1610 @rithviknishad  @mathew-alex  kindly review the PR for this issue and lmk any changes if needed

**Comment by nikhilagastya** [comment]
![Screenshot 2023-05-26 182127](https://github.com/coronasafe/care_fe/assets/72994295/c8bc46ad-2fca-4091-8e0d-5b1c38d8957a)

**Comment by nikhilagastya** [comment]
hey @rithviknishad  can you review the PR (#5544 ) issued to this issue.

**Comment by rithviknishad** [comment]
Kindly link PRs with issues @nikhilagastya using closing keywords: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
