### ISSUE TITLE
Consultation page is loading in the middle of the page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3975]
**Describe the bug**

When we are opening the consultation update from the patient detail page, the consultation page is loaded in the middle part of the page

**To Reproduce**

https://care.coronasafe.in/facility/c4911f55-d4f7-4b36-bbcb-9b115d1bfe2c/patient/88986c19-3ab5-4820-b35d-7b7d95ac4f00

**Expected behavior**

load the top part of consultation page

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/200159397-7d5cb460-145a-48cf-bdc7-912434ef1182.png)

**Comment by Ritesh-Aggarwal** [comment]
This issue is fixed in #3948 .
https://deploy-preview-3948--care-egov-staging.netlify.app/facility/c4911f55-d4f7-4b36-bbcb-9b115d1bfe2c/patient/88986c19-3ab5-4820-b35d-7b7d95ac4f00
