### ISSUE TITLE
Correction of the logos present in the  discharge summary of a patient

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3978]
**Describe the bug**

- [ ] Currently, the discharge summary of a patient is only having the coronasafe and government of kerala logo in the generated email

**To Reproduce**

https://care.coronasafe.in/facility/01810c32-ec26-494a-9e65-40e5547a7746/patient/9c6a4951-916e-439b-b41a-853b6980fefa/consultation/a8003ba0-9c0a-4d27-95b2-d3bd3139652f 

**Expected behavior**

Will discuss on EOD call

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/200161670-3c819ba1-afe1-47db-95b2-bcaf6c41364f.png)
[mohd nihal-Discharge_Summary.pdf](https://github.com/coronasafe/care_fe/files/9945391/mohd.nihal-Discharge_Summary.pdf)

**Comment by nihal467** [comment]
Remove the government logo and replace coronasafe logo with care logo

**Comment by aeswibon** [comment]
@nihal467 I have opened the PR to fix this issue. Can you check the PR? I have added the sample screenshot in the PR

**Comment by nihal467** [comment]
@cp-Coder the sample screen shot looks good
