### ISSUE TITLE
DateRangePickerV2 should not allow selecting end date that's before start date.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3983]
**Describe the bug**
Currently in the DateRangePickerV2 component, it allows picking an end date that's before the start date. This should not be allowed.

**To Reproduce**

1. Go to advanced patient filter.
2. Set any of the date filters to reproduce the above issue.

**Expected behavior**
The dates in the end date should not be selectable/clickable that's before the start date.

**Screenshots**

https://user-images.githubusercontent.com/25143503/200177529-dadd17c9-0218-4e89-8a88-1425ab176bcc.mp4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khavinshankar** [comment]
@cp-Coder what's the status of this issue

cc: @nihal467

**Comment by aeswibon** [comment]
The issue has already been fixed

**Comment by rithviknishad** [comment]
Issue is still present in the patient filters
