### ISSUE TITLE
Too much whitespace when a log updates list page has too little cards on the current page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3985]
**Describe the bug**
Too much whitespace when a log updates list page has too few cards on the current page

**To Reproduce**

1. Go to a patient that has lots of log updates [Patient: Madhu in staging](https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/8cb90ab1-1f13-4b86-91c7-7eb6a70b51c5/consultation/0eca832f-9640-48f8-b390-0f7d1b1ac2e5)
2. Observe when there are only one or two cards on the last page of the log update, the pagination bar is placed very far away from the end of the list.

**Expected behavior**
Let the pagination bar snap at the end of the log updates list without whitespace.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/200179110-eb04b7ef-c4eb-4b46-8d74-120f685ed4f2.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nihal467** [comment]
removing stale, as I can see a PR has been linked, will be following up with Kunal on the status of the PR

**Comment by aeswibon** [comment]
Closing this issue as it is already been fixed
![image](https://user-images.githubusercontent.com/77210185/221867611-c7c9c56c-07aa-4c3a-8d5e-45609b1c2cf1.png)
