### ISSUE TITLE
Redesign and generalization for SlideOver components.

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#3995]
![image](https://user-images.githubusercontent.com/23238460/200374196-2fd42b4b-b2c3-4d9e-86e0-d7d5510d2cbb.png)

**Comment by nihal467** [comment]
@skks1212 @rithviknishad what is the status on this issue

**Comment by rithviknishad** [comment]
@nihal467 the related PR had been broken down into smaller PRs. Few of them (including the one that implements the SlideOver) are completed and merged, advanced filters are pending.

**Comment by rithviknishad** [comment]
@skks1212 shall I proceed with wrapping with Slideover for Advanced Filters without waiting for the schema-based filters thing?

**Comment by shivankacker** [comment]
@rithviknishad yes sure, we can work on the schema ones after

**Comment by rithviknishad** [comment]
@nihal467 ETA soon after HCX
