### ISSUE TITLE
Update Asset dropdown bug

### ISSUE THREAD

**Issue by kunatastic** [coronasafe/care_fe#3998]
**Describe the bug**
The additional 
**To Reproduce**

1. Go to http://localhost:4000/facility/4e09588e-9d4f-40f1-8d27-e202318c86c0/assets/cb375835-3afa-4304-9cd3-ec11dd0ace3d
2. Click on Asset class dropdown
3. On dropdown opening the component will shift left

**Expected behavior**
The component must not shift

**Screenshots**

https://user-images.githubusercontent.com/61267953/200456045-57506143-2d8a-4857-9a37-161fe2aee9e2.mov

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rithviknishad** [comment]
Duplicate of #3882 @kunatastic

**Comment by rithviknishad** [comment]
Closing as #3882 is merged and this issue is no longer present in staging.
