### ISSUE TITLE
Facility search not working properly

### ISSUE THREAD

**Issue by GokulramGHV** [coronasafe/care_fe#4003]
**Describe the bug**
When searching for a particular facility, it shows the total no. of facilities to be a number that is greater than zero, but it says no facilities found.
The above issue only occurs when the facility list in not in the first page of the pagination.

**To Reproduce**

1. Go to [ttps://care.coronasafe.in/facility](ttps://care.coronasafe.in/facility)
2. Scroll down to the pagination
3. Change the page to any other page other than page 1.
4. Now search for a particular facility

**Expected behavior**
"No facilities found" should not be displayed when the total facilities is greater than zero when searching for a particular facility.

**Screenshots**
![image](https://user-images.githubusercontent.com/40627011/200577039-cd1dc642-6bf3-4395-844f-029708ee64f1.png)

**Comment by nihal467** [comment]
@GokulramGHV @gigincg the issue seems to be resolved, feel free to reopen if it persist
