### ISSUE TITLE
Patient dashboard: Text overflowing in buttons

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4007]
**Describe the bug**
When the side nav menu is expanded, there is not enough space for text in buttons on top right of the page

<img width="300" alt="Screenshot 2022-11-09 at 10 53 03 AM" src="https://user-images.githubusercontent.com/67050716/200745891-5d2c4cdf-e2cc-48e3-a6b2-4f35b3341af8.png">

Fix the spacing

**Comment by rithviknishad** [comment]
This is Facility Dashboard, which is redesigned in #3819 .
@aparnacoronasafe could you check the deploy of that?

**Comment by rithviknishad** [comment]
https://deploy-preview-3819--care-net.netlify.app/
