### ISSUE TITLE
alignment of buttons on Facility list

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4012]
On the facility list, when there are two facilities listed in the same row, and one facility card has more labels, the content in the adjacent facility card is not aligned properly.
<img width="1152" alt="Screenshot 2022-11-09 at 4 11 06 PM" src="https://user-images.githubusercontent.com/67050716/200813555-9956e9ca-6ff9-42f4-a63f-f72d98dc30d4.png">

The buttons for notify, facility and patients must be pinned to the bottom of the card

**Comment by rithviknishad** [comment]
@aparnacoronasafe duplicate of #3954
