### ISSUE TITLE
Movement of icons in Sidebar

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4014]
https://user-images.githubusercontent.com/67050716/200843723-41a32837-11a0-4ce3-84bf-f54f9cb497dc.mov

When the pointer is taken to the side nav bar, the icons move upwards, resulting in the user always accidentally clicking the icon below the one intended to click.

The icon placement must be consistent, whether pointer is on the side nav bar or not

**Comment by rithviknishad** [comment]
Already been solved by #3991 and it's been merged. Issue not present in staging. Could you try hard refreshing the page?
