### ISSUE TITLE
Replace Download Live Patients and All Patients to DropdownMenu as Export

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4023]
**Is your feature request related to a problem? Please describe.**
As discussed in EOD, Download all patients and the live list can be shrunk to one menu button.

**Describe the solution you'd like**
Replace Download Live Patients and All Patients to DropdownMenu as Export

**Comment by nihal467** [comment]
@rithviknishad is this discussed on EOD ?

**Comment by rithviknishad** [comment]
@nihal467 yes
![image](https://user-images.githubusercontent.com/25143503/201342750-b4559665-659c-4fd1-85a8-45070e894fd9.png)

**Comment by rithviknishad** [comment]
Duplicate of #4252
