### ISSUE TITLE
Location update of facility not working

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4031]
**Describe the bug**
When we update the location of a facility, it doesn't get updated
![image](https://user-images.githubusercontent.com/70687348/201289023-2fdb8683-be87-4d07-98e3-a7d37911e1c4.png)

![image](https://user-images.githubusercontent.com/70687348/201289000-de047438-db00-4691-95fd-87112b9b15ce.png)

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/fc68d1a4-dbd7-4fde-b987-cb26e7e2048a/update
2. Update the values of location
3. Click Update

**Expected behavior**
The location variables should get updated

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pranshu1902** [comment]
Fixes [#1095](https://github.com/coronasafe/care/issues/1095) in the backend

**Comment by nihal467** [comment]
@Pranshu1902  #3817 check this PR, seem the issue in getting resolved in this, can you check it and comment it

**Comment by Pranshu1902** [comment]
Solved in #3817
