### ISSUE TITLE
ECG waveform is breaking in patient consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4047]
**Describe the bug**

- [ ] the ECG sometimes malfunctions like a shivering

**To Reproduce**

https://care.coronasafe.in/facility/9a96c9d3-1ae6-4a69-ad1e-162d0e318d31/patient/2d825e30-b589-4798-aa1b-fce7fa6259fa/consultation/5209b2e8-977c-459b-b0ee-c7ad4576ff8d

**Expected behavior**

Make the waveform efficient

**Screenshots**

https://screen-recorder-bucket.s3.ap-south-1.amazonaws.com/ScreenRecorder_2022-11-09_c8bf154b-9a7c-4ec1-9acc-06cbb966748a.mp4

![image](https://user-images.githubusercontent.com/57055998/201510611-f9022cc4-72c7-4e2a-af52-82640dc3f10e.png)

**Comment by shivankacker** [comment]
@nihal bug 1 is expected behaviour. Will work on the others👍

**Comment by nihal467** [comment]
@skks1212 discussed on yesterday's EOD, the approach for this issue. Post an update on this issue ?

**Comment by nihal467** [comment]
@skks1212 what is the update on this issue

**Comment by shivankacker** [comment]
@nihal467 I have been working to find a reason for the stuttering for a while. Right now the waveforms dont seem to be connected. I am removing my assignment but will be actively trying to find a solution. Anyone else who could find a solution is free to assign it to themselves.

**Comment by nihal467** [comment]
the issue is resolved
