### ISSUE TITLE
Upload file still working for discharged patients

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4060]
**Describe the bug**
We can still upload patient files for discharged patients.

**To Reproduce**
Try to upload patient files for any discharged patient

1. Go to https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient/0fcb6bf8-99c2-4c22-a259-0e358b060865/consultation/c3514b0d-79e8-4b34-a46b-f28edcc0e73f/files
2. Upload a file

**Expected behavior**
The upload button should be disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/202095221-d6660d68-956d-4aa1-8533-3fc4fdcb1634.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khavinshankar** [comment]
@nihal467 @Pranshu1902 It would be a good idea to also block it in the backend
