### ISSUE TITLE
Monitoring Page for Waveforms

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#4067]
Create a dedicated page that monitors 5 Para Monitors in a specific hospital

**Comment by nihal467** [comment]
@Ritesh-Aggarwal what is the status of this Issue

**Comment by Ritesh-Aggarwal** [comment]
I am yet to work on this, if anyone else wants they can pickup this issue, sry for the delay

**Comment by rithviknishad** [comment]
Started working on it from yesterday
