### ISSUE TITLE
State-admin are unable to create a log-update for a patient

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4105]
**Describe the bug**

With state-admin access (Ernakulam District), when we try to create a log update for a patient (Alappuzha district), it is showing an error that the user has no permission for the action.

**To Reproduce**

https://care.coronasafe.in/facility/534e2a46-0998-42e8-8c02-fd2c3a06e0f8/patient/5089286d-900f-4826-b5da-513ed69ec70a/consultation/f8c89a97-2322-430a-ad26-bfe48f01ac2c

**Expected behavior**

 a state admin should be able to create log-update for all patients across the state

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/203712201-87f59877-3c6f-4bc5-a71b-e606c5e0f441.png)

**Comment by nihal467** [comment]
@cp-Coder what is the status on this update

**Comment by aeswibon** [comment]
@nihal467 I am not able to reproduce the issue now. Can you check again whether this issue still persist or not?

**Comment by nihal467** [comment]
issue is been resolved
