### ISSUE TITLE
Review Time is breaking patient detail page UI

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4115]
**Describe the bug**

When the review time badge is coming in the patient detail page, it is breaking the UI

**To Reproduce**

https://care.coronasafe.in/facility/a4a2f329-6ace-42ac-90c5-8d3d56f8e5e9/patient/48c5b043-d667-4283-b8fd-f624a567bbce

**Expected behavior**

The Ui should be having an effective utilization of white space, even when the review time badges come into the page

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/57055998/204002544-f6e345aa-eeef-40be-80c8-9e1e70ba8b35.png)

**Comment by khavinshankar** [comment]
@nihal467 downgrading it to a P2 issue as this doesn't break anything, It will be ready by this week
