### ISSUE TITLE
The profile page of a user is misaligned

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4126]
**Describe the bug**

when we click the update profile page, the spacing and the alignment of the page is not proper

**To Reproduce**

https://care.coronasafe.in/user/profile

**Expected behavior**

the edit profile page should be properly aligned 

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/204123902-1fa1ec17-2568-4e78-93b9-5738bd73c189.png)

**Comment by khavinshankar** [comment]
Todo
- [x] age field is misaligned
- [x] y-axis spacing is a bit much
- [x] page is not responsive
