### ISSUE TITLE
Cover Image Upload: Handle Errors; Add Hints

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#4139]
Updates needed to Improve UX for Facility Cover Image Upload

- [ ] Add a hint in the modal, specifying the max. file size, allowed formats along with the recommended aspect ratio
- [ ] Handle Errors when uploading fails. Currently it shows loading, infinitely

**Comment by khavinshankar** [comment]
@patelaryan7751 what's the status of this issue

**Comment by patelaryan7751** [comment]
yeah i would be doing it by today @khavinshankar
