### ISSUE TITLE
Solve the pagination Bug for Archived and Unarchived Files in FileUpload Component

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#4179]
**Describe the bug**
Solve the pagination Bug for Archived and Unarchived Files in FileUpload Component when the number of files increases by more than 14 then pagination should be visible as this is the results per page limit. But, here in 2 results, the pagination is visible which is not acceptable. The pagination is visible because it is based on the total count of files but we want pagination on the basis of the number of archived files and unarchived files respectively.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095/patient/dcc71a18-2b81-4d56-92c3-f4455aea4b0c/consultation/a014089f-ed53-4639-9b42-27ba8647f41f/files
2. Click on Archived File
3. Go to next page see archived files

**Expected behavior**
The archived files and unarchived files pagination need to be separated so that their count can be assigned to the pagination component
a backend filter is needed which is made in the PR https://github.com/coronasafe/care/pull/1112

**Screenshots**
![image](https://user-images.githubusercontent.com/59426397/205222374-6bede851-0fa9-41d1-b912-014cb763a9b3.png)
![image](https://user-images.githubusercontent.com/59426397/205222414-67a72f9f-6dbf-43f1-868d-891aecd7803c.png)

**Comment by patelaryan7751** [comment]
@cp-Coder What is the status on the https://github.com/coronasafe/care/pull/1112 .

**Comment by aeswibon** [comment]
I  have updated the PR. Waiting for it to be merged.
