### ISSUE TITLE
Facility Notify Textarea Not Accepting Input

### ISSUE THREAD

**Issue by naman114** [coronasafe/care_fe#4190]
**Describe the bug**
The textarea in the Facility Notify dialog box is not showing the input value when typing something into it

**To Reproduce**

1. Go to http://care.coronasafe.in/facility
2. Click on 'Notify'
3. Type something in the textarea
4. No value is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/57593654/205315230-f2d3bba9-160d-43ad-94de-3f59bd4f7805.png)

**Comment by nihal467** [comment]
@naman114 can you work on this ASAP
