### ISSUE TITLE
Clearing Advanced Filters For Facilities Collapses the Sidebar

### ISSUE THREAD

**Issue by naman114** [coronasafe/care_fe#4191]
**Describe the bug**
In the `Advanced Filters` for Facilities, the `Clear Filter` button collapses the Sidebar in addition to clearing the filters

**To Reproduce**

1. Go to http://care.coronasafe.in/facility
2. Click on 'Advanced Filters'
3. Click on 'Clear Filter'

**Expected behavior**
The `Clear Filter` button should just clear the filters and not collapse the sidebar

https://user-images.githubusercontent.com/57593654/208047371-b2faeaa1-8171-4f14-ba32-b62a3f1f52e4.mp4

**Comment by rithviknishad** [comment]
@naman114 this behaviour is solved as part of https://github.com/coronasafe/care_fe/pull/3996
