### ISSUE TITLE
Create config.json for Whitelabelling

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#4192]
We need to create a `config.json` file that would contain all environment variables relevant for Whitelabelling CARE.

There should be a useEffect in the App.tsx file, that does `fetch("./config.json") and initializes the global config for CARE.

The App should be "Loading" Until the `config.json` is fetched and the `config` state is initialized.

Here's a list of basic items we can whitelabel:
```
dashboard_url: "https://dashboard.coronasafe.network",
kasp_label: "KASP",
kase_full_string: "Karunya Arogya Sethu Padhathi",
enable_kasp: false,
government_logo: "cdn.coronasafe.network/xxx"
maps_api_key: "xxxxxxxxx",
sentry_api_key: "xxxxxxxxxx"
```

**Comment by rithviknishad** [comment]
Configurations for staging added to [coronasafe/care_deploy_configs/configs/](https://github.com/coronasafe/care_deploy_configs/tree/main/configs) directory.

cc: @mathew-alex

**Comment by rithviknishad** [comment]
Waiting for 
- #4514
