### ISSUE TITLE
Cancel button is malfunction in facility updation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4201]
**Describe the bug**

When we modify some data, by going to the facility updation page, and click the cancel button, the existing data are been modified on the facility page

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/63086719-10ec-4c6c-9b43-4b0f87ca6cba/update
2. Type any new data in any column
3. click cancel
4. see the error that the facility is been updated.

**Expected behavior**

when we click the cancel button on the facility updation page, we shouldn't be saving any modified data and exit the page.

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/205474893-a69b9845-be24-4d18-9e56-f87d9784c1a8.png)

**Comment by nihal467** [comment]
@cp-Coder this is a P1 issue, work on it ASAP

**Comment by aeswibon** [comment]
Sure
