### ISSUE TITLE
Change Export Asset button in asset detail page to secondary variant

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4205]
**Is your feature request related to a problem? Please describe.**

the export button in the asset detail page is kept along with other buttons

**Describe the solution you'd like**

We create a button like three dots, and when someone clicks on it, a dropdown comes in, with options like export as JSON, export as Spreadsheet, etc...

![image](https://user-images.githubusercontent.com/57055998/205476356-9f4f8567-018e-40ff-9e53-6e975d280c99.png)

**Comment by rithviknishad** [comment]
It was discussed to make this a secondary variant button instead of adding it to a dropdown.

cc: @nihal467
