### ISSUE TITLE
Modify Weight and Height data in Summary Page of patient consultation

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4211]
**Describe the bug**

When the height and weight of the patient are not mentioned on the consultation page, it is showing " - Kg " and " - Cm" on the summary page. 

**To Reproduce**

https://care.coronasafe.in/facility/63086719-10ec-4c6c-9b43-4b0f87ca6cba/patient/a340dbd4-8ee2-4660-8b97-67190707ebda/consultation/a1fb18bd-442c-41b3-a989-6a832ebf9047

**Expected behavior**

A few suggestions from my side:

- [ ] We replace "- kg " and " -cm " by displaying " 0 " when height and weight are not mentioned on the patient
- [ ] We don't display weight and height on the summary page, when height and weight are not mentioned on the patient
- [ ] We replace "- kg " and " -cm " by displaying " Nil " when height and weight are not mentioned on the patient

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/205478104-d94f430b-0f66-46e7-b1d5-84cdcb77cd10.png)

**Comment by nihal467** [comment]
@gigincg @aparnacoronasafe let me know which expected behaviour we should be following

**Comment by gigincg** [comment]
I think the current behaviour is expected behaviour

**Comment by aparnacoronasafe** [comment]
This is the expected behavior. lets not change it
