### ISSUE TITLE
The "Post Doctor Notes" button on hovering does not show disabled symbol when it is disabled

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#4213]
**Describe the bug**
When a patient is discharged the posting of doctor notes is disbaled. The "Post Doctor Notes" button on hovering does not show disabled symbol when it is disabled

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095/patient/4c16ebcd-87fb-4c51-bbad-82b3ac60006b/notes

**Expected behavior**
When hovering on the button the pointer should change to disabled symbol

**Screenshots**
![image](https://user-images.githubusercontent.com/59426397/205484529-0fc88962-9e71-4b48-8f68-6b457872ca16.png)

**Comment by ShenoyAman** [comment]
can I take this issue
