### ISSUE TITLE
Cypress: Add doctor's note to a patient page

### ISSUE THREAD

**Issue by rabilrbl** [coronasafe/care_fe#4235]

**Comment by SahilSingh177** [comment]
@nihal467, Can I work on this issue as #5602 is currently under review?

**Comment by nihal467** [comment]
@SahilSingh177 sure

**Comment by nihal467** [comment]
@SahilSingh177 unassigning you from the issue due to inactivity

**Comment by Ashesh3** [comment]
@nihal467 We now have a cypress test for posting doctor notes. Can this issue be closed?

**Comment by Ashesh3** [comment]
We now have a cypress test for posting doctor notes
