### ISSUE TITLE
Facility Update form giving success notification even on cancellation

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4261]
**Describe the bug**
When I click on update facility and then cancel update, I still get the `Facility updated` notification

**To Reproduce**
Open a facility and click on update facility. On the form, scroll down and click on `Cancel`

1. Go to https://care.coronasafe.in/facility/e3311351-3ec9-4cb0-a6e1-902225ac705c/update
2. Click on Cancel
3. See the error

**Expected behaviour**
The user should be just redirected to the facility home page without any notifications.

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/206645142-bc02de07-9853-42f2-8cb8-504dec26d51e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cp-Coder** [comment]
@Pranshu1902 This issue has already been fixed.
__PS__: Similar Issue: https://github.com/coronasafe/care_fe/issues/4201

**Comment by aeswibon** [comment]
@Pranshu1902 This issue has already been fixed.
__PS__: Similar Issue: https://github.com/coronasafe/care_fe/issues/4201
