### ISSUE TITLE
Text box and borderline are different across the platform

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4271]
**Describe the bug**

Currently, in multiple text box across the platform, the borderline and box outterline are in different spaces.

- [x] patient discharge notes
- [x] patient consultation page

**To Reproduce**

https://care.coronasafe.in/facility/f77a909d-95d3-4f4f-bb0d-18a715af82e4/patient/84c35aa2-1f32-412a-a461-6b97d1645c22/consultation/dd8ab0e5-156d-49d1-8b71-c3ac88d36d52

https://care.coronasafe.in/facility/f77a909d-95d3-4f4f-bb0d-18a715af82e4/patient/84c35aa2-1f32-412a-a461-6b97d1645c22/consultation/dd8ab0e5-156d-49d1-8b71-c3ac88d36d52/update

**Expected behavior**

the outline border and text-box border should be same.

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/206893300-18779b9a-7134-4690-af12-3e1b57efa090.png)
![image](https://user-images.githubusercontent.com/57055998/206893326-d3b01aff-5a40-42b5-9abd-6749819c5f69.png)

**Comment by nihal467** [comment]
@rithviknishad any Update on this issue

**Comment by rithviknishad** [comment]
@nihal467 I've made the changes by using the new tailwind components there. However now the form looks half old half new design and the new text area feels disabled because the new text area is gray background. 

Will update the colors of the component itself to white and link a PR by 11 AM.
