### ISSUE TITLE
Status doesn't change in the live camera feed of patient

### ISSUE THREAD

**Issue by siddnikh** [coronasafe/care_fe#4302]
**Describe the bug**
- The status of the live feed doesn't change regardless of the state. (For example: remains at *STATUS: LOADING* "Fetching Latest Feed")

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/01810c32-ec26-494a-9e65-40e5547a7746/patient/fcfad8af-bee7-4f6a-9773-25b7ae0a8031/consultation/5d8e7662-e2fb-4d10-8bf3-cf982d3ba0db/feed or any other patient camera feed.
2. If the feed does not load, the status remains as is (Loading).

**Expected behavior**
Should change to something like "Camera Offline" or something more suitable.

**Screenshots**
<img width="1680" alt="Screenshot 2022-12-13 at 11 05 10 PM" src="https://user-images.githubusercontent.com/51060067/207404273-add66bfc-eb2b-4167-a368-553e955e2783.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Brave Browser

**Comment by khavinshankar** [comment]
tracked in new issue https://github.com/coronasafe/care_fe/issues/4559
