### ISSUE TITLE
Alerts on Camera Feed of Patient

### ISSUE THREAD

**Issue by siddnikh** [coronasafe/care_fe#4303]
**Describe the bug**
When we try to interact with any button on the camera feed of a patient that hasn't yet loaded or is loading, we get an alert saying "Method "POST" is not allowed.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/01810c32-ec26-494a-9e65-40e5547a7746/patient/fcfad8af-bee7-4f6a-9773-25b7ae0a8031/consultation/5d8e7662-e2fb-4d10-8bf3-cf982d3ba0db/feed or any other patient feed.
2. Click on any button like move up or move down.
4. You will observe an alert message saying "Method POST is not allowed"

**Expected behavior**
A better alert could be placed there. The interactive buttons could even be disabled while the feed is loading or isn't available.

**Screenshots**
<img width="1680" alt="Screenshot 2022-12-13 at 11 10 30 PM" src="https://user-images.githubusercontent.com/51060067/207405715-470758b0-8cad-4237-9c66-095fd073a612.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Brave

**Comment by nihal467** [comment]
@Ashesh3 what is the status on this PR
