### ISSUE TITLE
Sidebar tooltip not visible

### ISSUE THREAD

**Issue by Ritesh-Aggarwal** [coronasafe/care_fe#4340]
**Describe the bug**
Tooltip not visible when hovering on collapsed sidebar options

**To Reproduce**

When the sidebar is collapsed hover on the tabs 

**Expected behavior**
Tooltip should be visible with tab name

**Screenshots**
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/57039447/208292485-768a121c-fb2f-4c34-b99c-c5db3b8c6bce.png">

**Comment by nihal467** [comment]
@patelaryan7751 what is the status on this PR

**Comment by patelaryan7751** [comment]
@nihal467 I would be working on it
