### ISSUE TITLE
Misalignment across the platform across multiple location

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4343]
**Describe the bug**

The icon and text inside the  buttons are misaligned in the:

- [ ] bed capacity
- [ ] Add location page
- [ ] Add bed page

*Steps to Reproduce*

- https://care.coronasafe.in/facility/52622c36-0ebf-4699-a9d2-3d4a18cfd40a/bed
- https://care.coronasafe.in/facility/52622c36-0ebf-4699-a9d2-3d4a18cfd40a/location/add
- https://care.coronasafe.in/facility/52622c36-0ebf-4699-a9d2-3d4a18cfd40a/location/d9374365-1838-4163-84d7-e3a3c1e85154/beds/add

*Screenshots*

![image](https://user-images.githubusercontent.com/57055998/208300480-b08b2fe6-3480-4cc9-b6c3-4b30f3784148.png)
![image](https://user-images.githubusercontent.com/57055998/208300836-51e94da2-5053-4211-8a5d-72f51c1f0e02.png)
![image](https://user-images.githubusercontent.com/57055998/208300923-159c6da5-2d39-4bdc-bead-746d950f1031.png)

**Comment by rithviknishad** [comment]
@cp-Coder the icon text alignment issue inside button will be resolved in one shot by PR of #4347 as discussed in it's comments.

@Ashesh3 do link this issue too in the PR
cc: @nihal467
