### ISSUE TITLE
Bed type badges are misaligned with other badges

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4344]
**Describe the bug**

Bed-type badges are misaligned with all other badges in the patient tab.

**To Reproduce**

https://care.coronasafe.in/patients?page=1&limit=12&name=nihal&ip_no=0395320983290&phone_number=&emergency_phone_number=&district=7&lsgBody=3619&facility=bd466cf6-0fde-46b1-9591-0acf9d955dd1&facility_type=Private+Hospital&date_declared_positive_before=&date_declared_positive_after=2022-12-01&date_of_result_before=2022-12-08&date_of_result_after=2022-12-01&created_date_before=2022-12-08&created_date_after=2022-12-01&modified_date_before=&modified_date_after=&date_of_result=&last_consultation_admission_date_before=&last_consultation_admission_date_after=&last_consultation_discharge_date_before=&last_consultation_discharge_date_after=&ordering=created_date&category=Comfort&gender=1&disease_status=POSITIVE&age_min=&age_max=&last_consultation_admitted_bed_type_list=2%2C6%2C7%2C1&srf_id=243423423434&number_of_doses=1&covin_id=243243432434&is_kasp=&is_declared_positive=false&last_consultation_symptoms_onset_date_before=&last_consultation_symptoms_onset_date_after=&last_vaccinated_date_before=&last_vaccinated_date_after=&last_consultation_is_telemedicine=&is_antenatal=true

**Expected behavior**

All the badges should be properly aligned

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/208303477-91550a63-e627-44a4-855f-98b950393c8f.png)

**Comment by rithviknishad** [comment]
@nihal467 @cp-Coder solved in https://github.com/coronasafe/care_fe/pull/4226

**Comment by nihal467** [comment]
@gigincg @khavinshankar removing the stale, as there is an active PR being linked and the author has been notified to merge the latest development branch for testing
