### ISSUE TITLE
Misalignment across the platform across asset page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4347]
**Describe the bug**

The icon and text inside the buttons are misaligned in the:

- [ ] configure asset page ( Both vital and camera page )
- [ ] asset info page

**To Reproduce**

- https://care.coronasafe.in/facility/0fd9dfa1-e4fb-4bbb-936d-c3cb05fa5e33/assets/a2bc8f07-d485-46ed-bcae-a850797da04c/configure
- https://care.coronasafe.in/facility/52622c36-0ebf-4699-a9d2-3d4a18cfd40a/assets/0b4f03af-c60c-475b-8fe5-e162331a9354

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/208305510-13248bda-e3f4-4d10-a50b-b67b05b827f3.png)
![image](https://user-images.githubusercontent.com/57055998/208305596-6fdc9ff2-cff6-4daf-9ae0-adc3d0729f93.png)

**Comment by rithviknishad** [comment]
@Ashesh3 i think all the icons are misaligned when we use care icons even after setting `flex gap-2 items-center`.

**Comment by rithviknishad** [comment]
I had to manually do `mt-0.5` or `mt-1` at places where font-awesome was replaced with CareIcon

**Comment by Ashesh3** [comment]
@rithviknishad `inline-flex` along with `items-center` seem to help remedy the alignment problem.

![image](https://user-images.githubusercontent.com/3626859/208306517-94d2a71c-6822-46bb-9ed2-473f5314f72c.png)

Before:
![image](https://user-images.githubusercontent.com/3626859/208306549-8d2ecb20-1097-4968-8ca9-20d4669e1ca8.png)

After:
![image](https://user-images.githubusercontent.com/3626859/208306553-1a6f2708-9950-45ff-9d88-6356445088ba.png)

**Comment by rithviknishad** [comment]
@Ashesh3 what do you think about updating the `ButtonV2` component to have `inline-flex items-center` already present in it's classNames?

**Comment by Ashesh3** [comment]
> @Ashesh3 what do you think about updating the `ButtonV2` component to have `inline-flex items-center` already present in it's classNames?

That'd be super clean and helpful!

**Comment by rithviknishad** [comment]
along with `gap-2` also maybe? it's still overridable since the `classNames` passed as a prop is appended to the end

**Comment by Ashesh3** [comment]
> along with `gap-2` also maybe? it's still overridable since the `classNames` passed as a prop is appended to the end

Yep, a default template for a button would make it much easier to use by default, while also allowing it to be overridden by `classNames`. So yea i think we can add those properties by default.
