### ISSUE TITLE
Facility card height is not consistent with different information

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4349]
**Describe the bug**
Facility card height is not consistent with different information

**To Reproduce**

1. Go to facility list page

**Expected behavior**
set a higher `min-height-...` (maybe a height equivalent to the first card?).

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/208306459-1b89c62c-6760-463a-a1ef-5ddc9492ebaf.png)

**Comment by khavinshankar** [comment]
@rithviknishad even when we set a `min width`, there are chances that if the content is bigger then we would have inconsistencies

**Comment by shivankacker** [comment]
@rithviknishad @khavinshankar should we close this issue?
