### ISSUE TITLE
Implement `Page` component to make padding across pages consistent

### ISSUE THREAD

**Issue by GokulramGHV** [coronasafe/care_fe#4375]
To create a component named `Page` which will have props like title etc similar to the `PageTitle` component. This Page component should have PageTitle component wrapped inside followed with the children.
The `Page` component will also set a uniform padding and alignment from screen top and left.
This would prevent inconsistent padding between pages.

**Comment by GokulramGHV** [comment]
#3742

**Comment by nihal467** [comment]
@GokulramGHV what is the status of this Issue

**Comment by GokulramGHV** [comment]
@nihal467 I'm working on it I'll make a PR soon..
