### ISSUE TITLE
Display total bed count on facility page

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4389]
Should we also display the total number of beds occupied by the number of beds in the facility
![image](https://user-images.githubusercontent.com/70687348/209098409-4af72ce3-764f-4336-816c-994a7f3100dd.png)

**Comment by Pranshu1902** [comment]
@nihal467 @khavinshankar

**Comment by khavinshankar** [comment]
@Pranshu1902 yes that would be nice, for totals instead of having a separate card, we could show it near the title greyed out


@nihal467 your thoughts

**Comment by nihal467** [comment]
@Pranshu1902 take it up in the EOD call
