### ISSUE TITLE
Change Advance filter colour on selection to dark blue

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4393]
**Describe the bug**

When we are selecting a filter in the advanced filters, the background is light blue, which doesn't give a good look to the user experience

**To Reproduce**

https://care.coronasafe.in/facility?page=1&limit=14&search=

**Expected behavior**

It should be dark blue, as in the previous version of the care

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/57055998/209423250-63329878-c979-44d8-81fc-a5be41406b4a.png)

**Comment by nihal467** [comment]
@Ashesh3 can you push a fix ASAP, since it is same across the platform

**Comment by Ashesh3** [comment]
Unable to replicate the issue.
Tested on Chrome v108 running on Windows 10/11. I always get the dark blue variant. 

`Win 11 / Chrome 108`
![image](https://user-images.githubusercontent.com/3626859/209432667-4c838def-bb07-4c56-9492-b0f7a2813852.png)

`Win 10 / Chrome 108`
![image](https://user-images.githubusercontent.com/3626859/209432670-a1d23947-48f1-4325-b9bd-e2ed5a21d85b.png)

`Win 11 / Opera 94`
![image](https://user-images.githubusercontent.com/3626859/209432761-f0fce5d3-d1c1-4d23-8b7e-7ae9b7ba8152.png)

**Comment by nihal467** [comment]
@Ashesh3 seems to be a browser-side issue, the issue seems to be resolved,
