### ISSUE TITLE
Unable to configure the asset 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4398]
**Describe the bug**

When we are trying to configure the asset page, unable to keep the middleware empty

**To Reproduce**

https://care.coronasafe.in/facility/57458c9b-7512-4a58-b0d5-cc526c219820/assets/52269758-412b-48fc-9128-31ae372cb45c/configure

**Expected behavior**

middleware in the asset configuration page should be an empty field

**Screenshots**

![WhatsApp Image 2022-12-24 at 14 23 42](https://user-images.githubusercontent.com/57055998/209430246-4a0ea017-9c40-447e-bf10-9980668ffe9b.jpg)

**Comment by khavinshankar** [comment]
should be fixed by https://github.com/coronasafe/care/pull/1136
