### ISSUE TITLE
Translations for the standardized submit and cancel buttons

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4423]
**Is your feature request related to a problem? Please describe.**
There are no translations for "Cancel" and "Submit".

**Describe the solution you'd like**
Now that the usage of Submit and Cancel buttons have been generalized, it's easy to provide translations for these keywords that applies across the platform.

![image](https://user-images.githubusercontent.com/25143503/209489006-97117969-769d-43c4-96aa-b3993099b3f8.png)

**Comment by khavinshankar** [comment]
@rithviknishad as a follow-up to this issue, can you make an epic issue that tracks multiple issues for adding localization support across the platform for all hardcoded string
