### ISSUE TITLE
New Popups for "Edit/ Add Bed Capacity" & "Edit/Add Doctor Capacity"

### ISSUE THREAD

**Issue by joelsajichacko** [coronasafe/care_fe#4425]
**Replacing separate pages with popups**
Now, if we want to add / edit bed capacity or doctor capacity we are directed to separate other pages. I think it will be a lot easier if we can give a way to update them on the "Facility page" itself b giving a modal/Popup

**Present Design**

![image](https://user-images.githubusercontent.com/45791338/209510274-4ab8af0d-2bb6-4367-adb4-7df70603c36f.png)

**New Design**

![image](https://user-images.githubusercontent.com/45791338/209510386-0d2f07f7-fbff-4390-910f-a7c86bbebe7f.png)
![image](https://user-images.githubusercontent.com/45791338/209510402-3871673d-04be-49bc-98d3-f0434499be32.png)
![image](https://user-images.githubusercontent.com/45791338/209510414-9514e044-8242-476c-ad40-d072dace6701.png)

Link to figma; https://www.figma.com/file/fqDMgeN2m4TCSz5KobZaKW/CoronaSafe-Network-Care?node-id=2065%3A1200&t=6hPGONdVWgJTMBya-1

**Comment by nihal467** [comment]
@Ashesh3 Once the facility is created, the page is redirected to the facility detail page, in which pop-up automatically loaded up along with the page.
