### ISSUE TITLE
Create a popup or modal for confirming the asset delete action

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#4434]
can we have a custom modal for this instead of just window.confirm?

_Originally posted by @khavinshankar in https://github.com/coronasafe/care_fe/pull/4304#discussion_r1058059887_

**Comment by rithviknishad** [comment]
@khavinshankar @GokulramGHV we already have a custom modal for actions that require confirmation, we could re-use it.

![image](https://user-images.githubusercontent.com/25143503/209784741-f803b34f-5deb-4fa2-b889-1d56fac39237.png)
