### ISSUE TITLE
Add state logo on login page

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4442]
https://care.coronasafe.in/

Add a customizable component for the state logo on the top left corner of the page. 

Since CARE is utilized by various health departments and other groups, having their logo on the home page would increase the sense of ownership and help in the smooth deployment.

Eg of a logo:

![Kar-Health](https://user-images.githubusercontent.com/67050716/210034780-f8dc64b6-76a6-4b49-ae34-99a6a5ffd627.png)

**Comment by rithviknishad** [comment]
@aparnacoronasafe is this an optional or mandatory feature for across all deployments?

In other words, can a few deployments have a logo and a few may not have?
