### ISSUE TITLE
Styling is breaking on some occasions

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#4452]
**Describe the bug**
On initial page load, the styling of the entire page is broken. This only happens sometimes but is persistent till a hard refresh is done.

**To Reproduce**

1. Go to https://care.coronasafe.in/
4. See the broken styling

**Expected behavior**
Styles should be properly applied, and page should appear normal.

**Screenshots**
### The page
![image](https://user-images.githubusercontent.com/3626859/210081268-e933ac11-7ca8-4762-8517-f613775dcab2.png)
![image](https://user-images.githubusercontent.com/3626859/210081292-b45d5a73-f05b-4bca-a603-623f2b4676fb.png)

### The console
![image](https://user-images.githubusercontent.com/3626859/210081332-008c6993-40ac-4994-9e04-75e8fb81aca2.png)

### Network requests
![image](https://user-images.githubusercontent.com/3626859/210081384-211076f0-9791-47e8-9113-14c2bb5def23.png)

Seems like the main css file fails to load on rare occasions, rendering an empty response:
![image](https://user-images.githubusercontent.com/3626859/210081530-555644d0-a8aa-479c-a033-b18ca39ff27c.png)

### HAR file
Here's the HAR file, which contains full details of every network request and response made during the page load:
[care.coronasafe.in.zip](https://github.com/coronasafe/care_fe/files/10325151/care.coronasafe.in.zip)

(On a Chrome browser, Go to network tab > drag and drop the `.har` file and you should see the logs)

**Desktop:**
- OS: Any
- Browser: Chrome/Firefox

**Comment by rithviknishad** [comment]
As discussed, we'll be trying to have auto update regardless of what branch, and use automated versioning based on `github.run_number`

**Comment by rithviknishad** [comment]
![image](https://user-images.githubusercontent.com/25143503/210332469-90a875e6-8598-44fa-a4c1-ee491627cc42.png)

**Comment by rithviknishad** [comment]
https://cdn.rithviknishad.dev/care.coronasafe.in_Archive.har

**Comment by rithviknishad** [comment]
This issue is not getting solved when we trigger an update. Will continue to debug, feel free to assign if anyone figures out the problem

**Comment by rithviknishad** [comment]
Now when the page loads with broken styling, the auto-update gets triggered and fetches the latest CSS files.

So now, first the page visibly loads with broken styling, but immediately refreshes because of the auto-update, and then visibly loads properly.

Workaround works, but underlying issue is still present.

**Comment by rithviknishad** [comment]
@gigincg @Ashesh3 closing this issue as not reproducible in recent weeks
