### ISSUE TITLE
UI of investigations, procedures, PRN prescription and prescription

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4461]
**Is your feature request related to a problem? Please describe.**
In the consultation form, the UI design for investigations, procedures, PRN prescription and prescription are uniform and is reported to be confusing for the users, especially when many entries are made under each of the fields.

The reasons for this confusion are:
- each entry have too many input fields. It is reported to cause confusion. the grouping of fields to each entry must be done more clearly
- The alignment of the fields against the field titles is confusing
- When fields are generated accidentally, the user finds it difficult to understand that the same must be deleted by clicking the small "delete icon"

**Describe the solution you'd like**

- [ ] Make each entry (all input fields relating to one entry) appear in a box. The grouping must be clear
- [ ] Give a serial number to each entry under a topic. 
- [ ] The delete icon must clearly be for the whole group of entry fields. Currently, its placed near the "notes" text field which gives the impression that it only holds for the said field

Any other UI fix to made it simpler for the users may be implemented

**Comment by nihal467** [comment]
@GokulramGHV what is the status on this issue

**Comment by GokulramGHV** [comment]
@nihal467 I'll make a PR soon
