### ISSUE TITLE
asset scanning- "Page not found"

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4488]
**Describe the bug**
CARE has the option to scan a registered QR code sticker and user is taken to the particular asset page. (https://care.coronasafe.in/assets)

This is not working. The user is instead taken to a "Page not found" page

**To Reproduce**

1. Go to ['...'](https://care.coronasafe.in/assets)
2. Click on 'Scan Asset QR'
3. Scan the below QR code (the QR is already linked to "Test camera: (https://care.coronasafe.in/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/assets/926a0371-a772-47e8-925f-aa853e24ee58)
![WhatsApp Image 2022-12-27 at 11 35 56 AM](https://user-images.githubusercontent.com/67050716/210498688-a45f4a27-96f1-4657-a3d1-247f6ebb8839.jpeg)

5. user will be taken to "Page not Found" page- BUG

**Expected behavior**
Te user must be taken to the asset page upon scanning qr code

**Comment by nihal467** [comment]
@aparnacoronasafe the url is invalid
