### ISSUE TITLE
Asset search- to QR code id/ serial No

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4490]
**Is your feature request related to a problem? Please describe.**
It becomes difficult to identify an asset by looking at the QR code sticker or serial no. 

**Describe the solution you'd like**
We already have a " search asset " field in the asset list (https://care.coronasafe.in/assets). Currently, that only supports search by asset name. 

- [ ] Enable search by asset QR ID and Serial No. also on the same field.
- [ ] The default text in the search field must change from "Search Asset" to "Search asset by asset name, serial no or asset QR code ID"

**Comment by aparnacoronasafe** [comment]
@GokulramGHV Any development on this?

**Comment by GokulramGHV** [comment]
@aparnacoronasafe this is a backend issue I don't know if I would be able to make a pr for this
