### ISSUE TITLE
View password option

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4491]
**Is your feature request related to a problem? Please describe.**
most of the users of care are people that do not use computers very often and are not very good a typing. In most cases, after they type in passwords they are unsure of accuracy. They erase it and type it out multiple times before submitting

**Describe the solution you'd like**
Add a "view password" option on all password fields to make input visible. 
Something like the below image
<img width="292" alt="Screenshot 2023-01-04 at 1 47 53 PM" src="https://user-images.githubusercontent.com/67050716/210512499-670ed225-e91f-4f4d-89bb-a14b8416a2e1.png">

**Comment by rithviknishad** [comment]
@aparnacoronasafe we already have view password

![image](https://user-images.githubusercontent.com/25143503/210512749-55891b4e-9a44-4db5-82a3-0493411a3b53.png)

**Comment by aparnacoronasafe** [comment]
We need that here as well: https://care.coronasafe.in/users/add

**Comment by rithviknishad** [comment]
@aparnacoronasafe can you check this deploy preview: https://deploy-preview-4378--care-net.netlify.app/users/add

A PR is already there that uses the new components that solves this issue.

**Comment by aparnacoronasafe** [comment]
This looks great. Okay...closing the issue. Thanks for pointing it out @rithviknishad :-)

**Comment by rithviknishad** [comment]
@aparnacoronasafe I'm re-opening this issue since it'll be auto-closed when the linked PR is merged.
