### ISSUE TITLE
Declare death

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4497]
In consultation form (https://care.coronasafe.in/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095/patient/86db5dde-ffdb-4473-9eab-3e6b2088d7d6/consultation/de8455fa-3d11-49e3-9dc2-1aaec616379b/update)

In "decision after consultation" add an option at the bottom of the dropdown "Declare Death"

**Comment by nihal467** [comment]
@khavinshankar reopened it as we are having a frontend PR waiting to merge, once it's done close it
