### ISSUE TITLE
Discharging patients

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4499]
When a patient is discharged from CARE, There are 4 reasons for discharge. ie, Recovery, Expiry, Referral, LAMA. Currently, we only take additional notes for discharge upon any of these reasons.

Enhance this to have different behavior for each of the reasons for discharge.

1. RECOVERED
When the reason for discharge is selected as "recovered"
- [x] Add field for discharge date. add data validation so that the discharge date is between the admission date and the present date. autofill this to the present date. This must be a mandatory field.
- [x] Rename "Notes" to discharge advice
- [x] Add a prescription and PRN Prescription module below to note discharge medication. give the heading above the modules as "Discharge medication". The whole section shall be non-mandatory

2. EXPIRED
- [x] Add a field before the cause of death to note the date and time of death. Make the date field mandatory and the time field optional
- [x] Add field below Cause of death to say "Death Confirmed By". this field shall have the name of the doctor that confirmed the death. This shall also be a mandatory field.

For REFERRED and LAMA we need not add more details for now

**Comment by aparnacoronasafe** [comment]
@cp-Coder Abhuiday, this has come up as an urgent requirement. Could you ship it out in the next two days so that it can be merged to production this week itself?

**Comment by aeswibon** [comment]
@aparnacoronasafe sure

**Comment by nihal467** [comment]
@cp-Coder what is the status of the P1 issue

**Comment by aeswibon** [comment]
Pushing the PR by today night

**Comment by aparnacoronasafe** [comment]
A few more changes would be nice in this. Only for the form when "Recovered" is selected.

- Rename "Prescription medication" to "Discharge Prescription"
- Change the order to "Reason for discharge", "Discharge Date", "Discharge Prescription including PRN" and "Discharge advice"
