### ISSUE TITLE
Doctors : Specialisation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4501]
When registering a doctor user type (https://care.coronasafe.in/users/add) the following additional fields to be added to the form 
- Specialisation- dropdown with search function. The list of specialities is available at https://docs.google.com/spreadsheets/d/1lCBF2hhmlYV3paPP3xIep6tPHmzTefdD67w-eaKql7I/edit?usp=sharing
- Qualification- short text field- mandatory field 
- Years of experience- drop-down (0, 1-2, 3-5, 5-7, 7-10, more than 10) years- mandatory field
- Medical council registration No. (short field for numeric values accepting max 10 digits)- mandatory field

- [x] Make all the input visible in the user list
- [x] Make qualification and specialty appear against the name in the doctor  connect panel (https://care.coronasafe.in/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095/patient/86db5dde-ffdb-4473-9eab-3e6b2088d7d6/consultation/de8455fa-3d11-49e3-9dc2-1aaec616379b)

**Comment by aparnacoronasafe** [comment]
@rithviknishad Please note that I have updated the requirement for the specialization field to be a dropdown with search. 

Earlier, it was specified to be a free text field

Please do the needful

**Comment by rithviknishad** [comment]
@aparnacoronasafe yes :)

**Comment by aparnacoronasafe** [comment]
@rithviknishad can you give me an ETD for this one?

**Comment by rithviknishad** [comment]
Both front-end and back-end PRs would be ready by Tuesday 17th Jan, so very likely to be present by January Week 4 Release.

I'm currently travelling this week, so if possible I'll try my best to push it earlier than above mentioned ETD.

**Comment by rithviknishad** [comment]
@aparnacoronasafe I'll be proceeding to make all other fields except specialisation for now.

Specialisation will be made as an extension over UserSkills once @Pragati1610's PR #4455 is merged.

Also, the Years of Experience will be a Month and Year of begin selector.

cc: @gigincg
