### ISSUE TITLE
Fix failing cypress tests - `patient_spec/patient-crud`

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#4512]
In patient_spec/patient-crud the age is hard coded, so from this new year the test is failing, make it dynamic

**Comment by nihal467** [comment]
@khavinshankar check this issue, seem to have a PR merged related to this, but not yet closed this issue, is there any more PR to come related to this or if its completed, can you close it

**Comment by nihal467** [comment]
the issue is resolved
