### ISSUE TITLE
One card is missing on all pages

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4531]
**Describe the bug**
The last card is missing on all pages like Assets, Users, Patients.

**To Reproduce**

1. Go to https://care.coronasafe.in/assets

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/211026190-585d4927-6991-48db-84dc-31d9926118e1.png)

![image](https://user-images.githubusercontent.com/70687348/211026279-10ecaea5-271d-401f-91e7-7e0670adaef0.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pranshu1902** [comment]
@nihal467 @khavinshankar @gigincg Is this intentional?

**Comment by nihal467** [comment]
@Pranshu1902 it is not intentional, you can work on the fix

**Comment by Pranshu1902** [comment]
Issue raised in backend [#1146](https://github.com/coronasafe/care/issues/1146)
