### ISSUE TITLE
Pagination and list view is broken across the platform

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4542]
**Describe the bug**

- [ ] when we are changing pages from one page to another one, even though the page is getting reloaded, the page is not getting changed and the same data is being reflected
- [ ] one card is missing on the patient and asset page.

**To Reproduce**

1. Go to https://care.coronasafe.in/assets
2. Click on the pagination of the page
3. See the error

**Expected behavior**

- [ ] when we are using the pagination, it should be functioning properly
- [ ] all the cards should be visible on a page

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/211263754-bac81b28-3f7b-47ad-8401-2c8b650449b4.png)

**Comment by rithviknishad** [comment]
https://github.com/coronasafe/care/issues/1146
