### ISSUE TITLE
Optimize Camera Feed for Mobile Usage

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#4558]

**Comment by rabilrbl** [comment]
@gigincg Currently camera feed looks like this
![image](https://user-images.githubusercontent.com/63334479/212554433-1a534e7d-f969-4742-a087-7a80c2e0f63c.png)

Besides making camera presets responsive
 What else to improve on? Please specify

**Comment by gigincg** [comment]
@rabilrbl The Camera View should maintain aspect ratio at all times. When in Portrait view, maybe the controls can go outside. Also, optimize for Landscape view as well

**Comment by nihal467** [comment]
@rabilrbl unassigning you from the issue due to inactivity for 6 months

**Comment by UdaySagar-Git** [comment]
Is this issue still open ? can I work on this @Ashesh3

**Comment by Ashesh3** [comment]
Sure @UdaySagar-Git

**Comment by UdaySagar-Git** [comment]
Hey @Ashesh3, could you please help me navigate to the camera feed page? I am having difficulty in pointing its exact location.

how ever i reached to feed page from 
http://localhost:4000/facility/64c2be92-47fd-47c3-9d3d-7891245f4611/patient/a4b86382-8998-4d66-a448-dbd2ce40da6b/consultation/ab765f7b-79a4-4e49-be88-2cdd63c834ca/feed

i just placed /feed at the end however i am not able to find any way to navigate to feed from 
http://localhost:4000/facility/64c2be92-47fd-47c3-9d3d-7891245f4611/patient/a4b86382-8998-4d66-a448-dbd2ce40da6b/consultation/ab765f7b-79a4-4e49-be88-2cdd63c834ca/

Am I on the wrong page ?

**Comment by bishwas-10** [comment]
@Ashesh3  can i work on this issue?
and if i can can you provide brief description about the issue as there is only issue titile!

**Comment by Ashesh3** [comment]
> @Ashesh3 can i work on this issue? and if i can can you provide brief description about the issue as there is only issue titile!

Hey, I only have the following context on this issue:

https://github.com/coronasafe/care_fe/issues/4558#issuecomment-1384031287

cc: @nihal467 could you provide more details on this issue?

**Comment by bishwas-10** [comment]
@Ashesh3 can you assign me this then? 
looks like nobody is working on it
