### ISSUE TITLE
Unable to configure middleware for the facility

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4578]
**Describe the bug**

Unable to configure middleware of a facility using district admin user privilege

**To Reproduce**

https://care.coronasafe.in/facility/32676d52-5454-4f14-bbb0-179a1981e536/middleware/update

**Expected behavior**

we should be able to configure a middleware for a facility

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/212332520-212f56d7-c6bb-42c4-be98-0bca0cf75478.png)

**Comment by Ashesh3** [comment]
@nihal467 are you sure you are using a valid URL for the configuration?
`http://example.com` works fine
`invalid_input` fails, as expected

**Comment by nihal467** [comment]
@Ashesh3 dev_middleware.coronasafe.live, this is the middleware

**Comment by Ashesh3** [comment]
> @Ashesh3 dev_middleware.coronasafe.live, this is the middleware

I am able to enter `https://dev_middleware.coronasafe.live` for the middleware URL. It accepts it and updates successfully.

`dev_middleware.coronasafe.live` is not a valid URL without the protocol at the beginning. (http/https)

**Comment by nihal467** [comment]
@khavinshankar Http was not part of our middleware right, can you comment on it

**Comment by Ashesh3** [comment]
Additional Context:

The validation for the middleware host was added yesterday on the backend.
https://github.com/coronasafe/care/blame/master/care/facility/api/serializers/facility.py#L122

```
def validate_middleware_address(self, value):
	value = value.strip()
	if not value or not value.startswith("http"):
		raise serializers.ValidationError("Invalid URL")
	if value.endswith("/"):
		raise serializers.ValidationError("URL should not end with /")
	return value
```

**Comment by nihal467** [comment]
issue is been resolved
