### ISSUE TITLE
When we jump to patients tab, it's being navigated with the default query params explicitly set

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4601]
**Describe the bug**
When we jump to the patients' tab, it's being navigated with the default query params explicitly set.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the Patients tab from some other tab
2. It goes to `/patients` and immediately adds the default query parameters.

However, when already on the patients' page and clicking on the patients' tab, it navigates to `/patients` without the query params set.

**Expected behaviour**
Clicking on the Patients tab should navigate to `/patients` without query parameters.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/212540225-2783e1e1-96aa-4f56-ad3b-2fd39d20d389.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nihal467** [comment]
@cp-Coder what is the status on the issue

**Comment by rithviknishad** [comment]
Fixed by #4802
