### ISSUE TITLE
Doctor connect for Facility

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4617]
**Is your feature request related to a problem? Please describe.**
When a doctor from the Hub does rounds of patients admitted in the spokes, they may want to discuss the details of multiple patients with the same local doctor. Currently, since the doctor connect feature is on the patient dashboard, the users have a sense that the call placed will have to be disconnected as they navigate to another patient. 

**Describe the solution you'd like**
Provide an option for "Doctor connect" in the patient list within a Facility. It shall show the details of all doctors and staff linked to the facility just like the doctor connect feature within the patient dashboard. 

Essentially only an additional button for "Doctor Connect" needs to be placed in the patient list of any facility.

https://care.coronasafe.in/patients?facility=4f885b99-9557-45b6-b696-0a851393dcdf&page=1&limit=12&emergency_phone_number=
<img width="872" alt="Screenshot 2023-01-16 at 11 02 58 PM" src="https://user-images.githubusercontent.com/67050716/212738178-b94637ff-2dfc-4de6-b5fe-e7a8f5ec8e2d.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by aparnacoronasafe** [comment]
@patelaryan7751 Could you commit to a date for this?

**Comment by patelaryan7751** [comment]
@aparnacoronasafe  i would complete this by monday

**Comment by patelaryan7751** [comment]
Hey @aparnacoronasafe i have made a PR https://github.com/coronasafe/care_fe/pull/4687
