### ISSUE TITLE
Patients page filter not removing on dashboard click.

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4619]
**Describe the bug**
When clicked on the Patient item of the dashboard, the filter badge gets removed but the patients list doesn't get updated.

**To Reproduce**

1. Go to https://care.coronasafe.in/patients?facility=d02ef2cb-b5b2-4baf-bc9a-fac348893b00&page=1&limit=12&emergency_phone_number=
2. Click on the Patient item on the dashboard
3. See error

**Expected behavior**
The patients list should get updated on click on dashboard.

**Screenshots**
https://www.loom.com/share/344b64785eb94da297cf92e750d40a23

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rithviknishad** [comment]
fixed via https://github.com/coronasafe/care_fe/pull/4703
