### ISSUE TITLE
resp support : IV, NIV, O2 support must be identified as period in time and not point in time. 

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4629]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gigincg** [comment]
- [ ] Dependent on the Events Rebuild
- [ ] May Require ConsultationBed-Flag

**Comment by gigincg** [comment]
@aparnacoronasafe This is not handled with ConsultationBed-Assets
