### ISSUE TITLE
Access to discharged patient file

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4678]
**Is your feature request related to a problem? Please describe.**
When hosp A discharges a patient and the same patient is admitted to hosp B, hosp A then cannot see the details of the patient in their discharged patient list.

It is mandatory for hospitals to store all patient records of even discharged patients for a few years. They may also have periodic audits etc, where the information may have to be retrieved.

**Describe the solution you'd like**

- [ ] On the facility dashboard (https://care.coronasafe.in/facility/0421de45-3541-4652-862d-79cec4acb6af) below "View patients" add an option to "View Discharged Patients"
- [ ] In the patient list, hide the "Discharged" tab for all users other than State Administrators. 

> Note: Requires a new API to get Unique Patients with active=false from Consultation for the Facility. Do not reuse the existing Patient List API

**Comment by nihal467** [comment]
@cp-Coder what is the status on this issue

**Comment by nihal467** [comment]
@cp-Coder don't work on this issue now, few clarifications need to be done. @aparnacoronasafe will be updating it by next Tuesday

**Comment by nihal467** [comment]
@aparnacoronasafe can you review this issue and unassign yourself

**Comment by aparnacoronasafe** [comment]
I have edited the issue to suggest a solution. 

@gigincg please review

**Comment by gigincg** [comment]
Note: Requires a new API to get Unique Patients with `active=false` from Consultation for the Facility. Do not reuse the existing Patient List API

**Comment by rithviknishad** [comment]
ETD: Feb 14th
