### ISSUE TITLE
Advance filter: Patient list - Malfunctioning

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4681]
**Describe the bug**
When I take patient list and add filter to view patients created between 24th April 2022- 26th April 2022, I get 5 Live patients as result. 

But in the result, I donot see the listing of patient "Annie Philip" whose card was created on 25th April 2022. (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce)

**To Reproduce**
Mentioned above

**Expected behavior**
The result list is not complete. The result must include the card of "Annie Philip"

**Comment by nihal467** [comment]
@cp-Coder what is the status on this issue

**Comment by aeswibon** [comment]
The issue has been resolved.

![image](https://user-images.githubusercontent.com/77210185/221355263-e10fcbdf-51ab-499f-b5a9-c6c90da69741.png)
