### ISSUE TITLE
Reason for discharge: Show on patient dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4697]
**Is your feature request related to a problem? Please describe.**
Once patient is discharged, no way to see the discharge reason

**Describe the solution you'd like**
Add "reason for discharge" on a discharged patients dashboard. 

Eg: https://care.coronasafe.in/facility/6248f03b-cf47-4bfb-9b89-d2235082d8ff/patient/f775ef85-0b1e-4ccd-b546-9152f6abf4cf/consultation/9df6592b-e99d-43af-896b-35f8865afc4b 
This patient is expired. So have "expired" appear in big bold letter above the investigation summary button on right side of the patient dashboard.

formatting suggestion: The right top corner of patient details page : https://care.coronasafe.in/facility/6248f03b-cf47-4bfb-9b89-d2235082d8ff/patient/f775ef85-0b1e-4ccd-b546-9152f6abf4cf

**Comment by khavinshankar** [comment]
@cp-Coder can you please work on this immediately and push a pr ASAP, this needs to be released in this week's release

cc: @nihal467

**Comment by aparnacoronasafe** [comment]
@nihal467 @cp-Coder This needs to get merged by 13th Feb
