### ISSUE TITLE
we can customise editor for writing notes so that user can customise text properties as he likes

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#4705]
**Is your feature request related to a problem? Please describe.**
We can customise editor for writing notes so that user can customise text properties as he likes. When a user wants to mark a text in red color or highlight he cannot do so if we have a customised editor like PupilFirst LMS would do good.
![image](https://user-images.githubusercontent.com/59426397/215636332-0db70e20-57e9-4408-8833-0d108d026285.png)

**Describe the solution you'd like**
We can customise editor for writing notes

**Describe alternatives you've considered**
No alternatives present

**Comment by nihal467** [comment]
@print-Sathvik unassigning you from the issue, due to inactivity for two months,

**Comment by print-Sathvik** [comment]
@nihal467 There is some work going on on redesigning doctors notes by C4GT interns. So I stopped working on this issue's outcomes might clash with their design

**Comment by Ashesh3** [comment]
The design of the doctor's notes has been updated to incorporate a chat feature. Could we re-evaluate the relevance of this feature in the context of the new design and conclude the assessment accordingly?

cc: @nihal467

**Comment by Keshav-0907** [comment]
@Ashesh3 @nihal467 

I want to work on this, Can you please assign this issue this to me.

**Comment by Ashesh3** [comment]
Hey, after revisiting this issue, it appears that this is already covered under one of our GSOC projects as a part of a bigger issue: https://github.com/coronasafe/care_fe/issues/7159 . Closing this in favor of the larger issue. Feel free to pick up other issues to work on!
