### ISSUE TITLE
Bed Assignment necessary before filing log update for patients admitted 

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4707]
**Is your feature request related to a problem? Please describe.**
Bed Assignment must be mandatory for users to file log updates for patients that are admitted. 
If the bed is not assigned, open a pop-up window to assign a bed before filing log update

This must be applied only to patients admitted in a hospital and not for other patients

**Comment by nihal467** [comment]
@cp-Coder push the fix ASAP

**Comment by aeswibon** [comment]
@nihal467 This feature is already there in the staging server.

https://user-images.githubusercontent.com/77210185/216050605-fd7421e3-4d5f-4b36-a059-6f9022133796.mp4

**Comment by nihal467** [comment]
@cp-Coder 
![image](https://user-images.githubusercontent.com/57055998/216059098-b5c6ba6e-4eb9-439d-8808-13f5fa08f9dd.png)

currently, the pop-up is coming for all the patients, but it shouldn't be the case. The pop-up should only be asked to assign a bed for a patient, who is selected "admitted" in the decision after consultation
