### ISSUE TITLE
IP No. - to be Mandatory only for admitted patients

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4708]
**Describe the bug**
Currently, IP Number is mandatory to submit the consultation form. It should be mandatory only for admitted patients at "IP number" stands for in-patient number.

**Comment by rithviknishad** [comment]
@aparnacoronasafe just confirming that IP No. should be mandatory only if "Decision after consultation" is "Admission" right?

![image](https://user-images.githubusercontent.com/25143503/215757503-54e1e43f-81a8-4c6b-8600-294433dc2dc4.png)
