### ISSUE TITLE
IMPROVING FORMAT OF PATIENT EXPORT

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4709]
Currently the export feature on patient list provides a lot of information about the patient which may/maynot be relevant. 
Please find the patient export csv below:
[export_2023-01-31T08_07_39.128Z.csv](https://github.com/coronasafe/care_fe/files/10544143/export_2023-01-31T08_07_39.128Z.csv)

This format must be revised to only include
- Demographic details about the patient
- Only a few very relevant clinical detail
- remove PIIs as much as possible. 

The suggested format for export must contain:
- Patient ID
- Patient name
- Hospital last admitted in
- Status (if live- "decision after consultation", if discharged "reason for discharge)
- Age
- Sex
- Diagnosis
- Date of registration in CARE
- Date of last consultation filed
- Date of discharge

**Comment by rithviknishad** [comment]
@aparnacoronasafe this would be the new format (taken from local care, populated with `load_dummy_data`)

[export_2023-02-02T03 31 24.097Z.csv](https://github.com/coronasafe/care_fe/files/10564538/export_2023-02-02T03.31.24.097Z.csv)

**Comment by aparnacoronasafe** [comment]
@rithviknishad Please check the date of registration/consultation. why is the format like that?

**Comment by rithviknishad** [comment]
@aparnacoronasafe shall I proceed with making it `DD/MM/YYY` or is there any specific format you want me to follow for the dates?

**Comment by aparnacoronasafe** [comment]
Dd/mm/yyyy works. 

Also, if there is already time there retain that too hh:mm format.
