### ISSUE TITLE
Auto-scroll: when mandatory fields are not filled

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4710]
**Describe the bug**
in consultation form, When "verified by " field is not filled, the form doesnt submit and the field is highlighted in red. 

But the page doesnt auto-scroll up so that the user can easily locate what field is not added and why the form is not getting submitted. 

Enable this auto-scrolling

**Comment by nihal467** [comment]
@cp-Coder what is the status of the issue

**Comment by aeswibon** [comment]
@nihal467 The issue has been resolved.

https://user-images.githubusercontent.com/77210185/220121439-32adf108-fdbf-4230-aa7b-8f1559d43bf5.mp4

**Comment by rithviknishad** [comment]
@nihal467 closing this as not reproducible.

cc: @aparnacoronasafe
