### ISSUE TITLE
Add button to delete recorded audio

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4713]
**Describe the bug**
After we have recorded the audio, we only get the option to upload it. There should also be an option to delete that recording.

**To Reproduce**

1. Go to https://care.coronasafe.in/sample/c099cd75-0910-4024-b8aa-3a3e3ff033dd
2. Click on Record
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/215723343-de7558c4-17ad-41ae-954a-2ddd52e76e2b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pranshu1902** [comment]
@nihal467 @khavinshankar @gigincg what's your opinion?

**Comment by nihal467** [comment]
@Pranshu1902 
![image](https://user-images.githubusercontent.com/57055998/216355378-2eb7aa53-a164-4f4b-9bb4-e5c1ffdaefbf.png)

- [ ] replace the rerecord button with the delete button
- [ ] reduce the button from save recording to save
- [ ] show all the preview and both buttons in a single line
