### ISSUE TITLE
BUG:Updating medicine in Log update: Not coming up in patient dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4717]
**Describe the bug**
https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce/medicines

Patient Annie Philip. 

I filed a new log update at 11:57 on 01/02/23. 
However, the Medicines tab doesn't show the medicines. It shows a prescription update at that time, but the table shows "No Data Found"

**Comment by nihal467** [comment]
@aparnacoronasafe 
![WhatsApp Image 2023-02-01 at 12 17 30](https://user-images.githubusercontent.com/57055998/215972646-f65ef640-3846-47f5-b528-90d1722f3aec.jpg)

I am able to see the medicine for the particular patient in the medicine tab
