### ISSUE TITLE
Mark Rounds by Virtual Nursing Assistant

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#4718]
Log Updates with RoundType = 300 should be marked as "Created by Virtual Nursing Assistant" in the Consultation Log History

**Comment by rithviknishad** [comment]
@gigincg I am finding difficulty finding out log updates coming of `rounds_type="AUTOMATED"` in staging.

However, the updated by and created by already seem to be using a fallback to show virtual nursing assistant as the username. 

Is that not working or should there be a different marker in the log update card to denote it was created by a virtual nursing assistant?
