### ISSUE TITLE
Add a dropdown to select dates for Patient export options

### ISSUE THREAD

**Issue by siddnikh** [coronasafe/care_fe#4753]
Currently, if we hover over the export options in the Patients tab, it shows that we need to select a 7-day period. 
Adding a dropdown that lets you select it there itself would be good for the UX.
<img width="1680" alt="Screenshot 2023-02-05 at 3 08 00 PM" src="https://user-images.githubusercontent.com/51060067/216811834-e71126b3-b47b-43bd-b647-e5bf7f4c0338.png">

**Comment by nihal467** [comment]
@GokulramGHV what is the update on this issue
