### ISSUE TITLE
Add validation for email in update profile page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4754]
**Describe the bug**

- [ ] email is " * " in the user profile updation page
- [ ] email input is not having a validation in the user profile updation page
 
**To Reproduce**

https://care.coronasafe.in/user/profile

**Expected behavior**

- [ ] add " * " to the email input in the user profile updation page
- [ ] add validation for the email input field

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/216813494-5a2cbc74-cedd-44eb-9e9b-393b05172db4.png)

**Comment by siva-balan** [comment]
Created a PR for this, please check.
