### ISSUE TITLE
Doctor connect is not working 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4760]
**Describe the bug**

The doctor connect in the patient consultation page is not showing any linked staff or doctors to the facility

**To Reproduce**

https://care.coronasafe.in/facility/520cfdc5-971d-4943-b545-81c9681ef093/patient/73ab43b2-fa30-4eaf-9a05-9b7351a95cb8/consultation/f9b24471-6452-419a-ba92-6b499b286e8c

**Expected behavior**

the home facility staff and all linked doctors should be present in the doctor connect  ( Home facility doctor in Doctors heading and non-home facility doctors in TeleICU Hub )

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/216822272-2b6a11db-4672-44b8-a6ce-3d222cdeec3b.png)

**Comment by khavinshankar** [comment]
The users are not showing up in the doctor connect as they don't have whatsapp number (alternate_phone_number) mentioned.

As this is an expected feature, closing this issue. A thought to improve UX, maybe we can also show the users without alternate number disabled and grayed out sorted to the end of the list

cc: @nihal467 @aparnacoronasafe
