### ISSUE TITLE
Enhancement of skill sidebar in the platform

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4768]
**Describe the bug**

- [ ] when we are trying to check another user's skills using a staff ID, it shows a " Not Found " error message

**To Reproduce**

https://care.coronasafe.in/users

**Expected behavior**

- any user can check other users linked skills using the users' tab page

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/216838809-e331d527-9739-4ec1-b692-6635ba29ec1b.png)

**Comment by nihal467** [comment]
- show user skill to other ids

**Comment by rithviknishad** [comment]
Duplicate of #4803
cc: @nihal467
