### ISSUE TITLE
Back Button: Malfunctioning

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4773]
- [ ] **Patient list**
When the user takes a facility and views the patients within the facility, open a particular patient dashboard. Then goes back, the user is taken to the complete list of patients in CARE rather than the facility-specific list.

- [ ] **Asset List** 
Same issue with the Asset list. When the user takes a facility and views the assets within the facility, open a particular asset page. Then goes back, the user is taken to the complete list of assets in CARE rather than the facility-specific list.

**Comment by rithviknishad** [comment]
An issue because useLocationChange's fullPath didn't preserve query params
