### ISSUE TITLE
Total Patient card is not consistent

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4785]
**Describe the bug**

When we are swapping between tabs such as asset, facilities, etc..., the card showing the total count in the top left side, is consistent for all the pages except the patient page

**To Reproduce**

1. go to: https://care.coronasafe.in/facility
2. select each tab randomly
3. see the error in consistency in the patient tab

**Expected behavior**

Redesign the patient tab as per the Figma design

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/217252075-554836bd-75da-486e-aedb-49b761b0df13.png)

**Comment by rithviknishad** [comment]
@nihal467 how about the design present in Figma?

![image](https://user-images.githubusercontent.com/25143503/217252807-1942e1c9-ffd3-4041-8402-94a407de344d.png)

**Comment by nihal467** [comment]
@rithviknishad as per the EOD, we will go with the Figma design in the screenshot you shared
