### ISSUE TITLE
Change "Ventilator Parameters" to "Respiratory Support"

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4809]
- [ ] When filing a critical care log update, in the index, change the heading "ventilator Parameters" to "Respiratory Support" (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/4e339b9d-1547-4f2f-9b80-64b378d9d835/consultation/781e00b4-af6a-4454-a729-52ae674d6948/daily_rounds/cad4123a-cd34-4464-96dd-b3c0938c5d89/update)
- [ ] Change heading in the ventilator parameter page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/4e339b9d-1547-4f2f-9b80-64b378d9d835/consultation/781e00b4-af6a-4454-a729-52ae674d6948/daily_rounds/cad4123a-cd34-4464-96dd-b3c0938c5d89/update) to respiratory support
- [ ] Change first section "ventilator interface" to "Respiratory Support" and change options to read as:
- Invasive ventilator (IV)-  (existing option-Invasive can be altered)
- Non-Invasive ventilator (NIV)-  (existing option-Non-Invasive can be altered)
- Oxygen Support (existing option-'None' can be altered)

**Comment by Ashesh3** [comment]
Acknowledged
