### ISSUE TITLE
Add Total Corona Triage

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4823]
**Describe the bug**
We can add a total corona triage row with the sum of data from all other triages on facility home page

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/711bd31a-feeb-4a9e-9893-b317579bfff8

**Sample view**
![image](https://user-images.githubusercontent.com/70687348/218957509-1d95a8b2-f054-43a4-b82b-d82bc354e186.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pranshu1902** [comment]
@nihal467 @khavinshankar @gigincg what's your opinion?

**Comment by nihal467** [comment]
@aparnacoronasafe do you think, is it relevant in the field right now.

**Comment by aparnacoronasafe** [comment]
@Pranshu1902 good thought. But nobody is using it now. We may phase it out in the future. Please do not waste effort on this.

**Comment by nihal467** [comment]
Anyone taking up the issue, before proceeding with it, take an opinion from @aparnacoronasafe / in EOD calls, to get align with current use-case

**Comment by Shahbaz898414** [comment]
@rithviknishad I would like to work on this. Can you assign me this issue?

**Comment by gigincg** [comment]
This is not a relevant number. Each row has cumulative count for that specific date
