### ISSUE TITLE
Bug : Badges are malfunctioning in patient tab

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4831]
**Describe the bug**

- [x] when we remove applied filters of primary  and emergency numbers using the badges , the data inputted in the field remain there itself
- [x] Unable to remove applied bed type filters using  the badges
- [x] the bed type filter badges and other filter are coming up in two lines

**To Reproduce**

https://care.coronasafe.in/patients?page=1&limit=12&name=&ip_no=&phone_number=&emergency_phone_number=&district=&lsgBody=&facility=&facility_type=TeleMedicine&date_declared_positive_before=&date_declared_positive_after=&date_of_result_before=&date_of_result_after=&created_date_before=&created_date_after=&modified_date_before=&modified_date_after=&date_of_result=&last_consultation_admission_date_before=&last_consultation_admission_date_after=&last_consultation_discharge_date_before=&last_consultation_discharge_date_after=&category=&gender=&disease_status=&age_min=&age_max=&last_consultation_admitted_bed_type_list=2%2C6&srf_id=&number_of_doses=&covin_id=&is_kasp=&is_declared_positive=&last_consultation_symptoms_onset_date_before=&last_consultation_symptoms_onset_date_after=&last_vaccinated_date_before=&last_vaccinated_date_after=&last_consultation_is_telemedicine=&is_antenatal=

**Expected behavior**

- [x] when we remove applied filters of primary  and emergency numbers using the badges , the data inputted in the field should be removed.
- [x] Bedtype filters should be coming in same line along with other badges and we should be able to remove the filters by closing the badges.

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/219339495-70960e4f-c90e-4b71-a29c-d4d144c703da.png)

**Comment by nihal467** [comment]
@cp-Coder push the fix ASAP

**Comment by aeswibon** [comment]
The code has been fixed. Will push the PR ASAP
