### ISSUE TITLE
Bottom align description in the auth layout

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4835]
**Describe the bug**
The description in the auth layout used to be bottom aligned. However, it's not at present.

**To Reproduce**

1. Go to care.coronasafe.in

**Expected behavior**
Description to be bottom aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/219403830-38141b91-0e5c-44f8-8b7c-6b1dea42a4c2.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by siva-balan** [comment]
I will be working on it.

**Comment by nihal467** [comment]
Thank you @siva-balan  for your contribution.
