### ISSUE TITLE
Control buttons of audio files are disabled

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4851]
**Describe the bug**
Not able to play the uploaded audio files, buttons are disabled

**To Reproduce**

1. Go to https://care.coronasafe.in/sample/bdb7b4ba-8778-4a75-93a6-7b14afbf444f
2. Scroll down to the Upload files section
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/220118479-afd457f3-359b-43ca-b2fb-20e61c91b569.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nihal467** [comment]
@Pranshu1902 

![image](https://user-images.githubusercontent.com/57055998/220125796-59ca3720-de4f-40b3-81bf-58d9f36c2296.png)


the issue is not there, can you check was your file not corrupted, can you check the URL you shared, I have uploaded a audio file, and it looks fine to me

**Comment by Pranshu1902** [comment]
@nihal467 Yeah, it working probably the file was corrupted.
Closing the issue
