### ISSUE TITLE
Add Corona Triage validation

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#4859]
**Describe the bug**
Should the user be allowed to add corona triage with the value of all fields as 0?

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/711bd31a-feeb-4a9e-9893-b317579bfff8
2. Scroll down to Corona Triage section

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/220359999-4cf0127a-3260-4e1d-b852-164b1f749391.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pranshu1902** [comment]
@nihal467 @khavinshankar @gigincg Is this intentional?

**Comment by nihal467** [comment]
@Pranshu1902 it is intentional
