### ISSUE TITLE
Change error statement colour from black to red in patient creation form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4867]
**Describe the bug**

in the patient creation form, the error statement for mandatory fields are shown in black color making it hard to understand the statement

**To Reproduce**

https://care.coronasafe.in/facility/4adaaff2-c6b2-4530-a518-3fbe44752421/patient

**Expected behavior**

 the error statement should be shown in red

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/220835658-e9d09917-01ad-4838-ba5e-a8b44ea36d6a.png)

**Comment by siva-balan** [comment]
Please assign this to me

**Comment by aparnacoronasafe** [comment]
@siva-balan The ideal design is as below:

<img width="553" alt="Screenshot 2023-02-24 at 8 14 37 AM" src="https://user-images.githubusercontent.com/67050716/221079990-015996a3-1ede-4249-955c-0ab4eca8fcd7.png">

**Comment by rithviknishad** [comment]
@siva-balan you may make use of `FormField` components such as `TextFormField` and `TextAreaFormField` that would automatically apply the required designs and behaviors that is consistent with other places.

**Comment by nihal467** [comment]
@siva-balan can you push a fix ASAP

**Comment by siva-balan** [comment]
> @siva-balan can you push a fix ASAP

I will push it by today
