### ISSUE TITLE
View procedures in Patient Dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4871]
**Is your feature request related to a problem? Please describe.**
We are recording procedures suggested for a patient in the consultation form (https://care.coronasafe.in/facility/e6b40cf4-4196-4e7d-83f0-b0bf5c38458a/patient/b80bbd73-8d8b-47ba-8a71-12a2bbfd65b2/consultation) However, we are not viewing the information anywhere.

**Describe the solution you'd like**
Add a card in the Patient Dashboard below "General Instructions" to show additional details about each of the procedures suggested. Keep the design consistent with the "prescription" and "General Instructions" cards.

**Comment by jeromtom** [comment]
Hi @aparnacoronasafe , I am currently working on this issue. There are two problems with keeping the design consistent with "General Instruction" cards with reference to my local build:
![image](https://user-images.githubusercontent.com/83979298/222643450-d1855082-f429-404d-968a-1820e7fc6c9d.png)


1. "General Instructions" card accepts only strings but the Procedure card would need a boolean.
2.  "General Instruction" card is too small to show details of the Procedure.

Hence, I am going for "Body Details" card clone.
