### ISSUE TITLE
Review after- add more options

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4883]
**Is your feature request related to a problem? Please describe.**
There are features to add "Review after <time>" on patient file. This is available both in Consultation form (only when telemedicine is marked yes( (https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/36cdd810-c3e1-45dd-993c-2877a46e35de/consultation/48f289bb-8ae2-46d8-b6b1-4840fa6f2385/update) and Log Update form (https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/36cdd810-c3e1-45dd-993c-2877a46e35de/consultation/48f289bb-8ae2-46d8-b6b1-4840fa6f2385/daily-rounds/2ec7e218-001c-4871-a4d5-5f8132d325b9/update)

The dropdown in the field gives a list of time intervals starting with 30min. 

We need to allow the user to set shorter time intervals for review time.

**Describe the solution you'd like**
Add "10 min" and "15 min" as options in the "review time" dropdown. These options must appear on top of the list in the dropdown.

**Comment by jeromtom** [comment]
@aparnacoronasafe, Sharing links won't help as it is behind a login. Use screenshots, next time. Thank you for raising the issue.

**Comment by nihal467** [comment]
Thank you @jeromtom for your contribution.
