### ISSUE TITLE
Doctor's Notes: Option to edit

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4884]
**Is your feature request related to a problem? Please describe.**
CARE has a feature for doctor's to leave notes on a patient file. (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/notes)

Here any doctor can post a note about the patient which can be viewed by other users. 

However, if the doctor incorrectly enters some suggestion and submits it, there is no way for the doctor to edit or correct it.

**Describe the solution you'd like**

- [ ] Allow the user that has posted a note to edit the note within 'X' hrs of posting such a note. 'X' (No. of hours) must be easily configurable 
- [ ] Set X to half an hour for the time being
- [ ] When a note is edited, show the time and date of such updation.
<img width="1099" alt="Screenshot 2023-02-25 at 12 14 15 PM" src="https://user-images.githubusercontent.com/67050716/221343039-0a4d0632-5609-464c-adad-da6ad450bcae.png">
(please keep the font and colour of text consistent with the note created date and time- the design in only indicative)

**Comment by Ashesh3** [comment]
@aparnacoronasafe Is this still relevant after the doctor notes was redesigned as a chat feature?

cc: @nihal467

**Comment by Ashesh3** [comment]
Fixed by https://github.com/coronasafe/care_fe/pull/6919
