### ISSUE TITLE
Transfer allowed flags on patient list- hide

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4886]
**Is your feature request related to a problem? Please describe.**
The transfer allowed/transfer blocked flags on the patient list (https://care.coronasafe.in/patients?page=1&limit=12&name=) is not very relevant today. 

**Describe the solution you'd like**
Hide the 'Transfer allowed' and 'transfer blocked" flags from the patient list.

**Comment by jeromtom** [comment]
![image](https://user-images.githubusercontent.com/83979298/221382220-c3806b2e-34ca-43d8-9bbd-8c6439f0e357.png)
Please send screenshots of the issue

**Comment by jeromtom** [comment]
> ![image](https://user-images.githubusercontent.com/83979298/221382220-c3806b2e-34ca-43d8-9bbd-8c6439f0e357.png) Please send screenshots of the issue

I didn't know about the login before.
