### ISSUE TITLE
advanced filter on patient list- renaming fields

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4887]
**Is your feature request related to a problem? Please describe.**
There are parameters in the advanced filter in the patient list (https://care.coronasafe.in/patients) to filter patients based on

- "Disease Status"
- "Vaccinated"
- "Date of result"
- "Date declared positive"
- "Vaccination Date"

This actually refers to the COVID Disease Status and COVID Vaccinations. This is not clear.

"Created date" refers to the date the patient is registered on. 

**Describe the solution you'd like**
In the advanced filter, 

- [ ] edit "Disease status" to "COVID Disease status"
- [ ] edit "Vaccinated" to "Vaccinated against COVID"
- [ ] edit "Date of result" to "Date of COVID test result"
- [ ] edit "Date declared positive" to "Date declared COVID positive"
- [ ] edit "Vaccination Date" to "COVID Vaccination Date"
- [ ] edit "Created date" to "Registration Date"

**Comment by nihal467** [comment]
Thank you @jeromtom for your contribution.
