### ISSUE TITLE
Bug: Pressure sore view

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#4894]
**Describe the bug**
In pressure sore view (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326/consultation/c5e82e5f-2bab-4cab-9239-307770792bce/pressure_sore) where there is a list of such body  parts with PUSH SCORE. The list contains an "X" , but it has no function.

**solution**
<img width="1165" alt="Screenshot 2023-02-27 at 10 19 34 AM" src="https://user-images.githubusercontent.com/67050716/221478810-7ee54b21-cfd5-4881-9f46-064cedeaabc8.png">

remove the "X"

**Comment by jeromtom** [comment]
The X has a function i.e to deselect the selected item. Ideally, it should be hidden for user roles who cannot edit and enabled for user roles who can edit.
![image](https://user-images.githubusercontent.com/83979298/221647600-a385f981-27c8-411a-a890-6f563378ea87.png)

![image](https://user-images.githubusercontent.com/83979298/221646750-ad1db797-30ee-4d8a-b20c-0257e0ecf930.png)

**Comment by jeromtom** [comment]
Can I have info on who should be able to edit i.e remove the selected item if needed?

**Comment by rithviknishad** [comment]
@aparnacoronasafe
