### ISSUE TITLE
Replace Material UI components in `src/Components/Facility/ConsultationDetails.tsx`:

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4948]
```tsx
2: import { Button, CircularProgress } from "@material-ui/core";\n35: import Dialog from "@material-ui/core/Dialog";\n36: import DialogActions from "@material-ui/core/DialogActions";\n37: import DialogContent from "@material-ui/core/DialogContent";\n38: import DialogContentText from "@material-ui/core/DialogContentText";\n39: import DialogTitle from "@material-ui/core/DialogTitle";
```

### Tasks

Ensure all the below tasks are accomplished if applicable to the file being modified in the PR.

- [ ] Migrate all Material UI components to use new Care UI / custom components. (ref: [🛠️ Tailwinding Care](https://github.com/coronasafe/care_fe/issues/3742))
- [ ] Migrate all Material UI icons to use [🏥 **Care Icons**](https://github.com/coronasafe/care_fe/pull/4071).
- [ ] Migrate `PageTitle` to `Page` component if any. (See [example](https://github.com/coronasafe/care_fe/pull/4796/files#diff-8e39f154ccf13c9dedd0f968d21a0abbde450e88df9724a4e7d4264d487a7846))

For more information see the epic issue that tracks this issue.

**Comment by vishvjeet-thakur** [comment]
Hello sir, 
If this issue is open  can I work on this?

**Comment by rithviknishad** [comment]
@vishvjeet-thakur any updates?

**Comment by rithviknishad** [comment]
Closing as this seems to be completed without this issue being linked.
