### ISSUE TITLE
Replace Material UI components in `src/Components/Facility/FacilityCreate.tsx`:

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4952]
```tsx
1: import { Card, CardContent } from "@material-ui/core";\n2: import Popover from "@material-ui/core/Popover";
```

### Tasks

Ensure all the below tasks are accomplished if applicable to the file being modified in the PR.

- [ ] Migrate all Material UI components to use new Care UI / custom components. (ref: [🛠️ Tailwinding Care](https://github.com/coronasafe/care_fe/issues/3742))
- [ ] Migrate all Material UI icons to use [🏥 **Care Icons**](https://github.com/coronasafe/care_fe/pull/4071).
- [ ] Migrate `PageTitle` to `Page` component if any. (See [example](https://github.com/coronasafe/care_fe/pull/4796/files#diff-8e39f154ccf13c9dedd0f968d21a0abbde450e88df9724a4e7d4264d487a7846))

For more information see the epic issue that tracks this issue.

**Comment by rithviknishad** [comment]
@print-Sathvik any updates on this? Avoid taking up multiple issues.

**Comment by print-Sathvik** [comment]
Replacing MateriaUI is completed but the GLocationPicker element is not working properly in mobile view and at lower screen width, even in the live deployment. When the location select button is clicked, the search bar and close button are occupying the entire popover element without displaying the map.

@rithviknishad Should I create a PR for the completed part and create new issue for GLocationPicker?

**Comment by rithviknishad** [comment]
Yes, if that issue is present in existing staging, yes create the issue!

**Comment by rithviknishad** [comment]
Do create the PR though, we can take that issue seperatley
