### ISSUE TITLE
Replace Material UI components in `src/Components/Patient/PatientRegister.tsx`:

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4980]
```tsx
9: } from "@material-ui/core";\n53: import { InfoOutlined } from "@material-ui/icons";\n54: import ExpandMoreIcon from "@material-ui/icons/ExpandMore";\n70: import { MaterialUiPickersDate } from "@material-ui/pickers/typings/date";
```

### Tasks

Ensure all the below tasks are accomplished if applicable to the file being modified in the PR.

- [ ] Migrate all Material UI components to use new Care UI / custom components. (ref: [🛠️ Tailwinding Care](https://github.com/coronasafe/care_fe/issues/3742))
- [ ] Migrate all Material UI icons to use [🏥 **Care Icons**](https://github.com/coronasafe/care_fe/pull/4071).
- [ ] Migrate `PageTitle` to `Page` component if any. (See [example](https://github.com/coronasafe/care_fe/pull/4796/files#diff-8e39f154ccf13c9dedd0f968d21a0abbde450e88df9724a4e7d4264d487a7846))

For more information see the epic issue that tracks this issue.

**Comment by yogeshbhutkar** [comment]
I would like to take up this issue.

**Comment by thtauhid** [comment]
Hi, @rithviknishad is this issue available? I would like to work on it.

**Comment by Ashesh3** [comment]
Unassigning due to inactivity and taking it up with the form draft PR.

**Comment by rithviknishad** [comment]
Hey @Ashesh3 any updates on this?
