### ISSUE TITLE
Replace Material UI components in `src/Components/Resource/ResourceDetailsUpdate.tsx`:

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4994]
```tsx
23: import { CircularProgress } from "@material-ui/core";\n32: } from "@material-ui/core";
```

### Tasks

Ensure all the below tasks are accomplished if applicable to the file being modified in the PR.

- [ ] Migrate all Material UI components to use new Care UI / custom components. (ref: [🛠️ Tailwinding Care](https://github.com/coronasafe/care_fe/issues/3742))
- [ ] Migrate all Material UI icons to use [🏥 **Care Icons**](https://github.com/coronasafe/care_fe/pull/4071).
- [ ] Migrate `PageTitle` to `Page` component if any. (See [example](https://github.com/coronasafe/care_fe/pull/4796/files#diff-8e39f154ccf13c9dedd0f968d21a0abbde450e88df9724a4e7d4264d487a7846))

For more information see the epic issue that tracks this issue.

**Comment by MayaSatishRao** [comment]
@rithviknishad can I do one of the tasks mentioned and create a pr? If so, can you assign this issue to me?

**Comment by rithviknishad** [comment]
u r expected to do all that are applicable.

**Comment by MayaSatishRao** [comment]
There are many components that are imported from Material UI like Circular Progress, Radio Group in the file. So we need to implement them using Typescript and Tailwind CSS right?

**Comment by rithviknishad** [comment]
read the EPIC #5006 
all components are already built.

**Comment by MayaSatishRao** [comment]
@rithviknishad In ResourceDetailsUpdate.tsx file Radio, RadioGroup, FormControlLabel, CardContent, Box are also imported. But I could not find these components.

**Comment by rithviknishad** [comment]
You won't have exact word to word component replacement. 

Checkout how `RadioFormField` is used in other places.

You don't need RadioGroup when using that. Same for box and card content, just use divs.

**Comment by rithviknishad** [comment]
All Legacy components should also be replaced with it's equivalent FormField components

**Comment by MayaSatishRao** [comment]
@rithviknishad ok, can you assign this issue to me?

**Comment by rithviknishad** [comment]
@MayaSatishRao any updates on this?

**Comment by MayaSatishRao** [comment]
@rithviknishad I am working on this. Been a little busy working on the proposal. I will finish it within 2 days

**Comment by MayaSatishRao** [comment]
@rithviknishad I am working on this. Been a little busy working on the proposal. I will finish it within 2 days

**Comment by rithviknishad** [comment]
@MayaSatishRao any updates?

**Comment by MayaSatishRao** [comment]
I will make a pr by eod @rithviknishad
