### ISSUE TITLE
Replace Material UI components in `src/Components/Shifting/ShiftingBoard.tsx`:

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5000]
```tsx
8: import Button from "@material-ui/core/Button";\n11: import { Modal } from "@material-ui/core";\n13: import CircularProgress from "@material-ui/core/CircularProgress";
```

### Tasks

Ensure all the below tasks are accomplished if applicable to the file being modified in the PR.

- [ ] Migrate all Material UI components to use new Care UI / custom components. (ref: [🛠️ Tailwinding Care](https://github.com/coronasafe/care_fe/issues/3742))
- [ ] Migrate all Material UI icons to use [🏥 **Care Icons**](https://github.com/coronasafe/care_fe/pull/4071).
- [ ] Migrate `PageTitle` to `Page` component if any. (See [example](https://github.com/coronasafe/care_fe/pull/4796/files#diff-8e39f154ccf13c9dedd0f968d21a0abbde450e88df9724a4e7d4264d487a7846))

For more information see the epic issue that tracks this issue.

**Comment by ayushjnv1** [comment]
assign to me I will do it

**Comment by rithviknishad** [comment]
@ayushjnv1 if the work is not yet completed and you are willing to complete it, you may create a draft PR and link this issue to it.

Unassigned to prevent this issue from being blocked.

Feel free to ping if you are facing any blockers.

**Comment by suprabathk** [comment]
@rithviknishad 
I'm willing to work on this issue
Can you assign it to me

**Comment by rithviknishad** [comment]
@suprabathk before you put your efforts into this issue, could you hold on until @gigincg confirms? Since there are lots of changes about to come up in the Shifting module, it's highly likely that your efforts may get overwritten.
