### ISSUE TITLE
Replace Material UI components in `src/Components/Users/UserDeleteDialog.tsx`:

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5005]
```tsx
8: } from "@material-ui/core";
```

### Tasks

Ensure all the below tasks are accomplished if applicable to the file being modified in the PR.

- [ ] Migrate all Material UI components to use new Care UI / custom components. (ref: [🛠️ Tailwinding Care](https://github.com/coronasafe/care_fe/issues/3742))
- [ ] Migrate all Material UI icons to use [🏥 **Care Icons**](https://github.com/coronasafe/care_fe/pull/4071).
- [ ] Migrate `PageTitle` to `Page` component if any. (See [example](https://github.com/coronasafe/care_fe/pull/4796/files#diff-8e39f154ccf13c9dedd0f968d21a0abbde450e88df9724a4e7d4264d487a7846))

For more information see the epic issue that tracks this issue.

**Comment by akshatvermavi** [comment]
If nobody is working please assign it to me @rithviknishad

**Comment by rithviknishad** [comment]
@akshatvermavi I think you can clearly see that there's a PR already for this right?

**Comment by akshatvermavi** [comment]
Yes sir @rithviknishad the PR is [Replaced Material UI components to CAREUI](https://github.com/coronasafe/care_fe/pull/5607#top)
#5607  Merging is blocked. Sorry for them sir because reassigning someone else work to me might disrupt the workflow and cause confusion.
