### ISSUE TITLE
Replace Material UI components with CareUI/custom components

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5006]
> 👉🏼 **Do not assign this issue to yourself, you may assign sub-issues of this epic.**
> 👉🏼 **Feel free to re-open the below-closed as not planned (not the ones that are closed as completed) issues once existing open issues are solved.**

- Now that we have pretty good coverage on the custom components (ref: [🛠️ Tailwinding Care](https://github.com/coronasafe/care_fe/issues/3742)) we can **replace all the existing usages of Material UI components and icons with custom components and** [🏥 **Care Icons**](https://github.com/coronasafe/care_fe/pull/4071).

- Migrate usages of `Legacy<ComponentName>` components if present in the file.

- Most of the below tasks consist of page-by-page migrations, hence also **consider migrating from the `PageTitle` with `Page` component** if `PageTitle` exists in the file you'll be modifying in the task. (See [example](https://github.com/coronasafe/care_fe/pull/4796/files#diff-8e39f154ccf13c9dedd0f968d21a0abbde450e88df9724a4e7d4264d487a7846))

- To migrate usages of `Tooltip`, use the `tooltip` class on parent component and `tooltip-text` in combination with `tooltip-[right/left/top-bottom]` classes for the tooltip text element. (See [example](https://github.com/coronasafe/care_fe/pull/4819/files#diff-f15a132265ab339453f06bc7dc6b773802090dfba335c46051a309b512de2060R202-R207))

## Primary Objective of this EPIC

- Get rid of all material UI dependencies and legacy components.

### Tasks

- [x] #4928
- [x] #4929
- [x] #4930
- [x] #4931
- [x] #4932
- [x] #4933
- [x] #4934
- [x] #4935
- [x] #4936
- [x] #4937
- [x] #4938
- [x] #4939
- [x] #4940
- [x] #4941
- [x] #4942
- [x] #4943
- [x] #4944
- [x] #4945
- [x] #4946
- [x] #4947
- [x] #4948
- [x] #4949
- [x] #4950
- [x] #4951
- [x] #4952
- [x] #4953
- [x] #4954
- [x] #4955
- [x] #4956
- [x] #4957
- [x] #4958
- [x] #4959
- [x] #4960
- [x] #4961
- [x] #4962
- [x] #4963
- [x] #4964
- [x] #4965
- [x] #4966
- [x] #4967
- [x] #4968
- [x] #4969
- [x] #4970
- [x] #4971
- [x] #4972
- [x] #4973
- [x] #4974
- [x] #4975
- [x] #4976
- [x] #4977
- [x] #4978
- [x] #4979
- [x] #4980
- [x] #4981
- [x] #4982
- [x] #4983
- [x] #4984
- [x] #4985
- [x] #4986
- [x] #4987
- [x] #4988
- [x] #4989
- [x] #4990
- [x] #4991
- [x] #4992
- [x] #4993
- [x] #4994
- [x] #4995
- [x] #4996
- [x] #4997
- [x] #4998
- [x] #4999
- [x] #5000
- [x] #5001
- [x] #5002
- [x] #5003
- [x] #5004
- [x] #5005
- [x] #5699
- [x] #5762

**Comment by sandhyasrini** [comment]
Hello! I can pick this one up if it is still pending to be picked

**Comment by nikhilagastya** [comment]
hey @nihal467 can i work on few of the components

**Comment by rithviknishad** [comment]
@nikhilagastya sub issues for the same have been created. you may take up those.
