### ISSUE TITLE
Software Update pop-up is malfunctioning on apple safari browser 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5015]
**Describe the bug**

When we are opening the care website, the software update pop-up comes in, and when we click the update button in the pop-up, the loading icon inside the pop-up will keep on rotating in an infinite loop

**To Reproduce**

1. Go to care.coronasafe.in
2. Click Update in the Software update pop-up
3. See the error

**Expected behavior**

The software pop-up should be working properly, when the user clicks update, it should be fetching the latest version of the software

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/222070249-a6b4f477-8e66-48b7-bfc8-a54fe545a0bb.png)

**Comment by Ashesh3** [comment]
Unable to replicate.

![msedge_dhMV8vIC2z](https://user-images.githubusercontent.com/3626859/222090699-814fb9b2-4e9a-477d-a92d-25f1f4a6866e.gif)

Tested on:
- Iphone 14
- iOS: v16.2
- Safari: 16.3

**Comment by nihal467** [comment]
@Ashesh3 closing the issue, seems to be a cache issue
