### ISSUE TITLE
Redesign Doctor Notes as a Chat Feature

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#5033]
Doctor Notes in CARE is a feature that allow keeping notes specific to a Patient. This can be upgraded keeping the following things in mind

- Notes should be visible as a chatbox (Expandable to a dedicated page)
- New Notes should work as if they are Chat Notifications.

**Comment by Rohanxmalik** [comment]
I can try to contribute to it under C4GT, please elaborate and assign it to me.

**Comment by rithviknishad** [comment]
Duplicate of #5493
