### ISSUE TITLE
Pain Scale data to be added in summary page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5042]
# Follow-up issue for the PR: #5039 

**Describe the bug**

- [ ] Pain scale data are reflected in a graphical view on the summary section of the patient consultation page and is not showing the whole data, as the pain scale is recorded now in the human anatomy structure.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/98375114-038b-4c95-a580-86d9ad09d06a/patient/e20f56a7-f822-4087-80e7-ec85d05849c8/consultation/411a34f3-aa20-4b09-8d9f-0f38b5ee3ff2/summary
2. Scroll down to the bottom of the page
4. See the error

**Expected behavior**

- [x] remove existing pain scale graph card
- [ ] we should be showing the pain scale in a human anatomy preview mode at the bottom of the summary page   ( similar to pressure sore data reflected on the patient consultation page )

**All the changes should be made on the summary page of a patient consultation page** since it is already filled with multiple data, @cp-Coder discuss the UI in the EOD, and once its approved, work on it

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/223656191-77b17e9e-a564-449f-a892-26edab08ee99.png)

**Comment by aeswibon** [comment]
@nihal467 Will add these functionality in PR #5044

**Comment by nihal467** [comment]
@cp-Coder as per our slack communication, I agree with the statement that, the rhythm would be requiring a lot of space, can you think of a better UI to solve the problem, we can discuss it in today's EOD call

**Comment by nihal467** [comment]
@cp-Coder you can start working on this issue, #5097 is merged. The existing pain scale card is already in the #5097 PR, you can work on the remaining issue
