### ISSUE TITLE
Delete all Bed capacity button

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5046]
**Describe the bug**
Inside the total bed capacity card, we should have a button to delete all bed capacities.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/ea9a2fbe-74f3-446b-bdb0-e038766bfb09
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/223129612-8515ca12-fa3d-481f-9886-ee448de1d25e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pranshu1902** [comment]
@nihal467 @khavinshankar @gigincg should I add this feature?

**Comment by nihal467** [comment]
we decided not to go forward with it
