### ISSUE TITLE
Get rid of material-ui/icons

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#5049]
There are only around 15 usages of material-ui/icons across the entire codebase. 

Let's refactor that to use CareIcons

**Comment by ayushjnv1** [comment]
can you please tell which doc refer for class name for careicons? so I  will replace all remain mui icons @gigincg

**Comment by rithviknishad** [comment]
@ayushjnv1  You may use [unicons library](https://iconscout.com/unicons/explore/line) to browse icons.
Suppose you want to use an unicon line icon: `analysis`, you may achieve it with `CareIcons` like:

`<CareIcon className="care-l-analysis text-lg" />`

For more refer: https://github.com/coronasafe/care_fe/pull/4071

**Comment by ayushjnv1** [comment]
ok, got it. Assign to me this issue so I replace all mui Icon

**Comment by ayushjnv1** [comment]
there are some icon that is not exactly match with MUI icon.
like LocationOnOutlined MUI icon according to me replacement is l-map-marker but which not exact match.
So what can I do for that ?

**Comment by rithviknishad** [comment]
@ayushjnv1 `map-marker` is fine.

As long as the alternative icon's intention/meaning conveyed to the user is the same, it should be fine.

**Comment by ayushjnv1** [comment]
https://github.com/coronasafe/care_fe/pull/5062/

**Comment by rithviknishad** [comment]
@ayushjnv1 have a look at [Linking a PR to an issue using keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) :) 
This way when the PR is merged, the issue gets closed automatically and there are other benefits too.
