### ISSUE TITLE
Occupied beds must not be available in Update bed Drop-down

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5080]
https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/4e339b9d-1547-4f2f-9b80-64b378d9d835/consultation/781e00b4-af6a-4454-a729-52ae674d6948

When updating bed for a patient/ assigning bed for a patient, the dropdown with list of beds show list of all beds registered. However, the patient can be only be assigned to a bed thats not occupied at the point.

Show only the unoccupied beds in the update/Assign bed dropdown

**Comment by rithviknishad** [comment]
Ack
