### ISSUE TITLE
Reordering Consultation Fields

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#5087]
The fields of the consultation form does not seem logical.

For Instance, it is based on the Diagnosis that Procedures are planned. But in the UI, Diagnosis Is after Procedures, Advice, Treatment Plan etc.

@aparnacoronasafe to comment

**Comment by GokulramGHV** [comment]
Clarification: The ordering of the fields in the consultation form needs to be redesigned to make it more logical. @aparnacoronasafe

**Comment by nihal467** [comment]
#5045 the issue is resolved, in the mentioned PR
