### ISSUE TITLE
Pressure pop-up not scrolling along with page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5088]
**Describe the bug**
- [ ] When we open a pressure sore pop-up and scroll, the pop-up doesn't scroll along with it.
- [ ] Pop-up does not close when clicked outside

**To Reproduce**

1. Go to a patient's pressure sore tab
2. Click on any body part.
3. Scroll / click outside.

**Expected behavior**
- [ ] Pop-up may scroll along with the page.
- [ ] Pop-up may close when clicked outside.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/224351563-746d7935-0945-4074-bff3-375f3b8b3cd4.png)

![image](https://user-images.githubusercontent.com/25143503/224351607-9e4e78b6-e503-4d2a-981b-d3c9bfa0d60d.png)

**Comment by nikhilagastya** [comment]
hey @khavinshankar can you assign me this issue

**Comment by nikhilagastya** [comment]
working on it !

**Comment by Rohanxmalik** [comment]
Are you still working on this @nikhilagastya . If not I want to contribute under C4GT, please assign it to me.

**Comment by nikhilagastya** [comment]
hey @rithviknishad could u help me with something , Here to remove the modal I need to work on pressure_sore_editor.res file right ? Coz earlier i was working on a .bs file and the changes got removed whenever i was deploying on the localhost .

**Comment by rithviknishad** [comment]
.bs files are generated files. You need to update the rescript files

**Comment by nihal467** [comment]
@nikhilagastya unassigning you from this issue, due to inactivity for almost two months

CC: @rithviknishad

**Comment by sghosh28** [comment]
Hey @rithviknishad
I hope this message finds you well. I've been diligently working on the project and I'm excited to update you on the progress I've made so far:
- [ x] Resolved the issue where the pop-up doesn't close when clicked outside.

With this done, I'm now moving on to tackle the next challenge: addressing the scroll-along-with-page problem. I'm confident I can make headway on this front as well.

Could you kindly assign this task to me?

**Comment by sghosh28** [comment]
Hello @rithviknishad ,

I'm pleased to inform you that I've successfully resolved both of the mentioned issues:

- [x] The pop-up now remains appropriately positioned as the page is scrolled.
- [x] The pop-up is designed to close when clicking outside of it.

Could you kindly review the pull request at your earliest convenience?

Thank you!

**Comment by sghosh28** [comment]
Hey @rithviknishad,

I have made new changes, can you please review my pull request?
Thank you!

**Comment by stokedowl** [comment]
@nihal467 Is this still a bug? I cannot seem to reproduce locally. Let me know if it is, I can pick it up.

**Comment by gigincg** [comment]
@stokedowl This is still an issue, @sghosh28 had attempted to fix the issue, but it seems to have been a little buggy. You could try salvaging the PR or you could make a new PR.

**Comment by gigincg** [comment]
@stokedowl The PR from @sghosh28 was not salveageable due to a recent refactor from Rescript to Typescript for the applicable files. I made a PR to fix the issue. I'm not an expert at Positioning, so I would appreciate a review.

If you can think of a better solution please do let us know & Feel free to take up any other issues as well.

You can also join in on our slack community at https://slack.ohc.network/ Where you can reach the team for any questions/discussions.
