### ISSUE TITLE
No loading feedback when add skill button is pressed

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5119]
**Describe the bug**
When we select a skill and add it for a user, there's no loading animation that conveys it's being added.

**To Reproduce**

1. Go to users list and attempt to add a skill to user

**Expected behavior**
Show a loading spinner icon beside add button text while it's being added.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/225864915-25508d74-6524-4582-bfb4-7abba9fb2b62.png)

**Comment by AdrianaMoralesQ** [comment]
Hi, I'll take this on!

**Comment by rithviknishad** [comment]
fixed via #5129
