### ISSUE TITLE
Revamp Show User linked skills button

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5132]
**Describe the bug**
Revamp Show User linked skills button

**To Reproduce**

1. Go to http://localhost:4000/users
2. See error

**Expected behavior**
Make it similar to that of the Linked Facility button

**Sample Screenshots**
![image](https://user-images.githubusercontent.com/70687348/226311653-1f7c7e65-9d93-4f15-91c2-3d47995855e7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pranshu1902** [comment]
@nihal467 @khavinshankar @gigincg what's your opinion?

**Comment by nihal467** [comment]
@Pranshu1902 Make two buttons for linked facilities and skills , name the buttons : 

1. linked facilities
2. skills
