### ISSUE TITLE
Add date of discharge to Discharge patient pop-up in patient consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5168]
**Describe the bug**

On the patient consultation page, the discharge patient pop-up for the reasons "LAMA" and "Referred" are just showing a note and we are not having a field to input the date related to the same.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/fc09dbc9-015a-4194-8dc8-14ccee34eee9/patient/61444d60-0aaf-4aa7-9463-b7a518969f9a/consultation/da16092c-972d-429f-a406-5958b6691110
2. Click on " discharge from care " button
3. Select the reason "LAMA"

**Expected behavior**

We should be having a date field for the "LAMA" and "referred" reasons in the patient discharge pop-up

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/227851019-0e4281f2-2e60-47d7-bc7a-d644778bc338.png)

**Comment by aparnacoronasafe** [comment]
good to go.

The field may be called "Date of Discharge"
