### ISSUE TITLE
Discharge: recovered- rename field

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5196]
**Describe the bug**
The pop-up box for entering the discharge details, when the reason is given as recovered, there is a last input field called "Description advice" the title makes no sense. 

**To Reproduce**

1. Go to the patient file (https://care.coronasafe.in/facility/41c73414-e95e-4e50-b0b9-84bafb3b7440/patient/2d7a2c15-83c3-44b9-9af4-f4d3f791d0c8/consultation/453295d1-37dc-46a5-9b97-c64ef61988fd)
2. Click on 'Discharge from CARE.'
3. Select the reason for discharge as "recovered"
4. See the last field in the pop-up window

**Expected behavior**

- [ ] Change the title of the last field from Description advice to "Discharge SOS Prescription"
- [ ] Change the prescription input module below to an SOS prescription input format

**Screenshots**
<img width="800" alt="Screenshot 2023-03-29 at 7 41 12 PM" src="https://user-images.githubusercontent.com/67050716/228571597-37645494-a556-4c6e-b0f4-36ca15815406.png">

**Comment by Ashesh3** [comment]
@aparnacoronasafe Can you shed some light on "SOS prescription input format"? Is it one of the below?

![image](https://user-images.githubusercontent.com/3626859/228573066-621d2cc5-a8d6-4375-8a97-811ffa669a04.png)

![image](https://user-images.githubusercontent.com/3626859/228573110-903f5cf3-8d4b-4f77-b316-9be037516b0b.png)

**Comment by aparnacoronasafe** [comment]
The first one @rithviknishad

**Comment by rithviknishad** [comment]
@Ashesh3
