### ISSUE TITLE
Update Buttons for Doctors List card

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5230]
**Describe the bug**
The Doctors List card has buttons named as `Edit` and `Button`. Instead we can add the icons like that in the Bed Capacity card.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/56de8619-ac54-4517-b38b-93b4f83249c3
2. Scroll down to `Doctors List`

**Expected behavior**
Icons should be added to make it more consistent

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/229741254-df47ceef-9ce1-42b4-be01-4b56bc308bb2.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nihal467** [comment]
@Pranshu1902 doesn't feel like it is required for now
