### ISSUE TITLE
Make Save Configuration button full width

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5236]
**Describe the bug**
The `Save Configuration` button should be full width just like the `Update Bed` button in the desktop view.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/a7651c6a-a9b7-4ab7-8efa-4ccabf8c9009/assets/4bbaff12-2e47-4785-b312-3b85c456f866/configure
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/229996080-378b62cd-9068-4d0a-9cb0-4844ae075b17.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranit-yawalkar** [comment]
Hey, I would like to work on this.

**Comment by pranit-yawalkar** [comment]
Getting this error, how to resolve this?

X [ERROR] The JSX syntax extension is not currently enabled

    node_modules/react-csv/src/components/Link.js:102:6:
      102 │       <a
          ╵       ^

The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able
to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.

**Comment by rithviknishad** [comment]
@pranit-yawalkar have you tried running `npm install` before `npm run dev`?

**Comment by pranit-yawalkar** [comment]
yes, this error is coming when I run npm run dev after npm install.

**Comment by rithviknishad** [comment]
@pranit-yawalkar this seems to happen in windows only.

You may upgrade `react-csv` package and work on the PR or you may use WSL.
