### ISSUE TITLE
Can we get discharged summary in printable format instead of sending to an email?

### ISSUE THREAD

**Issue by Deepjyoti14** [coronasafe/care_fe#5237]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aparnacoronasafe** [comment]
@Ashesh3 what is the Expected date of completion for this?

**Comment by Ashesh3** [comment]
> @Ashesh3 what is the Expected date of completion for this?

We had some issues last week regarding patient discharge. All those are resolved now. I'll get this feature done by tonight.

Edit: The feature requires backend changes which are being worked on by @sainak . ETA given by Khavin is by Wednesday.

**Comment by aparnacoronasafe** [comment]
@Ashesh3 @nihal467 Please expedite it

**Comment by Ashesh3** [comment]
> @Ashesh3 @nihal467 Please expedite it

@sainak Are the required changes done on the backend? Is this issue ready to be worked on at the front end?

**Comment by sainak** [comment]
> > @Ashesh3 @nihal467 Please expedite it
> 
> @sainak Are the required changes done on the backend? Is this issue ready to be worked on at the front end?

Both the backend and frontend changes are done and they are under review

**Comment by aparnacoronasafe** [comment]
@nihal467 @Ashesh3 Where are we with this Issue? Why dont I see a PR linked?

**Comment by Ashesh3** [comment]
> @nihal467 @Ashesh3 Where are we with this Issue? Why dont I see a PR linked?

@aparnacoronasafe I am not longer assigned to this issue. @sainak is taking care of this. cc'ing him here.
