### ISSUE TITLE
O2 is bydefault getting selected in respiratory support of patient critical care log update 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5254]
**Describe the bug**

When we create a critical care log update for the patient, without selecting the respiratory section, the patient is by default shown in 02 respiratory support.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/a7651c6a-a9b7-4ab7-8efa-4ccabf8c9009/patient/b51f618c-68b4-4ef0-9614-ad29e66131a9/consultation/f3ebae95-b767-474e-9f58-0ceae9a2f5cf
2. Click on log update
3. select critical care
4. input data in any section other than respiratory support and save it
5. See error

**Expected behavior**

When we create a critical care log update, without selecting the respiratory section, the patient shouldn't be having O2 respiratory support by default selected

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/230356561-233e491e-340c-4f11-8a5e-02a3b1ec66e1.png)

**Comment by shivankacker** [comment]
Acknowledged

**Comment by gigincg** [comment]
https://github.com/coronasafe/care_fe/pull/4810/files#diff-d87205b509f4d11a0ac60ff34e9eaec19d747ca0b553fc1d8227844299953727L162

Add Oxygen Support as a Separate Option.

Handle the same in the Edit & Display Components as well

 - [ ] Post fixing this, @mathew-alex to check Daily Rounds Created in Production. 
 - [ ] Add `OXYGEN_SUPPORT` as an option for Ventilator Parameters in `care_be`
 - [ ] Create a `care_be` migration to set existing Records with other Ventilator Parameters set to `Oxygen Support`
