### ISSUE TITLE
Removal of Buttons for Live dashboard on ohc.network

### ISSUE THREAD

**Issue by suprabathk** [coronasafe/care_fe#5255]
**The issue:**
There are links for Live Dashboard for Ernakulam on Landing page that is not active currently.

**To Reproduce**

1. Go to '[https://ohc.network/](https://ohc.network/)'
2. Click on '**Click for Live Dashboard**'

**Screenshots**
This is one of the links for live dashboard
<img width="960" alt="image" src="https://user-images.githubusercontent.com/34211797/230416495-0bb3b7f6-3cdf-42d7-83ae-07b8a1af1240.png">

What we get:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/34211797/230416702-12496c87-4584-4491-b071-0bac981ed402.png">

**Desktop:**
- OS: Windows 11
- Browser: Chrome
- Version: 112

**Comment by nihal467** [comment]
@aparnacoronasafe can you provide an insight about the expected behavior to be

**Comment by aparnacoronasafe** [comment]
redundant issue
