### ISSUE TITLE
Action data is not showing in the patient consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5272]
**Describe the bug**

When we select an action while creating a log update/ in consultation form, it is only shown in the patient list and not shown anywhere on the patient dashboard

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/aec039c8-d3e2-4691-a1b6-78b80d8530ed/patient/c278ebfa-5f30-4f9b-8f23-3acfd158f46c/consultation/53b241cb-e589-4d76-9fe5-796505cc4cf3
2. Create a log update with an action
3. come to patient dashboard

**Expected behavior**
The action tagged for the patient must be visible on the patient basic info card itself. 

Design how the action must look. It must be prominently visible on the basic info card on the patient dashboard. Once designed, discuss in EOD before finalising the design.

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/230612776-ca312688-319f-4210-b3b9-fb2220afc2a9.png)
![image](https://user-images.githubusercontent.com/57055998/230613076-cb2c6829-4fc5-42d0-800c-084cf15ad05d.png)

**Comment by aparnacoronasafe** [comment]
Please refer to #5271 also

**Comment by aeswibon** [comment]
![image](https://user-images.githubusercontent.com/77210185/231972070-d982a690-8da2-40a1-83af-73a61c1c2c50.png)

initial design for action and recommend discharge on patient consultation page.
cc: @nihal467 @aparnacoronasafe

**Comment by aeswibon** [comment]
@nihal467 I wasn't able to discuss the design in EOD call so I had posted the screenshot above as a comment. I was hoping you will check it and give me some suggestion then I will draft a PR fixing the issue

**Comment by nihal467** [comment]
@cp-Coder you are dedicating the whole one row, just to show the action badge, It doesn't look good, can you think of a better UI, since there are a lot of badges and multiple rows in the area now, think of a better UI and join in Monday's EOD call? We will discuss it there.
