### ISSUE TITLE
Center align Consultation Form

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5277]
**Describe the bug**

The consultation form is not horizontally centre aligned and looks slightly narrower than expected.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a patient
2. Submit to see create consultation form

**Expected behaviour**
- [ ] Should be center aligned as shown in screenshot
- [ ] Should look slightly wider

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/230649624-65f14a1e-8086-4b47-8eb7-3796212793f8.png)

**Comment by pranit-yawalkar** [comment]
@rithviknishad Please assign it to me.
