### ISSUE TITLE
ICD11 Diagnosis Field: Add required field's star or improve how we convey that anyone is mandatory

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5278]
**Describe the bug**
Currently, the consultation form does not convey that the Diagnosis and Provisional Diagnosis fields are mandatory input. However, anyone is mandatory and is noticed when we attempt to submit the form without filling any of them.

**To Reproduce**

1. Create a consultation
2. Do not fill diagnosis fields as it is not conveying it's required field and attempt to create consultation.
3. Validation error kicks in.

**Expected behavior**
Either or both:
- [ ] Add the required field's star for both and when one of them is filled remove the star for the other one.
- [ ] Change the placeholder "Select" of the dropdown to something that conveys that any one of them is required.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/230651905-40ca12a1-cf0a-4f74-b99c-48c2c6938720.png)

cc: @aparnacoronasafe @nihal467

**Comment by aparnacoronasafe** [comment]
I think what we could do is convert the prov and final diagnosis into a section
Section heading is "diagnosis" with an astrix to show that it is a mandatory field. 

Inside we could first have provisional diagnosis and diagnosis can be called "confirmed diagnosis"
