### ISSUE TITLE
Rename "Unknown" to "None" for Interface in Respiratory Support section view details of log update

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5279]
**Describe the bug**
When we select "None" in Respiratory Support when creating a critical care log update, it's shown as "Unknown" in the view details of the same log update instead.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a patient
2. Create a log update, choose round type as Critical Care
3. Select None in the Respiratory Support section, and Complete the Critical Care log update
4. Click view details on the recently created log update and scroll to the Respiratory Support section

**Expected behaviour**
Rename "Unknown" to "None"

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/230654830-c094fc38-8235-4c55-8124-97b97802ea44.png)

![image](https://user-images.githubusercontent.com/25143503/230654903-1579657b-3cf3-4371-ad05-c1dacd8f5402.png)

**Comment by jobayer12** [comment]
@rithviknishad Assign me

**Comment by jobayer12** [comment]
Can anyone give me some instructions? I tried but couldn't figure out where should I need change. The actual page I didn't found. If anyone gives me some suggestions it will help to solve this problem because I'm a newcomer to this project.

**Comment by rithviknishad** [comment]
@jobayer12 

Step 1: Create a log update
![image](https://user-images.githubusercontent.com/25143503/230758075-462e72bb-1a07-45e9-a863-1320c88eb721.png)

Step 2: Create a critical care log update
![image](https://user-images.githubusercontent.com/25143503/230758093-b6c2900c-62eb-4fdf-bce4-e08c5f8cce91.png)

Step 3: Open Respiratory Support
Step 4: Select None and Update the details
Step 5: Complete and select view details of the latest log update
![image](https://user-images.githubusercontent.com/25143503/230758147-36cf3620-f994-4b3a-89f7-a7732f1a11ff.png)

Notice the respiratory support interface attribute is Unknown instead of None.
https://care.coronasafe.in/facility/2bfdbbe6-0516-4269-9d17-860efd705ffb/patient/9db8dc7c-bd06-44fc-a6e0-7d7d148a1ac1/consultation/8eeb2ba4-41b2-4c20-8f4d-3f605b33d421/daily_rounds/c3fb70ce-92fa-4270-937d-4ca1f85b804c

![image](https://user-images.githubusercontent.com/25143503/230758179-5ee4422f-25dd-460f-b726-a1872cbf1d46.png)

**Comment by jobayer12** [comment]
@rithviknishad Thanks for your reply. I found this issue in my local environment when I start working on this ticket.
In the code, I can't figure out where should I need to change. I spend time understanding the project coding structure. I understood but can't figure it out the actual page where I need to rename "Unknown" to "None".
Thanks.

**Comment by rithviknishad** [comment]
@jobayer12 no worries. it might have been difficult to figure out since it was in a rescript file. i've pushed the fix https://github.com/coronasafe/care_fe/blob/develop/src/Components/CriticalCareRecording/types/CriticalCare__VentilatorParameters.res#L116

**Comment by jobayer12** [comment]
@rithviknishad Thanks. I thought the change will be in the Typescript/Javascript. That's why I was looking in TS/JS files. I saw this portion but didn't change it.

**Comment by rithviknishad** [comment]
@jobayer12 feel free to take up other issues 😄 
https://github.com/coronasafe/care_fe/contribute
