### ISSUE TITLE
Auto collapse the `DateFormField` after user clicks on a date

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5280]
**Describe the bug**
The `DateFormField` picker is not collapsing after the user clicks on a date. The user has to click somewhere else to make it collapse.

**To Reproduce**

1. Go to anywhere where the new `DateFormField` picker is present (maybe date range filters in the Advanced Filters of Patients section)
2. Click on a date

**Expected behavior**
When the user clicks on a date, the picker should collapse.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/230656496-a590dd7d-cbae-4eaf-b440-a1b9be6f8306.png)

**Comment by rahulnpadalkar** [comment]
@rithviknishad Can i work on this issue?

**Comment by rithviknishad** [comment]
sure @rahulnpadalkar 🚀

**Comment by k-deepak04** [comment]
Can i solve this issue?

**Comment by rithviknishad** [comment]
@k-deepak04 sure!

**Comment by ayushjnv1** [comment]
can you assign to me ?

**Comment by naksh2004** [comment]
Can I work on this issue?

**Comment by rithviknishad** [comment]
@naksh2004 feel free to make a PR and link this issue to it. 🚀

**Comment by rithviknishad** [comment]
If you are facing any difficulties figuring out, drop a comment

**Comment by nikhilagastya** [comment]
@rithviknishad  can i work on this issue ?

**Comment by rithviknishad** [comment]
sure, you may create a PR and link this issue to it.

**Comment by sachdevavaibhav** [comment]
@rithviknishad 
This can be solved using the close prop given by headless UI. Could you please assign me this issue?

**Comment by sachdevavaibhav** [comment]
@rithviknishad 
This can be fixed by using the close prop given by headless UI. Can I take up this issue?

**Comment by rithviknishad** [comment]
sure, you may create a PR and link this issue to it.

**Comment by rithviknishad** [comment]
Feel free to make PRs and link the corresponding issue to it.

**Comment by nikhilagastya** [comment]
hey @rithviknishad can you kindly review my PR and lmk if there are any changes.

https://github.com/coronasafe/care_fe/assets/72994295/6c6af58c-852a-4f65-9725-f76a083e3a62

**Comment by rithviknishad** [comment]
I've requested changes as it brings in additional problems.

**Comment by sachdevavaibhav** [comment]
@rithviknishad I have created a PR. Kindly review it.
