### ISSUE TITLE
Move Import/Export button to next line

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5284]
**Describe the bug**
The `Import/Export` button is overlapping with the heading on `External Results` page

**To Reproduce**

1. Go to https://care.coronasafe.in/external_results
2. See error

**Expected behavior**
The `Import/Export` button should be placed in next line just like it's on the Facility page
![image](https://user-images.githubusercontent.com/70687348/230715458-5b163212-9c61-4d21-ae36-9fdc2584a416.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/230715443-d652671b-7cb5-429c-81f5-6430cef72421.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbhishekPSingh07** [comment]
I Have Filed A PR for the same.Kindly Review It - #5288

**Comment by AbhishekPSingh07** [comment]
I Have added a PR for the same could you review it #5289

**Comment by rithviknishad** [comment]
@AbhishekPSingh07 link pull requests to issues using keywords. Learn more here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by manish-pamnani** [comment]
Hi @rithviknishad, let me know if the issue is still open.

**Comment by rithviknishad** [comment]
@pamnanaimanish169 this issue already has a PR (#5290) linked to it. 
Feel free to checkout other good first issues here: https://github.com/coronasafe/care_fe/contribute
