### ISSUE TITLE
Place buttons in new line in Search Facility Popup

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5287]
**Describe the bug**
The Cancel and Select button should be placed in new lines in mobile view

**To Reproduce**

1. Go to https://care.coronasafe.in/patients
2. Click on `Add patient details`
3. See error

**Expected behavior**
The buttons should be placed in a new line like this
![image](https://user-images.githubusercontent.com/70687348/230760246-0b1ad8e5-5e36-4c62-bca3-8cf6b66f6e5e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/230760235-a670a2a6-3e3c-41d6-a8bf-9728cbaca96e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbhishekPSingh07** [comment]
HIi @Pranshu1902 I Have Solved the Issue could you check my PR #5288
