### ISSUE TITLE
Consultation form- Referral outside CARE network

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5295]
**Is your feature request related to a problem? Please describe.**
We need a feature to note referring a patient to hospitals outside the CARE network. 

**Describe the solution you'd like**
In the Consultation form (https://care.coronasafe.in/facility/d02ef2cb-b5b2-4baf-bc9a-fac348893b00/patient/fddf2473-bc46-403d-b450-b569ce29d997/consultation) when "Decision after Consultation is selected as "Refer to another hospital", the field referred to facility appears with dropdown to select all hospitals in CARE Network.

- [ ] Add an option in the dropdown for "Others"
- [ ] When "Others" is selected, a short text field for "Name of the referred hospital" must appear for user to write the name of the hospital the patient is referred to.

**Describe alternatives you've considered**
Any better UX flow to achieve the above result is welcome.

**Comment by Ashesh3** [comment]
Possible duplicate of #4876 , that was resolved by allowing free flow text in the input itself if no hospitals matched the query.
@aparnacoronasafe can you confirm?

**Comment by rithviknishad** [comment]
@Ashesh3 maybe we should have separate input fields for it so that user is clear about this feature. (Although we could make use of the same backend field)

**Comment by Ashesh3** [comment]
> @Ashesh3 maybe we should have separate input fields for it so that user is clear about this feature. (Although we could make use of the same backend field)

That would be more intuitive correct. Though I remember discussing both options (with and without the addition input) with Gigin and deciding on the current implementation. Let's take it up for discussion again.

**Comment by rithviknishad** [comment]
Duplicate of #4876
