### ISSUE TITLE
Shifting Kanban- editing the process

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5302]
Simplifying the shifting flow to have the following steps: These steps will reflect as lists in the Shifting Kanban Board.

1) **Shifting approval pending:** List Only visible in "war-time configuration" #5300 
2) **Patients to be shifted**: All shifting requests in peacetime configuration will appear in this list. in war-time configuration only the shifting requests approved by the shifting approval facility will move from 'Shifting approval pending' into 'Patients to be shifted'
3) **Destination confirmed** All shifting requests where the destination is confirmed will appear here. Any staff from the origin facility/ destination facility can approve the destination
4) **Transport arranged**- any staff from the origin facility can mark this
5) **Patient in transit**- any staff from the origin facility can mark this
6) **Transfer complete**- Any staff from the destination facility can mark the shift as complete. Marking the shift as complete will automatically discharge the patient from the origin facility and move the card to the destination facility. At the origin facility, the discharge details will be auto-saved as a reason for discharge- referred, Date of discharge- present date. In case the destination hospital is one outside the CARE Network, the patient file gets discharged with the reason for discharge- referred, Date of discharge- present date. 
7) **Shift request canceled**- any staff from the origin facility can mark this
8) **Patient expired**- any staff from the origin facility can mark this. Redirect to Discharge from CARE pop-up window, with the reason for discharge "death" must come auto-populated and must not be editable. 

These steps must reflect in the lists in the shifting Kanban (https://care.coronasafe.in/shifting) as well as the Status dropdown in the update shifting request form (https://care.coronasafe.in/shifting/c10203c6-a382-4ffc-ab11-e416fb44c07e/update)

@gigincg to approve

**Comment by gigincg** [comment]
@aparnacoronasafe With all these changes, do you expect wartime approvals to work correctly too?

**Comment by aparnacoronasafe** [comment]
Yes. 

War- time will have only 2 difference from peace time configuration.

1) 1 additional feature of shifting approval authority (control room) approval. Keeping that as the first steps further simplifies the flow. In peace-time configuration, the flow will start from step two. 

2) the destination approval can be done in peace mode by anyone. In war mode, it needs to be restricted to staff from destination hospital or shifting approval authority. 

If we can have these two setting coded in such a way that is easily switchable, that would be ideal
