### ISSUE TITLE
Asset registration- Support tollfree No.

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5306]
In Asset page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/assets/c2e4edad-9c30-4a2f-9542-f29abef64306/update) 

the Customer support number is usually a toll free no.

The format of the number input field needs o be edited to 

- [ ] remove country code
- [ ] Allow 11-digit no. input such as "1800-425-2355"

**Comment by nihal467** [comment]
@Ashesh3 can you push a fix ASAP
