### ISSUE TITLE
Improving patient export

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5309]
The export feature for patient details in the Patient list (https://care.coronasafe.in/patients) needs to be improved with : 

- [x] Rename "Date of consultation" to "Date of first consultation"
- [x] Date of registration column has both date and time. separate that into two columns "Date of registration" and "time of registration"
- [x] Same for Date of discharge
- [x] Same for Date of consultation
- [x] Add a column for insurance policy ID/Policy name
- [x] Reorder the export columns in the following order:
- Patient ID
- Patient Name
- Facility Name
- Gender
- Age
- Insurance policy name/ID
- Date and time of registration
- Status during the consultation
- Date and time of first consultation
- Diagnosis and Provisional Diagnosis
- Decision after consultation
- Category
- Discharge reason
- Date and time of discharge

**Comment by rithviknishad** [comment]
@aparnacoronasafe regd. first one, renaming "Date of consultation" could you confirm if it's "Date of first consultation" or "Date of last consultation"? 

All the other details currently are of last consultation's.
