### ISSUE TITLE
Referred to another hospital: Consultation form

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5314]
When a consultation form is filed with "decision after consultation" as referred to another hospital, upon submitting the consultation form, redirect the user straight to discharge from care pop-up form with Reason for discharge auto-filled to "Referred"

**Comment by rithviknishad** [comment]
@aparnacoronasafe this behaviour is conflicting with the recently created issue #5296 where it's behaviour is to open of create shift request form. Could you confirm which behaviour is expected?

**Comment by nihal467** [comment]
@aparnacoronasafe we already achieved expected behavior in another issue, can you review and modify/close this issue

**Comment by aparnacoronasafe** [comment]
closing the issue as redundant
