### ISSUE TITLE
Page not responsive

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5331]
**Describe the bug**
The Linked Facilities page is going out of the screen in mobile view. The Left arrow button is not visible in mobile view/

**To Reproduce**

1. Go to https://care.coronasafe.in/users
2. Click on `Linked Facilities`
3. Open mobile view

**Expected behavior**
There should be padding around so that the button is always visible on the screen. For example on the `Linked Skills` popup, the button is visible in mobile view
![image](https://user-images.githubusercontent.com/70687348/231698375-cb25de6e-4be9-4a08-bfdd-9ee93d825b8f.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/231698312-03e4a472-e18a-4746-ba79-5cdb49d3e0f5.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbhishekPSingh07** [comment]
I have issued a PR for the Same #5344
