### ISSUE TITLE
Duplicate patient records present in CSV export if patient has multiple policies associated with them

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5332]
**Describe the bug**
If a patient has `N` policies associated to them, in the exported CSV file there are `N` duplicates of that patient each of them with all the different policies associated with them.

**To Reproduce**

1. Create a patient with two or more policies (policy name/id)
2. CSV Export patient list that includes this patient
3. Observe that particular patient id is present in multiple rows

**Expected behavior**
To be decided.
Maybe: One row per patient, multiple policies can be comma separated like how multiple diagnoses are.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/231942008-a91ddc61-6ade-4820-9b0a-55d4e7188154.png)

**Comment by nihal467** [comment]
- [ ] map out the preferred policy for the patient.
- [ ] map out the consultation policy

**Comment by rithviknishad** [comment]
@patelaryan7751 any updates on this?

**Comment by patelaryan7751** [comment]
yeah i would try give a PR by sunday @rithviknishad
