### ISSUE TITLE
Action in log update is malfunctioning

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5342]
**Describe the bug**
Action in log update is not the action set in consultation form

**To Reproduce**

1. Create a consultation with an action
2. Attempt to create a log update
3. Observe, the action selected in consultation form is not the action prefilled in log update form.

**Expected behavior**
- [ ] Make action optional field (allow null)
- [ ] Default should be null (not pending)
- [ ] Migrations for existing data from pending (NEED TO BE DISCUSSED)
- [ ] Pending should reflect in patients list

**Comment by nihal467** [comment]
- [ ] action field should be optional
- [ ] default should be a null
- [ ] pending should be having a reflection in the patient list
- [ ] migrate all existing data having pending action in the system to null

**Comment by rithviknishad** [comment]
Unassigning myself since I'll mostly not be available this week.
