### ISSUE TITLE
Log Availability of Devices Connected to the System

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5354]
**Issue Description:**
To better monitor and manage connected devices in the system, it is essential to log the availability status of these devices. This feature will help track device connectivity, identify potential issues, and improve system performance. Instead of implementing a dedicated UI for this feature, we will utilize an external dashboard using Metabase to visualize the data.

**Proposed Solution:**

- Implement a method to identify and log the status of connected devices.
- Periodically check the connectivity status of each device, and log any changes in their availability (e.g., online, offline, or intermittent connectivity).
- Design the data model for storing device availability logs in a way that is compatible with Metabase, ensuring that it can be used to build a comprehensive dashboard for monitoring and troubleshooting purposes.
- Implement notifications for critical device status changes, allowing prompt action to be taken when necessary.

Please feel free to share your thoughts or suggestions on improving this feature.

**Comment by nihal467** [comment]
@aparnacoronasafe currently, the asset uptime in deployed, is the issue this relevant

**Comment by rithviknishad** [comment]
Completed via #5879
