### ISSUE TITLE
Service Request: Assets

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5363]
**Is your feature request related to a problem? Please describe.**
Currently, only the last service Date and notes on the last service is captured in CARE in the Update Asset Form (https://care.coronasafe.in/facility/01810c32-ec26-494a-9e65-40e5547a7746/assets/00ea72f8-00e7-4827-b0dd-aa596481bde1/update) 

However, the data is not stored as a timeline. 

As the user enters details of say the 2nd service, information on the first service is lost.

**Describe the solution you'd like**

- [ ] In the asset details page, above "Transaction history", have a table for "Service History" that shows the historic data on the date of service and notes.

**Comment by aparnacoronasafe** [comment]
@Ashesh3 where are we with this? any ETD

**Comment by Ashesh3** [comment]
> @Ashesh3 where are we with this? any ETD

@aparnacoronasafe The feature is built and ready but is just pending to be merged. We recently had a major change to the backend and had paused any merges for a week. It should be ready to review and merge now.. @vigneshhari could you take a look into the linked backend PR so we can get this merged? 

https://github.com/coronasafe/care/pull/1277

**Comment by aparnaegov** [comment]
@vigneshhari can you review it soon?
