### ISSUE TITLE
Additional Role required; "Nurse"

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5365]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nihal467** [comment]
@aparnacoronasafe can you elaborate the issue

**Comment by rithviknishad** [comment]
Continued in: https://github.com/coronasafe/care_fe/issues/6240
