### ISSUE TITLE
Discharge tab in patient list view is not working properly

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5371]
**Describe the bug**

When we discharge a patient from a facility (name it A), the patient details will be available in the discharge tab of the patient list view. If the same patient gets admitted to some other hospital (name it B) later, for treatment, the patient card will disappear from the discharge tab of Facility A patient list view.

![image](https://user-images.githubusercontent.com/57055998/233851740-5724dfe0-8638-4f5b-8590-6e7f335514ff.png)

**Comment by nihal467** [comment]
@aparnacoronasafe the main intention for this issue, is that I am a staff of facility A, and when I check the discharge tab, I will see altogether discharged patient count to date, but when some already discharged patients get admitted to other facilities in the future for some other treatment and the card getting disappearing from facility A discharge tab of the patient list, will it be causing user trouble to actually know how much patients got discharge till date 

give me your opinion

**Comment by aparnacoronasafe** [comment]
This is already dealt with in #4678
