### ISSUE TITLE
district admin can't mark a Shifting Patient status as complete

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5373]
**Describe the bug**

Currently, an origin facility staff can only mark a shifting patient status to complete, if the destination hospital is a facility already registered in care and no other user type is having the access to do it (District admin and above)

Note: If we are sending a patient to a facility outside care, the bug won't happen to the district admin and above

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/233854801-5bb05ec8-55d0-42c5-bda0-66ab797f6c37.png)

**Comment by aparnacoronasafe** [comment]
This is a Bug. 

The preferred behavior is, 

1) WHEN DESTINATION hospital is in CARE 
Here the staff of the destination and origin facility must be able to complete a shift.

2) WHEN DESTINATION hospital is OUTSIDE CARE
the staff from the origin facility MUST be able to mark a shift as complete

The district admin and above should have access to do all the above.

Please make the necessary changes

**Comment by aparnacoronasafe** [comment]
@cp-Coder please note that I have changed the issue to have both user linked to of the destination and origin facility move shifting to complete for shifts with destination facility in CARE.

**Comment by aparnacoronasafe** [comment]
Issue overlapping with #5385 and #5389
