### ISSUE TITLE
Discharge is not created for patient moved to facility outside care

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5375]
**Describe the bug**

When we move a patient, outside the care facility, the discharge is not getting for the patient in the origin facility

note: We can update the status of patient as complete in the shifting board, but discharge is not getting created

**To Reproduce**

1. Complete a patient shifting flow this complete for outside care facility 
2. Click on patient tab
3. you can see the patient is still live in the origin facility

**Expected behavior**

When a patient is marked complete, he should be discharged from origin facility 

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/233855590-f0754772-cd76-43f3-b716-89b68595516d.png)

**Comment by aparnacoronasafe** [comment]
covered in #5389
