### ISSUE TITLE
Integrate medibase to care medication list

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5380]
**Feature Request**

We need to integrate medibase ( https://medibase.ohc.network/ ) with the care medication list. 

CC : @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
We need to Map medicines using the content.

Then we need to connect the medicine search field in prescription module with Medibase database.

The user must be able to not just search for medicine, but also type in a content in medicine and all medication with that content must come up in suggestion.

Eg: When user types in "Paracetamol" in search, dropdown must not only show the generic Paracetamol Tab etc, but also branded medicine like "Dolo 300mg", "Dolo 650mg" etc. (the main content of Dolo is paracetamol)

**Comment by shivankacker** [comment]
To anyone who assignes : The API is already present on medibase.ohc.network, along with its implementation. If you get CORS restrictions, do make a PR on the medibase repo.

**Comment by rithviknishad** [comment]
https://github.com/coronasafe/care_fe/pull/5458

**Comment by rithviknishad** [comment]
Fixed in #5851
