### ISSUE TITLE
Admins to have super powers in shifting

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5385]
**Describe the bug**
I am logged in as a district admin. I am unable to change status of a shifting request to "Destination approved". I see something went wrong notification

**To Reproduce**

1. Log in as a district admin. (I used ID: aparnaadmin, Password: Lilo@123)
2. Go to (https://care.coronasafe.in/shifting/cc6f6763-e178-4ff8-a11d-95032fbce78e/update)
3. Change status to detination approved
4. Submit form
5. See error notification with "Something went wrong"

**Expected behavior**
Allow district and state admins to update any status on shifting request

Part of #5393

**Comment by aeswibon** [comment]
Closing it as this issue has been fixed. Now, district admin and above is able to update the shifting status to complete
