### ISSUE TITLE
Shifting status- Complete- Bug

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5389]
**Expected behaviour**
When shifting status is updated to complete:

- [x] Any staff from the destination/origin facility or district/state admin can mark the shift as complete. 

- [x] Marking the shift as complete will automatically discharge the patient from the origin facility. At the origin facility, the discharge details will be auto-saved as a reason for discharge- referred, Date of discharge- present date. 

- [x] The shifting form must NOT be editable after a shift is marked as complete. The "Update status/details" button on shifting details (https://care.coronasafe.in/shifting/d350a891-0688-416f-8a50-a1c01a679c34) must be greyed out and when user tried clicking on it or hovers mouse on it, a message stating "A shifting request, once completed cannot be updated" must appear 

Part of #5393

**Comment by nihal467** [comment]
it is completed
