### ISSUE TITLE
Shifting request- clean up

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5390]
https://care.coronasafe.in/shifting/430b017a-f309-4fd9-972f-932fd58f1b86

- [x] Change "Origin Facility:" to "Current Facility"
- [x] Change "Contact person number:" to "Phone Number of Contact person at current Facility"
- [x] Hide "Karunya Arogya Suraksha Padhathi:" for peace-time shifts

DETAILS OF PATIENT
- [x] Remove SRF ID
- [x] Remove Date of test
- [x] Remove Contact with suspected carrier:
- [x] Remove Has SARI (Severe Acute Respiratory illness)?
- [x] Remove Domestic/international Travel (within last 28 days)
- [x] Remove Contact with confirmed carrier:

part of #5393

**Comment by aeswibon** [comment]
@aparnacoronasafe There are fields like `Number of chronic diseased dependents`, `Number of aged dependents`, `Estimated contact date`. Should these be removed too from the shifting details of the patient?

**Comment by aparnacoronasafe** [comment]
> @aparnacoronasafe There are fields like `Number of chronic diseased dependents`, `Number of aged dependents`, `Estimated contact date`. Should these be removed too from the shifting details of the patient?

@cp-Coder yes, please remove
