### ISSUE TITLE
Reconfiguring shifting steps

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5394]
In shifting Kanban board (https://care.coronasafe.in/shifting), and in shifting request form (https://care.coronasafe.in/shifting/d350a891-0688-416f-8a50-a1c01a679c34/update) reconfigure the list and status dropdown to have:

1) Shifting approval pending (only relevant in war-time)
2) Patients to be shifted
3) destination approved
4) Transportation arranged
5) Patient in transit
6) Completed
7) Cancelled
8) Patient expired

Part of #5393 

Cancelled is a new Stage for Shifting, creating the new stage can be handled as a separate feature/issue

**Comment by gigincg** [comment]
Cancelled is a new Stage for Shifting, creating the new stage can be handled as a separate feature/issue

cc: @aparnacoronasafe
