### ISSUE TITLE
Shifting approval pending- war-time shifting

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5397]
The step of shifting approval is only relevant to the war-time operation. 

- [x] The shifting request must show the field to link a " Shifting approval authority" only in war-time configuration and NOT otherwise

- [x] The first list in the kanban board " Shifting approval pending " must only be visible during war-time.

- [x] During wartime, any new shifting request must appear here. the default status for any new shifting request will be " Shifting approval pending "

- [x] Only a user linked to the shifting approval authority mentioned in the shifting request can change the status of the shifting request. 

Part of #5393

**Comment by nihal467** [comment]
@rithviknishad rename " Pending " to "Shifting Approval Pending"
