### ISSUE TITLE
"Transfer patient records"- shifting module

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5399]
Once the status of shifting request is changed to "Complete" and IF the destination facility is a hospital within CARE network,

- [ ] A button on the patient shifting card in the complete list of Kanban board (https://care.coronasafe.in/shifting) will allow user to "Transfer patient record"
- [ ] This button shall be visible only to users linked to the destination facility & district admin and above users
- [ ] This allows the user to automatically fetch patient records from the previous hospital to the destination facility at 1 click .
- [ ] Once the record is transferred, the button must appear greyed out as disabled.

If destination facility is a hospital outsode of CARE network, NO button for "Transfer patient record" will appear

#5393 

Note : 
![image](https://user-images.githubusercontent.com/57055998/235285641-680c9633-d2a3-402c-8ff3-c7183ed19c56.png)

this button is already present in the transfer in progress card, remove it and move it to complete card

**Comment by khavinshankar** [comment]
@aparnacoronasafe @nihal467 When a patient is admitted within care, aren't the previous consultations automatically available?

**Comment by nihal467** [comment]
@khavinshankar yeah, within care, previous consultation should be accessible from patient detail page ( function Already exist in the platform )

**Comment by gigincg** [comment]
@aparnacoronasafe This is a major change in the shifting flow, this can be taken up as a separate feature if required
