### ISSUE TITLE
Auto-cancelling shifting request

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5401]
Any shifting request is considered closed if such request is either in Completed, canceled or patient expired lists. a request in any other list is considered open. 

When a patient has an open shifting request, and in the meantime if the patient gets discharged from the current hospital and gets admitted, along with such admission, the following happens
- if the patient card is transferred to the destination hospital as marked in the shifting request, the shifting request automatically moves to completed
- If the patient gets admitted in any other hospital, shifting request moves to "Cancelled"

NOTE: note that the shifting status doesn't automatically change if the patient is discharged, but only upon the patient card coming live after such discharge

Part of #5393

**Comment by khavinshankar** [comment]
@GokulramGHV In this, there is another case, if the patient is discharged with EXP (expired) as the cause, move the shifting request automatically to patient expired.

cc: @aparnacoronasafe

**Comment by khavinshankar** [comment]
@GokulramGHV any updates on this

**Comment by gigincg** [comment]
@aparnacoronasafe This is a major feature request that involves creating automated movement of Shifting Requests.

If required, Please make a separate issue to block moving patients outside of the shifting request, if a shifting request is open.

**Comment by Shurtu-gal** [comment]
@gigincg Can I work upon this?

**Comment by bodhish** [comment]
Stale, lets consider if we get a request again.
