### ISSUE TITLE
Referred to facility- discharge form

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5407]
**Is your feature request related to a problem? Please describe.**
Currently, in discharge form, we capture when discharge is done for referral. 

But we dont capture to which hospital referral has happened. 

**Describe the solution you'd like**
https://care.coronasafe.in/facility/6dca552f-aba1-4ca5-afc1-a71744fc3d29/patient/4cdb4510-bfe5-4f41-b1d9-c0fdd27f77ad/consultation/f0dd3d31-b6db-4cc7-bc96-daa207e61a08

Add a field in the discharge pop-up right below "reason for discharge" when it is marked as referral,
Add field for referred to hospital. The field must be free text with suggest of hospital appearing as dropdown from CARE Network. However, the user must be able to input name of any hospital outside of CARE as well.

It must be a non-mandatory field, since sometimes, the doctors might simply ask patient to go to any highier center without specifying any one hospital. In those cases, he field may be left empty

**Comment by vissuresh** [comment]
There is already a field in the backend named `referred_to_external` , that issue has been closed.

**Comment by rithviknishad** [comment]
@vissuresh this is a front-end issue, there might have been some confusions.

**Comment by sindhuyamsani** [comment]
@rithviknishad Hey, Myself Sindhu and I'm interested in this. Can you assign me this issue?

**Comment by sindhuyamsani** [comment]
Hey @rithviknishad , Can you tell where the discharge form is, I can't find it in the 'Shifting' tab.

**Comment by patelaryan7751** [comment]
@sindhuyamsani 
Visit this link https://care.coronasafe.in/facility/eaab75f4-4f5c-4685-b769-bbfada64488e/patient/64de85fc-05f6-4e22-a80f-5413bf4d0d5c/consultation/cb398050-51db-4c6c-80c6-5ab2cb678cf9
Click on Discharge from care btn
![image](https://github.com/coronasafe/care_fe/assets/59426397/a05c956e-16e4-4d34-905c-d79eb3418bac)

**Comment by sindhuyamsani** [comment]
@patelaryan7751 Thank you

**Comment by sachdevavaibhav** [comment]
@rithviknishad If no one is working on it you can assign it to me.

**Comment by sachdevavaibhav** [comment]
@rithviknishad Is there any defined component for this issue already. We need a select menu with free text. Should I make modifications with `SelectMenuV2`?

**Comment by rithviknishad** [comment]
You won't need to make any modifications to the components. You can use `SelectFormField` instead of `SelectMenuV2`. Read the doc comments of each component or other usages to get a better understanding of how it is to be used.

**Comment by sachdevavaibhav** [comment]
okay
