### ISSUE TITLE
Not able to view all skills on users page

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5410]
**Describe the bug**
On clicking the open dropdown option of the add skill feature to a user, all skills aren't listed.

**To Reproduce**

1. Go to https://care.coronasafe.in/users
2. Click on `Linked Skills` of any user
3. Search `car` in the searchbox
4. Change the focus away from the box
5. Now open the dropdown, only skills containing "car" are visible.

**Expected behavior**
When the focus is shifted, the search box gets cleared but the text should still be there

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/234370228-823bdd84-37f7-44c0-9680-d6ae38e45681.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Prasang023** [comment]
Hey @Pranshu1902, I'm interested to work on this issue, can you assign this to me. Just for clarification, the text is needed to be present in the search box even when the focus is shifted - according to expected behaviour?

**Comment by Pranshu1902** [comment]
@Prasang023 Yes and when the written search text is removed, all available skills should be visible in the dropdown and not just the ones containing the search word.

**Comment by rithviknishad** [comment]
@Prasang023 any updates? Have you made a PR and linked this issue to it? I can see you've made a commit referencing this already

**Comment by Prasang023** [comment]
> @Prasang023 any updates? Have you made a PR and linked this issue to it? I can see you've made a commit referencing this already

my current commit doesn't provide the desired output completely, I still have to figure out few things to solve this issue, actually struggling with combobox a little. I'll will create the PR soon.

**Comment by rithviknishad** [comment]
Alright, feel free to let us know if you are facing difficulty figuring out something, or maybe you can use the care general slack channel.

**Comment by Prasang023** [comment]
Thanks, how can I join the slack channel?

**Comment by nihal467** [comment]
@Prasang023 https://bit.ly/join-openhealthcarenetwork , use this link to join our slack server

**Comment by kunal00000** [comment]
Is the issue solved as I see that dropdown is working as expected

**Comment by Pranshu1902** [comment]
> Is the issue solved as I see that dropdown is working as expected

Yup the issue has been resolved
