### ISSUE TITLE
 Not able to view all facilities on users page

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5412]
**Describe the bug**
On clicking the open dropdown option of the add skill feature to a user, all facilities aren't listed.

**To Reproduce**

1. Go to 
2. Click on `Linked Facilities` of any user
3. Search `ba` in the searchbox
4. Change the focus away from the box
5. Now open the dropdown, only facilities containing "ba" are visible.

**Expected behavior**
When the focus is shifted, the search box gets cleared but the text should still be there

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/234587395-c16e1162-0870-4ca1-adc1-0f1853b83762.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MayaSatishRao** [comment]
@khavinshankar @nihal467  @rithviknishad  I would like to work on this issue. Can you assign this issue to me?

**Comment by MayaSatishRao** [comment]
@khavinshankar I have created a PR. I did test it in the actual app as I do not have backend setup. For testing, I created a dummy React app and added ComboBox. I am attaching the screenshots:
1. When focus is in input:
![before](https://github.com/coronasafe/care_fe/assets/67920373/f72f054b-9ea2-422e-a93c-8e723edc87b5)
2. When focus is out of input:
![after](https://github.com/coronasafe/care_fe/assets/67920373/22cd0b71-2232-4bb5-b1eb-2ae5a499aaed)
Please do check if it is working fine

**Comment by rithviknishad** [comment]
@MayaSatishRao check review
