### ISSUE TITLE
Cant submit Resource Request

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#5440]
Resource Request generation is not working on all access levels.
 The "Submit" button is not responding.

**Comment by nihal467** [comment]
@cp-Coder I am unassigning you from this issue. I see that you have several backend and frontend pull requests still pending for review. Please follow up on those and get them merged before picking up new issues.

**Comment by aeswibon** [comment]
@nihal467 I have messaged Vignesh regarding the backend PRs and my frontend PRs  are waiting for the backend changes
