### ISSUE TITLE
Titles should be more highlighted 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#5441]
Some of the Titles should be more highlighted. eg: "Live"  and "Discharged" on Patient List, " Active" and "Archive" on the Shifting dashboard.

<img width="436" alt="image" src="https://user-images.githubusercontent.com/75214902/236209392-3784fc3f-831d-48fd-9639-b77921aa9c77.png">

"Live and Discharged" titles should be a little bigger if it's possible. Often new users won't be able to locate these titles.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/75214902/236210195-0ee94c46-5ca0-4ceb-9397-43a5d08f4903.png">

**Comment by nihal467** [comment]
Before starting to work on this issue, please create a mock-up and get it approved during the EOD call or through the Slack channel. Only then should you begin coding.

**Comment by nikhilagastya** [comment]
hey @nihal467 I would like to work on this issue !

**Comment by nihal467** [comment]
@nikhilagastya it is already taken up by @GokulramGHV , feel free to work on other issues

**Comment by rithviknishad** [comment]
@GokulramGHV any updates on this?

**Comment by GokulramGHV** [comment]
@rithviknishad I've completed working on the issue. I'll show the new UI in today's EOD and then make a PR once it's approved.
