### ISSUE TITLE
Device Preference: Temperature Unit

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5463]
**Is your feature request related to a problem? Please describe.**
Users may have different preferences for temperature units.

**Describe the solution you'd like**
Have a configurable temperature unit selector (maybe in the profile section, stored in localStorage). Upon updating this preference, the temperatures shown in various parts of care should be in this selected unit.

**Describe alternatives you've considered**
None

**Additional context**
Caught notice of this when the temperature readings from the physical vitals monitor from the camera was in degree C, but the temperature vitals monitor in care is shown in degree F.

**Comment by Deepanshu039** [comment]
Hi @rithviknishad I was looking at the issue and would like to work on this too. Can you please assign this to me.

**Comment by Deepanshu039** [comment]
also can we do it some other, just asking. I mean instead of using local storage.

**Comment by rithviknishad** [comment]
Can you explain how you are going to achieve it?

**Comment by Deepanshu039** [comment]
I was looking at the files and found that at most places we only need values of temperature, not graphs or any thing like that( ig there is only one place where we are plotting graph b/w temp and dates). So I was thinking maybe we can display both values at places where the temperature is mentioned such as: 25 °C/ 77 °F. Only if you find this approach good enough.

**Comment by Deepanshu039** [comment]
@rithviknishad you'll tell me what's your opinion about this way or is there anything I am missing with this approach?

**Comment by rithviknishad** [comment]
Okay, I was thinking of having this as a starting point of something like Device Preferences, where we could store not just Temperature Unit, but things like applied filters of Central Nursing Station (since a particular device might be associated to a particular location of CNS maybe), and so on.

**Comment by Deepanshu039** [comment]
Okay then I'll do it only in cache way.
Thanks for the clarification.

**Comment by Deepanshu039** [comment]
Hi @rithviknishad you'll just let me know your initial view on this...
![image](https://github.com/coronasafe/care_fe/assets/92849065/89a433fb-d77c-4f4b-85b2-823567a9e8d1)

**Comment by rithviknishad** [comment]
Yes! This looks nice.

You can make use of `SelectFormField` component (with `labelClass="hidden" errorClass="hidden") instead to keep designs consistent across the platform. 

`SelectFormField` also contains an `optionIcon` prop where you could maybe add degree symbol and C/F.

**Comment by Deepanshu039** [comment]
this is how it looks with SelectFormField
![image](https://github.com/coronasafe/care_fe/assets/92849065/ce417000-05fa-443b-bb1f-0f206fbdaa19)

**Comment by Deepanshu039** [comment]
also, @rithviknishad I wanted to ask how we can make one of our options as initially selected option instead of showing **Select** in the option field.
thankyou so much for you time and support.

**Comment by rithviknishad** [comment]
You could do:

```js
// utils.ts

function getTemperaturePreference() : "C" | "F" {
  return localStorage.getItem('temperature-preference') ?? "C";
}
```

and then in the component:

```jsx
<SelectFormField
  ...
  value={getTemperaturePreference()}
  onChange={({value}) => setTemperaturePreference(value)}
/>
```

**Comment by kunal00000** [comment]
Hey, is the task complete? If not, can I take it up.

**Comment by rithviknishad** [comment]
@Deepanshu039 any updates?

**Comment by Deepanshu039** [comment]
sorry last week my academics came I couldn't do much on the issue and I am still finding it hard to do any extra work other than that. Please if someone else is asking for it assign it to them.
Thank you so much @rithviknishad for your prompt replies and support really appreciate it : )

**Comment by kunal00000** [comment]
Hey Rithvik, added the component for temperature preference and stored temperature preference in local storage as discussed above. Let me know if this works.

**Comment by rithviknishad** [comment]
Reopening as the linked PR was reverted as it was causing websocket connections to disconnect only in patient consultation dashboard. Something is wrong with how we were merging last daily rounds vitals and it's temperature conversion.

**Comment by nihal467** [comment]
non-relevant to current develop
