### ISSUE TITLE
When the patient has no rhythm the card is fully empty

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#5468]
**Describe the bug**
When the patient has no rhythm the card is fully empty

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/dd001297-f509-4cdf-b1e8-7986ab5c7ced/consultation/1f8c13b9-aabb-4ae6-8662-5c6ff4b906bd/summary
2. Scroll down to Rythm Card
3. See the error

**Expected behavior**
There should be a message that no rhythm information is available.

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/59426397/1c52e7ab-3190-41c6-a47c-8084e3c2d94b)

**Comment by nikhilagastya** [comment]
hey @patelaryan7751 can you assign me this issue !

**Comment by nikhilagastya** [comment]
@patelaryan7751 can you assign me this issue

**Comment by nikhilagastya** [comment]
hey @patelaryan7751 where will I find the Rhythm component in the code base ?Can you mention the file name

**Comment by patelaryan7751** [comment]
Hey @nikhilagastya you can check out this file https://github.com/coronasafe/care_fe/blob/develop/src/Components/Facility/Consultations/PrimaryParametersPlot.tsx#L20
The rhythm card is present there.

**Comment by nikhilagastya** [comment]
thanks @patelaryan7751

**Comment by nikhilagastya** [comment]
![image](https://github.com/coronasafe/care_fe/assets/72994295/dd85f219-7b3d-4841-86eb-ad106a3db7e1)
hey @patelaryan7751 does this work ?

**Comment by rithviknishad** [comment]
Yes!

**Comment by nikhilagastya** [comment]
@rithviknishad can you review the PR
