### ISSUE TITLE
Asset cards in Asset list page is not a link. Unable to open in new tab.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5471]
**Describe the bug**
Asset cards in the asset list page can't be opened in a new tab as the component is not a link. However, cards in other list pages (such as patient list page) can be opened in a new tab as those are links.

**To Reproduce**

1. Go to Assets list page
2. Attempt to open asset in a new tab

**Expected behavior**

Should be able to open assets in a new page like in other list pages.
![image](https://github.com/coronasafe/care_fe/assets/25143503/0fc85138-b0b0-462e-a6ad-2213a11fac73)

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/25143503/f4134d66-893c-4dcd-b566-4e3da4d5ad7d)

**Desktop (please complete the following information):**

- OS: Ubuntu 23.04
- Browser: Chrome

**Comment by souravghosh01** [comment]
I want to work on this issue

**Comment by souravghosh01** [comment]
I would like to work on this issue

**Comment by souravghosh01** [comment]
Fixed! the issue. will create a PR shortly

**Comment by rithviknishad** [comment]
@souravghosh01 are you facing blockers creating a PR?
