### ISSUE TITLE
Need for "Discharge Reason Based" filter in Advanced Filters in the Patients Card

### ISSUE THREAD

**Issue by gayan-au** [coronasafe/care_fe#5474]
"Discharge Reason Based" Filter in Advanced filters adds up one more patient sorting filter which helps in easier way to get counts of Recovery, Referred, LAMA& Deaths.

**Comment by nihal467** [comment]
@gayan-au Does the requirement for the advanced filter solely involve retrieving the patient count, or are there any other additional uses associated with the filter?

**Comment by khavinshankar** [comment]
Hey @gayan-au, is the filter only for getting the count of patients or does it have any other uses? If it is only for the count, we could add a block or card in metabase (dashboard)

cc: @nihal467

**Comment by gayan-au** [comment]
@nihal467 @khavinshankar In Addition with the patient count, it helps to understand the information of patients who are discharged under that particular discharge reasons.
For instance if 10 patients are expired in given time period this filter helps the doctors or anyone  to understand what is reason involved for death by simply applying this filter instead of searching for only expired patients in whole discharged patients' list.

**Comment by Yash12Bansal** [comment]
@nihal467 @khavinshankar 
if this issue still persists then I would like to work on it

**Comment by Yash12Bansal** [comment]
also leave a detailed explanation of the issue and related files please

**Comment by akshatvermavi** [comment]
@khavinshankar  If Nobody is working then please assign it to me.
