### ISSUE TITLE
Change the "Break the chain" loader across the platform

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5478]
**Describe the bug**

We are still using the break-the-chain loader across the platform.

**Expected behavior**

We should be using a proper loader aligned to our current scenario

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/c9fd42d9-315b-4cd2-91f5-2a488b9e9760)

**Comment by nihal467** [comment]
@joelsajichacko can you give a insight on this issue

**Comment by joelsajichacko** [comment]
![qr140Fod7M](https://github.com/coronasafe/care_fe/assets/45791338/a627059e-e430-4973-86e5-92d85361c2d4)

I have found this on the internet. this is a gif file.. Please let me know whether this will work for care

**Comment by nihal467** [comment]
the CARE Logo will be fade-in and out while loading

**Comment by Bhavik-ag** [comment]
I'm interested in taking on this issue.

![Care Loading Final](https://github.com/coronasafe/care_fe/assets/73033511/a7ef5b91-4f7e-46e4-a149-f31b219c1562)

**Comment by rithviknishad** [comment]
Awesome!
