### ISSUE TITLE
Replace Coronasafe branding to OHC Network 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5479]
**Describe the bug**

In the log in place, replace all the coronasafe text and logo to OpenHealth Care Network

**To Reproduce**

1. Go to https://care.coronasafe.in/

**Expected behavior**

Replace all content with OpenHealth Care Network on the login page

**Screenshots**
[OHC_logo (1).zip](https://github.com/coronasafe/care_fe/files/11505694/OHC_logo.1.zip)

![image](https://github.com/coronasafe/care_fe/assets/57055998/28b93913-75bd-40e9-98b3-4777e58930b9)

**Comment by nikhilagastya** [comment]
Hey @siddnikh are u still working on this issue ? 
else I would like to work on it @nihal467

**Comment by siddnikh** [comment]
@nihal467 coronasafe branding is there in backend, emails, and some parts of the frontend as well. Do you suggest I create an issue for replacing of that too?
