### ISSUE TITLE
Bed Type in the location management and Facility Bed Capacity are not linked

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5482]
**Describe the bug**

The bed capacity card on the facility page and the bed type in the location management section of the facility page are not linked in any manner, which leads to 

- [ ] outdated information coming up on the facility page
- [ ] user need to update usage capacity manually while generating a report ( incase if its old data, it leads to incorrect information )

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/95588bd7-56ba-40a2-9350-dbe0b597414b
2. Click on location management button in the manage facility dropdown and add bed inside a location
3. once done come to the facility detail page
4. See the error

**Expected behavior**

To be discussed in the EOD

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/7d2c7a9b-218d-4e3d-9143-6ac74916ad2b)
![image](https://github.com/coronasafe/care_fe/assets/57055998/cd299698-4f97-4df9-bc21-4151ca131ba3)

**Comment by gigincg** [comment]
> This can only be done once all Types of beds are managed in the Bed Management in all Deployments
