### ISSUE TITLE
Add CSV support for the asset import/export

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5483]
**Describe the bug**

We don't support the CSV import/export of asset for a facility

**To Reproduce**

1. Go to https://care.coronasafe.in/assets?page=2&limit=18&search=
2. See error

**Expected behavior**

We should be able to use CSV to import and export bulk assets

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/5caa0502-0144-4e4c-a5cb-ae14bd615948)

**Comment by JahnabDutta** [comment]
Hey,
I was going through this and I found the error and applied a fix. I will make a PR for the same if that is fine?

**Comment by rithviknishad** [comment]
Sure!

**Comment by nihal467** [comment]
it is already solved in the platform ( #6262  ), so closing the related PR & issue
