### ISSUE TITLE
Consultation Form: Show bed type in the bed select drop-down

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5485]
**Is your feature request related to a problem? Please describe.**
The bed select dropdown in the create consultation form does not show what bed type a particular bed is.

![image](https://github.com/coronasafe/care_fe/assets/25143503/880db4c1-b289-475a-923d-e187704a13d0)

**Describe the solution you'd like**
A chip beside the bed name can be shown to show the bed type of that particular bed option.

**Comment by Bhavik-ag** [comment]
@rithviknishad I'm interested to work on this issue, can you assign this to me.

**Comment by knight-95** [comment]
I have identified the issue and am interesting in solving the same, kindly assign me the issue so I can start working on it

**Comment by rithviknishad** [comment]
@knight-95 this issue already has a PR linked to it. Kindly look into if it's already solved or not when picking up issues. Feel free to pick up other good first issues.
