### ISSUE TITLE
[C4GT] Cypress Tests for All Major Functionalities of CARE

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5491]
## Project Detail

CARE is a centralized capacity management and patient management system, central to the 10BedICU Project, integrating patients, doctors, hospitals, labs, specialized treatment centers, hospital administrators, and shifting control cells. Hospitals update crucial information about their assets, providing district administration with a comprehensive view of the healthcare system via smart dashboards. CARE digitizes patient records, streamlines workflows for pandemic management, and is deployed in remote areas, enabling TeleICU services for underserved citizens. It revolutionizes healthcare management, enhancing efficiency, accessibility, and patient outcomes.

## Features To Be Implemented

The goal of this project is to enhance the coverage of Cypress tests for the platform, ensuring comprehensive testing of all functionalities across the system.

## Learning Path

|  | Details |
| :---:  | :---:  |
| Complexity       | Medium |
| Required Skills | JavaScript, Cypress, React, TypeScript |
| Mentors            | @khavinshankar @rithviknishad @nihal467 @gigincg |
| Project Size      | 6 weeks |

## Product Set-up

To set up the project on a system, follow these guidelines:

- Install the required programming language and libraries, such as NodeJs and their respective data validation libraries.
- Fork the project
- Clone the forked project repository from GitHub.
- Set up the environment variables and configurations required to run the utility.

For more details, please refer to the readme file available at: https://github.com/coronasafe/care_fe
For more details on testing, please refer to our [manual testing template.](https://docs.google.com/spreadsheets/d/1OZCJ2L6ug3FyxxQyX5vEIlO79x3vPVM7Lhuno_Mob-s/edit#gid=1245996179)

## Acceptance Criteria

- All tests run and pass without timeouts or failures.
- Code is logically structured for long-term project sustainability.
- Proper descriptions should be included for review purposes.
- QA and Code Review

## Milestone

- Understand the workflow of CARE and enhance existing Cypress tests.
- Develop Cypress tests for all major functionalities.
- Increase test coverage based on real-time scenarios.
- QA and Code Review

**Comment by pramitsingh0** [comment]
Hi team,
I have went through your code base and already have various plans for the proposal. I have extensive experience with building django applications as well as working with react on the frontend.I have built various projects using the MERN as well as PERN stack, gaining experience with both SQL and NoSQL. I also have some level of experience with DevOps(linux, scripting, CI/CD, Deploying). 
I believe that my skill set will be of great use in this project. I will be asking you for the opportunity to work on this amazing project.
Best Regards,
Pramit Singh

**Comment by AdityyaX** [comment]
Hello there,
I have gone through the project and it seems really interesting and matches my skillset and experience too, Looking forward to submitting the proposal for this one!

**Comment by SaiRev0** [comment]
@nihal467   This project is interesting, and I m looking forward to contributing to this work in the C4GT 2023.

I have over 2 years of experience working with Technologies Like React for the frontend, nodejs, and Express for the backend. I'm a Full Stack Web developer and have worked with MERN stack. I have experience working in the open-source community and have contributed to numerous organisations. I have worked with Cypress in the past, so it will have a low learning curve, and I can start working on it.

So should I connect with the mentors or submit the proposal?

**Comment by nihal467** [comment]
@pramitsingh0 @AdityyaX @SaiRev0 Good to know you are interested in the CARE project. We are looking forward to seeing your proposals. We would recommend everyone to go through the platform's 'Good First Issue' to understand the workflow and product before submitting your proposals.

**Comment by SaiRev0** [comment]
> @pramitsingh0 @AdityyaX @SaiRev0 Good to know you are interested in the CARE project. We are looking forward to seeing your proposals. We would recommend everyone to go through the platform's 'Good First Issue' to understand the workflow and product before submitting your proposals.

Thanks a lot; I will work on some issues and understand the flow here.

**Comment by SaiRev0** [comment]
I tried to set up the repo on my local machine but got this error #5515 could you please help me out @nihal467

**Comment by harshikagoyal14** [comment]
Hello @nihal467 
The project seems pretty interesting to me, and I am looking forward to submit proposal for this project.

**Comment by Ayan-thecodeking** [comment]
Hello @nihal467 , I hope this message finds you well. I'm excited to express my keen interest in contributing to this project. After conducting a comprehensive review of the issue details, discussions, and codebase, I have found that my skills and experience align well with the project requirements. I have prior experience working with React.js, JavaScript, CSS, MySQL, and Docker. With my expertise in these technologies, I believe I can make valuable contributions to this project. I would greatly appreciate your guidance and support to ensure that I can deliver my best work. 🙌

**Comment by Mounika-Pavanthi** [comment]
I am eager to contribute to the CARE project and be a part of the team working towards revolutionizing healthcare management. With my proficiency in JavaScript, Cypress, React, and TypeScript, I am confident in my ability to enhance the coverage of Cypress tests and ensure comprehensive testing of all functionalities. I am dedicated to delivering high-quality code, adhering to best practices, and actively participating in QA and code reviews. Please consider my involvement in the CARE project as I am enthusiastic about improving healthcare accessibility and patient outcomes.
