### ISSUE TITLE
Browser autocomplete is blocking the view of AutocompleteFormField's dropdown.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5506]
**Describe the bug**
Browser autocomplete is blocking the view of AutocompleteFormField's dropdown.

**To Reproduce**

1. Open a bed select or any other autocomplete form field dropdown.

**Expected behavior**

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/25143503/b5a7676b-c551-454b-a5c0-88690e83b8c2)

**Comment by Deepanshu039** [comment]
Hi @rithviknishad I have submitted a [PR](https://github.com/coronasafe/care_fe/pull/5509) for this issue please do let me know if that'll be okay or if will I have to make some more changes.
thankyou so much for your time.

**Comment by rithviknishad** [comment]
Hey, it would be nice if you could link the issues in your PR using the closing keywords 😃 

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by Deepanshu039** [comment]
sure I ll definitely remember for the next time.
Thanks for the support.
