### ISSUE TITLE
npm run dev does not run, shows this error

### ISSUE THREAD

**Issue by SaiRev0** [coronasafe/care_fe#5515]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

I ran `npm install --legacy-peer-deps`
Then run `npm run dev`
It shows this error

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/96655163/24ea3ed4-b22f-4c49-8368-c4f28a14cf47)

**Desktop (please complete the following information):**

- Windows 11

**Additional context**
Using vs-code and GitBash Terminal

**Comment by rithviknishad** [comment]
I'm not sure if it's because your working directory path has spaces in it. I don't have a windows machine to test it. Could you retry in a working directory without spaces in the path?

@skks1212 any idea?

**Comment by shivankacker** [comment]
@SaiRev0 can you check if your project folder name contains spaces? If so, please remove the spaces and try again.

Reference: https://stackoverflow.com/a/73204282

**Comment by divyanshkhetan** [comment]
@rithviknishad I had the same issue, moving the repo to a directory with no spaces helped me solve it.

**Comment by MayaSatishRao** [comment]
@divyanshkhetan @rithviknishad  I have the  project in a directory whose name has no spaces. Still it is not working. Could you help?
![Screenshot 2023-05-25 172434](https://github.com/coronasafe/care_fe/assets/67920373/0315240b-e8db-445a-9338-1351cb0207d9)

**Comment by rithviknishad** [comment]
Did you run `npm install --legacy-peer-deps` before that?

**Comment by sainak** [comment]
@SaiRev0 @MayaSatishRao it's recommended to use a unix environment for developing care.
Can you try running the project in wsl.

**Comment by MayaSatishRao** [comment]
@rithviknishad I did. Do I need wsl as recommended by @sainak ?

**Comment by rithviknishad** [comment]
It's best if you could do it in WSL

**Comment by MayaSatishRao** [comment]
ok

**Comment by SaiRev0** [comment]
> @SaiRev0 @MayaSatishRao it's recommended to use a unix environment for developing care. Can you try running the project in wsl.

Thanks a lot for sharing, I m having a dual boot setup so I can directly work on Ubuntu

**Comment by MayaSatishRao** [comment]
I got the project running in my system and here is what I did:
1. run `npm cache clean --force`
2. Update the node version to 18.16.0 and npm version to 9.6.7(current latest ersions)
3. run `npm install --legacy-peer-deps`
4. run `npm run dev`

I updated the node version because I found this:[ https://github.com/vitejs/vite/issues/9113#issuecomment-1184319357](url)
