### ISSUE TITLE
Bed Type chip in Bed Select Dropdown is misaligned when a bed is selected

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5520]
**Describe the bug**
Bed Type chip in Bed Select Dropdown is misaligned when a bed is selected

**To Reproduce**

1. Attempt to switch bed / assign a bed to a patient consultation.

**Expected behavior**
The bed type chip may be aligned just after the bed name to avoid layout shifts when selecting/unselecting.

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/25143503/659e244a-fca2-400f-9e01-d878a7bcfdbe)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EshaBachuwar** [comment]
I am interested in working on this
