### ISSUE TITLE
Correct the CSV downloaded file name

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5524]
**Describe the bug**

Currently, it is 3:15 PM , indian time, i export a CSV file from care, the file is " capacities_2023-05-25T09_45_24.151Z " , in which the file name shows current date , but the time is not my local time.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility
2. Click on Export on the top right
3. Check the downloaded file name

**Expected behavior**

- [ ]  add a "_" between date and time in the file name, for example from this name " capacities_2023-05-25T09_45_24.151Z " it changes to "" capacities_2023-05-25_T09_45_24.151Z ""
- [ ] change the time mentioned in the file name to my local time

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/c3bcb7c7-a104-45ec-8689-a68abe650b12)

**Comment by MayaSatishRao** [comment]
I would like to work on this issue @nihal467 Can you assign this issue to me?

**Comment by MayaSatishRao** [comment]
@rithviknishad @nihal467 I am getting an error while running the app. When I run **npm run dev** , I am getting an error saying rescripts is not recognized as an internal or external command. If I run **npm run dev:react** , I am getting an error saying vite is not recognized as an internal or external command. I have checked and all the node modules are installed. How to resolve this issue?

**Comment by rithviknishad** [comment]
Refer: https://github.com/coronasafe/care_fe/issues/5515

**Comment by Prajuwal** [comment]
HI I have reproduced the behaviour at my end, let me know if I can work on it @rithviknishad

**Comment by rithviknishad** [comment]
@Prajuwal feel free to pick up other good first issues as this is already picked up 😄 
We have a mountain of good first issues available in the front-end

https://github.com/coronasafe/care_fe/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee

**Comment by MayaSatishRao** [comment]
@rithviknishad I need to change just 1 line of code and I know exactly where to change it. Can I submit a PR?

**Comment by rithviknishad** [comment]
Yes, i'll review it

**Comment by MayaSatishRao** [comment]
ok thanks

**Comment by Prajuwal** [comment]
sure @rithviknishad

**Comment by MayaSatishRao** [comment]
I have made a PR. Are the changes fine and working? @rithviknishad

**Comment by rithviknishad** [comment]
@MayaSatishRao I've reviewed it. All PRs will be tested by @nihal467

**Comment by MayaSatishRao** [comment]
ok
