### ISSUE TITLE
Staging API auth credential mentioned in readme not working 

### ISSUE THREAD

**Issue by sachdevavaibhav** [coronasafe/care_fe#5530]
**Describe the bug**
The following auth credentials mentioned in readme are not working:
 ```
- username: dev-staff
  password: Coronasafe@123
  role: Staff

- username: dev-doctor
  password: Coronasafe@123
  role: Doctor
```

I also noticed that username `devdoctor` is working instead of `dev-doctor` but, same is not the case with `dev-staff`.

**To Reproduce**

1. Go to '/'
2. Try to login with username `dev-doctor` and `dev-staff`
3. See error

**Expected behavior**
It should login with the respective role.

**Comment by sachdevavaibhav** [comment]
Can I take up this issue?

**Comment by rithviknishad** [comment]
@nihal467 ?

**Comment by nihal467** [comment]
@sachdevavaibhav @rithviknishad Someone might have deleted the user ID. I have updated it, so it should be working now.
