### ISSUE TITLE
Correct the occupancy details in facility card

### ISSUE THREAD

**Issue by Bhavik-ag** [coronasafe/care_fe#5533]
**Describe the bug**
The occupancy of the bed shown on the facility page for a facility card is currently shown equal to patient_count / bed_count.

**To Reproduce**

1. Go to facility tab

**Expected behavior**
Occupancy should be equal to no of occupied_bed_count / bed_count.

**Screenshots**
![2023-05-26_12-08](https://github.com/coronasafe/care_fe/assets/73033511/e832b341-c4eb-4dac-ae31-7f2d0fd12692)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rithviknishad** [comment]
Hey @Bhavik-ag this is not a bug and is expected behaviour. After discussions, it was decided to show live patients / total bed count. Not occupied beds / total beds.

cc: @nihal467 @aparnacoronasafe

**Comment by rithviknishad** [comment]
We could add a tooltip maybe saying: `Live Patients / Total beds`?

**Comment by Bhavik-ag** [comment]
Hey @rithviknishad Instead of one chip for occupancy, we can show two chips one for number of beds and one for live patients?

**Comment by rithviknishad** [comment]
We tweaked and tried lots of designs during the calls. 😅 
We could discuss this, can you share this in our Slack channel in care general so that we can get everyone's suggestions?

**Comment by nihal467** [comment]
@Bhavik-ag Can you add a tooltip for that chip? It would be helpful if you could complete it by 5:00 p.m. this evening since tonight is our weekly production release.

**Comment by Bhavik-ag** [comment]
Ya sure!! @nihal467 Working on this
