### ISSUE TITLE
Update consultation created notification for non admission decisions

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5536]
**Describe the bug**
Currently, if a decision after consultation is any option other than admission, the patient is discharged. However, the notification says Consultation was created successfully.

**To Reproduce**

1. Create a consultation with decision after consultation as any option other than admission.

**Expected behavior**
The notification should say the patient discharged successfully.

**Comment by MayaSatishRao** [comment]
@rithviknishad Can you assign this issue? I want to work on this

**Comment by MayaSatishRao** [comment]
I have made pr @rithviknishad I have tested it as well. Please review it once. Thanks!
