### ISSUE TITLE
Make buttons width consistent in mobile view of file section in patient consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5540]
**Describe the bug**

In the file tab of patient consultation page, all the buttons are not in full width during responsive view

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/2f4ec032-6748-49f7-b637-f40d2351a9ce/patient/78aad99e-cb65-4756-9ec0-74a1282280c4/consultation/c7f49a18-af4a-4258-b927-a8a420d42342/files
2. See error

**Expected behavior**

in the mobile responsive view, the buttons in the file tab should be on constant full width

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/3a9eacb5-8ab9-43ed-9128-56a8315f9e02)

**Comment by lord2anil** [comment]
Can you assign this issue to me? I want to work on this.

**Comment by abhishekchauhan15** [comment]
I can fix this, should I go on? @nihal467

**Comment by lord2anil** [comment]
I am working on this

**Comment by abhishekchauhan15** [comment]
ok sure, go ahead

**Comment by Rohanxmalik** [comment]
Is it fixed yet @lord2anil . If not I want to contribute to it under C4GT

**Comment by lord2anil** [comment]
ok,go ahead

**Comment by Rohanxmalik** [comment]
Sure @lord2anil , Please assign it to me @nihal467

**Comment by akshatvermavi** [comment]
There is no any progress in this week so its my please assign it to me @nihal467
