### ISSUE TITLE
Bed select dialog width feels too small

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5557]
**Describe the bug**
Increase bed select dialog's width.

**To Reproduce**

1. Go to a patients dashboard
2. Attempt to switch beds

**Expected behavior**
The width of the bed select dialog should be larger

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/25143503/bb05ea2a-013b-4840-a7d0-1b687d4f10c2)

**Comment by satyam0601** [comment]
Hey! i would like to work on this issue
