### ISSUE TITLE
Make buttons full width in mobile view on samples page

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5575]
**Describe the bug**
The `Choose File`, `Open Camera`, and `Upload` button are not full width in mobile view. It looks inconsistent in mobile view.

**To Reproduce**

1. Go to https://care.coronasafe.in/sample/dd4b47c7-818d-4700-a7b4-28de77200ef6
3. Scroll down to `Upload New File` section

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/70687348/868d92fd-a501-49df-8b1e-30c3be0189c8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by patelaryan7751** [comment]
hey @Pranshu1902 #5540 would solve the problem altogether as there is only a single file upload component in both the pages
