### ISSUE TITLE
Minor bug in UI of Facility Card

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#5577]
**Describe the bug**
Minor bug in UI of Facility Card there is no space between the KASP and View CNS button

**To Reproduce**

1. Go to https://care.coronasafe.in/facility?page=2
2. See error

**Expected behavior**
There should be space between the KASP and View CNS button

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/59426397/f31560d6-e4b9-4a55-b30f-3afa0a34ef99)

**Comment by satyam0601** [comment]
i feel its an easy fix can you assign this to me?

**Comment by perminder-17** [comment]
Assign me i will fix it my tommorow.
