### ISSUE TITLE
Control buttons are overlapping in Camera feed

### ISSUE THREAD

**Issue by suprabathk** [coronasafe/care_fe#5595]
**Describe the bug**
Control button are overlapping in Camera feed
All the buttons are placed in the bottom right corner, making the buttons overlap.

**To Reproduce**

1. Go to 'Facitilities'
2. Click on 'View CNS for a facility'
3. Click on a patient.
4. Click on "Camera feed"
7. See error

<img width="960" alt="image" src="https://github.com/coronasafe/care_fe/assets/34211797/33bb35af-53a9-4946-8dd8-0d5a3f9bf4be">

**Expected behavior**
The Arrow controls can be moved to left.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome

**Comment by perminder-17** [comment]
//assign
i am working in this issue

**Comment by rithviknishad** [comment]
@perminder-17 a PR is already present that fixes this issue as you can clearly see above.
