### ISSUE TITLE
key Warnings in .map methods

### ISSUE THREAD

**Issue by mecskyverse** [coronasafe/care_fe#5600]
**Describe the bug**
Currently, when visiting the Dashboard there is a warning named as 
"Each child in a list should have a unique key prop"
This Warning is coming in two methods ExportMenu and HospitalList

**To Reproduce**

1. Go to DashBoard Page
2. Open the Console 
3. See warning

**Expected behavior**
There Should be no warning while visiting the page 

**Screenshots**
![Screenshot 2023-06-05 123731](https://github.com/coronasafe/care_fe/assets/91150257/3a32c23b-c880-42ff-aec8-19fba36faa95)
![Screenshot 2023-06-05 123723](https://github.com/coronasafe/care_fe/assets/91150257/5a54a13f-f0a2-447b-89e1-1b450188a1a0)

**Comment by mustafaazad03** [comment]
Hi @mecskyverse,
Can I help in this issue ??
