### ISSUE TITLE
Discharge Summary preview not working in Firefox

### ISSUE THREAD

**Issue by Yash12Bansal** [coronasafe/care_fe#5611]
**Discharge Summary button under the patient's tab does not work properly in the Firefox web browser. It should show the PDF preview that will be generated after downloading the discharge summary. **

**To Reproduce**

1. Go to 'patients tab' after login in
2. Scroll down to patients list
3. Click on any patient
4. Then the details page will be opened
5. Click on "discharge summary" button 
6. This does not show PDF preview in firefox

**Expected behavior**
After the user clicks the "Discharge Summary " button then the PDF preview should be shown.

Issue faced on-
- Browser [Firefox] Latest Version

**Comment by Yash12Bansal** [comment]
I am working on this issue

**Comment by rithviknishad** [comment]
@Yash12Bansal kindly fill in the issue comment clearly so that someone would understand when they test or look back into this at a later point in time.

**Comment by Yash12Bansal** [comment]
I had made the changes but forgot to make a pr as I was working on other issues. So, sorry for that delay
I have made all the changes and it now supports all major browsers. I have also untracked package-lock.json files
So please review and accept the pr
@rithviknishad
https://github.com/coronasafe/care_fe/pull/5682
