### ISSUE TITLE
No wrapping of text patient note

### ISSUE THREAD

**Issue by kunal00000** [coronasafe/care_fe#5633]
**Describe the bug**

**To Reproduce**

1. Go to Patient
2. Click on any patient that has doctor notes
3. Add a 150 character string 
4. See that text overflows the card.

**Expected behavior**
-> Text should wrap in the card

**Screenshots**
<img width="1186" alt="Screenshot 2023-06-09 at 1 30 46 PM" src="https://github.com/coronasafe/care_fe/assets/92316166/f9d46494-17b1-4385-8ff1-07c63525d2e2">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] - MacOS
- Browser [e.g. chrome, safari] - Brave

**Smartphone (please complete the following information):**

**Additional context**
While working on proposal for C4GT, I observed this problem.

**Comment by rithviknishad** [comment]
@kunal00000 are you working on this or free for others to take it up?

**Comment by kunal00000** [comment]
Open for others. If nobody takes it up in a day or two, I'll raise a PR.

**Comment by sachdevavaibhav** [comment]
@rithviknishad I can work on it.

**Comment by kunal00000** [comment]
Sure, Go ahead.

**Comment by mustafaazad03** [comment]
Hello, 
I want to work on this issue.

**Comment by mustafaazad03** [comment]
Hi @rithviknishad , @kunal00000 ,
Please review my pull request as I have resolved this issue and if there any changes please suggest.

**Comment by sachdevavaibhav** [comment]
@Mustafa-Azad025 Its great that you have created a PR. But before working on the PR make sure the maintainers have assigned you the task and if you think someone else is also working on the same issue at least ask/tell them prior to creating a PR. This way we can contribute to the project and maintain a healthy environment.

Open source is about collaboration and not about competition.

**Comment by mustafaazad03** [comment]
I am really sorry for this, I think that this issue is open to all as there is no one assigned .
