### ISSUE TITLE
In the Sample Report "Coronasafe" should be renamed to "OHC"

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#5646]
**Describe the bug**
In the Sample Report "Coronasafe" should be renamed to "OHC"

**To Reproduce**

1. Go to https://care.coronasafe.in/patient/f71b8d9e-b902-4388-9afd-355ccff0e979/test_sample/fea2e04e-31a9-4d53-bbba-164cff6e2538/icmr_sample
2. See error

**Expected behavior**
In the Sample Report "Coronasafe" should be renamed to "OHC"

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/59426397/64aaef18-5341-4ef6-9339-a620b09d8b2f)

**Comment by mustafaazad03** [comment]
Hi @patelaryan7751 ,
I want to contribute .

**Comment by mustafaazad03** [comment]
Hi @patelaryan7751 ,
Just for conformation, 
![image](https://github.com/coronasafe/care_fe/assets/97380192/017e08ca-ecd7-480f-b00c-cc79eec1faed)

is this coronasafe I want to renamed ??

**Comment by rithviknishad** [comment]
Hey @Mustafa-Azad025 @patelaryan7751 

As part of replacing Material UI to custom components, the Sample Preview page will almost be fully rewritten very soon this week and your PR may be rendered obsolete. Feel free to take up other issues!

cc: @khavinshankar

**Comment by mustafaazad03** [comment]
Ok, No problem.
Can you suggest any issue in frontend or backend!?

**Comment by rithviknishad** [comment]
You can work on this, looks like the replace to MUI pr didn't convert it.

**Comment by khavinshankar** [comment]
This issue has been resolved
