### ISSUE TITLE
Make the error message consistent in forgot password section

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5683]
**Describe the bug**

the error message in the forgot password page is not consistent

**To Reproduce**

1. Go to https://care.coronasafe.in/
2. Click on forgot password
3. click the send reset link button

**Expected behavior**

the error message should be consistent with the login page

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/68a5e959-750a-4828-989e-e27731bf7e7b)

**Comment by Yash12Bansal** [comment]
@nihal467 
I would like to take this issue. Will you please assign it to me ?

**Comment by nihal467** [comment]
@Yash12Bansal the issue is already taken up @Ashesh3
