### ISSUE TITLE
make the error message consistent in facility config page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5689]
**Describe the bug**

In the facility config page, when we submit only the error pop-up, it is not having the consistent error message

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/5d1ec6df-76d9-412e-bea5-7ad8df37e434/middleware/update
2. Click on update button with empty field
3. See error

**Expected behavior**

it should be giving a consistent error like other pages

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/b1815186-03f0-4251-b2de-46945a74ddcd)

**Comment by kunal00000** [comment]
Can I take up this issue
