### ISSUE TITLE
Make all four field in Facility Inventory Addition Form Mandatory

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5690]
**Describe the bug**

Currently, we can submit the form, even without mentioning the quantity, so there will be a blank entry coming into the facility inventory management system

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/ce8e3a9b-ac87-416b-bfc9-ab88af0d7eaf/inventory/add
2. submit the form without filling quantity 
3. See error

**Expected behavior**

Make all the four field as mandatory, add " * " and add a consistent field validation too similar to other forms

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/6a90d7ff-5e42-4f2b-b1ad-257fe49b1c42)

**Comment by rithviknishad** [comment]
probable conflict with https://github.com/coronasafe/care_fe/pull/5623

cc: @Ashesh3
