### ISSUE TITLE
Not all the units are available in minimum quantity page of facility inventory

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5691]
**Describe the bug**

When we try to set a minimum quantity for an item on the inventory management page, the unit option we get on the inventory creation page and the inventory minimum quantity page are not the same. On the inventory creation page, we get multiple unit selections and on the minimum quantity page, we don't have the dropdown option in the unit field.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/ce8e3a9b-ac87-416b-bfc9-ab88af0d7eaf/inventory/min_quantity/set and check the unit field
2. Go to https://care.coronasafe.in/facility/ce8e3a9b-ac87-416b-bfc9-ab88af0d7eaf/inventory/add and check the unit field
3. See error

**Expected behavior**

- [x] make available all units available in the inventory creation page for the inventory minimum quantity too.
- [x] add field validation in the page mandatory and add " * " symbol to the fields

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/4e634bdd-507f-454f-bf94-42afb7e628cb)

**Comment by kunal00000** [comment]
Can I take up this issue
