### ISSUE TITLE
Modify the resource request page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5692]
**Describe the bug**

" Is this an emergency? " field in the resource create the page, is taking an entire row.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/5d1ec6df-76d9-412e-bea5-7ad8df37e434/resource/new
2. See error

**Expected behavior**

- [ ] move the " Is this an emergency? " field, into the same raw as the Name of Approving Facility field
- [ ] add " * " to the Request Title field

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/b90a32e4-06dd-448d-b78f-a1503b520fb8)

**Comment by kunal00000** [comment]
Can I take up this issue

**Comment by mustafaazad03** [comment]
Can I take this issue ??  @nihal467 and @kunal00000

**Comment by rithviknishad** [comment]
@kunal00000 @Mustafa-Azad025 nope, avoid asking for assigning if it's already assigned to someone. (Unless it doesn't have a PR for more than a week)

This issue is closely related to an existing PR, so I will be pushing directly to that branch to prevent conflicts.

**Comment by mustafaazad03** [comment]
ok, so sorry for this

**Comment by rithviknishad** [comment]
np 😄 feel free to take up other issues

**Comment by rithviknishad** [comment]
https://github.com/coronasafe/care_fe/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee

**Comment by kunal00000** [comment]
> This issue is closely related to an existing PR, so I will be pushing directly to that branch to prevent conflicts.

Oh ok, I thought you were assigned automatically by workflows and you wouldn't be working on these small tasks.
Would keep this in from now on 👍.

**Comment by rithviknishad** [comment]
Nope 😅 we don't have such workflows. I voluntarily took it up to prevent conflicts with the tailwinding prs
