### ISSUE TITLE
Add space between text box and button in the resource detail page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5693]
**Describe the bug**

the text box and button is so close to each other in the resource detail page

**To Reproduce**

1. Go to https://care.coronasafe.in/resource/e0896372-9f4b-454d-9371-e036fcc447df
2. See error

**Expected behavior**

Add space between the text box and the comment button

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/d28cd71e-1797-4ccc-800b-52b732373e6a)

**Comment by mustafaazad03** [comment]
Can I take this issue ?? @nihal467 and @rithviknishad

**Comment by rithviknishad** [comment]
@Mustafa-Azad025 I think its visible that it's already assigned right? 
Also, refrain from taking up multiple issues at once when you haven't made PRs for others yet.

**Comment by rithviknishad** [comment]
Also, this is related with a PR that I've already made so will be pushing a fix to that branch directly.

**Comment by mustafaazad03** [comment]
Ok 👍🏻
