### ISSUE TITLE
Add: Search box to filter data in resource board

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5695]
**Is your feature request related to a problem? Please describe.**

Currently, we are not able to search for a resource request in the board

**Describe the solution you'd like**

Add a search box to the filter the data in resource board similar to the shifting board

**Additional context**

![image](https://github.com/coronasafe/care_fe/assets/57055998/8461be42-171b-4448-9111-74f9ed804e25)
![image](https://github.com/coronasafe/care_fe/assets/57055998/b409455c-f6ea-4460-9b0a-b918332fce05)

**Comment by mustafaazad03** [comment]
Can I take this issue ?? @nihal467

**Comment by mustafaazad03** [comment]
Hi @rithviknishad, @nihal467,
I have added the search bar in resource section, will it be ok if I add functionality as well !?
![image](https://github.com/coronasafe/care_fe/assets/97380192/f0d8c678-0f6f-49fd-bac3-8851d5df6b4b)

**Comment by rithviknishad** [comment]
Yes! Without it being functional there's no way the PR would get merged 😄

**Comment by mustafaazad03** [comment]
can you guide me how I add this functionality ??

**Comment by mustafaazad03** [comment]
Hi, 
I tried 2-3 ways to get desired output on search but I didn't get all the column data . can you give some insights to make search work properly !?
I am also trying and let you know soon if I got desired result.

**Comment by rithviknishad** [comment]
See how searches work in other places. You might need to make backend changes too for this.

**Comment by mustafaazad03** [comment]
Yes, I am doing backend changes .

**Comment by khavinshankar** [comment]
@mustafaazad03 any progress on this issue?

**Comment by mustafaazad03** [comment]
Yes, I have build full frontend but not able to make the functionality.
Can I raised the PR for frontend !?

**Comment by nihal467** [comment]
@mustafaazad03 what is the status on this PR

**Comment by mustafaazad03** [comment]
Hi @nihal467 ,
I am just able to make a UI, I tried to add the functionality but I don't know why is it not working.
If anyone guides me for this, I will make PR today.

**Comment by rithviknishad** [comment]
@nihal467 is this issue still relevant? Users can always narrow down the search using the filters (created date, origin/approving/assigned facility). If not shall we move this to wishlist?

**Comment by vivramkrishna** [comment]
@Ashesh3 can you please assign me
