### ISSUE TITLE
Misaligned Pain scale pop-up in the critical care

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5703]
**Describe the bug**

the pain scale pop-up in the critical care (vital section) are off aligned

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/5d1ec6df-76d9-412e-bea5-7ad8df37e434/patient/c6987e7e-c22c-4d6b-95fc-2af1fc95bacc/consultation/b93cde7d-e922-48eb-94c3-a7578228b25d/daily_rounds/fc4a6179-e2c2-4ac3-95ff-21f4095c4d77/update
2. Click on vital
3. Scroll down to pain scale and click any part

**Expected behavior**

make the alignment of the pain scale, value box and text box proper

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/f8c4d7ea-d355-4d15-8954-37de4797fe08)

**Comment by akshatvermavi** [comment]
@nihal467 I want to work on the above issue and the link you provided are asking for login and I don't have any account so that I can see the UI So is it possible to look the UI or need to create the account via superusers
