### ISSUE TITLE
Signup option must be present in Login page

### ISSUE THREAD

**Issue by akshatvermavi** [coronasafe/care_fe#5710]
**Is your feature request related to a problem? Please describe.**
Yes if user is new one user want to Login in Login page there must be some signup button so that it can directly directed to the Signup page 

**Describe the solution you'd like**
I want to design a Signup button in the login page just behind the login button and directed to Signup page if it designed if not then I will design in same type of UI using Figma.

**Describe alternatives you've considered**
The IU of Signup page can be design using the Same Login page 

**Additional context**
If any one want to suggest me to optimize the problem then tag me
![Screenshot (139)](https://github.com/coronasafe/care_fe/assets/99114167/5ab7bab4-390d-4ff3-8731-e8338df4d82d)

**Comment by akshatvermavi** [comment]
@rithviknishad Please look this issue, If it is genuine then please allow me to work on it

**Comment by rithviknishad** [comment]
Sign up is not allowed. 

Superusers can create accounts for state admins and/or district admins. 

These users can create other type of accounts under the same state or district which that user belongs to.

**Comment by akshatvermavi** [comment]
Ok Sir thankyou for sharing such valuable information to me @rithviknishad
