### ISSUE TITLE
Bed Capacity & Doctor Capacity preview is not working

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5741]
**Describe the bug**

During creating a new facility, the bed capacity & Doctor Capacity preview in not working

**To Reproduce**

similar steps to doctor capacity too
1. Go to https://care.coronasafe.in/facility/create
2. Create bed capacity 
3. Click on save and add more button 

**Expected behavior**

The added data preview should be available in the bottom of the page

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/34a4bd66-5190-4d29-8940-fbb6d2d02692)
![image](https://github.com/coronasafe/care_fe/assets/57055998/cc27237e-c29d-4f18-a368-b0e73f050c59)

**Comment by rithviknishad** [comment]
<img width="1592" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/d36fd2ac-b107-4fcd-bf11-ffbe5b657e25">

@nihal467 unable to reporoduce

**Comment by rithviknishad** [comment]
@nihal467 unable to reproduce

<img width="1521" alt="Screenshot 2023-06-22 at 11 10 08 AM" src="https://github.com/coronasafe/care_fe/assets/25143503/b47b6474-52e1-4e77-8d79-ea850002d262">
