### ISSUE TITLE
Unable to input landline number in patient registration form

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5776]
**Describe the bug**
Unable to input landline number in patient registration form

**To Reproduce**

1. Go to the patient registration form
2. Add a landline number to the primary number

**Expected behavior**
The landline number should be accepted

**Comment by siddnikh** [comment]
Do you think adding another field for Landline number should be done? I think phone number is available with people there nowadays. We can make the landline field non-mandatory, too.

**Comment by siddnikh** [comment]
Seems like we're getting a validation error from the backend. I've made a [backend](https://github.com/coronasafe/care/issues/1405) issue for this.
