### ISSUE TITLE
Cypress Test for All Major Functionalities of CARE

### ISSUE THREAD

**Issue by ShivamJhaa** [coronasafe/care_fe#5834]
## Primary Objective of this EPIC

* Adding cypress test for all the major functionalities of CARE

## Tasks

- [x] #5835 
- [x] #5865 
- [x] #6108 
- [ ] Add test for [sample_test.cy.ts](https://github.com/coronasafe/care_fe/blob/develop/cypress/e2e/sample_test_spec/sample_test.cy.ts)
- [x] #6109

**Comment by nihal467** [comment]
closing this, as new detailed module-wise issues will be created
