### ISSUE TITLE
Gmaps not working in care.ohc.network

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#5842]
<img width="1463" alt="image" src="https://github.com/coronasafe/care_fe/assets/29787772/8a97db0b-2da1-4eec-90b1-cde03392ff86">

In facility create page, google maps are not working in our new domain (care.ohc.network), It is working in care.coronasafe.in

@mathew-alex  can you add the required permissions. 

cc: @nihal467

**Comment by mathew-alex** [comment]
added permission. issue resolved.
