### ISSUE TITLE
Phone number filter in the user tab is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5846]
**Describe the bug**

When we enter 10 digits in the phone number filter in the user tab, the filter is not working properly. when we enter the number with the country code (+91), the filter is working properly 

**To Reproduce**

1. Go to https://care.coronasafe.in/users?page=1&limit=18&first_name=&last_name=&phone_number=&alt_phone_number=&user_type=&district_id=
2. Click on advanced filter and enter 10 digit in the phone number field
3. See error

**Expected behavior**

When we enter a 10 digit phone number and apply filter, it should work properly

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/5ff29ac9-e678-4ba4-b080-4c015bcabcf3)

**Comment by rithviknishad** [comment]
@nihal467 have you tested this: https://github.com/coronasafe/care_fe/pull/5789
