### ISSUE TITLE
Ward for patients to be non-mandatory

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5858]
**Is your feature request related to a problem? Please describe.**
Most patients coming to the hospitals dont know the ward they belong to. 

**Describe the solution you'd like**
Make "ward" field in the patient registration form Non-Mandatory

@gigincg Please add details on how we can amend the role of the "Ward-level Admin" once the change is made. 
We could think of allowing ward-level admin access over only the patients where the ward is mentioned and keep the rest of the functionalities consistent.

**Comment by gigincg** [comment]
Ward is no longer Mandatory in Patient Registration
