### ISSUE TITLE
Pincode Auto-fill is not working properly for Sikkim & Assam pincode

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5859]
**Describe the bug**

the auto-fill for Sikkim is not working properly, as the district names don't match the API response. Currently, our platform stores district as "South Sikkim" and API respond recevied as "South District"/

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient
2. Click on pincode and type it in
3. See error

**Expected behavior**

Update our database as same as the API response 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/7d32b1e3-100c-4276-93f8-1db10b512c6f)

**Comment by Ashesh3** [comment]
We are keeping the existing state and district list as the pin code api is not up to date with the latest state and district data.
