### ISSUE TITLE
Make Patients page responsive

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5877]
**Describe the bug**
The `Consultation` buttons' text is going out. The `Vaccinated` and `Transfer blocked` divs are also congested.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/01810c32-ec26-494a-9e65-40e5547a7746/patient/4b230b87-392e-444e-bcc9-a0ff2f664820
2. Scroll down to the `Consultation History` section
3. See error

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/70687348/4b3767d5-c9cb-4848-ad65-24abaf84839f)

![image](https://github.com/coronasafe/care_fe/assets/70687348/9f4599d7-bfe6-4eea-972c-98015f4ba58a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kshitijv256** [comment]
Is someone already working on this issue?, if not can you assign it to me

**Comment by Pranshu1902** [comment]
@kshitijv256 You can start working on this issue, I have assigned it to you.
