### ISSUE TITLE
In the medicines tab time tooltip is not visible in mobile devices

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#5891]
**Describe the bug**
In the medicines tab time tooltip is not visible in mobile devices

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/be6211ba-9057-41eb-9a0d-b1800d76c2e7/patient/2efa2a49-9f4e-45f6-b0b1-4e4f0707d420/consultation/4e97d01d-d3fb-463b-b58a-05d0135dbb51/medicines
2. Scroll down to Prescriptions
3. Switch to mobile device view
4. See the error

**Expected behavior**
We can change the tooltip appearing position in mobile devices

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/59426397/990b6788-e14e-4ad6-9f2a-552c043ad7ba)

**Comment by kshitijv256** [comment]
hey @patelaryan7751, is someone working on it.
If not can you assign me
