### ISSUE TITLE
Clear button and other data's overlapping in log update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5900]
**Describe the bug**

In the log update of a patient, the data's such as bp, etc... are overlapping with the clear button, which looks bad

**To Reproduce**

1. Go to https://care.ohc.network/facility/bd0575bc-d516-49e5-89b2-02c455270edc/patient/403579cd-59e2-4b0a-a3cc-a21c9c6c01d3/consultation/83233bf8-c167-4664-827f-b2dfa4976b78
2. Click on log-update 
3. Scroll down

**Expected behavior**

The clear button and the data's related to the field should not overlap

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/986e0d8b-4fd1-48b2-8e9e-9e329673dd8c)

**Comment by rithviknishad** [comment]
ack
