### ISSUE TITLE
Not able to raise claim from the claims page in the CARE preview

### ISSUE THREAD

**Issue by ajitsingh2603** [coronasafe/care_fe#5906]
**Describe the bug**
After pre-auth approval, when trying to raise the claim from the claims page the claims request is not sent to the payor.

**To Reproduce**

1. Go to 'Claims'
2. Click on add details
3. Add treatment details
4. Select claims in the dropdown
5. Send claim request
6. See error

**Expected behavior**
It should raise claim request to the payor. 

Preview details : 
Care App :[ https://deploy-preview-5681--care-net.netlify.app/facility/](https://deploy-preview-5681--care-net.netlify.app/facility/)
devdistrictadmin
Coronasafe@123

**Comment by Ashesh3** [comment]
@khavinshankar could you confirm if this issue is still relevant?

**Comment by khavinshankar** [comment]
This issue was resolved, if it persists, please feel free to reopen this issue or create a new.
