### ISSUE TITLE
Coverage eligibility request after creating consultation

### ISSUE THREAD

**Issue by ajitsingh2603** [coronasafe/care_fe#5907]
**Describe the bug**
Not able to send coverage eligibility request after a new consultation

**To Reproduce**

1. Go to 'Create consultation ' and create new consultation
2. Click on 'Claims'
3. The coverage eligibility request is pre-approved as a coverage eligibility request sent after 'Add Patient' flow
4. The coverage eligibility button is 'not clickable'
5. See error

**Expected behavior**
The button should be in clickable mode permanently. We can update 'Eligible status' on the insurance dropdown card. Still, patient/provider should be able to raise coverage eligibility request as many times.

**Screenshots**<img width="1280" alt="Screen Shot 2023-07-24 at 12 46 43 PM" src="https://github.com/coronasafe/care_fe/assets/140377851/2086fdbc-52a1-429a-938d-a748d4bef340">

**Comment by UdaySagar-Git** [comment]
@nihal467 i would like to work on this

**Comment by khavinshankar** [comment]
This is an intended behavior, if the policy is already eligible, the `check eligibility` button is disabled.


@ajitsingh2603  Closing this issue, if the flow needs to be different i.e., if the policy should be verified before each claim or if there is an expiration for the policy's eligibility, please file a new issue with the respective context and details.

**Comment by khavinshankar** [comment]
@UdaySagar-Git this issue seems to need more discussion at the product end, please feel free to pick another issue. Thanks.
