### ISSUE TITLE
Date picker: allow user to type

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5909]
**Is your feature request related to a problem? Please describe.**
The date picker in CARE currently opens up a calendar where the user is supposed to select the year, month and date. 

This, especially when picking Date of Birth is not very user-friendly where users have to select a date way back in the past.

**Describe the solution you'd like**
Allow users to type in the date, month and year along with the option to pick from the calendar.

**Comment by rithviknishad** [comment]
https://vercel.com/design/calendar

How about this design? We add an editable date textbox inside the dropdown component.
