### ISSUE TITLE
Discharge summary is not generated properly in production

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5912]
**Describe the bug**

- Discharge summary is not generated in the production 
- the discharge summary notification should specify a time duration

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/bd0575bc-d516-49e5-89b2-02c455270edc/patient/403579cd-59e2-4b0a-a3cc-a21c9c6c01d3/consultation/83233bf8-c167-4664-827f-b2dfa4976b78
2. Click on generate discharge summary 
3. See error

**Expected behavior**

- Discharge summary should work properly https://github.com/coronasafe/care/pull/1482
- discharge summary notification should specify a time https://github.com/coronasafe/care_fe/pull/5954
- discharge summary file should be present in consultation file upload section https://github.com/coronasafe/care_fe/pull/5963

**Screenshots**

![WhatsApp Image 2023-07-25 at 11 01 43](https://github.com/coronasafe/care_fe/assets/57055998/1404e927-b160-402f-8db9-5d780039a6b1)

**Comment by aparnacoronasafe** [comment]
@Ashesh3 @nihal467 What does the PR https://github.com/coronasafe/care_fe/pull/5963 do? I dont see the discharge summary automatically getting added to File Upload. How is it supposed to work?

**Comment by nihal467** [comment]
@aparnacoronasafe 
![image](https://github.com/coronasafe/care_fe/assets/57055998/5f2a857f-2654-4f55-b203-62bd1c2cc7f3)

Initially, when a user clicks the "Discharge Summary" button to generate it, the discharge summary starts generating. Sometimes, it will be generated instantly, while others may take some time. Once the generation is completed, a "Discharge Summary" section will be visible in the files section, where you can find all the discharge summaries generated for the patient.

**Note:** If there is no discharge summary present for the patient, the "Discharge Summary" section in the file section will be invisible.

**Comment by nihal467** [comment]
the issue is resolved, closing this issue
