### ISSUE TITLE
Shifting form

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5943]
Make the following changes in the shifting form (https://care.coronasafe.in/facility/be6211ba-9057-41eb-9a0d-b1800d76c2e7/patient/2efa2a49-9f4e-45f6-b0b1-4e4f0707d420/shift/new)

- [ ] Change "Contact person at the current facility" to "Name of Contact person at the current facility"
- [ ] "Contact person phone" to "Contact person phone number"
- [ ] Allow "Contact person phone number" to accept landline numbers also. The format of a landline number varies largely across states. example:- 0827-4238365 or 03879-222120 or 011-3999-9808. Either add data validation that accepts all these numbers or allow numbers in any format to be fed to the field. Also allow for " " (space) and "-" to be added between the numbers

**Comment by rithviknishad** [comment]
@GokulramGHV 

After discussions for the phone number field, the following conclusions have been made.

- [ ] Enforce mandatory country code in the Phone Number Field (across the platform, no places this rule becomes inapplicable). 
- [ ] This way the auto-formatter by the library always works (spaces and dashes) are taken care automatically for display purposes.
- [ ] Ensure the state's value is always unformatted (does not contain spaces or dashes)
