### ISSUE TITLE
Auto-close Symptoms dropdown when "ASYMPTOMATIC" selected

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5944]
**Describe the bug**
When "Asymptomatic" is selected, the dropdown does not close automatically. Asymptomatic is a single select option and other options are multi-select options.

**To Reproduce**

1. Attempt to create a consultation
2. Select Asymptomatic symptom

**Expected behavior**
- [ ] Symptom dropdown should close automatically when "Asymptomatic" is selected.
- [ ] Symptom dropdown should NOT close automatically when any other option is selected.

**Screenshots**
<img width="930" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/60f625fe-4ce4-4c29-8624-1c3b7c6bde5e">

**Comment by pred695** [comment]
Hello @rithviknishad , can you please assign this issue to me? I will do the needful.

**Comment by Ashesh3** [comment]
@pred695 Any updates on this issue?

**Comment by UdaySagar-Git** [comment]
hi @Ashesh3 looks like he is not active , can i work on this issue ?

**Comment by Ashesh3** [comment]
sure @UdaySagar-Git
