### ISSUE TITLE
Understanding time contributed by doctors

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5956]
**Is your feature request related to a problem? Please describe.**
There is no distinction between a full-time resource (doctor) and a part-time resource

**Describe the solution you'd like**

- [ ] user registration form: when user type is selected as a doctor, a field for "Time-contributed to patientcare" ( must appear with dropdown with 4 option: "25%, 50%, 75%, 100%". When the user hovers over the field, you could also allow an explanation "The % time contributed by the doctor in treating patients in CARE deployed locations through a regular working day/week."
- [ ] This field must be editable in "Edit Profile" option by the concerned doctor themselves.
- [ ] The information must be visible in the "users" page in the respective cards
- [ ] Also allow district/state admins to edit this field for any doctor on the users page

**Comment by aparnacoronasafe** [comment]
@Ashesh3 we need this in the next release. It is a priority. 

Why is it blocked?

**Comment by Ashesh3** [comment]
@aparnacoronasafe the issue needs to be re approached to make it useful for the platform. A team discussion is required before proceeding to implement the feature.

**Comment by aparnacoronasafe** [comment]
Discussed with Gigin. Needed clarity on what are the requirements for the dashboard out of this. 

CARE must be able to send information on 
1) How many individual doctors
2) whats the actual resource available taking into account % availability?

Eg: If a hospital has the following doctors:
Doc 1: 100%
Doc 2: 50%
Doc 3: 50%

Metabase must be able to gain data on 
1) No. of individual doctors- 3
2) No. of resource (doctor) available: 2 (1+0.5+0.5)

@Ashesh3 please deploy in a manner that allows metabase to get this info

**Comment by Ashesh3** [comment]
> Discussed with Gigin. Needed clarity on what are the requirements for the dashboard out of this.
> 
> CARE must be able to send information on
> 
> 1. How many individual doctors
> 2. whats the actual resource available taking into account % availability?
> 
> Eg: If a hospital has the following doctors: Doc 1: 100% Doc 2: 50% Doc 3: 50%
> 
> Metabase must be able to gain data on
> 
> 1. No. of individual doctors- 3
> 2. No. of resource (doctor) available: 2 (1+0.5+0.5)
> 
> @Ashesh3 please deploy in a manner that allows metabase to get this info

Requirements changed after discussion with Gigin,

- We are adding a weekly working hours field for all the users on the platform.
- This information is to be processed through Metabase to show the data in the format mentioned originally in the issue.
