### ISSUE TITLE
Draw grid and scale using background canvas context.

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5983]

**Comment by gigincg** [comment]
@nihal467 Can you add context. If this is about the rebuild of 5 Para integrations that Rithvik did, I think this can be closed

**Comment by nihal467** [comment]
![image](https://github.com/user-attachments/assets/0db61821-26d5-4828-be30-6f2ca3a20781)

Closing this issue, as it was opened with the intention of adding a grid similar to the eChart component in the vitals monitor. Currently, there is no requirement for this feature, and the real device does not have a grid.
