### ISSUE TITLE
Disable `patient_category` in Consultation Form if there is a `last_daily_round` present.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5990]
### Tasks

- [ ] Disable `patient_category` in Consultation Form if there is a `last_daily_round` present.
- [ ] Add hint below the field mentioning that a daily round has been filed.

cc: @aparnacoronasafe any opinions

**Comment by aparnacoronasafe** [comment]
No. Please go ahead. 

We have instances where the nurses edit category on consultation and expect it to change over the patient profile. (While there is a log update) 

This change is to avoide them from updating it in consultation rather than the latest log update
