### ISSUE TITLE
Have a static loading screen in `index.html`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5991]
CARE loading animation (similar to one which we have inside the app) should be shown while the js files are being fetched. 

Refer #6012 for the first attempt on solving this.

**Comment by jainvedant392** [comment]
Hey @rithviknishad, is this issue open to work on? I would like to contribute to it.

**Comment by rithviknishad** [comment]
Hey @jainvedant392 Yes, it's open for contribution!

**Comment by jainvedant392** [comment]
Sure, thanks a lot.
Could you please provide a little idea on how to approach this issue?

**Comment by rithviknishad** [comment]
The index.html should show the CARE loading element (similar to the `Loading` component we have, see [this](https://github.com/coronasafe/care_fe/pull/6012/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R40-R55) for example implementation of it already done).

And this should be shown while the index.js is being fetched / ReactDOM.render() is executed.


Attaching some references that might help:

- https://stackoverflow.com/a/40989121/7887936

**Comment by jainvedant392** [comment]
Sure. That was a lot help. Will try to resolve this soon.

**Comment by jainvedant392** [comment]
Hello @rithviknishad, extremely sorry for being inactive for so many days due to some unavoidable circumstances.

**Comment by jainvedant392** [comment]
But I have been working for this issue for some days and reading the code of the repo as well.

**Comment by jainvedant392** [comment]
I had a doubt, since we have used "Suspense" from 'react' in App.tsx, which configures the loading screen, so why we have have to integrate it in the index.html.

**Comment by jainvedant392** [comment]
And to do the same, I might need to disable the effect of "Suspense", am I allowed to do so?

**Comment by rithviknishad** [comment]
Have you tried removing suspense? Didn't it break?
We have lazy-loaded components inside suspense.

Also is there a relation between suspense and this issue? This issue is about having a loading element in the index.html before react takes over / rewrites out that element.

**Comment by jainvedant392** [comment]
Ok I think I got what you are saying, so basically, I just have to configure a Loader in index.html, which would be same as the Loading component. Am I right?

**Comment by jainvedant392** [comment]
I can place the Loader inside the "root" div, which would afterwards be overwritten by the loaded React.

**Comment by rithviknishad** [comment]
Yes, that's what the previous PR attempted.

**Comment by jainvedant392** [comment]
Ok, thanks a lot.
