### ISSUE TITLE
User cards sizes are inconsistent

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5992]
**Describe the bug**

In the user page, we are showing the data's inconsistently, the below mentioned are the data shown in the card :

1. User Id
2. Full-name user
3. Last Online 
4. Role
5. District
6. Location ( For some user have it and some don't)
7. Created by ( For some user and some don't)
8. Home Facility
9. Weekly Working Hours
10. Qualification , Experience and MC Registration ( For doctor's Only)

This whole multiple data's shown in multiple ways for different users, which creates inconsistently in the card size

@aparnacoronasafe I am thinking, we can show all the common components and any specific field like Qualification, anything extra, can be hidden, and give the option to expand to view each user card's full fields.

**To Reproduce**

1. Go to https://care.coronasafe.in/users?page=1&limit=18&first_name=&last_name=&phone_number=&alt_phone_number=&user_type=Doctor&district_id=
2. Scroll down to bottom
3. See error

**Expected behavior**

To be reviewed by @aparnacoronasafe 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/79e02b81-417f-4de1-9b91-67eb5acca11f)

**Comment by aparnacoronasafe** [comment]
@nihal467 We do not want to hide important data points like qualifications (for doctors)

Let's have a uniform ordering and format. 

We could identify data points which are not as relevant and have those hidden (maybe user that created the user, last online etc)

With the above, can you edit the issue?

**Comment by bodhish** [comment]
We will rebuild users page with RBAC;
