### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#6004]
<img width="563" alt="image" src="https://github.com/coronasafe/care_fe/assets/46787056/202509b7-dfeb-4808-9e7b-71792865bda3">

for a detailed report run `npx vite-bundle-visualizer`

some ways this can be fixed:

- [x] #5977 
- [x] #7352
- [x] #6023
- [x] #6373
- [x] #6006
- [x] #6082 
- [x] #6305
- [x] #6051
- [ ] dynamic loading for huge components (Patient, Facility, CareIcons)
- [x] #7270
- [x] #7855
- [x] uninstall axios
- [x] #6316

**Comment by rithviknishad** [comment]
Just putting this here (before these are replaced/uninstalled)

<img width="1822" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/3087ab7c-25b7-4e3d-a27d-3fa67d2c0c03">

**Comment by nihal467** [comment]
entire platform are modified, reopen if its still relevant
