### ISSUE TITLE
remove lodash

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#6006]

**Comment by rithviknishad** [comment]
Keeping the issue opened, as loadash was not removed and only replaced in previous PR

**Comment by Ashesh3** [comment]
@sainak are you still working on this?

**Comment by tellmeY18** [comment]
@gigincg

**Comment by bodhish** [comment]
@tellmeY18 Whats the status here?

**Comment by SwanandBhuskute** [comment]
@rithviknishad @nihal467 pls assign me this issue

**Comment by SwanandBhuskute** [comment]
@tellmeY18 @nihal467 @rithviknishad so here
- i have to uninstall the "lodash-es": "^4.17.21", package 
- then remove the respective imports from all the files 
- and replace the lodash methods with some alternatives
- like
- - in file src/Utils/Notifications.js
- - we have - import { camelCase, startCase } from "lodash-es";
- - so by removing this import , i should replace the code for its method
- - make custom methods like
- - ![Image](https://github.com/user-attachments/assets/c0108a72-b249-4d46-85b4-735ee9b7d9ce)

and similar in other files

is my approach right?

**Comment by rithviknishad** [comment]
Yup!

For casing changes specifically, I'd suggest refactoring the usages to use [tailwind's text transform classes](https://tailwindcss.com/docs/text-transform) instead of JS wherever possible.

**Comment by SwanandBhuskute** [comment]
ok understood @rithviknishad

**Comment by SwanandBhuskute** [comment]
@rithviknishad @tellmeY18 @nihal467  I have removed all the lodash imports and used custom js functions / properties 

but these two files
- bom.json
- fe-sbom.json

has too many lodash occurences

so now
after uninstalling lodash from the project

how should i handle these two files?

**Comment by tellmeY18** [comment]
Hey, the bom.json and fe-sbom.json are autogenerated via a workflow which is listing out the dependencies used in care and care_fe. you can ignore the occurance of lodash inside these 2 files and once it's completely removed from the project we should be able to generate jsons that doesn't have lodash occurences.

**Comment by SwanandBhuskute** [comment]
> Hey, the bom.json and fe-sbom.json are autogenerated via a workflow which is listing out the dependencies used in care and care_fe. you can ignore the occurance of lodash inside these 2 files and once it's completely removed from the project we should be able to generate jsons that doesn't have lodash occurences.

oh okay, then I will just raise PR

**Comment by SwanandBhuskute** [comment]
@tellmeY18 @rithviknishad @nihal467 
hey after running npm run build
i got this log

![Image](https://github.com/user-attachments/assets/244df409-07e5-4a0c-a550-9e7901ee716d)
