### ISSUE TITLE
Marking Death on patient profile

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6022]
**Is your feature request related to a problem? Please describe.**
In CARE an expired patient can be re-admitted in another encounter. This must not be allowed. A patient, once marked dead, the record must not be editable.

**Describe the solution you'd like**

- [x] Once the patient is discharged marked as expired, the patient file must not be transferred to another hospital/ must not be able to have another encounter on top of it. 
In the patient transfer form, the dropdown to select patient, an expired patients name should appear disabled (in grey) with "(expired)"added against the name
![Screenshot 2024-07-08 at 10 29 24 AM](https://github.com/coronasafe/care_fe/assets/67050716/455fc1b2-dabf-430c-8845-11446a84f22b)

- [x] show a message stating that expired patient data cannot be edited later. In discharge pop-up, when Expired is selected in reason for discharge, change the text "Caution: this action is irreversible" to "Caution: Once a patient is marked as expired, the patient file cannot be transferred or edited. Please proceed with caution". Make this text appear in red colour. 

![Screenshot 2024-07-08 at 10 33 56 AM](https://github.com/coronasafe/care_fe/assets/67050716/80619d5b-239b-437e-8650-107a6b201b09)

@gigincg Please comment

**Comment by rithviknishad** [comment]
@gigincg can we unblock this? seems pretty straight forward.
