### ISSUE TITLE
Phone validation errors are not being shown during onBlur

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6027]
> - Follow up of #5999 
 
> -> Invalid input's post-submission getting rejected without error message
> -> Even though in user filters, we say it says  whatsapp phone number doesn't support landline number, the field is accepting the data and showing the badge
> 
> _Originally posted by @nihal467 in https://github.com/coronasafe/care_fe/issues/5999#issuecomment-1669401821_

**Describe the bug**
When a phone number is entered in advanced filters (eg: user filters), it is not showing invalid phone number if a landline number is entered when the field is supposed to accept only mobile numbers.

**To Reproduce**

1. Go to User Advanced filters
2. Enter landline number in WhatsApp number
3. Change element focus to trigger validation check
4. Does not show validation error message

**Expected behavior**
Should show validation error message

**Comment by kshitijv256** [comment]
I would like to work on it
