### ISSUE TITLE
add extra pading for the patient total count card

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6047]
**Describe the bug**

in the patient tab, total patients card padding is mis-aligned

note:
It is happening only in laptop with 150% display scale (recommended settings for all new windows laptop) and having a 14 inch screen size

**To Reproduce**

1. Go to https://care.coronasafe.in/patients?page=1&limit=12&emergency_phone_number=
2. See error

**Expected behavior**

the padding for the total patient no card should be increased 

**Screenshots**

<img width="959" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/d557e0e3-4b1a-49ea-a95e-e7f17a6e7932">

**Comment by kshitijv256** [comment]
@nihal467  can you assign me this issue
