### ISSUE TITLE
"update log" button is overflowing the patient consultation page 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6049]
**Describe the bug**

"update log" button is overflowing in the patient consultation page 

**note:**
It is happening only in laptop with 150% display scale (recommended settings for all new windows laptop) and having a 14 inch screen size

**To Reproduce**

1. Go to https://care.ohc.network/facility/9c1ffc8a-7dbe-45eb-94f7-fa754ad2d60f/patient/9e0919f5-f8a0-4011-8fab-063eca47390c/consultation/aea808ad-a5f8-4b40-9c22-b78f8cbc2e4d
2. See error

**Expected behavior**

it should not be overflowing

**Screenshots**

<img width="960" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/f996f188-c23c-4f26-b534-54693f66d6b3">

**Comment by rithviknishad** [comment]
Should we consider adding https://github.com/tailwindlabs/tailwindcss-container-queries now that we are having more responsiveness issues for different zoom/display scaling coming up.
