### ISSUE TITLE
Notification are not working properly

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6061]
**Describe the bug**

We are receiving notification of the care in the system, but when we open the notification, the entire system heat up and the page never loads up.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility ( using district admin)
2. Click on notify and send a notice
3. logout and login using a staff id, subscribe the notification and receive a notice
4. once you receive a notice, check the notification of your system, not care
5. you would have received the notification and click on it to open it
6. See error

**Expected behavior**

it should ideally show the notice

**Screenshots**
![WhatsApp Image 2023-08-11 at 13 10 17](https://github.com/coronasafe/care_fe/assets/57055998/c194f7f0-4edb-41c4-8f3e-df0b6079e694)

**Comment by harikamahapatra** [comment]
hi,
is this open? if it is I'd like to contribute.
thank you in advance.

**Comment by Ashesh3** [comment]
> hi, is this open? if it is I'd like to contribute. thank you in advance.

Yep, you can work on it.

**Comment by harikamahapatra** [comment]
thanks for assigning but I'm sorry about this, there seems to be a problem with subscribing to notifications action as I'm unable to get that on my device.

**Comment by Ashesh3** [comment]
@shrmp07 We plan to publish a documentation for setting up the notifications to work soon. Since this is a Priority 1 issue, I'll be taking care of it for now, feel free to work on other issues. Thank you :)

**Comment by harikamahapatra** [comment]
okay sure, thanks.
