### ISSUE TITLE
service workers not working in development environment

### ISSUE THREAD

**Issue by JahnabDutta** [coronasafe/care_fe#6069]
**Describe the bug**
Service workers are limited to prodcution environment. Request changes for working of service workers for all environments.

**To Reproduce**
- set up care_fe locally.
- Check applications tab in browser.

**Expected behavior**
- Registration of service workers in local environment.

**Desktop (please complete the following information):**

- OS [All]
- Browser [All]
- Version [Latest]

**Smartphone (please complete the following information):**

- Device: [All]
- OS: [All]
- Browser [All]
- Version [Latest]

**Comment by nihal467** [comment]
@khavinshankar can you look into it
