### ISSUE TITLE
Asset Export: Allow xlsx, csv

### ISSUE THREAD

**Issue by aparnaegov** [coronasafe/care_fe#6079]
**Is your feature request related to a problem? Please describe.**
The option to export asset list is not usable since it only allows for export in JSON

**Describe the solution you'd like**
Allow export of asset list from asset page (https://care.coronasafe.in/assets) in xlsx, csv formats

**Describe alternatives you've considered**

**Additional context**

**Comment by gigincg** [comment]
@aparnaegov Why?

**Comment by aparnaegov** [comment]
The users dont understand JSON. The feature is not usable.

If CSV export is allowed, the hub admins can download list of assets in a facility, change the serial nos, facility names etc for another 10bedicu and import it to easily register the newer 10bedicu assets

**Comment by nihal467** [comment]
@gigincg can you look into it

**Comment by aparnacoronasafe** [comment]
Need this delivered in next release
