### ISSUE TITLE
Disallow multiple prescriptions of same medicine that are active

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6085]
**Describe the bug**
Currently, there's no validation that prevents users from adding prescriptions with same medicine.

**To Reproduce**

1. Go to patients Medicines
2. Add two prescriptions of same medicines (without discontinuing)

**Expected behavior**
- [ ] Suggest to edit if prescription of same medicine exists and users intention is to update.
- [ ] Back-end should reject adding prescription with same medicine (active prescriptions).

**Screenshots**
<img width="902" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/34aeac8f-d5e3-43a0-9127-4a02a4fcb767">

**Comment by rithviknishad** [comment]
@aparnacoronasafe Thoughts on this?

Do we have requirements like one prescription of a medicine has frequency "twice daily" and another prescription of same medicine with different frequency say "once weekly" for example to exist at the same time?

**Comment by aparnaegov** [comment]
This is a good idea Rithvik.

If the user tries to select the exact same medicine from the medibase dataset, show a prompt saying the medicine is already there in prescription and allow user to edit the prescription for that medication.

To answer your questions, if medicine A is prescribes Once a day (morning) and the doctor wishes to make it thrice a day, hw must edit the existing prescription to change frequency (Not make a separate entry for Medicine A twice a day- Noon, evening)
