### ISSUE TITLE
Asset Availability History: Typo in Date Format

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6089]
**Describe the bug**
Typo in Date Format in Asset Availability History

**To Reproduce**

1. Go to asset details page

**Expected behavior**
Date should be in the format "12th July 2023" instead of "12o July 2023"

**Screenshots**
<img width="1005" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/dbf78803-2dd5-4071-8121-f16357ee2288">

**Comment by kshitijv256** [comment]
@rithviknishad I would like to work on it

**Comment by SamantaTarun** [comment]
@rithviknishad May I work on it?
