### ISSUE TITLE
Multiple beds can be created with the same name

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#6112]
**Describe the bug**
When we use the feature to create multiple beds at the same time, it results in beds having same names which doesn't allow the user to edit or delete those beds because of multiple ids.

**To Reproduce**
1. Go to https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/location/0ca0bc97-6b20-42e9-8a7a-f03cd8692f5f/beds
2. Create a bed with the name `Bed 1`
3. Now create another bed with the name `Bed` but set the number of beds to 2

**Expected behavior**
Before the algorithm automatically adds `1` at the end of each bed name, it should check whether that name has already been taken or not.

**Screenshots**
![image](https://github.com/coronasafe/care/assets/70687348/6266f541-6ae5-41cf-8593-545d2c3816dd)
![image](https://github.com/coronasafe/care/assets/70687348/3ae52528-f9be-4990-b313-5f779058a030)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mustafaazad03** [comment]
Can I contribute to this issue??

**Comment by Pranshu1902** [comment]
@mustafaazad03 this is a backend issue and the PR has already been raised

**Comment by mustafaazad03** [comment]
Ok thank you @Pranshu1902

**Comment by Pranshu1902** [comment]
PR raised in backend
