### ISSUE TITLE
Enhancement Of Temporary Asset UI

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6120]
**Describe the bug**

- [ ] Currently, when we unlink a temporary asset, the bed history table shows that the entire bed was unlinked during that unlinking process, even if it was just the temporary asset that was unlinked.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/e6981f39-d0b4-402d-9572-683f83c2f3eb/patient/04d80830-275e-4f93-8211-1a7a03005c29/consultation/5589c69e-490e-488d-9606-1c6066f063df
2. Click on switch bed and link and unlink an asset and see the error

**Expected behavior**

- [ ] Rename Bed to Bed/Ventilator ( Get UI approach in EOD call before working on it as there are chances that button become bigger and the UI look bad )
- [ ] The linked asset and bed start date and end date should be shown in separate rows rather than showing number 1 along with the bed

![WhatsApp Image 2023-08-21 at 12 49 31](https://github.com/coronasafe/care_fe/assets/57055998/827deb24-b7ed-43f4-81cb-7cd4ec84d6a6)

**Screenshots**

<img width="839" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/fc7584a0-7057-46cf-a6f9-ada771dffd09">

**Comment by gigincg** [comment]
@nihal467  This is expected behaviour for audit reasons
