### ISSUE TITLE
Shifting request- enhancement

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6134]
**Is your feature request related to a problem? Please describe.**
A patient can have only 1 live shifting request at a time. However, a user, unaware of the earlier raised shifting request, may fill out the shifting form, and only at the time of submission, will realise that the patient already has a live shifting request. Then the user will have to go to the shifting board, and search patient by name to view the shifting request. 

The user loses a lot of time.

**Describe the solution you'd like**
When there is a live shifting request for a patient (a shifting request which has status of pending, approved, destination approved, patient to be picked up, transfer in progress), the "shift patient" button on patient dashboard (https://care.coronasafe.in/facility/10c66ed2-5b95-4649-bd2f-f5766334e1cd/patient/5ea5550d-acc3-426e-888f-42f0ed58b705/consultation/a01ba745-67a4-4be7-9146-5ebc76aa500f) to change to "Track shift" and must redirect the user to the shift request (https://care.coronasafe.in/shifting/24772da0-1bf8-46d5-a7ab-85da89c71d81)

**Comment by aparnacoronasafe** [comment]
adding to wishlist since shifting module is not actively in use currently.

**Comment by thtauhid** [comment]
Hi,
I'd like to work on this.

**Comment by thtauhid** [comment]
Hi @rithviknishad can you assign this to me?
Thanks
