### ISSUE TITLE
Add "Bed Status" tab in Update consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6139]
**Is your feature request related to a problem? Please describe.**
The last section of update consultation form has log of beds assigned. However the same doesnt appear as a section in the navigation on the left.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.](https://care.coronasafe.in/facility/10c66ed2-5b95-4649-bd2f-f5766334e1cd/patient/5ea5550d-acc3-426e-888f-42f0ed58b705/consultation/a01ba745-67a4-4be7-9146-5ebc76aa500f/update)
Add "Bed status" as a section. make it appear in the navigation on left side below "treatment plan"

**Comment by suprabathk** [comment]
I would like to work on this
