### ISSUE TITLE
Capture time of admission

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6141]
**Is your feature request related to a problem? Please describe.**
We are not capturing the time of admission.

**Describe the solution you'd like**
In the consultation form, there is a field for "Date of admission". change it to "Date and Time of Admission". Use the usual time picker along with the date picker. The default date and time shall be the current date and time.

**Comment by rithviknishad** [comment]
The admission_date field seems to be marked as deprecated in the backend but is still being used in the front-end and is doing a required field validation in the serializer.

cc: @gigincg

**Comment by rithviknishad** [comment]
We should be renaming 

- [x] `admission_date` field to `encounter_start_date` (DateTimeField)
- [x] `discharge_date` to `encounter_end_date` (DateTimeField)

And following changes are to be made in front end:
- [ ] Allow Admission Date / Home Isolation start to be a DateTime input.

**Comment by nihal467** [comment]
@cp-Coder unassigning you from this (P2) PR due to inactivity

**Comment by khavinshankar** [comment]
This issue is tracked in different pr https://github.com/coronasafe/care_fe/issues/6280

cc: @nihal467 @rithviknishad
