### ISSUE TITLE
Principle Diagnosis

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6144]
**Is your feature request related to a problem? Please describe.**
The patient may have multiple diagnoses. However, there is always 1 diagnosis which is the primary reason why the patient is admitted in the ICU. It is important to capture that one diagnosis called "principle diagnosis". This principle diagnosis may be revised from time to time. However, at any point in time, there is only ONE diagnosis considered as the "principle diagnosis"

**Describe the solution you'd like**
In the consultation form, in the diagnosis section, once the user selects both provisional and final diagnosis,

- [x] Add a third field below prov. and final diagnosis for "Principle Diagnosis"
- [x] The input field will have a dropdown with options of all final diagnoses mentioned by the user above. In case, there is no final diagnosis and only provisional diagnosis is there for the patient, the options will show all provisional diagnosis. 
- [x] The user must select only 1 diagnosis as the principal diagnosis.
- [x] "Principle diagnosis" will be a mandatory field.
- [x] If the final/prov diagnosis is edited to remove the previously selected principle diagnosis, the principle diagnosis field must automatically reset and the user will have to select a new principle diagnosis before submitting the form. 

**Describe alternatives you've considered**

**Additional context**

**Comment by nihal467** [comment]
@gigincg need to discuss with @vigneshhari 

- [ ] merge provisional and final diagnosis into one and have flags to differentiate it.

**Comment by rithviknishad** [comment]
As a quick solution, we'll be simply adding a field "Principle Diagnosis".

As a larger refactor of the icd11 diagnosis, a seperate issue in backend will be created.
