### ISSUE TITLE
Prescriptions: Add toggle button to filter medicines by type: "generic" only

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6154]
- [ ] In the Prescriptions form, add a toggle button to filter medicines by type: "generic" only

cc: @aparnacoronasafe 

![image](https://github.com/coronasafe/care_fe/assets/25143503/cd9f64e0-ea89-4fe7-af11-e6050312987e)

**Comment by aparnacoronasafe** [comment]
@rithviknishad how much work is it? when will you be delivering this?

**Comment by rithviknishad** [comment]
Hopefully, 2 weeks from now.
