### ISSUE TITLE
Merge "Configure Facility" and "Configure Health Facility" to one page: "Configure Facility"

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6158]
**Describe the bug**
In the Facility Home Page, Manage Facility dropdown, there are two options "Configure Facility" and "Configure Health Facility" that could be confused with each other.

https://care.ohc.network/facility/657c32be-d584-476c-9ce2-0412f0e7692e

**Expected behavior**
- Contents of both pages are to be merged into one single page under "Configure Facility".
- Contents of "Configure Health Facility" should be shown only if ABDM is enabled.

**Screenshots**
<img width="335" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/427097b7-16b9-4994-a0c9-aae09f3c23ba">

cc: @khavinshankar

**Comment by kshitijv256** [comment]
@rithviknishad I would like to work on this issue
