### ISSUE TITLE
Prescription : Freeze columns

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6177]
**Issues**

<img width="959" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/1a623281-fdc3-4c1c-b457-0ca80191e3c1">

- [ ] freeze the medicine and dosage and frequency column, so that in case user scrolls to the right or left, he can still understand, the administration is related to which prescription medicine

- [ ] Upon loading the page, I initially not seeing the latest data, for that, i needed to scroll to the right, so flip the entire date so , keep the latest date and time on the leftmost

**Comment by aparnacoronasafe** [comment]
This looks good

**Comment by rithviknishad** [comment]
Decided to only freeze the columns
