### ISSUE TITLE
Prescription : Add a field to manually input date and time

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6178]
<img width="761" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/b0e01f8d-f747-41c2-94c8-e13d51bdf99f">

- [ ] Add a field to input the date and time, when it was administrated, ( It should auto-fill the current time as we fetch in log-update but should give the user a provision to edit it, if required ) 
- [ ] Add an option to edit existing administration in case of mistake happens, incase of edit occurs, show a log in the UI itself, similar to the one, we have in the asset service history.

**Issues trying to address**

- If a medicine was administrated at 10:00 am and the nurse updated the record later at 11:30 am, the administration record in care shows that the medicine was executed at 11:30 am, which leads to an incorrect record.
- In case, during any data entry of the previous record, incorrect data is inputted, there will not be a provision to correct it

**Comment by aparnacoronasafe** [comment]
Please deliver in priority

**Comment by rithviknishad** [comment]
This issue will cover:

- [ ] Allowing the user to input `administered_date` to optionally override from using current DateTime by default.

A separate issue will cover the workaround for editing administrations. Users can archive a MAR and create a new MAR instead. #6184
