### ISSUE TITLE
Camera Feed Buttons are not working properly in iphone

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6181]
**Describe the bug**

- the reset and full screen buttons are not working properly in the iphone 

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/assets/fd605386-90d5-4e8b-bb82-f62b7349d1d3/configure 
2. Click on reset and full screen button from iphone google chrome browser
3. See error

**Expected behavior**

all the button should work properly

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/375877ab-96c8-40be-8c1d-e13764401e18)

**Comment by rithviknishad** [comment]
I don't have an iPhone :/

**Comment by Ashesh3** [comment]
> I don't have an iPhone :/

No worries, he was assigning it to me and selected your name by mistake 😅
