### ISSUE TITLE
Consultation form is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6213]
**Describe the bug**

- when we mark a patient “Brought Dead” and create a consultation, it is not auto-discharging the patient
- In the patient consultation tab, the verified by section is showing : brought dead.

**To Reproduce**

1. Go to patient tab
2. Create a patient and create consultation as brought dead
3. See error

**Expected behavior**

- a consultation marked “brought dead” in status during consultation should auto-discharge upon clicking create consultation
- Verified by section should be hidden for brought dead as it is not recorded 

**Screenshots**

![IMG_3151](https://github.com/coronasafe/care_fe/assets/57055998/13f1c73b-d07c-4fe4-9a36-b126671823e6)
![IMG_3149](https://github.com/coronasafe/care_fe/assets/57055998/2a49cacc-e452-4e25-8835-75cc05c541fb)

**Comment by rithviknishad** [comment]
https://github.com/coronasafe/care_fe/pull/6194
