### ISSUE TITLE
Weekly working hours (Add average)

### ISSUE THREAD

**Issue by aparnaegov** [coronasafe/care_fe#6216]
**Is your feature request related to a problem? Please describe.**
Doctor are hesitant to put a number for weekly working hours since its mostly ad hoc. 

**Describe the solution you'd like**

https://care.coronasafe.in/user/profile , https://care.coronasafe.in/users

Please change "weekly working hours" to "Average weekly working hours"

**Describe alternatives you've considered**
Take steps to give confidence to the doctors that the input is only an approximation

**Comment by kshitijv256** [comment]
I would like to work on this issue

**Comment by aparnaegov** [comment]
Please go ahead @kshitijv256
