### ISSUE TITLE
Bug in Back buttons (asset management)

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6233]
**Describe the bug**
When configuration is updated for an asset, The back button take user from the configuration page to asset page. But when user clicks back button from asset page to go to asset list, it simply takes user back to the the configuration page and goes in a loop.

**To Reproduce**

1. Go to any integratable asset eg: https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/ca805b03-a608-4ec6-844e-0e7fc564e140
2. Click on configure. you are taken to the configuration page. Update details there to configure asset. The Bug is only seem when this configuration is updated. Click on 'set configuration' to save the new configuration.
3. Click 'Back arrow'. You will land on the asset page. https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/ca805b03-a608-4ec6-844e-0e7fc564e140.
4. Click 'Back arrow' again. You should ideally get to the asset list (https://care.coronasafe.in/assets), but here the user is taken back to the confure form.

**Desktop (please complete the following information):**

- Browser [e.g. chrome]

**Comment by kshitijv256** [comment]
I would like to work on this issue
