### ISSUE TITLE
Hide Asset Configuration option from Doctors and staff user type

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6234]
**Is your feature request related to a problem? Please describe.**
Exposing the "Configure" option in asset management page https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/acd6a5e5-b344-4164-aa80-40a278b87a9a allow doctor and staff users to view the passwords and even change the configuration.

This is not useful since they are not responsible for maintaining the integrations and networks.

Only District/ State admin user types must have the ability to configure assets

**Describe the solution you'd like**
Dont show the "Configure" button (or disable the button) asset management page https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/acd6a5e5-b344-4164-aa80-40a278b87a9a for all user types except the "District Admin" and "State Admin"

**Describe alternatives you've considered**

**Additional context**

**Comment by thtauhid** [comment]
Hi, 
I would like to work on this issue.
