### ISSUE TITLE
File upload and Video Embedding for Assets

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6236]
**Is your feature request related to a problem? Please describe.**
The asset management module will benefit from having the option to 
1. store the invoice of the asset, warranty card etc in the Asset registry.
2. Embed video of Simple Troubleshooting steps, tutorials and Dos and Donts in using the equipments. Allow user to name the video

**Describe the solution you'd like**
In Asset update form (https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/acd6a5e5-b344-4164-aa80-40a278b87a9a/update) have the option to 
- [ ] upload one of more files and give it a name
- [ ] Embed videos from youtube etc by pasting the link and give it a name
- [ ] Give option to Preview, Edit file name and Delete the file/video
Add these options in a separate section at the bottom of the form called "Resources"

Have such uploads appear on the Asset Page (https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/acd6a5e5-b344-4164-aa80-40a278b87a9a)
- [ ] Replace "Service Details" section with "Resources". 
- [ ] Have all the different files appear as a list with Icons showing whether it is a document/video, name given by the user for the file/video with "View" button

**Comment by gigincg** [comment]
@print-Sathvik Temporarily unassigning since the issue is blocked as a related issue needs to be first closed.

**Comment by nihal467** [comment]
non-relevant to current develop
