### ISSUE TITLE
Improving GCS (Log Update)

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6277]
**Is your feature request related to a problem? Please describe.**
https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/a3c3471a-ded2-4a0f-b5de-e97d58e42e61/consultation/1aff513c-a53f-4e34-aa47-2606191fe434/daily_rounds/7a725cb7-e238-4348-aaa0-424239876d85/update
The Text in the GCS calculator is not very clear. Make the following changes.
(Please note that the calculator itself works well. only the text available of the screen needs to be improved)

**Describe the solution you'd like**
Change

- [ ] "Eye Open" to "Eye Opening Response"
- [ ] Under "Eye Open" change "Pain" to "To Pain"
- [ ] Under "Eye Open" change "None" to "No Response"

- [ ] Under "Verbal Response" change "None" to "No Response"
- [ ] Under "Verbal Response" change "Oriented/coos/babbies" to "Oriented to time, place and person"

- [ ] Under "Motor Response", change "None" to "No Response"
- [ ] Under "Motor Response", change "Incomprehensible words/moans to pain" to "Abnormal Extension"
- [ ] Under "Motor Response", change "Withdrawing" to "Flexion withdrawal from pain"
- [ ] Under "Motor Response", change "Localising Withdrawal to touch" to "Moves to localised pain"
- [ ] Under "Motor Response", change "Obeying/normal activity" to "Obeys commands/normal activity"

**Comment by kshitijv256** [comment]
I would like to work on it
