### ISSUE TITLE
"Verified by" to "treating physician"

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6278]
https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/a3c3471a-ded2-4a0f-b5de-e97d58e42e61/consultation/1aff513c-a53f-4e34-aa47-2606191fe434/update

Rename "verified by" field to "treating physician"

**Comment by thtauhid** [comment]
Hi,
I want to ask if we are looking to 
- just rename the label 
or 
- rename the whole `verified_by_object` (may include some backend work too I'm guessing?)

**Comment by rithviknishad** [comment]
Just renaming the label for now would do. 
Do create an issue in care backend repo to rename the field altogether.

**Comment by thtauhid** [comment]
@rithviknishad 
Okay. 
Please assign me this issue.
I'll also create the backend issue.
