### ISSUE TITLE
Expose Camera Present configuration to nurses and doctors

### ISSUE THREAD

**Issue by aparnaegov** [coronasafe/care_fe#6297]
**Is your feature request related to a problem? Please describe.**
Now that Asset configuration page is hidden for doctors and nurses, they not only donot have access to camera configurations and middleware configuration, but also the preset setting.

As the deployment of CARE strengthens in the field, it's important to pass on maintenance tasks to the end users (nurses/doctors). 

Maintaining presets  is one such responsibility that is currently being passed on the the nurses/doctors. 

Please allow nurses/doctors to change and adjust presets.

**Describe the solution you'd like**
Let nurses/doctors only have access to camera preset configurations, and NOT middleware and other integration related settings
@gigincg Please suggest a solution

**Describe alternatives you've considered**

**Additional context**

**Comment by aparnaegov** [comment]
@gigincg

**Comment by nihal467** [comment]
@Ashesh3 enable the configuration button and hide the configuration fields
