### ISSUE TITLE
"Action" in consultation update- not working

### ISSUE THREAD

**Issue by aparnaegov** [coronasafe/care_fe#6298]
**Describe the bug**
Unable to update the "action" field in edit consultation (https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/7af2ae4b-97e5-40e5-a585-df820de2c8dc/consultation/0ce602fd-5ace-4e84-933c-522087b8fb8f/update)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to edit consultation (https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/7af2ae4b-97e5-40e5-a585-df820de2c8dc/consultation/0ce602fd-5ace-4e84-933c-522087b8fb8f/update)
2. Go to "Action" field- change to "Specialist required"
3. Save form
4. Go again to edit consultation (https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/7af2ae4b-97e5-40e5-a585-df820de2c8dc/consultation/0ce602fd-5ace-4e84-933c-522087b8fb8f/update). 
5. My update of "specialist required" is not visible.

**Expected behavior**
allow users to update "action" on edit consultation. The updated action must come prefilled when the user opens edit consultation form

**Desktop (please complete the following information):**

- Browser :  chrome

**Additional context**
Same issue sometimes happens with "Review after"

**Comment by yogeshbhutkar** [comment]
I would like to work on this issue.
