### ISSUE TITLE
NE6Z (ICD-11) not appearing in search

### ISSUE THREAD

**Issue by aparnaegov** [coronasafe/care_fe#6299]
**Describe the bug**
[A clear and concise description of what the bug is.](https://icd.who.int/browse11/l-m/en#/http%3a%2f%2fid.who.int%2ficd%2fentity%2f1236563202%2fmms%2funspecified)
NE6Z is the ICD-112 code for **Harmful effects of unspecified substance**

The same does not appear in ICD-11 search on CARE

**To Reproduce**

1. Go to Consultation/edit consultation (https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/7af2ae4b-97e5-40e5-a585-df820de2c8dc/consultation/0ce602fd-5ace-4e84-933c-522087b8fb8f/update)
2. Click on Diagnosis/ preliminary Diagnosis
3. Search for "NE6Z" or "Harmful effects of unspecified substance"
4. See error: No result found

**Expected behavior**
The ICD-11 item for NE6Z must come up in search dropdown

**Screenshots**
<img width="1119" alt="Screenshot 2023-09-18 at 4 46 48 PM" src="https://github.com/coronasafe/care_fe/assets/141631446/dfadbb94-4991-4ca7-ab78-bc76b7394b93">

**Desktop (please complete the following information):**

- Browser Chrome

**Additional context**

**Comment by rithviknishad** [comment]
To attempt running a script to see if the label start can be used as the ID or not

**Comment by aparnaegov** [comment]
@nihal467 This needs to be closed soon.

@gigincg Please review
