### ISSUE TITLE
patient tab page is malfunctioning in the mobile view

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6306]
**Describe the bug**

In the patient tab view, when we scroll the page to the right side, it stretches the page and goes to an empty space

**To Reproduce**

1. Go to https://care.coronasafe.in/patients in mobile view and scroll right
2. See error

**Expected behavior**

It shouldn't extend the page in mobile view when we scroll right side

**Screenshots**

https://github.com/coronasafe/care_fe/assets/57055998/50b1514d-e418-4e6f-a45c-1fb4ba73f5d6

**Comment by thtauhid** [comment]
Hi,
I'd like to work on this issue.
