### ISSUE TITLE
reset button not working in IOS devices

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#6321]
This issue is IOS specific

**Steps to Reproduce:**
- Go to the patient consultation dashboard (choose a patient with a consultation and camera configured) https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/updates
- Go to the feed tab
- In there, try clicking on the reset button 
<img width="701" alt="image" src="https://github.com/coronasafe/care_fe/assets/29787772/0a3b04b1-1e44-4acd-9d5c-5aede5791946">

---

**Expected Result:**
- The web socket connection should be reset _(but currently nothing is happening)_

**Comment by Omkar76** [comment]
I can take this issue.

**Comment by Omkar76** [comment]
Should this be close now because we are going to use WebRTC instead?

**Comment by nihal467** [comment]
issue resolved
