### ISSUE TITLE
add auto reset in asset config page

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#6322]
Like the feed on the patient consultation page, add auto-reset to the asset config one too.

**Comment by thtauhid** [comment]
Hi @khavinshankar 
I'm interested in working on this issue. 

But, not fully sure what output is expected, can you please give a bit more detail on what needs to be done? 
A screenshot will also help. 

Thanks

**Comment by khavinshankar** [comment]
@thtauhid check this pr (https://github.com/coronasafe/care_fe/pull/6286) in which the auto-reset feature is implemented for the patient consultation feed page, same functionality is required in the feed of the asset config page.


cc: @nihal467
