### ISSUE TITLE
🛠️ Replace `useDispatch` w. `useQuery`/`request`: DeathReport (`src/Components/DeathReport/**`)

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6328]

**Comment by AlexVCS** [comment]
I'd like to work on this

**Comment by rithviknishad** [comment]
Hey @AlexVCS, we'll be unassigning you from this issue to keep it open for others as the related PR has become stale.

Feel free to ping if you are facing any blockers or checkout other good first issues.

**Comment by shyamprakash123** [comment]
I would like to work on this issue, can you assign me to this?

**Comment by shyamprakash123** [comment]
Hello, @rithviknishad where the `PrintDeathReport` component is used in CARE.

- `PrintDeathReport` is present in src/Components/DeathReport/DeathReport.tsx
