### ISSUE TITLE
Display age of patients below 1 year

### ISSUE THREAD

**Issue by Deepjyoti14** [coronasafe/care_fe#6339]
**Is your feature request related to a problem? Please describe.**
Age of infant patients coming as 0 years.

**Describe the solution you'd like**
Age should be in years, months and days.
For patients above 1 year show only year and for patients below 1 year show months and days.

**Describe alternatives you've considered**

**Additional context**

**Comment by Deepjyoti14** [comment]
@Ashesh3 what is the expected date of delivery?

**Comment by Ashesh3** [comment]
@Deepjyoti14 EDD: 2nd October (next release)
