### ISSUE TITLE
Make Medicine administration editable

### ISSUE THREAD

**Issue by SeyiesilieChadi** [coronasafe/care_fe#6340]
**Is your feature request related to a problem? Please describe.**
https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7c0917bf-b8d8-4e3b-8f5e-feed90657727/consultation/79525a36-21b0-4ae7-b99c-acc1e103a69e/prescriptions
It is very common for Doctors to change the variables of the medication such as the dosage, frequency and no. of days as per the patients' condition. In those cases ,the nurses are forced to discontinue the medication when all they need is to change the frequency / dosage or no. of days of the medication.

**Describe the solution you'd like**
Allow nurses/doctors to change the dosage / frequency and no. of days of the medication.

**Describe alternatives you've considered**

**Additional context**

**Comment by SeyiesilieChadi** [comment]
When will I expect the changes to take place?

**Comment by Ashesh3** [comment]
@rithviknishad I think we discussed this being the expected behavior, could you comment on it?

cc: @gigincg

**Comment by rithviknishad** [comment]
Yes. This was intentionally designed to not support edits. 

To change the dosage/frequency or any other attributes, the user will have to discontinue the ongoing prescription, provide a reason for discontinuation (whether it was an accidental error in the entry or an intentional change), and then create a new one.

**Comment by aparnacoronasafe** [comment]
@rithviknishad @Ashesh3  I know this was discussed, but could we revisit it?

It is a valid ask. Adjustment of dosage and frequency of medication is very common in ICUs

@gigincg

**Comment by aparnacoronasafe** [comment]
> When will I expect the changes to take place?

A date will be updated post discussion @SeyiesilieChadi

**Comment by rithviknishad** [comment]
@SeyiesilieChadi @aparnacoronasafe 

Need more clarity on the reasons for the edit.
Whether it's a valid change as patients condition changes (whether these changes to be tracked or not), or is it a correction due to wrong data entry, or any other reason?

**Comment by SeyiesilieChadi** [comment]
@rithviknishad 
It is a valid change as patients' condition changes the dose and frequency of the medication has to be changed for the same medicine. For example , an antibiotic is given to a critical patient in an 8th hourly manner but as the patient's condition improves, the frequency goes down to twice daily. so if we can have the feature to do that it'll be very helpful.( this feedback is from the nurses and doctors)

**Comment by rithviknishad** [comment]
@aparnacoronasafe @SeyiesilieChadi we have decided to add an edit button, that behind the scenes will discontinue and create a new prescription with the edited attributes.

@aparnacoronasafe just wanted to confirm, whether should we restrict the editing of certain fields (in both normal and PRN cases)

- Medicine will not be editable
- Normal prescription CANNOT be converted to PRN prescription and vice versa via this method.

Should any other fields be restricted from edit?

<img width="1822" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/b3a4b9be-ba5e-4961-866c-e2fa69017add">

<img width="1822" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/cb1cb73d-aff6-4f29-88fb-6f565ff28b6f">

**Comment by aparnaegov** [comment]
> @aparnacoronasafe @SeyiesilieChadi we have decided to add an edit button, that behind the scenes will discontinue and create a new prescription with the edited attributes.
> 
> @aparnacoronasafe just wanted to confirm, whether should we restrict the editing of certain fields (in both normal and PRN cases)
> 
> * Medicine will not be editable- Yes. lets keep it like that
> * Normal prescription CANNOT be converted to PRN prescription and vice versa via this method.- Yes. lets keep it like that
> 
> Should any other fields be restricted from edit?- No. lets not restrict any other field
> 
> <img alt="image" width="1822" src="https://user-images.githubusercontent.com/25143503/271504580-b3a4b9be-ba5e-4961-866c-e2fa69017add.png"> <img alt="image" width="1822" src="https://user-images.githubusercontent.com/25143503/271504650-cb1cb73d-aff6-4f29-88fb-6f565ff28b6f.png">
