### ISSUE TITLE
Categorisation of patients

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6346]
**Is your feature request related to a problem? Please describe.**
In data analysis, it's found that since "Comfort Care" in the patient category is selected in default, there is a much higher number of "Comfort Care" patients than expected. This shows that the nurses are not updating the category as per the patient's condition, and leaving it at the default option of "Comfort Care"

**Describe the solution you'd like**
The Field of Patient Category must be left black with no default selection.
Make the change both in Consultation form and Log Update form

**Comment by Ashesh3** [comment]
EDD: 2nd October, 2023
