### ISSUE TITLE
Whitelabel `jwt_token_refresh_interval`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6361]
- [ ] Add `jwt_token_refresh_interval` to `useConfig`. (Also update here: [coronasafe/care_deploy_configs](https://github.com/coronasafe/care_deploy_configs))
- [ ] Default it to the current value if not specified in `config.json`

https://github.com/coronasafe/care_fe/blob/bebb693d0a8489701059a59272e2bef32723bbe8/src/Providers/AuthUserProvider.tsx#L27

**Comment by kshitijv256** [comment]
I would like to work on it
