### ISSUE TITLE
Medico-Legal Case

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6367]
**Is your feature request related to a problem? Please describe.**
We need to mark an encounter as a "Medico-Legal Case"

**Describe the solution you'd like**

- [ ] Mark an encounter as a "Medico-Legal Case" 
Any encounter (active or closed)  will be marked as a "Medico-Legal Case" 

Have a toggle added at the Patient dashboard (https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/adefe869-7b9a-44ab-bffe-8fb115d8265a/consultation/17ca4172-4b08-404b-934f-b3ad77ae2a6f)  "Is this a medico-legal case?" Yes/No- The default option will be "No"

- [ ] Have filter in patient list to filter patients whose latest encounter is marked as a medico-legal case. The advanced filter to have a new filter added at the end of "Patient details based". 

- [x] #6439

- [ ] Metabase dashboard to have "No. of medico-legal cases" across each hospital.

**Comment by Ashesh3** [comment]
EDD: 9th October
