### ISSUE TITLE
The location picker component is not rendering properly

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#6371]
**Describe the bug**
The location picker component is not renering properly.

**To Reproduce**

1. Go to https://care.ohc.network/facility/de52dfdf-f306-41e3-a854-5110942296ab/update
2. Click on location picker

**Screenshots**

<img width="494" alt="image" src="https://github.com/coronasafe/care_fe/assets/46787056/3c3cabfd-47a2-42e7-8eaa-85b1737f086a">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sriharsh05** [comment]
I want to work on this issue.
