### ISSUE TITLE
🛠️ Replace `useDispatch` w. `useQuery`/`request`: Consultations (`src/Components/Facility/Consultations/**`)

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6372]

**Comment by AshrafMd-1** [comment]
I would like to work on this issue.

**Comment by rithviknishad** [comment]
@AshrafMd-1 any progress on this?

**Comment by AshrafMd-1** [comment]
Just rewriting some files after merges 
and converting the liveFeed.tsx to pagination
that should be done by today
