### ISSUE TITLE
🛠️ Replace `useDispatch` w. `useQuery`/`request`: Facility (Part 1, A-D) (`src/Components/Facility/*`)

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6376]

**Comment by thtauhid** [comment]
@rithviknishad please assign this to me

**Comment by rithviknishad** [comment]
Hey @thtauhid , any updates on this?

**Comment by thtauhid** [comment]
Hi @rithviknishad I am aiming to finish it by tomorrow. Sorry for taking so much time.

**Comment by MjStar24** [comment]
hey @rithviknishad I have started working on this issue... can you assign this to me
