### ISSUE TITLE
Replace useDispatch w. useQuery/request: HCX (src/Components/HCX/**)

### ISSUE THREAD

**Issue by print-Sathvik** [coronasafe/care_fe#6381]
**Is your feature request related to a problem? Please describe.**
Part of #6316

**Comment by vivramkrishna** [comment]
@print-Sathvik are you still working on it? if not @rithviknishad can you please assign me

**Comment by print-Sathvik** [comment]
I had to take leave unexpectedly. I will continue from today.

**Comment by rithviknishad** [comment]
@print-Sathvik any updates on this? Any blockers?

**Comment by print-Sathvik** [comment]
> @print-Sathvik any updates on this? Any blockers?

Yes, I am unable to add insurance details. /payors is giving 501 bad gateway error
 I am taking Khavin's help
