### ISSUE TITLE
🛠️ Replace `useDispatch` w. `useQuery`/`request`: Notifications (`src/Components/Notifications/**`)

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6392]

**Comment by adriansliva** [comment]
Hi can you please assign me this issue?

**Comment by adriansliva** [comment]
sorry for the inactivity but I'm working on it, the solution will be ready in the next few days

**Comment by adriansliva** [comment]
specifically today I will add the first solution

**Comment by shyamprakash123** [comment]
@adriansliva are you still working on this? If not @rithviknishad I would like to work on this, can you assign me?

**Comment by adriansliva** [comment]
@shyamprakash123 im still working on this issue

**Comment by adriansliva** [comment]
I must have this issue because it relates to a subject at the university I am studying at and I can no longer change the role I have chosen. Until recently I didn't have time to solve it, but I have already started working on its implementation. thank you for your understanding @shyamprakash123.

**Comment by adriansliva** [comment]
@rithviknishad I can't push the changes I created in the code
I created my own branch and I'm trying to put what I made into it but it doesn't work. Can you help or advise me thank you

**Comment by rithviknishad** [comment]
@adriansliva You'll have to make the branch in your fork in order to be able to push.

Refer: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by adriansliva** [comment]
Hi @rithviknishad I edited all components in the Notifications folder (change useDispatch). This is my fork https://github.com/adriansliva/issue-6392, and should I now create a branch?

I apologize for the delay in editing the code. Thanks for your answer.

**Comment by rithviknishad** [comment]
Yes. You can now

1. Create the branch
2. Push your changes to the branch
3. Open a PR in this repository from your branch.

**Comment by adriansliva** [comment]
@rithviknishad I created a pull request for the issue. What are the next steps?

**Comment by rithviknishad** [comment]
@adriansliva the PR will be reviewed and QA testing will be done. If any changes are requested, you'll have to follow up on it. Once the `tested` label is added, it'll be merged anytime in the same week.

**Comment by rithviknishad** [comment]
@adriansliva I've reviewed and requested some changes to the PR

**Comment by adriansliva** [comment]
Hi @rithviknishad could I ask you 2 questions. I need to find out information about the project. I need this in the context of creating a presentation for a subject in school in which we had to address an issue. I would be grateful for your answers to these questions if it is within your competence and capabilities.

Question 1 - What DevOps services and tools does your project use? For each tool, please write how it is used in the project.

Question 2 - What was the test coverage like? Provide "covered lines" metrics - absolute or relative (if you measured them).

**Comment by rithviknishad** [comment]
> Question 1 - What DevOps services and tools does your project use? For each tool, please write how it is used in the project.

You can see all the CI/CD actions here: [care_fe/actions](https://github.com/coronasafe/care_fe/actions) and [care/actions](https://github.com/coronasafe/care/actions)

@sainak should be able to provide you links to the deploy docs which you can refer to.

> Question 2 - What was the test coverage like? Provide "covered lines" metrics - absolute or relative (if you measured them).

@adriansliva we don't have "covered lines" metrics for the front-end. However we do have one for the backend, which you can see from here. https://app.codecov.io/gh/coronasafe/care

cc: @nihal467
