### ISSUE TITLE
Prescription activity view grouped by "medicine"

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6395]
Currently, prescriptions that are edited (discontinued and created with the same medicine) are not tracked as a single continuous activity.

Follow-up enhancement of prescription activity timeline introduced in: https://github.com/coronasafe/care_fe/pull/6311

cc: @nihal467

**Comment by nihal467** [comment]
Anyone wishing to work on this issue should discuss the approach and UI during the EOD call or care_general channel before starting to work on it.

**Comment by gigincg** [comment]
With events being fired for Prescriptions the audit trail is available in Care. If required by Users, we could show events filtered by prescription related events and group by medicine in the future
