### ISSUE TITLE
Patient tab export is not working properly

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6406]
**Describe the bug**

- [x] #6414
- [ ] Once you click on created before date, and try to select created after date, it is not getting selected

**To Reproduce**

1. Go to https://care.coronasafe.in/patients?page=1&limit=12&district=&lsgBody=&facility=&facility_type=&date_declared_positive_before=&date_declared_positive_after=&date_of_result_before=&date_of_result_after=&created_date_before=2023-10-03&created_date_after=2023-09-26&modified_date_before=&modified_date_after=&date_of_result=&last_consultation_admission_date_before=&last_consultation_admission_date_after=&last_consultation_discharge_date_before=&last_consultation_discharge_date_after=&category=&gender=&disease_status=&age_min=&age_max=&last_consultation_admitted_bed_type_list=&last_consultation_discharge_reason=&srf_id=&number_of_doses=&covin_id=&is_kasp=&is_declared_positive=&last_consultation_symptoms_onset_date_before=&last_consultation_symptoms_onset_date_after=&last_vaccinated_date_before=&last_vaccinated_date_after=&last_consultation_is_telemedicine=&is_antenatal=&ventilator_interface=
2. Click on export
3. See error

**Expected behavior**

- we should be able to see patient details in the export
- the calendar should be working properly in patient advance filters

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/2a493010-ee60-498c-ae6b-fb6ddfaa6c55)
![image](https://github.com/coronasafe/care_fe/assets/57055998/7883faa5-fa31-4992-b93a-6cc4df060521)
[export_2023-10-06_04_34_28.csv](https://github.com/coronasafe/care_fe/files/12825296/export_2023-10-06_04_34_28.csv)

**Comment by rithviknishad** [comment]
@nihal467 unable to reproduce both issues mentioned

**Comment by rithviknishad** [comment]
Both live and all export is working. Able to modify registered date too without issues.

<img width="1707" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/87c70091-7db1-431c-b619-a34d5f4e2cd9">
