### ISSUE TITLE
Incorrect browser tab page title in Consultation: Medicines Tab

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6425]
**Describe the bug**
Incorrect browser tab page title in Consultation: Medicines Tab

**To Reproduce**

1. Go to a patients consultation dashboard
2. Switch to medicines tab

**Expected behavior**
Page title should be: "Medicines | CARE" similar to how other tabs are.

**Screenshots**
<img width="1710" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/d195b9e6-d31a-4b9b-aaa2-25d6db15606a">

**Additional context**

**Comment by AshrafMd-1** [comment]
i would like to work on this issue
