### ISSUE TITLE
Prescription: Titrated drug dose

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6432]
**Is your feature request related to a problem? Please describe.**
Dosage in prescription may be Titrated.  Especially in ICUs, a lot of medicines tend to have intense side effects and must be administered in precise dosage based on the patient's present condition.

Dosage titration allows doctors to instruct the administration of medicine with an Initial dosage and a target dosage based on parameters set by the doctor. The nurse will start administration as per the initial dosage and slowly increase/decrease dosage to the target dose closely monitoring the patients condition, strictly following the doctors instructions.

Eg: Medicine XYZ, to be administered every 1 hour and the dosage to be titrated between 10 mg to 50mg. And instruction on titration may be "increase dosage by 10mg with each administration maintaining Heart rate of the patient below 90 bpm. If heart rate goes above 90, donot increase dosage, continue at the previous dosage till heart rate falls below 90, then continue increasing dosage"

**Describe the solution you'd like**

**Make the following changes in the Prescription** (https://deploy-preview-6396--care-net.netlify.app/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/85497ba2-3319-4acc-829a-d116e8b3136a/consultation/e356715b-5fd3-4cfc-ab45-d64509cb7cb2/prescriptions)

- [ ] before field for dosage, add a checkbox for "Titrate Dosage"
- [ ] When the checkbox is selected, The field for Dosage will be replaced with "Start Dosage" and "Target Dosage"
- [ ] When the checkbox is selected, also add a field for "Instruction on titration" after the "frequency" field. 

**Make the following changes in Medicine Administration Record** (https://deploy-preview-6396--care-net.netlify.app/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/85497ba2-3319-4acc-829a-d116e8b3136a/consultation/e356715b-5fd3-4cfc-ab45-d64509cb7cb2/medicines)
- [ ] When administration is selected for a prescription with Titrated dosage, the administration form shall have field for "Dosage" for the nurse to enter the dosage of medicine administered. 
- [ ] The field title for the "Dosage" field must also show the "Start Dosage" and "Target Dosage". Eg: "Dosage (10mg-50mg)". This will help the nurse dose the administration appropriately. 
- [ ] Also show the "Last administered Dosage" and "Last administered time" along with the other details of the prescription

**Comment by gigincg** [comment]
@aparnacoronasafe 

Based on some minimal research, FHIR seems to represent the min-dosage as dosage itself & the target dosage as maxDosage. I'm concerned about the terms we use here. Could you please comment.


@rithviknishad Please attach the FHIR JSON for Titrated Dosages

```json
{
  "resourceType": "MedicationRequest",
  "id": "titration-example",
  "status": "active",
  "intent": "order",
  "subject": {
    "reference": "Patient/123"
  },
  "medicationCodeableConcept": {
    "coding": [{
      "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
      "code": "XYZ",
      "display": "Medicine XYZ"
    }]
  },
  "dosageInstruction": [{
    "text": "Administer every 1 hour. Start with 10mg, increase dosage by 10mg with each administration maintaining Heart rate of the patient below 90 bpm. If heart rate goes above 90, do not increase dosage, continue at the previous dosage till heart rate falls below 90, then continue increasing dosage.",
    "timing": {
      "repeat": {
        "frequency": 1,
        "period": 1,
        "periodUnit": "h"
      }
    },
    "doseAndRate": [{
      "doseQuantity": {
        "value": 10,
        "unit": "mg",
        "system": "http://unitsofmeasure.org",
        "code": "mg"
      },
      "type": {
        "coding": [{
          "system": "http://terminology.hl7.org/CodeSystem/dose-rate-type",
          "code": "titrated"
        }]
      }
    }],
    "maxDosePerPeriod": {
      "value": 50,
      "unit": "mg",
      "system": "http://unitsofmeasure.org",
      "code": "mg"
    }
  }]
}

```

**Comment by aparnacoronasafe** [comment]
@gigincg @rithviknishad @GokulramGHV 

Why I insist on having "start dose and target dose" and NOT min dose and max dose is because :

Titration is of 2 kinds. Up-titration and down-titration. Up-titration is when medicine dosage is slowly increased, and down-titration is when patient is being veined off a medication. In the former, the user is moving dosage from min to max, while in the later the reverse. Hence for users indicating dosage as Min and max may be confusing.

To know more on Drug Titration, you may refer to the scientific paper; https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7967860/

**Comment by GokulramGHV** [comment]
@aparnacoronasafe Should I change the existing "Notes" field to "Instruction on titration" for a titrated prescription, or do we need both the "Notes" and "Instruction on titration" fields for a titrated prescription?

**Comment by aparnacoronasafe** [comment]
@GokulramGHV Please create a new field for "Instruction on titration" and retain "Notes" as well.

**Comment by GokulramGHV** [comment]
@aparnacoronasafe Should I create a separate table in the discharge summary for titrated prescriptions or should I incorporate the titrated prescription fields along with the regular prescriptions table?

cc: @rithviknishad

**Comment by aparnacoronasafe** [comment]
Separate table is not needed. 

Dosage column may just show

5mg to 10mg
Instruction on titration

Is something like this possible?
