### ISSUE TITLE
MEWS

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6433]
Issue to be taken up once https://github.com/coronasafe/care_fe/issues/6434 is closed.

**Is your feature request related to a problem? Please describe.**
MEWS Scoring system is a well regarded method of assigning score to rate the condition of a patient in the ICU.

A summary of how the MEWS is calculated is available below:
<img width="606" alt="Screenshot 2023-10-06 at 9 05 14 AM" src="https://github.com/coronasafe/care_fe/assets/67050716/5d429898-21e7-421f-8218-e5d98c14d996">

**Describe the solution you'd like**

<img width="1425" alt="Screenshot 2023-10-10 at 9 38 06 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/8da8e609-066e-465d-bb6f-07d00c46b0e8">

- [ ] Add a section in the patient dashboard for MEWS

- [ ] When all the parameters in the MEWS calculator is logged in the CARE system within 30min, then the system automatically calculates the MEWS based on the above calculation.
If one of the parameters is not updated in the system, then, the dashboard will simply show option to Calculate MEWS

- [ ] When the user clicks on the option to "Calculate" MEWS, Open up a pop-up window with the relevant parameters. When the user fills it out, the data is saved as a new Logupdate.

- [ ] If one or more of the Parameters are already filled out in any log update within the last 30 min, the pop-up window will be auto-filled with those values. 

- [ ] When MEWS is calculated and shown in the patient dashboard, colour code the section based on the colour coding on the MEWS calculator

- [ ] Show the latest MEWS on the Patient list on the respective patient cards

**Comment by AshrafMd-1** [comment]
Hi @nihal467 can you assign me this issue.

**Comment by nihal467** [comment]
- [ ] Calculate it only if all the data is available. If it's unavailable, mention why it can't be calculated.
- [ ] Perform the calculation in the front-end only.
- [ ] Do not create a calculate button to do it manually.

@aparnacoronasafe @AshrafMd-1 

_Discussion note on 27/11/2023 - Engineering Call_
