### ISSUE TITLE
Export Icon: Patient and facility list

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6438]
**Is your feature request related to a problem? Please describe.**
In facility list (https://care.coronasafe.in/facility) and patient list (https://care.coronasafe.in/patients), there is export option on top right corner of the screen. However, the icon on the export button is a "Download/import Icon"

**Describe the solution you'd like**
Replace the icon with a better Icon for "Export" that is consistent with the design of CARE

**Comment by shyamprakash123** [comment]
I would like to work on this issue, can you assign me to this?

**Comment by Ashesh3** [comment]
> I would like to work on this issue, can you assign me to this?

Sure, I've assigned you.
