### ISSUE TITLE
Add feature to "export entire patient file" in the patient dashboard

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#6439]
Refer to the linked issue for context: https://github.com/coronasafe/care_fe/issues/6367#issue-1918621797

Add a new option to patient dashboard to export the medical records for particular encounter
- The user must get a complete dump of all medical records within that encounter.

**Comment by Ashesh3** [comment]
Discussed on EOD call to mark this as wishlist as it's not an immediate requirement.

**Comment by gigincg** [comment]
To be taken up after HMIS Requirements
