### ISSUE TITLE
Patient Advance Filters are over crowded

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6445]
<img width="959" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/18f5555b-9fe9-4af3-8295-434cebef0f7c">

- [ ] there is a lot of advance filters in the patient tab, we should be looking into the relevance and hide/reorder to have better UX experience

**Comment by aparnaegov** [comment]
We have already re-ordered based on relevance and grouped them.

What we could do is remove the covid specific filters.

@gigincg What do you think?

**Comment by nihal467** [comment]
non-relevant to current develop
