### ISSUE TITLE
Pressure Sore popup does not close when clicked outside

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6446]
**Describe the bug**
Pressure Sore popup does not close when clicked outside

**To Reproduce**

1. Go to a patient's consultation dashboard
2. Open the "Pressure Sore" tab
3. Open a popup and attempt to click outside

**Expected behavior**
The popup should close onBlur/click outside.

Consider using headlessui's Popover component instead which would out of the box handle onBlur/click outside (and for consistent behaviour across other popover usages)

**Screenshots**
<img width="1822" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/ab2a7e65-e40f-4a46-8a14-6a5bbd7b1993">

**Comment by thedevildude** [comment]
Hi, can you please assign me this issue?
