### ISSUE TITLE
Redirect to Original URL After Session Expiry and Re-login

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#6486]
**Issue:**

Currently, when a user's session expires on a specific page, they are correctly redirected to the "Session Expired" page which subsequently leads them to the login page. However, after re-logging in, instead of being redirected to their last active page (where their session had expired), they are taken to the home page. This disrupts user flow and can lead to confusion or a poor user experience.

**Expected Behavior:**

Upon re-login after a session expiry, users should be redirected to the URL of their last active page, thereby preserving the context of their work or activity.

**Steps to Reproduce:**
1. Navigate to any page in the application.
2. Wait for the session to expire.
3. You'll be redirected to the session expired page.
4. Proceed to the login page.
5. After logging in, observe that you're taken to the home page instead of the page where the session had originally expired.

**Potential Solution:**

Preserve the URL of the page where the session expires and utilize this URL to redirect the user post re-login.

**Comment by AshrafMd-1** [comment]
I would like to take up this issue .

**Comment by Ashesh3** [comment]
> I would like to take up this issue .

Assigned it to you.
