### ISSUE TITLE
Header buttons are clipping the Patient Dashboard title

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#6488]
**Describe the bug**
The buttons on top of the Patient Dashboard are clipping the page title on smaller screens

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/80e47d10-9ed8-4193-ade6-d69aa45999e9/consultation/b81e5e1f-fd11-4b38-aa51-14bea5583c76
2. Reduce the width of the page
3. See the issue with the header bar at the top

**Expected behavior**
The buttons should not clip the text, they should rearrange themselves somewhat like this:
![image](https://github.com/coronasafe/care_fe/assets/3626859/0fe26251-c034-4d19-9a8d-c1d7410de6a3)

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/3626859/4b90ea87-17af-4eba-b100-e6c14f3a8c9f)

**Comment by Ashesh3** [comment]
@Omkar76 comment on this issue so that I can assign you.

**Comment by Omkar76** [comment]
assign me. thanks
