### ISSUE TITLE
Show loading state for fetching asset locations in Asset Import

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#6489]
In the Asset Import modal, the loader for when the locations are still being fetched does not work anymore.. 
Functionality for `setLocationsLoading` was removed. We need to add back the loading state.

Refer to this change for more info:

https://github.com/coronasafe/care_fe/pull/6374/files#diff-abdb9a86f18dd154c547c5b8884c695e30d12d0e9b8775bbff93cdcfcd7b6132L48

_Originally posted by @Ashesh3 in https://github.com/coronasafe/care_fe/pull/6374#discussion_r1371259181_

**Comment by shyamprakash123** [comment]
I want to work on this, assign me

**Comment by Ashesh3** [comment]
> I want to work on this, assign me

You are assigned.

**Comment by shyamprakash123** [comment]
@Ashesh3 `setLocationsLoading` is removed and in place of that `loading` variable of `useQuery` is used to handle the loading state. If I'm wrong correct me. Can you provide a screenshot of the problem for a better understanding?

**Comment by Ashesh3** [comment]
> @Ashesh3 `setLocationsLoading` is removed and in place of that `loading` variable of `useQuery` is used to handle the loading state. If I'm wrong correct me. Can you provide a screenshot of the problem for a better understanding?

I noticed that this issue was just fixed with rithviknishad in this PR: https://github.com/coronasafe/care_fe/pull/6494/ . Closing this issue as resolved.
