### ISSUE TITLE
Responsiveness Issue in Facility List Page / Facility Card

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6502]
**Describe the bug**
In some sizes, there are a couple of responsiveness issues with the facility list page

- [ ] Facility cover image does not have a min-width set. As you can see in the attached screenshots, the facility cover image is invisible in one of them, although for ones that do not have a cover image set, the placeholder image is shown fine.
- [ ] View CNS buttons need to be aligned to the top right always (`sticky top-[x] right-[x]`)
- [ ] The buttons at the bottom panel should be wrapped if overflowing.

**Screenshots**
<img width="1822" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/aab1e93f-3e74-435a-b8e4-39a79424f656">

<img width="1822" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/14bbcdec-3259-4904-ba91-5cbb035ee0fd">

**Comment by shyamprakash123** [comment]
I would like to work on this, can you assign me?
