### ISSUE TITLE
Show more monitors in CNS on very large displays

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6503]
**Describe the bug**
When CNS is opened in large 4K displays, 75% of the screen space is wasted. 

**To Reproduce**

1. Visit https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/cns on a 4K display

**Expected behavior**
On large displays, render more vitals monitors into view per page.

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/25143503/98f9e3f9-7e20-42ce-a095-5abe841e88c6)

**Comment by kshitijv256** [comment]
9 monitors if available should be fine in this size screen i guess
or maybe increase the size of monitors  to use most of screen with same no. as it is

I would like to work on it.

**Comment by ayush-seth** [comment]
I can pick this up if still required

**Comment by MjStar24** [comment]
hey @nihal467 I would like to work on this can you assign this to me

**Comment by MjStar24** [comment]
hey @rithviknishad when I am clicking on the above it is showing no data found

![Screenshot 2024-03-18 173337](https://github.com/coronasafe/care_fe/assets/118470362/b5f9dfc5-9d68-4cca-8283-e118a57609e6)

**Comment by rithviknishad** [comment]
Try logging in as `devdistrictadmin` `Coronasafe@123` instead.

**Comment by MjStar24** [comment]
thanks @rithviknishad its working!

**Comment by MjStar24** [comment]
hey @rithviknishad I have raised the pull request for this issue 

what I have done : 

-by default 6 monitors will displayed per view page for small screens
-for large screens 9 monitors will be displayed per view page for 4k displays 
-for this I have used window.resize and react hooks to check the display size and change number of monitors according to display size

**Comment by nihal467** [comment]
@MjStar24 Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by i0am0arunava** [comment]
@nihal @rithviknishad ,I would like to work on this ,can you please assign it to me?

**Comment by i0am0arunava** [comment]
@rithviknishad , https://deploy-preview-6396--care-net.netlify.app/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/cns](https://deploy-preview-6396--care-net.netlify.app/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/cns)  is not working provide from where have you taken this scrrenshoot ? can I find it here https://care.ohc.network/users/add

**Comment by rithviknishad** [comment]
https://github.com/ohcnetwork/care_fe/issues/6503#issuecomment-2003748444

**Comment by i0am0arunava** [comment]
@rithviknishad ,after login with this devdistrictadmin Coronasafe@123   help?

![Image](https://github.com/user-attachments/assets/bfd08cff-1b21-4527-8dcd-f851891a7825)

**Comment by rithviknishad** [comment]
Read steps to reproduce mentioned in issue; the link with that credentials should show monitors.

**Comment by i0am0arunava** [comment]
@rithviknishad ,is this issue solved already?

![Image](https://github.com/user-attachments/assets/789a6eda-06cd-4da7-a7e5-f0c43c91bcf3)

**Comment by rithviknishad** [comment]
as you can see in the screenshot even you've attached, there's a lot of blank space. let's increase the grid columns to whichever fits and increase the number of monitors per page for 4k displays

**Comment by rithviknishad** [comment]
@i0am0arunava any updates on this?

**Comment by i0am0arunava** [comment]
> [@i0am0arunava](https://github.com/i0am0arunava) any updates on this?

Working

**Comment by i0am0arunava** [comment]
@rithviknishad ,raised a pr please check ,https://github.com/ohcnetwork/care_fe/pull/9013
