### ISSUE TITLE
User signout flow is mafunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6504]
**Describe the bug**

When we click 'sign out' in the care system, we experience a delay of 1-2 seconds on the facility tab before successfully logging out and returning to the login page.

**To Reproduce**

1. Go to https://care.ohc.network/
2. sign in with any credentials and click signout
3. See error that you are seeing the facility tab

**Expected behavior**

it should be showing loader before signing out 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/cdcbd93e-ae5e-4f13-86f2-f721be26848b)

**Comment by shyamprakash123** [comment]
I want to work on this, can you assign me?

**Comment by rithviknishad** [comment]
This issue has come back alive due to a incorrect merge conflict resolution
