### ISSUE TITLE
Add Page loader to the asset list tab

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6505]
**Describe the bug**

When we load the asset list tab, the page shows no asset rather than a page loader

**To Reproduce**

1. Go to https://care.ohc.network/assets
2. See error

**Expected behavior**

when we load the asset list tab, the page should be showing a page loader

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/2e5006f9-1dc0-44a8-840a-40b17ffceb9c)

**Comment by shyamprakash123** [comment]
I want to work on this. Can you assign me?

**Comment by nihal467** [comment]
@shyamprakash123 what is the status on this issue

**Comment by shyamprakash123** [comment]
@nihal467 I've started working on it. I will make a PR in a couple of days.
