### ISSUE TITLE
Abha Profile download is not working properly

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6508]
**Describe the bug**

- The download button for the Abha profile is not working properly
- anyone can download it easily, shouldn't we log it somewhere, who all downloaded the profile

**To Reproduce**

**Expected behavior**

- 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/e2d11a4a-36ea-450b-ac53-73ee13024a8b)

**Comment by khavinshankar** [comment]
@nihal467 The download feature will not work after 3 days of linking the ABHA number, this is because, the refresh token expires. We have to add a flow to re-login the user. 

I will take it up after the M3 integration is done.
