### ISSUE TITLE
Insurance details: make visible

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6517]
**Is your feature request related to a problem? Please describe.**
Currently the insurance details entered by the user is not visible on any of the pages.

**Describe the solution you'd like**
- [ ] Create a card for "insurance details" in patient details page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/85497ba2-3319-4acc-829a-d116e8b3136a)
- [ ] Add "Insurer name" in patient export sheet (https://care.coronasafe.in/patients)

**Comment by vivramkrishna** [comment]
I would like work on it, can you please assign me

**Comment by vivramkrishna** [comment]
Hello @aparnacoronasafe 

I have added insurance details to the patient’s details page. However, I noticed that we can add multiple insurance details (e.g., Insurance Details 1, Insurance Details 2, Insurance Details 3, etc.).

I have a few questions regarding this:
- How would you like these multiple insurance details to be displayed on the patient’s details page? I have attached some images of my implementation for your reference.
- Initially, I thought of adding a simple card in the same row as the location details and medical details. However, only one insurance detail can be added in this row. If no insurance details are present, should I display a message stating that no insurance details are recorded or simply not show the card?
- What should be done if there are multiple insurance details? If the next detail is displayed in the next row, it may lead to wastage of space.
- Could you clarify how the four details (Member ID*, Policy ID/Policy Name*, Insurer ID, Insurer Name) should be aligned in the card Member ID* and Policy ID/Policy Name* are mandatory while Insurer ID and Insurer Name are not.



![image](https://github.com/coronasafe/care_fe/assets/101407963/5ecc5332-8082-4e6b-9362-d805e240a784)
![image](https://github.com/coronasafe/care_fe/assets/101407963/45271902-994f-4f6a-9b6f-0f877db2ceac)
![image](https://github.com/coronasafe/care_fe/assets/101407963/10b3a0fc-8015-450e-8269-b77abac274e8)
![image](https://github.com/coronasafe/care_fe/assets/101407963/724f80ab-c880-412e-9576-6c780188fd61)

**Comment by rithviknishad** [comment]
We could have a section with heading "Insurance Policies" and show a list of cards maybe.

**Comment by vivramkrishna** [comment]
@aparnacoronasafe @rithviknishad 


![image](https://github.com/coronasafe/care_fe/assets/101407963/d1e2245f-6af6-4f97-9560-c79b5c4c1e81)
![image](https://github.com/coronasafe/care_fe/assets/101407963/c43b626d-f0e9-4f43-9129-6a4a1bd4c16d)
![image](https://github.com/coronasafe/care_fe/assets/101407963/a792b512-6843-45b9-bef7-d8276dde1ca7)

**Comment by vivramkrishna** [comment]
I think this approach can reduce space wastage.

**Comment by aparnacoronasafe** [comment]
@nihal467 why does the implementation look nothing like the images above? @konavivekramakrishna

**Comment by nihal467** [comment]
![image](https://github.com/coronasafe/care_fe/assets/57055998/df49bfef-70ad-4162-83dd-b5e18c121414)
![image](https://github.com/coronasafe/care_fe/assets/57055998/309841af-21d5-4505-95db-e172a68ff73e)
![image](https://github.com/coronasafe/care_fe/assets/57055998/bd0ef5d5-d8fe-4df7-946c-7792e1ae88af)

@aparnacoronasafe After the discussion during the EOD call, the screenshot above was approved design as an effective way of handling spaces on the patient detail page.
