### ISSUE TITLE
Pop-up for selection of facility, redundant 

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6518]
**Describe the bug**
When a user has access to only 1 facility, and he/she goes to patient page (https://care.coronasafe.in/patients) and tries to register a new patient by clicking on "+ Add patient details", a pop-up window to select the facility the patient is admitted to appears. Such pop-up window is redundant since the user can anyway only choose the one facility he has access to.

Desirable flow: The pop-up window for user to select facility must only appear for users that have access to more than one facility.

**To Reproduce**

1. Login with the username "test-staff123", pass: Lilo@123
2. Note that the user has access to only 1 facility
3. Click on 'patients' in side nav menu
4. Click on "+ Add patient details"
5. See the pop-up window to select facility and the dropdown has only 1 option.

**Expected behaviour**
The user upon clicking "+ Add patient details" must be taken to the patient registration form, since it is obvious that the patient is being admitted to the only facility that the user has access to.

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign this to me.

**Comment by AnuMessi10** [comment]
Hi @aparnacoronasafe, I am new to this and would like to contribute, let me know if you can assign this to me. Cheers!

**Comment by Ashesh3** [comment]
> Hi @aparnacoronasafe, I am new to this and would like to contribute, let me know if you can assign this to me. Cheers!

Just a heads up, @sriharsh05  had already requested this issue first, so we're going to assign it to them. But there are plenty of other issues up for grabs. Thanks for understanding!

**Comment by AnuMessi10** [comment]
> > Hi @aparnacoronasafe, I am new to this and would like to contribute, let me know if you can assign this to me. Cheers!
> 
> Just a heads up, @sriharsh05  had already requested this issue first, so we're going to assign it to them. But there are plenty of other issues up for grabs. Thanks for understanding!

No issues, let me know if @sriharsh05 needs any help with this.

Meanwhile I will definitely explore other interesting issues 😁
