### ISSUE TITLE
Asset uptime and downtime is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6524]
In a facility called JNIMS, the camera-2 , is showing asset availability down, and the feed is not been showing in the asset preview but when we go to any of the patient consultation page, which this camera is linked, the feed is visible in the consultation page.

**Comment by khavinshankar** [comment]
When the asset was deleted and recreated, the asset uptime started working correctly.

Closing this issue as done, incase if this issue persists, feel free to reopen this issue or create a new issue.


cc: @nihal467
