### ISSUE TITLE
Bed number coming up two time in patients page 

### ISSUE THREAD

**Issue by dpnkr1** [coronasafe/care_fe#6525]
**Describe the bug**
In Assam CARE website in the patients page/view patients page in any facility where the list of all the patients comes up the bed number is coming up two time like "Bed 5 Bed 5" "Bed 4 Bed 4".

**To Reproduce**

1. Go to 'CARE website'
2. Click on 'Click on patients or view patients for any facility'
3. The patients list will come up there you see the same bed nos are coming up twice.

**Expected behavior**
It should show "ICU Bed 1"  "ICU Bed 4" "ICU Bed 5"

**Screenshots**
![WhatsApp Image 2023-10-30 at 18 32 15_1fb8618b](https://github.com/coronasafe/care_fe/assets/132548965/e725d94d-ab90-401e-95c2-c117e78eca3d)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]
- Version [Version 118.0.5993.118 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**

- Device: [Mi Note 10]
- OS: [Android]
- Browser [Chrome]
- Version [118.0.5993.1111]

**Additional context**
In computer system you might not see the issue bcoz in computer system it will show "ICU BED 1..." "ICU BED 2..." "ICU Bed 4..." but those "...." is the repeated bed numbers but in mobile devices it is clear.

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Can you assign this to me?

**Comment by rithviknishad** [comment]
@AshrafMd-1 this is a P1 issue, could you push it by a day or two?

**Comment by AshrafMd-1** [comment]
Yes, I will be able to.

**Comment by AshrafMd-1** [comment]
@rithviknishad done.
