### ISSUE TITLE
Image of hospital is not showing.( Care Meghalaya)

### ISSUE THREAD

**Issue by salgra108** [coronasafe/care_fe#6534]
**Describe the bug*
The image of the hospital doesn't show in care even if it is uploaded with precise requirements.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khavinshankar** [comment]
@salgra108 I can't seem to reproduce this issue in staging, can you please record a short clip of the process, or snap a screenshot and share it here. 

cc: @nihal467

**Comment by salgra108** [comment]
@nihal467 Thank you so much
