### ISSUE TITLE
Hide Camera Feed button for all users other than doctors and district admin and above

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6539]
**Describe the bug**

Even though currently, we restricted the staff user-id to view the patient camera feed, the camera feed button is still visible for the patient with staff user-id

**To Reproduce**

1. Go to any patient with camera linked to them
4. See error on the top right side

**Expected behavior**

Hide Camera Feed button for all users other than doctors and district admin and above

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/848383a9-5d98-4c83-bd36-f2577f28b089)

**Comment by shyamprakash123** [comment]
I want to work on this issue. Can you please assign me?

**Comment by nihal467** [comment]
@shyamprakash123 it is already assigned to @Ashesh , feel free to take other issues
