### ISSUE TITLE
Limiting Access Control of Camera Feed and configuration to Multiple User type

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6542]
- the State Admin and District Admin have access to the camera feed on the patient consultation page and can configure the camera asset.
- Doctors have access to the camera feed on the patient consultation page and can only create presets on the asset configuration page.

However, there are multiple user types for which we need to determine whether to provide access to the patient camera feed & Asset configuration page:

1. State Read Only Admin
2. State Lab Admin
3. District Lab Admin
4. District Read Only Admin

**Comment by aparnaegov** [comment]
No access for all. 

Lets not even allow them to view camera. We need to be conservative with camera access
