### ISSUE TITLE
Make principal diagnosis as dropdown instead of having mark as principal button on each diagnosis.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6544]
<img width="891" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/e11fd230-dfdd-45fd-9c61-48ec8961ff4f">

**Comment by jainvedant392** [comment]
Hello @rithviknishad, I would really love to contribute to and solve this issue, as I am familiar with the tech-stack and the required frontend to solve this issue. So could you please assign me this issue?

**Comment by rithviknishad** [comment]
Hey @jainvedant392 this PR is related to the PR: https://github.com/coronasafe/care_fe/pull/6528

Will assign you once it is merged.

**Comment by rithviknishad** [comment]
Meanwhile have a look at other issues at: https://github.com/coronasafe/care_fe/contribute

**Comment by jainvedant392** [comment]
Yeah sure @rithviknishad, thanks a lot

**Comment by jainvedant392** [comment]
> Meanwhile have a look at other issues at: https://github.com/coronasafe/care_fe/contribute

Sure
