### ISSUE TITLE
🛠️ Replace `useDispatch` w. `useQuery`/`request`: Patient (`src/Components/Patient/**`)

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6546]

**Comment by vivramkrishna** [comment]
I would like work on this, can you please assign me

**Comment by rithviknishad** [comment]
@konavivekramakrishna You've 2 issues assigned to you already that are not completed yet (1 has no PR, 1 has changes requested to be followed up) 

https://github.com/coronasafe/care_fe/issues/assigned/@me

Feel free to take up the issues once they are completed.

**Comment by krushn-a** [comment]
Hi @rithviknishad, I would like to work on this issue.

**Comment by krushn-a** [comment]
Hi @rithviknishad from the past 3 days i was going through the files of patient folder and some references related to this type of issue, I am facing a bit problem that is i couldn't able to understand how could i come up with code by which i can replace usedispatch() usage from files. So please if you could help me with me it...

**Comment by rithviknishad** [comment]
Hey @krushn-a, feel free to look at the documentation https://github.com/coronasafe/care_fe/issues/6316 and the example PRs attached in the same issue.

This issue will have 17 files to be changed. Feel free to break this issue further down to multiple sub-tasks, and have multiple PR's so that it'd be easier to review and test (also to steer away from having merge conflicts). Have around 1-3 files changed at a time in a single PR.

**Comment by rithviknishad** [comment]
Hey @krushn-a 
Were you able to get back at this? Are you facing any blockers?

**Comment by krushn-a** [comment]
I working on it and am really trying my best. Just need some more time.

**Comment by vivramkrishna** [comment]
@rithviknishad can you please assign this to me
