### ISSUE TITLE
Vitals Monitor: Improving how monitor related info is shown in mobile view

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6549]
**To Reproduce**

1. In mobile view, open: https://care.ohc.network/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/85497ba2-3319-4acc-829a-d116e8b3136a/consultation/e356715b-5fd3-4cfc-ab45-d64509cb7cb2
2. See the Vitals monitor's top bar

**Expected behavior**
<img width="391" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/33a455f2-32d9-4fef-b240-38be74c84dc2">

**Screenshots**
<img width="392" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/ac1ceb67-4a9f-4e63-bea1-750c3553832d">

**Comment by shyamprakash123** [comment]
I want to work on this issue, can you please assign me.
