### ISSUE TITLE
Asset List Tile: Non-uniform height

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6550]
**Describe the bug**
In the asset list page, the tile heights are of non-uniform heights.

**To Reproduce**

1. Go to asset list page.

**Expected behavior**
The asset tiles should be of uniform height
<img width="683" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/42ca8a35-c170-42f1-a97e-7aa44238a9af">

**Screenshots**
<img width="700" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/abe252af-04e7-4f47-a521-f26d55eaef25">

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign it to me.

**Comment by rithviknishad** [comment]
@sriharsh05 you've an issue that is assigned to you and pending changes. Feel free to take up once it's cleared.

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Please assign it to me.

**Comment by rithviknishad** [comment]
@AshrafMd-1 you have an issue that is pending changes. Feel free to take up the issue once it's cleared.

Check: https://github.com/coronasafe/care_fe/issues/assigned/@me

**Comment by shyamprakash123** [comment]
@rithviknishad can I work on this?
