### ISSUE TITLE
Configure Facility: Add max width constraint to the cards.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6551]
**Describe the bug**
The cards in the facility configure page seem to be too wide in desktop view.

**To Reproduce**

1. Go to Facility Configure page ([link](https://care.ohc.network/facility/df1a22fb-1875-4949-af85-15d1917b8bfd/configure))

**Expected behavior**
<img width="1039" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/9937a3c0-879c-4425-b945-f4191a56a518">

**Screenshots**
<img width="1707" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/6a6d702b-7d8d-452b-876b-33c3f12c4d67">

**Comment by vivramkrishna** [comment]
I would like work on it, can you please assign me
