### ISSUE TITLE
Configure Facility: Unnecessary multiple cancel buttons present

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6552]
**Describe the bug**
On the configure facility page, there are two cards and each has its own cancel button although both do the same behaviour-wise.

**To Reproduce**

1. Go to the configure facility page.

**Expected behavior**
Remove the cancel button in favour of the back button, or have only one cancel button.

**Screenshots**
<img width="594" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/afe437e8-b163-4ddf-bbc9-19a48282bf1c">

**Comment by KshitijTodkar48** [comment]
I want to do it. Please assign this to me.

**Comment by KshitijTodkar48** [comment]
And please check if this is ok?
![Screenshot 2023-11-09 163609](https://github.com/coronasafe/care_fe/assets/120639775/6e428da0-1a6f-4859-9008-06ef08593e81)

**Comment by rithviknishad** [comment]
The back button would suffice I guess. Let's remove both. cc: @nihal467

**Comment by KshitijTodkar48** [comment]
Is this good @rithviknishad ?
![Screenshot 2023-11-09 193031](https://github.com/coronasafe/care_fe/assets/120639775/3fbe10f5-6bfa-4668-8638-3f1b6cb037c0)

**Comment by rithviknishad** [comment]
I mean, there is a back button at the top left already right? That'd be enough.

**Comment by KshitijTodkar48** [comment]
Sorry, I don't know how I missed that. 😅
