### ISSUE TITLE
Opening Investigations or Treatment Summary from Consultation Dashboard causes CARE app to reload.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6554]
**Describe the bug**
When opening the investigation summary or treatment summary from the consultation dashboards show more dropdown, the CARE app loads again entirely.

**To Reproduce**

1. Go to a consultation dashboard ([link](https://care.ohc.network/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/80e47d10-9ed8-4193-ade6-d69aa45999e9/consultation/b81e5e1f-fd11-4b38-aa51-14bea5583c76))
2. Open Investigations or Treatment summary
3. Notice that the CARE app reloads entirely.

**Expected behavior**
hen opening the investigation summary or treatment summary from the consultation dashboards show more dropdown, the CARE app should not load again entirely. It should be a `Link` or `navigate` instead of `<a>`.

**Screenshots**
<img width="368" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/c89fc6df-6092-4061-95f5-ab16df6e85dc">

**Comment by shyamprakash123** [comment]
I want to work on this issue, can you please assign me.

**Comment by rithviknishad** [comment]
@shyamprakash123 you've an issue assigned with you that has no linked PR yet. Feel free to take up once your other assigned issues are completed. 

https://github.com/coronasafe/care_fe/issues/assigned/@me

**Comment by shyamprakash123** [comment]
> @shyamprakash123 you've an issue assigned with you that has no linked PR yet. Feel free to take up once your other assigned issues are completed. 
> 
> https://github.com/coronasafe/care_fe/issues/assigned/@me

Ok, can I take issues, when all my issues are linked with PR's?

**Comment by rithviknishad** [comment]
Yes as long as it is linked and no pending changes required for those PRs

**Comment by shyamprakash123** [comment]
Understood, thank you.

**Comment by shyamprakash123** [comment]
@rithviknishad can you assign this to me now?
