### ISSUE TITLE
Consultation Camera Feed: Improve rounded borders of preset buttons

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6555]
**Describe the bug**
The rounded borders for the presets in the camera feed doesn't look good. It has `rounded` when active, and `rounded-none` when inactive.

**To Reproduce**

1. Go to a consultation page and open the camera feed

https://care.ohc.network/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/80e47d10-9ed8-4193-ade6-d69aa45999e9/consultation/b81e5e1f-fd11-4b38-aa51-14bea5583c76/feed

**Expected behavior**
Instead, it should be `first:rounded-l last:rounded-r`
<img width="1186" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/83b08485-3880-4e35-94ac-45477cb0f118">

**Screenshots**
<img width="1158" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/51fbf850-5427-4be4-be72-70f5c757d115">

**Comment by Omkar76** [comment]
@rithviknishad You can assign this to me. Thanks.
