### ISSUE TITLE
Multiple duplicate API requests dispatched to fetch resource comments

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6556]
**Describe the bug**
3 duplicate API requests are dispatched to fetch resource comments with different pagination limits for the same resource in resource details page.

**To Reproduce**

1. Go to a resource details page ([link](https://care.ohc.network/resource/df18360c-5cb8-446b-b981-9452beafce14))
2. See network tab

**Expected behavior**
Only 1 API request should be dispatched to fetch the comments in the resource details page.

**Screenshots**
<img width="1715" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/8ab14498-cf59-4b55-8858-2cd3a6121784">

**Comment by vivramkrishna** [comment]
This issue is due to before we don't have refetch in PaginatedList, now it got fixed I would like to work on this
