### ISSUE TITLE
Make "view facility" , "View Patient" and "Notice" buttons right aligned in facility card

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6560]
**Describe the bug**

"view facility" , "View Patient" and "Notice" buttons are left aligned in the facility card

**To Reproduce**

1. Go to https://care.coronasafe.in/facility
2. See error

**Expected behavior**

only move the "view facility" , "View Patient" and "Notice" buttons to the right side of the facility card

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/452e755b-940f-4f38-8f24-19de70c605fe)

**Comment by vivramkrishna** [comment]
I would like to work on this can you please assign me
