### ISSUE TITLE
Discharge Reason is marked Unknown for transferred patients

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6593]
**Description of bug**

A patient is admitted to one facility, and without discharging the patient from the initial facility, the destination facility transfers the patient using the patient transfer function on the patient registration page. The patient will be auto-discharged from the initial facility with the discharge reason 'UNKNOWN'.

**Steps to replicate**

1. Admit a patient to a facility A
2. Transfer the patient from Facility A to Facility B using the Add New Patient Registration Page by using the same number
3. Once the transfer is completed, the discharge reason shown in facility A related consultation page is Unknown
4. see the error

**Expected Behaviour**

- [ ] It should be shown discharge reason as Referred 
-Note: Validate there is a existing live consultation in the facility A, then only mark it "referred" 

**Screenshot**

![image](https://github.com/coronasafe/care_fe/assets/57055998/bd5bb882-8b01-4c3c-b670-9270c914019c)

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Can you assign this to me.

**Comment by nihal467** [comment]
@AshrafMd-1 Sorry, it was already assigned to @Ashesh3 , feel free to take up other open issues
