### ISSUE TITLE
Copy values for Log Updates

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6602]
**Is your feature request related to a problem? Please describe.**
When filing the log update, when the user selects the "copy values from the previous log", all the fields stay hidden. This is not ideal, sice the users have no option of looking at the values, ensuring everything is correct and then submitting the form.

**Describe the solution you'd like**

- [ ] "Copy values from previous log" must NOT be selected as default

- [ ] When user selects "Copy values from previous log", all the field must get filled with values from previous log. But the fields and values must be visible to the user. User must be allowed to edit one of more of the fields, and then submit the form

**Comment by AshrafMd-1** [comment]
I want to work on this issue can u assign this to me

**Comment by Omkar76** [comment]
Can assign me. I've got no bugs assigned currenly.

**Comment by Omkar76** [comment]
@aparnacoronasafe what should happen when user unchecks the checkbox? will it be more appropriate to turn this checkbox into a button?

**Comment by aparnaegov** [comment]
I see your point there. 

Yes, lets make it a button

**Comment by gigincg** [comment]
Nice suggestion @Omkar76

**Comment by nihal467** [comment]
non-relevant to current develop
