### ISSUE TITLE
Facility Capacity Export updated date field is not showing date properly

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6603]
**Describe the bug**

In the Facility Capacity Export, under the header, updated date, we are marking date and time in a non-user-friendly manner

**To Reproduce**

1. Go to Facility tab and export the capacity
2. See error

**Expected behavior**

- [ ] in the updated date column, remove the Time is that column and only display date

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/3a0fd902-2f5b-4488-838f-7eeb44815551)

**Comment by konavivekramakrishna** [comment]
I would like to work on it and discuss it in today's EOD call.

**Comment by GokulramGHV** [comment]
@nihal467 can you close the issue? I think it's completed.
