### ISSUE TITLE
Preserve Applied Advance filter in facility page while switching

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6605]
**Describe the bug**

- [ ] currently when we switch tabs, the Applied Advance filter in facility page are not preserved

**Expected behavior**

Preserve Applied Advance filter in facility page while switching in between tab

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/c5bc5b09-2811-4c4e-874e-f2e65a442035)

**Comment by vivramkrishna** [comment]
I would like to work on it, can you please assign me

**Comment by rithviknishad** [comment]
@konavivekramakrishna this would be a backend issue

**Comment by vivramkrishna** [comment]
@nihal467 

Can you please provide me with the login details of a district admin or user from a state other than Kerala

**Comment by vivramkrishna** [comment]
@rithviknishad 

If I'm not mistaken, the state and district for which a user has access are stored in the state_object, and the district_object isn't, right?

Also, I have a doubt: Can a user have access to multiple states and districts? If not, we can remove these from the filtering.

![image](https://github.com/coronasafe/care_fe/assets/101407963/d1b0fae7-dc53-4048-b30a-4fbf6462bc5f)

**Comment by rithviknishad** [comment]
> If I'm not mistaken, the state and district for which a user has access are stored in the state_object, and the district_object isn't, right?

Correct.

> Also, I have a doubt: Can a user have access to multiple states and districts? If not, we can remove these from the filtering.

The highest user type we have is a State Admin, which will be linked to a particular state always. Hence the state filter seems to be a no-op. We could remove it from the filters right @nihal467? Am I missing any other cases?

State Admins will be able to access multiple districts. Users less than or equal to the District Admin can have a disabled district filter with the accessible district pre-filled.

**Comment by vivramkrishna** [comment]
@nihal467 

can you please provide the login details for state admin

**Comment by vivramkrishna** [comment]
fixed in [6695](https://github.com/coronasafe/care_fe/pull/6695)
