### ISSUE TITLE
Hide the Delete Facility for user who don't have access to do it

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6608]
**Describe the bug**

Currently district admin and above have a delete facility button shown in the manage facility dropdown, even though they don't have permission to delete it

**To Reproduce**

1. Go to any facility
2. Click on manage facility
3. See error

**Expected behavior**

Hide the delete facility button for users, who don't have permission to do it

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/670f71c9-7667-40f0-a1cd-e11f5cb1d5c4)

**Comment by shyamprakash123** [comment]
@nihal467 I want to work on this, can I know who don't have access to `Delete Facility`?

**Comment by shyamprakash123** [comment]
> @nihal467 I want to work on this, can I know who don't have access to `Delete Facility`?

Can you assign this to me?

**Comment by ayush-seth** [comment]
@rithviknishad is this under the same category? Only state admin should see this button?

**Comment by rithviknishad** [comment]
Which user can delete is already present in the code base. The issue is about hiding the button instead of keeping it disabled.

<img width="474" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/dd2083b1-8996-4ecf-b883-83acdadbe4e8">

**Comment by xakep8** [comment]
@rithviknishad  I wish to work on this issue can you assign it to me?

**Comment by shyamprakash123** [comment]
> Which user can delete is already present in the code base. The issue is about hiding the button instead of keeping it disabled.
> 
> <img alt="image" width="474" src="https://user-images.githubusercontent.com/25143503/283868574-dd2083b1-8996-4ecf-b883-83acdadbe4e8.png">

Understood,  please assign me so that I can start working on this.

**Comment by xakep8** [comment]
@rithviknishad  @nihal467 if i am not wrong a district admin must be able to delete the facility if the facility belongs to his district and the stateadmin must only be able to delete a facility if the facility is in his state right?

**Comment by rithviknishad** [comment]
Yes, but are you able to even read a facility that's outside of the district admin's district?

If not, why bother defining that no-op check that'd always evaluate to true?

**Comment by rithviknishad** [comment]
@xakep8 unassigning as the related PR has not been followed up

**Comment by Ashesh3** [comment]
> @nihal467 I want to work on this, can I know who don't have access to `Delete Facility`?

Hey, do you still want to take up this issue?
