### ISSUE TITLE
Design Enhancement Scope in Facility Detail Page 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6609]
**Describe the bug**

In the header part of the facility detail page, the card has a huge un-utilised space and there is a scope of effective utilisation of space and a redesign of this part of the page

**To Reproduce**

1. Go to any facility detail page with district admin access 
2. See error

**Expected behavior**

An effective way to utilize the spacing and a new design

**Note:** Whoever wishes to work on this issue, get the mock-up design approved in the EOD call, then only, the issue will be assigned to the respective author.

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/68be86b3-862b-4118-a07c-694644b1735b)

**Comment by Keshav-0907** [comment]
@nihal467 I want to work on this issue, can you please assign this to me

**Comment by Shahbaz898414** [comment]
@rithviknishad Hey, can i work on this issue?

**Comment by MjStar24** [comment]
hey @rithviknishad I would like to work on this can you assign this to me

**Comment by UltigendLemate** [comment]
I wish to work on this issue @rithviknishad 
I have a rough design in my mind for this. Pls advice how to get on call.

**Comment by rithviknishad** [comment]
Closing as duplicate of #7285

**Comment by rithviknishad** [comment]
> Pls advice how to get on call.

@UltigendLemate refer https://github.com/coronasafe/care_fe/issues/6715#issuecomment-1958729788 on how to join the calls

**Comment by dwip708** [comment]
I would like to work on this issue and update the styles and make it responsive for various screen-sizes.

**Comment by tellmeY18** [comment]
.
