### ISSUE TITLE
Facility Cover Image upload pop-up is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6610]
**Describe the bug**

When we click anywhere on the places where i mentioned in the screenshot, the cover image pop-up is been opening up

**To Reproduce**

1. Go to facility detail page
2. Click on any specific place mentioned in the screen shot
3. See error

**Expected behavior**

The cover image pop-up should be only open when we click on the respective place

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/c4dade2f-0d72-4057-a984-9f800b68ab8a)

**Comment by vivramkrishna** [comment]
@nihal467 
I checked where the issue is and understood, can you please assign me
I will do it now
