### ISSUE TITLE
Facility name is mentioned twice on the facility cover upload page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6611]
**Describe the bug**

- [ ] When we open camera to upload the facility cover image, the facility name is shown twice
- [ ] buttons are not properly responsive

**To Reproduce**

**Expected behavior**

- [ ] facility name should be only shown once
- [ ] Make the button properly responsive rather than adding a scroller

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/b36e17f5-2ea5-46c1-8089-1c9d85c6cd2d)
![image](https://github.com/coronasafe/care_fe/assets/57055998/8ac94e23-5335-4610-9860-d51ee216f6c6)

**Comment by kshitijv256** [comment]
I would like to work on it
