### ISSUE TITLE
Move the cancel button to the right in facility  inventory add page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6613]
**Describe the bug**

The cancel button is on the left side in the inventory add page, which is design inconsistency compared to other page

**To Reproduce**

1. Go to facility inventory add page
2. See error

**Expected behavior**

Move the cancel button to the right side of the inventory add a page, to ensure design consistency 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/ff39316a-fe56-4a3b-8164-62014562c00f)

**Comment by AshrafMd-1** [comment]
I want to work on this issue can you assign me.
