### ISSUE TITLE
Rice can't be added as gram in the inventory list but shown in the dropdown

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6615]
**Describe the bug**

Currently, we can add rice as gram and Kg as per the dropdown, but when we submit the by select gram, it is getting rejected by the backend

**To Reproduce**

1. Go to Facility inventory and add rice with gram
2. See error

**Expected behavior**

- [ ] Add support the gram unit

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/fd6cc9d6-5c5e-4d4b-a146-248dde5b8650)

**Comment by sriharsh05** [comment]
@rithviknishad 
I want to work on this issue. Please assign this to me.

**Comment by Ashesh3** [comment]
@sriharsh05 Any updates on this issue?

**Comment by sriharsh05** [comment]
Yes @Ashesh3, I have stared working on it.
