### ISSUE TITLE
Make the consultation page more properly responsive

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6617]
**Describe the bug**

In the below screenshot we are seeing following issues in the responsive view 👍 

- [ ] where we can two buttons in a row, it is stretching the button a lot and utilising the entire row, which give a weird UI
- [ ] the red circled part, where the patient detail and bed details are marked, it is not effectively utilising the space in responsive

**To Reproduce**

1. Go to any patient consultation and view it in responsive view
2. See error

**Expected behavior**

- [ ] If the screen size support in responsive view, allow two or three buttons in a row, and as the screen size reduces move the button to the next rows
- [ ] Rather than keeping the bed detail in center, move it to the left side and patient detail and all other detail to the right side based on the available space ( this is a suggestion ), try to achieve a better responsive view utilising the space properly 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/8ea41ebd-02ab-4de9-bdf0-486f81e2e05b)

**Comment by Omkar76** [comment]
I'll like to work on this.

**Comment by nihal467** [comment]
the entire page getting redesign
