### ISSUE TITLE
Make the facility detail page more properly responsive

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6621]
**Describe the bug**

- [ ] the facility details which can be shown in the same row are been displayed as a different row in the responsive view
- [ ] the buttons are stretched a lot to occupy the entire row, where it can occupy two or three buttons as per the screen size 

**To Reproduce**

1. Go to facility detail page
2. See error

**Expected behavior**

- [ ] make the facility detail page, fully responsive properly

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/c4adcef6-078c-4546-abd6-8fbb7e192473)

**Comment by kshitijv256** [comment]
I would like to work on this issue

**Comment by nihal467** [comment]
@kshitijv256 you already have a issue assigned to yourself, i would recommend post fixing that, only assign yourself with another issue

**Comment by Ashesh3** [comment]
> I would like to work on this issue

Hey, do you still want to take this up?
