### ISSUE TITLE
Add auto-scroll function to error in add triage form 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6622]
**Describe the bug**

In the mobile view, when the triage form throw mandatory field error, it is not auto-scroll to the error

**To Reproduce**

1. Go to the facility triage page in the mobile view
2. submit the form without filling the triage date
3. See error

**Expected behavior**

in mobile view, the auto-scroll to the error should be working in the facility triage form

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/179646ce-cabb-4433-bc94-9cc90d174d60)

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign it to me.
