### ISSUE TITLE
Add Frontend validation in the add multiple bed function

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6624]
**Describe the bug**

We can only create 100 multiple beds at a location per request, there is no validation for the front-end but back-end has it and rejects any creation request for 100+ bed

**To Reproduce**

1. Go to facility location management and try creating multiple 100+ beds
2. See error

**Expected behavior**

- [ ] add a frontend validation for multiple bed creation form

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/7b2b34bf-190f-45ac-ad1a-7bde3dd2be8d)

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign it to me.
