### ISSUE TITLE
Dosage field in prescription are malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6625]
**Describe the bug**

when we input a lot of zero initially and input any integer, the dosage accepts the value and causes the UI to break.

**To Reproduce**

1. Go to 'prescription of any patient
2. Add dosage with lots of zeros initially and submit it
3. See error

**Expected behavior**

It should accept only valid inputs

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/4bf6c8cc-7afc-481e-8ab5-d86423474021)

**Comment by AshrafMd-1** [comment]
I want to work on this issue can u assign me this?

**Comment by nihal467** [comment]
@AshrafMd-1 can you push the fix by EOD, its a P1 Urgent issue

**Comment by AshrafMd-1** [comment]
> @AshrafMd-1 can you push the fix by EOD, its a P1 Urgent issue

okay I will

**Comment by AshrafMd-1** [comment]
@nihal467 i have submitted a PR.

**Comment by rithviknishad** [comment]
@AshrafMd-1 also create a backend issue for this, to sanitize/validate the dosage fields

**Comment by AshrafMd-1** [comment]
@rithviknishad created an issue
