### ISSUE TITLE
 Patient body details are shown twice in the patient consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6631]
**Describe the bug**

Patient body details are shown twice on the patient consultation page expect the Body surface area, on the info card, and the patient details on the top side, we should be keeping any right?

**To Reproduce**

**Expected behavior**

Remove the blood group, weight and height badges on the top

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/91205c56-ae88-4204-8011-b8b05701923e)
![image](https://github.com/coronasafe/care_fe/assets/57055998/92dab58d-de98-427e-8934-9161d1d791bf)

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign this to me.
