### ISSUE TITLE
User Management is showing all user without user access limitation / user location

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6633]
**Describe the bug**

We are now able to see all the users in the entire care in the user management, irrespective of what user role / user location the logged in user having in the platform

**To Reproduce**

1. Go to user tab
2. See error

**Expected behavior**

- [ ] District admin should be seeing all users from that district
- [ ] Under below district admin should be able to see users linked to the facility they have access to
- [ ] state admin should be able to see all users inside the state

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/e90e09bc-396a-418f-9664-115f9322df07)

**Comment by rithviknishad** [comment]
Hey @GokulramGHV any updates on this?

**Comment by GokulramGHV** [comment]
@rithviknishad I've started working on this, I'll make a PR soon

**Comment by nihal467** [comment]
resolved in https://github.com/coronasafe/care/pull/1742
