### ISSUE TITLE
District Filter in the user advance filter need to be modified

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6634]
**Describe the bug**

in the district filter in the user advance filter, it displays the district in the entire country together, which is not a good user experience

**To Reproduce**

1. Go to user tab and open the advanced filter
2. See error

**Expected behavior**

- [ ] District dropdown list change the data format to "district name, State name"

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/7c502144-22d6-4a69-bd2d-0a8084d6bab4)

**Comment by vigneshhari** [comment]
Use a state filter before the dist filter is applied to solve this problem, no backend changes required.
