### ISSUE TITLE
Comment Section in the shifting detail page is stretching the page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6637]
**Describe the bug**

When we post multiple comment on a shifting detail page, it keep on stretching the page to the bottom

**To Reproduce**

1. Go to any existing shifting detail page and post multiple comments ( https://care.coronasafe.in/shifting/e785d651-9fde-4279-ac33-e9282296dc10 )
2. See error

**Expected behavior**

It shouldn't be stretching the page a lot and the entire page should be effectively utilizing the white space

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/47547ff6-f34e-4c6c-82b0-f99dbc600202)

**Comment by parthksingh1** [comment]
@rithviknishad  Please assign me this issue .To resolve the bug, I will inspect and adjust the CSS styles associated with the comment section on shifting detail pages, ensuring responsive design and dynamic sizing. Will Thoroughly test the changes with different comment quantities and devices to ensure optimal page layout

**Comment by vivramkrishna** [comment]
@rithviknishad 

A simple solution would be to passing perPage 5 or 6. by default per Page is 14, causing the entire page to stretch significantly

 
![image](https://github.com/coronasafe/care_fe/assets/101407963/fd7d1115-e1f8-450e-8383-c6842f760071)

**Comment by Bhavik-ag** [comment]
@rithviknishad @nihal467 Here are two simple possible solutions

1) We can shift the patient details section to the right side of grid and setting comment perPage limit to 5.

![image](https://github.com/coronasafe/care_fe/assets/73033511/12413c5c-52af-4361-8744-c6c266b1ac87)

2) We can make patient details page expand full width and comments and rest section side by side.

![image](https://github.com/coronasafe/care_fe/assets/73033511/64d9d657-2b5b-445e-a2f9-b4f55f45f0e1)

**Comment by rishbanerjee** [comment]
Hey @rithviknishad @nihal467 I tried to see this error on the webpage but when I try to post a comment it shows an error "Not found" , is this issue still relevant?

**Comment by senthil-athiban** [comment]
Hey @nihal467. We can enhance the user experience by adding a view more button. Based on that, when the user clicks on it, an extra 5 more comments will be visible, and we'll repeat the same until the comment exists. And intially Top 5 comments will be only displayed.

**Comment by Thanush19** [comment]
Hey, if the issue is not completed, I can work on this.

**Comment by Thanush19** [comment]
https://github.com/coronasafe/care_fe/assets/110150744/c70667bc-4afe-4967-a45c-7fe00c20904f


i  have submitted my PR #7364,  kindly review it , if any changes need to be done , intimate me @rithviknishad

**Comment by Thanush19** [comment]
@rithviknishad , is there any corrections needed to be done ? if so, intimate me...?

**Comment by Thanush19** [comment]
@rithviknishad , whats the status  on this PR?? is any changes required...

**Comment by rithviknishad** [comment]
Hey, not sure if you've missed it, but I've requested changes in your PR two days ago

**Comment by Thanush19** [comment]
@rithviknishad You instructed me to reuse the existing type, but it lacks the required types for comments. Additionally, you mentioned reusing the ReadMore.tsx component, but when I attempt to do so, it doesn't align with the Comment Box. Modifying the CSS of the ReadMore component might disrupt the UI of other components, so I opted to write new code to address this issue.

**Comment by rithviknishad** [comment]
Alright. ReadMore component is fine.

But `any` type is not allowed when we already have types for it.

If you look carefully, proper types are already present for created_by_object in the same file too. You just have to re-use it.

<img width="708" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/899f0530-e0c3-4caa-a707-da3703ddcc56">

**Comment by Thanush19** [comment]
@rithviknishad , i've submitted new PR ,correcting all the changes u asked for , and also added Multilingual support for all the Button i have used , check my PR  https://github.com/coronasafe/care_fe/pull/7402

**Comment by Thanush19** [comment]
@rithviknishad , kindly review the PR [](https://github.com/coronasafe/care_fe/pull/7402)

**Comment by Thanush19** [comment]
hey @rithviknishad , whats the status on my PR....

**Comment by nihal467** [comment]
@Thanush19 Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by bilalarifsiddiqui** [comment]
Hey @nihal467 assign this to me.

**Comment by NikhilGolla72** [comment]
@rithviknishad  hello,is this issue still open? if yes, I would like to work on this issue.

**Comment by Jacobjeevan** [comment]
Holding this on the back burner now, as shifting details page might get redesigned (as grid/table format). If so, could redesign this page along with that 🤔

**Comment by Jacobjeevan** [comment]
Closing as this page is reworked.
