### ISSUE TITLE
Use relative time / RecordMeta component for audit log details in shift details

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6638]
**Describe the bug**
Most of the places we use relative time with absolute time in tooltip and user shown through `RecordMeta` component. But that's not the case in audit log details in shift details page.

**Expected behavior**
Use relative time / RecordMeta component for audit log details in shift details

**Screenshots**
<img width="586" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/731080f1-76b9-4fd0-b145-8cc57f3284ec">

**Comment by AshrafMd-1** [comment]
I want to work on this issue can u assign this to me.
