### ISSUE TITLE
Adding support for gmeet/zoom/ any other video call to doctor connect

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6641]
**Is your feature request related to a problem? Please describe.**

Currently doctor connect is limited to phone call and whatsapp no, if the doctors don't want to expose there phone number, we doesn't have any support for any other platform

**Describe the solution you'd like**

We should be adding support to googlemeet, zoom or any other common platform people want to use as an extension to the doctor connect

**Comment by rithviknishad** [comment]
- Ref: https://github.com/coronasafe/care_fe/pull/5147

**Comment by nihal467** [comment]
- [ ] add a field to store video conferencing links to a user profile
- [ ] It should be editable from the user profile page
