### ISSUE TITLE
Import Old Patient File into CARE

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6644]
**Is your feature request related to a problem? Please describe.**

There are millions of patient record, which is stored as paper format, currently the only want to store them is using the file upload, but it will be hard for a user to go through the old record page by page, in case if we want to learn about the patient history

**Describe the solution you'd like**

- [ ] We built a feature to import data from a pdf scan page into the relevant category module after a "Manual Cross-verification" of a human, so the old patient detail such as there initial allergy , when it started, how much years this been there, all kind of data can be digitally converted 

**The steps involved will be :** 

1. A PDF format old patient consultation need to be uploaded to care
2. CARE convert the pdf to relevant different format and categories it based of section like medicine, investigation, lab reports, etc...
3. a prompt comes into the user, what all data you want to import from the file
4. based on the selection, the software show the user, what all it was able to convert and ask for a verification plus allow the user to rectify incase of any mistake
5. once the data is verified, it is imported into care platform

**Comment by nihal467** [comment]
**note of EOD Meeting 15/11/2023**

- [ ] focus this approach to add lab report to the care

**Comment by nihal467** [comment]
requires GPT Vision API, and can be considered only if operationally feasible

**Comment by bodhish** [comment]
lets build it when we have a user requirement.
