### ISSUE TITLE
"Reviewed before" chip in Consultation Dashboard has no padding

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6646]
**Describe the bug**
"Reviewed before" chip in Consultation Dashboard has no padding

**Expected behavior**
Have padding

**Screenshots**
<img width="477" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/cd3605dc-6bba-46cc-80a0-61349115be06">

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Can u assign it to me.
