### ISSUE TITLE
Modify the existing external results sample format as it is not working

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6649]
**Describe the bug**

When attempting to upload the downloaded sample format to external results without making any changes, an error is thrown.

**To Reproduce**

1. Go to external results
2. Click on import and download the sample format then upload the same file without changing
3. See error

**Expected behavior**

the sample format upload should work properly for the external result

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/57afb0dc-20ab-47a5-8686-25519fb14c1e)

**Comment by vivramkrishna** [comment]
@nihal467 @rithviknishad 

Could you please raise my edit access for this document, or would it be better for you to create a new spreadsheet and grant access to me: [https://docs.google.com/spreadsheets/d/17VfgryA6OYSYgtQZeXU9mp7kNvLySeEawvnLBO_1nuE/edit#gid=0]

I believe there's an issue with the default download format; when we open the CSV file in Excel and enter details, the date format changes to DD-MM-YYYY, whereas we need it in YYYY-MM-DD format.

It would be preferable if the default download format is set to Excel.

I would like to work on it can you please assign me

**Comment by rithviknishad** [comment]
As discussed, you can create a clone of that sheet, modify as required and keep it in the github repo itself under https://github.com/coronasafe/care_fe/tree/develop/public directory
