### ISSUE TITLE
External Results upload functionality is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6650]
**Describe the bug**

I've created a working external result import file with data from the Ernakulam district. When logged into Care with a user privilege other than "Ernakulam District," such as "Palakkad District," trying to upload the external result will succeed, but no data will be reflected in the external result tab

**To Reproduce**

1. Login as a user other than Ernakulam district
2. Click on import button and upload the file attached to this issue
3. file upload will get uploaded and data won't be reflected

**Expected behavior**

- [ ] relevant errors should be thrown incase the data is not successfully created in the frontend
- [ ] check the latest comment as well

**Screenshots**

[externalresultsample.csv](https://github.com/coronasafe/care_fe/files/13372166/externalresultsample.csv)

![image](https://github.com/coronasafe/care_fe/assets/57055998/b4a5fcc0-73b7-46df-a91c-ed88672686cc)

**Comment by vivramkrishna** [comment]
@nihal467 

I think everything is working fine, just need to change the sample format 
![image](https://github.com/coronasafe/care_fe/assets/101407963/fb0a9acd-72ab-4e2b-86a4-10f8afdfa4f4)
![image](https://github.com/coronasafe/care_fe/assets/101407963/67b81b48-e5eb-4a6b-a4f4-c04794ea59e9)

**Comment by vivramkrishna** [comment]
@nihal467 @rithviknishad 

can you please provide the login details for the user

**Comment by nihal467** [comment]
@konavivekramakrishna use the login :
username ;nihal-district  / Password : Test@123

**Comment by vivramkrishna** [comment]
@nihal467 

I think this is a backend issue because the response is empty if the response includes any error message we can show the error message
![image](https://github.com/coronasafe/care_fe/assets/101407963/18cf9d13-e06d-4eee-a33d-0fd6d083813b)
![image](https://github.com/coronasafe/care_fe/assets/101407963/1b38c2b2-13a0-4178-9c90-c3f09355414d)

**Comment by rithviknishad** [comment]
@konavivekramakrishna The API has responded with 202 Accepted. Hence no errors were encountered. Have you tried calling the list API for the same after a successful upsert?

**Comment by vivramkrishna** [comment]
@rithviknishad 
yes
![image](https://github.com/coronasafe/care_fe/assets/101407963/3ae7de98-9b88-4e66-b513-350a51c6f978)

**Comment by vivramkrishna** [comment]
@rithviknishad 

I will check once again if there is any error with api call

**Comment by vivramkrishna** [comment]
@rithviknishad 

There is no error with api call

**Comment by rithviknishad** [comment]
Currently, the user is able to upload results for other districts. However, the list view will only show results the user can access. 

So if a user from Ernakulam uploads results with the local body that belongs to Kannur, then they won't be able to preview these bulk created results in the list view as the user does not have the permission.

**Comment by nihal467** [comment]
- [ ] The users should only be allowed to upload results for their particular district.
