### ISSUE TITLE
Make Covid Detail section by default collapsed in patient advance filters

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6651]
**Describe the bug**

covid detail section in the patient advance filters are having the least use case right now

**To Reproduce**

1. Go to patient advance filters in the patient tab
2. Scroll down to bottom

**Expected behavior**

Covid Detail section should be default collapsed, not expanded

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/e337e06d-7eaf-4386-969e-a366af95a65e)

**Comment by AshrafMd-1** [comment]
I want to take up this issue can you assign this.
