### ISSUE TITLE
Update admission date validation

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#6657]
**Description of bug**

Add a minimum date validation for the admission date in the patient consultation.

**Expected Behaviour** 

- [ ] Add minimum date validation for the admission date as year 2000

<img width="844" alt="image" src="https://github.com/coronasafe/care_fe/assets/29787772/8c6c83ab-d643-4e8e-85b6-ed37b2d38cf5">

Issue edited post weekly engineering call discussion on 20/11/2023

cc: @nihal467 @gigincg

**Comment by nihal467** [comment]
- [ ] mark minimum date validation for the admission date as year 2000

**Comment by sriharsh05** [comment]
@rithviknishad 
I want to work on this issue. Please assign this to me.
