### ISSUE TITLE
Hide the Delete User button for users who don't have access to do it

### ISSUE THREAD

**Issue by AshrafMd-1** [coronasafe/care_fe#6660]
**Describe the bug**
Currently district admin and above have a delete user button shown in the view users in facilities, even though they don't have permission to delete it

**To Reproduce**

1. Go to Facility
2. Click on Manage facilities
3. Click on View users

**Expected behavior**
Hide the delete user button for users, who don't have permission to do it

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/98876115/803ffaed-d0af-4e35-beb2-98724750d2f4)
![image](https://github.com/coronasafe/care_fe/assets/98876115/1aeb14a0-2711-4e5a-889c-d15dcebb6046)
![image](https://github.com/coronasafe/care_fe/assets/98876115/9dcbd3de-9f68-429a-9078-02e4894d913c)
![image](https://github.com/coronasafe/care_fe/assets/98876115/1b55cce2-94e9-4f31-a620-e6599844606b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ayush-seth** [comment]
This is the function that controls the visibility of the delete button
```typescript
 const showDelete = (user: any) => {
    const STATE_ADMIN_LEVEL = USER_TYPES.indexOf("StateAdmin");
    const STATE_READ_ONLY_ADMIN_LEVEL =
      USER_TYPES.indexOf("StateReadOnlyAdmin");
    const DISTRICT_ADMIN_LEVEL = USER_TYPES.indexOf("DistrictAdmin");
    const level = USER_TYPES.indexOf(user.user_type);
    const currentUserLevel = USER_TYPES.indexOf(authUser.user_type);
    if (user.is_superuser) return true;

    if (currentUserLevel >= STATE_ADMIN_LEVEL)
      return user.state_object?.id === authUser.state;
    if (
      currentUserLevel < STATE_READ_ONLY_ADMIN_LEVEL &&
      currentUserLevel >= DISTRICT_ADMIN_LEVEL &&
      currentUserLevel > level
    )
      return facilityData?.district_object_id === authUser.district;
    return false;
  };
 ```
 
Reproducing the issue, I can see that the delete button is visible because the 3rd `if` condition is evaluating to `true` which because `currentUserLevel > level` which implies that the `authUser` should be able to delete `user` and they also belong to the same `district`. Which makes me think something is wrong on the backend here? Since the logic for showing the button seems to be right. How can I find out why exactly the backend API is failing?

**Comment by rithviknishad** [comment]
@ayush-seth https://github.com/coronasafe/care/commit/0cbff7c6932245cd44eaf3f4aab1ee23a9461d60 has changed the restriction to much simpler, only "StateAdmin" user can delete other users.

**Comment by rithviknishad** [comment]
This change was not reflected in front-end. Hence the issue.

**Comment by ayush-seth** [comment]
cool, I can take this up. Can you assign it to me? @rithviknishad
