### ISSUE TITLE
Care app reloads upon login

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6665]
**Describe the bug**
When we login to care, the app reloads (as `window.location.href=...` is done instead of `nvaigate(...)`. This causes to load the app again / fetch `index.html`, `index.js`, and other files all again. 

It'd be much faster if we could avoid this from being reloaded.

**To Reproduce**

1. Open network tab and observe the files that are being fetched.
2. Open CARE
3. Login to CARE using valid credentials

**Expected behavior**
Should not reload the entire app upon valid login.

**Comment by AshrafMd-1** [comment]
I want to take up this issue can u assign this to me

**Comment by ayush-seth** [comment]
Any reason this project is using [raviger](https://github.com/kyeotic/raviger) which barely anyone has ever heard of and has not been updated since 2022 instead of using the industry standard [React Router](https://github.com/remix-run/react-router)?

**Comment by ayush-seth** [comment]
This is a bigger problem at its core with how route protection and login is being handled and just replacing `window.location.href =` with `navigate()` is not going to solve these issues. 

For ex. when I am logged out and I navigate to `/shifting/board`, instead of being redirected to `/login` I stay on `/shifting/board` and in those cases, after logging in, it does `window.location.href = window.location.pathname.toString()`, using `navigate` here won't do anything because the path does not change, you have to reload the whole page. Same goes for any other url.

**Comment by rithviknishad** [comment]
I don't see any issue with Raviger's routing.

If you look at the code, we have two routers: Session and App router. App router is accessible only if the query to get the current profile responds with 200, you'll be exposed to the App router, else it'll show the Session router.

We just need to invoke the refetch of the current user query somehow whenever the JWT access token is updated in the local storage. That'd cause the AuthUserProvider component to render, and hence exposing the appropriate router based on the response.

<img width="566" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/6c5c9540-0d5a-4edf-879c-6e183eb0c73a">

<img width="691" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/f180b3cb-c646-4c7e-af9c-b35e8b0af0c0">

**Comment by Ashesh3** [comment]
@AshrafMd-1 What are the updates on this issue?

**Comment by AshrafMd-1** [comment]
@Ashesh3 , I am currently addressing a p2 issue. Once I have resolved that, I will proceed to work on and submit a pull request soon.

**Comment by AshrafMd-1** [comment]
@rithviknishad  can you unassign me this issue as I am unable to find an optimal solution for the problem

The process is to refetch the current user query when the user logins correctly

My attempts to this were:

- Passed the refetch option as props, but it resulted in the code becoming quite messy.
- Used the current URL as a condition for refetch  but doing so caused many requests each time the url changes
