### ISSUE TITLE
Show Patient details of selected Preset in Location Live Feed Monitoring

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6667]
**Describe the bug**
Currently, we are not showing the patient in the selected bed in Live Feed monitoring as there's no efficient way to fetch which patient is present on a particular bed.

**To Reproduce**

1. Go to a location live feed monitoring page

**Expected behavior**
Show Patient name, age gender as shown in the mockup

**Screenshots**
<img width="1118" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/e4d2a9c8-3676-4f08-9b1c-6b771b0fc7b4">

**Comment by kirtanchandak** [comment]
Hey, can I work on this issue?

**Comment by rash-27** [comment]
If no one is working on this , I would like to work on this issue

**Comment by rithviknishad** [comment]
@rash-27 could you describe how you'll be trying to solve this?

**Comment by rash-27** [comment]
@rithviknishad Currently, we are fetching information for assets from [api/v1/assets] to display the feed
![Screenshot from 2024-04-03 16-18-12](https://github.com/coronasafe/care_fe/assets/146672184/96cf9a7b-3905-40f4-8d12-9b97fcfacb70)
. Instead, if we try to fetch from [/api/v1/facility/{facility_external_id}/patient_asset_beds/], we get the additional information of the patient name too, and if we try to include the patient's age in the route in the backend I think we can solve this, Is my approach right?

**Comment by rithviknishad** [comment]
Yup, you can try that! You need not change the backend to provide the age. We can calculate age from FE itself using the recently added utility function right?

**Comment by rash-27** [comment]
Yup , I'll try it .

**Comment by rash-27** [comment]
@rithviknishad , is this ok ?
![image](https://github.com/coronasafe/care_fe/assets/146672184/f5499a98-443d-4151-ae65-bd564ae00263)

**Comment by noufalrahim** [comment]
@rithviknishad can u assign this to me..?

**Comment by noufalrahim** [comment]
@rithviknishad  can u mention how to reproduce to the monitoring page
