### ISSUE TITLE
Advanced filter on patient: Location (Improvement)

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6671]
**Is your feature request related to a problem? Please describe.**
The location based filter is confusing. Since location could also mean, which district/localbody the patient is from.
Also, since the filter is only applicable when 1 facility is selected, there is no need to show it to the users all the time.

**Describe the solution you'd like**

- [ ] Make the locations filter appear only when 1 facility is selected.
- [ ] Change the name of the filter from "Location" to "Location patient is admitted to"

**Comment by ayush-seth** [comment]
I would like to take it up

**Comment by ayush-seth** [comment]
I need more info to work here, are we talking about the `Location` input in this section in the `Patients` page?

- What does it mean "only one facility is selected"? Where do I select the facility?
- "Make the location filter appear...", should the whole `Geography` section be hidden? or just the `Location` input?
<img width="1497" alt="image" src="https://github.com/coronasafe/care_fe/assets/24858182/51e2a9dd-3000-4ee6-b6f9-e51b4b5fcc81">

**Comment by rithviknishad** [comment]
> What does it mean "only one facility is selected"? Where do I select the facility?

<img width="228" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/79b95742-4042-49e3-b3da-3d2448b4c63a">

> "Make the location filter appear...", should the whole Geography section be hidden? or just the Location input?

Just the location input. Currently, it's disabled, right? The same condition in which it is disabled should be used to hide/show it instead.
