### ISSUE TITLE
Log Update: Round types: Telemedicine

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6676]
(https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7c0917bf-b8d8-4e3b-8f5e-feed90657727/consultation/22d72f5d-ff83-43bb-a711-0be618e24f0d/daily-rounds)

When the "Decision after consultation" on the consultation form is marked as "Domiciliary care", 

- [ ] In log update form, "Round Type" add an option for "Telemedicine"
- [ ] The short log update form that is available with the "Normal Round type" shall also be made available for "TeleMedicine Round type"

**Comment by xakep8** [comment]
I wish to work on this issue can you assign it to me?

**Comment by aparnacoronasafe** [comment]
@xakep8 I have updated the issue a little. 

Let me know if you have any confusion.

**Comment by xakep8** [comment]
@aparnacoronasafe what are we calling as the short log update form?
also what should be the difference in action on selection of Telemedicine as RoundType?

**Comment by aparnacoronasafe** [comment]
@xakep8 If you go to log update, Round Type, currently we have two options.
**Normal**- When they select normal log update, they only fill out the one form that appears with vitals and a few other fields.
**Critical Care**- When this is selected, the log update form leads to another more lengthy critical care forms.

In this new type "Telemedicine" round type, we will go with the same form as in "Normal" round type.

Is it clear?

**Comment by nihal467** [comment]
@xakep8 It's a P2 priority issue that needs to be closed within the next 7 days. Could you please provide an update on this issue? If no update is received within 48 hours, the issue will be unassigned.

**Comment by nihal467** [comment]
@xakep8 due to inactivity, I'm unassigning you from this issue, feel free to take up other open issues

**Comment by aparnacoronasafe** [comment]
@Ashesh3 lets close this by next release. Please mark as P1
