### ISSUE TITLE
Death datetime before admission date shouldn't be restricted

### ISSUE THREAD

**Issue by Deepjyoti14** [coronasafe/care_fe#6678]
**Is your feature request related to a problem? Please describe.**
A patient got admitted at 2am in morning and got expired at 6am. Patient's info was entered in care at 9am (admission datetime). Care not allowing to discharge at time before admission time. This happens as there is a staff storage.  

**Describe the solution you'd like**
Since we are taking current time as admission time, then restriction should be removed. Else the **date of admission** field should have a time field also.

![issue 2](https://github.com/coronasafe/care_fe/assets/129942643/4d3eba0e-23a7-44ef-81b9-f924ddc4b1e3)
![issue](https://github.com/coronasafe/care_fe/assets/129942643/e21776f2-7e3a-46ea-996c-f977f8e61a2b)

**Comment by rithviknishad** [comment]
@Deepjyoti14 The PR https://github.com/coronasafe/care_fe/pull/6458 introduces support for capturing Date & Time. Once it is merged, the time part of the Admission Date & Time for existing records would be reset to 12AM (local time). 

I hope that'd solve this problem.

cc: @aparnacoronasafe

**Comment by Deepjyoti14** [comment]
Ok. Thanks @rithviknishad

**Comment by nihal467** [comment]
@Deepjyoti14 As a temporary fix, follow the below steps :

1. Go to edit consultation
2. Click on the date of admission field
3. select the same date again from the calendar
4. then click on the update consultation button

This will reset the time to 12:00 AM
