### ISSUE TITLE
OP Consultation: auto-discharge.

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6679]
**Is your feature request related to a problem? Please describe.**
When a patient's consultation form is saved with "OP Consultation" in "Decision after consultation" " the patient is auto-discharged once the consultation is saved. 

The discharge reason is "Unknown" in such cases.

**Describe the solution you'd like**
The discharge reason in such cases must appear as "OP file closed"

**Comment by rithviknishad** [comment]
@aparnacoronasafe should we align it as per https://terminology.hl7.org/5.1.0/CodeSystem-discharge-disposition.html

<img width="1135" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/9c6b2d30-8655-48d8-9205-b82645cbdf98">
