### ISSUE TITLE
Adding a Date/time and round type filter for log updates

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6690]
Add a filter to help users sort through many log updates filed within an encounter

- [ ] Add a Date/time based filter
- [ ] Add a round type based filter

These filters shall appear on top of the Log Update list on the patient dashboard (https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/400cbedd-98d7-4f8f-b835-155ba71cc28d/consultation/6ae67a3d-305b-4404-bfd6-b21b0d0f8426)

- [ ] When filter is applied, the same should be visible
- [ ] There must be option to clear all filters
- [ ] Default must always be the entire list without any filters

**Comment by vivramkrishna** [comment]
I would like to work on it, can you please assign me

**Comment by vivramkrishna** [comment]
@aparnacoronasafe 

Could you please review the UI implementation, Can I proceed with this implementation?

ps: I should change the label name


![image](https://github.com/coronasafe/care_fe/assets/101407963/579dd244-9c92-4f43-af6e-730714756ed4)
![image](https://github.com/coronasafe/care_fe/assets/101407963/4f895e22-7cda-436f-991d-1a70ce4798a0)
