### ISSUE TITLE
Phase out "Covid" classification from Bed Types in Bed Capacity

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6692]
**Describe the bug**
COVID is over. Phase out "Covid" classification from Bed Types in Bed Capacity

**Expected behavior**

check the latest comment

**Screenshots**
<img width="712" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/47ecba66-94ca-4e89-b60d-32b25da3c621">

**Comment by nihal467** [comment]
- [ ] Rename all bed types starting with "non-covid" to their respective bed types. For example, change "Non-covid Oxygen Bed" to "Oxygen Bed."

**Comment by kshitijv256** [comment]
I would like to work on it

**Comment by kshitijv256** [comment]
@rithviknishad 
we are getting only `id` as number from backend and mapping it to various bed types on frontend, is there a need for backend changes?

**Comment by rithviknishad** [comment]
yes

**Comment by rithviknishad** [comment]
Nope, my bad
