### ISSUE TITLE
Replace useDispatch with useQuery in Doctor Notes related components

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6705]

**Comment by Omkar76** [comment]
I'd like to take this up. Can you assign me @rithviknishad

**Comment by rithviknishad** [comment]
@Omkar76 you have multiple issues already assigned to you that has no PR / changes required.

https://github.com/coronasafe/care_fe/issues/assigned/@me

Feel free to take up once your existing assigned issues are cleared!

**Comment by thedevildude** [comment]
Which components needs to be changed? Are they related to `Facility/ConsultationDetails`, `Facility/Consultation` , `Patient/PatientNotes`?

**Comment by rithviknishad** [comment]
- `Facility/PatientNotesList.tsx`
- `Facility/PatientNotesSlideover.tsx`
- `Patient/PatientNotes.tsx`

**Comment by thedevildude** [comment]
@rithviknishad Got it. Can you assign it to me?

**Comment by rithviknishad** [comment]
Hey @thedevildude any updates on this?

**Comment by thedevildude** [comment]
@rithviknishad I should be able to make a PR by tomorrow for this.
