### ISSUE TITLE
Camera Preset created are not shown in asset configure page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6706]
**Describe the bug**

The camera preset are getting preset successful in asset configuration, but it is not shown in the page

**To Reproduce**

1. Go to https://care.ohc.network/facility/17fc35c9-1aab-42f5-9bee-4c4ef512d651/assets/e9b25e4c-b1ac-412c-97b7-91990c308b02/configure [ id = nihal-district / password = Test@123 ]
2. Create a camera preset
3. See error

**Expected behavior**

created camera preset should be visible in the asset page

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/bcc85170-46fe-4b31-8329-052a7e5488a0)

**Comment by rithviknishad** [comment]
Issue from #6484
