### ISSUE TITLE
Show ICU Admission Date and Time in Discharge Summary / Consultation Page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6731]
**Describe the bug**
Currently, ICU admission date is shown only in Edit Consultation Details

**To Reproduce**

1. Create a consultation with Transfer within Facility

**Expected behavior**
- [ ] Show ICU admission date in Discharge Summary
- [ ] Show ICU admission date in consultation page
- [ ] Show ICU admission date in post discharge timestamp details

<img width="508" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/cd3156bc-2844-4c32-909a-e9cc696ce8c2">

**Comment by rithviknishad** [comment]
@aparnacoronasafe

**Comment by nihal467** [comment]
- [ ] make it visible in the bottom of the page and discharge summary
