### ISSUE TITLE
Route to facility for old patient record is marked null

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6741]
**Describe the bug**
Follow-up : https://github.com/coronasafe/care_fe/issues/4496

Currently, the data before the Status during the consultation ( currently route to facility ) , was introduced, this whole field is considered as null, but since we disabled the field, any old patient record which are still live are not able to update the consultation page.

**To Reproduce**

1. Go to any patient record before status during the consultation field introduced
2. Click on edit consultation
3. try to update the consultation

**Expected behavior**

if the route to facility field is null by any chance, the should be made enabled to edit, incase it has data, it should be disabled field

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/e9e51215-fdfe-4545-9142-c2efdcae8581)

**Comment by rithviknishad** [comment]
Example: https://care.ohc.network/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095/patient/a709c84e-28e8-41ee-bf5e-f7beb7e859f3/consultation/e38edfd5-bf18-40bd-8cc8-0c46b484dd39/update

**Comment by rithviknishad** [comment]
Another example: https://care.ohc.network/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/e8709ecf-2f3f-4b35-94fe-75da962a0acd/consultation/f7747ab9-8b74-4461-a7ff-747b1cd24223/update
