### ISSUE TITLE
Patient Advanced Filter: filter by review missed

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6745]
**Is your feature request related to a problem? Please describe.**
Currently there's no direct way to filter patients list by review missed.

**Describe the solution you'd like**
Support for filtering patients by review missed

**Comment by jainvedant392** [comment]
Hey @rithviknishad, I am willing to contribute to this issue, is it open to contribute?

**Comment by rithviknishad** [comment]
Hey @jainvedant392 
Could you mention how you are planning to solve this?

As this might require changes to backend too to support it.

**Comment by jainvedant392** [comment]
Actually I was thinking the same to discuss this with you, as I am feeling to know some more on this issue briefly.

**Comment by jainvedant392** [comment]
Could you brief me a little?

**Comment by rithviknishad** [comment]
So if you go to the consultation dashboard, and file a log update, you can specify when the net review should be.

<img width="1003" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/12d1881b-dd50-408a-b361-2748cb21cb1f">

If no review is performed by that specified time, you'll get to see that "Review missed" badge.

<img width="1533" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/cf22bad7-9e52-4752-87af-8703fb6ee26a">

<img width="678" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/f43e5d0f-f8d7-4f3a-8bc4-45915e95bbcd">

**Comment by jainvedant392** [comment]
OK, so we will have a badge for "Review Missed" if the patient is not reviewed in the specified time. And the issue is to filter out the "not reviewed" patients from patient list by creating it's category in the filter.

**Comment by jainvedant392** [comment]
And to solve this, we can create a get request in the backend, which will return the list of those patients only who have this badge.

**Comment by jainvedant392** [comment]
Am I correct in getting this?

**Comment by rithviknishad** [comment]
Yes, more specifically, you'll need to add a filter to the existing list patients' GET API endpoint.

**Comment by jainvedant392** [comment]
Yes yes I got that. So can I get this issue assigned?

**Comment by jainvedant392** [comment]
Hello @rithviknishad, could you please answer a doubt of mine? Whenever I run the project locally, the first page which appears is the login page. But since I don't have any account, so how can I navigate to other pages of the site for working on them. Are there any credentials through which I can login to the site.

**Comment by rithviknishad** [comment]
Have you read the README?

https://github.com/coronasafe/care_fe/?tab=readme-ov-file#-staging-api-credentials

**Comment by jainvedant392** [comment]
OK I got it. I did read it before, but I didn't understand that particular block of README.

**Comment by jainvedant392** [comment]
Thanks for clearing it.

**Comment by jainvedant392** [comment]
Hey @rithviknishad, when we click the "Advanced Filters" button on the "Patients" page, we have 4 categories in the SlideOver - Patient Details based, Date based, Geography based and COVID Details based. So I wanted to ask under which category should I put the "Review Missed" filter option?

**Comment by rithviknishad** [comment]
Patient Details based

**Comment by jainvedant392** [comment]
OK!

**Comment by jainvedant392** [comment]
Hello @rithviknishad , in the code block of showing the chip of "Review Missed", the chip has been conditionally rendered using some criteria and properties of the patient object from the "patientList" in ManagePatients.tsx

**Comment by jainvedant392** [comment]
So my idea was to create a "is_review_missed" field in the patient object, and assigning th values to it using the same criteria, and then adding the filter based on this particular field.

**Comment by jainvedant392** [comment]
Like other fields as gender, age, telemedicine, etc.

**Comment by rithviknishad** [comment]
Just clarifying the wording, you will be adding the filter in the patients viewset right? And not an additional field in the patient/consultation model right?

**Comment by jainvedant392** [comment]
There are filelds like review_interval and review_time in the PatientModel, so if I create a review_done field in the PatientModel, then according to you, how can I handle the filters with the help of it ?

**Comment by jainvedant392** [comment]
> Just clarifying the wording, you will be adding the filter in the patients viewset right? And not an additional field in the patient/consultation model right?

Actually what I was trying to do was finding a way to add a filter for review missed in the same way as the "Review Missed" chip is shown on a patient's card.

**Comment by jainvedant392** [comment]
Also currently, there is no patient having the review missed chip, is there was any, it would be easier for me to check the filter once it's made.

**Comment by rithviknishad** [comment]
Consultation on page 1: https://care.ohc.network/facility/fa4942c3-dce3-477e-81b2-7c95cd18b5da/patient/b26e30ab-7557-42d5-a5fb-14f23c086964/consultation/fae6f90b-c8d9-4593-83ff-1918f7a9bafd

<img width="1234" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/c0536aba-4ee3-4701-9171-273ece66674b">

**Comment by jainvedant392** [comment]
> > Just clarifying the wording, you will be adding the filter in the patients viewset right? And not an additional field in the patient/consultation model right?
> 
> Actually what I was trying to do was finding a way to add a filter for review missed in the same way as the "Review Missed" chip is shown on a patient's card.

What about this ?

**Comment by rithviknishad** [comment]
> There are filelds like review_interval and review_time in the PatientModel, so if I create a review_done field in the PatientModel, then according to you, how can I handle the filters with the help of it ?

You need not add a field in the model. You could simply annotate with an expression (same expr. as in FE) and filter by that annotation's value.

**Comment by jainvedant392** [comment]
OK sure.
