### ISSUE TITLE
Patient List Updated relative time is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6747]
![image](https://github.com/coronasafe/care_fe/assets/57055998/aceac764-1621-4b84-9d33-9769b8c57b40)
![image](https://github.com/coronasafe/care_fe/assets/57055998/ed51bd69-5faa-4ab3-b2ef-50f646ea8076)
![image](https://github.com/coronasafe/care_fe/assets/57055998/1c8b5a24-8ad4-45be-b1e5-e087d0607b82)

- [ ] review missed badge, 5 days ago than the latest modified date
- [ ] The latest modified date is in sync with the latest log update, but the patient list view is showing 9 days ago,

**Comment by Ashesh3** [comment]
Unable to reproduce the issue. Need more details about the patient, specifically regarding any changes made in the last few days that could have led to this mismatch.
