### ISSUE TITLE
Assign Bed throws error "Cannot create conflicting entry" even though no bed was allocated previously

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6748]
**Describe the bug**
Assign Bed throws an error "Cannot create conflicting entry" even though no bed was allocated previously

**To Reproduce**

1. Attempt to assign bed for this [consultation](https://care.ohc.network/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/e8709ecf-2f3f-4b35-94fe-75da962a0acd/consultation/f7747ab9-8b74-4461-a7ff-747b1cd24223)

**Expected behavior**
If the bed is already occupied, the option for selecting such beds should be disabled by either showing "Occupied" badge or the bed should be hidden.

Otherwise, if there are no conflicting entries, it should allow to assign the bed.

**Screenshots**
<img width="1710" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/1baa3dc2-e297-498a-96a7-e073b296ff71">

**Comment by rithviknishad** [comment]
Bed is vacant too btw

<img width="1390" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/0791feef-a714-40c6-80d0-179ff5b96252">

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign it to me.

**Comment by sriharsh05** [comment]
@rithviknishad 
I have a doubt regarding this issue. When I try to assign or switch a patient to another bed, the feature works perfectly fine. However, the error only occurs with the bed you provided (eafefo). I even attempted to create new patients and assign them to that bed (eafofo), but it still throws the same error. There doesn't seem to be any issue with the new beds created. Is it possible that the problem lies only with that specific bed, or am I missing something?

**Comment by sriharsh05** [comment]
The bed eafefo was created on "2022-07-15T12:44:16.229074+05:30". Can the problem be related to the creation date of that bed?

**Comment by rithviknishad** [comment]
How would the creation date of that bed be a problem? It could be a problem with that specific bed, but what exactly is the problem? If it's vacant, then it should be assignable with current time right?

**Comment by Pranshu1902** [comment]
@rithviknishad I am not able to recreate the issue, I can assign that exact bed `eafefo` to patients with or without bed history
[Example Patient](https://care.ohc.network/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/8da567dc-7cd0-43af-900d-d101e3150d8b/consultation/47fc6ca8-a8e0-4c40-9f6e-cc1db83ea958)

**Comment by sriharsh05** [comment]
@Pranshu1902 
The error message is thrown when you change beds with in same minute.
To reproduce:
Switch a patient within 2 fixed beds alternatively.

**Comment by Pranshu1902** [comment]
> @Pranshu1902 The error message is thrown when you change beds with in same minute. To reproduce: Switch a patient within 2 fixed beds alternatively.

yeah, I guess that is intentional to block switching withing the same minute
