### ISSUE TITLE
Form default date time values: To be current date time instead of date time at which app was loaded

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6751]
**Describe the bug**
Default date time for forms are default date and time at which app was loaded and not when the component was mounted into view.

**To Reproduce**

1. Open CARE app and keep yourself logged in for couple of minutes. Observe the system date and time at which you opened the CARE app.
2. After couple of minutes of login, attempt to create a consultation
3. Observe that the default date and time filled for admission date is the date and time at which CARE app was loaded and not when the consultation form was opened.

**Expected behavior**
The default date and time if the current date time is intended to be default should be the current date and time when the component is mounted and not when the app was loaded.

**Screenshots**

Notice the system date and time (top right) and admission date and time.

<img width="1710" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/fed52311-98e4-4cb0-bcbf-7504bfa3a577">

**Comment by shyamprakash123** [comment]
I want to work on this bug, can you assign me?
