### ISSUE TITLE
CARE reloads when a patient is discharged

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6756]
**Describe the bug**
When "Discharge From Care" is submitted, the entire CARE app reloads causing it to fetch all the resources again.

**To Reproduce**

1. Discharge a patient

**Expected behavior**
Instead of refreshing the page, just trigger the refetch of appropriate queries to cause it to re-render with new state.

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign it to me.

**Comment by rithviknishad** [comment]
Just updating this issue, we have `window.location.reload()` in multiple places. These can also be solved.

<img width="491" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/d297b6da-7c8b-4eaf-8a5c-7204e6126213">
