### ISSUE TITLE
Eslint not working locally

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#6758]
**Describe the bug**
Whenever I push some changes, the eslint test fails with the error message as shown in the screenshot.

**Expected behavior**

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/70687348/0337c887-a901-4292-b7e4-7926bdcdc3b7)

I am using:
- Yarn
- Node 18.13.0

**Comment by Pranshu1902** [comment]
@gigincg @khavinshankar @nihal467

**Comment by rithviknishad** [comment]
Have you tried `npm i` or `bun install` instead of `yarn`?

**Comment by Pranshu1902** [comment]
> Have you tried `npm i` or `bun install` instead of `yarn`?

It worked with `npm i`. Thanks
Closing this issue
