### ISSUE TITLE
Page scroll resets to top when switching to medicines tab

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6765]
**Describe the bug**
Page scroll resets to top when switching to medicines tab

**To Reproduce**

1. Go to a consultation dashboard
2. Scroll down a bit
3. Switch to medicines tab.

**Expected behavior**
When we switch tabs in the consultation dashboard, page scroll should not be reset for any tabs (except Feed tab where it scrolls to fit feed in view).

**Screenshots**
<img width="1707" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/490ee687-4147-4575-8bf1-6b626e569b1f">

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Can you assign this to me?

**Comment by AshrafMd-1** [comment]
@rithviknishad for some reason this happens like randomly
sometimes it happens and sometimes it doesn't 
I feel like this is due to the fact that before loading of data there is empty space due to which the whole page height becomes small making it to scroll top

**Comment by AshrafMd-1** [comment]
like this happens for all tabs when the loading screen is present or the data is small it suddenly changes the scroll position as the page height becomes small

**Comment by rithviknishad** [comment]
Maybe two workarounds together would help fix this:

1. when we click on a tab, we should scroll such that the tab goes to the top of the screen instead of just preserving the current scroll position.
2. Show `<Loading />` component or any component that takes `h-screen` height until the actual content is loaded. if the content is shorter than h-screen we could fill it with whitespace for remaining vertical space? (Or in other words, place the content in a div that is `min-h-screen`)
