### ISSUE TITLE
Bed Name and Location Name not distinguishable in Bed Select

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6767]
**Describe the bug**
As attached in the screenshot, the bed name: "Bed. 90" and location name: "Local" is shown without being distinguishable.

**To Reproduce**

1. Open Assign / Switch Bed from Consultation Dashboard

**Expected behavior**
Bed Name and Location Name should be separately identifiable.

**Screenshots**
<img width="802" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/ac5223de-eee3-45c2-8a99-74c5d480eaff">

**Comment by kshitijv256** [comment]
I want work on it

**Comment by kshitijv256** [comment]
@rithviknishad how should bed name and location name be separated. by `,` ,  `/` , location in `[ ]` or maybe add `in` between bed name and location name or any other suggestions
### examples
![Screenshot from 2023-12-02 23-06-57](https://github.com/coronasafe/care_fe/assets/101321276/10c6f303-4c7b-46c3-8a0e-8159ff01fa20)
![Screenshot from 2023-12-02 23-07-15](https://github.com/coronasafe/care_fe/assets/101321276/872912d0-f246-4794-970b-0d22db574068)
![Screenshot from 2023-12-02 23-07-42](https://github.com/coronasafe/care_fe/assets/101321276/298201ba-039c-499b-b9fa-3de2c959c56c)
![Screenshot from 2023-12-02 23-08-16](https://github.com/coronasafe/care_fe/assets/101321276/316690b2-167b-4487-aac0-520d9bca8261)
