### ISSUE TITLE
Prescriptions Details Card is not responsive in Bulk Administer Medicines slideover

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6768]
**Describe the bug**
Prescriptions Details Card is not responsive in Bulk Administer Medicines slideover

**To Reproduce**

1. Go to medicines section of a consultation
2. Add a prescription if none is present.
3. Open Bulk Administration view

**Expected behavior**
The Prescription Details Card should be responsive.

**Screenshots**
<img width="914" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/caebb387-e12f-449a-bb09-c80fdf968b0c">

**Comment by nihal467** [comment]
in windows : 

![image](https://github.com/coronasafe/care_fe/assets/57055998/e8703d27-9ded-4b1b-89a7-5561e09f1ab2)

**Comment by sagarkori143** [comment]
I want to work on this issue. Please assign it to me.

**Comment by nihal467** [comment]
it is already resolved
