### ISSUE TITLE
Timeline style view for Bed Allocation History

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6771]
**Is your feature request related to a problem? Please describe.**
Now that we have a reusable timeline component in CAREUI, how about we show Bed Allocation History in Timeline Format?

<img width="880" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/2257dc17-e5cd-423d-86c2-8449878e2c8b">

<img width="768" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/a42d5048-4611-4022-91d6-8fff720f70b5">

**Comment by thedevildude** [comment]
Hi, can you assign it to me?

**Comment by thedevildude** [comment]
@rithviknishad I've started working on the issue. Couldn't work on it due to Semester exams.

**Comment by rithviknishad** [comment]
@thedevildude any updates on this?

**Comment by thedevildude** [comment]
Yes I've posted one yesterday on slack general channel
