### ISSUE TITLE
Asset Update: Selected location not being shown for some cases

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6773]
**Describe the bug**
For the particular asset, the asset location is not being shown in update asset form.

http://care.ohc.network/facility/01810c32-ec26-494a-9e65-40e5547a7746/assets/150aa43f-5fdd-43ce-ac46-df1cc32556b9

**To Reproduce**

1. Go to http://care.ohc.network/facility/01810c32-ec26-494a-9e65-40e5547a7746/assets/150aa43f-5fdd-43ce-ac46-df1cc32556b9
3. Observe the location
4. Click on update asset
5. Observe the location in the form

**Expected behavior**
The already selected location must be shown

**Screenshots**
<img width="1822" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/784194fe-8193-4f29-9c45-78558b308df7">

<img width="1822" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/dcf1e9bd-4dc7-4718-bcb5-5019ca5883d0">

**Comment by vivramkrishna** [comment]
I would like to work on it can you please assign me

**Comment by konavivekramakrishna** [comment]
![image](https://github.com/coronasafe/care_fe/assets/101407963/81312126-a627-482e-b347-1a0087eccf33)
![image](https://github.com/coronasafe/care_fe/assets/101407963/dc6c3c77-5475-48bc-a630-0926cb0db3f4)
![image](https://github.com/coronasafe/care_fe/assets/101407963/a1949d12-10b0-4146-b53d-51a8e5da85fe)
![image](https://github.com/coronasafe/care_fe/assets/101407963/5f288f64-5276-44c9-8c55-a2033cea93bc)


I tried to hardcode and selected the default Location 2 ID but didn't understand why it is not showing location2 Even on selecting Location 2 it's not getting selected 

The ID's test asset and location2 are the same both have the same id is this the reason why it's not showing the location2 in the field?
`c3b2a9c7-dcc4-4ec0-bb08-97ab3782d311`

**Comment by vivramkrishna** [comment]
![image](https://github.com/coronasafe/care_fe/assets/101407963/81312126-a627-482e-b347-1a0087eccf33)
![image](https://github.com/coronasafe/care_fe/assets/101407963/dc6c3c77-5475-48bc-a630-0926cb0db3f4)
 

I tried to hardcode and selected the default Location 2 ID but didn't understand why it is not showing location2 Even on selecting Location 2 it's not getting selected 

`c3b2a9c7-dcc4-4ec0-bb08-97ab3782d311`

**Comment by rithviknishad** [comment]
Have you checked the network responses? Maybe it could be because the selected location was not able to be matched with any of the items in the response, probably because it was beyond the first page (since it's a paginated response).

If that's the case, have a look at how `useAsyncOptions` is used in other places for such cases (which would require `LocationSelect` to be refactored), or if you have other ways to merge the selected option with the response from the paginated list items.

**Comment by parthksingh1** [comment]
Hey @rithviknishad , I'm interested to work on this issue, can I please get it assigned?

**Comment by rithviknishad** [comment]
@parthksingh1 Feel free to take this up once two of your other assigned issues are approved

- https://github.com/coronasafe/leaderboard/issues/219
- https://github.com/coronasafe/care_fe/issues/6974

**Comment by Keshav-0907** [comment]
@rithviknishad I want to work on this issue, can you please assign this to me

**Comment by Ashutosh0602** [comment]
@rithviknishad I was looking over this issue but I found that it is working properly on system.

This image is assets page showing location:
<img width="1426" alt="Screenshot 2024-02-24 at 4 42 38 AM" src="https://github.com/coronasafe/care_fe/assets/85889617/4f06bd98-83fb-455c-b64c-1a8377af8624">


This image on update page showing location correctly:
<img width="1412" alt="Screenshot 2024-02-24 at 4 42 50 AM" src="https://github.com/coronasafe/care_fe/assets/85889617/52df7bdd-1aa4-4f56-908f-3f325da17d29">

**Comment by Keshav-0907** [comment]
@rithviknishad @Ashutosh0602 
Indeed, I've also thoroughly checked for all the Assets, and everything appears to be in good working order.

**Comment by rithviknishad** [comment]
Seems to be not reproducible right now.
