### ISSUE TITLE
Clear selection tooltip shown even when mouse is hovered on the add button instead of clear selection button

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6776]
**Describe the bug**
Clear selection tooltip shown even when mouse is hovered on the add button instead of clear selection button

**To Reproduce**

1. Go to users tab
2. Open linked skills tab

**Expected behavior**
Tooltip to be shown only when mouse hovered on clear selection button

**Screenshots**
<img width="398" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/77dd04e7-f759-4d4c-8773-db4c7ec406eb">

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by sagarkori143** [comment]
Hello @AshrafMd-1, I'm interested in working on this issue. If you're not currently handling it, could you please let me get assigned to this issue? Thank you!

**Comment by AshrafMd-1** [comment]
Hey @sagarkori143 ,
I am working on this issue.
There are many other issues you can take up.

**Comment by rithviknishad** [comment]
https://github.com/coronasafe/care_fe/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee
