### ISSUE TITLE
Don't allow adding of linked skills for users in other districts other than Ernakulam

### ISSUE THREAD

**Issue by AshrafMd-1** [coronasafe/care_fe#6782]
**Describe the bug**
Currently, If you are a user from a different district and we click on add skills it shows an error and says `not found`

**To Reproduce**

1. Go to users
2. Click on the linked skills of a user from a different district 
3. Select a skill and click on add

**Expected behavior**
We should not be able to add skills of users from different district 

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/98876115/e65ffb8c-7150-4303-86d9-ff3a3b8a8cf2)
![image](https://github.com/coronasafe/care_fe/assets/98876115/88db2af1-bfee-47c3-9a59-646248abda1e)
![image](https://github.com/coronasafe/care_fe/assets/98876115/1081b88c-296a-46a2-b3ac-5103efca3bd8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nihal467** [comment]
@AshrafMd-1 Modify the issue's content and heading to make it easily understandable. The issue is related to district admin access-related to linking skills to other users. Re-Structure the content and heading in a more specific manner.

**Comment by nihal467** [comment]
@AshrafMd-1 https://github.com/coronasafe/care_fe/issues/6633 , already a co-related issue is open,

**Comment by rithviknishad** [comment]
Closing as duplicate
