### ISSUE TITLE
Disable Submit button in normal log update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6787]
**Describe the bug**
Related to PR : #6738 

when we merge the above PR, user will be able to create blank normal log update, so it will be creating blank records in the normal log-update

**To Reproduce**

**Expected behavior**

- [ ] disable the submit button for the normal log update unless anyone of the fields shown in the screenshot have data inputted by the user

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/24a80357-0b3d-4eac-994b-d4b4c00d65ad)

**Comment by rithviknishad** [comment]
@Pranshu1902 escalating as P2 as #6738 is waiting for this and it'd be nice to ship that out soon

cc: @nihal467
