### ISSUE TITLE
Redirection: when deleting asset, user is taken to universal asset page instead of facility asset page

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6804]
**Describe the bug**

**To Reproduce**

1. Go to Facility> View Asset 
2. Click on any one asset
3. Delete the Asset
4. Redirection is to the universal asset page, rather than the facility specific asset page

**Expected behaviour**
When the user navigates to an asset from facility-specific asset page, once the asset is deleted, the user must be redirected to the facility-specific asset page.

**Comment by Pranshu1902** [comment]
@aparnacoronasafe not able to re-create the issue

[Screencast from 2023-12-07 16-20-34.webm](https://github.com/coronasafe/care_fe/assets/70687348/7f6d467a-33c4-4bd8-a4d2-b6c26b3523de)

**Comment by rithviknishad** [comment]
Closing as completed via https://github.com/coronasafe/care_fe/commit/f992917be084ee53a021a957abff49b3fe7abbc0
