### ISSUE TITLE
Hide Camera Feed button for patient with no bed assigned

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6809]
**Describe the bug**

Camera Feed button on the top right of the page is currently shown if there is no bed is assigned to the patient

**To Reproduce**

1. Go to patient consultation file with no bed assigned
2. See error

**Expected behavior**

Hide Camera Feed button on the top right of the page if there is no bed is assigned to the patient

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/d2ea9577-9e57-43bf-90e0-a5322f4d29d7)

**Comment by shyamprakash123** [comment]
I want to work on this, can you assign me?
