### ISSUE TITLE
Patient transferred notification shows UUID instead of patient name

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6811]
**Describe the bug**
Patient transferred notification shows UUID instead of patient name

**To Reproduce**

1. Add patient that already had a consultation
2. Transfer the patient to new facility

**Expected behavior**
Show name in place of UUID

**Screenshots**
<img width="427" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/d15bfa30-61e2-4f4b-9f87-ca5e880ce2f7">

**Comment by vivramkrishna** [comment]
![image](https://github.com/coronasafe/care_fe/assets/101407963/8ab65ef5-7cff-4920-aed6-d742c0b44b3f)
![image](https://github.com/coronasafe/care_fe/assets/101407963/e26da479-ffeb-4193-bedc-93050134b7fe)

the API response does not contain the patient name

**Comment by rithviknishad** [comment]
Why do you need the patient name from the transfer API?

The front end is already aware of the patient object before even the transfer API is called. Users can see the patient's name in the transfer modal right?

**Comment by konavivekramakrishna** [comment]
I tried to replicate it but couldn't manage to get the expected message
![image](https://github.com/coronasafe/care_fe/assets/101407963/7032c4cc-4ac9-4e81-83ca-6989b3afee87)
![image](https://github.com/coronasafe/care_fe/assets/101407963/c910e5ab-5bc0-4073-8c33-ac1d725b0f6e)

**Comment by rithviknishad** [comment]
No, this is shifting, not this.

You'll have to do the following to to "Patient Transfer"

- Click Add Patient
- Type phone number of an existing patient's phone number (can be discharged or active patient)
- This will prompt you asking whether the patient is one of in the list.
- Next it'll ask you to select a patient from that and verify the date of birth.
- Once successful, you'll be able to transfer the patient and land to consultation page.
