### ISSUE TITLE
Add consultation button is disabled in mobile view but not in desktop view

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6812]
**Describe the bug**
Add Consultation button is disabled in the mobile view but not in the desktop view

**To Reproduce**

1. https://care.ohc.network/facility/5092d953-6742-49b0-b1e3-025c53a89e8a/patient/0890932a-2d6b-434a-86ed-49163c750b5c

**Expected behavior**
THe disabling logic for both should be identical

**Screenshots**
<img width="2350" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/53daf2eb-0026-4281-a7a6-f73c1ff0e8c1">

<img width="2350" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/0f4eab31-e150-48a3-85eb-2cddca17e1c3">

**Comment by kshitijv256** [comment]
I would like to work on it
