### ISSUE TITLE
Add keyboard shortcut "Cmd + Enter" / "Shift + Enter" to send doctor notes

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6817]
**Expected behavior**
When "Cmd + Enter" (for mac) or "Shift"+"Enter" (for non mac) is pressed while doctor notes message is in focus, it should send the message

**Screenshots**
<img width="449" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/85dd449b-6eee-4a05-a1df-9a2bd035c90b">

**Comment by dipandhali2021** [comment]
Hey, @rithviknishad ,please assign this to me
