### ISSUE TITLE
Asset uptime and operate asset is not working

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6821]
**Describe the bug**
Asset uptime and operate asset is not working

**Screenshots**
<img width="1850" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/381f39f4-3b40-4a1c-93b2-5d655347a526">

**Comment by Ashesh3** [comment]
Issue was an `_` in the middleware hostname. For more info refer: https://github.com/coronasafe/care/pull/1759#issuecomment-1848949837
