### ISSUE TITLE
Patient Notes UX improvement

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#6824]
- [ ] submit by pressing enter on the keyboard
- [ ] have a draft feature for the messages that were typed and not posted _(this should also fix the issue of typed message going away when going full screen or vice versa)_

Patient Notes (Doctor Notes) can be access from patient consultation dashboard
<img width="1455" alt="image" src="https://github.com/coronasafe/care_fe/assets/29787772/99445d54-2b01-47ee-bfc5-86d23b354be8">

**Comment by rithviknishad** [comment]
First task related to: https://github.com/coronasafe/care_fe/issues/6817

**Comment by shramanpaul** [comment]
I would like to work on this issue. Could you please assign it to me? @rithviknishad

**Comment by shramanpaul** [comment]
The first task is complete of submitting by pressing enter key  

https://github.com/coronasafe/care_fe/assets/110323017/20454e28-3c27-4d4c-b919-c33dfa6bc43b

please have a review @rithviknishad

**Comment by rithviknishad** [comment]
@shramanpaul could you link the PR to this issue? I'm unable to find out your PR for review.

**Comment by shramanpaul** [comment]
ok @rithviknishad

**Comment by shramanpaul** [comment]
@rithviknishad I have again created the PR but by now there are merge conflicts i have also attached the video in the PR when it was working

**Comment by shramanpaul** [comment]
what should i do next @rithviknishad for the successful merging of this PR ?

**Comment by rithviknishad** [comment]
Reviewed, changes suggested
