### ISSUE TITLE
Shift level of consciousness from critical care log update to normal log update

### ISSUE THREAD

**Issue by AshrafMd-1** [coronasafe/care_fe#6839]
**Describe the bug**
This is related to issue #6433

Currently, the mews component requires 5 parameters to give a rating
- Respiratory rate per minute
- Heart rate per minute
- Systolic blood pressure
- Conscious level
- Temperature

All these are available in normal log updates except **consciousness** which is available only in critical care log update 

So for ease of use add the Level of consciousness present in the critical care log update to the normal log update.

![image](https://github.com/coronasafe/care_fe/assets/57055998/177fcc59-2dde-4839-8aa1-f3321c83fba3)

**To Reproduce**

**Expected behavior**

![WhatsApp Image 2023-12-28 at 13 05 08_236f7fe8](https://github.com/coronasafe/care_fe/assets/57055998/195b8445-976f-4a1c-8a93-42ba85860c12)

**Screenshots**

**Comment by Ashesh3** [comment]
![image](https://github.com/coronasafe/care_fe/assets/3626859/1fe6ae92-3ef4-45ad-8560-f40604aecfdd)

@aparnacoronasafe could you review this design?

**Comment by nihal467** [comment]
@Ashesh3 we don't need to separate it as neurological monitoring with the heading : Finalised after a call with aparna
