### ISSUE TITLE
UI for Location Management Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6843]
follow-up : #6592 

![image](https://github.com/coronasafe/care_fe/assets/57055998/b6cc93f1-df9c-44f6-88b9-c99ae6105118)

- [ ]  Create a badge to show location type in the location list page
- [ ]  create a mock up entire UI of the location list where location name, location description, middleware address, buttons, location type, created date and modified date

**Comment by GokulramGHV** [comment]
@rithviknishad can I take this up?
