### ISSUE TITLE
Care Date Time Component

### ISSUE THREAD

**Issue by vivramkrishna** [coronasafe/care_fe#6858]
**Is your feature request related to a problem? Please describe.**
Currently, in CARE we have a Custom Date Component for date input (not browser default).

In CARE, we currently use the browser default date/time input field.

We need to create a custom date/time component for input both date and time.
![image](https://github.com/coronasafe/care_fe/assets/101407963/9109c8c3-8a5e-4c11-a71b-41a6a01c4ed4)
![image](https://github.com/coronasafe/care_fe/assets/101407963/cd34a89e-55c2-4316-b0e8-4240fddd518e)

**Comment by konavivekramakrishna** [comment]
@rithviknishad can you please assign me

**Comment by vivramkrishna** [comment]
@rithviknishad 

can you please assign me

**Comment by vivramkrishna** [comment]
![image](https://github.com/coronasafe/care_fe/assets/101407963/f1c7b468-a676-4cbb-bd48-9d724c33ba80)
![image](https://github.com/coronasafe/care_fe/assets/101407963/68fbe0c8-35a9-4508-8260-78cc7bba78c1)
![image](https://github.com/coronasafe/care_fe/assets/101407963/4a2f32d3-17db-464a-b3e6-c5f5535d691b)

@Ashesh3 @rithviknishad 

can you please look into this

I am trying whether we can implement an infinite scroll for hours and minutes. Currently, when a user reaches the end, i.e., 23 hours or 59 minutes, the scroll stops. However, in the browser's default date-time input, the scroll is continuous.

**Comment by Ashesh3** [comment]
@konavivekramakrishna I've created a quick fiddle with the logic you are expecting, check it out if that helps.

https://codesandbox.io/p/sandbox/react-scroll-time-j7ln3y

**Comment by konavivekramakrishna** [comment]
@Ashesh3 

I implemented it, when checking it in mobile the scroll is not working the minutes are constant
I checked the same with the link you provided in mobile, same issue, unable to scroll

🥲

**Comment by vivramkrishna** [comment]
@Ashesh3 @rithviknishad 
Could you please check the following link on a mobile device and suggest any improvements for scrolling


https://codesandbox.io/p/sandbox/react-scroll-time-forked-nxnxjn
https://nxnxjn.csb.app/

**Comment by Ashesh3** [comment]
> @Ashesh3 @rithviknishad Could you please check the following link on a mobile device and suggest any improvements for scrolling
> 
> [codesandbox.io/p/sandbox/react-scroll-time-forked-nxnxjn](https://codesandbox.io/p/sandbox/react-scroll-time-forked-nxnxjn) [nxnxjn.csb.app](https://nxnxjn.csb.app/)

Let's not over engineer it. Do not make it infinite scroll, just make it a static list. User can scroll up or down to select the time. 
Reference:
![msedge_TqHT60p5fh](https://github.com/coronasafe/care_fe/assets/3626859/c0d6abac-5883-409c-b393-a186724ad276)

**Comment by nihal467** [comment]
@konavivekramakrishna Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by Vasanth375** [comment]
@Ashesh3 @rithviknishad

![image](https://github.com/coronasafe/care_fe/assets/77767837/a7a0da06-69b6-4023-bfe5-f058b476c2cb)
![image](https://github.com/coronasafe/care_fe/assets/77767837/bbfafd20-9ea8-4d6d-b22a-792f5c3bdf94)
![image](https://github.com/coronasafe/care_fe/assets/77767837/d71856e4-bde1-46bc-8a66-67c0e572db61)

Can you please look into this
I have been working on this issue from a few days back. Here are the screenshots of the code and interface.
if you say yes, I will raise a PR

**Comment by rithviknishad** [comment]
@Vasanth375 Nice attempt, few things...

- Could you rethink the UI a bit? It'd be great if it could be kept in a single row.
- You'll need to create a separate component "DateTimeFormField" instead of adding time related inputs to the `DateFormField`. `DateFormField` is intended to be used only for date "ONLY" inputs.

**Comment by Vasanth375** [comment]
@rithviknishad Please check it once, 
I've created a separate component  `DateTimeFormField`
![image](https://github.com/coronasafe/care_fe/assets/77767837/0da3486d-f792-4fd7-acdd-bb057a9346aa)
![image](https://github.com/coronasafe/care_fe/assets/77767837/c44b3178-298d-44e9-812c-c74e1925311e)
