### ISSUE TITLE
Remove Date of Positive & Date of Negative in Treatment Summary

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#6876]
Date of Positive & Date of Negative are irrelavant fields from COVID19 Days. They are even more irrelavant in the Treatment Summary Page.

Here's an example Treatment Summary on the staging instance

https://care.coronasafe.in/facility/fa4942c3-dce3-477e-81b2-7c95cd18b5da/patient/b26e30ab-7557-42d5-a5fb-14f23c086964/consultation/fae6f90b-c8d9-4593-83ff-1918f7a9bafd/treatment-summary

**Comment by kshitijv256** [comment]
I would like to work on it

**Comment by AshrafMd-1** [comment]
Can you assign this to me?

**Comment by gigincg** [comment]
@kshitijv256 Assigned it to @AshrafMd-1 since it's an very urgent issue. 

Will be filing a few more issues this week. 

cc: @nihal467 Please prioritize this issue. It is vital that we ship it this week.

**Comment by kshitijv256** [comment]
Sure, no problem 🙂

**Comment by rithviknishad** [comment]
@gigincg should we also remove the field from being captured in patient registration?

cc: @AshrafMd-1 

<img width="2672" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/03272f30-1947-43cb-9b91-840a441645b2">

**Comment by gigincg** [comment]
@rithviknishad Let the fields be there. Just needs to be removed from Treatment Summary
