### ISSUE TITLE
Close Button in Treatment Summary is Malfunctioning

### ISSUE THREAD

**Issue by vivramkrishna** [coronasafe/care_fe#6877]
**Describe the bug**
When the treatment summary is accessed through the link i.e URL, the close button is malfunctioning 
at times it is completely not working and redirected to a  new tab

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/fa4942c3-dce3-477e-81b2-7c95cd18b5da/patient/b26e30ab-7557-42d5-a5fb-14f23c086964/consultation/fae6f90b-c8d9-4593-83ff-1918f7a9bafd/treatment-summary
2. Click on Close
3. See error

**Expected behavior**
It should be redirected to patient dashboard

CC: @nihal467 @rithviknishad

**Comment by sagarkori143** [comment]
Can you please assign this issue to me?

**Comment by sriharsh05** [comment]
@rithviknishad 
I want to work on this issue. Please assign this to me.
