### ISSUE TITLE
Add IP Number in Treatment Summary

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#6885]
In the Treatment Summary Page, show the IP or OP Number of the Consultation

**Comment by AshrafMd-1** [comment]
I want to work on this issue can you assign me this issue ?

**Comment by AshrafMd-1** [comment]
@gigincg is this format okay
![image](https://github.com/coronasafe/care_fe/assets/98876115/f5893927-0ac2-42db-86c6-916fef450999)

cc @rithviknishad
