### ISSUE TITLE
Fix Loading State in Update Log List

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#6886]
In the Update Log List, in the Patient Dashboard, when you apply a filter, the skeletal loading component is currently being shown on top of the list of updates. 

When Loading, the List of items should be shown & ensure that API failures or timeouts are handled as well.

**Comment by AshrafMd-1** [comment]
I want to work on this issue can you assign me this issue ?

**Comment by Ashesh3** [comment]
@AshrafMd-1 on a quick glance, the loading component is being shown separately that causes it to appear separately on top of the items. So remove the `WhenLoading` part and use 
 `shimmer` with `<LoadingLogUpdateCard />` along with `shimmerCount` in the `<PaginatedList.Items` component itself, or if you want to show the list of items then just omit the loading state altogether.

**Comment by rithviknishad** [comment]
Fix present in https://github.com/coronasafe/care_fe/pull/6808#issuecomment-1862275552

**Comment by AshrafMd-1** [comment]
@rithviknishad then should i unassign myself as the fix is already present

**Comment by Pranshu1902** [comment]
Closed as completed in #6808
