### ISSUE TITLE
Patient transfer function in the registration form is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6895]
**Describe the bug**

A staff user tries to transfer a patient using the option in the patient registration form, where the patient lives in a facility where this user does not have access.

Even though the transfer is not taking place/data are transferred, the successful notification is shown in the front end

**To Reproduce**

**Expected behavior**

Show proper notification mentioning the user doesn't have access to it 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/e99b3424-4ccb-4e19-ac0c-eaf9950c3f54)

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign this to me.

**Comment by Ashesh3** [comment]
Issue is already resolved as per discussion with the team.
