### ISSUE TITLE
Back button in CNS is not Working

### ISSUE THREAD

**Issue by vivramkrishna** [coronasafe/care_fe#6899]
**Describe the bug**
In CNS,
clicking on back button ideally it should redirect to the specific facility or facility tab but clicking on it the page simply refreshes without any changes 
url : https://care.ohc.network/facility/ea9a2fbe-74f3-446b-bdb0-e038766bfb09/cns?page=1&limit=6

**To Reproduce**

1. Go to Facility tab
2. Click on view cns for any facility
3. Click on back button 

**Expected behavior**
it should redirect to the specific facility or facility tab 

cc : @rithviknishad

**Comment by rithviknishad** [comment]
Same issue is present for all tabs too (facility list, patient list, asset list), etc...

Looks like the pagination query parameters are being applied after being mounted causing it to have an additional navigation in the history.

Pressing back takes to the previous URL, but pagination filter gets reapplied, and hence stuck in a loop.

**Comment by AshrafMd-1** [comment]
I want to work on this issue can u assign me this?
