### ISSUE TITLE
Query Parameter in facility bed pagination is not shown

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6906]
**Describe the bug**

When I go to the second page of the facility bed, inside the location management, even though the pagination is working properly , the query parameters are not being shown properly

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/d21d2185-b671-4ab8-a0dd-44ed7d210035/location/5d3fb7c0-128c-4a49-b011-ce3dce661434/beds
2. Click on next page and check the query parameters
3. See error

**Expected behavior**

when we use pagination and go to next page in the bed, the query parameters should be updated and shown

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/99625f2c-bd76-4704-89ab-14136a85d44e)

**Comment by AshrafMd-1** [comment]
I want to work on this issue can u assign me this?
