### ISSUE TITLE
Improve auto-fill experience for patient critical care log update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6917]
**Is your feature request related to a problem? Please describe.**

currently, it's unable to determine which section in the critical care has auto-fill data from its previous patient log update

**Describe the solution you'd like**

When data is auto-fill in the critical care section do the following : 

- [ ]  Add a warning color and unverified badge for sections with auto-fill data in the critical care 
- [ ]  Once the user clicks the complete button, and any unverified data is there, have a dialogue box warning the user that there is still unverified data and you want to continue with the submit.

**Screenshot**

![image](https://github.com/coronasafe/care_fe/assets/57055998/4aa043cf-1f8a-4555-897e-0e28a7c652d3)

**Comment by sagarkori143** [comment]
I'm interested to work on this issue. Can you assign this to me?

**Comment by sagarkori143** [comment]
@nihal467  Could you please help me reproducing the page shown in above image.

**Comment by nihal467** [comment]
1. Login to the platform
2. Select a live patient from the patient tab

**Comment by nihal467** [comment]
@sagarkori143 follow the below steps

1. Login to the platform
2. Select a live patient from the patient tab
3. Then click on the log update button that appears on the right side of the patient consultation page
4. in the log update page, create a critical care round type log update

**Comment by sagarkori143** [comment]
Okay @nihal467 
![image](https://github.com/coronasafe/care_fe/assets/129517558/544b0b71-ee10-45af-9e9d-4e84f2f603a0)

After copying values from the last log :
![image](https://github.com/coronasafe/care_fe/assets/129517558/cd2e0e81-7028-493e-b62e-425a3b06c5f2)



If I am on the right track, I want to know exactly where should I place the warning indicator? Inside the value field or next to the label text.  
What exactly the warning indicator should look like:
1) A svg logo with a tool-tip on hovering OR
2) A clear warning text written OR
3) svg logo and warning text

**Comment by sagarkori143** [comment]
@nihal467  Also few more doubts:
After copying the data from last log update:
a) If user click on any input field but don't change the value.
b) When user change the input field value but the undo all changes.

The data is now verified in both the cases and should not contain any warning right?

**Comment by sagarkori143** [comment]
@nihal467 Please help regarding these doubts.

**Comment by Ashesh3** [comment]
![image](https://github.com/coronasafe/care_fe/assets/3626859/8aeae7ac-9ebb-4a84-9a41-e1d10bbe43a4)

- The background for unverified section should be of the warning class 
- Show `unverified` badge next to the name of the section
- If the user visits the section, then clicks the update details button at the bottom, that should mark the section as verified, i.e removing the unverified badge. 
- The unverified badge and color should only appear for sections having copied data from the previous logs, and not for all the sections.

@sagarkori143

**Comment by Ashesh3** [comment]
@sagarkori143 any updates on this issue?

**Comment by vivramkrishna** [comment]
@Ashesh3 

can you please assign me

**Comment by AshrafMd-1** [comment]
@rithviknishad i want to work on this issue can you assign me this issue

**Comment by AshrafMd-1** [comment]
@Ashesh3 is this UI okay if yes i will start working on the logic 

![image](https://github.com/coronasafe/care_fe/assets/98876115/4c56916b-5a36-48d2-891d-e5c395654d0f)

**Comment by Ashesh3** [comment]
> @Ashesh3 is this UI okay if yes i will start working on the logic
> 
> ![image](https://private-user-images.githubusercontent.com/98876115/318534307-4c56916b-5a36-48d2-891d-e5c395654d0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTc1MzEsIm5iZiI6MTcxMTk5NzIzMSwicGF0aCI6Ii85ODg3NjExNS8zMTg1MzQzMDctNGM1NjkxNmItNWEzNi00OGQyLTg5MWQtZTVjMzk1NjU0ZDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE4NDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NmUxYzk2Y2VmYTEwYmE1NTQyMmI2OWY4MWI1NzY4MTk5MmI0OTJiNmMyZTM4ZTU4ZTUyODc0MmMwYjhkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iBImx_BBuVrOoy15l9dgrdUIL7KCwvN9UOOsGQRKOx4)

This looks good to me! Let's confirm this in tomorrow's EOD call once to finalize it before you start working on it.

**Comment by AshrafMd-1** [comment]
@Ashesh3 okay 

also i feel instead of this UI changing the care tick icon color is better as ona  smaller screen we dont need to redesign it

![image](https://github.com/coronasafe/care_fe/assets/98876115/235c9e00-b635-45b9-a797-a42fe5e2b71c)

**Comment by nihal467** [comment]
the entire thing have been moved to questionnaire
