### ISSUE TITLE
Advanced filter: Patient with no consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6921]
**Is your feature request related to a problem? Please describe.**
At some ICUs nurses forget to file consultations for patients. When there are a large number of active patients, it becomes difficult to sort through them to identify the files without consultation.

**Describe the solution you'd like**
In the advanced filter- patient-based filter, add a filter on top for "status of consultation" with options as "Show all, No consultation filed, consultation filed" 

**Describe alternatives you've considered**

**Additional context**

**Comment by rithviknishad** [comment]
Related issue (but not a duplicate): https://github.com/coronasafe/care_fe/issues/6635 cc: @Ashesh3

**Comment by nihal467** [comment]
message from Aparna : you may close this for now. Let the sorting be implemented. If there is still need from the ground, we will go the filter

**Comment by nihal467** [comment]
@Ashesh3 can you close all the co-related PR and the issue
