### ISSUE TITLE
Log Update - filter

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6931]
**Is your feature request related to a problem? Please describe.**
When a user has applied filter for log update, there is no indication that a filter is in place.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.
](https://care.coronasafe.in/facility/fa4942c3-dce3-477e-81b2-7c95cd18b5da/patient/b26e30ab-7557-42d5-a5fb-14f23c086964/consultation/fae6f90b-c8d9-4593-83ff-1918f7a9bafd)

Apply a filter for log update. You will see a shorter list of log updates. However, the user maynot realise it.

Add a small icon on top of "filter" to show that a filter is in place. 

**Describe alternatives you've considered**

**Additional context**

**Comment by shramanpaul** [comment]
@aparnacoronasafe  @Ashesh3  
![image](https://github.com/coronasafe/care_fe/assets/110323017/941d9705-a448-412a-9872-b8797c24142b)
 
do you mean changes in the highlighted part in the above image?

**Comment by Ashesh3** [comment]
@shramanpaul just for the log updates, not there.

Check out here:
https://care.coronasafe.in/facility/fa4942c3-dce3-477e-81b2-7c95cd18b5da/patient/b26e30ab-7557-42d5-a5fb-14f23c086964/consultation/fae6f90b-c8d9-4593-83ff-1918f7a9bafd

![image](https://github.com/coronasafe/care_fe/assets/3626859/3b7487b8-fb3c-4587-9cd2-ae84f7ec3510)

Just indicate when a filter is active.

**Comment by shramanpaul** [comment]
ok @Ashesh3 
but i am still facing a issue in my screen page not found is coming by your given link 
![image](https://github.com/coronasafe/care_fe/assets/110323017/022472b9-59c7-4613-b48a-a2b034255c71)

I would like to work on this issue. Could you please assign it to me?

**Comment by Ashesh3** [comment]
@shramanpaul  Try this:

https://care.coronasafe.in/facility/f8f05c04-5c97-415c-814d-419ecf692d0e/patient/efab1a72-3a97-4732-b740-c23ac1d71912/consultation/49664bdb-eb58-4841-9446-4baa3baa842b

Use `District Admin` account as per the README file:

```
- username: dev-districtadmin
  password: Coronasafe@123
```

**Comment by shramanpaul** [comment]
yeah i got it please assign me this issue @Ashesh3

**Comment by shramanpaul** [comment]
I am working on it I will be making the PR by today
