### ISSUE TITLE
For patients discharged from CARE, the bed still shows In Use

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#6938]
**Describe the bug**
For patients discharged from CARE, the bed still shows In Use

**To Reproduce**

1. Go to https://care.ohc.network/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/e8709ecf-2f3f-4b35-94fe-75da962a0acd/consultation/f7747ab9-8b74-4461-a7ff-747b1cd24223
2. Click on `Bed History`
3. See error

**Expected behavior**
It should show the end date and the bed should be available to be assigned to other patients

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/70687348/3eeabdd8-98ad-452f-a663-759531e71e90)

![image](https://github.com/coronasafe/care_fe/assets/70687348/b014f1a0-ba0f-46a2-b297-53603c3ff6d7)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign it to me.

**Comment by Pranshu1902** [comment]
@sriharsh05 any updates?

**Comment by Pranshu1902** [comment]
Fixed in [#1820](https://github.com/coronasafe/care/pull/1820)
