### ISSUE TITLE
Route of medicine- Add inhalation/ryles tube

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6939]
**Is your feature request related to a problem? Please describe.**
Route in the prescription module is limited to a few options

**Describe the solution you'd like**
Add the following options:

- [ ] Inhalation
- [ ] Nasogastric/Gastrostomy tube
- [ ] intrathecal injection
- [ ] Transdermal 
- [ ] Rectal

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign this to me.

**Comment by nihal467** [comment]
LGTM
