### ISSUE TITLE
Multiple scrolls- unnecessary: doctor connect 

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6940]
**Describe the bug**
When there are over 5 staff of a particular type appearing on the doctor connect panel, the section (Doctor/staff/teleicu Hub) has a separate scroller while the whole Doctor connect panel has a second scroller. This seems confusing and unnecessery.

**To Reproduce**

1. Go to 'any patient with consultation filed'
2. Click on '.Doctor connect.'
3. if there are over 5 listing in any of the section, you will see a section scroller in addition to the doctor connect panel scroller.

<img width="410" alt="Screenshot 2023-12-29 at 5 44 01 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/96b4803d-72f4-4c1c-834e-ed91f80caee0">

This was done maybe to retain all the section headings in view on the panel.

Can we think of a better visualisation? Maybe collapsable sections?

**Comment by rithviknishad** [comment]
Waiting for changes from #6924

**Comment by rithviknishad** [comment]
@aparnacoronasafe I'm thinking of removing the sections, instead a single list would be shown, however, few things that'd help in improving the UX:

1. Sort will be maintained, doctors followed by staff followed by tele icu hub.
2. A chip will be shown in the user card indicating what group the user belongs to (doctor/staff/teleicu hub)
3. A search bar on top to search for the users

**Comment by thedevildude** [comment]
I'd like to work on the issue

**Comment by thedevildude** [comment]
@aparnacoronasafe 
@rithviknishad 

What do you think of this mockup for doctor connect? I've also added three filter buttons on top for Doctors, Nurses and TeleICU Hub

![DoctorConnect](https://github.com/coronasafe/care_fe/assets/63492939/03e0dfd1-0321-4e94-9a16-051a3953446f)
