### ISSUE TITLE
Group call: Doctor Connect

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6941]
**Is your feature request related to a problem? Please describe.**
Karnataka State will be launching Zoom calls managed by the health department for discussing COVID cases across the state. These calls will be open during designated hours.

CARE doctor connect panel to allow users to join the zoom/gmeet/any other VC.

**Describe the solution you'd like**
Add a section above the "Doctors" section with one button for "Join the Group VC". 

Can we hard code the button to only be active during the designated hours when the VC will be live? 

NOTE: this is a COVID effort. Hence we need not develop it as a full feature where admins can configure the VC link and the timings for now. However, that may come up as a requirement if the model succeeds and is established as a permanent workflow.

**Comment by Ashesh3** [comment]
@aparnacoronasafe Hello, I have a question regarding the proposed Group VC feature. Could you please clarify at what level the group call link will be set up? Will it be at the facility level, location level, or state level? Will there be a single universal link for all? How would you like the overall structure to be?

**Comment by aparnacoronasafe** [comment]
For now lets just do one universal link. 

In the future there could be separate links for clusters. But we will build for it when the requirement comes

**Comment by Ashesh3** [comment]
@gigincg as discussed, should we proceed with this feature by injecting JS through Cloudflare or developing the feature and enable it with a config key?

**Comment by Ashesh3** [comment]
Discussed to inject JS through Cloudflare to deliver this feature for KR instance.

**Comment by Ashesh3** [comment]
JS to be injected - Version 1

```
function isWithinTimeRange() {
    var now = new Date();
    var start = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 8, 0, 0); // 8 AM
    var end = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 20, 0, 0); // 8 PM
    return now >= start && now <= end;
}

function addButton() {
    var targetElement = document.getElementById('doctor-connect-filter-tabs');
    if (targetElement && !document.querySelector('.doctor-connect-button') && isWithinTimeRange()) {
        var button = document.createElement('button');
        button.className = 'btn btn-primary m-1 mb-4 w-full hover:text-white doctor-connect-button';
        button.textContent = 'Join Group Video Call';

        button.onclick = function() {
            window.open('https://www.zoom.com', '_blank');
        };

        targetElement.parentNode.insertBefore(button, targetElement);
    }
}

var observer = new MutationObserver(function(mutations) {
    if (document.getElementById('doctor-connect-home-doctor')) {
        addButton();
    }
});

observer.observe(document.body, { childList: true, subtree: true });
```

![image](https://github.com/coronasafe/care_fe/assets/3626859/2bbdcd58-b07c-4160-8bc6-482e6b9263b7)

**Comment by Ashesh3** [comment]
Update: Feature deployment is tested and working. Waiting for the Zoom link before making it live.

**Comment by Ashesh3** [comment]
Closing as the requested feature is created and tested. Waiting for the Zoom link before it's deployed live.
