### ISSUE TITLE
Symptoms : Expand list

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6942]
Expand list of symptoms to include:

- [ ] Chills
- [ ] General weakness
- [ ] Irritability
- [ ] Confusion
- [ ] Abdominal pain
- [ ] Joint pain
- [ ] Redness of eyes
- [ ] Anorexia
- [ ] New Loss of taste/smell
- [ ] Push "Others" to the bottom of the downtown

**Comment by Omkar76** [comment]
Can someone please assign this to me?

**Comment by sainak** [comment]
@aparnacoronasafe  can we make "New Loss of taste/smell" -> "Loss of taste", "Loss of smell"?

**Comment by aparnacoronasafe** [comment]
@sainak That is actually a good suggestion 

Can you make it "New loss of taste", "New loss of smell"

**Comment by rithviknishad** [comment]
cc: @Omkar76 ☝🏼
