### ISSUE TITLE
Patient registration form: Collect "Post partum"

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6943]
https://care.coronasafe.in/facility/eeb23cb7-1524-479a-825e-660311386b47/patient/51ff0682-065d-4e25-bcc6-fb1b682642fb/update

After Gender is collected, there is a question of whether the patient, if female is anenatal. 

- [ ] Where the female is antenatal, collect the "Date of start of last menstruation" 
_________
- [ ] Right after that, also add "Is Post-partum(< 6 weeks)"- Yes/No
- [ ] If yes, collect date of delivery.

**Comment by Omkar76** [comment]
Can someone please assign this to me?

**Comment by gigincg** [comment]
@aparnacoronasafe Can we move all 4 of these fields to the PatientConsultation ? It does not seem relevant to the Patient Profile. It's very time-specific (implies consultation/encounter specific)

**Comment by nihal467** [comment]
based on the discussion, a new issue have been filed to meet necessary requirements https://github.com/coronasafe/care_fe/issues/7815
