### ISSUE TITLE
Expanding Comorbidities: Medical History

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6944]
**Is your feature request related to a problem? Please describe.**
CARE gathers all underlying medical conditions the patient has (Comorbidities) in the patient registration form, under medical history (https://care.coronasafe.in/facility/eeb23cb7-1524-479a-825e-660311386b47/patient/51ff0682-065d-4e25-bcc6-fb1b682642fb/update). The list is limited.

**Describe the solution you'd like**
Expand the option to include:

- [ ] COPD
- [ ] Bronchitis
- [ ] Chronic neurological or neuromuscular disease
- [ ] Immunocompromised condition
- [ ] Liver Disease
- [ ] TB, if selected "Active/Old" and "treated duration"

- [ ] Kidney diseases to be renamed as "Chronic Renal Disease"

- [ ] Lung diseases/Asthma may be hidden from the list as "Lung diseases" is a very large set of diseases including COPD. Instead, introduce a new item for "Asthma" and "other chronic lung diseases"

- [ ] When "cancer" is selected, have options for "Type of cancer" to select from "Breast (show option only for females)/ Lung/ Skin/ Colorectal/ Uterus (show option only for females)/ Leukaemia/ Bladder/ Prostate (show option only for males)/ Melanoma/ Lymphoma/ Brain/ Liver/ thyroid/ Others)

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign this to me.

**Comment by sriharsh05** [comment]
Unassigned myself because I am already working on 2 other backend issues.

**Comment by shramanpaul** [comment]
@aparnacoronasafe @rithviknishad   I want to work on this issue. Please assign me

**Comment by shramanpaul** [comment]
@rithviknishad could you please assign me this issue? So that I can start working on it

**Comment by shramanpaul** [comment]
(https://care.coronasafe.in/facility/eeb23cb7-1524-479a-825e-660311386b47/patient/51ff0682-065d-4e25-bcc6-fb1b682642fb/update) I received a "Not Found" error. Could you please look into this ? 
![image](https://github.com/coronasafe/care_fe/assets/110323017/825b1b6c-a84e-4c73-be9c-3163d75c700b)

**Comment by shramanpaul** [comment]
I'm still encountering the 'Not Found' error mentioned earlier. Whenever you have a moment, could you please take a look?

**Comment by shramanpaul** [comment]
I'm still encountering the 'Not Found' error mentioned earlier. Whenever you have a moment, could you please take a look?

**Comment by rithviknishad** [comment]
You can create a new patient, that'd lead you to the patient registration form

**Comment by rithviknishad** [comment]
https://care.ohc.network/facility/0421de45-3541-4652-862d-79cec4acb6af/patient/aab8ff1c-10b9-426a-b5b1-d4cbbd675dee/update

**Comment by nihal467** [comment]
@shramanpaul Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by AshrafMd-1** [comment]
@nihal467 i want to work on this issue

**Comment by nihal467** [comment]
non-relevant to current develop
