### ISSUE TITLE
Alignment of search field in tablet view 

### ISSUE THREAD

**Issue by vivramkrishna** [coronasafe/care_fe#6961]
**Describe the bug**
The Search by primary Number field and search by Emergency field are Misaligned

**To Reproduce**

1. Go to Patients tab
2.change the screen size to tablet view

**Expected behavior**
the alignment of search fields should be consistent

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/101407963/bda3d716-f772-42b5-b477-1b9724b5f582)

**Comment by vivramkrishna** [comment]
+1 fix the top i.e header part (buttons are stretched a lot to occupy the entire row, where it can occupy two or three buttons as per the screen size)
![image](https://github.com/coronasafe/care_fe/assets/101407963/7eded129-7222-4974-88df-3bd0fa5ae455)

**Comment by thedevildude** [comment]
Can you assign this issue to me?

**Comment by rithviknishad** [comment]
@konavivekramakrishna this issue can be addressed by the related duplicate issue: https://github.com/coronasafe/care_fe/issues/6648

@thedevildude feel free to take up #6648

**Comment by thedevildude** [comment]
@rithviknishad understood, I'll try take that up start and working on the mock-up
