### ISSUE TITLE
 Add Line breaking support to the doctor notes

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6962]
**Is your feature request related to a problem? Please describe.**

Currently, we can input data in a single line for the doctor notes.

**Describe the solution you'd like**

- [ ] Add a keyboard shortcut , when we click {Enter} , it should break the existing line and start a new row

**Comment by kshitijv256** [comment]
I would like to work on it

**Comment by sagarkori143** [comment]
@nihal467 
There is already an open issue #6824 where Enter button is being implemented to be used for submit purpose.

**Comment by rithviknishad** [comment]
@sagarkori143 the related PR #6915 has already been merged where Cmd/Shift + Enter is being used for submit purpose
