### ISSUE TITLE
Add user details in the asset configuration page, HFR ID, middleware and location

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6972]
**Is your feature request related to a problem? Please describe.**

It is hard to understand which user has updated the asset configuration page, HFR ID, middleware, and location fields related to a facility.

**Describe the solution you'd like**

- [ ] We should display the user ID, along with privileges, time, and date, on the asset configuration page, HFR ID, middleware, and location fields associated with a facility. This way, in later periods, we can verify who updated these fields. ( Added a screenshot of similar thing we implemented in the patient consultation page )
- [ ] Created by and modified by for location management
- [ ] modified by for asset configuration page, HFR ID, middleware, 

**Describe alternatives you've considered**

![image](https://github.com/coronasafe/care_fe/assets/57055998/1125cc82-d62c-44e3-a2ce-51fcfad97826)

**Comment by nihal467** [comment]
- [ ] it will be covered under the events module once its fully built

**Comment by rithviknishad** [comment]
Related issue https://github.com/coronasafe/care/issues/1697

**Comment by nihal467** [comment]
@sainak since the events module is already merged, can you look into it's possibility

**Comment by nihal467** [comment]
non-relevant to current develop
