### ISSUE TITLE
Enhancement to the inventory log entry management

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6983]
**Describe the bug**

The responsive view for the inventory entry log page needs to be improved

**Expected behavior**
![image](https://github.com/coronasafe/care_fe/assets/57055998/66f9c4b7-86f7-4275-ab43-7f697763538c)

- [ ] implement the same card view for the small screen devices in the inventory entry list page same as we have implemented in the minimum quantity

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/8687f1cc-ad76-4ebc-98d6-424070e43559)
![image](https://github.com/coronasafe/care_fe/assets/57055998/2a083476-7328-4cbc-ae6e-4bd1a59083fc)

**Comment by Bhavik-ag** [comment]
Hey @nihal467 I am working on this issue !!

**Comment by nihal467** [comment]
the entire module is getting redesigned
