### ISSUE TITLE
Support for adding description to ICD-11's search

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6995]
**Describe the bug**

ME24.A5 diagnosis is missing in our ICD-11 data present in care

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/c7153cc9-9230-47c1-ac4d-2bc7ca6d6fd8)

**Comment by nihal467** [comment]
1. ACUTE FEBRILE ILLNESS 
2. DIABETIC MELLITUS
3. URINARY TRACT INFECTION 
4. HYPONATREMIA 
5. HAEMATEMESIS 
6. RENAL FAILURE 
7. HEMORRHOIDS 
8. HYPERTENSION 
9. CARDIOVASCULAR DISEASE 
10. FEVER (PYREXIA) OF UNKNOWN ORIGIN

@rithviknishad few more diagnosis are missing, list shared by gayan

**Comment by nihal467** [comment]
- ACUTE FEBRILE ILLNESS ( Missing in ICD-11 central database)
- DIABETIC MELLITUS  ( Missing in ICD-11 care)
- URINARY TRACT INFECTION ( its available )
- HYPONATREMIA ( Missing in ICD-11 care)
- HAEMATEMESIS ( Missing in ICD-11 care)
![image](https://github.com/coronasafe/care_fe/assets/57055998/addfc040-676d-4368-98db-9ae98a4a50bb)

- RENAL FAILURE ( it's part of kidney disease, its available but exact renal failure is not available in care nor in icd-11 )
- HEMORRHOIDS ( Missing in ICD-11 care)
- HYPERTENSION ( Missing in ICD-11 care) 
- CARDIOVASCULAR DISEASE ( Missing in ICD-11 care) 
- FEVER (PYREXIA) OF UNKNOWN ORIGIN ( Missing in ICD-11 care)  MG26 code

**Comment by nihal467** [comment]
Description based search is not available, as we don't have that data , so marking it for discussion

**Comment by sainak** [comment]
related to https://github.com/coronasafe/care/issues/1838

**Comment by Clemo97** [comment]
> **Describe the bug**
> 
> ME24.A5 diagnosis is missing in our ICD-11 data present in care
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> 
> ![image](https://private-user-images.githubusercontent.com/57055998/294849137-c7153cc9-9230-47c1-ac4d-2bc7ca6d6fd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg0OTgsIm5iZiI6MTcwOTcyODE5OCwicGF0aCI6Ii81NzA1NTk5OC8yOTQ4NDkxMzctYzcxNTNjYzktOTIzMC00N2MxLWFjNGQtMmJjN2NhNmQ2ZmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyMjk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OWZhYTNmNjY0YWJkNmNlYzY3ODZhYjkzZDAxZDU5NjJmN2IwMDgwOGJjOGQ3ZTQzZmYzMDE0MTQ1ZDI4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oyZZ6DKvprrnE3JJZp_l9zwz7OST9iHmErKWzbI4pL8)


Hey @nihal467 I'm working on this [issue](https://github.com/coronasafe/care/issues/1838)  and I'd like you to direct me on how I can do the "ME24.A5" search you just did, specifically where in care_fe url can i do that?

**Comment by rithviknishad** [comment]
https://icd.who.int/browse/2024-01/mms/en

**Comment by nihal467** [comment]
the icd-11 have been removed
