### ISSUE TITLE
How to restrict access to external results for nurse users

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#7002]
https://github.com/coronasafe/care_fe/issues/6240#issuecomment-1783827403

as per the requirements, nurse users should be able to list and edit the external result uploads, but we don't store the facility ID of the result, so there is no way to filter the objects

cc: @aparnacoronasafe @nihal467

**Comment by aparnacoronasafe** [comment]
@sainak you are right! i did not consider that challenge.

Lets not allow them to access External results or create patients from external results.
