### ISSUE TITLE
404 Not found errors on district and local bodies in Advanced Filters

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7005]
**Describe the bug**
404 Not found errors on district and local bodies when Advanced Filters opened.

Issue from #6889

**To Reproduce**

1. Go to Facilities Tab
2. Open Advanced Filters

**Expected behavior**
Prevent querying district and local bodies when dependent params are missing

**Screenshots**

<img width="920" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/10357823-83e9-4be0-97c8-f4e86e9d4722">

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign this to me.
