### ISSUE TITLE
Login-in button going to infinite loading post clicking it

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7010]
**Describe the bug**

when we click the login button with no user credentials, it goes to infinite loading state

**To Reproduce**

1. Go to https://care.coronasafe.in/
2. Click on login button without user credentials
3. See error

**Expected behavior**

when we click login, it should be only show frontend error validation since user credentials are missing, 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/37d73365-7cd7-461e-87ad-853a51d83a24)

**Comment by rithviknishad** [comment]
> ⚠️ **Refrain from assigning this issue to yourself if you have another `P1` issue assigned that is not yet closed.** @rithviknishad kindly acknowledge this message by commenting 'Acknowledged' below.

Ack
