### ISSUE TITLE
Inconsistent Auto-Removal of facility advance Filter When Closing Parent Filter

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7013]
**Describe the bug**

When applying three advanced facility filters - Kerala (State), Ernakulam (District), and Aluva (Local Body) - an inconsistency arises when attempting to remove the Ernakulam district filter. Specifically, closing the Ernakulam district filter badge does not automatically remove the Aluva local body filter, even though Aluva is a local body within the Ernakulam district.

**To Reproduce**

1. Go to https://care.coronasafe.in/faciltiy
2. Apply facility advance filters: Kerala (State) > Ernakulam (District) > Aluva (Local Body).
3. Attempt to remove the Ernakulam district filter by closing the associated badge.
4. see the error that Aluva local body filter remain applied

**Expected behavior**

The Aluva local body filter should be auto-removed upon closing the Ernakulam district filter badge. This behavior ensures logical consistency, as Aluva is tied to the Ernakulam district. 

similar logic should be applied, if we remove the state "Kerala", then both district and local bodies if applied should be auto-removed

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/b6b293f2-9cfa-4c84-8955-e261be081b99)

**Comment by Omkar76** [comment]
Hi, I can work on this.
