### ISSUE TITLE
Camera component for the file upload is not resetting after successful upload

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7016]
**Describe the bug**

The camera component for file upload is not resetting after a successful upload of the file. Even after completing the upload, it still displays the previously captured image using the component again to take another image.

**To Reproduce**

1. Navigate to the patient file upload section and upload a file using the camera.
2. After clicking on the camera and completing the upload,
3. Click on the open camera button again and observe the earlier uploaded image reappearing.
4. Note the error.

**Expected behavior**

The camera component for file upload should reset after a successful upload of the file.

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/13cbd71b-effb-4d8c-b352-a1c056cf8bd6)

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign this to me.

**Comment by Ashesh3** [comment]
@sriharsh05 Hey, we're treating this with priority. Feel free to pick up other issues!

**Comment by nihal467** [comment]
@sriharsh05 sorry, its already assigned to @Ashesh3 , feel free to take other open issues
