### ISSUE TITLE
Restrict Live monitoring button in facility details page to Certain users

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7021]
**Describe the bug**

Live monitoring button in the facility detail page is visible to all users

**To Reproduce**

1. Go to facility detail page with staff user credentials
2. See error

**Expected behavior**

Live monitoring button in the facility detail page should be visible to state admin, district admin and doctor only

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/e7ab055e-bfd4-4f3b-accc-68b7fa21bdff)

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Can you assign this to me?
