### ISSUE TITLE
District data is misaligned in the user card

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7022]
**Describe the bug**

District data in the user card is misaligned

**To Reproduce**

1. Go to user tab and search for "test-jan-staff-001"

**Expected behavior**

district data in the user card should be properly aligned

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/229a4f2b-6a69-4cc7-aca4-aa7754c92f75)

**Comment by singhbaidwan** [comment]
Hi Team 
Can I work on this bug ?

**Comment by Ashesh3** [comment]
@singhbaidwan Hey, this issue is already resolved. Feel free to pick up another issue.

**Comment by Ashesh3** [comment]
Fixed by https://github.com/coronasafe/care_fe/pull/7028
