### ISSUE TITLE
Investigation summary view is misaligned

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7023]
**Describe the bug**

the investigation summary view is misaligned 

**To Reproduce**

1. Go to patient consultation page and click view button for already created investigation
2. See error

**Expected behavior**

the investigation summary for a patient should be properly aligned

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/c5b6fc62-9d3e-4ab4-b0a5-c2a09e4c9e21)

**Comment by Ashesh3** [comment]
Fixed by https://github.com/coronasafe/care_fe/pull/7028
