### ISSUE TITLE
Patient registration form: COVID fields

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7032]
**Is your feature request related to a problem? Please describe.**
Karnataka state is going to be using CARE to monitor COVID-19 patients within the state.  

We will be identifying COVID patients from the diagnosis (ICD-11) on the patient's encounter. The existing COVID fields needs to be aligned to cater to this.

**Describe the solution you'd like**

- [ ] Remove "COVID Disease Status" field in COVID details section in the patient registration form.

Retaining the above field will confuse since there will be 2 separate sources of truth (the field and ICD-11). Hence it is important to remove the field

**Comment by rithviknishad** [comment]
So how should we deal with the "COVID Disease Status" Filter? 

<img width="472" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/a393ef68-0698-4691-b662-07e14753d7df">

cc: @aparnacoronasafe

**Comment by gigincg** [comment]
@aparnacoronasafe This would majorly affect how many of the Pandemic Management Related Features in CARE would work. 

We will have to operationally enforce using the COVID Tracking Fields for now. We can consider improving the Pandemic Management Features in this direction as a larger piece, if it is important

**Comment by aparnacoronasafe** [comment]
@gigincg I donot agree. for the following reasons:
1) The covid disease status is in the patient registration form. In ernakulam deployment it worked because the system was ONLY catering to COVID patients. which is not the case now. You cannot expect nurses to do back to the patient registration form of the pre-registered patient to mark this. So it is clear that we will need to amend the system.
2) This is a good opportuinity for us to fix the system rather than pushing it to another day. Lets see it as our pilot for Disease specific support, which in the future will include Cancer, neurological disorders etc

**Comment by gigincg** [comment]
Closing this, as discussed, using Metabase for Diagnosis specific analytics for now

cc: @aparnacoronasafe @nihal467
