### ISSUE TITLE
Support for filtering patients by ICD11 Diagnosis

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7033]
**Is your feature request related to a problem? Please describe.**
Karnataka will be deploying CARE to monitor its COVID-19 patients. 
Patients will be identified as COVID patients using the ICD-11 Diagnosis selected in the active encounter.
To cater to this, it is best that we build an ICD-11 based filter on patient list.

**Describe the solution you'd like**
Patient list>advanced filter to have "filter by ICD-11" that will allow users to multi-select ICD-11 items. The filter will show patients with at least one of the ICD-11s selected marked as a confirmed diagnosis.

Good to have: A toggle to search in provisional and unconfirmed diagnoses as well. This will extend the search to all provisional and unconfirmed diagnoses marked on the patient as well.

**Comment by nihal467** [comment]
@aparnacoronasafe we can get it work based on covid disease status

CC: @gigincg

**Comment by aparnacoronasafe** [comment]
Discussed with @gigincg and updated Issue.

**Comment by rithviknishad** [comment]
ETD January 30th as this will require backend changes
