### ISSUE TITLE
Patients list cards are uneven

### ISSUE THREAD

**Issue by shyamprakash123** [coronasafe/care_fe#7038]
**Describe the bug**
In the patient's list view the cards of patients are uneven.

**To Reproduce**

1. Go to (https://care.ohc.network/patients?is_active=False&page=3)
2. See error

**Expected behavior**
In the patient's list view the cards of patients must be even.

**Screenshots**
![Screenshot 2024-01-15 204956](https://github.com/coronasafe/care_fe/assets/106866225/48dec24d-923f-4bd0-9f06-74f7ee6bc789)

**Comment by shyamprakash123** [comment]
@rithviknishad assign this to me.

**Comment by rithviknishad** [comment]
@shyamprakash123 kindly resolve your other stale PR's https://github.com/coronasafe/care_fe/pull/6835#event-11487084541
