### ISSUE TITLE
Allow diagnoses starting with disease code to be picked (even if it's a chapter or a category, regardless of whether it's a leaf entity or not)

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7042]
- Related to #6995

Allow diagnoses starting with disease code to be picked (even if it's a chapter or a category, regardless of whether it's a leaf entity or not)

cc: @gigincg @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
@rithviknishad please go ahead

**Comment by aparnacoronasafe** [comment]
@rithviknishad had a call with hub admins. They have requested to deliver this asap. Nurses are not able to file consultation for patients with these specific ICds. Can this be shipped asap? 

@nihal467 @gigincg

**Comment by rithviknishad** [comment]
Acknowledged
