### ISSUE TITLE
Facility list: image to be 1:1

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7045]
**Is your feature request related to a problem? Please describe.**
The Facility image is uploaded as a 1:1 image, but the visualisation on the facility page (also the first page someone sees after logging in) has a different aspect rato which doesn't look good.

**Describe the solution you'd like**
Edit the facility list to show the image in a 1:1 ratio.

**Comment by AshrafMd-1** [comment]
I want to work on this issue can u assign this to me.

**Comment by AshrafMd-1** [comment]
@rithviknishad i want to work on this issue please assign this to me.

**Comment by aparnacoronasafe** [comment]
@AshrafMd-1 please give an estimate date of release

**Comment by AshrafMd-1** [comment]
@aparnacoronasafe Currently I have started working based on this design 
![Pasted image at 2024-01-24 at 15 00 37 PM](https://github.com/coronasafe/care_fe/assets/98876115/99793566-fae8-449b-8425-1a404da5aa91)

Will submit by 2-feb
cc @rithviknishad
