### ISSUE TITLE
Patient dashboard- Log update- negative space below

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7046]
**Is your feature request related to a problem? Please describe.**
In the patient dashboard, when a patient has more than 3 log updates, the log updates list cuts short and has negative space at the bottom.

<img width="1227" alt="Screenshot 2024-01-16 at 8 12 26 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/35e34c86-a9e6-4552-b888-e8444d12dd1e">
https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e 

**Describe the solution you'd like**
Extend the log updates list to the bottom of the screen

**Comment by konavivekramakrishna** [comment]
![image](https://github.com/coronasafe/care_fe/assets/101407963/d24c734a-f1e3-491d-8972-6b3885ce870e)

@aparnacoronasafe @rithviknishad 

extending the log updates height may cause empty space. Can you please share any ideas on how to handle it or is it okay?

**Comment by thedevildude** [comment]
@rithviknishad Can you assign this issue to me?

**Comment by younome71** [comment]
@rithviknishad I would like to work on this issue.  Kindly assign me this

**Comment by thedevildude** [comment]
Hey @younome71 I am currently working on it. Couldn't make a PR due to ongoing exams. Can you look for some other issue?
