### ISSUE TITLE
Improve Loading Discontinued Prescriptions in MAR

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#7049]
In the Medicine Administrations Page, When showing/hiding discontinued prescriptions, the entire list get's hidden. There should be a loading animation only for the discontinued medications

https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/medicines

**Comment by kshitijv256** [comment]
Can i work on this issue?

**Comment by rithviknishad** [comment]
@kshitijv256 kindly follow up on the PR that has changes requested in https://github.com/coronasafe/care_fe/pull/6977
