### ISSUE TITLE
Personalised notification and alerts on updates on EMR

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7079]
**Is your feature request related to a problem? Please describe.**
CARE is going to be used for providing disease-specific support like Cancer through CARE. With this specialists from far off centres will be checking for updates on patients, like if a test report has been updated etc.

**Describe the solution you'd like**
Build personalised notifications and alerts for users for :
- File upload
- Investigation
- Change in prescription

The notification/alert must come as a small icon for update in the relevant sections which must mark any unread update for that user.

**Comment by Shahbaz898414** [comment]
@aparnacoronasafe can i work on this issue?

**Comment by rash-27** [comment]
hey @Shahbaz898414 if you are not working on this , let me know , I would like to work on this issue .

**Comment by rash-27** [comment]
@khavinshankar should we create two kind of notifications (PATIENT_PRESCRIPTION_CREATED and PATIENT_PRESCRIPTION_UPDATED ) or only one field (PATIENT_PRESCRIPTION_UPDATED) is sufficient ?

**Comment by nihal467** [comment]
non-relevant to current develop approach
