### ISSUE TITLE
Migration of font-awesome icons to `CareIcon`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7080]
Currently, we are using both Font-awesome and CareIcons for icons in care. We need to phase out existing usages of font awesome icons.

Existing usages (143 usages) of font-awesome icons can be found by searching for `fa-solid|fas fa-` with regex search enabled.
<img width="470" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/927f4367-55ba-4335-82d3-1646888e962b">

cc: @sainak

**Comment by Omkar76** [comment]
I can take this up
