### ISSUE TITLE
Registering assets with state admin read-only account

### ISSUE THREAD

**Issue by Sunilsubba** [coronasafe/care_fe#7081]
----Describe the bug-----

State Admin Read-only users are restricted from registering an asset. However, if we write the complete URL (.../assets/new), we can register an asset successfully.

----Steps to Reproduce----
1- Log in using provided credentials
2- Click https://care.coronasafe.in/facility/497fd4fc-c5c1-4ed3-9b57-64cc881087fe/assets/new
3- Fill the asset details
4- Click on "Create Asset"

----Login Credentials----
Username: state_read123
Password: Lilo@123

----Screenshots----
![IMG_20240123_144617.jpg](https://github.com/coronasafe/care_fe/assets/144016088/808a6298-bc60-4403-9310-38ecfd4bbe8f)

![IMG_20240123_144554.jpg](https://github.com/coronasafe/care_fe/assets/144016088/92611115-e190-4728-9cb0-864d1448cf46)

**Comment by rithviknishad** [comment]
Anyone working on this can use the newly added `AuthorizeUserRoute` to protect this route from certain user types (along with permission checks in backend)

**Comment by kshitijv256** [comment]
I can work on this

**Comment by Sunilsubba** [comment]
Bug is still valid
