### ISSUE TITLE
Click and Upload patient file is not working

### ISSUE THREAD

**Issue by Sunilsubba** [coronasafe/care_fe#7082]
----Describe the bug----
Able to click the patient file using the camera but cannot upload it after submitting the picture

----To Reproduce----
1- Log in using the provided credential
2- Click "https://care.coronasafe.in/facility/fe1b9b4b-def3-488a-808a-a5776222f65b/patient/5dc47e6b-eae3-48d0-85a7-aee4bd9ce4a7/consultation/529a02d2-f140-4e9e-95e4-7f186b849fbd/files"
3- Go to "Upload New File"
4- Open Camera/ Capture/ Submit
5- Upload (which is not working)

----Login Credentials----
Username: state_admin123
Password: Lilo@123

----Screenshots----
![IMG_20240123_174945.jpg](https://github.com/coronasafe/care_fe/assets/144016088/3d8c0d3a-71cc-4f5f-adc1-07f78baa4522)

![IMG_20240123_174919.jpg](https://github.com/coronasafe/care_fe/assets/144016088/845d72fb-c093-4fb7-a759-e89fa4c18cb4)

**Comment by rithviknishad** [comment]
@Sunilsubba the "Upload" button is disabled as no file name is entered in the mandatory field. Once entered, the upload button should be enabled and working.

<img width="690" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/d9103656-9445-47ea-bd87-aa3c12e53cd8">

cc: @nihal467

**Comment by Sunilsubba** [comment]
Got it, thanks.
