### ISSUE TITLE
Add Cypress Test for Patient file upload

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7086]
**Description Of the Test**

Add a new cypress test to the patient file upload on the patient detail page, and cover the following flow in the test file

- [ ] Upload a new file to the patient detail page. (Both Audio and file)
- [ ] Edit the file name of an existing uploaded file.
- [ ] Archive the existing file and verify its move to the archive section along with archive details.
- [ ] Verify the uploaded file can only be modified by the author, district admin, and above users.
- [ ] Verify file download is possible for all users.

**Note**

- add query parameter, notification, and API verification wherever necessary
- follow the POM approach while coding
- create a new file named "patient_detailpage.cy.ts" and page object file "PatientFileupload.ts" 

**Screenshot**

![image](https://github.com/coronasafe/care_fe/assets/57055998/68f3fc51-817e-41ff-b48b-297a612ff07c)

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Can you assign this to me.
