### ISSUE TITLE
Failed to upload patient file in External Result

### ISSUE THREAD

**Issue by Sunilsubba** [coronasafe/care_fe#7101]
----Describe the bug----
Restricted to import patients. CSV file, the error comes out as "Different District". 
It will only work when the User's ( State admin) District from the location is the same as the District from the Patient. CSV File

----Steps to reproduce----
1- Log in
2- Go to External Result/ import Result/
3- Click on "Sample Format" and download.
4- Click on "Choose File" and Upload that sample format
https://care.coronasafe.in/external_results/upload

----Login Credentials----
Username: state_admin123
Password: Lilo@123

----Screenshots----
![IMG_20240125_002428.jpg](https://github.com/coronasafe/care_fe/assets/144016088/dd8d51fa-e41f-4dc3-94e4-940c50367777)

**Comment by SamakshAgarwal1112** [comment]
Can you please describe what should be the expected behaviour?

**Comment by SamakshAgarwal1112** [comment]
Hey, I think I get what's the problem. It won't let you save the records if there are no valid records. If that needs to be changed, I'll change it. @Sunilsubba please assign me this issue. I'll raise a PR.

**Comment by Sunilsubba** [comment]
State admin should be able to upload the patient files of all the districts of that particular state. "Different District" must not come up for all the districts of the respective state.

**Comment by jainvedant392** [comment]
Hey @rithviknishad , I'm interested to work on this issue, can I please get it assigned?

**Comment by jainvedant392** [comment]
Hey @rithviknishad , I'm interested to work on this issue, can I please get it assigned?
I think I have to find the condition for downloading or importing the CSV file, and alter it to produce the result for any district.

**Comment by SinghYuvraj0506** [comment]
Hey, @jainvedant392 are you working on the issue, or can I proceed with it.

**Comment by SinghYuvraj0506** [comment]
Hey @Sunilsubba , can you tell me if I'm correct or not, If the user is a StateAdmin then it may add patients of any district in the state, whereas if it is a district admin then the patient allowed should be of same district, and the rest other cases would throw an error.

**Comment by jainvedant392** [comment]
> Hey, @jainvedant392 are you working on the issue, or can I proceed with it.

Hey @SinghYuvraj0506  , actually I am working on this issue.

**Comment by jainvedant392** [comment]
Hey @rithviknishad @Sunilsubba, I wanted once to discuss the approach of this issue.

**Comment by jainvedant392** [comment]
So when the logged in user has a "user_type": "StateAdmin", he should be able to upload the files such that, if the user and patient in the file has same state, "Different Districts" should not be visible.

**Comment by jainvedant392** [comment]
And if the states of both are different, then only we should set the "validationErrorCount". Right?

**Comment by jainvedant392** [comment]
Also there is no field or property like "state" in the csvData, so I have to extract the state from the address property.

![image](https://github.com/coronasafe/care_fe/assets/129421822/e2b79dc1-1273-427d-b9db-f9c8764a8d1e)

**Comment by Sunilsubba** [comment]
@jainvedant392 Hey, if the user type is a state admin then it should be allowed to import patients of all the districts.
