### ISSUE TITLE
Location/ Bed Management issue ( District Lab Admin Account)

### ISSUE THREAD

**Issue by Sunilsubba** [coronasafe/care_fe#7102]
----Describe the bug----
Error Message coming up "You don't have permission to perform this action" but still allowed to create and manage beds using district lab admin account

----Steps to reproduce----
1- Log in using provided credential
2- Click on https://care.coronasafe.in/facility/42d0dbbd-e3e1-4d64-88ff-f606b90975b0/location

3- Click on "manage beds" from any existing location
4- add new bed

----Login Credentials----
Username: district_lab123
Password: Lilo@123

----Screenshots----
![IMG_20240125_003827.jpg](https://github.com/coronasafe/care_fe/assets/144016088/d0a54e07-3d87-4af2-8d6b-765f27bdcf0a)

![IMG_20240125_003749.jpg](https://github.com/coronasafe/care_fe/assets/144016088/aee147d9-6aec-4fe9-9a30-03279a7f8dca)

**Comment by SamakshAgarwal1112** [comment]
Working on it!

**Comment by rithviknishad** [comment]
Hey @SamakshAgarwal1112 any updates on this?

**Comment by konavivekramakrishna** [comment]
@rithviknishad 

can you please assign me

**Comment by shramanpaul** [comment]
Hello @rithviknishad, could you please assign me this issue? I'm eager to work on it.

**Comment by rithviknishad** [comment]
Hey @shramanpaul 

Feel free to make a PR on this once the changes requested for #7200 is completed

**Comment by parthksingh1** [comment]
Hey @rithviknishad ,may I address this issue if @shramanpaul doesn't mind? I have prior experience dealing with this type of issue, so I am familiar with it.

**Comment by balaji-sivasakthi** [comment]
@rithviknishad Could you explain to me why this issue is throwing a 403 error?
```
GET /api/v1/facility/42d0dbbd-e3e1-4d64-88ff-f606b90975b0/asset_location/6ee4cae3-f9e3-40d4-9b47-337ac8052f76/
HTTP 403 Forbidden
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Authentication credentials were not provided."
}
```

**Comment by rithviknishad** [comment]
Have you set the Authorization headers when making the request?

**Comment by balaji-sivasakthi** [comment]
> Have you set the Authorization headers when making the request?

I'm not sure, this is the stuff  I cached from the browser.

**Comment by AnkurPrabhu** [comment]
@rithviknishad @balaji-sivasakthi i tried using the same front-end on my local backend it does not show this error. do we have some sort of waf or any firewall this passes through that could be the issue here pls correct me if i am wrong, also this does not exist in https://care.ohc.network/

**Comment by varshith257** [comment]
@rithviknishad I would like to work on this. Can you assign me this issue?

**Comment by hrit2773** [comment]
@balaji-sivasakthi that 403 error is because there is no authentication details. I tried to find the method associated with the url in the care backend repo but I'm unable to find it

**Comment by balaji-sivasakthi** [comment]
Has anyone checked with a different account? I believe the account listed below may be broken in terms of roles.

```
Username: district_lab123
Password: Lilo@123
```

**Comment by r-nikhilkumar** [comment]
please assign this issues to me, I want to contribute here

**Comment by Shahbaz898414** [comment]
@rithviknishad I would like to work on this. Can you assign me this issue?

**Comment by AnkurPrabhu** [comment]
> Has anyone checked with a different account? I believe the account listed below may be broken in terms of roles.
> 
> ```
> Username: district_lab123
> Password: Lilo@123
> ```

i tried on my local using devdistrict admin, staff and doc everything works fine, i feel like this is some sort of configuration or firewall setting for some apis
or this could be some specific permission is not giving to the user account from django admin can anyone check the user type ?

**Comment by rithviknishad** [comment]
Have you tried creating a district lab admin user type user and tried replicating the issue with that user?

**Comment by AnkurPrabhu** [comment]
Yes I did 
What I did for this is 
Went to django users table edited type to  district level admin and then tried  it was working fine for me 
Let me know my steps to replicate are correct or have I missed something

**Comment by rithviknishad** [comment]
"District Lab Admin" is the user type. Not "District Admin"

Also, I'm able to replicate this issue.

To replicate this, you'll need to go directly to the URL instead of navigating to the location page through Care.

<img width="1051" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/008c5c4a-bf2d-4b68-afd2-c951565e8ca4">

There seems to be multiple permission issues:

1. A district lab admin user seems to be able to see "facilities" that this user does not have access to. (Although when I click on a facility it gives 404 Not Found)
2. If I directly go to the location management page of such inaccessible facilities, I'm able to list the locations of such facilities. This shouldn't be permitted. 
3. Now this user can read and write beds of those locations of inaccessible facilities too, which also shouldn't be permitted.

cc: @sainak

**Comment by sainak** [comment]
> "District Lab Admin" is the user type. Not "District Admin"
> 
> Also, I'm able to replicate this issue.
> 
> To replicate this, you'll need to go directly to the URL instead of navigating to the location page through Care.
> 
> <img width="1051" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/008c5c4a-bf2d-4b68-afd2-c951565e8ca4">
> 
> There seems to be multiple permission issues:
> 
> 1. A district lab admin user seems to be able to see "facilities" that this user does not have access to. (Although when I click on a facility it gives 404 Not Found)
> 2. If I directly go to the location management page of such inaccessible facilities, I'm able to list the locations of such facilities. This shouldn't be permitted. 
> 3. Now this user can read and write beds of those locations of inaccessible facilities too, which also shouldn't be permitted.
> 
> cc: @sainak 

Yes @rithviknishad this is a permission issue, it needs to be restricted on the backend

**Comment by AnkurPrabhu** [comment]
can you assign this to me ? @rithviknishad @sainak

**Comment by AnkurPrabhu** [comment]
> 1. A district lab admin user seems to be able to see "facilities" that this user does not have access to. (Although when I click on a facility it gives 404 Not Found)

@rithviknishad can you pls explain what do you mean by this as on what basis do we need to validate if user has access to these facilities ?

**Comment by rithviknishad** [comment]
Refer Facility Permissions here: https://github.com/coronasafe/care/blob/master/care/facility/api/viewsets/facility.py#L50-L61

**Comment by Thanush19** [comment]
if the issue is not resolved , i can work on this @rithviknishad

**Comment by AnkurPrabhu** [comment]
i am working on it @Thanush19

**Comment by AnkurPrabhu** [comment]
lets close this issue @rithviknishad
