### ISSUE TITLE
Notification and Notice board not working for State Admin Access

### ISSUE THREAD

**Issue by Sunilsubba** [coronasafe/care_fe#7106]
**Describe the bug**
Notification and Notice Board not functioning

**To Reproduce**

1. Login Using Provided Credentials
2. Go to Notice board
3. Go to Notification

**Login Credentials**
Username: state_admin123
Password: Lilo@123

**Expected behavior**
 After notifying hospital, the message should come up in the notice board.

**Screenshots**
![Screenshot (9)](https://github.com/coronasafe/care_fe/assets/144016088/bfe00e3d-708f-47d1-a3f6-7ee02c7b31b3)
![Screenshot (10)](https://github.com/coronasafe/care_fe/assets/144016088/d42f6949-5b1e-4052-8f07-cac17444f232)
![Screenshot (11)](https://github.com/coronasafe/care_fe/assets/144016088/323f2581-bdbf-4296-8485-6bb02b484ca3)
![Screenshot (12)](https://github.com/coronasafe/care_fe/assets/144016088/bef59172-77ce-43d3-a155-d1f3533a09e1)

**Comment by shramanpaul** [comment]
I want to work on this issue

**Comment by rithviknishad** [comment]
Hey @shramanpaul 

I see that you've assigned #6944 but have not made any PR against it. It'd be nice if you could take up one issue at a time to work on, so that other contributors would also be able to participate. Feel free to comment down any issues or blockers you are facing if any.

**Comment by nihal467** [comment]
![image](https://github.com/coronasafe/care_fe/assets/57055998/c23b3699-4ea7-407c-a310-7a77326d02b1)

-  I have sent a notification from the **state admin** user credential to a facility and re-login as a **nurse** user type, the notice is available in the notice board section 

Note: There might be a delay sometimes, as the celery worker of the staging environment is overloaded, and the request is in the queue.

@Sunilsubba Could you please specify how to replicate the bug, from which user type the notification is sent, and through which user type you attempt to verify whether the notice is delivered or not?

**Comment by Sunilsubba** [comment]
@nihal467 Nothing was coming up in the notification field, seems fixed now.

![IMG_20240128_012307.jpg](https://github.com/coronasafe/care_fe/assets/144016088/8e4896d2-0a23-47a9-ab30-917b0a322b57)

**Comment by nihal467** [comment]
@Sunilsubba When you send a notice to a facility, users linked to the facility, except the one who sent the notice, will receive a notification.
