### ISSUE TITLE
Filters under the notification section.
 
There are filters like "Patient Deleted" and "Patient Consultation Deleted", are we supposed to have that since no user in CARE has access to them?

### ISSUE THREAD

**Issue by Sunilsubba** [coronasafe/care_fe#7112]
-![IMG-20240127-WA0010.jpeg](https://github.com/coronasafe/care_fe/assets/144016088/69eee8f7-30ec-402a-8698-372bedcded31)

**Comment by Ashesh3** [comment]
After discussion: "Patient Deleted" and "Patient Consultation Deleted" categories from notification filters are to be removed

**Comment by kshitijv256** [comment]
I would like to work on it
