### ISSUE TITLE
To increase the respiratory rate in log update page

### ISSUE THREAD

**Issue by SeyiesilieChadi** [coronasafe/care_fe#7121]
**Is your feature request related to a problem? Please describe.**
Not able to enter correct respiratory rate during log update as the existing value is not high enough. Patients with heart condition , especially Paediatric patients, experiences respiratory rate higher than 70.

**Describe the solution you'd like**
It seems necessary to increase the respiratory rate in log update.

**Comment by SeyiesilieChadi** [comment]
@aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
Increase pulse rate data validation to any number equal to or less than 600.

**Comment by aparnacoronasafe** [comment]
Let us allow resp rate of upto 150 breaths per minute. 

@nihal467 @rithviknishad

**Comment by vivramkrishna** [comment]
@rithviknishad 

can you please assign me

**Comment by aparnacoronasafe** [comment]
Can we expedite this? expected in next release

**Comment by vivramkrishna** [comment]
Yes,
The PR needs to be tested.
