### ISSUE TITLE
Add consultation updates button not disabled in Patient Details page for Discharged consultations

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7131]
**Describe the bug**
Add consultation updates button not disabled in Patient Details page for Discharged consultations

**To Reproduce**

1. Go to patients tab
2. Open discharged tab
3. Open any patient that has this issue (eg: https://care.ohc.network/facility/eeb23cb7-1524-479a-825e-660311386b47/patient/9ed7c221-a3ac-4bb3-8fcb-f0e0756cb49e)
4. See that the consultation although is discharged (`discharge_date` NOT NULL), we are still showing the "Add consultation updates" button.

**Expected behavior**
Disable the "Add consultation updates" button for discharged consultations.

**Screenshots**
<img width="2052" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/7baf5a57-6388-43e5-9371-af60c8120c95">

**Comment by HubertGrabda** [comment]
Hey, I can help with that

**Comment by younome71** [comment]
@rithviknishad I would like to take on this issue. Could you please assign it to me? I will promptly address this by checking and updating the relevant code to disable the button based on the discharge_date.

**Comment by rithviknishad** [comment]
Hey @younome71 

Assigned to @HubertGrabda since he had already made a working PR
