### ISSUE TITLE
Able to create daily round update without a bed assigned through patient details page but not through consultation dashboard

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7132]
**Describe the bug**
When a consultation has no bed assigned, we are restricted from filing a log update if there is no bed assigned if the "Log update" button is clicked from the consultation dashboard.

However, if we go to the patient details page and click "Add consultation updates" we can still access the daily round form and we can file a Daily Round log update successfully. This should not be allowed.

**Expected behavior**
Disallow "Add consultation updates" button for active consultations without a bed assigned.

**Screenshots**
<img width="2052" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/63b651b5-0e1f-4665-bff0-b6af663ad800">

<img width="2052" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/bdb4659d-5095-4d60-9196-c0e8e35b49d6">

<img width="2052" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/43ad8dfe-c0d0-4967-b501-47e1af9bdf25">

<img width="2015" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/aef18112-1c57-4e53-9acb-862ee0d75405">

**Comment by sriharsh05** [comment]
I want to work on this. Please assign this to me.

**Comment by younome71** [comment]
@rithviknishad I'd like to handle this issue. Could you please assign it to me? I'll ensure the "Add consultation updates" button is appropriately disabled for active consultations without a bed assigned.

**Comment by rithviknishad** [comment]
Hey @younome71 any updates on this?

**Comment by younome71** [comment]
@rithviknishad I was facing some issues initially setting up the environment, which got resolved just now. Will update shortly about the progress

**Comment by younome71** [comment]
@rithviknishad Do it need to disallow as in show an error ? Or Remove the button itself if there is no bed assigned?

**Comment by rithviknishad** [comment]
same behaviour as how its there when we click log update from consultation dashboard. Show error notification and open bed assign dialog

**Comment by mohanrajnambe** [comment]
@rithviknishad I have created a PR on this issue #7303. Please review it!
