### ISSUE TITLE
Limit the decimal points in the Facility GPS Location field upto 7

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7135]
**Describe the bug**

When opening the "Update Details" page for a facility where the GPS location was entered during the facility's creation, the location field displays a 16-decimal-point value.

**To Reproduce**

1. Create a new facility with GPS location (https://care.ohc.network/facility/create )
2. Post Creation , go to the facility detail page and click update details button
3. Scroll down to location

**Expected behavior**

GPS Location location field should be having only 7 decimal points

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/59b594d7-5aec-4e5b-9ef5-e1fd3c7c39ad)

**Comment by sriharsh05** [comment]
@rithviknishad 
I want to work on this issue, Please assign this to me.
