### ISSUE TITLE
Remove the 0 in the Link facility sidebar

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7140]
**Describe the bug**

There is an unwanted 0 shown in the link facility when there is no facility linked to a user

**To Reproduce**

1. Go to User tab
2. Click on Link facility button of a user card, who have no facility linked to the idea
3. See error

**Expected behavior**

Remove the unwanted 0 in the link facility sidebar

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/9b4f16dd-2c1b-4e48-bfad-069709d8398b)

**Comment by sriharsh05** [comment]
I can work on this.

**Comment by vivramkrishna** [comment]
@rithviknishad 

can you please assign me
