### ISSUE TITLE
Fix the Mobile responsive view in the user card

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7141]
**Describe the bug**

- [ ] the delete button borders are improperly shaped in the mobile responsive view
- [ ] the working hour button text is getting clipped in in the mobile responsive view

**To Reproduce**

1. Go to user tab
2. Swtich to mobile view and select iPhone SE
3. See error

**Expected behavior**

Both the button should be properly responsive in the mobile view

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/a0f48d6f-da92-498e-8436-71da9de37177)

**Comment by shyamprakash123** [comment]
@rithviknishad I want to work on this, can you assign me?

**Comment by nihal467** [comment]
Already its been addressed in a new PR https://github.com/coronasafe/care_fe/pull/7480
