### ISSUE TITLE
Increase the Add button height in skills slideover

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7142]
**Describe the bug**

- [ ] the height of the add button in the skill slideover is not uniform compared to the box adjacent to it

**To Reproduce**

**Expected behavior**

- [ ] make the height of add button consistent to the adjacent text box height in the skill slideover

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/d2f4bfa7-dabb-48c5-be6d-0d9a74161f32)

**Comment by shyamprakash123** [comment]
@rithviknishad I want to work on this can you assign me?
