### ISSUE TITLE
Add max validation for doctor experience years

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7143]
**Describe the bug**

**To Reproduce**

1. Go to Add User page
2. Attempt to add a doctor user type with experience set to a number above 100

**Expected behavior**
Limit selecting above 100 and show validation error if selected

**Screenshots**
<img width="526" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/8e56246d-9895-4c45-85b9-24af8173242c">

<img width="1607" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/37c5edaa-e2c2-41bc-8c9c-90a3638da621">

**Comment by sriharsh05** [comment]
I want to work on this.
