### ISSUE TITLE
Add a new row for facility name to Patient investigation summary

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7150]
**Describe the bug**

- [ ] Investigation summary is not generated based on a specific consultation

**To Reproduce**

**Expected behavior**

- [ ] The investigation summary table should show the facility name as a new row

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/4c6b1638-2fc8-4fb9-b9d6-89284b8a07b2)

**Comment by Ashesh3** [comment]
Facility name to be linked to the investigation record and shown in the UI.
