### ISSUE TITLE
Improve the camera uploaded patient files quality

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7154]
**Describe the bug**

When we upload a file using the camera feature to a patient file, the quality drops significantly

**To Reproduce**

1. Go to patient consultation page
2. Click on file upload and select camera
3. upload a captured file and check the image quality

**Expected behavior**

file upload using the camera feature to patient file should retain a good amount of quality

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/b833855e-f7e6-4dcd-9fc7-46b4e822cf29)

**Comment by Omkar76** [comment]
Assign this to me. Sending a PR to improve resolution of image capture.
