### ISSUE TITLE
Replace `useDispatch` w. `useQuery`/`request`: Patient Registration Form (`src/Components/Patient/PatientRegister.tsx`)

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7171]

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign this to me.

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign this to me.

**Comment by rithviknishad** [comment]
Hey @sriharsh05 any updates on this?

**Comment by sriharsh05** [comment]
Yes @rithviknishad 
I am working on it. I will make a PR very soon.
