### ISSUE TITLE
Manage Patient button is clipping out

### ISSUE THREAD

**Issue by vivramkrishna** [coronasafe/care_fe#7192]
![image](https://github.com/coronasafe/care_fe/assets/101407963/46d2d01e-9a80-4fb4-9ecf-6d999e6af941)

**Describe the bug**
1. Button is clipping out of the card
2. The height of manage patient and log update button is inconsistent.

**To Reproduce**

1. Go to https://care.ohc.network/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/291bf9c3-b016-43a6-84f3-7ea6d860814c/consultation/1bd88c34-1008-4359-96e5-5d11109a84bb
2. See error.

**Comment by konavivekramakrishna** [comment]
@rithviknishad 

can you please assign me

**Comment by vivramkrishna** [comment]
![image](https://github.com/coronasafe/care_fe/assets/101407963/7cb04e91-be1b-46e5-92e3-21ebf135c36a)
fixed
