### ISSUE TITLE
Add Cypress test to verify error thrown for duplicate bed name

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7206]
**Describe the test**
Follow-up: https://github.com/coronasafe/care/pull/1783

Currently, the backend throws an error, if we create a duplicate bed name for the same location, so verify the same

**Check-list**
- [ ] add the test to locations.cy.ts file
- [ ] it should be in the POM approach
- [ ] create multiple beds with the same name and verify the backend throws the error

**Comment by vivramkrishna** [comment]
@nihal467 can you please assign me

**Comment by vivramkrishna** [comment]
@sainak 

![image](https://github.com/coronasafe/care_fe/assets/101407963/28de9295-91f9-4d8e-b39c-d9b701a71fdc)

when creating bed with same name getting 500 instead of 4xx

**Comment by vivramkrishna** [comment]
https://care.ohc.network/facility/6762fa68-0f86-4135-a436-09d8c9e61073/location/6b5bbacc-4700-4655-a24f-65dc4287b564/beds/add

**Comment by sainak** [comment]
fixed in https://github.com/coronasafe/care/pull/1894

**Comment by vivramkrishna** [comment]
@nihal467 

how is this new Cypress test different from the already existing Cypress test for verifying the creation of duplicate beds?

https://github.com/coronasafe/care_fe/blob/develop/cypress/e2e/facility_spec/locations.cy.ts#L87-L94

**Comment by nihal467** [comment]
@konavivekramakrishna Sorry, my bad, the test already exist, so closing this issue and feel free to assign other open issue
