### ISSUE TITLE
Asset detail page is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7209]
**Describe the bug**

when we open the asset detail page, its showing "something went wrong" error

**To Reproduce**

1. Go to asset detail page
2. See error

**Expected behavior**

**Screenshots**

<img width="960" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/b5658a01-1100-4af7-bf96-4c66215c6d8a">

**Comment by rithviknishad** [comment]
@Ashesh3 https://github.com/coronasafe/care/pull/1843 requires changes in front end too right?
