### ISSUE TITLE
Discharge date issue

### ISSUE THREAD

**Issue by Deepjyoti14** [coronasafe/care_fe#7212]
**Describe the bug**
Discharge date field is not allowing to select a date from year 2023.

**Expected behavior**
If the change is intentional, can it please be allowed for few days. Since we are doing some backlog data entry.

**Screenshots**
Attached
![Uploading Screenshot (12).png…]()

**Comment by rithviknishad** [comment]
@Deepjyoti14 could you specify what the error was when attempting to discharge? I was able to successfully discharge a patient with a discharge date in 2023.

The discharge date must be later than the admission date.

**Comment by Deepjyoti14** [comment]
@rithviknishad Sorry I was checking for wrong patient. Yes its working. Thanks. Please close the issue.
