### ISSUE TITLE
Support for showing tutorial on how to use CARE inside CARE

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7215]
**Is your feature request related to a problem? Please describe.**
When a new user is onboarded to CARE, they may not how to use CARE. They'll have to get training in order to use CARE.

**Describe the solution you'd like**
- Show an on-boarding tutorial on how to use CARE.
- These tutorials could be specific to the user type to show what functionality that user would be using most. Backend would track whether the user has completed the tutorial or not.
- On every new version, show the new changes that have been added to CARE. Optionally include tutorials for those features.

**Comment by nihal467** [comment]
non-relevant
