### ISSUE TITLE
Limit number of facilities a single user can be linked to.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7219]
**Describe the bug**
Currently, the user in staging "devdistrictadmin" has ~1000 facilities linked to the user. This makes the query slow.

**To Reproduce**

1. Go to users tab
2. Open linked facilities of devdistrictadmin

**Expected behavior**
Limit how much facilities a user can be linked to.

**Screenshots**
<img width="2991" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/4007b4bf-f3fd-4091-ae59-a837d02a1b0e">

**Comment by aeswibon** [comment]
I was wondering what would be the limit? Like 10 or 15.

**Comment by aeswibon** [comment]
As discussed in EOD, would be adding pagination...
