### ISSUE TITLE
Patient Gender Display Issue in HL7Monitor and VentilatorPatientVitalsMonitor

### ISSUE THREAD

**Issue by thedevildude** [coronasafe/care_fe#7226]
**Describe the bug**
Currently, the HL7Monitor and VentilatorPatientVitalsMonitor components are not displaying the patient's gender. This discrepancy arises from a mismatch in the data type sent to these component.

**To Reproduce**

1. Go to any patient with vital monitors attached
2. Scroll down to Updates tab
3. See error

**Expected behavior**
@aparnacoronasafe @rithviknishad please suggest an expected behavior

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/63492939/78979a37-05bf-4984-8047-cc5a1003d5d1)

**Additional context**
The PatientModel defines the gender property as a number type, where each number corresponds to a GENDER_TYPE ID. However, the HL7 and vitals monitors expect the patient's gender to be represented by the gender type's ID (GENDER_TYPES.id). Instead, the parent component preprocesses the patient's gender data and sends GENDER_TYPES.text to the components.

**Comment by rithviknishad** [comment]
@thedevildude let's hide the top bar when on the consultation page. We can show the asset information alone in that (i) popover.

All details to be shown when this is in CNS

**Comment by rithviknishad** [comment]
Related to #7186
