### ISSUE TITLE
Provision to link an investigation which led to the change in verification status of a diagnosis

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7232]
**Is your feature request related to a problem? Please describe.**
There is no direct linkage that the user can create between lists of diagnostics and tests done to the confirmed ICD-11

**Describe the solution you'd like**
- Build a feature that allows users to select from existing diagnostics and test reports, linking them to each diagnosis mentioned. There must also be an option to leave comments along with such linkage
- A test could lead to multiple provisional diagnoses
- Multiple tests could lead to confirmation of a diagnosis

**Additional context**
Part of NCG EMR Requirements (A-6)

### Action Items

- [ ] Ability to link an external result test with a consultation diagnosis
- [ ] Ability to view the related tests of a consultation diagnosis

**Comment by rithviknishad** [comment]
As discussed with @aparnacoronasafe , 

- [ ] We need to track changes made to a consultation diagnosis.
- [ ] Provision to link an Investigation to the changelog as the reason.

**Comment by noufalrahim** [comment]
@rithviknishad can u assign this to me

**Comment by nihal467** [comment]
non-relevant to current develop
