### ISSUE TITLE
Issues in Events Module

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7234]
- [ ] Log update modification is not recorded in the event module

![image](https://github.com/coronasafe/care_fe/assets/57055998/60efbbaa-d53a-413e-9f0d-4e2513eb9fda)

- [x] #8370

![image](https://github.com/coronasafe/care_fe/assets/57055998/93f6282d-67ea-4aea-9839-7be3d57fe741)

- [x] #8376

- [x] #8377

**Comment by Ashutosh0602** [comment]
@nihal467 Is this problem still open or someone working on it?

**Comment by sainak** [comment]
@gigincg should we add hooks to save log updates?
and can you give confirmation for `Hide N/A, Null, 0 in the frontend`

**Comment by gigincg** [comment]
@sainak We can hide N/A, and null Values. I think we should Solve 0 Values being saved as a separate issue.

**Comment by gigincg** [comment]
@sainak Why is this marked as an Epic Issue?

**Comment by praffq** [comment]
I'll like to work on this issue.

**Comment by bodhish** [comment]
@DraKen0009 whats the status here?

**Comment by praffq** [comment]
Waiting for clarification here - https://rebuildearth.slack.com/archives/C01035FT0P5/p1728578665852069?thread_ts=1728578665.852069&cid=C01035FT0P5

**Comment by bodhish** [comment]
@DraKen0009 status here?

**Comment by praffq** [comment]
We no longer need to take work on events' issue since they will be deprecated soon. So I think this can be closed. https://rebuildearth.slack.com/archives/C010GQBMFJ9/p1731242053885619
