### ISSUE TITLE
Prevent users who don't have access to register a patient to a facility from opening the patient registration page of that facility

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7244]
**Describe the bug**
Certain user types are not allowed to register a patient into a non-home facility. However, it is frustrating when user fills out the patient form only to realise when submitting that they don't have permission to do this action.

**To Reproduce**

1. Register a patient to a non home facility as a doctor
2. Fill the patient registration form and hit submit
3. See permission denied error

**Expected behavior**
Users who do not have permission to register a patient to a non-home facility should not be allowed to open patient registration form for that facility.

**Screenshots**
<img width="1710" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/5018ef26-da9f-4391-8a59-2fe770e5679d">

**Comment by AshrafMd-1** [comment]
I want to work on this issue can you assign me this.

**Comment by AshrafMd-1** [comment]
@rithviknishad can you specify what users I need to keep the condition on 
as of now, I have identified 3
- Doctor
- nurse
- staffdev

**Comment by rithviknishad** [comment]
Instead of adding a condition, how about fetching only the permitted facilities in the facility select dropdown in the first place?

**Comment by AshrafMd-1** [comment]
@rithviknishad I have figured out another issue that is if I paste the URL of a non-home facility patient addition page  and paste it then it does open the  page and has the same issue as above

**Comment by rithviknishad** [comment]
Just clarified the permissions with @nihal467 

- State Admin has access to create a patient to facilities that belong to their state. (irrespective of their home facility)
- District Admin has access to create a patient to facilities that belong to their district. (irrespective of their home facility)
- Users below this user type have access to create patients only in their home facility.

**Additional context:**

Users will still have access to view existing patient records on all their linked facilities (non-home facilities).
