### ISSUE TITLE
Implement 'Discard Changes' Modal for Form Editing Confirmation

### ISSUE THREAD

**Issue by Keshav-0907** [coronasafe/care_fe#7255]
**Is your feature request related to a problem? Please describe.**
Currently, when a user is updating a form with different fields and accidentally navigates away without saving, all updated data is lost. 

**Describe the solution you'd like**
To mitigate the risk of unintentional data loss, we can implement a 'Discard Changes' modal that would serve as a confirmation step before discarding any modifications.

**Additional context**
( Video : No confirmation model when form is updated and user navigates away )

https://github.com/coronasafe/care_fe/assets/91189139/17b71990-37f1-444c-9f06-05c488d3c235

**Proposed Solution**
Refactor the HTML Form used here to use the higher order `<Form>` component with draft support

**Comment by Ashesh3** [comment]
We already have support for auto saving drafts for our <Form component, I think converting this basic html form to our higher order <Form component should resolve this issue alongside. 

cc: @rithviknishad

**Comment by rithviknishad** [comment]
@Ashesh3 I think @Keshav-0907 meant more like a "Confirm Navigate Away" popup to prevent accidental navigations. Yes, we can always enable form restorations too on top of this.

<img width="372" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/4c4636c3-6618-43b4-8708-91471d7ed395">

**Comment by Ashesh3** [comment]
> @Ashesh3 I think @Keshav-0907 meant more like a "Confirm Navigate Away" popup to prevent accidental navigations. Yes, we can always enable form restorations too on top of this.
> 
> <img alt="image" width="372" src="https://private-user-images.githubusercontent.com/25143503/307317400-4c4636c3-6618-43b4-8708-91471d7ed395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTA5MDcsIm5iZiI6MTcwODY5MDYwNywicGF0aCI6Ii8yNTE0MzUwMy8zMDczMTc0MDAtNGM0NjM2YzMtNjYxOC00M2I0LTg3MDgtOTE0NzFkN2VkMzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEyMTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjN2VhYzJlZjIxNmU0MDlhOTE1NTE5NjEwM2RiYzRkMDk2OTk3YTA4OTUxMGZjNzVmNWViZjdiZDZlMzVmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jU5PbTOcNA3ZArJaWT6F28XQeRu8cMIYJ4mEBFvdWKg">

Yep, I got that, but since we don't have it anywhere else, even for the more imp and longer forms like consultation, patient etc. Instead of adding this popup for all existing long forms, I feel we should just upgrade this form to support drafts, that serves the same purpose to get users back their data in case they navigate away unintentionally. Just my thoughts, open to discussions!

This drafts solution also aligns with the required solution mentioned in the issue:
> all updated data is lost. .... To mitigate the risk of unintentional data loss, ....

**Comment by rithviknishad** [comment]
I agree with @Ashesh3 

@nihal467 / @gigincg / @aparnacoronasafe

**Comment by Keshav-0907** [comment]
> @Ashesh3 I think @Keshav-0907 meant more like a "Confirm Navigate Away" popup to prevent accidental navigations. Yes, we can always enable form restorations too on top of this.
> 
> <img alt="image" width="372" src="https://private-user-images.githubusercontent.com/25143503/307317400-4c4636c3-6618-43b4-8708-91471d7ed395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDQ5MDYsIm5iZiI6MTcwODcwNDYwNiwicGF0aCI6Ii8yNTE0MzUwMy8zMDczMTc0MDAtNGM0NjM2YzMtNjYxOC00M2I0LTg3MDgtOTE0NzFkN2VkMzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE2MTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYzRmYjI3MjRiZmUyNmQyNDE0NjI0ZGI1ZjQ4ZjkwY2UwZTlmNTE2OWI5MTljYmNlOWY1YTNjMjVjNmNjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FvftSzpvxOMivsjOmG59J34oAxQeeUyr8cW7O5_YI0w">

@rithviknishad Sir, I actually meant to address the unintentional data loss concern by adding a 'Discard Changes' confirmation modal. However, following @Ashesh3's suggestion, I think upgrading the form for draft support can be a better approach. 

I want to work on this issue. Can you please assign this to me?

**Comment by Ashesh3** [comment]
> > @Ashesh3 I think @Keshav-0907 meant more like a "Confirm Navigate Away" popup to prevent accidental navigations. Yes, we can always enable form restorations too on top of this.
> > <img alt="image" width="372" src="https://private-user-images.githubusercontent.com/25143503/307317400-4c4636c3-6618-43b4-8708-91471d7ed395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDQ5MDYsIm5iZiI6MTcwODcwNDYwNiwicGF0aCI6Ii8yNTE0MzUwMy8zMDczMTc0MDAtNGM0NjM2YzMtNjYxOC00M2I0LTg3MDgtOTE0NzFkN2VkMzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE2MTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYzRmYjI3MjRiZmUyNmQyNDE0NjI0ZGI1ZjQ4ZjkwY2UwZTlmNTE2OWI5MTljYmNlOWY1YTNjMjVjNmNjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FvftSzpvxOMivsjOmG59J34oAxQeeUyr8cW7O5_YI0w">
> 
> @rithviknishad Sir, I actually meant to address the unintentional data loss concern by adding a 'Discard Changes' confirmation modal. However, following @Ashesh3's suggestion, I think upgrading the form for draft support can be a better approach.
> 
> I want to work on this issue. Can you please assign this to me?

Hey, remember that our higher order <Form component already has drafts support, you just need to convert the shifting form to use that higher order <Form component.
basically to convert basic html <form> to our custom <Form implementation which we already have.

**Comment by AshrafMd-1** [comment]
@Keshav-0907 are you still working on this issue?
If not I would like to work on this

**Comment by AshrafMd-1** [comment]
@rithviknishad it seems like @Keshav-0907 is inactive 
can you assign me this issue

**Comment by AshrafMd-1** [comment]
I am actually slightly busy in doing other issues [p2] so as of now I will unassign myself

**Comment by gigincg** [comment]
@Keshav-0907 Are you interested in taking this up?

**Comment by Keshav-0907** [comment]
@gigincg Yeah sure, I will work on it

**Comment by gigincg** [comment]
@Keshav-0907 Assigned the issue to you. Do create a draft PR when you start working on it

For any help, feel free to reach out here. Also join in on our slack community at https://slack.ohc.network

**Comment by JavidSumra** [comment]
@gigincg Sir  Does this issue still persist? If no one is working on it, may I take it up?

**Comment by Utkarsh-Anandani** [comment]
Hello @gigincg @rithviknishad can i work on this issue, I've understood the doings.

**Comment by rajku-dev** [comment]
Hi @rithviknishad, can i take up this issue. 
Please assign me so that i raise a PR soon.

**Comment by Utkarsh-Anandani** [comment]
I'm working on the issue @rajku-dev

**Comment by rajku-dev** [comment]
> I'm working on the issue @rajku-dev 

I noticed an inactivity but that's alright go ahead.
