### ISSUE TITLE
Overflow of some fields such as district in the user management page

### ISSUE THREAD

**Issue by alanansari** [coronasafe/care_fe#7256]
**Describe the bug**
Fields like Role and District in the user management page are fixed in width, so if a word of length greater than that width comes there it overflows over other elements or goes out of boundary.

**To Reproduce**

1. Go to https://care.ohc.network/
2. Click on 'Users' tab in the left sidebar
3. Scroll down to the cards

**Expected behavior**
The fields if overflowed should wrap the elements in the next line to align themselves or the text itself can be shortened instead of showing the full names. Eg: Thiruvananthapuram can be Thiruvanan.. and hovering over shows a tooltip with full text.

**Screenshots**
<img width="252" alt="image" src="https://github.com/coronasafe/care_fe/assets/22475370/fde89a9b-6acb-4dba-a055-8b41a8eeaa8d">

**Desktop:**

- OS: Windows 11
- Browser Chrome
- Version 122.0.6261.57 (Official Build) (64-bit)

I would like to work on this issue as well.

**Comment by kshitijv256** [comment]
I would like to work on it

**Comment by rithviknishad** [comment]
@kshitijv256 feel free to take this up once the changes requested 3 weeks ago for https://github.com/coronasafe/care_fe/pull/7111 has been addressed

**Comment by alanansari** [comment]
I would like to work on this issue.
