### ISSUE TITLE
Bug : Values in Forms can be Negative

### ISSUE THREAD

**Issue by Keshav-0907** [coronasafe/care_fe#7272]
**Describe the bug**
Currently in forms users are allowed to input negative values in places where it's should be not allowed. 

**To Reproduce** 
(one of the examples)
1. Navigate to '/facility/a782943c-6db9-4994-880d-2c391b89b955'
2. Click on "Add Triage"
3. Fill out the form with a negative value and submit
4. Observe the bug.

**Expected behavior**
The form should not allow for negative values, and the minimum value accepted should be 0.

**Screenshots**

https://github.com/coronasafe/care_fe/assets/91189139/e75ffa39-8930-45a8-af12-bf41ffed4593

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 22

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Keshav-0907** [comment]
@rithviknishad, there are other forms also where the minimum value is not defined. Should I also fix them in the same PR?

**Comment by rithviknishad** [comment]
Yup, go ahead! Update the issue description and title too

**Comment by Keshav-0907** [comment]
Okay :)

**Comment by rithviknishad** [comment]
@Keshav-0907 re-request for review once the changes are done.

**Comment by nihal467** [comment]
![image](https://github.com/coronasafe/care_fe/assets/57055998/6be836fb-9bdc-46fa-bdfa-e313f750c885)

@rithviknishad @Keshav-0907 can we have frontend validation like this rather than the browser validation

**Comment by Keshav-0907** [comment]
Absolutely, @nihal467 ! Having frontend validation instead of relying solely on browser validation is a great idea. It provides a more seamless and user-friendly experience.

**Comment by Keshav-0907** [comment]
@nihal467 @rithviknishad @Ashesh3 

Sir I have updated the PR #7273 by implementing frontend validation instead of browser validation. 

<img width="1422" alt="Screenshot 2024-02-29 at 10 22 04 AM" src="https://github.com/coronasafe/care_fe/assets/91189139/a4a0869a-9bcb-4d06-8aba-79c236ef9a60">
