### ISSUE TITLE
Inline view of selected options of Multiselect

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7278]
## Is your feature request related to a problem?
Currently, the selected options of a Multi-select component are shown below the input field. It'd be cleaner to show these selected option chips inside the field itself.

## Describe the solution you'd like

- [ ] Show the selected options within the input itself. 
- [ ] Overflowing chips could be wrapped in a new line within the input itself or horizontally scrollable in one line. 
- [ ] Each chip could optionally also have a remove button to the right of it.

### Current
<img width="882" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/8cf5c76c-b1ab-4a6f-8c8f-852ed0d9fc26">

### Expected

<img width="1417" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/b37cceaa-14f5-4106-aa37-1e04d76e2560">

**Comment by UdaySagar-Git** [comment]
I want to work on this please assign me

**Comment by nihal467** [comment]
@creator79 To avoid multiple authors raising duplicate PRs, it's a recommended best practice to first get the issue assigned to yourself before pushing a PR.

@UdaySagar-Git feel free to take other open unassigned issues
