### ISSUE TITLE
Inconsistency in details of user

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7281]
**Is your feature request related to a problem? Please describe.**
When new user is registered, one of the info sought is the date of birth.
However, when an existing users edits/updates his details in his own profile, the edit profile form asks for Age and not date of birth.

There is inconsistency.

**Describe the solution you'd like**
On Edit Profile form (https://plexus.coronasafe.in/user/profile) ask for "Date of birth" instead of Age. 

**Describe alternatives you've considered**

**Additional context**

**Comment by rash-27** [comment]
I would like to work on this issue.

**Comment by varunsh17** [comment]
I can take up on this issues if no one else is already..

**Comment by rash-27** [comment]
@aparnacoronasafe I have noticed that there is no field for date of birth in the user model. There is only the age field. Now, should I convert the date of birth field while creating the user to the age field, or need to change the backend?

**Comment by Shahbaz898414** [comment]
Hey, can i work on this issue?
