### ISSUE TITLE
Live feed viewing and camera controls- inconsistency

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7284]
**Is your feature request related to a problem? Please describe.**
In CARE Live camera feed is visible on 2 screens.
1) On patient file ( https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/feed)
![Uploading Screenshot 2024-02-27 at 2.33.32 PM.png…]()

2) On facility> live monitoring for location (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/live-monitoring?location=09ab6e88-9132-434a-b8ab-b342b10e7bef) 
![Uploading Screenshot 2024-02-27 at 2.32.21 PM.png…]()

The camera feed design as well as the controls available to pan the camera are slightly different on both.

**Describe the solution you'd like**
Users prefer the view on the live monitoring page. The advantages are:
- Option to pan camera diagonaly
- All the controls for the camera are placed in the bottom half, making it easier to find
- The precision setter is right in the centre of buttons to pan, making the experience more intuitive

Bring the design and features of camera feed view on controls available on Live Monitor page to patient file as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by shivankacker** [comment]
Will work on as soon as middleware is online

cc. @gigincg

**Comment by rithviknishad** [comment]
@skks1212 solved in #7654
