### ISSUE TITLE
Improving UI of Facility dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7285]
The current facility dashboard (https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718) is 
<img width="1202" alt="Screenshot 2024-02-27 at 2 43 59 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/ac3ae566-1dc9-437d-897a-0ef1cde1662f">

Make the following changes to improve the usability of the screen

- [ ] rearrange the banner on top with basic details of the hospital as below:
a) arrange the address and phone number along with the rest of the details
b) Enlarge the image. retain aspect ratio of 1:1
c) reduce the spacing between "manage facility" and "central nursing station" and reduce height of the entire banner.
<img width="1129" alt="Screenshot 2024-02-27 at 2 52 28 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/df0ee3e2-ae62-48c9-8e22-8169329b8631">

- [ ] Below the banner with basic details of the hospital, there are cards for "Oxygen information" "bed capacity", "Doctors list" and "corona Triage". rearrange these as 
1. "Bed capacity"
2. "Doctors List"
3. "Oxygen information"
4. "corona Triage"

**Comment by kshitijv256** [comment]
I can work on this issue

**Comment by aparnacoronasafe** [comment]
@kshitijv256 Awesome!

**Comment by Shahbaz898414** [comment]
@aparnacoronasafe Hey, can i work on this issue?

**Comment by Thanush19** [comment]
hey , i can fix this..? 
kindly , assign it to me..
