### ISSUE TITLE
Events (Beta) improvement

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7286]
**Is your feature request related to a problem? Please describe.**
Events (Beta) recently introduced, show a lot of redundant data.
On patient dashboard (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e)

**Describe the solution you'd like**

- [ ] For every critical log update 22 separate items appear in the events list. There is no logic to what information comes clubbed together as one item in events list and what information comes up as a separate items. 

- [x] When vital are updated automatically by virtual nursing assistant, events update reads as "(Nurse) created the Daily Round Details Event." , instead it must read as "Virtual nursing assistant created the Daily Round."

- [x] Only the fields in daily rounds that's updated must come up in events. Right now a lot of fields are listed with N/A against it.

- [x] When "Treating physician is updated in consultation, no update comes up in events list

**Describe alternatives you've considered**

**Additional context**

**Comment by aeswibon** [comment]
@aparnacoronasafe Can you tell me on which basis should I club the events?

cc: @gigincg
