### ISSUE TITLE
re-arrange tabs in patient dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7288]
**Is your feature request related to a problem? Please describe.**
The patient dashboard (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e)  has multiple tabs into which clinical data is arranged. These tabs can be named and arranged better.

**Describe the solution you'd like**

- [ ] Rename "Summary" to "Vitals"
- [ ] Rename "Update" to "Overview"
- [ ] Rename "Neurological monitoring" to "Neuro"
- [ ] Rename "Respiratory Support" to "Ventilation"
- [ ] Rearrange it as
1. Overview
2. Feed
3. Vitals
4. ABG
5. Medicines
6. files
7. Investigations
8. Neuro
9. Ventilation
10. Nutrition
11. Pressure sore
12. Nursing
13. Dialysis

**Describe alternatives you've considered**

**Additional context**

**Used** 
Update
summary
feed
medicine
file
Investigation
Nursing care
Resp Support

**Comment by AnkurPrabhu** [comment]
i can work on this issue can you pls assign this to me  @aparnacoronasafe

**Comment by arnit-coder** [comment]
Hi!
Is there anyone working on this issue?
If not may i proceed with the task?

**Comment by AnkurPrabhu** [comment]
Yes I am
