### ISSUE TITLE
Improving Tabs in patient dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7289]
**Is your feature request related to a problem? Please describe.**
The patient dashboard (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e) has multiple tabs into which clinical data is arranged. 

For many patients, most of these tabs have no data. So the viewer still has to go through each tab to see which one has data and which does not. 

Hiding the tabs is not a good move, since showing empty tabs encourages doctors to enforce entry of more data into CARE.

**Describe the solution you'd like**
Show the tabs with no data as faded. Viewer should be able to differentiate between tabs with or without data without opening each tab.

**Describe alternatives you've considered**

**Additional context**

**Comment by SinghYuvraj0506** [comment]
Hi @aparnacoronasafe , i have a suggestion regarding the issue, you idea of fading the tabs with no patients is good but how would the user come to know about this feature until informed, instead the tabs already show occupancy and if there are no patients then occupancy is by default zero and hence I think we can give all these 0 occupancy tags a separate color or add certain fields in filters tags.

**Comment by SinghYuvraj0506** [comment]
Or we can mark a new tag on the tabs

**Comment by pankaj87072** [comment]
@aparnacoronasafe @SinghYuvraj0506 what's your views on this 
[Screencast from 28-02-24 01:29:47 AM IST.webm](https://github.com/coronasafe/care_fe/assets/112722707/3642ab81-adbd-4cd6-90fc-03fd31e50a5e)

**Comment by pankaj87072** [comment]
@aparnacoronasafe @SinghYuvraj0506 what is your view's on this 
[Screencast from 28-02-24 01:42:13 AM IST.webm](https://github.com/coronasafe/care_fe/assets/112722707/c4cbeb04-0c89-466c-9e2d-7a3a28443d5a)

**Comment by sainak** [comment]
@SinghYuvraj0506 @pankaj87072 
the requirement is to indicate the user that tabs like investigations/abg/nursing dont have any data
<img width="1135" alt="image" src="https://github.com/coronasafe/care_fe/assets/46787056/04471f48-5dd4-46c7-a72c-5036ec6712b0">

cc: @aparnacoronasafe

**Comment by SinghYuvraj0506** [comment]
@sainak thanks for helping, I got your point. I am currently facing an issue in solving this issue, if we want to differentiate between the tabs on the basis of data if they contain or not, then we may have to fetch all their corresponding data at once when the page loads, because the tabs are requesting for data when they are active.

Can you tell me is it the way to solve the issue or there is some other method too for it?

**Comment by saloni0419** [comment]
@aparnacoronasafe , Can you please assign me this issue?

**Comment by yashmangal112** [comment]
@aparnacoronasafe , Can you please assign me this issue?

**Comment by r-nikhilkumar** [comment]
@aparnacoronasafe can you please assign this issue to me?

**Comment by Shahbaz898414** [comment]
@aparnacoronasafe can you please assign this issue to me?

**Comment by Shahbaz898414** [comment]
Hi @aparnacoronasafe  I'd like to take on this issue

**Comment by rithviknishad** [comment]
@aparnacoronasafe This would require fetching data of all tabs when loading the consultation dashboard at once to determine whether the tab has data or not (as mentioned in https://github.com/coronasafe/care_fe/issues/7289#issuecomment-1968630321). A lot of network bandwidth would be required to facilitate this, especially for a page that is frequently used it could make this page slower.

**Comment by aparnacoronasafe** [comment]
@gigincg can you suggest a way out?

**Comment by gigincg** [comment]
@aparnacoronasafe If doctors have an understanding of what all data are relavant to a certain type of patient, they might be able to skip certain tabs. 

If based on any parameters from a consultation (Diagnosis or Decision after Consultation for eg.) some tabs can be hidden, we can do that.

**Comment by nihal467** [comment]
not aligned with the current develop version
