### ISSUE TITLE
Log update- vitals

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7290]
**Is your feature request related to a problem? Please describe.**
In Log updates (Critical round), Vitals section, there is a section to mark details of pain.

Against a region, user can mark scale of pain from 0-5. 

<img width="285" alt="Screenshot 2024-02-27 at 3 35 23 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/15f6dd87-52d6-4bec-b9d3-53518dead6f1">

Here the text "Low" , "Normal", "High" comes written next to the number.

**Describe the solution you'd like**

It is not useful to tag pain as "Normal"

Only retain "Low" only at 0 and "High" at 5.

- [ ] remove the appearance of "normal" against 1-4 painscale

**Comment by saloni0419** [comment]
@aparnacoronasafe can you please assign me this issue

**Comment by aparnacoronasafe** [comment]
@saloni0419 done!

**Comment by saloni0419** [comment]
![image](https://github.com/coronasafe/care_fe/assets/100074110/5f70beee-8058-4fe8-8705-4bdc077ce3d2)
I have set up the project locally 
Can you please tell me how should I login, there is no way to sign up showing here

**Comment by saloni0419** [comment]
Hey, @aparnacoronasafe can you please guide me to where I can generate this issue on the website?

**Comment by saloni0419** [comment]
![image](https://github.com/coronasafe/care_fe/assets/100074110/54916742-3f7e-4481-abab-241dec4bc35f)
Is this the same issue here mentioned because I am confused there are so many options in vitals showing high and low

**Comment by saloni0419** [comment]
> Hey, @aparnacoronasafe can you please guide me to where I can generate this issue on the website?

I have generated the issue now

**Comment by saloni0419** [comment]
@aparnacoronasafe I have solved the issue, i am not able to push it on Git Hub i am running the command right but on git commit it is showing no filed staged. I have forked, cloned right added a new branch, and git add. , git status. I have done all these still showing the error. Can you please help me
![image](https://github.com/coronasafe/care_fe/assets/100074110/3e1591ca-65cd-4044-977a-7857229b7232)

**Comment by rithviknishad** [comment]
@saloni0419  You'll need to stage your changes first before being able to commit them.

Refer: https://school.ohc.network/targets/19455

**Comment by rithviknishad** [comment]
@saloni0419 what does `git status` and `git diff` show?

**Comment by saloni0419** [comment]
@rithviknishad git diff shows nothing and git status shows 
![image](https://github.com/coronasafe/care_fe/assets/100074110/ee7d5da4-669d-4b4d-a0b7-7917049b0448)

**Comment by rithviknishad** [comment]
Seems weird. Are you in the right directory? 😅 

cc: @sainak @Ashesh3

**Comment by sainak** [comment]
@saloni0419 it's better to use the integrated terminal or the visual git manager included in your editor

**Comment by sainak** [comment]
Most of the problems can be solved with a simple on/off so close your terminal and editor and open them again in the correct path

**Comment by saloni0419** [comment]
@sainak I have done it I have even reforked it. but I will try to get it in the integrated terminal

**Comment by saloni0419** [comment]
![image](https://github.com/coronasafe/care_fe/assets/100074110/70c5caf1-2144-4cb8-9830-ebba8640c8f1)
![image](https://github.com/coronasafe/care_fe/assets/100074110/a5800792-e72f-4e86-8263-b436c0ca7144)

i did it again still shows the same issue

**Comment by Ashesh3** [comment]
> ![image](https://private-user-images.githubusercontent.com/100074110/308438020-70c5caf1-2144-4cb8-9830-ebba8640c8f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDA2NzEsIm5iZiI6MTcwOTEwMDM3MSwicGF0aCI6Ii8xMDAwNzQxMTAvMzA4NDM4MDIwLTcwYzVjYWYxLTIxNDQtNGNiOC05ODMwLWViYmE4NjQwYzhmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwNjA2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQxN2YxMDE4ZmZiODhlNGMwYjhhMTdhYTg0MWJjYjNlMGE4ZmNjZjYzMDc5MDhjNmE5MDE3NmEwODM0MDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P33PIbY_jRwhUpasjkc6OkaJyTvxe-H4QnT00x7g28M) ![image](https://private-user-images.githubusercontent.com/100074110/308438120-a5800792-e72f-4e86-8263-b436c0ca7144.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDA2NzEsIm5iZiI6MTcwOTEwMDM3MSwicGF0aCI6Ii8xMDAwNzQxMTAvMzA4NDM4MTIwLWE1ODAwNzkyLWU3MmYtNGU4Ni04MjYzLWI0MzZjMGNhNzE0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwNjA2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzdkZGQ5MjU5NTRlYWNkODdlNzkwNThjOTQ2N2I5NzRiODZhZjBkMmNlZTU2MDc1ZjBmN2IzOWFmMTNjYmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o4kf8JeFqxSBZdDPNJutMgeuVZMLwXiq46ofUDYC4-k)
> 
> i did it again still shows the same issue

Can you verify if your changes are still there in the respective files?

**Comment by saloni0419** [comment]
@Ashesh3 yes I have changed the file but it showing modified husky.sh

**Comment by saloni0419** [comment]
![image](https://github.com/coronasafe/care_fe/assets/100074110/7b8744ae-f970-4809-a496-74b67076334b)
here is the ss of change in UI. i have solved this issue and changed the code

**Comment by Ashesh3** [comment]
> ![image](https://private-user-images.githubusercontent.com/100074110/308439551-7b8744ae-f970-4809-a496-74b67076334b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDA5MjAsIm5iZiI6MTcwOTEwMDYyMCwicGF0aCI6Ii8xMDAwNzQxMTAvMzA4NDM5NTUxLTdiODc0NGFlLWY5NzAtNDgwOS1hNDk2LTc0YjY3MDc2MzM0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwNjEwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDAwYWY1ZjJhMGE2NjdkYTIxMDk0NDFjNzg3ZThkZGI0YTdkMzlhMmY5ZTM3MzI1ZjczZmMyODVmMDc4YWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qmsMFufuEMWoAWb5r1dsnHeaApX6SF7xD567vnNamrI) here is the ss of change in UI. i have solved this issue and changed the code

Could you point out the full path of the file you edited in order to make this change? (Entire path `/d/...../.../...`)

**Comment by saloni0419** [comment]
D:\Open Source\care_fe\src\Components\CriticalCareRecording\Pain\CriticalCare__PainInputModal.bs.js

**Comment by sainak** [comment]
> D:\Open Source\care_fe\src\Components\CriticalCareRecording\Pain\CriticalCare__PainInputModal.bs.js

@saloni0419 the above file is generated from src/Components/CriticalCareRecording/Pain/CriticalCare__PainInputModal.res
the issue that you are working on requires changes in rescript files

**Comment by Ashesh3** [comment]
As Aakash said above, you need to make changes to `src/Components/CriticalCareRecording/Pain/CriticalCare__PainInputModal.res` file, and the same will auto reflect in your preview, then try to git add that file, make the commit and push changes.

**Comment by saloni0419** [comment]
okay I am doing it

**Comment by saloni0419** [comment]
I am just new to rescript files and just wanted to know, that I have changed the code in .res file, now how it will reflect the change in js and overall . can anyone please help in this

**Comment by Ashesh3** [comment]
> I am just new to rescript files and just wanted to know, that I have changed the code in .res file, now how it will reflect the change in js and overall . can anyone please help in this

Once you've made the changes to the Rescript file (.res), you need to build them

1. To build them just once you can run `npm run build:res`  (Which runs `rescript clean && rescript build`)
2. For a better dev experience, run the rescript builder in watch mode `npm run dev:res`, this will auto build your .res files as you keep making changes.
3. After the build, refresh the page if that does not happen automatically and you should see your changes.

To learn more about rescript files: https://rescript-lang.org/

**Comment by saloni0419** [comment]
I have linked a PR yesterday. 
Please review it.
