### ISSUE TITLE
Flicker when loading new page

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#7293]
**Describe the bug**
Changing page has a flicker when you load in a new page not stored in memory.
- I suppose issue is due to the loading mechanism in `index.html`

**To Reproduce**

- Switch Pages, there should be a short white flicker where everything disappears.

**Comment by ab1123** [comment]
Hello @skks1212 if you haven't already fixed the bug, can I work on the bug??

**Comment by shivankacker** [comment]
@ab1123 sure, you can take this up.

**Comment by Thanush19** [comment]
hey @skks1212 ,if the issue is not resolved , i can fix this

**Comment by ab1123** [comment]
Thanks @skks1212

**Comment by nihal467** [comment]
@ab1123 Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by nihal467** [comment]
the issue seem to be resolved,
