### ISSUE TITLE
Improving Facility type options

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7295]
**Is your feature request related to a problem? Please describe.**
The facility registration form (https://care.coronasafe.in/facility/create) allows users to tag facility as

1. Private Hospital
2. Other
3. TeleMedicine
4. Govt Hospital
5. Labs
6. Primary Health Centres
7. 24x7 Public Health Centres
8. Family Health Centres
9. Community Health Centres
10. Urban Primary Health Center
11. Taluk Hospitals
12. Taluk Headquarters Hospitals
13. Women and Child Health Centres
14. General hospitals
15. District Hospitals
16. Govt Medical College Hospitals
17. Co-operative hospitals
18. Autonomous healthcare facility
19. Corona Testing Labs
20. Corona Care Centre
21. Shifting Centre
22. Request Approving Center
23. Request Fulfilment Center

So many options tend to be confusing for the users. 

**Describe the solution you'd like**

- [ ] Rename "Lab" to "Government Lab"

- [ ] Add a new type "Private Lab"

- [ ] Edit the list to have only the following items in the said order:
1. Primary Health Centres
2. Family Health Centres
3. Community Health Centres
4. Women and Child Health Centres
5. Taluk Hospitals
6. District Hospitals
7. Govt Medical College Hospitals
8. Govt. Labs
9. Pvt Labs
10. TeleMedicine
11. Private Hospital
12. Autonomous healthcare facility
13. Shifting Centre
14. Request Approving Center
15. Request Fulfilment Center
16. Other

- [ ] Migrate data: all facilities that have selected the following facility type (which is removed from the list) data may be migrated in the following manner:
1. 24x7 Public Health Centres & Urban primary health centre- Add to Primary health centres
2. Taluk Headquarters Hospitals- add to taluk hospitals
3. General hospitals- Add to district hospitals
4. Co-operative hospitals- Add to "Autonomous healthcare facility"
5. Corona Testing Labs- Add to "Govt. Labs"
6. Corona Care Centre- Add to "other"
7. Govt hospitals- Add to "Govt Medical College Hospitals"

**Comment by varunsh17** [comment]
I have read the requirements and would like to work upon this issue gladly!

**Comment by varunsh17** [comment]
I am working extensively on other issue, Please assign it to someone else..

**Comment by Vibhu1710** [comment]
Hi! If no one else is working on this issue, I can gladly take this up..
I also have a doubt, I think the migration part is BE related, right? whatever comes up from BE we are showing it in "/facility" page [specifically in FacilityCard.tsx]..

**Comment by SinghYuvraj0506** [comment]
Hi @sainak @aeswibon i want to work on the issue, if its free as the frontend part is very easy and its done should I create a pull request. For the already created data we need to change it from backend for permanent resolution should I create a pull request on backend repo.

**Comment by pankaj-2503** [comment]
Hi, @aeswibon  can i work on this issue it seems like it has to change the frontend as well as backend for from options to selects items from.

**Comment by aeswibon** [comment]
> Hi! If no one else is working on this issue, I can gladly take this up.. I also have a doubt, I think the migration part is BE related, right? whatever comes up from BE we are showing it in "/facility" page [specifically in FacilityCard.tsx]..

@Vibhu1710 Would you like to work on this issue??

**Comment by Vibhu1710** [comment]
Hey @aeswibon, FE part is quite easy! Ig this requires resolution from BE repo as well. Not confident about BE repo as of now, I guess we can assign it to other contributors.. Would like to keep an eye on any other FE issues however :)

**Comment by aeswibon** [comment]
> Hi @sainak @aeswibon i want to work on the issue, if its free as the frontend part is very easy and its done should I create a pull request. For the already created data we need to change it from backend for permanent resolution should I create a pull request on backend repo.

Have assigned the issue to you. You can open the PR now...

**Comment by SinghYuvraj0506** [comment]
Hi @aeswibon i have done changes in the frontend and its working fine, for the backend migrations I have made changes in facility.py model you can see in the figure, is it ok, how can I make migrations out of these changes. 

<img width="954" alt="Screenshot 2024-02-29 at 3 05 53 PM" src="https://github.com/coronasafe/care_fe/assets/98007961/28fb6ffa-344a-4ba6-82dd-ed73eea1dc9f">
<img width="1141" alt="Screenshot 2024-02-29 at 3 06 30 PM" src="https://github.com/coronasafe/care_fe/assets/98007961/0ccc7546-9cfb-446d-ab0f-d21449320fa3">

**Comment by arnit-coder** [comment]
Is this issue still open?
If not i would love to work on this issue

**Comment by aeswibon** [comment]
> Hi @aeswibon i have done changes in the frontend and its working fine, for the backend migrations I have made changes in facility.py model you can see in the figure, is it ok, how can I make migrations out of these changes.
> <img alt="Screenshot 2024-02-29 at 3 05 53 PM" width="954" src="https://private-user-images.githubusercontent.com/98007961/308872460-28fb6ffa-344a-4ba6-82dd-ed73eea1dc9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDkzOTMsIm5iZiI6MTcwOTIwOTA5MywicGF0aCI6Ii85ODAwNzk2MS8zMDg4NzI0NjAtMjhmYjZmZmEtMzQ0YS00YmE2LTgyZGQtZWQ3M2VlYTFkYzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDEyMTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MzVmMmE4OGNmMmQ2Yzc0ZjlkMTljNzNmMjk5MDY0ZDdhNDg3ZmQ2MzgwNGU1ODIwMTc3MDNmMjlmNDY5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mTbIiLKb3CAokjwLj2zGGrX9s2C6BedeWtTxaBDuRvM"> <img alt="Screenshot 2024-02-29 at 3 06 30 PM" width="1141" src="https://private-user-images.githubusercontent.com/98007961/308872476-0ccc7546-9cfb-446d-ab0f-d21449320fa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDkzOTMsIm5iZiI6MTcwOTIwOTA5MywicGF0aCI6Ii85ODAwNzk2MS8zMDg4NzI0NzYtMGNjYzc1NDYtOWNmYi00NDZkLWFiMGYtZDIxNDQ5MzIwZmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDEyMTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNDc0Y2M0MDMzZDdkNjlhZmMwZWI1YTg5OTE1YzNmOTg2YWY1Y2RiZWZkMzgwMTIwMDA0ODk3ODQwOWEzOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XoQosSAP_W8-u_jhHkmQFL4EPB9WUeaIr4dcp0ofCSw">

You can use makemigrations utility from django. 
Read this: https://docs.djangoproject.com/en/5.0/topics/migrations/

**Comment by aeswibon** [comment]
> Is this issue still open? If not i would love to work on this issue

This issue is already taken. You can work on other issues. There are plenty of them...
