### ISSUE TITLE
Bed Capacity- facilities

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7296]
**Is your feature request related to a problem? Please describe.**
Within facilities, there is option to update bed capacity (https://care.coronasafe.in/facility/create)
There are n number of bed types given in the form, which is confusing.

Current list
1. Ordinary Beds
2. Oxygen beds
3. ICU (ICU without ventilator)
4. Ventilator (ICU with ventilator)
5. Covid Ordinary Beds
6. Covid Oxygen beds
7. Covid ICU (ICU without ventilator)
8. Covid Ventilators (ICU with ventilator)
9. Hostel
10. Single Room with Attached Bathroom

**Describe the solution you'd like**
Update the list to
1. Ordinary bed 
2. Oxygen supported bed
3. ICU beds
4. Isolation bed
5. Others

beds marked under the redundant bed types may be deleted. 

![image](https://github.com/user-attachments/assets/d4efff2e-fa12-47fb-880b-9ba8a2983f6e)

**Comment by Ayush398** [comment]
Can you please assign me this issue

**Comment by nihal467** [comment]
@Ayush398 Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by khavinshankar** [comment]
@aparnacoronasafe can u point out how the existing bed types should be mapped to new bed types. 

cc: @nihal467

**Comment by aparnacoronasafe** [comment]
@khavinshankar please find notes on mapping below:


Ordinary Beds- Ordinary bed
Oxygen beds- Oxygen-supported bed
ICU (ICU without ventilator)- ICU beds
Ventilator (ICU with ventilator)- ICU beds
Covid Ordinary Beds- Ordinary bed
Covid Oxygen beds- Oxygen-supported bed
Covid ICU (ICU without ventilator)-  ICU beds
Covid Ventilators (ICU with ventilator)-  ICU beds
Hostel- Others
Single Room with Attached Bathroom- Isolation bed
