### ISSUE TITLE
Facility registration form- cover photo upload

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7297]
**Is your feature request related to a problem? Please describe.**
When registering a facility, user gives all details of the facility in the facility registration form (https://care.coronasafe.in/facility/create). However, this form has no option to add facility cover image.

The facility cover image is uploaded after the user submits the facility registration form with the details and is taken to the facility dashboard (https://care.coronasafe.in/facility/31809579-8e0d-402a-b137-843fd77f6290) where the option to upload facility cover image appears.

**Describe the solution you'd like**
Add option to upload facility cover image in the facility registration form itself. This shall be a non-mandatory item.

Retain the option to upload cover image in the facility dashboard as is.

**Comment by alanansari** [comment]
Hi, I would like to take this issue.

**Comment by alanansari** [comment]
Hi, can you include these to reproduce the above mentioned details:
- the account where this can be accessed by.
- The UI required to be implemented. (design or image)
- Image of the current faculty dashboard where the option to upload image is present.

**Comment by saloni0419** [comment]
@aparnacoronasafe Can you please assign me this issue

**Comment by arnit-coder** [comment]
> @aparnacoronasafe Can you please assign me this issue

Actually I had raised a PR for this issue.

**Comment by arnit-coder** [comment]
@aeswibon Sir, I had raised a PR in which i had solved 2 issues this one and #7309 .

**Comment by nihal467** [comment]
@arnit-coder Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by NikhilGolla72** [comment]
hello @nihal467 i would like to contribute to this issue, it no one is assigned,could you please assign me to this.

**Comment by rithviknishad** [comment]
This can be added as a step in the facility create form

**Comment by Utkarsh-Anandani** [comment]
Is the issue still open, I would love to contribute to it @rithviknishad @bodhish

**Comment by NikhilGolla72** [comment]
@rithviknishad  @bodhish  @Utkarsh-Anandani Sorry rithvik, I couldn't focus on this as I was having my semester exams and i am done with them today. I am still working on this issue and about to complete it. Please assign me to this issue.

**Comment by Utkarsh-Anandani** [comment]
@rithviknishad @bodhish @nihal467 
Should I create a PR?

- Desktop view
![Image](https://github.com/user-attachments/assets/0dc49ecb-ebce-439c-9cc3-6c3aadd4b994)

- Phone view
![Image](https://github.com/user-attachments/assets/8863402c-47c8-4df2-a6b1-e36a6fbf24e4)

**Comment by rithviknishad** [comment]
Yup!

**Comment by Paul-sharon** [comment]
I would like to work on this issue.

**Comment by rithviknishad** [comment]
@Utkarsh-Anandani what's the status on this?
