### ISSUE TITLE
Enhancement: Add hover effects on navbar

### ISSUE THREAD

**Issue by pankaj-2503** [coronasafe/care_fe#7306]
**Is your feature request related to a problem? Please describe.**
Adding hover effects on navbar feels dynamic website but here it feels like some text is written in navbar section.
**Describe the solution you'd like**
![image](https://github.com/coronasafe/care_fe/assets/90036864/f8309a36-c8a8-49a0-9f7a-94e857ec982f)

**Describe alternatives you've considered**

**Additional context**

**Comment by pankaj-2503** [comment]
I would like to work on this issue if it get's assigned to me.

**Comment by rithviknishad** [comment]
@pankaj-2503 The site https://ohc.network/ does not belong to this repository. Managing this site is out of the scope of contributors.

Checkout https://care.ohc.network/ which is this repository.
