### ISSUE TITLE
Issue in adding new user in users section

### ISSUE THREAD

**Issue by Ashutosh0602** [coronasafe/care_fe#7307]
> [!NOTE]
> Maintainer Note: The issue was filed a considerable amount of time ago. Ensure that the issue is still relevant before working on solving it. 

Before we enter anything in input section of user it is showing user is available in empty string.

<img width="276" alt="Screenshot 2024-02-28 at 7 46 39 PM" src="https://github.com/coronasafe/care_fe/assets/85889617/b69d9af0-f6ed-4202-8761-e27b2103c015">

There is also some problem with validation of user.

**Comment by Ashutosh0602** [comment]
I would like to work on this please assign me.

**Comment by Ashutosh0602** [comment]
@rithviknishad I solved this issue you can check it once and if there is something wrong you can tell me I will try to solve

**Comment by RushiK100** [comment]
I would like to work on this please assign me

**Comment by nihal467** [comment]
@Ashutosh0602 Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by ivobubenko** [comment]
I would like to work on this, could you please assign it to me

**Comment by SwanandBhuskute** [comment]
I would like to work on this issue!

**Comment by bodhish** [comment]
Nice find @SwanandBhuskute

**Comment by SwanandBhuskute** [comment]
![Image](https://github.com/user-attachments/assets/3e01e24e-c6d8-4af5-aad2-5938ae03c6a8)
The same issue is occuring with Password field

Should i solve it too in the same go? 

Or I have one suggestion
When we have empty fields (haven't typed anything), we can keep it as normal black text and not red, also without any cross/check marks
and once we start typing, then it will perform as usual as now, like
- it will become red for some checks, green for some checks etc

This will work for both Username field as well as Password field....

Will work as per suggestions...

**Comment by rithviknishad** [comment]
yup, can be done in same issue

**Comment by SwanandBhuskute** [comment]
So should I try that "keep normal black text" for empty field and then after typing, behave like now (checks, red, green text) ?

I mean i will try 
because the issue is resolved, just this will add some improvement

**Comment by SwanandBhuskute** [comment]
![Image](https://github.com/user-attachments/assets/ce217075-c913-4292-b9c9-5b446f4adf27)
![Image](https://github.com/user-attachments/assets/30c22be7-8633-4956-8af0-b8f53ecb037b)

So now, before entering any details , this is how username and password fields will look like
- black, with circle

and after we start entering it will be as normal as now

![Image](https://github.com/user-attachments/assets/9d08ce77-8ead-4772-b69a-c87ce7eebc50)
![Image](https://github.com/user-attachments/assets/df5fd214-5157-4363-b374-12d442af14c9)

![Image](https://github.com/user-attachments/assets/3fdfd1bb-8b11-4cda-997b-58b352031227)


should i raise the PR for the same or any more suggestions?

**Comment by Jacobjeevan** [comment]
@SwanandBhuskute Go ahead and open the PR 👍

**Comment by SwanandBhuskute** [comment]
I have raised the pr for this issue
pls check
https://github.com/ohcnetwork/care_fe/pull/8940
