### ISSUE TITLE
Back to Login button in forget password overlapping with CARE Icon

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7308]
**Describe the bug**

In mobile view, the 'Back to login' button in a language other than English is overlapping with the care icon.

**To Reproduce**

1. Go to https://care.coronasafe.in/
2. Click on forgot password button
3. switch to mobile view

**Expected behavior**

the back to login button shouldn't overlap with the CARE Icon in mobile view

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/f15467fa-c9c4-4bde-90c2-bea6f7468526)

**Comment by Vibhu1710** [comment]
Hi @nihal467, I would like to pick up this bug.. Please assign this to me

**Comment by Huzaif-Ahmed** [comment]
hi @nihal467  I would also like to work on this issue and where can i find the link to join the community

**Comment by arnit-coder** [comment]
Hey @Vibhu1710  are you working on this issue?

**Comment by aeswibon** [comment]
> hi @nihal467 I would also like to work on this issue and where can i find the link to join the community

@Huzaif-Ahmed This issue is already assigned. You can work on different issue. As for the communtiy link, you can join our slack channel: https://slack.ohc.network/

**Comment by Vibhu1710** [comment]
Hey @aeswibon , @nihal467... I have made a PR with necessary changes, not sure if I have added the right reviewers or if the branch is out of sync.. Can you please have a look & verify
