### ISSUE TITLE
"Set average weekly working hour" button in user tab is not responsive 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7309]
**Describe the bug**

"Set average weekly working hour" button text is clipping out in user tab ( Mobile View) 

**To Reproduce**

1. Go to https://care.coronasafe.in/users
2. switch to responsive view and see the error

**Expected behavior**

it should be properly responsive in mobile view

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/92b5c777-3514-4f36-8202-6be587c734b1)

**Comment by Ashutosh0602** [comment]
Please assign me I will try to fix this issue.

**Comment by saloni0419** [comment]
@nihal467 can you assign me this issue

**Comment by arnit-coder** [comment]
Respected sir,
I request you to please review my pull request.

**Comment by Ashutosh0602** [comment]
@nihal467 I have solved this issue with another issue related to the Users Section.
Is it right or do I make another pull request for this issue.

**Comment by princepal9120** [comment]
Respected sir,i fix the given issues,please review my issues
![image](https://github.com/coronasafe/care_fe/assets/107296821/cc01baa2-036e-4f9c-b043-92d3871144c3)

**Comment by kabirrajsingh** [comment]
Hi @rithviknishad @nihal467 is this fixed or can I raise a PR for this since it's marked as stale?
Just needs a simple change.
