### ISSUE TITLE
VIsual Bug: Issue in responsiveness

### ISSUE THREAD

**Issue by ab1123** [coronasafe/care_fe#7317]
**Describe the bug**

**To Reproduce**

1. Go to 'care.coronasafe.in/patients'
2. Click on 'sort dropdown in your mobile device'

**Expected behavior**
A dropdown should fill the 70 - 90% width of the page in case of a mobile view. Also there should be a symmetry in the webpage. In mobile view, the export button and the sort dropdown should be in the same row.

**Screenshots**
![WhatsApp Image 2024-03-01 at 02 41 05](https://github.com/coronasafe/care_fe/assets/37205949/6b2a5e81-8b80-431c-b046-0d11310f6f63)
![WhatsApp Image 2024-03-01 at 02 25 59](https://github.com/coronasafe/care_fe/assets/37205949/d1c8c80f-0761-4421-a837-cfac5f5fe90c)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 122.0.6261.71

**Smartphone (please complete the following information):**

- Device: IQOO Z6 Pro 5G
- OS: Android
- Browser Chrome
- Version 122.0.6261.90

**Additional context**
The problem is that the rseponsiveness of the Overall Website is not maintained properly and thus throws visual bugs while using this in phone. The visual bugs are shared as following

**Comment by ab1123** [comment]
Can I work on this issue?

**Comment by ab1123** [comment]
Thanks @rithviknishad

**Comment by ramchandra06032004** [comment]
sir i can solve this issue ,please assign me this issue.
