### ISSUE TITLE
Change type of token from any to avoid security risks

### ISSUE THREAD

**Issue by tanpreetjolly** [coronasafe/care_fe#7319]
**Describe the bug**
The Token type inside the SessionRouter file being passed as prop to ResetPassword component has an "any" type which leads to potential risk of security as any type of data can be received as token. 

**To Reproduce**

1. Go to 'src/Routers/SessionRouters'
2. Click on 'SessionRouters.'
3. Scroll down to 'routes'
4. See token prop passed to ResetPassword Component

**Expected behavior**
The type should be set as a string to avoid potential security risks

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/104998427/f9d05681-61b0-47ca-ad25-25aa9a24bed0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sainak** [comment]
lets get it resolved asap

**Comment by sainak** [comment]
Also make sure to link the docs where this is described as a vulnerability.

**Comment by tanpreetjolly** [comment]
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any
Here's the official docs explaining why "any" shouldn't be used as it simply means turning off safety inside TS. It looses type safety which shouldn't be ideal for sensitive infos like tokens. Here's one more article suggesting it should only used in case of flexibility https://www.totaltypescript.com/concepts/any-type

**Comment by SinghYuvraj0506** [comment]
Hi, can i work on the issue

**Comment by tanpreetjolly** [comment]
You can  assign me this issue if you think this needs to be patched asap

**Comment by rithviknishad** [comment]
> https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any Here's the official docs explaining why "any" shouldn't be used as it simply means turning off safety inside TS. It looses type safety which shouldn't be ideal for sensitive infos like tokens. Here's one more article suggesting it should only used in case of flexibility https://www.totaltypescript.com/concepts/any-type

I still couldn't understand how this is a security risk.

cc: @sainak

**Comment by tanpreetjolly** [comment]
I don't have the exact resource to reference it but to put it simple incase of sensitive info there should be a strict type check as if there is XSS , an attacker can inject a diff type of token that might cause any potential security issues. It's not a vulnerability but a measure to avoid potential risks

**Comment by sainak** [comment]
> [typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any) Here's the official docs explaining why "any" shouldn't be used as it simply means turning off safety inside TS. It looses type safety which shouldn't be ideal for sensitive infos like tokens. Here's one more article suggesting it should only used in case of flexibility [totaltypescript.com/concepts/any-type](https://www.totaltypescript.com/concepts/any-type)

Type safety is only relevant for development, once the code is transpiled, there is no role of typescript in browsers, so how would replacing 'any' help?

**Comment by sainak** [comment]
@tanpreetjolly if you want to fix types, you can create a new issue with a relevant title

**Comment by tanpreetjolly** [comment]
Yeah I think you are correct over here, I got it wrong. I'll create another issue with relevant title
