### ISSUE TITLE
Redesign UI for imports in external results 

### ISSUE THREAD

**Issue by UdaySagar-Git** [coronasafe/care_fe#7327]
**Is your feature request related to a problem? Please describe.**
The current file upload functionality lacks a drag and drop feature, which is a preferred method among users. This absence creates a less intuitive and user-friendly experience.

**Describe the solution you'd like**
Enhancing the file upload experience by implementing a drag and drop feature. Users should be able to simply drag files from their local environment and drop them onto the designated area for uploading.

**Steps to reproduce this**
- click on External results tab 
- click on import results

**Comment by UdaySagar-Git** [comment]
I would like to work on this issue

**Comment by kumar11jr** [comment]
I think it already has drag and drop feature

**Comment by UdaySagar-Git** [comment]
@kumar11jr it is implemented only at some places i guess 
![image](https://github.com/coronasafe/care_fe/assets/111575806/1a4a1edf-5745-4eda-aab4-0760017a1c33)
