### ISSUE TITLE
Improve import UI for External Results Import

### ISSUE THREAD

**Issue by UdaySagar-Git** [coronasafe/care_fe#7333]
**Describe the bug**
The current UI for the External Results import is inconsistent and differs from the UI on other pages. Specifically, when attempting to import, it navigates to new page instead of the present page

**To Reproduce**
1. Go to External Results tab 
2. Click on import 

**Expected behavior**
current ui :
![image](https://github.com/coronasafe/care_fe/assets/111575806/cbf0ebac-fc37-45eb-8e41-030544f01998)
expected ui :
![image](https://github.com/coronasafe/care_fe/assets/111575806/60fb3ece-e8ce-4e19-b21c-78b2a71e827e)

**Comment by UdaySagar-Git** [comment]
can you please assign me !

**Comment by Maku38** [comment]
i wanna work on this...can u assign me this plz
