### ISSUE TITLE
Unable to create a log update for domiciliary care patient

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7340]
**Describe the bug**

when we create a log update for a domiciliary care patient, the backend throws an error

**To Reproduce**

1. Create a patient in domiciliary care
2. Click on log update and create a normal log update
3. See error

**Expected behavior**

Patients with domiciliary care, don't need a bed assigned to them to create a log update 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/b3d5f6e8-2d46-40e1-a273-11b782ea8d30)

**Comment by Ashesh3** [comment]
Fixed by https://github.com/coronasafe/care/pull/1945
