### ISSUE TITLE
Preset save- need to refresh's

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7342]
**Is your feature request related to a problem? Please describe.**
Users have the option to save a change made to the preset position right on patient dashboard- live feed. However such update to the preset is only available when the user refreshes the page. 

**Describe the solution you'd like**
When a user updates preset- such updation must be available immediately. The user must not have to refresh the page to access the updated preset.

**Describe alternatives you've considered**

**Additional context**

**Comment by KshitijTodkar48** [comment]
Hi, I would like to work on this issue, can you please assign it to me?

**Comment by KshitijTodkar48** [comment]
@aparnacoronasafe, how can I get the live feed while developing and testing locally and with what role, can I reach the live feed section?

**Comment by KshitijTodkar48** [comment]
@rithviknishad, @aparnacoronasafe can you please answer my query?

**Comment by rithviknishad** [comment]
You can use the asset "Dev Camera" for testing. It is linked to patient:

https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/feed

**Comment by KshitijTodkar48** [comment]
@rithviknishad, I have found the files to make changes in the codebase. But to test the changes, I checked the assets, no asset had live camera feeds working. And could not find the asset with the name "Dev Camera". And the link you shared is showing "Page not found". Am I missing something here?

**Comment by thedevildude** [comment]
> @rithviknishad, I have found the files to make changes in the codebase. But to test the changes, I checked the assets, no asset had live camera feeds working. And could not find the asset with the name "Dev Camera". And the link you shared is showing "Page not found". Am I missing something here?

Try Logging in using "devdistrictadmin" as username and "Coronasafe@123" as password

**Comment by KshitijTodkar48** [comment]
@rithviknishad , @thedevildude, I logged in as "devdistrictadmin" as you said and reached the camera feed. But the feed is offline. Also, when I start the project locally, there are no patients that have camera feed available and working.

**Comment by rithviknishad** [comment]
As long as you connect your frontend to staging backend, you should be able to access the patient with the dev camera.

Dev Camera could be offline at times. cc: @nihal467 @gigincg

**Comment by KshitijTodkar48** [comment]
@rithviknishad, I have the backend running locally, how to connect my local frontend to the backend, because I still cannot see the "Dev Camera" asset and the live feed, what else should I do?

**Comment by rithviknishad** [comment]
Check now with the above-mentioned credentials. I've updated the configurations

https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/assets/fd605386-90d5-4e8b-bb82-f62b7349d1d3/configure

**Comment by KshitijTodkar48** [comment]
@rithviknishad, Thanks for your help so far. 
I've checked the live-feed, it is working. I tried updating the preset values of the live-feed and the updates were immediately available without the need of refreshing the page. I didn't find the described issue. The updated presets are available immediately without the need of refreshing the page.

**Comment by thedevildude** [comment]
I'd like to work on this issue if it's still relevant

**Comment by KshitijTodkar48** [comment]
Go ahead man, I'm not working on it.

**Comment by Ashesh3** [comment]
@thedevildude could you confirm if the issue is still relevant? After updating a preset - does it reflect immediately or you need to manually refresh the page?

**Comment by thedevildude** [comment]
@Ashesh3 it does seem to work fine in my case.  After updating a preset, I switched to a different preset, and then switched back to the updated preset, the updated preset was as expected without refreshing the page.

**Comment by Ashesh3** [comment]
@aparnacoronasafe could you confirm the same, so we can close the issue?

cc: @nihal467

**Comment by KshitijTodkar48** [comment]
Even I didn't find the described issue @Ashesh3, I've mentioned it earlier as well.

**Comment by rithviknishad** [comment]
I'm able to replicate the issue, it's pretty straightforward as mentioned in the issue.

**Comment by rithviknishad** [comment]
See the attached video, where I try to correct the preset: "Clock" to where the clock is visible. Had to refresh for the preset buttons to know about the new coordinates.

https://www.loom.com/share/44a11f82b1e34c6c8a58116ae1a9fc48?sid=c61559a6-084d-4abd-aeb4-5ca51b7f50b7

**Comment by thedevildude** [comment]
@rithviknishad @Ashesh3  When using `devdistrictadmin` on staging deployment, the default presets doesn't update for some reason. When we refresh the page, the last location of camera is available however on selecting the same default preset again, we are sent back to old position. The patient presets seems to work fine. Is it supposed to happen?

https://github.com/coronasafe/care_fe/assets/63492939/af4d8ffc-1287-4c41-ba04-0f10de3c8c5a

**Comment by thedevildude** [comment]
I've started working on it, should be ready with a draft PR by Monday

**Comment by nihal467** [comment]
@thedevildude Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.
