### ISSUE TITLE
Change WhatsApp message: doctor connect

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7343]
**Is your feature request related to a problem? Please describe.**
When a user gets in touch with another doctor/nurse through WhatsApp directly from doctor connect. WhatsApp opens up with a preset message in the text field. 

![image](https://github.com/coronasafe/care_fe/assets/67050716/a961c2f5-e6ca-4663-8302-58be02a0260c)

The language is too informal in the message and is not appreciated at the hospitals. 

**Describe the solution you'd like**
Edit the message to read as 
"Dr/ms/mr <name of doctor/nurse>

I have a query regarding a patient.

< link to patient file >"

**Describe alternatives you've considered**

**Additional context**

**Comment by vishisht-dubey** [comment]
hey @aparnacoronasafe  can i work on this?? please assign this to me

**Comment by saloni0419** [comment]
@aparnacoronasafe please assign me this issue

**Comment by vishisht-dubey** [comment]
Hey @aparnacoronasafe @rithviknishad i am going through the issue i think this message would be correct **Dear Dr. B,

I trust this message finds you well. I am writing to seek your professional consultation regarding a patient under my care named patient_name. Patient is currently being treated for [disease_name]. I am attaching relevant medical records, test results, and any other important information for your review.
Your insights and recommendations would be highly valued in ensuring the best possible care for Patient. Please let me know a convenient time for you to discuss this case further or if you require any additional information.
patient_details: [patient_details]**

apart from it i waas thinking that see below image
![Screenshot 2024-03-05 222020](https://github.com/coronasafe/care_fe/assets/98794736/fd02d5ca-e13c-4d50-b1d8-e749f5277ec0)
When we click on this whole div it routes to whatsapp, if we only provide routing on whatsapp phone by clicking on the icons only it would be much better as sometimes we by mistake click the whole card, what are your suggestions on this please let me  know......

**Comment by aparnacoronasafe** [comment]
@vishisht-dubey 

The message that you suggested would be great when a Local doctor is trying to reach a doctor at the hub.

However, the Doctor Connect feature allows communication between different stakeholders. For eg:
- Local doctor to hub doctor
- Hub doctor to local doctor
- Hub doctor to the local nurse
- local nurse to the local doctor

So we need a message that holds good in all these above scenarios. A simple message like the one below works well for all.
"Dr/ms/mr <name of doctor/nurse>

I have a query regarding a patient.

< link to patient file >"

Keeping the above scenarios in mind, can you see how to improve the message?

2) The feature to allow WhatsApp routing when the user clicks on the card was introduced after studying user patterns. Doctors generally prefer using communication over WhatsApp. Especially when using CARE on phones, it's very difficult to click precisely on the icon. So allowing users to click anywhere in the card makes it easier. My recommendation is we leave it as is.

**Comment by vishisht-dubey** [comment]
@aparnacoronasafe can i go with this messgae only which you suggested so that we can wrap up with this issue?? "Dr/ms/mr <name of doctor/nurse>
I have a query regarding a patient.
< link to patient file **>""**

**Comment by Thanush19** [comment]
Hey @aparnacoronasafe  , if the issue is not resolved , i can work on this...

**Comment by rithviknishad** [comment]
@Thanush19 https://github.com/coronasafe/care_fe/issues/7372#issuecomment-1987882533

**Comment by thedevildude** [comment]
@rithviknishad if this is not solved, can I work on it?

**Comment by rithviknishad** [comment]
@thedevildude do you want to take this issue up?

**Comment by thedevildude** [comment]
@rithviknishad yes please assign

**Comment by nihal467** [comment]
@thedevildude What is the status of this PR? Since the priority has been escalated to P1, could you push a PR in the next 48 hours for review?

**Comment by thedevildude** [comment]
@nihal467 Yes I will be able to
