### ISSUE TITLE
Add footer with copyright <date> next to logo

### ISSUE THREAD

**Issue by pankaj-2503** [coronasafe/care_fe#7344]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/coronasafe/care_fe/assets/90036864/c89affe2-0b19-4fed-9052-405fa8d8ab89)

**Describe the solution you'd like**
A paragraph may be text next to open health care network logo in footer.
**Describe alternatives you've considered**

**Additional context**

**Comment by pankaj-2503** [comment]
i would like to work on this would you assign me this issue @aparnacoronasafe

**Comment by Shahbaz898414** [comment]
i would like to work on this would you assign me this issue @aparnacoronasafe

**Comment by rithviknishad** [comment]
https://github.com/coronasafe/care_fe/issues/7306#issuecomment-1968997088
