### ISSUE TITLE
Rewording Telemedicine- consultation form

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7349]
**Is your feature request related to a problem? Please describe.**
CARE has the feature to link an individual patient file to a doctor. 

When introduced, this was used to assign patients in home isolation to doctors in the TeleMedicine panel. 

But today, since Telemedicine is not as relevant, the feature is used at large to assign external doctors to patients. 

Eg: supposing CARE is deployed in a general ICU. A Cardiologist is willing to support remotely. Any cardio cases that come to the ICU may to assigned to the doctor for remote monitoring.

**Describe the solution you'd like**
In consultation form (https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/patient/42dd0666-2076-4373-8767-e809fbf4a2c1/consultation) the last question "Is Telemedicine required for the patient?" needs to be reworded to
"Would you like to refer the patient for remote monitoring to an external doctor?"

**Comment by hrit2773** [comment]
@aparnacoronasafe assign this issue to me I will merge a PR after rewording it
