### ISSUE TITLE
"Log Update"- consistency in terminology

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7350]
**Is your feature request related to a problem? Please describe.**
Log update is mentioned as "Daily rounds" and "consultation updates" in various places. 

**Describe the solution you'd like**

- [ ] In patient dashboard (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e) 

<img width="1224" alt="Screenshot 2024-03-06 at 4 52 50 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/3722d968-ba3c-4f9e-8eb2-d6b9405283a0">

- [ ]  In patient dashboard (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e) 

<img width="732" alt="Screenshot 2024-03-06 at 4 54 05 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/e30b8ac4-ce19-43ad-a560-7be4ed7c6601">

<img width="392" alt="Screenshot 2024-03-06 at 4 55 33 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/ff77072d-f969-4851-84a3-807965a7106b">

- [ ] viewing a saved log update (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/daily_rounds/2da792c7-7ff8-4b8f-8e68-1397b7848597)
title shows "consultation update"

- [ ] https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/daily-rounds/6469a83e-470e-4fbb-a8ee-51770a42360e Viewing a saved log update, title shows "Consultation update" and bread crumb shows "Daily rounds"

Change all the above to "Log Update"

**Describe alternatives you've considered**

**Additional context**

**Comment by aparnacoronasafe** [comment]
@nihal467 please check if Log update is mentioned as "Daily Round" or "consultation update" anywhere else and add it to the list above

**Comment by Ayush398** [comment]
I want to take this issue

**Comment by saloni0419** [comment]
@aparnacoronasafe @rithviknishad can you please assign this issue to me

**Comment by nihal467** [comment]
@Ayush398 Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by syedfardeenjeelani** [comment]
@rithviknishad  i have raised a pr for this issue please review it

**Comment by vishwansh01** [comment]
@aparnacoronasafe  @rithviknishad can you assign this issue to me ?

**Comment by yash-learner** [comment]
Can this be assigned to me ?
