### ISSUE TITLE
Replace usage of `axios` with `request` or `fetch`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7352]
Replace usage of `axios` with CARE's data fetching utility [`request`](https://github.com/coronasafe/care_fe/tree/develop/src/Utils/request) or `fetch` in the following files. Skip replacing it in `fireRequest.tsx`.

<img width="300" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/1fe44f03-41c9-468c-ac61-f0700ce14c50">

**Comment by itxsoumya** [comment]
Can I work on this issue??

**Comment by itxsoumya** [comment]
file: `src/Components/Patient/FileUpload.tsx/FileUpload/uploadAudiofile`
```js
const config = {
      headers: {
        "Content-type": newFile?.type,
        "Content-disposition": "inline",
      },
      onUploadProgress: (progressEvent: any) => {
        const percentCompleted = Math.round(
          (progressEvent.loaded * 100) / progressEvent.total
        );
        setUploadPercent(percentCompleted);
      },
    };
```
fetch does not have any `onUploadProgress` handler. It's limited to `axios` . What should I do here?
```js
 axios
      .put(url, newFile, config)
      .then(() => {
        setAudioUploadStarted(false);
        // setUploadSuccess(true);
        setAudioName("");
        fetchData();
        Notification.Success({
          msg: "File Uploaded Successfully",
        });
      })
      .catch(() => {
        setAudioUploadStarted(false);
      });
  };
```

**Comment by rithviknishad** [comment]
You could try XHR https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload

**Comment by Sulochan-khadka** [comment]
hey @rithviknishad would you mind explaining me why to replace axios? Is it not appropriate or something or efficiency related or something else?

**Comment by rithviknishad** [comment]
Hey, yes. So most of the requests are currently made using browser fetch and not axios. And for very minor use cases like file upload, only we are using axios.

Just for these minor use cases adding axios to the bundle size is not ideal. It'd be great if we could reduce the bundle size.
