### ISSUE TITLE
prescription- Log of change

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7354]
**Is your feature request related to a problem? Please describe.**
Currently, the medicine tab in the patient file only shows the list of active and discontinued medications. There is no log of change visible to the users. 

**Describe the solution you'd like**
Below the medicine table, add separate cards for each change made to the prescription.

Follow the design of the investigation tab where table summary is available on top and below user can click and open individual tests updated.

**Comment by saloni0419** [comment]
@aparnacoronasafe can you please assign this issue to me

**Comment by Sulochan-khadka** [comment]
@saloni0419 are you currently working on this? If not, let me know ... And if by any chance you require any help , let me know as well.

**Comment by Sulochan-khadka** [comment]
@aparnacoronasafe may you kindly attach the screenshots so that I can understand better. And also is the issue being worked on?

**Comment by saloni0419** [comment]
@Sulochan-khadka  yes I am working on this issue.

**Comment by rithviknishad** [comment]
@saloni0419 could you specify how you are planning to solve this issue?

**Comment by saloni0419** [comment]
@rithviknishad I am making a new component for Prescription Log and integrate it to all required component.

**Comment by aeswibon** [comment]
@aparnacoronasafe Can you give more context about the issue??
