### ISSUE TITLE
Show a info card in patient list page if filtered by a facility or if the user has access to a single facility only to view the discharged patients of that facility

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7356]
Follow up on #4678

If a patient has access to only one facility or if the patient list page is filtered by a facility, show an info card to take them to the discharged patients list view

<img width="1710" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/6d566c4e-0e55-47ac-a9ba-289543048ba1">

**Comment by Shahbaz898414** [comment]
@rithviknishad plz assign me?

**Comment by rithviknishad** [comment]
I think someone is already assigned to this?
