### ISSUE TITLE
Show proper error message for invalid DOB in patient registration form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7360]
**Describe the bug**

When we input an invalid DOB in the patient registration form and submit the form, an error message "Something went wrong"

**To Reproduce**

1. Go to https://care.coronasafe.in/patient
2. Click on add patient button and create a patient registration form with dob of (Future Date)
3. Submit the form

**Expected behavior**

it should be showing the proper error message 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/7fd7d387-aeab-41f3-9605-7773b4090c8d)

**Comment by saloni0419** [comment]
@nihal467 can you please assign this issue to me

**Comment by Dareenfadel** [comment]
@nihal467 could you please assign it to me?

**Comment by saloni0419** [comment]
@nihal467 I have a question regarding this. There is no option to select the future date in DOB. Can you please guide me on how to generate this error
![image](https://github.com/coronasafe/care_fe/assets/100074110/8e9a9ffd-7eda-4e66-a268-825149747b7a)

**Comment by nihal467** [comment]
@saloni0419 you can type the invalid date

**Comment by saloni0419** [comment]
@nihal467 Okay

**Comment by saloni0419** [comment]
@nihal467 Has someone solved this issue becuase it is already showing this message
![image](https://github.com/coronasafe/care_fe/assets/100074110/01c9ae51-b93b-46d3-bf97-9821ee93d64f)

**Comment by rithviknishad** [comment]
Closing as completed in https://github.com/coronasafe/care_fe/pull/7366
