### ISSUE TITLE
 Cannot read properties of undefined (reading 'length') while changing the dimension

### ISSUE THREAD

**Issue by bishwas-10** [coronasafe/care_fe#7362]
**Describe the bug**
in the camera feed section of patient
When i change the dimension of screen from one viewport to another for eg dimension: responsive to dimension:iphone SE 
its showing me an error of 
TypeError: Cannot read properties of undefined (reading 'length')
 but once i refresh it goes away

**To Reproduce**

1. Go to 'camera feed section of patient'
2. try changing the dimension

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/120932783/98ee7298-e16c-44c6-a376-08b150082185)
![image](https://github.com/coronasafe/care_fe/assets/120932783/fa55b8d3-67c4-4d97-8c49-6d18bfd888a7)

**Comment by r-nikhilkumar** [comment]
@rithviknishad, @bishwas-10, can you please assign this to me?

**Comment by Shahbaz898414** [comment]
@r-nikhilkumar can you please assign this to me?

**Comment by Thanush19** [comment]
hey @rithviknishad , if the issue to be resolved,i can  fix this....

**Comment by r-nikhilkumar** [comment]
@Thanush19 what's your idea to solve this issue?

**Comment by r-nikhilkumar** [comment]
@rithviknishad, can I implement auto-page-refresh whenever viewport changes?

**Comment by rithviknishad** [comment]
Waiting for related PR: https://github.com/coronasafe/care_fe/pull/6223

**Comment by khavinshankar** [comment]
@r-nikhilkumar fork the branch from #6223 and make a pr with the base branch as #6223 

cc: @rithviknishad

**Comment by r-nikhilkumar** [comment]
@khavinshankar , @rithviknishad , Do I have to fork branch "[JahnabDutta:qa-testing](https://github.com/JahnabDutta/care_fe/tree/qa-testing)"  and raise pr to the main branch [coronasafe:develop](https://github.com/coronasafe/care_fe/tree/develop)??? without any changes?? Did I get it right? please guide...!

**Comment by rithviknishad** [comment]
No, You have to branch out from @JahnabDutta 's branch and make a PR to his branch instead of develop.

**Comment by r-nikhilkumar** [comment]
okay, and do I need to make changes anything in the code or just make pr only?

**Comment by khavinshankar** [comment]
@r-nikhilkumar
1. Create a new branch from `"[JahnabDutta:qa-testing](https://github.com/JahnabDutta/care_fe/tree/qa-testing)"`
2. Make necessary changes
3. Create a pull request with base branch as `"[JahnabDutta:qa-testing](https://github.com/JahnabDutta/care_fe/tree/qa-testing)"`
