### ISSUE TITLE
Handle the 0 Input in the Pressure sore and Pain Scale component

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7365]
**Describe the bug**

- [ ] In pressure sore, the weight and height input columns have inconsistent lengths.
![image](https://github.com/coronasafe/care_fe/assets/57055998/249bf7ce-aacd-4f5f-85dc-2a654cee8a39)
- [ ] When we submit input with 0 on pressure sore / pain scale, both are accept empty input

**To Reproduce**

1. Go to the patient consultation page and click on log update.
2. Create a critical care log update then input 0 in the pain scale (Vital Section) 
3. save it and see the error.

similar error to pressure sore as well

**Expected behavior**

- [ ] In pressure sore, the weight and height column should have consistent length
- [ ] When we input 0 in the pain scale and submit it, the input should be skipped.
- [ ] similar behavior should be implemented in the pressure sore  as well

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/9311260d-f335-445b-8a3b-2140f2d519d6)
![image](https://github.com/coronasafe/care_fe/assets/57055998/cd214ae2-d4b0-4439-bc4a-78355e11fc51)

**Comment by vishisht-dubey** [comment]
Hii @nihal467 would you please assign me this issue??

**Comment by Shahbaz898414** [comment]
Hii @nihal467 would you please assign me this issue??

**Comment by r-nikhilkumar** [comment]
@nihal467, I can solve this issue, can you please assign it to me?

**Comment by Shahbaz898414** [comment]
Hii @nihal467 would you please assign me this issue??

**Comment by Sulochan-khadka** [comment]
I am unable to reproduce this issue... @nihal467 may you help me out with this... Since I am unable to reproduce this issue hence I am unable to understand the core issue it holds...

**Comment by rithviknishad** [comment]
@r-nikhilkumar hold until issue is finalized and unblocked

**Comment by r-nikhilkumar** [comment]
@rithviknishad okay

**Comment by Thanush19** [comment]
hey @nihal467 , if the issue is not resolved yet , i can fix this...

**Comment by r-nikhilkumar** [comment]
for width and height consistency:-

![image](https://github.com/coronasafe/care_fe/assets/91010142/0ca63f84-b615-47f6-8602-b5583ea544f0)

![image](https://github.com/coronasafe/care_fe/assets/91010142/37d65007-b73b-4448-88d9-e4fb1084d5a9)
Is it looking cool?

I did this for the painScale 0 issue
![Screenshot 2024-03-12 001604](https://github.com/coronasafe/care_fe/assets/91010142/c899feba-08c2-4714-ad78-ff696636dcf2)

I did this for the PressureSore 0 issue
![Screenshot 2024-03-12 001334](https://github.com/coronasafe/care_fe/assets/91010142/24d330ad-77a4-4335-bfd3-607e8a8d1520)

@rithviknishad, @nihal467, is it okay? Please guide...!
