### ISSUE TITLE
List of users- Limit Access

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7374]
**Is your feature request related to a problem? Please describe.**
Today, all users of CARE can see all the other users of CARE. Exposing details such as last online, years of experience etc is seems to cause unnecessary and unhealthy comparisons between care providers registered in CARE.
 
**Describe the solution you'd like**
For usertypes Staff/Doctor/Nurse/Pharmacist/Volunteer, only expose the following details in the user listing:
- username
- name of user
- Role
- District
- Created by 

**Describe alternatives you've considered**

**Additional context**

**Comment by Dareenfadel** [comment]
@aparnacoronasafe could you assign me ?

**Comment by Thanush19** [comment]
hey @aparnacoronasafe , can i work on this...?

**Comment by Dareenfadel** [comment]
@aparnacoronasafe  just to make sure do you want to hide all other details to have only this shape?
![Screenshot (141)](https://github.com/coronasafe/care_fe/assets/103316419/ab54dbe9-a541-4d16-8039-409cb15ad719)

**Comment by nihal467** [comment]
@Dareenfadel Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by nihal467** [comment]
non-relevant to current develop
