### ISSUE TITLE
Advanced filter (patient list) for active medicine

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7375]
**Is your feature request related to a problem? Please describe.**
It is very useful for users to quickly filter and see how many patients are actively on "morphine" etc. or even medication groups like "antibiotics"

**Describe the solution you'd like**
Below ICD-11 diagnosis based filter, add another field for 
- Active medication
- Active medication Group

@gigincg to approve this

**Comment by gigincg** [comment]
@aparnacoronasafe This seems more like a Dashboard Question, rather than a feature on CARE. Can you clarify if there is a usecase for Nurses/Doctors to be doing this.

**Comment by aparnacoronasafe** [comment]
> @aparnacoronasafe This seems more like a Dashboard Question, rather than a feature on CARE. Can you clarify if there is a usecase for Nurses/Doctors to be doing this.

@gigincg yes. 
This is relevant for nurses and doctors treating the patients. 

The doctors in any ICU may want to do periodic audits of antibiotic use. For which they will add the filter, and then review the medical file of each patient to ensure that the approach to the use of antibiotics is conservative.

For home care (arikey also) the use of medication like morphine is closely supervised. In fact, they maintain a separate register to keep a list of all patients on morphine. With this filter, they won't have to maintain a separate register and can simply draw the list of patients from CARE and audit it.

**Comment by gigincg** [comment]
@aparnacoronasafe If a patient being on antibiotic/morphine is the only use case, we can consider building an automated label/flag for the patient_encounter (currently consultation).

Filtering Patients by Presribed medicines or medicine groups would be a much larger feature

**Comment by athulmanuel** [comment]
This also comes as part of schedule H drugs. Psychiatric medications and all. We can't have it as dash board because we need to know which all patients are on that medication. Flagging is good in bringing focus on the patient on such medications but that alone might not address the need. Same thing happens with patients on immunosuppressants.

**Comment by aparnacoronasafe** [comment]
@gigincg looks like this requirement is not specific to morphine or antibiotics. 

Can we proceed with the filter?

**Comment by gigincg** [comment]
@athulmanuel @aparnacoronasafe 

Flagging seems like a good direction,

Can we make a list of what all criterias should be flagged?

**Comment by nihal467** [comment]
we have removed all filters from the patform
