### ISSUE TITLE
Dosage mandatory for combination medications.

### ISSUE THREAD

**Issue by athulmanuel** [coronasafe/care_fe#7377]
At the moment dosage is mandatory for any prescription but when we add combination medicines, single dosage cannot be written. 

Temporary solution would be add an extra column to write the another dose which should not need to be mandatory
![image](https://github.com/coronasafe/care_fe/assets/64475161/a6d4c12c-34a4-4f16-bbf5-c829c8ef6f98)

**Comment by aparnacoronasafe** [comment]
The patient may need 2 antibiotics. azhitromicin may be once a day for 5 days, cephtriaxon may be twice a day for 7 days

**Comment by nihal467** [comment]
non-relevant to current develop
