### ISSUE TITLE
Pain Scale (0-10)

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7378]
**Is your feature request related to a problem? Please describe.**
https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/daily_rounds/8e4d0791-30d4-4e5d-8ca4-f6e27abb6418/update

Currently the pain scale in CARE is from 0-5.

Change it to 0-10 to allow user to input a more nuanced measure of pain experienced by the patient.

**Comment by rithviknishad** [comment]
@aparnacoronasafe should we also be updating the existing data to scale accordingly?

For example, if old data is 5, should it be updated to 10?

**Comment by shivankacker** [comment]
https://github.com/coronasafe/care_fe/assets/23238460/a3a9ae63-e88c-4474-b555-bfb2e48c7b24

Pain below 2 is being shown in red, then green, then once again red after 5. @aparnacoronasafe can you also tell if this coloring should be changed?

Ill take up the issue because I am already working on the preview UI for this

**Comment by r-nikhilkumar** [comment]
@skks1212, @rithviknishad can you please assign it to me?

**Comment by leftover19** [comment]
The slider corresponds to pain. I have few suggestions to make.
1. Instead of Low, Normal and High labels, we can change it to Normal, Mild and High.
2. In that regard, Color of Low can be Green, Mild can be Yellow, and High ( or severe) can be Red.
3. 0-2 Normal    3-6 Mild    7 - 10 High ( or severe )
If this is acceptable, I can raise a PR.
Let me know if there's any issue

**Comment by aparnacoronasafe** [comment]
Great suggestions guys!

@rithviknishad yes, the existing entries needs to be adjusted against scale of 0-10. So previously entered "2" will become 4.

@leftover19 Good suggestion. However, one change I want to suggest is to have description of pain as "Low, mild and high". "Normal" in the context of pain is not logical. 

0-3- Low (Green)
3-7- Mild (Yellow)
8-10- High (Red)

@skks1212 Please go ahead with the above.

**Comment by leftover19** [comment]
[Solution.mp4](https://github.com/coronasafe/care_fe/assets/113136731/1d8b4bed-b70b-4caa-90d7-36c8c5b6f425)
I have raised a PR for the same. Please review. Thanks

**Comment by rithviknishad** [comment]
@leftover19 needs changes to be made in the backend for:

> the existing entries needs to be adjusted against scale of 0-10. So previously entered "2" will become 4.

**Comment by leftover19** [comment]
> @leftover19 needs changes to be made in the backend for  existing entries.

Can you please guide how?
Do I need to raise PR in [Backend](https://github.com/coronasafe/care) repository?
or what exactly do I need to do here?

**Comment by rithviknishad** [comment]
Yup, you need to create a custom migration to migrate existing data and raise a PR in that repository.

**Comment by shivankacker** [comment]
@leftover19 thank you for your inputs, but I would recommend having a look at the issue assignees and history before assigning an issue to yourself and raising a PR. Now there will be a duplicate PRs for this issue🙂

Keep this in mind from next time!

**Comment by leftover19** [comment]
> @leftover19 thank you for your inputs, but I would recommend having a look at the issue assignees and history before assigning an issue to yourself and raising a PR. Now there will be a duplicate PRs for this issue🙂
> 
> Keep this in mind from next time!

I wasn't able to completely close this issue. Feel free to do the backend part.
