### ISSUE TITLE
Inline view of options missing for `AutocompleteMultiSelectFormField`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7382]
- Follow up of #7287

**Describe the bug**
#7287 has introduced support for an inline view of selected options for "MultiSelectFormField". However, the same is not present for `AutocompleteMultiSelectFormField` and hence makes the UI inconsistent.

**To Reproduce**

1. Go to a place where `AutocompleteMultiSelectFormField` is used (for example Log Lab Results page)

**Expected behavior**
The UI should be similar to the inline view that `MultiSelectFormField` provides.

**Screenshots**

Current:
<img width="457" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/f555259f-a6b7-4479-a7ce-2ce92f89b181">

Expected:
<img width="847" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/02e5bed2-3587-4f6c-a473-58d8e18c8208">

**Comment by Shahbaz898414** [comment]
@rithviknishad plz assign me?

**Comment by Sulochan-khadka** [comment]
Is this issue still in progress? @rithviknishad . 
@Shahbaz898414 in case you are stuck somewhere, let me know where can I help you fix this issue.

**Comment by thedevildude** [comment]
@rithviknishad I'd like to work on it if it's still open

**Comment by Sulochan-khadka** [comment]
Dear @Shahbaz898414 , kindly do not halt the solution to this issue. If you are stuck somewhere, let me know if I can help. Also if you want , I can give you the idea or rather the initial approach to solve this issue.

**Comment by Shahbaz898414** [comment]
> Dear @Shahbaz898414 , kindly do not halt the solution to this issue. If you are stuck somewhere, let me know if I can help. Also if you want , I can give you the idea or rather the initial approach to solve this issue.

I apologize for the delay. Please grant me some additional time to work on this.

**Comment by Sulochan-khadka** [comment]
> > Dear @Shahbaz898414 , kindly do not halt the solution to this issue. If you are stuck somewhere, let me know if I can help. Also if you want , I can give you the idea or rather the initial approach to solve this issue.
> 
> I apologize for the delay. Please grant me some additional time to work on this.

Sure... No issues . Just let me know if you get stuck somewhere.

**Comment by Shahbaz898414** [comment]
> > > Dear @Shahbaz898414 , kindly do not halt the solution to this issue. If you are stuck somewhere, let me know if I can help. Also if you want , I can give you the idea or rather the initial approach to solve this issue.
> > 
> > 
> > I apologize for the delay. Please grant me some additional time to work on this.
> 
> Sure... No issues . Just let me know if you get stuck somewhere.

bro can you provide your linkedin plz ?

**Comment by ankitmrj** [comment]
@rithviknishad sir if issue is still not resolved, can I work on it?

**Comment by Sulochan-khadka** [comment]
> > > > Dear @Shahbaz898414 , kindly do not halt the solution to this issue. If you are stuck somewhere, let me know if I can help. Also if you want , I can give you the idea or rather the initial approach to solve this issue.
> > > 
> > > 
> > > I apologize for the delay. Please grant me some additional time to work on this.
> > 
> > 
> > Sure... No issues . Just let me know if you get stuck somewhere.
> 
> bro can you provide your linkedin plz ?

sure... www.linkedin.com/in/sulochan-khadka here you go...

**Comment by Sulochan-khadka** [comment]
@rithviknishad this has been solved by probably two ways. Since Combobox.input does not explicitly support this type of styling , 2 ways seemed to me to get it solved. The easiest way to get this solved was to use any pre-worked feature / library (increasing dependencies), while the other way round was to create from scratch, by working on the stylings , modifying some, and then achieving the required. Do let me know which one to push. I prefer the latter one since combobox consistency will be preserved along with no increase in dependency.

**Comment by Utkarsh-Anandani** [comment]
Is the issue still open

**Comment by rithviknishad** [comment]
Closing as we are switching to use shadcn's components
