### ISSUE TITLE
Incorrect representation of Patient Age

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7383]
**Describe the bug**
Incorrect representation of Age in Patient Home

**Issues Identified**
- [x] DB has 3 fields: `age`, `year_of_birth`, `date_of_birth`. 
- [x] Age calculation is not using `timezone.now()` in the model save method.
- [ ] Possible issue with `formatAge` utility method in FE. cc: @Ashesh3 

<img width="731" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/3c025f17-6a14-4722-82a3-e6caa41d78bb">

### Action Items in Backend
- [x] Drop field `age` from patient registration in favour of `year_of_birth`
- [x] Add serializer field: `age_in_days`
- [x] Age should be the number of days between (date of birth/year of birth) and (date of death/today).
- [x] Filters to be based on `year_of_birth` instead of `age`.

### Action Items in Front-end

- [ ] Support for collecting year of birth alone as an alternative to date of birth.
- [ ] Update filters to be based on year of birth instead of age.

**Screenshots**
<img width="372" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/d4763b3d-9f27-46a8-8928-f1d21e7d31a5">

cc: @nihal467 @sainak

**Comment by Ashesh3** [comment]
Interesting, could you add the link of the patient which is being shown in the attached screenshot?

**Comment by rithviknishad** [comment]
@Ashesh3 from production... That's why hid most of the irrelevant details. @nihal467 has tested in staging, but unable to reproduce.

**Comment by manasvi-gaur** [comment]
@rithviknishad, can you please assign this to me?

**Comment by rash-27** [comment]
I would like to work on this issue

**Comment by dwip708** [comment]
Hi, can I work on this issue ?  @rithviknishad 
I am interested to work on this.
