### ISSUE TITLE
UI discrepancies in the file upload page

### ISSUE THREAD

**Issue by AshrafMd-1** [coronasafe/care_fe#7384]
**Describe the bug**
There are a few small UI discrepancies in the file upload page 

[ ] When clicked on the record button it doesn't have responsiveness and extends outside
[ ] The `Archived_by` text is incorrect 

**To Reproduce**

1. Go to Patients
2. Click on a patient
3. CLick on file upload 

**Expected behavior**
The UI Changes must be fixed

**Screenshots**

1. 
![image](https://github.com/coronasafe/care_fe/assets/98876115/6bcad64a-77d5-4c29-9ecf-a0e7ffd54c10)

---

2. 
![image](https://github.com/coronasafe/care_fe/assets/98876115/e29c42a3-8da0-4366-a7f8-48bb5bdbf9d8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AshrafMd-1** [comment]
@rithviknishad can you assign this issue to me.

**Comment by manasvi-gaur** [comment]
@rithviknishad, can you please assign this to me?
