### ISSUE TITLE
[Enhancement] Ventilator Parameters Input - Validate Consultation Bed for Linked Ventilator Asset

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#7397]
## Summary

When users enter Ventilator Parameters for a patient, the system should verify whether the patient's current `consultation_bed` record has a linked Ventilator Asset. If no linked asset is found, the system should prompt the user with a dialog to link a Ventilator being used and capture the time the patient was put on the Ventilator.

## Motivation

This enhancement is crucial for ensuring the integrity of clinical data and for operational efficiency. It prevents the oversight of linking ventilator assets to patients, which is essential for tracking the use of critical equipment and for clinical audits. It also enhances patient safety by ensuring that ventilator use is accurately documented and linked to the patient's record.

## Detailed Description

- When a user saves Ventilator Parameters in the system, initiate a check to confirm if the patient's current `consultation_bed` record has an associated Ventilator Asset.
- If no Ventilator Asset is linked, display a dialog box prompting the user to:
   - Select a Ventilator Asset from a list of available ventilators.
   - Specify the time the patient was put on the ventilator. This time should be logged for accurate medical history and asset tracking.
- Once the user links a Ventilator Asset and specifies the time, the system should create the updated `consultation_bed` record accordingly. 
- Provide appropriate error messages if the linking process fails or if no available Ventilator Assets exist.

## Alternatives Considered

N/A - This specific enhancement addresses a critical workflow gap and improves both clinical data integrity and patient safety. Other alternatives may not provide a direct solution to the issue of unlinked ventilator assets.

## Additional Context

This enhancement is proposed to streamline clinical workflows and ensure that critical equipment usage is accurately recorded against patient records. It not only aids in clinical decision-making but also in inventory management of life-saving equipment.

**Comment by manasvi-gaur** [comment]
@gigincg @rithviknishad can you please assign this issue to me ?

**Comment by r-nikhilkumar** [comment]
@gigincg, @rithviknishad, can you please assign this issue to me?

**Comment by manasvi-gaur** [comment]
@gigincg Where a user saves Ventilator Parameters in the system, where do I need to make changes?

**Comment by rithviknishad** [comment]
@manasvi-gaur 

1. Ventilators are linked to the patient along with the bed through the Switch Bed / Assign Bed Popup.

https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e
<img width="3008" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/a26d8689-4850-406e-9f52-876644c98193">

---------

2. Users can input Ventilator Parameters by creating a log update with round type set to "Critical Care" and by entering the "Respiratory Support" tab

<img width="3008" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/0d2f7f28-ab3a-4ec4-bf07-151bcb05662f">

<img width="3008" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/71173041-684d-4db3-8f19-b27b696c1802">

<img width="3008" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/e3b747ef-ea86-4bf3-96d7-dfc436544788">

---------

3. These information are shown in the "Ventilation" tab of the patient's consultation dashboard

<img width="3008" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/48fbe667-9193-4ead-97b2-336e20e20d09">

**Comment by manasvi-gaur** [comment]
@rithviknishad, I mistakenly unassigned myself please assign it to me, I almost solved this issue, I just had to make a confirmation and create pull request, could you please re-assign me

**Comment by rithviknishad** [comment]
@manasvi-gaur I was able to replicate the issue.

If we submit by editing only the following fields shown in the screenshot, we are able to submit the form without linking a ventilator.

It does works only for changes in fields under the Respiratory Support subtitle. 

<img width="758" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/e60c533d-3e10-45c8-a65d-e99cd38801f4">
