### ISSUE TITLE
Modify the Error in Consultation form to be self explanatory 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7410]
**Describe the bug**

- [ ] When we create multiple patient consultations with same IP number, it throws an "Non Fields Errors - Patient number mustbe unique within the facility" 

**To Reproduce**

1. Create consultation for multiple patient with same IP number
2. See error

**Expected behavior**

- [ ] error message should be self explanatory something like consultation with this IP/OP number already exists; it should be a unique value.

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/21f11aa4-03c4-44dd-b7de-0174bbde093b)

**Comment by Dareenfadel** [comment]
@nihal467 could you assign it to me?

**Comment by hrit2773** [comment]
@nihal467 I would like to work on this can you please assign me

**Comment by kumar11jr** [comment]
Hii @nihal467 can you assign me this issue

**Comment by nihal467** [comment]
![image](https://github.com/coronasafe/care_fe/assets/57055998/d3fc3433-8f36-491c-b5e6-c0f2df23f5f5)

- [ ] when we input duplicate OP number , the error thrown is "something went wrong" @rithviknishad

**Comment by hrit2773** [comment]
@nihal467 I tried to create 2 patient consultations with same IP number but they were created successfully. I did not encounter any error

**Comment by rithviknishad** [comment]
@hrit2773 it needs to be in the same facility too.
