### ISSUE TITLE
Feature to upload consent file per encounter

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7416]
**Is your feature request related to a problem? Please describe.**
Hospitals must maintain records of the consent received from patients. Such consent must be taken on paper and uploded to CARE.

**Describe the solution you'd like**
Add a section in the consultation form, below the treatment plan called "Consent records"

- [ ] Add field for "Consent Type"- with dropdown: 
1- Consent for admission
2- Patient Code status
3- Consent for procedure
4- High risk consent
5- Others

Only when "Patient code status" is selected, an additional field for "Patient code status" with dropdown options as below appear. 
Do Not Hospitalise (DNH)
Do Not Resuscitate (DNR)
Comfort Care Only
Active treatment (Default)

The user must be able to select an option from the Consent Type dropdown and upload a file and add a text title to the file (the existing file upload component may be used).

For the same consent type, multiple files may be uploaded.

Below this, a list of already uploaded files, arranged in sections for each consent type must be available.

- [ ] On the patient dashboard, (https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/ba1e2de6-6ded-456c-836a-de25fcc1f4c7/consultation/c50a8ccf-ee9b-42ec-beb8-b5f62e91cb12) add a section at the bottom of "Overview" for "Consent Record" and show the uploaded consent records. 

NOTE: the minimum urgent requirement for now is to have the ability to upload "Consent for admission" alone. That may be taken up first and then improved with other types of consent later.

**Comment by aparnacoronasafe** [comment]
Expected to go live with minimum requirement in 2 weeks (by 29th Mar)

**Comment by Anish-Parkhi** [comment]
Hello @aparnacoronasafe I would like to contribute towards this issue

**Comment by nihal467** [comment]
@skks1212 any update on the PR

**Comment by shivankacker** [comment]
@aparnacoronasafe So at once, only one type of consent can be selected and files for the selected consent, right?
Or do we want the option to multiselect the consent types, and upload files for each?

**Comment by aparnacoronasafe** [comment]
Multi-select, if possible would be a nice enhancement to have. 

However it must be very clear for the user, which consent to be uploaded where.
