### ISSUE TITLE
 Modification of padding  in ScrollingComponent for Improved Mobile Display in pages like resource board

### ISSUE THREAD

**Issue by soumya-maheshwari** [coronasafe/care_fe#7427]
**Describe the bug**
Adjustment of padding in ScrollingComponent from px-4 to px-0 to enhance card visibility on mobile screens, particularly evident in pages like the shifting board page and resouces board page.

**To Reproduce**

1. Go to https://care.ohc.network/
2. Click on Resources tab in the left sidebar
3. Scroll down to the cards.

**Expected behavior**
 The ScrollingComponent should display cards with improved visibility on mobile screens. The change from px-4 to px-0 padding should ensure that cards are appropriately sized and readable, enhancing the overall user experience on smaller devices.

**Screenshots**

**Shifting board screen**

![image](https://github.com/coronasafe/care_fe/assets/104725768/6e7e7a1b-6f90-4fd8-8fc5-127a1731e607)

**Resources board screen**

![image](https://github.com/coronasafe/care_fe/assets/104725768/eb50df4e-fe0a-4e6d-a49a-938b75c8d7ba)

**Desktop**

- OS: Windows 11
- Browser: Chrome

**Comment by NutNick31** [comment]
Can you please assign this issue to me?

**Comment by soumya-maheshwari** [comment]
Hi @sainak ,
I've created a pull request (#7428) to address the issue (#7427).
Please review the changes and provide any feedback or suggestions. Let me know if there's anything else I can do to help move this forward.
