### ISSUE TITLE
Modify the E-chart preview to have consistency with user input

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7429]
**Describe the bug**

We input the normal log update data with a maximum of one decimal point and in some cases with only an integer value, but all our preview charts have two decimal points **{DISCUSSION ISSUE FOR CORE TEAM}**

**To Reproduce**

### Things to discuss

- [ ] Decimal places
- [ ] Cypress test for data from canvas render

**Expected behavior**

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/57055998/79f6f111-c86c-418f-aec4-e34db26fd8a6)
![image](https://github.com/coronasafe/care_fe/assets/57055998/749f318d-0344-4fc0-8929-8eac97d43153)

**Comment by vishisht-dubey** [comment]
Hiii @nihal467 would you please assign me this issue

**Comment by Thanush19** [comment]
hey @nihal467 , i can resolve this issue..

**Comment by gigincg** [comment]
@vishisht-dubey @Thanush19 

Blocked Discussion Issues are not assignable until more depth is added to it. The labels will be updated at that point

**Comment by gigincg** [comment]
@nihal467 

1. Regarding showing decimal data, we can round to the precision, only if precision data exists. 
For eg: 
- 150.00 will be shown as 150. 
- 130.52 will be shown as 130.52. 
- 130.524 will be shown as 130.52
- 130.5 will be shown as 130.50

2. For Cypress Tests, we can add an additional `span` with `className="sr-only"`
Ref: https://tailwindcss.com/docs/screen-readers#screen-reader-only-elements

**Comment by gigincg** [comment]
@vishisht-dubey @Thanush19

Either of you wanna take this up?

**Comment by hrit2773** [comment]
@gigincg I want to take this up can you assign this to me

**Comment by gigincg** [comment]
> @gigincg I want to take this up can you assign this to me 

@hrit2773 I've assigned the issue to you. Please share an ETA on this, as an acknowledgement and create a Draft PR as soon as you start working on it.

**Comment by hrit2773** [comment]
@gigincg ya sure I'll start working on it tmrw morning onwards

**Comment by vishisht-dubey** [comment]
Hii @hrit2773 if you don't have any problem can I do it? As I would raise the pr today.

**Comment by hrit2773** [comment]
@vishisht-dubey can you share an ETA on this

**Comment by vishisht-dubey** [comment]
@hrit2773  ETA means ??
