### ISSUE TITLE
Overflow of the text in the UI button Advanced Filters

### ISSUE THREAD

**Issue by NutNick31** [coronasafe/care_fe#7433]
**Describe the bug**
The title "Advanced Filters" in the Patients table UI is overflowing and clipping off text. This creates a visual inconsistency and makes it difficult for users to understand the functionality of the section.

**To Reproduce**

1. Go to https://care.coronasafe.in/patients
2. Click on Patients Tab
3. Scroll down to Advanced Filter Button

**Expected behavior**
The entire text should be displayed clearly and completely within the button, regardless of screen size. This ensures consistent UI presentation across different devices.

**Screenshots**
![Screenshot from 2024-03-18 21-15-15](https://github.com/coronasafe/care_fe/assets/81872302/bf617195-5139-46f2-8dca-e7419156492b)

**Desktop:**

- OS: Ubuntu
- Browser: chrome

**Comment by rithviknishad** [comment]
I'm not aware of any mobile manufacturer manufacturing phones with such a display. Closing as not planned.

<img width="495" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/58b7e216-389f-4f6a-9885-4d58b61c6053">

**Comment by rithviknishad** [comment]
Feel free to take up more valuable issues here: https://github.com/coronasafe/care_fe/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+no%3Aassignee 😄
