### ISSUE TITLE
Add option to mark notification as unread

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#7459]
**Describe the bug**
Currently, the user has the option to mark a notification as read but no option to mark it as unread.

**To Reproduce**

1. Go to https://care.ohc.network/facility
2. Click on `Notifications`
3. See error

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/70687348/a37bcb28-eb6e-4c65-9803-977f59fe0889)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pranshu1902** [comment]
@rithviknishad @khavinshankar what are your thoughts on this?

**Comment by shamun-khatri** [comment]
I think It may be useful many other products have this feature to unread. but I want to know from others too.  If others also want this then I want to work on this issue.

**Comment by shamun-khatri** [comment]
Hey, I want to work on this issue @rithviknishad please assign it to me.

**Comment by hrit2773** [comment]
@Pranshu1902 I want to work on this can you assign me @rithviknishad

**Comment by vishisht-dubey** [comment]
Hey @rithviknishad i want to work on this can you please assign?

**Comment by NutNick31** [comment]
Hello @Pranshu1902 , I suggest that instead of adding a feature of marking the notification as unread, I think we should add a feature of star marking a notification or pinning that notification. In this way users can differentiate between important and unimportant notifications.
