### ISSUE TITLE
Prescriptions: Scroll to see more overlay being shown even if no more prescriptions to be shown

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7464]
**Describe the bug**
Prescriptions: Scroll to see more overlay being shown even if no more prescriptions to be shown

**To Reproduce**

1. Go to a patient with prescriptions

**Expected behavior**
"Scroll to see more" overlay should show only when the table is scrollable and has not reached the end of the scroll.

**Screenshots**
<img width="1693" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/84be962e-444d-4e28-b4da-cc1d32b9401b">

**Comment by AshrafMd-1** [comment]
@rithviknishad I want to work on this issue can you assign me this
