### ISSUE TITLE
"Undefined" is not a valid UUID : response while updating patient notes.

### ISSUE THREAD

**Issue by Sulochan-khadka** [coronasafe/care_fe#7473]
**Describe the bug**
When trying to update the patient notes, on changing the note and updating, it gives an error of "Undefined" is not a valid UUID.

**To Reproduce**

1. Go to Notifications tab
2. Click on "open" on any of the notes
3. Try to update the note.

**Expected behavior**
The note should be updated with the updated text.

**Screenshots/Video**
https://github.com/coronasafe/care_fe/assets/122200551/8ead9411-8cb4-4366-82bc-c6656d97b044

**Comment by Sulochan-khadka** [comment]
@nihal467, @rithviknishad  is this issue not addressed till now? if so, may you assign this to me to work?

**Comment by Sulochan-khadka** [comment]
@rithviknishad did you solve this issue in your PR or shall I raise one?

**Comment by rithviknishad** [comment]
Solved in #7469, it was a minor type error so had to fix it in that PR itself.
Feel free to checkout other open issues.
