### ISSUE TITLE
Facilities added but not displayed in Users.

### ISSUE THREAD

**Issue by Sulochan-khadka** [coronasafe/care_fe#7474]
**Describe the bug**
On linking a new facility to user, it is not displayed though it has been added(probably since on adding again, it shows already added).

**To Reproduce**

1. Go to Facilites tab
2. Click on View facility on any facility
3. select View users from the manage facility dropdown
4. Click on "Click here to show "
5. add new facility
6. It is not displayed but on again adding , it shows error "User already has permission to this facility ".

**Expected behavior**
The attached facility should be displayed.

**Screenshots/Video**

https://github.com/coronasafe/care_fe/assets/122200551/d9c4f1ba-54b5-48b0-8cda-4078213d018c

**Comment by Sulochan-khadka** [comment]
Kindly ignore the above video since the OBS freezed in-between. I will be uploading the video here.

**Comment by Sulochan-khadka** [comment]
https://github.com/coronasafe/care_fe/assets/122200551/418971b4-c8f1-451a-b0ef-5e2bff8295a2

**Comment by Sulochan-khadka** [comment]
@nihal467 @rithviknishad Kindly assign this issue to me to start working on it.

**Comment by rithviknishad** [comment]
@Sulochan-khadka we can instead use the Linked Facilities slide over here like how we have in the users list page.

**Comment by Sulochan-khadka** [comment]
@rithviknishad I have raised a PR for this. Kindly review it and merge! Also let me know if there are improvements needed.

**Comment by Sulochan-khadka** [comment]
Pr number is #7494

**Comment by Sulochan-khadka** [comment]
Acknowledged
