### ISSUE TITLE
Add "needs testing" label if contributor comments "ready for testing"

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7479]
## Motivation
Since we have a growing number of contributions and since open-source contributors do not have triage permissions, we might miss to add "needs testing" label and the PR might become stale without being noticed.

## Solution

- [ ] Add an auto label workflow for adding the "needs testing" label.

The needs testing label can be added if either of the following conditions are met:

- User comments "ready for testing" and the PR is not a draft PR
- PR opened and is not a draft PR
- PR changed from draft status to open.

- [ ] When "changes required" label is added by a user, add a comment in the PR to remind the contributor on how to add the "needs testing" label by commenting "ready for testing".

Feel free to suggest alternatives or add on to this.

**Comment by saloni0419** [comment]
@rithviknishad can you please assign this issue to me
