### ISSUE TITLE
Linked Skill Issue

### ISSUE THREAD

**Issue by Sulochan-khadka** [coronasafe/care_fe#7497]
**Describe the bug**
Some kind of Inconsistent Issue as it appears to me that in some cases, on adding skill, gives error whereas in some cases, unlinking skill gives no error but linking skill throws one, and also in some cases, it works perfectly fine...

**To Reproduce**

1. Go to Users tab
2. Click on Linked skill
3. Add a skill from the dropdown

**Expected behavior**
Linking and unlinking should be allowed.

**Screenshots/video**

https://github.com/coronasafe/care_fe/assets/122200551/fad12546-9ae1-4876-b96e-a5104d44930b

@rithviknishad @nihal467 let me know if this is even a bug or just some sort of testing.

**Comment by Sulochan-khadka** [comment]
@rithviknishad if this issue hasn't been addressed yet, let me work on it.

**Comment by Sulochan-khadka** [comment]
@rithviknishad if this issue hasn't been addressed yet, let me know.

**Comment by shivankacker** [comment]
Looks like this issue has been fixed, feel free to reopen if you encounter this again.
