### ISSUE TITLE
Refactoring the access of a district admin in respect to list of users

### ISSUE THREAD

**Issue by kabirrajsingh** [coronasafe/care_fe#7500]
#needs-discussion

Currently a district admin has access to view all the users from the users tab.
But he/she cannot perform any function on it if the user is not from his own district, basically cannot utilize the Linked facility, Linked Skills and set weekly average hours button. When he tries to perform such an operation, it gives an error from the backend but this issue could be handled better.
Suggested changes-
1. Option 1: Does a district admin need to have even view access to users from other districts? We can restrict the view access to only users within the own district.
2. Option 2: If the view access is provided, the users can be segregrated by adding 2 seperate tabs (My district, Other districts). The users on these tabs could be handled seperately. The action buttons would only be visible for users under my district tab.
3. Option 3: Do not make seperate tabs and just hide the action buttons for users outside the district.

Solving this issue would also solve #7497 .
This could also be extended to solve #7374 
![Screenshot_15](https://github.com/coronasafe/care_fe/assets/24957846/7d39f035-7724-45c2-aba6-0a94814dc081)

@coronasafe/code-reviewers

**Comment by Sulochan-khadka** [comment]
Actually I as well encountered the issue, but am not sure whether this is an actual issue or some role-based feature.
It would be better if @rithviknishad confirm this...

**Comment by Sulochan-khadka** [comment]
@kabirrajsingh if your PR solves multiple issues, then I guess you should go ahead with my issue as well... But first get the conformation .

**Comment by kabirrajsingh** [comment]
@Sulochan-khadka it is actually a restriction on the basis of District, I raised the issue in the last standup. A district admin can only use the action buttons in his own district, which in this case is Thiruvananthapuram. When you try to use it on user from another district like Ernakulam, it would throw an error. We can work on this together but the issue needs discussion first as to which approach would be the best to solve it.

**Comment by Sulochan-khadka** [comment]
@kabirrajsingh Yeah I guess this issue will be addressed once it comes to the attention of the contributors.

**Comment by nihal467** [comment]
the issue has been already handled in the https://github.com/coronasafe/care/pull/1742
