### ISSUE TITLE
Replace `react-qr-scanner` package

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7505]
**Reason:** 
- Package no longer maintained (https://www.npmjs.com/package/react-qr-scanner)
- Has missing peer dependencies

**Suggested alternatives:**
- https://www.npmjs.com/package/reactjs-qr-code-reader

**Comment by thedevildude** [comment]
I'd like to work on it. Can you please assign?

**Comment by kumar11jr** [comment]
hey @thedevildude if you are not working on this issue I will take it up because it has been already 2 days.

**Comment by thedevildude** [comment]
@rithviknishad The suggested package produces this error 
![image](https://github.com/coronasafe/care_fe/assets/63492939/1c1c821f-5109-461c-b267-7771c89044cc)

Switching to bundler breaks other modules

**Comment by rithviknishad** [comment]
@thedevildude it is because there are no type definitions for that package... You can use any other package that has types..

**Comment by rithviknishad** [comment]
Check this out: https://www.npmjs.com/package/react-qr-code
