### ISSUE TITLE
Support for Home Facility filter in Users list

### ISSUE THREAD

**Issue by NNSiri** [coronasafe/care_fe#7510]
**Is your feature request related to a problem? Please describe.**
On clicking to Users>Advanced Filters i cant select specific Taluka

**Describe the solution you'd like**
Since we have deployed in Taluka Hospitals in Karnataka, and  we have 2 hospitals in many districts, we may scale it up to many more taluka hospitals. Hence we would require the advance filter option to filter out the taluka as well.
**Describe alternatives you've considered**

**Comment by ankitmrj** [comment]
Hi @rithviknishad @NNSiri 
Feature Request: Enhanced Filtering for Users

Problem Statement: Currently, in the Users section under Advanced Filters, there is no option to select specific Talukas, which limits our ability to efficiently manage and scale operations across Taluka Hospitals in Karnataka.

Proposed Solution: We request the implementation of a feature that allows users to filter based on Taluka. This would greatly benefit our organization as we expand our presence and operations within Karnataka.

Benefits:

Efficiency: Enables us to quickly identify and manage users associated with specific Talukas.
Scalability: Supports our growth strategy by facilitating management across multiple Taluka Hospitals.
Accuracy: Ensures precise user targeting and management within designated geographic areas.
Alternative Consideration: While we await this feature implementation, a temporary workaround could involve manually sorting and categorizing users based on Taluka information provided in their profiles. However, this manual approach is time-consuming and prone to errors, highlighting the necessity of an automated filtering feature.

Thank you for considering my feature request. I believe that this enhancement will significantly improve our workflow and contribute to the overall effectiveness of the platform.

**Comment by gigincg** [comment]
@NNSiri The hierarchy in CARE are State, District, Local Body & Wards, And for users we have only State, District & Local Body. Local Body is an optional field when creating Users, therefore a Local Body filter for Users may not work as you would expect.

Can you tell us what would be the purpose of looking at Users from a certain Taluka? If the purpose is to filter users by a Home Facility, that can be implemented in a better way.

**Comment by NNSiri** [comment]
@gigincg yes the purpose it to filter the users by Home facility. so if that is deployed, then that should be good.

**Comment by NNSiri** [comment]
Any update on this ? @gigincg

**Comment by rithviknishad** [comment]
It was discussed to add support for filtering by home facility users.

**Comment by rithviknishad** [comment]
Backend changes not required as backend already supports filtering by home facility
