### ISSUE TITLE
In the Patient registration page: Occupation dropdown is not suffecient.

### ISSUE THREAD

**Issue by NNSiri** [coronasafe/care_fe#7516]
**Is your feature request related to a problem? Please describe.**
In the Patient registration page: Occupation dropdown is not sufficient. it shows only Student, Businessman, Healthcare Worker, Healthcare lab Worker, Animal Handler and others!!!

**Describe the solution you'd like**
It should include all occupations.
I found this on GitHub, it might be helpful 

https://gist.github.com/ag14spirit/fbf877576c9d6b78899e3ad02fe92b50#file-occupation-dropdown-html

Atleast the below options are desirable.

- Healthcare Practitioners
- Paramedics
- Business, Executive, Management, and Financial Occupations
- Engineer
- Teacher 
- Other Professional Occupations:
- Office and Administrative Support Occupations:
- Chef or Head Cook
- Protective Service (e.g., Fire Fighting, Police Officer, Correctional Officer)
- Cook or Food Preparation Worker
- Food and Beverage Serving Worker (e.g., Bartender, Waiter, Waitress)
- Building and Grounds Cleaning and Maintenance
- Personal Care and Service (e.g., Hairdresser, Flight Attendant, Concierge)
- Sales Supervisor, Retail Sales
- Retail Sales Worker
- Insurance Sales Agent
- Sales Representative
- Real Estate Sales Agent
- Construction and Extraction (e.g., Construction Laborer, Electrician)
- Farming, Fishing, and Forestry
- Installation, Maintenance, and Repair
- Production Occupations
- Other Agriculture, Maintenance, Repair, and Skilled Crafts Occupation
- Aircraft Pilot or Flight Engineer
- Motor Vehicle Operator (e.g., Ambulance, Bus, Taxi, or Truck Driver)
- Other Transportation Occupation
- Military
- Homemaker
- Other Occupation
- Don't Know
- Not Applicable

**Comment by hrit2773** [comment]
@rithviknishad @NNSiri can you assign this issue to me I want to work on this

**Comment by perminder-17** [comment]
Hello @NNSiri , I appreciate the idea of incorporating the extensive range of occupation details you mentioned, as opposed to just a few. However, including such a vast amount of data in the drop-down menu might make our user interface appear cluttered, requiring users to scroll extensively to find their desired occupations. Perhaps we could brainstorm a design solution where users can start typing their occupation, and the system suggests relevant options, similar to the feature we have when adding patient details.
![image](https://github.com/coronasafe/care_fe/assets/127239756/3cd2ec30-e1c8-4a36-96fd-3b4adfccc1ab)

Please let me know what are your thoughts on it?

**Comment by rithviknishad** [comment]
@perminder-17 @hrit2773 

Here is what is required:

- [ ] Expand the occupation choices to include the above-mentioned choices.
- [ ] Switch to using `<AutocompleteFormField />` component instead of `<SelectMenuFormField />` for selecting an Occupation.

**Comment by hrit2773** [comment]
@rithviknishad got it

**Comment by hrit2773** [comment]
@rithviknishad https://github.com/coronasafe/care/pull/2055 this is the backend PR
