### ISSUE TITLE
Optimization :  Using React memo()  for  routes like to avoid unnecssary rerenders for the same page 

### ISSUE THREAD

**Issue by tanpreetjolly** [coronasafe/care_fe#7521]
**Is your feature request related to a problem? Please describe.**. 
The current load time for a patient route is about 3-4 seconds right now which is higher than the standard 0-2 seconds. The same pages are re rendered multiple times for different props.

**Describe the solution you'd like**
We can use React memo() to optimize this re-rendering for highly dynamic pages like the patient routes. This can decrease the load time of a page by 50% and highly improve the user experience

**Comment by rithviknishad** [comment]
@tanpreetjolly could you provide more specific insights in detail?

As for what I see, the patients' list API itself takes ~4 seconds to respond. I don't think using memo would make it 50% better.

<img width="999" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/a068941e-1887-4465-af81-ec5e4c4ef1b9">

**Comment by tanpreetjolly** [comment]
Yeah I ran some test again, the majority time is with the API response and not a rendering issue. Using memo wouldn't enhance it any better. I am hardly getting 50ms faster load time and that too in some case.

**Comment by tanpreetjolly** [comment]
closing the issue
