### ISSUE TITLE
HL7 Vital Monitor error message is clipping out

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7534]
**Describe the bug**

When there is no feed in the HL7 vital monitor, the error message is clipping out

**To Reproduce**

1. Go to any vital monitor asset
2. Click on the configure page
3. See error

**Expected behavior**

the error message should be properly visible in the vital monitor component

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/8cf3d7c7-6295-4ed7-b74d-810257ece969)

**Comment by ab1123** [comment]
I would like to work on this issue. Can you please assign me this issue?? @nihal467

**Comment by Aryanshu919** [comment]
Hi @nihal467 
I've created a pull request (https://github.com/coronasafe/care_fe/pull/7534) to address the issue (https://github.com/coronasafe/care_fe/issues/7550)
Please review the changes and provide any feedback or suggestions. Let me know if there's anything else I can do to help move this forward.
