### ISSUE TITLE
Add highlight for in-use preset in asset configure page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7535]
**Describe the bug**

When we click on a existing preset, and the camera feed is showing that particular feed, the preset is not being showing any highlight 

**To Reproduce**

1. Go to any camera configuration page
2. Click on any existing camera configuration
3. See error

**Expected behavior**

- [ ]  When we click on an existing preset and the camera feed is being shown, the preset should be highlighted.
- [ ] By adding this, an extra advantage is provided to the user, allowing them to know which preset they are modifying using the update preset button.

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/6ec593f0-76f6-4336-9d80-f4605857d366)

**Comment by thedevildude** [comment]
I'd like to work on this issue, it can be fixed with issue #7342 if applicable

**Comment by nihal467** [comment]
@thedevildude Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by UdaySagar-Git** [comment]
@nihal467 can you assign this to me

**Comment by rithviknishad** [comment]
Closing in favour of #7511
