### ISSUE TITLE
Replace "_" in patient registration form for age field

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7536]
**Describe the bug**

the space in the age field of the patient registration form is filled with "_"

**To Reproduce**

1. Go to the patient registration form
2. Click on the field and input the age 
3. See error

**Expected behavior**

replace _ with space in the age field for the Year of birth

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/46799127-5176-4521-b0a0-d7099d12d6c7)

**Comment by Aryanshu919** [comment]
I'd like to work on it. Can you please assign ?

**Comment by ab1123** [comment]
I would like to work on this issue. Can you please assign me this issue?
 @nihal467
