### ISSUE TITLE
Date of Domiciliary Care Commenced is missing in Treatment Summary

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7538]
**Describe the bug**

- [ ] When we generate treatment summary for a domiciliary care patient, the date of commencement is missing in the generated report
![image](https://github.com/coronasafe/care_fe/assets/57055998/9810e0cc-c648-49f4-8ac8-b53aea68eed5)

- [ ] domiciliary care patients, the commenced date is shown as admission on badge in consultation page
![image](https://github.com/coronasafe/care_fe/assets/57055998/015ef733-504e-460b-90e7-d79fe39b2dfb)

**To Reproduce**

1. Go to patients consultation tab of a Domiciliary patient
2. Click on manage patients button and click treatment summary

**Expected behavior**

- [ ] in treatment summary report of domiciliary patients, replace the "date of admission" field with "date of domiciliary care commenced".
- [ ] replace the badge "admission on" with "commenced on"for domiciliary patient

**Comment by AshrafMd-1** [comment]
@nihal467 can you assign me this issue
