### ISSUE TITLE
Add subheading for user type in doctor connect

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7542]
**Describe the bug**

Currently in the all section of doctor connect, the entire user types are scattered 

**To Reproduce**

1. Go to patient consultation page
2. Click on doctor connect
3. See error

**Expected behavior**

- [ ] add a separate heading for each type of user (nurse, doctor, Teleicu Hub) in all section in Doctor Connect 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/6918bfea-7796-49fe-b48d-69f261305f7c)

**Comment by rash-27** [comment]
I would like to work on this
