### ISSUE TITLE
search by typing in symptoms list

### ISSUE THREAD

**Issue by athulmanuel** [coronasafe/care_fe#7543]
at present the symptom list in the consultation is only drop down, could we add search by typing as well?
![Screenshot 2024-04-05 at 7 29 34 AM](https://github.com/coronasafe/care_fe/assets/64475161/9e1f1abf-3ebb-4bf9-b3c2-110025f08947)

**Comment by hrit2773** [comment]
@athulmanuel we can use autoCompleteFormField component to solve this issue

**Comment by hrit2773** [comment]
@rithviknishad @athulmanuel can you assign me
