### ISSUE TITLE
Add support for date of onset selection for each symptom

### ISSUE THREAD

**Issue by athulmanuel** [coronasafe/care_fe#7544]
presently we are only able to add one date of onset, but it might be different for each symptom. this determines the diagnosis, because, it depends on the timeline of presentation of each symptom
![Screenshot 2024-04-05 at 7 42 58 AM](https://github.com/coronasafe/care_fe/assets/64475161/e889bb92-01c0-4f10-910d-036bcb2c3a16)

**Comment by hrit2773** [comment]
@athulmanuel we can make the changes in such a way that user gets a date form field for every symptom and accordingly we can changes in the backend also.

**Comment by hrit2773** [comment]
@rithviknishad @athulmanuel I can do this can you assign me

**Comment by rithviknishad** [comment]
@hrit2773 refer the same issue here too: https://github.com/coronasafe/care_fe/issues/3618
Drop a comment there too, will assign

**Comment by hrit2773** [comment]
@rithviknishad the requirement would be that for every symptom that a user selects there will be a date of onset field visible right. That would be good right. And in the overview section it is showing the symptoms and only one date of onset so i can change it like this 
FEVER from [onset date]
COUGH from [onset date]
SORE THROAT from [onset date]
and so on i this way....just confirm it so that i can work according to the exact requiremments

**Comment by athulmanuel** [comment]
Yes. I exactly.

**Comment by athulmanuel** [comment]
Also I was thinking , we might need a stop date as well. So that we can ensure the symptoms are resolved. Not urgent, but on a the long run, it will give proper data and surety that the symptom is controlled.

**Comment by hrit2773** [comment]
> Also I was thinking , we might need a stop date as well. So that we can ensure the symptoms are resolved. Not urgent, but on a the long run, it will give proper data and surety that the symptom is controlled.

@rithviknishad your thoughts?

**Comment by nihal467** [comment]
similar issue to : https://github.com/coronasafe/care_fe/issues/3618

**Comment by hrit2773** [comment]
@nihal467 maybe discussion is required regarding whether to add multiple other symptoms form fields and multiple date of onset for other symptoms also...plz provide clarity on this.. I'm almost done with the PR I just need clarity on this @rithviknishad
