### ISSUE TITLE
Unexpected Behaviour When Removing Multiple Selected Options

### ISSUE THREAD

**Issue by UdaySagar-Git** [coronasafe/care_fe#7552]
**Describe the bug**
When closing (deleting) multi-selected options, dropdown appear, which is a little annoying and impacts the user experience.

**To Reproduce**

1. Go to the Edit Consultation page.
2. Add multiple options to symptoms.
3. Click on the `x` and observe the behavior.
**Expected behavior**
Dropdown should not open upon removing a selected option

**Screenshots**
[Screencast from 06-04-24 12:10:51 PM IST.webm](https://github.com/coronasafe/care_fe/assets/111575806/292cab7f-03ad-4e39-b3ee-4dc48ddc579a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UdaySagar-Git** [comment]
can you please assign this to me

**Comment by ShreySinha02** [comment]
@UdaySagar-Git I like to address one more issue here that when we select symptom the drop down should automatically close

**Comment by UdaySagar-Git** [comment]
@ShreySinha02 the drop down will automatically close when a single select option is selected (asymptomatic) , and it will remain unclosed when multi select option is selected 

I already made related changes in #7253

**Comment by ShreySinha02** [comment]
@UdaySagar-Git may be bubbling is the cause of this issue
