### ISSUE TITLE
Total Discharge patients Number to be made Visible for all user type

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7570]
Total Discharge Patient Number is evanesce after the reposition the Discharge Patients module. 
There's Need to show the total number of Discharge patient Counts on Clicking "Discharge" in the total Patients list like how it is seen for Live Patients for the purpose understand and analytics for all user Types. 
Since Currently the total counts(numbers) of Discharged patients is only visible for State Admin User type.

![Screenshot 2024-04-08 172442](https://github.com/coronasafe/care_fe/assets/166367729/0e6d0676-82eb-454f-bf5e-7b1ac93a3d79)

**Comment by r-nikhilkumar** [comment]
@gayann-au, @rithviknishad can you please assign it to me?

**Comment by r-nikhilkumar** [comment]
@rithviknishad @gayann-au how can I login as state admin, provide me credentials for that bcz it's not mentioned in readme.md

**Comment by aparnacoronasafe** [comment]
@skks1212 can you ship this ASAP so that its released next week?
