### ISSUE TITLE
Unable to Scan The QR Code in Asset Module 

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7571]
Unable to Scan the QR Codes in the assets Module in Windows 11,Mac,iOS irrespective of any Browsers used. error Messages are popped as soon as the QR Code is scanned and detected. The Snapshot of the Error Message is pasted below

![Screenshot 2024-04-08 173142](https://github.com/coronasafe/care_fe/assets/166367729/b8451006-ef41-40cb-ae71-3806404b6464)

**Comment by AnkurPrabhu** [comment]
@rithviknishad I found the root cause

**Comment by AnkurPrabhu** [comment]
fixing it and raising a pr

**Comment by AnkurPrabhu** [comment]
@rithviknishad  here is the pr, can you tell me how can i test it locally for valid QR codes

**Comment by AnkurPrabhu** [comment]
@khavinshankar @Ashesh3   my changes are to handle invalid qr code 
currently the page starts infinite loading if a wrong QR code is sent 
and notification says something went wrong 

**before** 

<img width="1469" alt="Screenshot 2024-04-16 at 12 22 17 AM" src="https://github.com/coronasafe/care_fe/assets/85862184/f7619b13-da70-4cf2-9543-37c2061afa5a">

**after**
<img width="1436" alt="Screenshot 2024-04-16 at 12 26 04 AM" src="https://github.com/coronasafe/care_fe/assets/85862184/04d2d00b-6aa4-4d03-8159-b245a228fc5f">
