### ISSUE TITLE
Unable to Change the Values using Upward and Downward arrow

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7572]
Unable to Change the Values using Upward and Downward arrows in the Oxygen Capacity tabs in the Update Facility Page.
Here the only values can be entered but can't be updated using the available arrows with respective of all fields.

![image](https://github.com/coronasafe/care_fe/assets/166367729/e0b8a3fd-2c0b-4dd6-869c-5f05c3dc508c)

**Comment by manasvi-gaur** [comment]
@rithviknishad can you please assign this issue to me?

**Comment by nihal467** [comment]
@manasvi-gaur unassigning you from this due to inactivity, feel free to assign this issue if you are still working on it
