### ISSUE TITLE
Camera access feature issue for not availibility of user role StateReadonly 

### ISSUE THREAD

**Issue by Jrl0** [coronasafe/care_fe#7578]
To allow Camera access  for user role "StateReadonly" 
Reason for requiring camera access for this user role
- Higher officials within the health directorate, including directors, commissioners, and the health minister, are designated as "state readonly" users.
- Revoking camera access for these state readonly users may be perceived as offensive since they utilize this feature for facility inspections.
- Such actions could potentially strain our relationship with these officials rather than fostering a positive rapport.

**Comment by aparnacoronasafe** [comment]
Please allow all view access to State Admin (read only) including patient live feed and live monitoring.

**Comment by Jrl0** [comment]
@nihal467 please update me status of this issue.

**Comment by rithviknishad** [comment]
@Jrl0 It is a work in progress, ready for QA testing, and it will go live within a week after the related PR has been tested.

cc: @nihal467 @aparnacoronasafe
