### ISSUE TITLE
Discharged patient's timeline order issue in facility's view patients feature 

### ISSUE THREAD

**Issue by Deepjyoti14** [coronasafe/care_fe#7581]
**Describe the bug**
Although patient's admission and discharged timestamp order (newest to oldest) is correct under both "active and discharged" tab in "patients" section in Home page; But in "view patients" section in a particular facility the order is coming as "oldest to newest" under "discharged" tab.

**To Reproduce**

1. Go to 'care.coronasafe.in'
2. Click on 'click on any facility's "view patients" button.'
3. Click on 'discharged' tab.
4. Order is wrong.

**Expected behavior**
1. order should be "newest to oldest" or
2. filter should be available to sort out data as per admission date timestamp.

**Comment by hrit2773** [comment]
@Deepjyoti14 @khavinshankar can you assign this to me
