### ISSUE TITLE
Add a new field on facility to link a spoke facility to hub facility

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#7583]
We need to change the facility form to allow deployments with hub and spoke hospitals specify relations between hub and spokes facilities

![image](https://github.com/coronasafe/care_fe/assets/46787056/876958bd-f9fa-43d7-81f0-0a2e9168bd92)

![image](https://github.com/user-attachments/assets/e186207a-dde6-4827-9754-e6c35d39889e)

- Add a spoke editor to facility form
- Spokes can be of two types : regular or TeleICU
- A spoke can have multiple hubs
- A spoke can be a hub to other spokes

**Comment by Sulochan-khadka** [comment]
Hey @sainak , would love to work on this issue but just for my understanding, may you explain somewhat more?

**Comment by AnkurPrabhu** [comment]
@sainak can i take this up ?

**Comment by hrit2773** [comment]
@nihal467 can I take this up?

**Comment by sainak** [comment]
@Sulochan-khadka can you post an eta on this, we are expecting this to be merged by next week.

**Comment by nihal467** [comment]
@Sulochan-khadka Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by shivankacker** [comment]
As discussed on EOD call (03-05-24) a spoke can have multiple hubs.
