### ISSUE TITLE
Icon overlapping with text in text-box of Patient's Notes. 

### ISSUE THREAD

**Issue by Sulochan-khadka** [coronasafe/care_fe#7586]
**Describe the bug**
Bug similar to #7495 

**To Reproduce**

1. Go to Patient tab
2. Click on any patient card
3. Click on patient's details
4. Scroll down to view patients notes
5. Type something... (till the line breaks)... See the error.

**Expected behavior**
Icon must be separated from the text section.

**Screenshots**
<img width="1436" alt="Screenshot 2024-04-11 at 2 26 09 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/3c3548a8-fe53-462e-a78a-69b705b27137">

**Comment by Sulochan-khadka** [comment]
@rithviknishad just have a look at the pr...

**Comment by kumar11jr** [comment]
hey @rithviknishad  can i work on this issue

**Comment by Sulochan-khadka** [comment]
Hey mann @kumar11jr , there's already a PR which fixes this issue. If you wish, you can explore other issues. Let me know if you are willing to contribute, I will tag you in the next issue that I report. Is that ok with you mate?

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad, should we close this issue? I tried reproducing the error, but everything seems to be working fine.

**Comment by nihal467** [comment]
The issue is already resolved
