### ISSUE TITLE
Add Notifications for Facility Cover Image Deletion

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7595]
**Describe the bug**

- [ ] Notification is Missing Upon Deletion of Facility Cover Image

**To Reproduce**

1. Go to the Facility detail page with the existing cover image
2. delete the existing cover image
3. See error

**Expected behavior**

- [ ] Upon deletion of a cover image, add a notification stating " Facility Cover Image Deleted Successfully "

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/33d592df-2ac5-45a7-8d4d-8e40f34124da)

**Comment by AnkurPrabhu** [comment]
can i take this up ?

**Comment by AnkurPrabhu** [comment]
@nihal467 we already had a notification for this one just fixed it do we still need the copy change ? it is currently "Cover image deleted"
