### ISSUE TITLE
Add Appropriate Notification upon updating facility middleware configuration

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7596]
**Describe the bug**

When updating the facility middleware address, ensure that the notification message accurately describes the action taken.

**To Reproduce**

1. Go to facility configuration page
2. update its middleware address
3. See error in the notification

**Expected behavior**

Upon successful update of the facility middleware, modify the notification to display the specific message: 'Facility Middleware updated successfully'.

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/a7baa7f6-44dc-43e5-9861-fff7e8a180bf)

**Comment by rash-27** [comment]
I would like to work on this issue
