### ISSUE TITLE
Disable the delete button for user other than admin in location and bed management

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7601]
**Describe the bug**

Users without admin privilege have no delete permission for the bed in a facility location

**To Reproduce**

1. Go to facility location page
2. Click on manage beds
3. delete a existing bed

**Expected behavior**

- [ ] Disable the delete button in bed management and location management for user other than admin (district, state and super admin)
- [ ] when users hover-over the disabled button, have tooltip, mentioning "Contact your admin to delete the location" and "Contact your admin to delete the bed"

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/f8690e22-4f5c-4768-83f5-e025239126ed)

![image](https://github.com/coronasafe/care_fe/assets/57055998/93cda674-30c6-4b1e-8275-84319c75c8ae)

**Comment by AnkurPrabhu** [comment]
i can take this up now as p1 issue is not assigned to me now
