### ISSUE TITLE
Revise the notification message for facility inventory use stock.

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7602]
**Describe the bug**

When we submit the use stock of a inventory, the notification says, "inventory created successfully"

**To Reproduce**

1. Go to facility inventory 
2. Click on manage inventory
3. Add a new stock for a item
4. now make few quantity as use stock for the same item
5. See error

**Expected behavior**

When updating the inventory with used stock and submitting the form, the notification should display: 'Inventory use stock updated successfully'.

![image](https://github.com/coronasafe/care_fe/assets/57055998/90358560-4883-4eda-afa8-b9e84655d4c3)

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/dec41b10-0159-4fa8-906e-347221be5060)

**Comment by AshrafMd-1** [comment]
@nihal467 i want to work on this issue can you assign me this
