### ISSUE TITLE
Tooltip clipping in the facility inventory entry log page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7603]
**Describe the bug**

When we hover over the "mark as accident" button in the inventory log page, the tooltip is clipping in the list

**To Reproduce**

1. Go to facility inventory manage page
2. Click on the name of a existing item in the inventory page
3. hover over the button

**Expected behavior**

the tooltip should be properly visible in the normal and mobile view

*Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/6447fae5-b7c9-49ee-bb5e-0db63072441f)

**Comment by AshrafMd-1** [comment]
@nihal467 i want to work on this issue can you assign me this
