### ISSUE TITLE
Refactor user privileges in linked facility functionality

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7604]
**Describe the bug**

- [ ] When the nurse user trying to unlink themselves from a home facility, they are not allowed to perform this action and there are multiple error thrown in the frontend, which is little bit confusing
- [ ] When the nurse user try to unlink themselves from a linked facility, they are allowed to do that action

**To Reproduce**

1. Go to user tab. and click facilities button ( With nurse user ID)
2. Click on clear the home facility icon
3. See error

**Expected behavior**

- [ ] When the nurse user trying to unlink themselves from a home facility, they should be able to do it.
- [ ] When the nurse user try to unlink themselves from a linked facility, they should be able to do it.

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/ebc969b0-9152-4a7d-98e5-95887047a14d)

**Comment by UdaySagar-Git** [comment]
i would like to work on this can you please assign this to me

**Comment by nihal467** [comment]
@UdaySagar-Git Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.
