### ISSUE TITLE
Improve the change password handling in profile edit page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7605]
**Describe the bug**

- [ ] The password change input box on the profile update page lacks the same conditional checks found on the user creation page.
- [ ] When the wrong password is entered, there are multiple errors thrown at the same time
- [ ] we can input current password in the new password column and submit the form

**To Reproduce**

1. click on the profile name in the bottom right 
2. in the profile page, update the password
3. See error

**Expected behavior**

- [ ] password change input box on the profile update page should have the same condition check as the new user creation page
- [ ] Show the specific notification only " the old password - wrong password entered. Please check your password "
- [ ] add a validation for the new password column checking the current password inputted data and new password column are not having the same text

![image](https://github.com/coronasafe/care_fe/assets/57055998/7c8a192a-a45e-4cc5-afca-0a41249c5355)
![image](https://github.com/coronasafe/care_fe/assets/57055998/c1c6066e-d0e8-4b4f-8541-5ab1078f1a57)
---
**Screenshots below are the bugs**
![image](https://github.com/coronasafe/care_fe/assets/57055998/2e78a160-8b36-4c82-b87b-2dd2c9ee7c27)

![image](https://github.com/coronasafe/care_fe/assets/57055998/5ccb4a91-1be7-4471-a885-1f3d761f01e1)
![image](https://github.com/coronasafe/care_fe/assets/57055998/7a92c189-1274-448e-957c-d7e8d88bda39)

**Comment by UdaySagar-Git** [comment]
I would like to take this as well can you please assign me !

**Comment by r-nikhilkumar** [comment]
@nihal467 @rithviknishad can you assign this issue to me?
