### ISSUE TITLE
Facility view user page is not working as expected

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7606]
**Describe the bug**

- [ ] When clicking the 'Click here to show facility' button in the facility view user page, no linked facility is displayed for the user. Even after adding a new facility, it does not appear on the page.

**To Reproduce**

1. Go to the facility detail page
2. Click on manage the facility and click on View users
3. Scroll down to click here to show the facility button

**Expected behavior**

- [ ] In the card, mention the home facility of the user, as similar as the role
- [ ] reuse the slide over in the user tab, when the user clicks on the  "click here to show facility" button, show the link facilities slide over
below is the expected behavior screenshot 
![image](https://github.com/coronasafe/care_fe/assets/57055998/609f8e85-011c-4b53-84f8-67f5942d986b)

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/d2a5f54e-2ba8-4363-bd9c-e4662ac7d27c)

**Comment by rash-27** [comment]
I would like to work on this issue

**Comment by nihal467** [comment]
@rash-27 will you be able to push the PR in next 24-48 hours

**Comment by rash-27** [comment]
Yup , I'll try my level best

**Comment by Sulochan-khadka** [comment]
@nihal467 , this issue has already been reported by me and a PR was raised before... The issue is #7474 and the PR is #7494 . Thankyou...

**Comment by Sulochan-khadka** [comment]
All that is required @nihal467 is the quick testing of my PRs' that I have raised...

**Comment by Sulochan-khadka** [comment]
@nihal467 @rithviknishad Kindly merge my PR to solve this important issue. Thankyou.

**Comment by nihal467** [comment]
@rash-27 the issue have been already resolved, feel free to take over any other open issues
