### ISSUE TITLE
Toggle to be made available to Enter Emergency Contact No. From Phone Number

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7610]
During Filing the Demographic Information Of the Patient, Toggle to be made available to Enter Emergency Contact No. From Phone Number so that it eases the process for User.
Below Image is attached as Example illustration(Below Image is from User Module, similarly this can be made available in Patient Demographic fields-with change in respective Wordings)

![Screenshot 2024-04-15 112715](https://github.com/coronasafe/care_fe/assets/166367729/e26b7ed8-3a30-48a9-b40d-b1dd85b4ad6a)

**Comment by manasvi-gaur** [comment]
@gayann-au @rithviknishad can you please assign this issue to me?
