### ISSUE TITLE
Areas of Specializations needs to Be increased to a Doctor w.r.t. facility Details

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7612]
When Updating the facility details, while adding the Doctors list currently it is observed only few areas of Specialization are found in dropdowns.
This has to be incremented with various Specialization skills. Attaching the respective Snapshot for reference
![Screenshot 2024-04-15 114410](https://github.com/coronasafe/care_fe/assets/166367729/7df0a8e7-c7d6-4fe8-8d75-5f47f7b0d3ab)

**Comment by nihal467** [comment]
@gayann-au can you provide the list of Specialization you are proposing to expand

**Comment by gayann-au** [comment]
@nihal467 Adding the specialization sets which are present in 'Link Skills' in User module should help. Also Kindly add just "MBBS Doctors" without any specialization for Interns and MO Doctors and MBBS DTCD(Diploma in Tuberculosis and Chest disease) which is currently not available in "Link Skills" dropdowns.

![Uploading Screenshot 2024-04-15 131740.png…]()

**Comment by aparnacoronasafe** [comment]
@gayann-au @nihal467 just reviewed the issue.

addition of "mbbs doctor" in the list is taken up separately at https://github.com/coronasafe/care_fe/issues/7616

for this issue, do the following:
- [ ] Facility dashboard (https://github.com/coronasafe/care_fe/issues/7616) change "Doctor List" to "Staff Capacity"
- [ ] Change the text on the button for "Add doctor type" to "Add Staff type"
<img width="665" alt="Screenshot 2024-04-15 at 3 29 51 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/d2949ac8-f7ca-4f63-a162-4328550dd89e">

- [ ] edit the pop-up window. title to be "Add staff capacity"
- [ ] "area of specialisation" to be changed to "Staff type"
- [ ] the dropdown for area of specialisation to be synced with the list of skills available on user module + Others+ Nurse. 
- [ ] the existing data to be mapped as "Critical care"= "Intensivist", "pediatric"="Pediatrician". "other speciality"="Others"

**Comment by rash-27** [comment]
I would like to work on this issue

**Comment by aparnacoronasafe** [comment]
@rash-27 please give a delivery date. this needs to be closed ASAP
