### ISSUE TITLE
Modify the error message on the user session expired scenario

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7613]
**Describe the bug**

When a session is getting expired, the notification error is thrown as "Authentication credentials were not provided"

**To Reproduce**

1. Stay of a page until you're session is expired
2. See error

**Expected behavior**

rephrase the notification to show as "Session expired. Please Login again"

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/8f84a2ec-62ad-465e-a478-182d04f38a43)

**Comment by Sulochan-khadka** [comment]
Let me take this up and quickly solve this @nihal467

**Comment by kumar11jr** [comment]
hey @nihal467 can you assign me this issue

**Comment by AshrafMd-1** [comment]
@rithviknishad can you assign me this issue I want to work on this issue?
