### ISSUE TITLE
revise list of skills

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7616]
**Is your feature request related to a problem? Please describe.**
Users in CARE may be linked with skills in the user management page (https://care.coronasafe.in/users).

List of such skills need to be upgraded.

**Describe the solution you'd like**
Add:
"MBBS doctor"
"Dentist"
"Oral and Maxillofacial Surgeon"
"Infectious Disease Specialist"
"Immunologist"
"Geriatrician"
"Sports Medicine Specialist"
"Pediatric Surgeon"
"Transfusion Medicine Specialist"

**Comment by rash-27** [comment]
Can I work on this issue ?

**Comment by aparnacoronasafe** [comment]
@rash-27 could you please check? I have expanded the list to be added a bit more. This is the final requirement.

**Comment by rash-27** [comment]
> @rash-27 could you please check? I have expanded the list to be added a bit more. This is the final requirement. 

Ok sure !

**Comment by rithviknishad** [comment]
Closing as completed in https://github.com/coronasafe/care/pull/2096
