### ISSUE TITLE
Modify the Notification related to Patient Log update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7619]
**Describe the bug**

When we are creating normal log updates or critical care log updates, most of the notifications are "Consultation update created successfully" , which is generic and not specific to user actions.

**To Reproduce**

1. Go to patient consultation page
2. create a log update
3. See error

**Expected behavior**

All log update-related notification should be action specific for example , if a normal log update got created, it should be giving a notification "Normal Log update created successfully"

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/d7547073-f0d8-4fc9-994c-51349f2446b7)

**Comment by r-nikhilkumar** [comment]
@nihal467, @rithviknishad  can you assign this issue to me?

**Comment by r-nikhilkumar** [comment]
@nihal467 it should be something like this, right?
![image](https://github.com/coronasafe/care_fe/assets/91010142/21f5d0bf-5569-42b9-9aba-742347345071)

if yes? assign me, I'll create pull request asap
