### ISSUE TITLE
Add proper error message for Camera configuration page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7620]
**Describe the bug**

When we enter the wrong middleware for a camera configuration, it throws "something went wrong" error

**To Reproduce**

1. Go to camera asset configuration page
2. input wrong middleware and submit
3. See error

**Expected behavior**

It should be throwing a proper error

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/dde96b0e-39dc-4749-8860-f13f9a6b9ffe)

**Comment by hrit2773** [comment]
@nihal467 can you assign this to me

**Comment by hrit2773** [comment]
@nihal467 should the error message say wrong middleware hostname

**Comment by hrit2773** [comment]
@nihal467 the server is throwing internal server error even after clicking configure in Asset details page is the middleware address already configured wrong?

**Comment by rithviknishad** [comment]
Unassigning as stale

**Comment by rithviknishad** [comment]
Closing in favour of #7511
