### ISSUE TITLE
overlapping the search box's placeholder text

### ISSUE THREAD

**Issue by arindamsaha2022** [coronasafe/care_fe#7622]
**Describe the bug**
The placeholder text in the search box overlaps with the other text (Ctrl K), and this overlap issue also appears when you write to the end of your writing. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the Assets tab
2. control + scroll 
3. See error
4. type something all the way to the end 
5. See error

![Untitled design](https://github.com/coronasafe/care_fe/assets/112413589/b1eea937-dd03-4369-b91a-bfd1fc39ac10)

![Screenshot Capture - 2024-04-14 - 19-16-03](https://github.com/coronasafe/care_fe/assets/112413589/cada6489-c016-46ee-8636-4a5ec3ad21f6)

**Expected behaviour**
it should not be overlapping

**Comment by manasvi-gaur** [comment]
@rithviknishad can you assign this issue to me?

**Comment by Damika-Anupama** [comment]
Hi @arindamsaha2022 I'd like to contribute this issue, please assign this to me

**Comment by rithviknishad** [comment]
Closing as duplicate of #7857
