### ISSUE TITLE
Export function is not working Sample Test

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7628]
**Describe the bug**

the export function is not working for the sample test homepage

**To Reproduce**

1. Go to /sample
2. Click on export button
3. See error

**Expected behavior**

the export function should be working for the sample test homepage as expected

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/ad9d8350-26b4-427d-8204-83e76489ba06)

**Comment by AshrafMd-1** [comment]
I want to work on this issue can you assign me this

**Comment by AshrafMd-1** [comment]
@nihal467  The URL seems to be wrong

<img width="469" alt="image" src="https://github.com/coronasafe/care_fe/assets/98876115/3a451531-6d1a-4bf8-85fc-91886efce2db">

<img width="456" alt="image" src="https://github.com/coronasafe/care_fe/assets/98876115/90caab28-f422-459a-9bc8-e6461beebb73">

**Comment by Ashesh3** [comment]
> @nihal467 The URL seems to be wrong
> 
> <img alt="image" width="469" src="https://private-user-images.githubusercontent.com/98876115/322903011-3a451531-6d1a-4bf8-85fc-91886efce2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODM5MzQsIm5iZiI6MTcxMzI4MzYzNCwicGF0aCI6Ii85ODg3NjExNS8zMjI5MDMwMTEtM2E0NTE1MzEtNmQxYS00YmY4LTg1ZmMtOTE4ODZlZmNlMmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE2MDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MmExZjA4ZjNlZmExZmQ5MWJhNDVhMWE2MDgwOGZiM2YyNmY3NzJkMGU3OTMxMWI3ODQxMDhjMjFjM2FjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9tilu3irdosNS6xP7WfhezlnfisZmAzl9Sr4pFQV6oQ"> <img alt="image" width="456" src="https://private-user-images.githubusercontent.com/98876115/322903141-90caab28-f422-459a-9bc8-e6461beebb73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODM5MzQsIm5iZiI6MTcxMzI4MzYzNCwicGF0aCI6Ii85ODg3NjExNS8zMjI5MDMxNDEtOTBjYWFiMjgtZjQyMi00NTlhLTliYzgtZTY0NjFiZWViYjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE2MDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyY2NhNmE5NWVmMTVkMjAzYjhiZmNhMzY3ZDZlMjA0MmZhNmQ5MWJjMzczZDk5ZTQzZTdkYmYzZTJmN2ViOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7llBFtbagWWEY_MLXIZuVslykkfYV3IoQ16i0MvXIOc">

api url is correct.

This is the stacktrace of the crash:

```
FieldError
Unsupported lookup 'age' for BigAutoField or join on the field not permitted, perhaps you meant range or gte?

Cannot resolve keyword 'age' into field. Choices are: abha_number, abha_number_id, action, address, allergies, allow_transfer, assigned_to, assigned_to_id, blood_group, cluster_name, consultations, contact_with_confirmed_carrier, contact_with_suspected_carrier, contacted_patients, contacts, countries_travelled, countries_travelled_old, covin_id, created_by, created_by_id, created_date, date_declared_positive, date_of_birth, date_of_delivery, date_of_receipt_of_information, date_of_result, date_of_return, date_of_test, death_datetime, deleted, designation_of_health_care_worker, disease_status, district, district_id, emergency_phone_number, estimated_contact_date, external_id, facility, facility_id, fit_for_blood_donation, frontline_worker, gender, has_SARI, id, instituion_of_health_care_worker, is_active, is_antenatal, is_declared_positive, is_medical_worker, is_migrant_worker, is_vaccinated, last_consultation, last_consultation_id, last_edited, last_edited_id, last_menstruation_start_date, last_vaccinated_...


Crashed in non-app: django/db/models/sql/query.py in names_to_path

Show 6 more frames

care/facility/api/viewsets/patient_sample.py in list at line 127
In App

            and request.user.user_type < User.TYPE_VALUE_MAP["Doctor"]
        ):
            raise PermissionDenied()
        if settings.CSV_REQUEST_PARAMETER in request.GET:
            queryset = self.filter_queryset(self.get_queryset()).values(
                *PatientSample.CSV_MAPPING.keys()
            )
            return render_to_csv_response(
                queryset,
                field_header_map=PatientSample.CSV_MAPPING,
__class__	
<class 'care.facility.api.viewsets.patient_sample.PatientSampleViewSet'>
args	
[]
kwargs	
{}
request	
<rest_framework.request.Request: GET '/api/v1/test_sample/?csv=1&'>
self	
<care.facility.api.viewsets.patient_sample.PatientSampleViewSet object at 0x7f7fd3d49510>

Show More
Called from: rest_framework/views.py in dispatch
```

**Comment by AshrafMd-1** [comment]
@Ashesh3 It seems like a backend issue most probably because there is no age field in the DB
Even in the frontend we calculate age by using data of birth 
also adding a backend tag would be better
