### ISSUE TITLE
Modify the error message in the asset configuration page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7635]
**Describe the bug**

When we try to input the same IP address, into an asset within a facility, it throws multiple errors

**To Reproduce**

1. Create two assets with the same IP configuration
2. See error

**Expected behavior**

It should only be throwing one proper error  for example in the screenshot it should be: "IP Conflict: 192.168.68.116 is in-use by 'test-camera' asset within the facility"

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/675da183-adbc-4d71-8728-79992605e0b6)

**Comment by manasvi-gaur** [comment]
@nihal467 can you please assign this issue to me?

**Comment by AshrafMd-1** [comment]
@rithviknishad   I want to work on this issue can you assign me this ?

**Comment by rithviknishad** [comment]
Closing in favour of #7511
