### ISSUE TITLE
Terminology needs to Changed to "Critical Care" of Round type in Log Updates instead of 'Ventilator'

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7641]
Terminology which comes up when Round Type is selected as 'Crictical Care' in Log Updates needs to Changed to "Critical Care". Currently When Round type in Log Updates is selected As 'Critical Care', updated Card is shown as 'Ventilator'.

 PFA snapshot for reference 
![Screenshot 2024-04-17 111740](https://github.com/coronasafe/care_fe/assets/166367729/8c75ac33-2181-4082-8dd3-abfbc805b549)

**Comment by Sulochan-khadka** [comment]
@gayann-au may I work on this?

**Comment by Ashesh3** [comment]
This seems to be resolved already - @nihal467 could you confirm?

**Comment by Ashesh3** [comment]
Fixed by https://github.com/coronasafe/care_fe/pull/7666
