### ISSUE TITLE
To Tag Specialization to Treating Physician Card in Patient Dashboard

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7648]
To Tag Specialization to Treating Physician Card in Patient Dashboard. This will help the users to understanding specialization of respective Doctor without reviewing the skills and avoids multiple search efforts to know the specialization.   PFA screenshot below for better understanding

![image](https://github.com/coronasafe/care_fe/assets/166367729/58480fb9-e2f1-4f9b-b712-eb64ae2aa553)

**Comment by Vasanth375** [comment]
I would like work on this can you please assign me

**Comment by Vasanth375** [comment]
![image](https://github.com/coronasafe/care_fe/assets/77767837/e28088b0-831a-4709-8893-e979c0bbc2e5)
Here in the consultation object treating_physician_object we have firstname last name of the physician right and also we have user_type attribute, but you said specialization of the physician right 
user_type only specialization right?

Just need a clarification of the issue

**Comment by aparnacoronasafe** [comment]
Closed with #7810
