### ISSUE TITLE
IP/OP Number Search to be search by exact match

### ISSUE THREAD

**Issue by dpnkr1** [coronasafe/care_fe#7651]
**Describe the bug**
suppose we are looking for discharge patient record in particular facility, so to find that patient record we use the ip/op number because its unique number assigned to them by the facility. so while searching for that patient record using the ip/op number multiple patient records are coming  up along with that patient record. 

**To Reproduce**

1. Go to 'patient page'
2. Click on 'click on discharge patients'
3. Then click on advance filter.
4. Then set the date range and select a particular facility in which you want find the patient, then apply the filter.
5. Then search for a patient record using the ip/op number. After searching you will find multiple patient record coming up along with the patient record you were looking for.

**Expected behavior**

Modify the "search by OP/IP number" function in the patient tab to only provide exact matching results.

**Screenshots**
![Screenshot 2024-04-18 140519](https://github.com/coronasafe/care_fe/assets/132548965/01e5fe6e-f0d9-42ea-a1ca-5dd6db90a915)

**Comment by AshrafMd-1** [comment]
@dpnkr1 I am somehow not even able to reach this

**Comment by nihal467** [comment]
@AshrafMd-1 follow the below step :

1. create multiple patient with IP/OP number 1/24 ,121/24, 211/24, 311/24 
2. in the patient tab, search the OP number field input 1/24
3. you will be seeing search result with 4 patient card, that is the error.

Expected beahvior

we should be only seeing patient card with exact ip/op number match as 1/24

**Comment by rithviknishad** [comment]
Closing as completed via https://github.com/coronasafe/care/pull/2136
