### ISSUE TITLE
Search functionality should be showing exact match result on top

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7653]
**Describe the bug**

When we perform the search function in the care, it does not show the exact match results on the top.

**To Reproduce**

1. Go to facilities page
2. Click on search and type
3. See the error

**Expected behavior**

in the search result, the exact match should be shown at the first of the sorting
Ref: https://stackoverflow.com/a/75932387/7887936

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/a5180abe-879a-4635-9386-d454dc6ce1d0)

**Comment by hrit2773** [comment]
@nihal467 can you assign this to me... while searching we should give priority to the first name and the one which exactly includes the first name should be given priority while sorting. I will make a PR as soon as you assign me. @rithviknishad

**Comment by hrit2773** [comment]
@nihal467 can you assign this to me it was inactive from the last week

**Comment by hrit2773** [comment]
@rithviknishad Iam ready with the PR along with test cases can you assign me back i will immediately make PR

**Comment by hrit2773** [comment]
https://github.com/coronasafe/care/pull/2167 @rithviknishad can you plz review it

**Comment by hrit2773** [comment]
@rithviknishad https://github.com/coronasafe/care/pull/2167 I already made a PR can you please review it
