### ISSUE TITLE
'Treating Physician' field nomenclature should be changed to 'Treating Doctor'

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7659]
'Treating Physician' field in Edit Consultation page the nomenclature should be changed to 'Treating Doctor' Since there are various Specialized Doctors treating Doctors are present in ICU.   Eg: If Dr.xxxxxxx is Anesthetist and shown Dr.xxxxxxx as Treating Physician which is technically Wrong. Since General terminology 'Treating Doctor' should be maintained.

Please find below snapshot for reference
       Seen in Patient Dashboard:    ![image](https://github.com/coronasafe/care_fe/assets/166367729/d238452a-c6ad-4777-9d3a-dbe8ac9fc85f)

Seen in Edit Consultation Page
![image](https://github.com/coronasafe/care_fe/assets/166367729/cb0ddc26-c350-4ea1-9f7f-640f53161669)

**Comment by ayushchauhan12** [comment]
i would like to work on this issue
