### ISSUE TITLE
'Normal' Round Type need to eliminated from Round type dropdown 

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7660]
'Normal' Round Type needs to eliminated from Round type dropdown since CARE being used in ICUs and selecting 'Critical' is should be mandated amongst users since it fetches all required Data in Critical CARE.

Currently Selecting  'Normal' round type by users which is resulting in Major Data missing both in CARE and Dashboards Maintained. 

Hence forth Round Type Being Only Critical avoids confusions

Please find the snapshot for reference 
![image](https://github.com/coronasafe/care_fe/assets/166367729/35c40c78-21a7-42b0-95e6-6102267035cf)

**Comment by nihal467** [comment]
since its a product level change @aparnacoronasafe can you comment on this issue ,

**Comment by aparnacoronasafe** [comment]
@gayann-au I understand your point. However, we need to give nurses the option of only adding vitals. the idea is vitals and some basic details may need to be updated more frequently than other details such as neurological monitoring etc.

Just giving you a heads up, the entire log update is being changed now. The large form would be broken down and data entry will be made easier.

**Comment by nihal467** [comment]
@gayann-au @aparnacoronasafe closing this issue as the discussion seem to be over, feel free to reopen the issue with a comment
