### ISSUE TITLE
Add Proper notification for Oversized cover image in facility page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7661]
**Describe the bug**

when we upload an oversized facility cover image, it throws a something went wrong error

**To Reproduce**

1. Go to facility details page
2. Click on cover image and upload a oversized image
3. See error

**Expected behavior**

when we upload an oversized image, it should be throwing "Oops! Facility cover image is too large. Please use a smaller size image. "

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/b549edf0-f134-45e1-bfa4-05da11dbcc7a)

**Comment by arindamsaha2022** [comment]
I want to work on this issue

**Comment by 609harsh** [comment]
hi @arindamsaha2022 are you still working on this issue?

**Comment by arindamsaha2022** [comment]
yes i am still working on this issue

**Comment by sainak** [comment]
resolved in https://github.com/ohcnetwork/care/pull/2472
