### ISSUE TITLE
Add more validation check for patient transfer logic

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7662]
**Describe the bug**

- [ ] When we transfer a patient today to a new facility and create a consultation with admission two days ago, they are being accepted in the system
- [ ] When we transfer a patient to a multiple new facilities, a create a consultation with the admission of the same time, they are being accepted in the system
- [ ] When we transfer a patient today to a new facility, today's date is considered as the discharge date but the user might have forgotten to do this, and they updated the card two days later 

**To Reproduce**

**Expected behavior**

- [ ] if already a active consultation exist, add a flow to accept manual discharge date from user while patient transfer
- [ ] new facility admission date should be less than the existing discharge date

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/a64d48a3-4012-4af3-8337-b127b05af850)

**Comment by nihal467** [comment]
@aparnacoronasafe can you provide your opinion on this issue

**Comment by aparnacoronasafe** [comment]
When a patient is discharged automatically, due to transfer to another facility, can we mark the discharge date as "unknown". 

Any encounter with discharge date as "unknown" must not be included in analytics relating to length of stay.

**Comment by nihal467** [comment]
non-relevant to current develop
