### ISSUE TITLE
CARE feels less responsive in Mac OS, Chrome when an overlay/blur is present

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7673]
**Describe the bug**
When an overlay is present, such as discharge modal, CARE high GPU usage is observed and the app feels less responsive than usual. This is noticeable especially in larger display resolutions.

**To Reproduce**

1. Open an overlay (advanced filters / discharge patient modal)
2. Observe high iGPU usage on Mac OS and lesser responsive app.

**Screenshots**
<img width="1710" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/acfbdccf-123b-4e12-bc2e-1ba247beab71">

**Desktop (please complete the following information):**

- OS: Mac OS Sonama
- Browser Chrome

**Comment by shivankacker** [comment]
What happens on removing the backdrop blur? I think that should reduce the load significantly.

**Comment by rithviknishad** [comment]
It happens even for this page:

The GPU load is consistently high on mouse hover. Looks like causing because of the small buttons having blur...

(unable to take screenshot with mouse hover on camera feed)

<img width="1710" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/f7bb4f4f-ad54-43e0-8c64-6f89543d30c3">

**Comment by rithviknishad** [comment]
Not reproducible on Firefox
