### ISSUE TITLE
No. of ICU Beds per Nurse per Shift in dashboard

### ISSUE THREAD

**Issue by Jrl0** [coronasafe/care_fe#7682]
At present the no. of ICU Beds per Nurse per Shift in dashboard is reflected as per the nurse registered on CARE. 

Problem: In many hospital, the use case of CARE for nurse is less so not all nurses are registered in CARE even if they are do duty at the ICU.  CARE is use by nurse only for data entry so it is quite unnecessary to register all the nurses in CARE.   e.g. In JNIMS many of the nurses are deregistered from CARE as per the order of ward in-charge in fear of misused yet they are on duty in ICU.

So the no. of ICU Beds per Nurse per Shift in dashboard represent wrongly. 

Proposed Solution: Create one data point at the CARE FACILITY dashboard where we manually update the number/status of nurses on duty in ICU for no. of ICU Beds per Nurse per Shift.

Something like this
![WhatsApp Image 2024-04-22 at 3 22 15 PM](https://github.com/coronasafe/care_fe/assets/54631630/7c88eb48-363f-4290-b9b5-260102c7d291)

**Comment by aparnacoronasafe** [comment]
this issue is closed as redundant. All nurses in the ICU must be registered in CARE. This problem will be further solved once we develop staff linking to location.
