### ISSUE TITLE
Make avail the Back Date entry in Shifting Module  

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7684]
Make avail the Back Date entry in Shifting Module so that after filing the Shifting Request and just in Case if User overpass to update the status on that particular day and update in future time the average length of Stay Increases in CARE and as well as in Dashboard which is current Condition. So availing the feature for Back Date Entry in Shifting Module might help user to avoid error and improve User Experience.
 
![image](https://github.com/coronasafe/care_fe/assets/166367729/de965b53-9542-44f5-bf1f-b8b27fc9f0e5)
 
Suggesting to bring above request in this Card.

**Comment by aparnacoronasafe** [comment]
When status of shift is marked as complete, it automatically discharges the patient from previous facility as "referred". This discharge is marked at present time.

Change required:

- [ ] Allow only staff from the origin facility or district/state admin to mark the shift as complete. Staff from the destination must not be able to mark the shift as complete.
- [ ] Once the shift is marked as complete, open up the discharge pop-up window with "Referred" as the reason for discharge and name of destination facility in "referred to" fields. Allow the user to type in the remaining details. once this is submitted, the patient is discharged from the facility.

**Comment by Ashesh3** [comment]
@aparnacoronasafe could you clarify the behavior when the wartime flag is active? 

>Allow only staff from the origin facility or district/state admin to mark the shift as complete. Staff from the destination must not be able to mark the shift as complete.

Is this still applicable for that situation?

cc: @gigincg

**Comment by aparnacoronasafe** [comment]
Yes. this proposed behaviour applies for when 'Wartime' flag is active

**Comment by nihal467** [comment]
@aparnacoronasafe 
![image](https://github.com/coronasafe/care_fe/assets/57055998/4a73a2b0-9b04-445d-8ee1-9f4deabcb447)

- [ ] when you are marking a patient complete, the destination facility is mandatory , then only we can successfully discharge a patient in shifting module
- [ ] But at the same time, the referred to discharge pop-up destination facility is a optional field, so it will throw a error, since we are trying to reuse the discharge pop-up here
