### ISSUE TITLE
Doctor's Notes- rename as "Discussion Notes"

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7686]
**Is your feature request related to a problem? Please describe.**
"Doctor's Notes" is confusing for the users. Since the feature is used for TeleICU, rename it to "Discussion Notes"

**Comment by ayushchauhan12** [comment]
i would like to work on this issue

**Comment by NNSiri** [comment]
> **Is your feature request related to a problem? Please describe.** "Doctor's Notes" is confusing for the users. Since the feature is used for TeleICU, rename it to "TeleICU Notes"

@aparnacoronasafe State has suggested to Name it as TeleICU specialist Advice. The term Notes is Very colloquial.
Also by doing this, i wanted to ask, where wil the spoke doctors enter their advices ?

**Comment by aparnacoronasafe** [comment]
As discussed the name shall be changed to "Discussion Notes".

Only to be done once #7705 is closed. Blocking issue for now
