### ISSUE TITLE
Doctor's Log update

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7705]
Add a new "Round Type" "Doctor's log"

The following fields must be available in the form

- Measured at (Mandatory)
- Category (Mandatory)
- Physical examination info
- Symptoms ( all active symptoms must appear, for the doctor to edit)
- Prescription (All active prescriptions must appear, for the doctor to edit)
- Investigation suggestion (all active suggested investigations must appear, for the doctor to edit)
- Respiratory support tab (from critical care round)
- Vitals tab (from critical care round)

-----

### Pre-requisites

- [x] #7711
- [x] #7712
- [x] #7567 
- [x] #3618

**Comment by ankitmrj** [comment]
@mentor
 can you assign this issue ?

**Comment by rithviknishad** [comment]
@ankitmrj This is a larger piece to be solved with a few prerequisites that need to be solved before this can be taken up.

Feel free to take up other good first issues: https://github.com/coronasafe/care_fe/contribute

**Comment by Sulochan-khadka** [comment]
@rithviknishad @aparnacoronasafe is there anything I can help in this? This issue seems important to be solved.

**Comment by aparnacoronasafe** [comment]
This is expected in production in 1-2 weeks @gigincg

**Comment by gigincg** [comment]
@aparnacoronasafe This feature by itself cannot be built on Care as is. The pre-requisites of the issue are being taken up right now, post which this will be taken up. It's a long roadmap to production, practically you can expect it in 3-4 months. 

Given the realities in the field, Will prioritize.

As a temporary solution, If you would like to update the issue, to a version that encompasses only fields that are available in Daily Rounds, we can ship it in on shorter notice.

**Comment by aparnacoronasafe** [comment]
I had informed the field team to expect the feature in 4-6 weeks after you said it can be done in the time frame. 

Revising timelines like this, and going from 6 weeks to 4 months will be hard for me to explain to the field team now. 

We must give more realistic timelines and stick to it. 

For now I will file another issue to simplify the form with existing fields.

Let us delivery this asap

**Comment by aparnacoronasafe** [comment]
@gigincg 

As V1, can we deploy a separate doctor's Log Update with the following items:
- Measured at (Mandatory)
- Category (Mandatory)
- Physical examination info
- Symptoms ( all active symptoms must appear, for the doctor to edit)
- Investigation suggestion (all active suggested investigations must appear, for the doctor to edit)
- Vitals tab (from normal round form)

The form, when submitted to take user to the prescription screen for adding changes to prescription 

Can this be deployed ASAP?
