### ISSUE TITLE
Reply function on Doctor's Note

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7706]
Develop an option to "reply" against a message on the doctor's note. Once user clicks on the reply option under a message, they must be able to add text message and send it as a reply. 

Eg: Whatsapp replies

This feature will in future allow us to understand how a suggestion added to a the doctor's note is received.

**Comment by rithviknishad** [comment]
Related to #7159

**Comment by UdaySagar-Git** [comment]
can you please assign this to me
