### ISSUE TITLE
Add page loader to the external results page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7716]
**Describe the bug**

The page loader is missing for the external results page

**To Reproduce**

1. Go to external results page
2. See error

**Expected behavior**

Add page loader to the external results page

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/d32e95b8-2e55-4ce3-94fe-edc185ed1ffa)

**Comment by AshrafMd-1** [comment]
I want to work on this issue can you assign me this
