### ISSUE TITLE
Make the switch bed card consistent

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7719]
**Describe the bug**

" the no-bed alloted yet " card is not having consistent design with other existing similar card

**To Reproduce**

1. Go to patient consultation page and click switch bed
2. See error

**Expected behavior**

Make it consistent similar to the existing design , add a white card, with related text

![image](https://github.com/coronasafe/care_fe/assets/57055998/339f51aa-07ac-47eb-a1d6-d5ef10765953)

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/17e50567-a733-4fdb-8d67-3042b98ef34e)

**Comment by AshrafMd-1** [comment]
@nihal467 can you assign me this issue

**Comment by AshrafMd-1** [comment]
Is this okay 

![image](https://github.com/coronasafe/care_fe/assets/98876115/4b14f9ef-9cbc-444b-ba5c-a2b918dbba02)

**Comment by nihal467** [comment]
@AshrafMd-1 put the no bed allocated yet inside a white card similar to the ss
