### ISSUE TITLE
Add frontend validation for titrated dosage

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7721]
**Describe the bug**

Currently, if we enter start dosage higher than the target dosage, in the medicine titrated dosage, the system accept it.

**To Reproduce**

1. Go consultation page, create a medicine with titarted dosage
2. start dose is 15 and target dose is 10
3. try to administor it

**Expected behavior**

there should be a frontend validation to ensure the target dosage is higher than the start dosage

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/e1b6889c-b794-4e0c-977d-b4bf3a59d3b9)

**Comment by hrit2773** [comment]
@nihal467 this seems good... I will make the PR today itself for this issue its a small one can you assign me

**Comment by Sulochan-khadka** [comment]
@nihal467 , there are some other issues as well. For example, one can change the units separately, which I think should not be permissible and many more of such vital errors. Therefore, should I include them as well in the PR, or just the start-target in this and file another PR to address them together?

**Comment by nihal467** [comment]
@Sulochan-khadka the issue is assigned to @hrit2773 , feel free to open a new issue for the bug you found related to this module

**Comment by Sulochan-khadka** [comment]
Sure @nihal467 . @hrit2773 , let me know if I can help you out to create PR as soon as possible. I think you will have to create and pass a function to DosageFormField so that a proper validation is added , so that it not only works when data is added from start to target but also checks if the start is changed again.

**Comment by hrit2773** [comment]
@Sulochan-khadka can you take this up... actually I started working on another issue which is a big one so I'm into that flow. I think this is a high priority issue right @nihal467

**Comment by Sulochan-khadka** [comment]
Yeah sure... Will be creating a PR soon...

**Comment by soumya-maheshwari** [comment]
hi @nihal467 i want to work on this issue
please assign me this.

**Comment by Sulochan-khadka** [comment]
Hey @soumya-maheshwari actually I have progressed significantly... Therefore if you already have progressed further, let me know... Otherwise I will be raising a PR in 2-3 hours.

**Comment by soumya-maheshwari** [comment]
Hey @Sulochan-khadka  it's fine you can continue with the issue as i have not started working on it.

**Comment by Sulochan-khadka** [comment]
<img width="942" alt="Screenshot 2024-04-30 at 4 14 26 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/649a127b-199a-4668-9a7d-1d85cc06570f">
is the UI all OK ? @nihal467 ? Or should the message be displayed somewhere else? Currently it is checking for validation once the submit is clicked.

**Comment by nihal467** [comment]
it's an expected behavior, @Sulochan-khadka closing this issue, feel free to assign new issues

**Comment by Sulochan-khadka** [comment]
@nihal467 is this solved? And I am unable to understand the meaning of expected behaviour in this reference? Does it mean that this was not even an issue?
