### ISSUE TITLE
Disable multiple buttons for discharged patients

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7722]
**Describe the bug**

few buttons are still active for discharged patients on the consultation page

**To Reproduce**

**Expected behavior**

![image](https://github.com/coronasafe/care_fe/assets/57055998/a10035ce-7b34-4777-8f20-78f7e6f95f75)

- [ ] disable log update edit button for discharge patient

![image](https://github.com/coronasafe/care_fe/assets/57055998/ec202d53-12c6-46f8-b8a8-4c68e1f0978d)

- [ ] disable all file upload related button in consultation page for patient

![image](https://github.com/coronasafe/care_fe/assets/57055998/eb544db8-907c-40bb-bd38-14fa86250a87)

- [ ] disable edit button in the already existing investigation view details page

**Comment by alanansari** [comment]
Hi, I would like to work on this issue. Please assign me.

**Comment by alanansari** [comment]
@rithviknishad please review the pr
