### ISSUE TITLE
Handle the wrong links in the platform properly

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7723]
**Describe the bug**

Our consultation edit form platform links ends with "/updates" for example "https://care-staging.ohc.network/facility/18b5f689-5dc1-4ff8-b585-daa19a03ec2b/patient/6de90332-3427-4b92-9368-eb36a45684ca/consultation/5a7bed2b-9d45-43d3-a6d6-5b1e99adc6f8/update" but if we replace the "/updates" with "/edit" we are been taken into a white screen

**To Reproduce**

1. Go to the consultation page of an active patient
2. Proceed as issue description 
3. See error

**Expected behavior**

we should be redirecting the user to an existing 404 page, mentioning the page doesn't exist 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/5f6b2385-3ed4-4d56-97c5-2b98685f591c)

**Comment by Aryanshu919** [comment]
Hey @nihal467 would you please assign this to me??

**Comment by AshrafMd-1** [comment]
@rithviknishad i want to work on this issue can you assign me this?
