### ISSUE TITLE
Redesign ABHA related POP-up

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7729]
**Issue Description**

The ABHA ID and No. are not properly represented in the Abha-related pop-up found on the patient consultation page
below is the existing design

![image](https://github.com/coronasafe/care_fe/assets/57055998/554b21c9-0c54-4699-a482-3b397ebdcfbe)

below is the expected design

![image](https://github.com/coronasafe/care_fe/assets/57055998/9d5909c7-15df-4b24-90d6-6053f9fb9c62)

**Comment by Aryanshu919** [comment]
Hey, I would like to work on this issue can you assign this to me.

**Comment by Ashutosh0602** [comment]
@nihal467 I was trying to locate this ABHA profile pop-up but could not find it. Can you help find out so I can fix this issue?
