### ISSUE TITLE
COVID related data, not required for every patient.

### ISSUE THREAD

**Issue by NNSiri** [coronasafe/care_fe#7732]
**Is your feature request related to a problem? Please describe.**
COVID related data as Vaccination status and COVID positive or Negative status on all patients discharge cards. 
only for relevant patients, where COVID specific data is enter, then these details can be shown, otherwise, it is not relevant for all the patients. 
<img width="547" alt="image" src="https://github.com/coronasafe/care_fe/assets/165636597/3c662c35-51bc-488b-b4ed-4ad204c364c6">
 
**Describe the solution you'd like**

- [ ] The vaccination status and the COVID positive status may be shown only for those patients for whom it is relevant. 

**Similar issue to be addressed along with this**

- [ ] modify forms to remove non-relevant covid fields https://github.com/coronasafe/care_fe/issues/7825

**Comment by nihal467** [comment]
https://github.com/coronasafe/care_fe/issues/7813 it is partly addressed, 

To do 

- [x] remove not vaccinated badge
