### ISSUE TITLE
The reference ranges on investigations modules.

### ISSUE THREAD

**Issue by NNSiri** [coronasafe/care_fe#7733]
**Is your feature request related to a problem? Please describe.**
the reference ranges on the investigation module is in correct. 
<img width="635" alt="image" src="https://github.com/coronasafe/care_fe/assets/165636597/375234dc-d391-4ddd-8bd9-909001ec762a">

**Describe the solution you'd like**
kindly refer to the list of investigations required and the normal reference values attached over an email to @aparnacoronasafe

**Comment by NNSiri** [comment]
@aparnacoronasafe @gigincg any update on this ?

**Comment by gigincg** [comment]
@NNSiri Can you attach the correct reference values here? You could upload it to a drive and share a link too!

**Comment by NNSiri** [comment]
https://drive.google.com/file/d/1vWoG7M55tTEx4blI2bYR1P5GCDNfTPgt/view?usp=sharing

https://docs.google.com/spreadsheets/d/1VeO1gJ5Lz_5-Jk0y96sTt6vCQbntowJu/edit?usp=sharing&ouid=100871533057731704360&rtpof=true&sd=true

Find the link to the documents on reference values.

**Comment by AdityaJ2305** [comment]
Hey @nihal467 , Is this issue open for contribution ? If yes, Can you clarify final expected behaviour and steps to reproduce 

cc: @Jacobjeevan

**Comment by nihal467** [comment]
the entire investigation module is being restructured , closing this issue
