### ISSUE TITLE
Occupation- patient registration form

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7736]
https://care.coronasafe.in/facility/997c7f30-8e2f-4d62-8b58-2a8771e658d6/patient/400cbedd-98d7-4f8f-b835-155ba71cc28d/update

"Occupation" field has a lot of options arranged in a chaotic manner. Difficult to find the right option.

- [ ] Arrange all option in alphabetical order.

- [ ] Keep "Others" and "Not applicable" as the last 2 items

- [ ] Remove "Don't Know" from the dropdown. no need to worry about data migration. Delete the records where "Don't Know" is selected.

**Comment by 609harsh** [comment]
hi @aparnacoronasafe please assign this issue to me

**Comment by 609harsh** [comment]
hi @aparnacoronasafe , @rithviknishad please review the PR
