### ISSUE TITLE
Discharge patient list

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7737]
Discharge patient page (facility wise) (https://care.coronasafe.in/facility/997c7f30-8e2f-4d62-8b58-2a8771e658d6/discharged-patients) must look exactly like the live list page

https://github.com/coronasafe/care_fe/issues/7570 adds the total number of patients.

Also add the following:

- [ ] Search by IP/OP Number
- [ ] Search by Primary Number
- [ ] Search by Emergency Number
- [ ] Advanced filter

All these features to be added, like on live patient listing

As a follow-up :

- [ ] admitted to, in the advanced filter, filter data based on the last bed assigned to the patient 
- [ ] remove the review missed filter since it's not required, 

The above details are verified on a call with @aparnacoronasafe

**Comment by shivankacker** [comment]
Will track exports in another issue

**Comment by gigincg** [comment]
@aparnacoronasafe Removing Exports from the Requirements here, as we are not supporting bulk exports
