### ISSUE TITLE
Recording Nursing Consultation from HUB

### ISSUE THREAD

**Issue by NNSiri** [coronasafe/care_fe#7748]
**Is your feature request related to a problem? Please describe.**
A Senior ICU Nurse will be deployed in HUB to take consultations with ICU nurses at the Spoke hospital. 
Where can she write her advices on CARE? 
She cant write it on Doctor's notes, as it is meant to be Doctor's space. 

**Describe the solution you'd like**
Have a *Senior Nursing Advice* tab for HUB Nurse to record Her/His advices.

**Comment by gigincg** [comment]
@NNSiri We have planned to make the Doctor Notes more generic, to solve this issue as well as #7686 

We can segregate notes from Doctors and Nurses within the Generic Patient Notes Tab. We discussed the following terms:

 - Patient Notes
 - Encounter Notes
 - Discussion Notes
 - Notes on Patient
 
 cc: @aparnacoronasafe

**Comment by NNSiri** [comment]
> @NNSiri We have planned to make the Doctor Notes more generic, to solve this issue as well as #7686
> 
> We can segregate notes from Doctors and Nurses within the Generic Patient Notes Tab. We discussed the following terms:
> 
> * Patient Notes
> * Encounter Notes
> * Discussion Notes
> * Notes on Patient
> 
> cc: @aparnacoronasafe

Discussion notes is the best fit in this scenario.

**Comment by aparnacoronasafe** [comment]
#7686 renames "Dcotor's Notes" to "Discussion notes"

Discussion notes to have 2 threads of Chat. 
1. Doctor's Discussion
2. Nurses Discussion

May be contained in 2 tabs within the chat window. 

- Nurses and doctors both must be allowed to post messages on both chat threads. this may be needed in the following scenarios
1) Doctor through TeleICU notices that the patient's Oxygen mask is not fitting properly. The doctors will be leaving a message for the nurses in the Nurses Discussion thread instructing them to correct it. 
2) In the doctor's discussion thread, the doctors are discussing the patient's condition and the remote doctor may have raised a question regarding a particular symptom the patient has. The nurse may be able to quickly respond to it and provide the doctors with a quick answer. 

Therefore, even though it is important to differentiate the 2 threads, doctors and nurses both may participate in these chats.

**Comment by rithviknishad** [comment]
@aparnacoronasafe 

Which thread would all of the existing notes go to?
Shall we categorize existing notes by doctor users to "doctors discussions" tab and notes by nurse users to "nurse discussions"?

**Comment by rithviknishad** [comment]
With that approach, we'll have an issue with categorizing notes filed by "District Admin" user type. Which thread will those existing notes belong to?

We have such records as of develop env. DB

<img width="640" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/a02d300a-b4fd-4cb1-860a-c42bea664090">

<img width="1698" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/ae14153a-bdb6-446b-ad4a-02c667b61386">

**Comment by rithviknishad** [comment]
As discussed, we'd be migrating all existing notes under doctor's discussion thread.
