### ISSUE TITLE
Remove all OP number validation 

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7751]
**Is your feature request related to a problem? Please describe.**
When a patient is readmitted to the same facility and both the consultation (new and previous) are Out-patient consultations (decision after consultation), the OP number may be the same as the last consultation's OP number. However, currently it throws an error 

**Describe the solution you'd like**

- [ ] Remove all validation for IP and OP fields

**Additional context**
<img width="1482" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/197102ec-2ecd-4580-abb0-43b54baa0fed">

cc: @nihal467 @aparnacoronasafe 

issue have been modified based on @gigincg and @aparnacoronasafe latest comments

**Comment by aparnacoronasafe** [comment]
The requirement here is to remove any type of Data validation on the OP No. field. Irrespective of the facility the patient is admitted to.

Discussed with @gigincg 

CC: @rithviknishad @skks1212 @nihal467 

REASON: The issue is, some hospitals are utilising this field to add their Patient ID (MRD No) for the patient, which may be consistent across all encounters for the patient in the facility. This is an acceptable behaviour. In order to allow this, remove all data validation from the field

**Comment by sainak** [comment]
> The requirement here is to remove any type of Data validation on the OP No. field. Irrespective of the facility the patient is admitted to.
> 
> Discussed with @gigincg
> 
> CC: @rithviknishad @skks1212 @nihal467
> 
> REASON: The issue is, some hospitals are utilising this field to add their Patient ID (MRD No) for the patient, which may be consistent across all encounters for the patient in the facility. This is an acceptable behaviour. In order to allow this, remove all data validation from the field

@aparnacoronasafe the field is handling many responsibilities, should we consider splitting it up?

cc: @gigincg

**Comment by gigincg** [comment]
> The requirement here is to remove any type of Data validation on the OP No. field. Irrespective of the facility the patient is admitted to.
> 
> Discussed with @gigincg
> 
> CC: @rithviknishad @skks1212 @nihal467
> 
> REASON: The issue is, some hospitals are utilising this field to add their Patient ID (MRD No) for the patient, which may be consistent across all encounters for the patient in the facility. This is an acceptable behaviour. In order to allow this, remove all data validation from the field

@aparnacoronasafe I thought we finalized on dropping Validations for Both OP and IP Numbers.

**Comment by rithviknishad** [comment]
https://github.com/coronasafe/care_fe/issues/7798

**Comment by aparnacoronasafe** [comment]
please proceed with removing all validations for both IP and OP field
