### ISSUE TITLE
Improving usages of font sizes to respect browser's font size preference

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7753]
## Summary

In CARE, font sizes are mostly relative and hence respect browsers preferred font sizes. However, in some places, font sizes are absolute and hence do not respect the preferred font size set by the user's browser.

One such example is the "beta" label for the Daily Rounds which is hard-coded at 10px.

- At "Very Large" browser font size:

<img width="614" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/479dede9-1ba3-46ee-8443-c5504ca2a6b2">

- At "Medium" (default) browser font size:

<img width="635" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/d910643b-1555-496b-b26e-98843f7c7b43">

This same issue is present in a couple of other places as well.

## Action Items

- [ ] Replace the font size to be relative (use rem values) instead of absolute pixels, to respect the browser's font size preference.

Ref: https://tailwindcss.com/docs/font-size

### Notes

To find all such occurrences, use regex search in your IDE, and search for: `text-\[.*px\]`

<img width="541" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/8164d9c3-9712-43ca-a7c6-c1cce23e51eb">

**Comment by Ashutosh0602** [comment]
I would to work on this issue
