### ISSUE TITLE
Nurse user type without home facility is able to edit prescriptions

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#7755]
**Describe the bug**
Nurse user id without Homefacility shouldn't be able to edit the prescription

**To Reproduce**

1. Go to patient dashboard
2. Click on medication and edit prescription

**Expected behavior**
When click on 'edit prescription', Show some error message saying no permission to do this task without a homefacility linked

**Comment by nihal467** [comment]
@rithviknishad downgrading it to P2, as frontend changes are been merged

**Comment by rithviknishad** [comment]
Updated the backend based on review changes requested
