### ISSUE TITLE
Clean up Facility registration form

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7758]
**Is your feature request related to a problem? Please describe.**
Details of oxygen storage and consumption may not be very relevant for many facilities registered in CARE.

Hence the data input fields may be moved to a separate section in the facility dashboard  https://care.coronasafe.in/facility/40ff580a-b37f-4738-b74c-25073d6b1288 (like the bed capacity and doctor's list)

**Describe the solution you'd like**

- [x] Remove the oxygen related fields from facility registration form https://care.coronasafe.in/facility/40ff580a-b37f-4738-b74c-25073d6b1288/update
<img width="1199" alt="Screenshot 2024-05-06 at 3 12 54 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/4f427659-5ceb-4c4e-9ab3-a36e02d47493">

- [ ] On facility dashboard edit the title "Oxygen Information" to "Details on oxygen supply and consumption"
- [ ] Add button to "Add details"
- [ ] Pop-up to be added (design consistent with "Bed Capacity") Pop-up title "Add oxygen details" with 
- Type of oxygen (dropdown with "Liquid Oxygen, Type B cylinder, Type C cylinder, Type D cylinder"
- Field for Max. Capacity and Expected burn rate to be added on the Pop-up window
- [ ] Visualisation of the details to be kept in consistent with the visualisation of bed capacity and doctors list.

**Comment by 609harsh** [comment]
hey  @rithviknishad  please assign this issue to me.

**Comment by 609harsh** [comment]
@rithviknishad for oxygen do we have any icon already at add oxygen details button?
![image](https://github.com/coronasafe/care_fe/assets/97297407/56c4218c-bc08-4ac1-9478-199679d9c40c)

**Comment by rithviknishad** [comment]
Couldn't find one specific to oxygen/cylinder. You could use the same one as the one used in the  "Add Triage" button.

**Comment by 609harsh** [comment]
Hi @rithviknishad, we need 4 new api endpoints (Get,Post,Put,Delete) for Oxygen Section at facility home page. can i create those or do i have to raise a issue?

Also while making Post api call at update facility button should we remove oxygen data that we are sending (as in  ui we have removed) or keep default values to be 0. since if we remove oxygen related data for api call i guess we will also need to update that endpoint.

**Comment by rithviknishad** [comment]
You could simply use the existing  PATCH facility api instead right?

**Comment by 609harsh** [comment]
@rithviknishad this one?
![image](https://github.com/coronasafe/care_fe/assets/97297407/8145601f-3820-4454-bd1b-bb1b7f885a13)

**Comment by rithviknishad** [comment]
Yup!

**Comment by 609harsh** [comment]
and what about fetching oxygen details?
should i use this 
![image](https://github.com/coronasafe/care_fe/assets/97297407/1774ec8d-34e0-4d06-b598-75ec54c7d51d)

**Comment by rithviknishad** [comment]
You don't need to fetch anything right? The parent component which is the facility details page, already would have fetched the facility record right? Just pass it down as a prop?

**Comment by noufalrahim** [comment]
@rithviknishad is the issue still on? Can I work on this?

**Comment by ayushpatil2122** [comment]
hey can you assign this issue to me

**Comment by NikhilGolla72** [comment]
@rithviknishad @aparnacoronasafe Hey guys, I would like to contribute to this issue. Could you please assign me to this?

**Comment by bodhish** [comment]
Resolved with https://github.com/ohcnetwork/care_fe/pull/9436
