### ISSUE TITLE
Unable to View the Log Updates for State Admin User Type

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7759]
Error Messages are popping up when the State Admin-User type try to View the Log Updates and unable to view the log Updates done.
Attached below the error Message Noted for ref.
![image](https://github.com/coronasafe/care_fe/assets/166367729/069e9217-f5ce-4f84-8075-476e71ec2009)

**Comment by shivankacker** [comment]
@gayann-au Can you share the link of the log updates you are trying to access?

**Comment by gayann-au** [comment]
@skks1212 This is encountering for all the Patients log Updates.
Sharing One of the Tested Patients Log Update(tested with State admin Creds) link For Reference 

https://care.coronasafe.in/facility/f8f05c04-5c97-415c-814d-419ecf692d0e/patient/b0d4401e-70e3-4390-876a-d0aa6f51352d/consultation/de7d4e63-efc1-44e6-b766-2fe2921a97da/daily-rounds/264bc627-e7b1-437f-94cf-8ce3e331e280
