### ISSUE TITLE
Text is not being reenforced for the dropdown when linking facilities while adding the user. 

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7762]
Typed Text gets wiped out/not support to the dropdown shown while linking the multiple facilities to one user when creating the user in the user Module. 
There's a need for enablement to select multiple searched result for relevant keyword Typed. Alongst all facilities should available to select when dropdown arrow is clicked
Screen recording is attached below for ref.

Uploading User_bug.mp4…

**Comment by Sulochan-khadka** [comment]
@gayann-au the issue is unclear to work on. Also the screen recording is not visible to me...

**Comment by gayann-au** [comment]
@Sulochan-khadka 

Readded the Screenrecording below. Let me Know for Further Clarification Is Needed


https://github.com/coronasafe/care_fe/assets/166367729/6d2b6e53-eb6d-487d-942d-073ff6977fdb
