### ISSUE TITLE
Prescriptions: Default Discontinued Prescriptions Collapsed

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#7767]
When there are multiple discontinued prescriptions for a patient, looking at the ones that are prescribed becomes difficult. Since they are not editable, having a collapsed view for prescriptions, and defaulting all discontinued prescriptions as collapsed would considerably improve 

Ref Screenshot:
![image](https://github.com/coronasafe/care_fe/assets/13028584/9693e220-512d-440c-8e9e-12c78e991a6b)

**Comment by Sulochan-khadka** [comment]
Is this issue solved @gigincg @bodhish or shall I raise a PR?

**Comment by gigincg** [comment]
Please do @Sulochan-khadka

**Comment by Sulochan-khadka** [comment]
https://github.com/coronasafe/care_fe/assets/122200551/584b5b16-b415-4992-93c3-9b8c65af3024

This is the fix that the PR is aiming at. @gigincg , @rithviknishad do let me know if any changes are required further in this.

**Comment by gigincg** [comment]
@Sulochan-khadka The design looks good. Please clear the issues that @rithviknishad had pointed out it so that it can be reviewed and merged

**Comment by Sulochan-khadka** [comment]
@gigincg @rithviknishad I am not in my work place, this , do not have access to my gadgets... I urge you to go ahead for now with rest of the PRs for them to get merged... Will resume from 3rd June...

**Comment by rithviknishad** [comment]
Thanks for informing @Sulochan-khadka 😄
