### ISSUE TITLE
ICD-11 Diagnosis code not working properly in CARE diagnosis module.

### ISSUE THREAD

**Issue by dpnkr1** [coronasafe/care_fe#7769]
**For some of the ICD diagnosis code when entered in CARE its shows no result found but after we delete the last character of that code the diagnosis comes up **

**To Reproduce**

1. Go to 'cares consultation page then  scroll down to the diagnosis part'
2. Then open icd 11 and copy the code for copd "CA22.Z"
3. Then come back to cares diagnosis part and paste or type the icd-11 code there.
4. Then you will see that care is not able to find the diagnosis copd with that copd code copied from icd 11, but when we delete the last character of the code (CA22.Z) which is Z, you will see the diagnosis copd will come up.

**Expected behavior**
After putting the code in diagnosis part. which we take from icd-11,  the diagnosis should come up. 

**Screenshots**

https://github.com/coronasafe/care_fe/assets/132548965/bb9dbdd9-a331-4ef2-95fa-6d756847eeae

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rithviknishad** [comment]
Related to: https://github.com/coronasafe/care/issues/1838

**Comment by aparnacoronasafe** [comment]
@nihal467 @sainak @rithviknishad 

Can we take this up as priority and close in 14 days?
