### ISSUE TITLE
Enhancement to the pain scale / Pressure sore component

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7781]
**Is your feature request related to a problem? Please describe.**

When we click on the badges related to the pain scale / pressure sore data's , there is no behavior been executed, it is acted as a simple badge.

**Describe the solution you'd like**

When i click on the badge, in the preview mode of pain scale / pressure sore, the user should be auto-scrolled to the part of the preview mode, the pop-up related to the body part should come up

**Describe alternatives you've considered**

![image](https://github.com/coronasafe/care_fe/assets/57055998/f587c58d-5baf-4c6c-aa79-68316611713a)

- [ ] above is the badge, user will be clicking

![image](https://github.com/coronasafe/care_fe/assets/57055998/6442db16-cdf8-4e89-9c55-0424a1a4d23c)

- [ ] post clicking the badge, this should be the view, this pop-up related to the body part

**Comment by shivankacker** [comment]
Will be fixed in #8119
