### ISSUE TITLE
Lengthy asset name is not properly handled in asset list page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7787]
**Describe the bug**

When we have bigger asset names, they are hidden few characters, even if we have enough white space

**To Reproduce**

1. Go to asset tab
2. create asset with wider lengthy names
3. See error

**Expected behavior**

- [ ] if space is available, based on the screen size, show the full asset names
- [ ] in the cases, due to limited space, if we are hiding part of the asset name with "...", add a tooltip to the asset name, if user hover over it, they can view the full name of the asset in the tooltip

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/3da9f4e0-06a9-4d1d-8700-34c4e27bdd78)

**Comment by Aryanshu919** [comment]
Could you assign this to me? I would like to work on this.

**Comment by 609harsh** [comment]
hey @nihal467 please assign this issue to me

**Comment by SwanandBhuskute** [comment]
I would like to work on this, can you assign me to it?

**Comment by SwanandBhuskute** [comment]
I have solved this locally, if you allow, I can raise PR
![Image](https://github.com/user-attachments/assets/b3c6148e-5aa0-4a91-936e-3f7f07c10552)
![Image](https://github.com/user-attachments/assets/c02da637-a330-4c9e-8352-1df395d16be8)
this will like this when hovered

**Comment by SwanandBhuskute** [comment]
I read the earlier PR and found what you want to achieve and I think I am able to do it using js logic with css
for now, by counting it seems if the name is > 18 , then it "truncates" (this 18 seems true for mobile screens also) 
but i know this should not be hardcoded to 18 and rather be some dynamic check 
any suggestions?

![Image](https://github.com/user-attachments/assets/715ca745-a346-4bf8-82ad-509152cccd2f)
means only longs names will be hovered and shown and normal ones won't

**Comment by gigincg** [comment]
@SwanandBhuskute Can you also add links to Assets that can be used with testing as well
