### ISSUE TITLE
Whatsapp Connect flow is not properly handled

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7793]
**Describe the bug**

When we click on the doctor connect icon, the whatsapp app opens in the first click, on the second click over the same button, the patient details get auto-fill

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/a74fa22a-0feb-4647-be32-f12e9cada12a)
![image](https://github.com/coronasafe/care_fe/assets/57055998/a1a33300-2ba5-4130-ab11-cec095ba3db4)

**Comment by gigincg** [comment]
@nihal467 Seems like an issue with Whatasapp Windows Client 😢 

Consider Reporting to WhatsApp 👍
