### ISSUE TITLE
manage patient button is not properly responsive 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7799]
**Describe the bug**

in the patient consultation page , the manage patient button is not properly responsive in the mac book screen

**To Reproduce**

**Expected behavior**

it should be properly responsive based on the screen size

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/00bedb38-538b-4f97-83e5-c86a0c632484)

**Comment by Sulochan-khadka** [comment]
Assign me... I will raise a PR now...
