### ISSUE TITLE
consent record only added to "edit consultation" and not new consultation forms

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7809]
**Is your feature request related to a problem? Please describe.**
#7416 adds consent record section in "edit consultation" (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/update) form. 

But the section is not added to new consultation forms

**Describe the solution you'd like**

- [ ] Add the "Consents" section in new consultation forms after dialysis
- [ ] It will be an optional field
- [ ] add a badge for patients with missing consent records (Live admitted patient only for now)

**Comment by nihal467** [comment]
#7812 new detailed issue has been filed regarding the same
