### ISSUE TITLE
Renaming patient categorisation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7811]
Currently the patient categorisation is as:
1) Comfort Care
2) Stable
3) Abnormal
4) Critical

Change this to
1) Comfort Care- keep as is
2) Stable- "Mild"
3) Abnormal- "Moderate"
4) Critical- keep as is.

This change needs to be made in the following places:

- [x] Consultation and edit consultation form (dropdown for category)
- [x] Log update form (dropdown for category)
- [x] Patient dashboard
- [x] Patient listing
- [x] Advanced filter (category filter)

Once done, inform Neil to change the terms on the state dashboard @nihal467

**Comment by Sulochan-khadka** [comment]
I think the data which has already been saved aren't changing. For example in this :
<img width="1438" alt="Screenshot 2024-05-14 at 4 40 40 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/78cba153-c500-439a-abfc-358b93170985">

However, I have changed in the mentioned places...

Shall I raise a PR? @aparnacoronasafe

**Comment by rithviknishad** [comment]
@Sulochan-khadka 

You can just re-label the text attribute in the constants, instead of changing the DB value.
It should reflect for all existing data too.

Feel free to create a PR (or draft) so that we can help you out!
