### ISSUE TITLE
Enhancement to the Existing consent form Implementation

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7812]
_The issue was created after a call with @aparnacoronasafe understanding user difficulties and requirement_

**Is your feature request related to a problem? Please describe.**
Ref: #7809 , #7416 
Currently, the consent form is part of the edit consultation form, which is not user-friendly and reported following problems such as:
- since it is not shown during the create consultation, the user assumes that, there is no function to upload patient consent in the platform
- The second concern is that, as it is present only in the edit consultation, users are not using the function and they are not alerted that the consent is missing in the consultation

**Describe the solution you'd like**

- [ ] Add a new button called "Consent Records" in the Manage patient dropdown below edit consultation (refer: SS 1)
- [ ] Create a dedicated page called "Consent Record"
- [ ] Replace the Consent form section from the edit consultation form to the new Manage Consents page.
- [ ] Remove the consent form preview from the overview section of the consultation dashboard
- [ ] In the file upload component of the consent form, add an option to select consent type and patient code (applicable only for patient code consent type) Refer: SS 3
- [ ] Add consent type and patient code status(If available) details along with the existing file details such as File name, created and created (Refer: SS 4)
- [ ] When consent is missing for a live admitted patient, show a consent missing badge similar to the review missed badge in the patient consultation page (Refer: SS 2)

Note:
- It will have similar behavior to the existing file upload ( Access controls, functionality, and all )
- It is an optional field and will apply to all patients (For now)
- Currently, Each patient consent type has individual archives and unarchive sections, we will be combining them into one view like our file upload section
- file upload dropdown for patient consent file selection **UI needs to be discussed on call and get approved before starting working on it.**

**Describe alternatives you've considered**

![image](https://github.com/coronasafe/care_fe/assets/57055998/8afc52f0-4faa-4435-9877-a51379dfd8c6)
![image](https://github.com/coronasafe/care_fe/assets/57055998/28691db6-f9bc-4df4-b4df-5ab96a070794)
![image](https://github.com/coronasafe/care_fe/assets/57055998/07b14577-481a-4309-9c99-490fe71c45d2)
![image](https://github.com/coronasafe/care_fe/assets/57055998/0d9a4756-76bf-4586-a38e-5f4cd25ebda6)

**Comment by nihal467** [comment]
As per @gigincg 's suggestion, 
- It is better to keep the consent inside the manage patient dropdown as all the data in the consultation tab are related to clinical data
- once we click on the consent records button, we will go to a dedicated page called consent records, where we will be doing all the related operations
- In case of missing consent, we will be showing a red badge in the patient consultation dashboard similar to the patient review missed badge

@aparnacoronasafe can you comment on this

**Comment by aparnacoronasafe** [comment]
LGTM

**Comment by nihal467** [comment]
@skks1212 you can start working on this issue as @aparnacoronasafe & @gigincg approved it
