### ISSUE TITLE
remove COVID Status from Patient details page

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7813]
Remove COVID status from patient details page (https://care.coronasafe.in/facility/06518832-e181-477d-9c0a-e46b3186edf3/patient/2ce2d39b-3be9-44f7-b1cf-d618d44f53ef)
<img width="1188" alt="Screenshot 2024-05-14 at 12 58 32 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/79353767-840d-4a62-89e2-50f892ec0b55">

Instead show "status- discharged" and "Last Discharge Reason- ....." on the left and the right section

**Comment by Sulochan-khadka** [comment]
@aparnacoronasafe for status-live, I have made "Last Discharged Reason" : "-".

Have a look at the proposed PR.
<img width="1438" alt="Screenshot 2024-05-14 at 4 06 40 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/492960a7-d68f-468b-a7f5-a118de575630">

<img width="1438" alt="Screenshot 2024-05-14 at 4 06 52 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/37a34849-8ecb-47c6-8e4a-9c0dc18ad782">

<img width="1438" alt="Screenshot 2024-05-14 at 4 07 13 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/4f387358-5046-45e0-ab46-dd527dc5693e">
