### ISSUE TITLE
Medical history and health details to be part of consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7815]
Add 2 new section to patient consultation form on top of existing content for 
- Medical History
- Health profile

The section must contain the following fields:

MEDICAL HISTORY
1. Any medical history? (Comorbidities) -(currently field present in patient registration form)
2. Ongoing medication (currently field present in patient registration form)

HEALTH PROFILE

1. only for female patient, Is antenatal? if yes "Last Menstruation Start Date" (currently field present in patient registration form)
2. only for female patient, Is postpartum? if yes "Date of delivery" (currently field present in patient registration form)
3. Allergies (currently field present in patient registration form)
4. Blood Group (currently field present in patient registration form)
5. Body Surface Area with weight and height (currently field present in patient consultation form)

Fields to discontinue
1. Present health condition (currently field present in patient registration form)- this field is not relevant since the consultation form already has another field for "History of present illness" which serves the same purpose

NOTES:
- This issue tries to improve categorisation of data points across patient registration and consultation form (and within the relevant section in consultation form). All the fields are existant but may need to be moved from one form to the other. 
- The fields moved from patient registration form to consultation form, the data will need to be stored as an encounter specific data. 
- For a new patient, once registration is done, consultation form opens up will all the fields empty. However, for the subsequent consultations, auto-fill the "Medical History" and "health profile" sections with data from previous encounter. The user will be updating this data as required and moving on to filling out the remainder of the consultation form.

**Comment by aparnacoronasafe** [comment]
@khavinshankar why is this blocked?

**Comment by Sulochan-khadka** [comment]
Saw this as P2 and still open. Can i be of any help to this? @gigincg @khavinshankar @nihal467

**Comment by nihal467** [comment]
@Sulochan-khadka the entire form is been restructured @gigincg is working on it

**Comment by nihal467** [comment]
not a requirement based on the current develop
