### ISSUE TITLE
Drop date-fns infavor of dayjs

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#7842]
Both Day.js and date-fns provide similar functionality for date and time manipulation. We have decided to remove date-fns in favor of dayjs due to its minimal package size.

**Comment by shivankacker** [comment]
@khavinshankar 
Day.js is 666kb,
date-fns is 22Mb
why are we removing Day.js? Is it because of more functionality? 😅

**Comment by khavinshankar** [comment]
Oh my bad, I wrote it in reverse 😅

**Comment by rithviknishad** [comment]
Closing as completed in https://github.com/coronasafe/care_fe/pull/8318
