### ISSUE TITLE
File is not getting reset after upload

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7843]
**Describe the bug**

- [ ] When we upload a .png file from a **Windows laptop**, after the successful upload, the file name is not being reset

**To Reproduce**

1. Go to the patient tab
2. click on a patient card with active consultation
3. go to the file section using the nav section under the diagnosis card
4. upload a file with .png format to the file section
5. once the upload is completed, 
6. see the error, The file name .png is still visible under the file name field even after successful upload

**Expected behavior**

- [ ] after the successful upload, the file name should reset

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/d678e8b6-487e-4d48-bc90-3477bfb143b1)

**Comment by AshrafMd-1** [comment]
@nihal467  not able to reproduce it

**Comment by gigincg** [comment]
@nihal467 Requires updated Steps to Reproduce

**Comment by nihal467** [comment]
> @nihal467 Requires updated Steps to Reproduce

done

**Comment by shivankacker** [comment]
@nihal467 seems like the issue was resolved with the recent file upload component redo. Closing as completed. Please reopen if you encounter the issue again.
