### ISSUE TITLE
Enhance the existing AutocompleteFormField component

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7849]
**Is your feature request related to a problem? Please describe.**

When we click on a component, such as the occupation input field in the patient registration form, it does not prefetch the entire list unless the user inputs a character.

![image](https://github.com/coronasafe/care_fe/assets/57055998/0e15849b-cfd2-4819-b306-10fcad847823)

**Describe the solution you'd like**

When the user clicks on the component, it should prefetch the entire list, and the dropdown should appear as shown in the screenshot below.

Note: it should filter the dropdown based on user input incase user type anything in the component

![image](https://github.com/coronasafe/care_fe/assets/57055998/ed188dd7-32bc-4462-9d32-df626182e83e)

**Comment by 609harsh** [comment]
@rithviknishad please assign this issue to me

**Comment by nihal467** [comment]
@609harsh I am unassigning you from this issue, as you already have an unfinished PR pending Cypress changes. Kindly work on that PR, before getting new issues assigned

**Comment by JOSHIK27** [comment]
I would like to take up this issue. Can you assign me @rithviknishad

**Comment by JOSHIK27** [comment]
https://github.com/coronasafe/care_fe/assets/96165631/f76387d3-645f-4316-bb55-9a9593b3547e

@nihal467 The requested feature can be achieved by adding a prop to the combo box headless UI component (Latest). For that, we will have to install this [updated](https://github.com/tailwindlabs/headlessui/discussions/1236#discussioncomment-7375206) headless UI package. I have added a demo. Please let me know if this solution is ok, happy to open PR.

**Comment by rithviknishad** [comment]
@JOSHIK27 Yes go ahead!

You could use https://github.com/coronasafe/care_fe/pull/7840 as the base branch as that upgrades headless UI to the required version.

cc: @khavinshankar

**Comment by JOSHIK27** [comment]
@rithviknishad I am getting conflicts when rebasing my branch with develop branch to open pr (when worked with #7840 as base branch).  I will open pr once [conflict](https://github.com/coronasafe/care_fe/pull/7840#issuecomment-2124389044) is resolved.

**Comment by gigincg** [comment]
@JOSHIK27 Will you be able to work on this? #7840 Has been merged.

**Comment by JOSHIK27** [comment]
Yes I can.

**Comment by JOSHIK27** [comment]
> @JOSHIK27 Will you be able to work on this? #7840 Has been merged.

Yes I can. But the pr #7840 is still open. I have set up the project again, still it is using the older version of headless ui.

**Comment by gigincg** [comment]
@nihal467 Update here once HeadlessUI v2 is merged

**Comment by nihal467** [comment]
@gigincg the migration to headless v2 PR is still in not completed, so for proper triaging purpose assigning it to you

**Comment by nihal467** [comment]
@JOSHIK27 the headless UI is merged, 

cc: @gigincg

**Comment by JOSHIK27** [comment]
Here's the pr @nihal467 #8414
