### ISSUE TITLE
Scroll functionality is malfunctioning in the consultation form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7850]
**Describe the bug**

When we keep the mouse cursor in the white space for example the place where shown in the screenshot, the scroll wont work

**To Reproduce**

1. Go to patient edit consultation page
2. Place the cursor in the marked location
3. try to scroll

**Expected behavior**

It should be working as expected the functionality of scroll

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/8fe8665c-b2e2-40a2-8905-ad21c3f60ffd)

**Comment by AshrafMd-1** [comment]
@nihal467 i want to work on this issue can you assign me this
