### ISSUE TITLE
Enhance the treating doctor field in the consultation form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7854]
**Is your feature request related to a problem? Please describe.**

- When there is no home facility doctor available, the "treating doctor" column will not indicate this unless the user types something in the column.
- When an external contributor tries to interact with this field, it is not clear why there is no doctor available to select.

**Describe the solution you'd like**

- [ ] "When there is no home facility linked doctor available, grey out the field and display the text 'No home facility doctor is linked to this facility.' inside the field."

**Describe alternatives you've considered**

![image](https://github.com/coronasafe/care_fe/assets/57055998/73676009-79af-4a9b-84e5-499904b07c62)

**Comment by Jacobjeevan** [comment]
Mind assigning the issue to me? @nihal467 Thanks!

On an added note, some of the consultations are assigned to Dr. KUM sample user - so deselecting that would disable the field immediately since the user isn't a home facility doc. Would that be an issue?

**Comment by rithviknishad** [comment]
A simpler solution would be to show a notification when there are no home facility doctors available when the prefetch request completes. And maybe also modify the dropdown text to the following:

<img width="603" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/533053a0-f292-4acf-930f-0d71f03c611f">

**Comment by Jacobjeevan** [comment]
> A simpler solution would be to show a notification when there are no home facility doctors available when the prefetch request completes. And maybe also modify the dropdown text to the following:

To clarify, do you mean use the notification function with similar/same message in addition to changing the text under the drop down? Or just the latter?

**Comment by Jacobjeevan** [comment]
> > A simpler solution would be to show a notification when there are no home facility doctors available when the prefetch request completes. And maybe also modify the dropdown text to the following:
> 
> To clarify, do you mean use the notification function with similar/same message in addition to changing the text under the drop down? Or just the latter?

@rithviknishad Sorry about the ping, wanted some clarification.

**Comment by rithviknishad** [comment]
>To clarify, do you mean use the notification function with similar/same message in addition to changing the text under the drop down? Or just the latter?

We can do both!
