### ISSUE TITLE
Online Status of the Doctors and Nurses are not shown in Doctor Connect

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7859]
When the users(Doctor with Home Facility, Remote Doctor, Nurse - User types) are actively using CARE at instances the Online Status is not seen in the Doctor Connect. Instead the time after last Log-in is shown.

There's need to avail the ONLINE Status in the Doctor Connect so that it eases the user to Contact respective User without time leak.
Attaching the Supporting Image for work Ref.

![image](https://github.com/coronasafe/care_fe/assets/166367729/14d429d0-432b-4f07-8026-6c25ae6e8e29)

Color Coding-Green showing- ONLINE/Green Bold Dot Should help this

**Comment by Shelly011s** [comment]
@skks1212 Hello, I would love to contribute, can you please assign this issue to me?

**Comment by gayann-au** [comment]
Online Status Indicator also avoids multiple connection attempts from users to reach another, if it clearly signifies who is available Currently. This avoids time and Energy during Critical Care intervention
