### ISSUE TITLE
Avail the feature to Tag specific Specialist card with color Code to respective Specialist required Patients.

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7860]
As we click on the Patients Card, all admitted Patients are shown with Last updated details, Category, IP Days, Decision after the Consultation etc. Likewise there's a need to tag the Specific Specialist Card where that specialist Intervention is required to the Patients.

Suggested Change is Roughly edited and Shared Below for Understanding the mentioned request and for ref.
![image](https://github.com/coronasafe/care_fe/assets/166367729/927ac5b5-e6e4-4768-af62-363097206f60)

Also Suggesting few additional Specialization to be Incorporated into the dropdowns selections during data Entry by the user as follows:
General Medicine
Allergist/Immunologist
Anesthesiologist
Cardiologist
Cardiothoracic Surgeon
Dermatologist
Emergency Medicine Physician
Endocrinologist
Family Medicine Physician
Gastroenterologist
Geriatrician
Gynecologic Oncologist
Hematologist
Hepatologist
Infectious Disease Specialist
Intensivist/Critical Care Physician
Internist
Neonatologist
Nephrologist
Neurologist
Neurosurgeon
Obstetrician/Gynecologist (OB/GYN)
Oncologist
Ophthalmologist
Orthopedic Surgeon
Otolaryngologist (ENT)
Pain Management Specialist
Pathologist
Pediatrician
Pediatric Surgeon
Physiatrist (Physical Medicine and Rehabilitation)
Plastic Surgeon
Podiatrist
Preventive Medicine Specialist
Psychiatrist
Pulmonologist
Radiation Oncologist
Radiologist
Rheumatologist
Sleep Medicine Specialist
Sports Medicine Specialist
Thoracic Surgeon
Transplant Surgeon
Trauma Surgeon
Urologist
Vascular Surgeon

**Comment by shivankacker** [comment]
@gayann-au some doubts with the new skills

Is `Family Medicine Physician` and `Family Physician` the same skills?

Do we wish to rename the following already present skills?
- `Intensivist` to `Intensivist/Critical Care Physician`
- `Obstetrician and Gynecologist` to `Obstetrician/Gynecologist (OB/GYN)`

We already have `Thoraco-Vascular Surgeon`. Do we need to separate it into `Thoracic Surgeon` and `Vascular Surgeon` or treat them as new skills?

From the list you shared, I came up with the following new skills to be added

- Allergist/Immunologist
- Cardiothoracic Surgeon
- Gynecologic Oncologist
- Hepatologist
- Internist
- Neonatologist
- Pain Management Specialist
- Physiatrist (Physical Medicine and Rehabilitation)
- Podiatrist
- Preventive Medicine Specialist
- Radiation Oncologist
- Sleep Medicine Specialist
- Thoracic Surgeon
- Transplant Surgeon
- Trauma Surgeon
- Vascular Surgeon

Hope I didn't miss out something.

**Comment by NNSiri** [comment]
@skks1212 

Is Family Medicine Physician and Family Physician the same skills?
No please keep it as **Family Physician** 

Do we wish to rename the following already present skills?

Intensivist to Intensivist/Critical Care Physician - **No**
Obstetrician and Gynecologist to Obstetrician/Gynecologist (OB/GYN) - **Yes**
We already have Thoraco-Vascular Surgeon. Do we need to separate it into Thoracic Surgeon and Vascular Surgeon or treat them as new skills?
**The new updated domains are
Cardio Thoracic Surgeon
Vascular Surgeon**

**Comment by shivankacker** [comment]
@aparnacoronasafe need your inputs here

cc. @gigincg

**Comment by gigincg** [comment]
@skks1212 Can you specify what you need clarification on? It would be good to share the existing list of Skill as well. We can decide on what migrations are required as well.

**Comment by shivankacker** [comment]
@gigincg We need inputs regarding the new badge that is requested, as we currently just have an option to request for a specialist, but not what kind. So do we update that field to accommodate the skill of the requested physician, and should it allow for multiple skill requirements or just one?

Here is how the new skills look like https://github.com/coronasafe/care/pull/2302

    (1, "General Medicine"),
    (2, "Pulmonology"),
    (3, "Intensivist"),
    (4, "Pediatrician"),
    (5, "Others"),
    (6, "Anesthesiologist"),
    (7, "Cardiac Surgeon"),
    (8, "Cardiologist"),
    (9, "Dentist"),
    (10, "Dermatologist"),
    (11, "Diabetologist"),
    (12, "Emergency Medicine Physician"),
    (13, "Endocrinologist"),
    (14, "Family Physician"),
    (15, "Gastroenterologist"),
    (16, "General Surgeon"),
    (17, "Geriatrician"),
    (18, "Hematologist"),
    (29, "Immunologist"),
    (20, "Infectious Disease Specialist"),
    (21, "MBBS doctor"),
    (22, "Medical Officer"),
    (23, "Nephrologist"),
    (24, "Neuro Surgeon"),
    (25, "Neurologist"),
    (26, "Obstetrician/Gynecologist (OB/GYN)"),
    (27, "Oncologist"),
    (28, "Oncology Surgeon"),
    (29, "Ophthalmologist"),
    (30, "Oral and Maxillofacial Surgeon"),
    (31, "Orthopedic"),
    (32, "Orthopedic Surgeon"),
    (33, "Otolaryngologist (ENT)"),
    (34, "Palliative care Physician"),
    (35, "Pathologist"),
    (36, "Pediatric Surgeon"),
    (37, "Physician"),
    (38, "Plastic Surgeon"),
    (39, "Psychiatrist"),
    (40, "Pulmonologist"),
    (41, "Radio technician"),
    (42, "Radiologist"),
    (43, "Rheumatologist"),
    (44, "Sports Medicine Specialist"),
    (45, "Thoraco-Vascular Surgeon"),
    (46, "Transfusion Medicine Specialist"),
    (47, "Urologist"),
    (48, "Nurse"),
    (49, "Allergist/Immunologist"),
    (50, "Cardiothoracic Surgeon"),
    (51, "Gynecologic Oncologist"),
    (52, "Hepatologist"),
    (53, "Internist"),
    (54, "Neonatologist"),
    (55, "Pain Management Specialist"),
    (56, "Physiatrist (Physical Medicine and Rehabilitation)"),
    (57, "Podiatrist"),
    (58, "Preventive Medicine Specialist"),
    (59, "Radiation Oncologist"),
    (60, "Sleep Medicine Specialist"),
    (61, "Transplant Surgeon"),
    (62, "Trauma Surgeon"),
    (63, "Vascular Surgeon"),
    (64, "Critical Care Physician"),

**Comment by gigincg** [comment]
@gayann-au Closing the issue, as the Backend changes have been made, this should be available in 2 weeks, in the next release
