### ISSUE TITLE
Cleaning up Nav Menu

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7866]
**Is your feature request related to a problem? Please describe.**
The navigation menu has many modules listed that are not currently being used. The menu looks cluttered with so many options.

**Describe the solution you'd like**
Edit the list to show only the modules that are being used, and hide the remaining in a collapsable "More" section. User must be exposed with the options within "More" only when it is clicked on.

The Options on Nav bar must be in the below order:
- Facilities
- Patients
- Shifting
- Assets
- Users
- Notice board
- Notifications
- More: Sample test, resource, external results.

**Comment by AshrafMd-1** [comment]
@aparnacoronasafe this has already been addressed in https://github.com/coronasafe/care_fe/issues/6920

**Comment by gigincg** [comment]
Closing Duplicate Issue
