### ISSUE TITLE
Watermarks for camera feed

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7872]
**Is your feature request related to a problem? Please describe.**
The camera live feed on CARE transmits video feed of patients in ICU. This is an extremely sensitive feed and all measures must be taken to ensure that it is not misused. 

**Describe the solution you'd like**
Adding watermarks to the feed revealing the username of user accessing the feed would force more accountability on the part of the user to make sure that no screenshot is taken and misused. 

However, it is important to ensure that such watermarks doesnt obstruct view of the doctor in actually monitoring the patient to provide expert opinion.

The suggested design for the watermark is as follows:
PLACEMENT: when the feed is divided into three both horizontally and vertically, place the watermarks near the intersection of the lines as suggested in the image below.
COLOUR: give me a colour that does not stand out too much to distract the doctors from properly using the video feed. Grey is an ideal colour.
OPACITY: keep the watermark at 50-70% opacity.
<img width="1168" alt="Screenshot 2023-10-10 at 6 04 34 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/8a4b8846-728f-468f-b10a-a5fa16759d9b">

<img width="1193" alt="Screenshot 2023-10-10 at 6 36 43 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/65d86954-f5bd-4fbf-99d2-4adf16af8c92">

<img width="1191" alt="Screenshot 2023-10-10 at 6 36 55 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/cc0fdcc0-a3df-4b71-ad8f-9167d390b698">

It is good to create a mock-up first and present it in the EOD before building it out. 

**Describe alternatives you've considered**

**Additional context**

**Comment by rithviknishad** [comment]
We'll also need to disable right clicks on the video player as the context menu has options to the following options where we cannot place watermark.

1. play in picture-in-picture mode
2. cast
3. save video frame as image

<img width="1703" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/6c7efdd2-0d41-4780-a802-069cb62ed0ea">

**Comment by aparnacoronasafe** [comment]
@rithviknishad 

Please improve the watermarks. 

- [x] I think placing 2 watermarks should be enough. 4 seems a bit excessive right now. 
![Screenshot 2024-05-29 at 12 46 49 PM](https://github.com/coronasafe/care_fe/assets/67050716/3a105161-bc9b-4260-8072-f9b0d2bc13d7)
Would you consider removing the ones marked in red?

- [x] Size of the watermark doesnt respond to display size. This needs to be fixed.
![Screenshot 2024-05-29 at 12 44 14 PM](https://github.com/coronasafe/care_fe/assets/67050716/1ce934cc-87a5-4caf-ac4e-35759dc3b156)
Screenshot from a smaller phone screen. Please ensure the size of the watermark decreases with screen size.
