### ISSUE TITLE
Login-in page is clipping in

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7890]
**Describe the bug**

On the responsive view , the login page text is clipping in

**To Reproduce**

1. Go to care.ohc.in
2. select any other languages
3. switch to mobile view

**Expected behavior**

in mobile view, it should be properly responsive, irrespective of which language the user select's

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/b8989408-a698-4df8-9897-3f4fe8279c2d)

**Comment by sunny-thakurwar** [comment]
@nihal467 i checked issue on staging the text is not getting clipped on mobile. are u using text-5xl

<img width="1138" alt="image" src="https://github.com/coronasafe/care_fe/assets/87633236/71f5cc5a-f601-40fc-8935-f3ffa670efb9">
