### ISSUE TITLE
Add padding in the user tab for "No user found"

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7894]
**Describe the bug**

When there is no user found in the user tab, text is shown without a padding

**To Reproduce**

1. Go to user tab
2. filter the data with no match
3. See error

**Expected behavior**

Add white padding and show the "No user found" text similar to the no sample file card similar to below screenshot

![image](https://github.com/coronasafe/care_fe/assets/57055998/172fb4d0-0d69-410a-b7fa-29e180c40afa)

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/3558afd9-5423-47b7-990c-7b12ac06ed6c)

**Comment by Aryanshu919** [comment]
I would like to work on this issue. Could you assign it to me?
