### ISSUE TITLE
Hide skills already linked to the user

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7901]
**Describe the bug**

When we link a skill to a user and the dropdown list shows the already linked skill, an error is thrown if the user selects it again and submits it

**To Reproduce**

1. Go to user tab
2. try to link a skill, which is already linked to the user
3. See error

**Expected behavior**

Hid the already linked skill in the skills dropdown

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/f315f847-8548-4fe8-b1e4-80fa0f07ca59)

**Comment by AshrafMd-1** [comment]
@nihal467 I want to work on this issue can you assign me this issue
