### ISSUE TITLE
Uploaded Files are  default Zoomed in when opened

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7911]
All the files are default Zoomed in when the files are opened after files are selected and uploaded from the device. This has to be resolved to make the use of  preview ease in the files.
 Screen recording is attached below for ref.
 

https://github.com/coronasafe/care_fe/assets/166367729/13a0c56b-209d-4014-bef6-c27c28c39e63

**Comment by Ashutosh0602** [comment]
@gayann-au I would like to work on this issue. Please assign me

**Comment by Ashutosh0602** [comment]
Is this issue still open?
