### ISSUE TITLE
Enhancement to the Patient consent

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7921]
- [ ] Modify the backend based on the discussion on 27/05/2024
- [ ] Show the Created by and archived by details along with the file
- [ ] When all existing file are archived and no active file is present for the patient, show the badge "Consent File Missing " badge in the patient consultation page, currently it is only show when there is no file present in active and archive together

**Comment by shivankacker** [comment]
Awaiting discussion on https://docs-git-fork-skks1212-cep-consent-restructure-ohcnetwork.vercel.app/docs/care/CEP/consent-restructure
