### ISSUE TITLE
Hide "Refer to another facility" and "Declare Death" in the edit consultation

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7939]
**Describe the bug**

When a user creates a patient record as admitted and later edits the consultation, selecting the decision as "Refer to another facility," then without completing the shifting patient flow, they cancel it. Now, keeping the decision as "Refer to another facility," the origin facility staff tries to discharge the patient from the origin facility with the reason "Recovered," which causes a data integrity issue.

**To Reproduce**

**Expected behavior**

- [ ] Hide "Declare Death" and "Refer to Another Facility" in the edit consultation, since they are having specific flow users can use in the discharge reason pop-up

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/b2f77b84-9645-4f48-92e8-c978a263a9d4)

**Comment by aparnacoronasafe** [comment]
Agreed. Please go ahead
