### ISSUE TITLE
Enable relevant Dropdowns to select File Names

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7942]
Availing the feature of relevant dropdowns to select file names while uploading the file in 'Files' should help the users to assign the names to the picture or Files what uploading.
This helps to preview to required files in the lists without searching for among all files if the name of file is inappropriately named.

attaching the illustration to understand how the file names are usually mentioned

![image](https://github.com/coronasafe/care_fe/assets/166367729/8db5dee4-888c-45f0-908e-e9d5f0d4316d)
  In the above Image, files names are default fetched from the device while uploading, if the Doctor wants to search X-Ray report amongst the uploaded file he/she needs to search whole set of Uploaded file rather than searching particular file which constitutes in time and energy consumption.
  
  If we avail the dropdowns with Relevant/most or standardly used file names user can select required while uploading the file which avoids confusions and Duplications.

**Comment by Shelly011s** [comment]
@gayann-au @rithviknishad  Hey, I am new to this project but I am really interested to contribute. Can you give an overview of the implementation and assign the issue to me?

**Comment by shivankacker** [comment]
@gayann-au can you provide with a list of file names you would like to see in the dropdown?

**Comment by gayann-au** [comment]
Admission Records:
Patient's personal information
Admission date and time
Reason for admission

Medical History:
Past medical conditions
Surgical history
Family medical history
Medication history
Allergies

Progress Notes:
Daily updates by physicians, nurses, and other healthcare providers
Changes in patient’s condition
Responses to treatment

Diagnostic Reports:
Laboratory test results (blood tests, urinalysis, etc.)
Imaging reports (X-rays, CT scans, MRIs)
Biopsy and pathology reports
Electrocardiograms (ECGs)
Other diagnostic tests (EEGs, pulmonary function tests, etc.)

Treatment Records:
Medication administration records (MAR)
Details of procedures and surgeries
Treatment plans and progress
Physical therapy records

Operative Reports:
Pre-operative assessments
Surgical procedure details
Post-operative recovery

Consultation Reports:
Opinions and recommendations from specialists

Discharge Summary:
Condition at discharge
Discharge instructions
Follow-up care recommendations

@aparnacoronasafe I've Suggested few listed in the field. Please Comment for this

**Comment by aparnacoronasafe** [comment]
Creating an exhaustive list of all possible types of file uploads is difficult. 

Alternative:

When user uploads file, DONOT fetch the file name and autopopulate the file name in CARE. Mandate the user to manually type out a file name. 

@nihal467 @gayann-au

**Comment by shivankacker** [comment]
@aparnacoronasafe in our current system, files that are uploaded from device will have their name autofilled with the name of the file on device. The user can change the file name before they upload it. Camera captures and audio captures need to be named manually.

![image](https://github.com/user-attachments/assets/10fe566a-88a3-4981-a5ec-2d75c997fe86)

Do you want me to remove the autofill for the name when uploaded from device?

cc. @gigincg

**Comment by aparnacoronasafe** [comment]
@shivankacker 

Yes. please remove autofill.

We see a lot of users forgetting to remove the autofilled name to add a more appropriate name. To enforce the behaviour of making users add appropriate names to the files, we want to remove auto-filling of names whenever file upload is used. This includes when file is attached from device (desktop/phone) or when image is uploaded straight from camera.
