### ISSUE TITLE
Avail 'Edited' tag to Manipulated data

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7943]
Enable the 'Edited' tag to any edited data in Patient dashboard once after the data is entered and that patient card opened more than once.
Use-case: Availing 'Edited' Tag to manipulated Patient data avoids the discrepancies of opinions amongst the clinicians while reviewing the patient Data.
For illustration: If the Patient is admitted in CARE and initially diagnosis are mentioned as COPD(Confirmed) and aftermath Remote specialist reviews the case and puts his/her treatment plans to COPD. After a moment, If COPD is changed to Tuberculosis, the treatment plan doesn't make any sense and there might come probe to understand the reason for Remote specialist to file irrelevant treatment(which is initially mentioned for COPD) plan for Tuberculosis.
In the Concern of avoiding this discrepancies, 'Edited' tag to all manipulated data points should help in understanding spoke and remote users.

**Comment by gigincg** [comment]
@gayann-au 
![image](https://github.com/user-attachments/assets/1210d31b-5393-40fd-916c-9910d1575d8b)


Doesn't the option to mark as "Added by Error" solve this issue?

**Comment by gigincg** [comment]
Marking as "Remove as Entered in error" Is not viewable in the Diagnosis View:
![image](https://github.com/user-attachments/assets/0cfec514-52ed-42ec-b572-10756c22d765)

Edit View:
![image](https://github.com/user-attachments/assets/36b69b98-5570-4f27-9907-b31b4c64f525)

Showing an "Edited" or some other label when there is a Deleted/Currently Hidden Diagnosis seems like a good feature to have. 

cc: @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
- [ ] All diagnosis, even the once removed must be listed in the expanded diagnosis card on patient dashboard. Removed diagnoses should appear at the bottom of the list, displayed in grey with a strikethrough, and labeled with either ‘(entered in error)’ or ‘(refuted),’ as applicable.
- [ ] When a change to the diagnosis is made, it must appear in events module. It must appear as <username> updated diagnosis. " <ICD_11 item> marked as "unconfirmed diagnosis" changed to "removed as entered in error"

**Comment by nihal467** [comment]
not a requirement based on the current develop
