### ISSUE TITLE
Map Modified Patient category in shifting detail page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7948]
**Describe the bug**

the patient category detail in the shifting detail page is missing

**To Reproduce**

**Expected behavior**

Implement the modified patient category in the shifting detail page

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/f71b9ed4-dbd9-4197-a17c-2179f07ba324)

**Comment by rithviknishad** [comment]
Closing as not planned as patient category is a mandatory field and this issue is only for very old data.

cc: @nihal467
