### ISSUE TITLE
Doctor's Log Update-  Progress Note and other improvements

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7961]
**Is your feature request related to a problem? Please describe.**
Doctor's Log update needs to be called Progress Note and the experience of doctors and nurses to log updates must be improved.

**Describe the solution you'd like**

- [x] Rename "Doctor's Log update" to "Progress Note"
- [x] For "Nurse" usertype- Hide the Doctor's Log Update (Progress note) "Round Type" in Log updates
- [x] For Doctor Usertype, replace "+Log update" button on Patient dashboard with "File Note"- when clicked, "Progress notes" must open up as the default round type.  
- [x] Hide the discontinued prescription list, give user option to expand and view the list
- [x] Hide "Administer" button from prescription list on Progress note

**Comment by nihal467** [comment]
@rithviknishad allow the staff, doctor and admin users to view "progress note" , confirmed with aparna over a call
