### ISSUE TITLE
Patient categorisation- add definitions

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7962]
**Is your feature request related to a problem? Please describe.**
CARE provides options for users to categorise patients as "Comfort care/ Mild/Moderate/Critical". However, there is no definition for this categorisation and users may use it subjectively. 

Providing more definitions would help bring about more standardisation in the way this categorisation is utilised.

**Describe the solution you'd like**

- [ ] Only for patients admitted, the dropdown for patient category in consultation form, edit consultation form and log update form must also have the definitions for these categories in fine text.

Mild (Urgent: not life-threatening)
Moderate (Emergency: could be life-threatening)
Critical (Immediate: life-threatening)

Make this fine text visible in the dropdown itself

- [ ] We are discontinuing "Comfort care" as a category and introducing "Actively Dying" as the 4th category. In the dropdowns, hide "comfort care" and add the new category "Actively dying". All previous records with comfort care classification will stay as is. In future medical records, the only option for category must be Mild, Moderate, Critical and Actively dying.

**Comment by nihal467** [comment]
![image](https://github.com/coronasafe/care_fe/assets/57055998/a8ee0ec8-25f3-4f07-a89f-fb26764c3bc6)

- When we are filing a new consultation, the category is filled first and later only, we will be allocating a bed, so based on a bed category, if we are showing the fine text, it might not work properly during create consultation. @aparnacoronasafe can you share your view on this

**Comment by aparnacoronasafe** [comment]
Place patient category below IP no.

**Comment by gigincg** [comment]
@aparnacoronasafe Having descriptions only when it's ICU patients seems inconsistent.

Can you suggest descriptions for non-ICU patients too? Would that be the same or different?

**Comment by shivankacker** [comment]
@aparnacoronasafe The issue is blocked pending your clarification. Please clarify so that this can go into the next release.

**Comment by aparnacoronasafe** [comment]
@gigincg I got confirmation that the categorisation holds good for all hospitalised patients. 

Edited the issue.

**Comment by gigincg** [comment]
@skks1212 Can you take this forward?

**Comment by shivankacker** [comment]
@aparnacoronasafe thanks for the clarification, I'll update the PR accordingly

**Comment by nihal467** [comment]
@aparnacoronasafe 
1. can you specify the operational reason, why we hiding and discontinuing comfort care option
2. what is the fine text required for the category "Actively Dying"

@gigincg @aparnacoronasafe Had a doubt, As per issue, we are going to keep all existing data as comfort care itself without migration and hide the comfort care patient category from the frontend from now on. If someone pulls analytics of patient categories for one year after six months from now, won't they see a decline in comfort care patients count and one more that is that they will be seeing data for an option that is no longer available on the frontend. Will this cause a problem for someone who is primarily checking analytics and not interacting directly with the platform alot?

CC: @gigincg @skks1212

**Comment by aparnacoronasafe** [comment]
The reason why we need to classify patient as "mild moderate critical" is for the obvious need to understand what degree of care is provided to patients admitted. Having a 4th category for "actively dying" is important to understand the number of patients admitted, where the goal for healthcare providers is not to treat the patient to recovery but to provide the patient care so the patient can have a comfortable death. 

Having this classification is patients in important to make sense of patient outcomes. Where ever you have higher % of actively dying patients, % of expired in outcome will also be high. 

Earlier we were using the term "comfort care" for the classification. However using comfort care is not correct here because it is a wider term that may include patients actively dying or other patients that may be suffering from a disease like a viral infection that may not have any active treatment options. Some of such patients may recover. Hence the definition is "comfort care" is too wide. "Actively dying" is defined very specifically as patients that are dying. 

For analytics we will have 5 categories 
Mild
Moderate
Critical
Comfort care
Actively dying. 

2- there is no fine text required for actively dying. The term is self explanatory

**Comment by bodhish** [comment]
@aparnacoronasafe I had a word with @athulmaunel and he is of the option that the descriptions are quite confusing. 

Even for me it was super confusing.

**Comment by bodhish** [comment]
<img width="664" alt="image" src="https://github.com/user-attachments/assets/7b3cd48a-c0f2-4d1e-a2de-563670ca2423">
