### ISSUE TITLE
Auto capture vitals from 5-para (wherever integration with 5-para monitor is deployed)

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7963]
**Is your feature request related to a problem? Please describe.**
The vitals of a patient are captured in Log update form. Wherever 5-para integration is available, this vitals can be auto-fetched rather than forcing users to type in manually. 

**Describe the solution you'd like**
Auto fill vitals fields with data from 5-para integration when log update form is opened. 
Please note that the data is only autofilled into the form, and not auto-saved. the user may choose to remove/update it.

**Describe alternatives you've considered**

**Additional context**

**Comment by Ashutosh0602** [comment]
<img width="826" alt="image" src="https://github.com/coronasafe/care_fe/assets/85889617/baf0faad-0757-4b28-9f75-f219a98c07a6">

Okay what I understand that in the above all vitals data should get prefilled if already some data are present like in below image

<img width="1187" alt="image" src="https://github.com/coronasafe/care_fe/assets/85889617/e7ca8f6b-f025-4a9e-9394-4fd3bf8f0b35">

**Comment by Ashutosh0602** [comment]
If I understand the issue right, please assign me.

**Comment by Ashutosh0602** [comment]
Is this issue still open to work?

**Comment by awaiskhan21** [comment]
Hi @rithviknishad @aparnacoronasafe if this issue is still open i would love to work on this, please assign me!!

**Comment by Utkarsh-Anandani** [comment]
Hii @gigincg @rithviknishad can you assign the issue to me?
As I understood, the issue is regarding autofilling of vitals value, correct me if I'm wrong.

**Comment by nihal467** [comment]
not a requirement based on the current develop
