### ISSUE TITLE
Maintain aspect ratio for Bed Icon in Patient Dashboard

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#7971]
The Box that shows the Bed of the Patient in the Patient Dashboard gets deformed in different screens and with different data. It would be better for it to always remain square

![image](https://github.com/coronasafe/care_fe/assets/13028584/0af51a55-b07e-4e84-a092-42e7eb499031)

**Comment by Ashutosh0602** [comment]
@gigincg I would like to work on this issue can you please assign me.

**Comment by Sulochan-khadka** [comment]
Before:
<img width="1431" alt="Screenshot 2024-06-11 at 8 42 52 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/af5e4bea-fb35-4100-a811-a41299ef90f6">


After:
<img width="1431" alt="Screenshot 2024-06-11 at 8 43 04 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/227cfa37-b193-4a5f-b13b-550280458976">


Let me know if something else is required... (May be some small UI changes).
