### ISSUE TITLE
flag on patient live encounter with no consent for admission

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7972]
Live Encounters , marked as admitted must have at least 1 consent for admission filed.

Wherever that is not the case,

- [ ] Have flag in red appear on live patient list (add a blinker to the flag: eg: look at flag for no consultation filed)
- [ ] Add flag to patient dashboard

Good to have:

- [ ] On live patient list, Add a card citing "24 patients admitted without consent" on top in red. When clicked only the patient files with no consultation must appear. It must applied as a filter. user to have option to remove the filter by closing the filter flag

**Comment by shivankacker** [comment]
Waiting for [7946](https://github.com/coronasafe/care_fe/pull/7946) to get merged before working on this
