### ISSUE TITLE
Create a new useInfiniteQuery hook to handle paginated queries independently

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#7985]
_Originally posted by @skks1212 in https://github.com/coronasafe/care_fe/pull/7946#discussion_r1629078169_

The new useInfiniteQuery hook would work like useQuery, but will contain utils to work with multiple pages.

The new hook should replace queries where we are fetching 1000 records as a hack

cc. @khavinshankar @rithviknishad

**Comment by rithviknishad** [comment]
we are now using tanstack query
