### ISSUE TITLE
Allow creation of duplicate symptoms if cure date is present

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8002]
**Describe the bug**

Currently, the symptoms dropdown shows symptoms that are already added to the list, which can create a duplicate record for the same symptoms

**To Reproduce**

1. Go to create consultation
2. add a symptoms and search for the same in the list
3. See error

**Expected behavior**

hide already added symptoms from the dropdown

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/9d6663b5-d818-4cf9-85b7-874eaac68bc5)

**Comment by rithviknishad** [comment]
@nihal467 this is expected behaviour if the existing symptom is already cured (has cure date). So that the same symptom can be started with a new onset date.

<img width="913" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/cf2dace2-3a5c-4e4e-8d9a-59d6fa412a59">

**Comment by nihal467** [comment]
![image](https://github.com/coronasafe/care_fe/assets/57055998/0b7118a5-922c-463e-8baa-efd211df24af)

- [ ] In the frontend, when a symptom is marked as cured, the same symptom can be added again to the list while creating a consultation. This will throw an error: "Create symptoms - duplicate symptoms are not allowed," since the backend only checks if all symptoms are unique or not.

@aparnacoronasafe 
1. should we allow user to input date of cure while creating a consultation
2. once a date of cure is added, should we allow user to add a existing symptoms with cure date to the same list during create consultation

**Comment by aparnacoronasafe** [comment]
1. Yes. While creating consultation say on 1st June, they may want to note that the patient has symptom XYZ from 20-30th May. 

2. Yes. In the above eg, the user may want to add symptom xyz from 20-30th May, and then again same symptom from 31st May to 2nd June, Or 31st May - ongoing with no cure date

**Comment by rithviknishad** [comment]
Update: waiting for backend review from @vigneshhari
