### ISSUE TITLE
TypeError in NotificationsList Component on Service Worker Subscription Fetch

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care_fe#8006]
## Summary
A TypeError occurred within the NotificationsList component of our application, specifically during the execution of the initialSubscriptionState function. This error impacts users on the Chrome Mobile iOS browser, as seen in a recent log from our production environment.

## Description
When the function initialSubscriptionState tries to fetch the subscription status from the service worker, it fails because the subscription object returned by pushManager.getSubscription() is unexpectedly undefined. This indicates that the service worker might not be properly initialized or the pushManager is not available in the current browser context at the time of invocation.

## Steps to Reproduce
- Open the application using any device.
- Navigate to the Notifications area of the application.
- The error occurs during the loading process of this component.

## Expected Behavior
The application should safely check for the availability of the service worker and gracefully handle cases where the push manager's subscription object is undefined.

## Actual Behavior
The application encounters a TypeError and may impact the user experience by halting subsequent JavaScript execution, potentially leading to a partially rendered or non-responsive page.

**Comment by yanurag-dev** [comment]
@khavinshankar 

Hey, I would like to fix this issue. Please assign it to me.

**Comment by gigincg** [comment]
@Yadavanurag13 The issue had been assigned to you, not sure if you missed the assignment.

**Comment by yanurag-dev** [comment]
@gigincg Sorry, I forgot to mention this in our previous chat. I removed my assignment 3 weeks earlier.

**Comment by vishwansh01** [comment]
Hey ! @bodhish 
I just created a pull request related to the issue : https://github.com/ohcnetwork/care_fe/pull/8686
