### ISSUE TITLE
TypeError: s.map is not a function in InvestigationBuilder component

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care_fe#8008]
An error was encountered in the `InvestigationBuilder` component causing the JavaScript TypeError: `s.map is not a function`. This error is likely due to attempting to call `.map()` on a variable `s` that is not properly initialized as an array before this method call.

#### Error Details
- **File**: `InvestigationBuilder.tsx`
- **Function**: `InvestigationBuilder`
- **Error Message**: `TypeError: s.map is not a function`
- **Sentry Event ID**: `3533b1853bd646609326b51cf152345a`

#### Steps to Reproduce:
1. Navigate to the URL: `https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/19adff46-588e-4072-89b3-a23ec1dec5fa/consultation/cc5ec4c3-94af-4fec-a954-fb9b7c45b89e/daily-rounds`
2. Error triggers when the component attempts to render based on fetched data that presumably includes an incorrectly formatted `s` variable.

#### Potential Cause:
The variable `s` might be either `undefined` or not an array at the time `.map()` is called. This could be due to a failure in data fetching or data transformation before passing it to the `InvestigationBuilder`.

#### Suggested Fix:
- Ensure `s` is always initialized as an array.
- Add error handling to check the type of `s` before applying array-specific methods like `.map()`.

This issue has occurred in a staging environment, so it's crucial to address it before the next production deployment to prevent user-facing errors and potential disruptions in service.

**Comment by yanurag-dev** [comment]
@khavinshankar Hey, I would like to fix this issue. Please assign it to me.

**Comment by yanurag-dev** [comment]
I used the optional chaining method to avoid errors, but it ended up causing more issues.
?.map

"Could you please clarify if 'is s' is referring to investigations?"

**Comment by Nithin9585** [comment]
hi @rithviknishad ,can you  please assign  this issue to me!.
