### ISSUE TITLE
Handle Users skill fetching in patient consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8027]
**Describe the bug**

When a doctor is not linked to a facility anymore, and we try to open any old consultation treated by the doctor, the patient consultation page will throw no user matches the given query error message in the frontend since the page try to fetch the doctors skill details.

**To Reproduce**

1. Go to patient consultation page of a discharged patient
2. unlink the related doctor from the facility
3. refresh the page

Note: The doctor id should have some skills linked to the user

**Expected behavior**

- [ ] remove the queryset filters for user details and userskill apis

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/dfe1d2fc-4b04-4e2a-b9c8-bdf587b0c852)

Solution:
Instead of making an api call to get user details, serilaize the user skill details on the consultation__treating_physician object

**Comment by gigincg** [comment]
@sainak This seems like a good first issue, can you add a few lines for implementation detail, and mark as good first issue

**Comment by Indrajeety993648** [comment]
@rithviknishad , I would  like to  work  on this issue if no one working on it , Please assign it to me

**Comment by Sulochan-khadka** [comment]
I am unable to reproduce the error. Am i doing something wrong? @rithviknishad @nihal467 
https://github.com/user-attachments/assets/9bee7eba-269b-4a7e-b2b7-c399beb9a5a2

**Comment by nihal467** [comment]
@Sulochan-khadka i have modified the issue, you need to make sure that, the doctor id you are using have some skills linked to the users

steps to add skills to the user:

1. go to the user tab
2. search for the user id
3. click on linked skills buttons
4. add any random skills

post that try the steps you done , you should be able to replicate the bug

**Comment by JavidSumra** [comment]
Is there any one working on this issue?

**Comment by SwanandBhuskute** [comment]
Is this issue still valid? if yes, would like to solve it @nihal467

**Comment by SwanandBhuskute** [comment]
@nihal467 I am unable to see the error

I went to DIscharged , then , Gayan's Hospital, then Gururaj, then his consultations, then I see doctor Sriharsh Gampa
then in user management, I added few skills to him and unlink Gampa from gayan hospital, come back to consultaion page , but still the Sriharsh Gampa doctor is visible along with his skills
![Image](https://github.com/user-attachments/assets/603b41b0-a22a-4880-9c5d-5938b565d5ca)
![Image](https://github.com/user-attachments/assets/79892f38-4af9-41cf-96cd-5d4335daaf0c)
![Image](https://github.com/user-attachments/assets/f869acd5-3339-42e8-a8e0-abb59f7917fa)

same for 1 2 more discharged patients
(discharged - gayan - ramesh - devdeep doctor)

can you give more clarity?

**Comment by nihal467** [comment]
@SwanandBhuskute the issue seem to be resolved, feel free to assign new open issues
