### ISSUE TITLE
Modify the IP/OP number in the facility specific discharge patient card

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8028]
**Describe the bug**

On the discharge patient page, we are showing the IP/OP number, but in an edge case, it is failing:

- [ ] Case 1: If a patient is discharged from Facility A with IP number 1/24 and then admitted to Facility B with a new IP number 2/2024, the IP/OP number on the patient card in the facility-specific discharge page of Facility A also gets modified based on the new IP/OP number from Facility B. [this is effecting the search by IP/OP number as well as the card]

- [ ] Case 2: On the discharge page, we are currently showing IP/OP numbers in the search results based only on the last consultation. If I want to search for the IP/OP number of a patient who has been re-admitted five times in the same facility, only the latest consultation is considered, and older consultations in the same facility are not taken into account.

**To Reproduce**

1. Go to facility detail page
2. Click on view discharge patient button
3. search with the IP no

**Expected behavior**

- [ ] we need to return last consultation for unique patient which matches the given filters  

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/593bcbc1-e157-479a-86a6-8146398c06c4)

**Comment by SwanandBhuskute** [comment]
If this issue is still valid , I would like to work on it @nihal467

**Comment by SwanandBhuskute** [comment]
> If this issue is still valid , I would like to work on it [@nihal467](https://github.com/nihal467)

pls assign me this issue @nihal467

**Comment by SwanandBhuskute** [comment]
Is this still a valid issue? @nihal467 @rithviknishad @gigincg

**Comment by SwanandBhuskute** [comment]
@nihal467 @rithviknishad @gigincg 
Because lets say a patient has 2 consultations
Consultation A - IP-56
Consultation B - IP-57 (latest)

only for display purpose, we show latest IP/OP number
so now only IP-57 is displayed in the card, 

so when I search for 56, I don't get to see the patient, this is not expected right?
I should be able to see the patient based on any of his IP/OP number?

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.

**Comment by SwanandBhuskute** [comment]
@nihal467 i would like to work on this , pls assign me

**Comment by rajku-dev** [comment]
@SwanandBhuskute are you working on this issue?

**Comment by nihal467** [comment]
not a requirement based on the current develop
