### ISSUE TITLE
Modify non-admin users access to the patient consultation record

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8029]
**Describe the bug**

Once a patient is discharged from a facility, the non-admin users of the facility, can view the details page and see the card of the consultation specific to their facility, but when they try to view the consultation detail page, they are taken to a 404 page

**To Reproduce**

**Expected behavior**

Refer the mentioned conversation for final behavior
(https://github.com/ohcnetwork/care_fe/pull/8727#issuecomment-2472832743)

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/925007b1-bc4f-488b-a117-151780ef3f63)
![image](https://github.com/coronasafe/care_fe/assets/57055998/48c2fe59-4d3b-42d1-83cd-4d3c1f61fdb1)

**Comment by aparnacoronasafe** [comment]
@nihal467 staff at hospital should be able to view all previous records from the facility (all facilities they have access to).

The staff should NOT be able to open and view history from any facility that they currently do not have access to.

**Comment by gigincg** [comment]
Given the access control is already working fine, just disabling the button based on the conditions should solve this

**Comment by Waheedsys** [comment]
hi @nihal467  i would like to try to work on this can you please assign it to me

**Comment by Sulochan-khadka** [comment]
> Given the access control is already working fine, just disabling the button based on the conditions should solve this

What about the "View/Upload Consultation Files" button? Should that button also be disabled for staff? It seems fine in the dev env though. Where is the issue?

**Comment by AdityaJ2305** [comment]
Hey @nihal467, I’d like to work on this issue. Could you please assign it to me and clarify the final expected behaviour?

**Comment by nihal467** [comment]
@Sulochan-khadka unassigning you from the issue due to inactivity, @AdityaJ2305 are you still interested in working on this issue

**Comment by noufalrahim** [comment]
@nihal467 can I work on this..? Can u assign me..

**Comment by Sulochan-khadka** [comment]
> @Sulochan-khadka unassigning you from the issue due to inactivity, @AdityaJ2305 are you still interested in working on this issue

I became inactive because  was unsure what was the conclusion of the discussion on the PR. Kindly clarify and will submit within 24, hrs.

**Comment by AdityaJ2305** [comment]
> [@Sulochan-khadka](https://github.com/Sulochan-khadka) unassigning you from the issue due to inactivity, [@AdityaJ2305](https://github.com/AdityaJ2305) are you still interested in working on this issue

Yes, but I think @Sulochan-khadka got this already

**Comment by gurramkarthiknetha** [comment]
@Sulochan-khadka can I work on this..? Can u assign me..

**Comment by Sulochan-khadka** [comment]
@nihal467 what is the access level of 
"WardAdmin" , "LocalBodyAdmin" , "DistrictLabAdmin" , "DistrictReadOnlyAdmin" , "StateLabAdmin" , "StateReadOnlyAdmin" , "StateAdmin" ?

As per the discussion we had in the previous PR, DistrictAdmin has complete access regardless of the permitted facilities. How about the other Admins stated above?

Also since the requirement was changed from disabling button to giving error, should the "Add consultation updates " remain disabled for discharged patient?

Suggestions for the error message? ![Image](https://github.com/user-attachments/assets/8bd79ffd-8f0d-403f-9821-462927a2a79b)

**Comment by Sulochan-khadka** [comment]
@nihal467 @rithviknishad could you kindly let me know the outcome of the PR? i hope to close this in 24 hrs. Also , would be great if you may answer the above asked questions...

**Comment by rithviknishad** [comment]
Already mentioned in issue comment: https://github.com/ohcnetwork/care_fe/pull/8727#issuecomment-2472832743

**Comment by Sulochan-khadka** [comment]
> Already mentioned in issue comment: [#8727 (comment)](https://github.com/ohcnetwork/care_fe/pull/8727#issuecomment-2472832743)

so i think the above approach and message is good to go with? Also only the district-admin can have all the access, other admins can only access permitted facilities...?

**Comment by nihal467** [comment]
not a requirement based on the current develop , we moved to RBAC
