### ISSUE TITLE
Add a skeleton loader during advance filters are loaded

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8030]
**Describe the bug**

When we open a patient tab, which is already having a cache advanced filter applied to that page, for a second or two, the count of the patient will be shown as 0

Similarly, this behavior issue is happening across the platform

**To Reproduce**

**Expected behavior**

On discussion, we need to check it in packet loss 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/6d5ddf76-1689-44f3-8184-09f2b08d121a)

**Comment by Tusharjamdade** [comment]
Assign this to me if it is not complete.

**Comment by noufalrahim** [comment]
@rithviknishad  can you assign this to me..?

**Comment by ghost** [comment]
Hey @nihal467 , @bodhish  can I try this issue ?

**Comment by Rishith25** [comment]
Hey @rithviknishad  @bodhish can i work on this issue?
