### ISSUE TITLE
Tooltip clipping in for preset save button

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8032]
**Describe the bug**

On the patient consultation page, the tooltip of the preset save button is clipping in

**To Reproduce**

1. Go to patient consultation page
2. hover-over the preset save button in the feed page
3. See error

**Expected behavior**

the tooltip should be properly visible in this page

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/a286e75b-48a0-4729-a681-82d89bdf2c21)

**Comment by Aryanshu919** [comment]
@nihal467  I am unable to reproduce this issue. Could you please provide more details on how to reproduce it ?
