### ISSUE TITLE
Unable to scroll through the voice-autofill pop-up

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8033]
**Describe the bug**

once the data is processed in the patient log update, we are unable to scroll through the pop-up in the normal laptop view (14inch screen)

**To Reproduce**

**Expected behavior**

add a scrolling support to view the scribe pop-up properly

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/7ae4f8c7-2027-4337-ae8c-9565af29c1da)

**Comment by FrankenDeba** [comment]
@nihal467 How to access the add consultation update page? I am new.
