### ISSUE TITLE
Unable to View all Patient records in Shifting Module

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#8037]
In Shifting Module currently we don't provision in the interface to view all patients and Patient records.
 If the Number of 'Completed' is 350 there are no ways to view all 350 patients. This is throughout all the Shifting Statuses'.
 Please find below reference for detailed Understanding
 

Uploading Shifting Module (1).mp4…

**Comment by nihal467** [comment]
@aparnacoronasafe can you check and suggest the way of approach should be + mock UI for this issue

**Comment by aparnacoronasafe** [comment]
bug: unable to view all patients in the list.

A list in Kanban might say "45" on top, but when you scroll down only 18 or so patients are listed. Show all 45 patients in list

**Comment by nihal467** [comment]
@khavinshankar currently, we are adding a temporary fix where users can click on load more button, to load more cards (14 more cards on each click ). We need to implement infinite scroll in the system.

**Comment by khavinshankar** [comment]
Infinite scrolling would need an additional hook (useInfiniteQuery) which is similar to tanstack query, this will be picked up once we decide to go ahead with tanstack query refactor.

**Comment by sanjayh-2022** [comment]
@nihal467 Sir can i please work on this issue?

**Comment by nihal467** [comment]
not a requirement based on the current develop
