### ISSUE TITLE
Avail the feature to filter out the users with No Home Facilities in User Module

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#8038]
Currently there's no provision to filter-out Users with no Home Facilities, availing this feature of filter out users with No Home facility should help in easy retrieve of Remote Doctors.
attaching supporting Screen recording for ref.

https://github.com/coronasafe/care_fe/assets/166367729/f8e7c09a-cc77-4ce2-970a-01350bdd104d

**Comment by nihal467** [comment]
removing the stale badge as there is a PR up for review
