### ISSUE TITLE
URGENT NEED: Improve camera feed

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8040]
**Is your feature request related to a problem? Please describe.**
The new camera feed component is getting a lot of negative feedbacks for the following reason:

- [ ] The aspect ratio has changed. The width is increased with respect to the height. This reduces the feed space on phone screens.
- [ ] Is it possible that the new component is slower and requires a better internet speed to work? Many complaints of camera feed freezing with internet speed dips. Users say this was not the case before
- [x] #8085

**Comment by rithviknishad** [comment]
@aparnacoronasafe 

> The aspect ratio has changed.

The aspect ratio has not been changed. It uses 16:9 standard video ratio before and now. Could you provide screenshots / more details for it?

> Is it possible that the new component is slower and requires a better internet speed to work.

The new component does not require any extra internet speed to work. It uses the same method as before to stream the video. 

The new component would attempt to reconnect if the latency goes beyond 5 seconds and would cause a momentary black screen until reconnected. Should we consider increasing the latency threshold?
