### ISSUE TITLE
BUG : View details page is crashing for critical care & progress note

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8050]
**Describe the bug**

When you click on the view details page of the card related to critical care and progress note, the page is crashing.

Note : it is working perfectly with normal log update

**To Reproduce**

1. Go to patient consultation page
2. Click on view details button of either critical care or progress note in the log updates card
3. See error that the page crash

**Expected behavior**

it should be showing the view details page

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/fb6a1680-30f5-4a4d-b405-9979058014fe)

**Comment by Ramannandiwal** [comment]
@nihal467 can you elobarate the path on which the error are you facing ?

**Comment by nihal467** [comment]
@Ramannandiwal steps to reproduce 

1. Go to patient consultation page of a existing patient from the patient tab
2. Click on the log update button
3. create a log update with round type "Critical care" or "Progress Note"
4. submit it, now in the daily round tab, find the relevant card, and click view details button in the card
5. then you will see the page crashes
