### ISSUE TITLE
Mobile/Landline Icons are not responding

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#8051]
Mobile and Landline Icons in the Patients' list page ain't responding irrespective of updating phone numbers of any types. This is noted across the instances.
This is necessary to identify which kind of Phone Numbers are given and understand its usage
Attached the snap marking the icons where the responses were not seen below
![Phla](https://github.com/coronasafe/care_fe/assets/166367729/936ace26-fab2-430f-9be6-fc0526bbeb75)

**Comment by Ramannandiwal** [comment]
@gayann-au can you please elaborate the issue do you excepting that icons functions should be like to select wheater you have to enter a landline number of the mobile number ?

**Comment by rithviknishad** [comment]
@gayann-au The purpose of the mobile/landline/support(toll-free) number icons are for indicating which type of number are ALLOWED in that particular field, and not which is the current type based on the input. 

Certain phone number fields in CARE do not accept landline numbers and certain fields do accept support / toll-free numbers in addition to mobile and landline numbers. Icons are to indicate which types are supported in the corresponding input field.

**Comment by rithviknishad** [comment]
@gayann-au it is not easily possible to distinctively differentiate between a landline and a mobile number. So instead we've decided to add an info icon to convey what the icons try to convey. (i.e., the icons represent which numbers are allowed in this field and rather not about which type of number the currently entered one is).
