### ISSUE TITLE
Respiratory support- ease data entry

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8054]
**Is your feature request related to a problem? Please describe.**
Today, for a user to update respiratory support-related data on CARE, the only way is to file a detailed log update. A doctor may update this information through the progress note as well. However, this information sits inside of large forms making it difficult for users to update this.

It is observed that data entry specifically for respiratory support is not being logged across most hospitals because of this difficulty in data entry.

**Describe the solution you'd like**

- [ ] Rename "ventilation tab" on patient dashboard to "Resp. Support" (short form for respiratory support)
- [ ] Add a button on top right corner of the tab to update details and allow user to only update the details in Respiratory support section of detailed log updates. Provide a field for "Measured at" as the first field.

**Comment by shivankacker** [comment]
@aparnacoronasafe can you provide more information regarding the issue?

**Comment by nihal467** [comment]
non-relevant to current develop
