### ISSUE TITLE
Facility listing- occupancy

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8055]
**Is your feature request related to a problem? Please describe.**
Today, the facility listing (https://care.coronasafe.in/facility) shows the total occupancy of the hospital. ICU occupancy needs to be shown separately

**Describe the solution you'd like**

- [ ] In the facility listing (https://care.coronasafe.in/facility) add a second label with ICU occupancy. Keep the design consistent with "occupancy". Show "number of patients admitted to ICU bed type/ number of ICU beds registered"
- [ ] Occupancy label today shows total live patients/total beds registered. Instead, correct it to "total patients marked as admitted in consultation/ total no. of registered beds"

**Comment by Ni-011** [comment]
Hey I made the changes to ICU occupancy and Occupancy, since the text is too long I wrapped it around is this ui fine?

![image](https://github.com/coronasafe/care_fe/assets/63962929/ef1ccc76-4eed-4faa-b883-d93dd5f7ed25)

![image](https://github.com/coronasafe/care_fe/assets/63962929/41de53e1-8724-4b83-a138-bb5bfcc0f45f)

**Comment by Fredrick2503** [comment]
Hey can you assign me this issue I would like to solve it
@aparnacoronasafe

**Comment by gigincg** [comment]
@aparnacoronasafe This seems overkill, this would lead to way too much data on each card. Can you throw some light on what we're solving with this. 

This data is available in the dashboards.

**Comment by aparnacoronasafe** [comment]
@gigincg Currently we have multiple 10BedICU and smartICUs coming up where total beds may not necessarily be 10. There are must larger 15-20 bedded ICUs as well. 

In Karnataka, we are pushing for use of CARE in normal wards as well starting with patients downshifted from ICU. 

With all these, it becomes important for users to have a way to quickly check the occupancy, in ICU and non-ICU beds. For the team at the hub, seeing this info on facility listing is specially helpful to get a sense of the remote patient load. 

This info is not available on the dashboard. Only no. of active ICU patients are available on the dashboard

Can we consider improving design of the card? Anyway there is so much negative space on the card. we should be able to better use it. I could ask a designer to help out.

**Comment by nihal467** [comment]
closing this issue, as we can achieve the same by creating a new card in Metabase, @aparnacoronasafe connect with Neil on this!
