### ISSUE TITLE
Domiciliary care - improving patient flow

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8057]
**Is your feature request related to a problem? Please describe.**
The experience for users managing patients in domiciliary care may be improved through the following

**Describe the solution you'd like**

- [ ] Consultation form, when a patient is marked as under "domiciliary care' (in Decision after consultation), make "Treating Doctor" field non-mandatory

**Comment by 0hmX** [comment]
hey if no one is working on this i would like to be assigned

**Comment by Shahbaz898414** [comment]
can you assign me ?

**Comment by aparnacoronasafe** [comment]
@rithviknishad @nihal467 Who is working on this? 

Why is it marked as "work in progress" while no one is assigned?

**Comment by rithviknishad** [comment]
@aparnacoronasafe closing this as duplicate as already completed in https://github.com/ohcnetwork/care_fe/issues/8304
