### ISSUE TITLE
Review after - expand dropdown

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8058]
Review after field in consultation form and log update form has various options in the dropdown. 

The the following options
- 5 days
- 10 days
- 21 days
- 25 days

The dropdown options need to be arranged in ascending order

**Comment by Dev-Harwani** [comment]
Hi @aparnacoronasafe! I would like to work on this.
Basically I have to add the options you mentioned while retaining the already available options right?

**Comment by Ramannandiwal** [comment]
@aparnacoronasafe please attach the screenshot because the options are already sorted in the consulation Review after field

**Comment by nihal467** [comment]
@aparnacoronasafe the 21 days will be marked as 3 week to have consistency in showing the time

![image](https://github.com/coronasafe/care_fe/assets/57055998/ac088f08-6396-420f-85d3-dec5b95f2a32)
