### ISSUE TITLE
Improvement to ICD-11 search

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8080]
**Is your feature request related to a problem? Please describe.**
In CARE, ICD-11 dropdown field in consultation form, log update does not provide all options containing the search keyword.

Eg: When I search "Sepsis" on CARE, I only get 4 options in the dropdown
![Screenshot 2024-06-26 at 12 17 42 PM](https://github.com/coronasafe/care_fe/assets/67050716/64ea80fa-55b2-4924-b180-ceee5e42d76f)

Whereas when I search for the same keyword in ICD-11 directory (https://icd.who.int/browse/2024-01/mms/en), 30+ options. 

**Describe the solution you'd like**
@gigincg please add

**Comment by gigincg** [comment]
@sainak Can you add to the issue, what options are available in RedisSearch

**Comment by sainak** [comment]
@aparnacoronasafe the other entries in the WHO list are a combination of sepsis with other condition, and currently we don't have the way to store those combinations in care.

Also we don't have a database of Combinations.

It would be good to assess 
1. Whether it there is a publicly available database of combinations
2. Model in Care ICD Combinations liike, "Has causing condition", "Associated with" & "Other postcoordination"

**Comment by aparnacoronasafe** [comment]
@gigincg What would you recommend here? 

Users find using the ICD-11 search feature much easier https://icd.who.int/browse/2024-01/mms/en
Is there way for us to import all the info that the directory provides and give a similar experience on CARE?

**Comment by gigincg** [comment]
@aparnacoronasafe We don't plan to support Combination Diagnosis right now. This is expected behaviour. 

If you can think of any other ways to improve ICD11 Search, we can plan for it
