### ISSUE TITLE
Summary: prescription module

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8095]
On medicines tab on patient dashboard, at the bottom, you can see the summary. (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/medicines)

The summary shows the history or log for each medicine.

Instead, show date-wise summary. Show the exact delta advice by doctor on that day.

Eg: 

**20th June 2024**

Medications added:
1) Predox-OD
Dosage: 112 mg, Route: ORAL, Frequency: TID, Days: 10, Prescription Type: REGULAR
2) 
3).....

Medications discontinued:
1) Predox-OD
Dosage: 112 mg, Route: ORAL, Frequency: TID, Days: 10, Prescription Type: REGULAR
2) 
3).....

**Comment by nihal467** [comment]
non-relevant to current develop
