### ISSUE TITLE
Hide or add a note to the disabled options in status drop-down in shifting update form

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#8100]
Currently, for the destination facility users we disabled certain statuses in shifting update form as they don't have permission to set those statuses. We should show this in UI to avoid the confusion of why those options are disabled.

cc: @nihal467

**Comment by AdityaJ2305** [comment]
Hey Team, is this still an issue? If yes, could you assign it to me and provide the final expected behaviour along with the steps to reproduce?

**Comment by nihal467** [comment]
not a requirement based on the current develop
