### ISSUE TITLE
Bug : Location Management and Bed Management redirection are failing

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8102]
**Describe the bug**

When we click on the either location name or bed name of a cns without patient, it is not being properly redirected to the respective pages

Note: If there is a patient in the cns page, it is working properly

**To Reproduce**

1. Go to critical care facility
2. Click on view cns button
3. Go to setting button and toggle to show no patient cns as well
4. click on the bed name or location name
5. See error

**Expected behavior**

It should be properly redirected to the respective pages

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/7958abb6-be9c-43c1-819f-706c9f4900cf)

**Comment by Aryanshu919** [comment]
I want to work on this issue, Could you assign it to me.
