### ISSUE TITLE
filters in Facility>user page

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8106]
**Is your feature request related to a problem? Please describe.**
It is very difficult to find out how many nurses/doctors are allocated within a facility, either as staff in the facility or for remote support

**Describe the solution you'd like**
Add filter to facility>user page with the following options

- [ ] User role (Doctor/staff/nurse/pharmacist/volunteer etc)

- [ ] Access type (Show home facility /others/show all)

**Comment by tomahawk-pilot** [comment]
@yadev64

**Comment by yadev64** [comment]
I would like to take up this issue.

**Comment by bodhish** [comment]
@yadev64 if you are working on it, don't pick the solution listed. Feel free to ideate. 
I am not sure if its the right way to list users also. This can be a good time to build a better UI/UX

**Comment by NikhilGolla72** [comment]
@bodhish @Jacobjeevan @dauntlessnomad @gigincg i would like to contribute to this issue, it no one is assigned,could you please assign me to this.

**Comment by nihal467** [comment]
@NikhilGolla72 the issue is assigned to you, do check the comment made by bodhi

**Comment by nihal467** [comment]
not a requirement based on the current develop
