### ISSUE TITLE
Prescription backdate availability 

### ISSUE THREAD

**Issue by NNSiri** [coronasafe/care_fe#8114]
A Scenario:
a patient admitted in the morning, but the data entry starts by afternoon. Hence the prescription is added by afternoon. the date and time are automatically fetched , it is not editable.  Now because the time of prescription added is  noon, the morning dose of medications cannot be entered. 

**Describe the solution you'd like**
Date and Time should be editable while entering the prescription.

**Comment by aparnacoronasafe** [comment]
Already taken care of in https://github.com/coronasafe/care_fe/issues/8116
