### ISSUE TITLE
Support for form templates in Log Update

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8115]
## Problem Statement
As the log update feature in our application evolves, it has become increasingly clear that a one-size-fits-all approach to the daily rounds form is insufficient to meet the diverse needs. Different rounds or scenarios require different sets of fields, making the existing form structure cumbersome. To enhance user experience and ensure accurate data collection, it is essential to implement a more dynamic and configurable system for form templates.

Also, the design of the log update pages (Detailed and normal log updates) is very different.

## Proposed Solution
To address these issues, a flexible, configurable form template system is required to easily configure forms with specific fields/sections based on each round type. 

Also, the design of various log update types should be consistent. (Read more in #7351)

--------

**Pre-requisites:**

- [x] https://github.com/coronasafe/care_fe/issues/8094
- [x] https://github.com/coronasafe/care_fe/issues/7705
- [x] https://github.com/coronasafe/care_fe/issues/7855

**Comment by gigincg** [comment]
@rithviknishad Unassigning you to open up bandwidth. I'll take this up as part of other clinical pieces

**Comment by nihal467** [comment]
we have implemented the questionnaire
