### ISSUE TITLE
Merging Prescription and PRN Presription

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8116]
**Is your feature request related to a problem? Please describe.**
Prescription and PRN prescription are not 2 distinct items. PRN prescription is simply a prescription given by a doctor where the direction is to administer the medicine is based on any clinical condition, which is different from a normal prescription where medicine is administered daily twice, or repeatedly at said intervals. 

Eg: Normal prescription- 
Paracetamol 500mg once daily for 5 days
![Screenshot 2024-07-04 at 5 21 30 PM](https://github.com/coronasafe/care_fe/assets/67050716/fca94994-2e8a-4469-bba0-c365a373c564)

PRN prescription-
Take Paracetamol 500 mg if temp goes above 100F. Take up to 1000mg a day, with min 2hrs between the doses.
![Screenshot 2024-07-04 at 5 22 40 PM](https://github.com/coronasafe/care_fe/assets/67050716/430820ea-532d-4052-a209-16c87e47653b)

Therefore PRN is actually an indication of frequency in prescription.

Merging Prescription and PRN prescription would make data entry simpler

**Describe the solution you'd like**

The Prescription form will contain the following fields

![Screenshot 2024-07-05 at 3 44 37 PM](https://github.com/coronasafe/care_fe/assets/67050716/a6fa98f9-07ff-4454-9c1d-dace7e856944)
NOTE: The text in red are the mandatory fields and the blue boxes are the various options available to the user. 

To Do:

- [ ] Merge Prescription and PRN prescription in the UI as well as the database
- [ ] Add an option in Dropdown for Frequency with "PRN" as an option
- [ ] Reorder the content of the prescription in the given order
- [ ] Add start and end date and time. Start date should contain default date and time of data entry. Allow user to pre-date the start time up to the date and time of admission. End time should not be before start time.
- [ ] Wherever Days and start date-time is given, Auto- calculate the end date time

**Comment by gigincg** [comment]
@aparnacoronasafe Can you add some clarity to this? 

Is it apt, to make PRN one option of frequency? FHIR Does this quite differently. Is frequency never applicable for PRN Prescriptions

Alt Reference: https://mn.gov/boards/assets/prescription%20abbreviations_tcm21-26882.pdf

**Comment by aparnacoronasafe** [comment]
@gigincg 

Referring to FHIR structure here: https://build.fhir.org/medicationrequest0307.json.html
The PRN medication request is written as 
Medicine:
Dosage instruction: Take if pain persists
Dosage: 1 tab
frequency 4 hrs

The problem with defining prescription this way is, in MAR, the medicine may come up as needing administration every 4 hrs. Which may arise confusion. 

Medicine frequency is not applicable for PRN prescription. A more accurate way to define it is to simply define "min time between 2 dose" and "Max dose in 24 hrs". This is also the practice among doctors. 

Hence, I believe it is better to follow the structure above. 

You are right in saying that PRN is not an option within Frequency. The more apt way to do it is to let the user select between "PRN/Scheduled", if, scheduled, then have the option for frequency. 

It is recommended to provide all options under frequency only with the intention to avoid having two input fields, instead of 1

**Comment by bodhish** [comment]
@gigincg @aparnacoronasafe

How important is this now? I am quite convinced that our UI/UX for prescription is quite broken so can this be done as part of a refactor?

**Comment by sanjayh-2022** [comment]
@bodhish  Sir can i please work on this issue

**Comment by nihal467** [comment]
completed in the current development
