### ISSUE TITLE
Show Bed no. of location card

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8131]
**Is your feature request related to a problem? Please describe.**
in location list, users don't see how many beds are registered in each location. to know that they have to open up each location and see list of beds

https://care-staging.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/location

**Describe the solution you'd like**
Add No. of beds of each bed type registered in a location on the location card in location listing
https://care-staging.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/location

**Describe alternatives you've considered**

**Additional context**

![Image](https://github.com/user-attachments/assets/34212c87-015e-4d7d-aa7a-96d38428d5d5)

**Comment by shubhamchasing** [comment]
I would like to work on this

**Comment by ahmedobaid23** [comment]
I want to clarify a few things regarding this issue.

1. This is information about types and number of beds in a location: 
![main](https://github.com/user-attachments/assets/62eb72c9-8c7c-4702-b1a6-c4cae7560240)

Do you want the above information to be shown on the outlined FacilityCard on this page?
![WhatsApp Image 2024-07-15 at 1 25 28 AM](https://github.com/user-attachments/assets/998fe92b-9dcf-466e-91fc-ce1cc8b0dbf8)

2. Do you have any design preferences? Because accommodating all the information into the small FacilityCard will change the design alot!

**Comment by nihal467** [comment]
@shubhamchasing @ahmedobaid23 
![image](https://github.com/user-attachments/assets/aa405a51-a4a5-4051-b1be-5ede5ec5d664)

this is the location management page.

- go to facility detail page, click on the manage facility button, in that dropdown click on the location management option to reach this page

**Comment by nihal467** [comment]
![image](https://github.com/user-attachments/assets/95f40896-fc7a-4579-931d-f4e165655dc5)

@ahmedobaid23 as per the issue, in the above location card itself, we should be able to view each type of bed associated with that location, it can be icons or anything that goes in-sync with the design, so try to create a mock-up before start coding on it.

in the location management card, we only have four beds which are supported, so only need to handle that

**Comment by Shelly011s** [comment]
@aparnacoronasafe @nihal467 I would like to contribute to this issue. Please assign this to me.

**Comment by rithviknishad** [comment]
@Shelly011s unassigned due to inactivity. Feel free to assign again if available and create a draft PR.

**Comment by noufalrahim** [comment]
@aparnacoronasafe @nihal467 @rithviknishad  can u assign this to me..?

**Comment by Shelly011s** [comment]
@rithviknishad Hello, really sorry for the prolonged delay but I have created and discussed upon the UI on slack. I have been struggling to get the number of beds with no limit or offset. Would you be kind enough to guide me a little and please assign the issue? I will finish the PR by tomorrow without any delays.

**Comment by noufalrahim** [comment]
@Shelly011s, I have already raised a PR, if this is not what is required definitely you can take up the issue..
Sorry for the inconvenience!

**Comment by nihal467** [comment]
@aparnacoronasafe currently we will be only showing total number of bed in the entire location, if you still want the requirement of no of bed under each bed type in each location, feel free to reopen this issue post the linked PR is merged
