### ISSUE TITLE
Avail the filter to extract users who never logged In 

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#8133]
Enable the filter in Users module to fetch the users who never logged.
This avails the privilege to the admins to know the user activity across, which helps in administrative point.

**Comment by mayankdutta** [comment]
Hi, I was trying to figure out how `search functionality` by `user_name` in user section is working. 
From what i could understand the `user_name` key-value is set in `query params` via `raviger` library and from there, **Filter** should be carried out. But I couldn't locate where that filter operation is being performed. 
can you help me out pls, any hint?
