### ISSUE TITLE
Improve the Error for Consultation Form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8142]
**Describe the bug**

When a doctor called "Dr A" is being unlinked from a facility and you try to edit a consultation of a patient, where the Dr A was assign, the error thrown in front is not user friendly

**To Reproduce**

1. Go to patient consultation page of a patient
2. Identify the treating doctor (from consultation form) and unlink the doctor from the facility (using user tab)
3. Now try to edit the consultation form and submit it

**Expected behavior**

The error message should be modified to "Oops! The treating doctor is no longer linked to this facility. Please update the respective field in the form before proceeding. "

**Screenshots**

![WhatsApp Image 2024-07-09 at 15 33 02_9a4b86d9](https://github.com/user-attachments/assets/a53bd942-1fbb-4473-b8d5-837daad559b5)

**Comment by lakshaydewan** [comment]
Hi @nihal467 ,

I'd like to be assigned to this issue. I'm interested in working on it and believe I can help resolve it.

**Comment by lakshaydewan** [comment]
how do i unlink the doctor from the facility?
unlinking the Doctor shows an Error - "Facility access not present"

**Comment by nihal467** [comment]
- Go to user tab, by clicking on the sidebar
- Search for the user id
- Click linked facilities button in the respective user card
- click the red button in the same row of the facility name , you click on that
- You will receive a successful notification to confirm unlinking is done

**Comment by shivankacker** [comment]
@nihal467 adding to this, I think a user should not be able to unlink a doctor from a facility until the doctor is unassigned from all the active patients. An error should be thrown if unassigned.

cc. @gigincg

**Comment by nihal467** [comment]
@skks1212 can you push the fix as well discussed in the engineer call, modify the error message for now
