### ISSUE TITLE
Enhance the Review time approach in the CARE

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8151]
**Describe the bug**

The review time and action can be modified on the edit consultation page. For instance, if a user sets a review time of 30 minutes when creating a consultation at 1:15 PM, this would mean the review time is set for 01:45 PM. If at 1:30 PM, a staff nurse opens the edit consultation page for the same patient, makes some changes, and submits the form, the review time becomes 2:00 PM based on the initial selection of a 30-minute review period preserved in the form. However, this results in the review time being incorrectly reset without the user's awareness.

**Expected behavior**

- Allow Keeping the existing Review in consultation form as it is when Creating a Log Update
- ⁠Show a Preview of the current planned review in the Log Update Page
- Either remove Review Time in Edit Consultation Or use the same approach above for Log Update, based on Product Input

CC: @gigincg @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
This needs to be built out in more depth. The review feature needs to be replaced by a more elaborate task management module for nurses and other users.

Eg: to-do for nurses would include

Review Vitals every 20 min
or
Review BP every 15 minutes for the first 2 hours and every hour after that for 3 days
or
Review Temp every 15 min till it comes below 100F and then every 2 hrs

Time may be set to perform any procedure like doing 
- ABG tests every 24 hrs starting at 6AM today

Medicine administration is similarly scheduled for specific time.

This has to be built as part of the larger nurse task management module. 

Similarly for doctors also there may be tasks such as Administering specific drugs

Physiotherapists may need to perform specific procedures like "exercise to extend limbs" at a specific time.

Therefore a feature to set timer for a specific time schedule linked to an action and an actor is what is needed. Corresponding "to-do list" must be accessible to the relevant actor

**Comment by aparnacoronasafe** [comment]
@gigincg @bodhish 

This is something we will need to develop soon. What are your thoughts on this?

**Comment by gigincg** [comment]
> Review Vitals every 20 min or Review BP every 15 minutes for the first 2 hours and every hour after that for 3 days or Review Temp every 15 min till it comes below 100F and then every 2 hrs
> 
> Time may be set to perform any procedure like doing
> 
> * ABG tests every 24 hrs starting at 6AM today

@aparnacoronasafe Can you add more depth on the user flow here? I don't see Nurses looking at Notificaitons in Care and executing these. This sounds like Tasks involved in the Treatment Plan. Unrelated to this specific issue.

**Comment by aparnacoronasafe** [comment]
@gigincg my point is generic review time is not useful. 

What we need is scheduled appointments along with task managers (to-do lists) for specific users.

I can write a doc scoping this out in detail. 

This may be taken up after the fundamental modules of HMIS. until then lets continue with the existing review

**Comment by bodhish** [comment]
I am removing this for current sprint.

**Comment by nihal467** [comment]
non-relevant to current develop
