### ISSUE TITLE
Reduce the Notification-Message display timings

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#8157]
Error Messages/Notifications when attempted to update data, access denial Notification, Notifications when Discussion Notes are filing attempts are done and for other Error Messages, the Notification message display timings should be reduced in contrast to current usage.  Currently these message take extra Time to Auto Vanish.

Attached few snapshots of these messages for ref:
![image](https://github.com/user-attachments/assets/588dc2c4-b012-4982-b163-b5e153db6a3e)
![image](https://github.com/user-attachments/assets/cf01b9c6-2469-4c44-97b9-97b5fa33eab3)
![image](https://github.com/user-attachments/assets/1f7f6bb9-aac3-4b9f-8136-ba64eeb7f942)

**Comment by gigincg** [comment]
Anyone who would like to work on it, please describe your solution before working on it

**Comment by HitishRaoP** [comment]
@gigincg By adding a delay option in the notify configuration, we can control the visibility duration of notifications. This can be set to a reasonable default (e.g., 1000 milliseconds), while still allowing users to adjust it based on their requirements.

File : https://github.com/HitishRaoP/care_fe/blob/develop/src/Utils/Notifications.js

Relevant code:
![Screenshot 2024-09-10 114610](https://github.com/user-attachments/assets/acaa34b9-f758-41e1-9b24-9699d7ca1e12)

**Comment by BarryByte** [comment]
@gigincg Hello maintainers, i would like work on this issue, please assign this issue to me
My solution is to add include a delay option in the notification settings allows control over how long notifications are displayed.
