### ISSUE TITLE
Death report is missing patient age

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8160]
**Describe the bug**

When the patient's age is less than a year, we are showing it as month and days in the platform now, that same is not being copied to the death report form

**To Reproduce**

1. Create a new patient with age less than 1 years of age
2. Discharge the patient as expired
3. Go to the patient details page and click of death report

**Expected behavior**

The age column in the death report should be filled with month and date, if the patient is less than 1 years old

**Screenshots**

![image](https://github.com/user-attachments/assets/bb356b8a-35c0-4053-b0a8-553317d34cca)
![image](https://github.com/user-attachments/assets/d937e53b-6854-4994-a3c6-b0d9ada41afc)

**Comment by SagarSharma2809** [comment]
Hi, if no one is working on this issue, I am willing to take the issue. I will create a new patient age less than 1 year and try to see the error and fix it. Thank You

**Comment by bodhish** [comment]
Why show age? Can’t we show the date of birth?

**Comment by Indrajeety993648** [comment]
hey @rithviknishad  I would like to work on this issue ,  If no one working on it  Please  assign it  to me

**Comment by noufalrahim** [comment]
@rithviknishad  Can u assign this to me..?

**Comment by rithviknishad** [comment]
@noufalrahim feel free to pick up ones other issues assigned to you has PRs raised and approved.
