### ISSUE TITLE
In CNS page: filter by location- hide locations with no Monitors

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8162]
**Is your feature request related to a problem? Please describe.**
In the CNS page, when filtering by location, I can see all locations within the facility. This is not useful since only a few of these facilities may have 5-para monitors deployed in.

**Describe the solution you'd like**

https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/cns

- [ ] In the filter by location option, remove all locations with no monitors registered. Every monitor registered is linked to a bed within a location (https://care.coronasafe.in/facility/b87b1396-631b-4306-bf33-3022bec0a5a5/assets/3297fee3-3872-4a3a-99ab-367876458267/configure)

- [ ] Disable the filter by location option if only 1 location has monitors deployed

**Describe alternatives you've considered**

**Additional context**

**Comment by amjithtitus09** [comment]
I would like to work on this issue

**Comment by JohnLu2004** [comment]
@rithviknishad May I contribute to this issue?

**Comment by Jacobjeevan** [comment]
@bodhish Keeping the issue open since BE [changes](https://github.com/ohcnetwork/care/pull/2545) has to be reviewed/merged yet (at the moment, FE changes would make no difference).

**Comment by bodhish** [comment]
Missed that while checking the PR;
