### ISSUE TITLE
Facility Page: View discharged patients 

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8164]
**Is your feature request related to a problem? Please describe.**
https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8

On the facility page, there is an option to "View Patients" and "View Discharged Patients"

This was relevant when out patients listing (https://care.coronasafe.in/patients?facility=0c95c7f0-e1d2-4aff-83fa-933cef60d3a8) didn't have the "live" and "discharged" tabs.

Now that the tabs are working, there is no need to show both View Patients" and "View Discharged Patients" options on the facility page

**Describe the solution you'd like**

- [ ] Remove "View Discharged Patients" button from Facility Page (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8)

**Comment by NitinPSingh** [comment]
hi , @aparnacoronasafe 
I have fixed this issue , kindly review 
![Screenshot (672)](https://github.com/user-attachments/assets/8e8fd10f-5ffe-4936-9c6f-35b81ed88f5a)
