### ISSUE TITLE
Enable monitoring of 1 bed through multiple cameras

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8165]
**Is your feature request related to a problem? Please describe.**
TeleICU-enabled ICUs usually have multiple cameras deployed. Currently, CARE only allows presets for a bed to be created with 1 specific camera. 

Allowing 1 bed to be monitored through multiple cameras would improve such monitoring capability by allowing users to look at patients from various angles etc.

**Describe the solution you'd like**
Allow 1 bed to be monitored through multiple cameras by creating presets for that bed with multiple cameras.

**Additional context**
For smartICU it is important to choose and mark 1 preset as catering to 1 medical device (5-para monitor, later to be expanded to other medical devices. Additional fields on camera configuration page/ 5-para configuration page to allow user to mark a specific preset as theprimary preset for the device may be considered. @gigincg

**Comment by rithviknishad** [comment]
Needs https://github.com/coronasafe/care_fe/issues/7511 before proceeding

**Comment by rithviknishad** [comment]
Closing in favour of #7511
