### ISSUE TITLE
Add a feature to tag releases related to specific PR

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8176]
**Is your feature request related to a problem? Please describe.**

When a PR is merged, it's hard to understand when it was released

**Describe the solution you'd like**

Similar to the cypress GitHub repo, have a action comment on each PR, on which version it was released

![image](https://github.com/user-attachments/assets/374f9114-ea8a-4a23-a35a-904528add74f)

**Comment by rithviknishad** [comment]
@nihal467 GitHub already provides this feature:

<img width="1453" alt="Screenshot 2024-07-17 at 22 24 06" src="https://github.com/user-attachments/assets/5f633893-faaf-40f0-942c-0383cbe86b1d">

**Comment by gigincg** [comment]
@nihal467 This is a wishlist feature right? Would be better to mark them when you file it. Assigning it to you for your response

**Comment by nihal467** [comment]
> @nihal467 This is a wishlist feature, right? Would be better to mark them when you file it. Assigning it to you for your response

Yes, it's a wishlist item
