### ISSUE TITLE
In patient detail , when going to investigation tab it's starts to show a blank  screen

### ISSUE THREAD

**Issue by praffq** [coronasafe/care_fe#8182]
**Describe the bug**
https://jam.dev/c/7cccfe88-baf3-4157-93c6-77a91fd90918

**To Reproduce**

1. Go to patients detail
2. Click on investigation
3. white screen

**Expected behavior**
Should show investigation window

**Desktop (please complete the following information):**

- OS: Windowsa
- Browser : Firefox

**Comment by nihal467** [comment]
@DraKen0009 the issue is not replicable in staging or develop branch, kindly check your branches are up to date,

**Comment by praffq** [comment]
Got it.
