### ISSUE TITLE
Modify Transfer patient pop-up behavior

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8187]
**Describe the bug**

When the patient transfer pop-up comes in front of the user for checkbox selection, accidently user click outside the pop-up, it will close the pop-up and take user to the patient list page

**To Reproduce**

1. Go to patient registration page, and input +919999999999 to phone number column
2. Click outside the transfer pop-up after that
3. See error

**Expected behavior**

- [ ] When user click outside the pop-up, the user should be returned back to the patient registration form itself, with the inputted phone number cleared
- [ ] Rename the "Cancel Registration" button to "Close"
- [ ] when user click on the close button, the user should be returned back to the patient registration form itself, with the inputted phone number cleared

Implement similar behavior for both duplicate phone number check and transfer patient dialogue

**Screenshots**

![image](https://github.com/user-attachments/assets/98301693-a961-4160-9124-9339616b8234)

**Comment by renoseHarsh** [comment]
When the user clicks the close button, is it fine if the page refreshes to clear the inputted phone number?

**Comment by rithviknishad** [comment]
@renoseHarsh 

Nope, that'll also clear all other fields right? That is not expected behaviour.

**Comment by renoseHarsh** [comment]
I was able to change the pop-up so that it closes instead of redirecting but I can't figure out how to clear the phone number field 
```
<PhoneNumberFormField
  {...field("phone_number")}
  required
  label="Phone Number"
  onChange={(event) => {
    if (!id) duplicateCheck(event.value);
    field("phone_number").onChange(event);
    if (isEmergencyNumberEnabled) {
      field("emergency_phone_number").onChange({
        name: field("emergency_phone_number").name,
        value: event.value,
      });
    }
  }}
  types={["mobile", "landline"]}
/>
```
Could you help with this? Thanks!

**Comment by rithviknishad** [comment]
On the popup's close callback, you could do: `field("phone_number").handleChange("+91")`
