### ISSUE TITLE
Improve the Validation check for phone number in patient list page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8189]
**Describe the bug**

Currently, we are checking if the phone numbers entered are valid or not, on each input, let's say we want to type "9846856118", on inputting 9 itself, the error message start showing " enter valid number number " until we finish the number  

**To Reproduce**

1. Go to patient list page
2. enter the phone number
3. See error

**Expected behavior**

Once the user go out of focus only the validation check should take place,

Note: we already experimented with one approach, but in that, if user inputs 9 digits, the error is not thrown https://github.com/coronasafe/care_fe/pull/8185/commits/5a33cb78fbe1dcb4c544610ab81fd15b158ec139

**Screenshots**

![image](https://github.com/user-attachments/assets/a742d398-f287-45ea-a188-8b02a9998ed9)

**Comment by saloni0419** [comment]
@rithviknishad @nihal467  can you please assign this issue to me

**Comment by nihal467** [comment]
@saloni0419 Are you still working on this issue? Please respond with the current status. If no response is received within the next 48 hours, you will be unassigned due to inactivity.

**Comment by saloni0419** [comment]
@nihal467 sorry for the late reply. i was busy somewhere . i am unassigning myself

**Comment by Nithin9585** [comment]
@nihal467  can you please assign this issue to me

**Comment by Nithin9585** [comment]
Hi @rithviknishad sir, could you please review my PR https://github.com/coronasafe/care_fe/pull/8394#issue-2480346514  when you get a chance? It addresses issue #8189 by improving the validation check for phone numbers on the patient list page.

Thank you!
