### ISSUE TITLE
Remove the badge for facility specific discharge patient list page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8194]
**Describe the bug**

When we take the facility discharge patient list page, clear all filter badge shows up, which is not relevant on that page

**To Reproduce**

1. Go to facility specific discharge patient page
2. See error

**Expected behavior**

when we visit facility specific discharge list, it shouldn't be showing any advance filter badges

**Screenshots**

![image](https://github.com/user-attachments/assets/ecd183ee-1dbf-431c-ab66-fa6deb681be8)

**Comment by Fredrick2503** [comment]
Hey can you assign me with this issue

**Comment by rithviknishad** [comment]
Closing as a more accurately described issue has been created #8449
