### ISSUE TITLE
scribe is malfunctioning in iphone devices

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8203]
**Describe the bug**

When you record audio in the Scribe using an iPhone, hit the stop recording button, and the next second, it throws an invalid file format error on the iPhone without completing the file upload.

**To Reproduce**

1. Go to the patient log update page using iPhone [ For testing i used iPhone 14pro 17.4 Version ]
2. Click on the auto-fill button
3. start recording audio and hit the stop button

**Expected behavior**

- [ ] The recorded file should be properly uploaded to the Scribe, and it should auto-fill the form as expected.

**Screenshots**

![IMG_8371](https://github.com/user-attachments/assets/259d6a11-1523-4402-868d-deab072573c9)

.

**Comment by bodhish** [comment]
@nihal467 please update the issue description

**Comment by nihal467** [comment]
> @nihal467 please update the issue description

done
