### ISSUE TITLE
Events Module: Diagnosis

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8212]
**Describe the bug**
When a diagnosis is added to the patient file, 2 issues arise

- [ ] When diagnosis is added in the first consultation, the event note shows a lot of redundant data
![Screenshot 2024-07-24 at 7 47 02 PM](https://github.com/user-attachments/assets/f6332022-6c28-4937-9b51-c0517463105e)

It should only say: 
"Diagnosis - **GA90 Hyperplasia Of Prostate** added as confirmed Diagnosis and marked as Principle Diagnosis"

- [ ] When diagnosis is edited in "Edit consultation form" or "Progress Note (Log update)" no event note appears.

**To Reproduce**

1. Go to any patient with no consultation filed
2. submit consultation form with diagnosis as "GA90 Hyperplasia Of Prostate", mark as confirm and primary diagnosis
3. Go to patient dashboard and check events log
4. See error in screenshot above

**Comment by nihal467** [comment]
@aparnacoronasafe https://github.com/coronasafe/care_fe/issues/7902 , there is already related issue opened, and assigned to aakash
