### ISSUE TITLE
Events module: Advise

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8213]
**Describe the bug**
In consultation form there is a field to update "General Instructions (Advice)". When the user updates it, on events log the corresponding log calls it "CONSULTATION NOTES"

Change it in the events log to "General Instructions (Advice)"

**To Reproduce**
See this patient file: https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/14dd4345-450b-4392-9c5c-4f88bc32c533/consultation/952ebe29-8cdd-44fc-b13c-acde347f951b

**Comment by ahmedobaid23** [comment]
I would like to work on this issue
