### ISSUE TITLE
diagonal shortcut camera feed movement is not working in Windows system

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8218]
**Describe the bug**

In the windows system, due to conflict shortcut with its system key combination, the diagonal camera movement shortcut keys are not working properly

**To Reproduce**

1. Go to patient consultation feed page
2. Use shortcut for diagonal movements
3. See error

**Expected behavior**

The shortcut for diagonal control should work properly for all system

**Screenshots**

![image](https://github.com/user-attachments/assets/d06eab1e-2456-4996-ad1d-bce78b1e972b)

**Comment by KoustubhShidlyale** [comment]
@rithviknishad @nihal467 can you please assign this issue to me

**Comment by SwanandBhuskute** [comment]
I would like to solve this...

Can I get more info on this issue?
like on which route should I go ?
is it /patients ?

**Comment by Jacobjeevan** [comment]
> I would like to solve this...
> 
> Can I get more info on this issue? like on which route should I go ? is it /patients ?

Not sure if this ticket is still relevant, especially since we were making some changes to camera (but that might just be bed presets if I recall?) @nihal467

**Comment by SwanandBhuskute** [comment]
ok sir, I will take another issue

**Comment by nihal467** [comment]
non-relevant to current develop
