### ISSUE TITLE
camera element shortcut stop working after viewing feed for sometime

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8219]
**Describe the bug**

The camera element shortcut won't work if i keep on viewing the camera feed for 5-10 minutes straight

**To Reproduce**

**Expected behavior**

camera shortcut should work properly irrespective of the time users is viewing the feed

**Screenshots**

![image](https://github.com/user-attachments/assets/e7b20c12-8a46-40d2-9c76-a379c0c54844)

**Comment by rithviknishad** [comment]
Unassigning due to:

- Unable to consistently reproduce the issue.
- Unable to identify the root cause of the issue.
