### ISSUE TITLE
Date component in the symptoms module is not responsive

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8220]
**Describe the bug**

On smaller mobile screens, the date overlaps with the calendar icon in the symptoms module

**To Reproduce**

**Expected behavior**

- [ ] the text and components shouldn't overlap in the smaller screen

**Screenshots**

![image](https://github.com/user-attachments/assets/57da62df-2e3f-4ee3-8996-cdee77ab1ca2)

**Comment by Suvrajit69** [comment]
Can I work on this issue?

**Comment by nihal467** [comment]
@Suvrajit69 already @NitinPSingh pushed a PR for this issue, feel free to work on any other open issues post getting it assigned

**Comment by rithviknishad** [comment]
@NitinPSingh 

It'd be great if you could comment on issues when picking it up, so that the issue can be assigned to you and would make it easier for others to pick-up unassigned issues 😄
