### ISSUE TITLE
Increase the width of the log update form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8221]
**Describe the bug**

The max dosage and min time between dose fields in the PRN prescription module present in the log update form, its been shown in two rows

**To Reproduce**

1. Go to patient log update in the consultation page

**Expected behavior**

Increase the width of the entire form little bit and adjust the field of indicator little bit , make these two minor adjustment, make those fields name to be shown in one row

**Screenshots**

![image](https://github.com/user-attachments/assets/7f7475c2-3ed3-445a-9f22-b0c408b39385)

**Comment by renoseHarsh** [comment]
I’m new to open-source contributions. I’ve increased the form's max-width by changing max-w-4xl to max-w-5xl. Here’s how it looks now. If this solution is satisfactory, could you please assign the issue to me? I’ll prepare a PR.
<img width="1152" alt="Screenshot 2024-08-02 at 1 51 29 PM" src="https://github.com/user-attachments/assets/faee6eae-98f1-4c12-b7ff-86af280c5b54">

**Comment by rithviknishad** [comment]
Awesome! Feel free to create a PR!
