### ISSUE TITLE
Implement Auto-scroll for missing mandatory fields in log update form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8222]
**Describe the bug**

When I click save button in the log update and if there are any mandatory fields left blank, the platform is not auto-scrolling to the fields so that user can locate the error easily

**To Reproduce**

1. Go to log update and click save button without selecting any patient category
2. See error

**Expected behavior**

the form should auto-scroll to the error field in the log update form up-on trying to save the form

**Screenshots**

![image](https://github.com/user-attachments/assets/f52ba910-41e9-49e8-92e2-968120cb5fd0)

**Comment by ashparshp** [comment]
@nihal467 Can you please assign it to me?

**Comment by gigincg** [comment]
@Ashparshp Do let us know if you have any blockers. When you make the PR, do link the issue :)
