### ISSUE TITLE
Misalignment of placeholder text inside date component in the add user page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8239]
**Describe the bug**

the Placeholder text in the date component in the add user page is not aligned when compared with the other Placeholder text in the same page

**To Reproduce**

1. Go to user tab
2. Click on add user button
3. See error

**Expected behavior**

all the Placeholder text in the form should be properly aligned and consistent

**Screenshots**

![image](https://github.com/user-attachments/assets/54941546-2bfa-4437-a310-fde4036c0363)

**Comment by 0xvish** [comment]
Hi can I work on this issue?
