### ISSUE TITLE
Correct spelling mistake of daily round field: `ventilator_fi02` to `ventilator_fio2`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8241]
Daily rounds model's field name: `ventilator_fi02` needs to be corrected to `ventilator_fio2`

### Action Items

- [x] Correct the field name in the backend (https://github.com/coronasafe/care).
- [x] Correct the field name in the type definition and usages in the frontend.

**Comment by 0xvish** [comment]
Is this a Backend Issue or a Frontend Issue?

**Comment by rithviknishad** [comment]
Both needs to be updated as mentioned in the issue description

**Comment by 0xvish** [comment]
I believe all the definitions in the frontend are named **ventilator_fio2**

**Comment by SagarSharma2809** [comment]
I am willing to take this issue

**Comment by TrevorMustoe** [comment]
Hello! I would love to fix this issue if you assign it to me! Thanks and hope to help!

**Comment by SagarSharma2809** [comment]
Corrected in Backend too. Created a Pull request in backend : https://github.com/coronasafe/care/pull/2345
