### ISSUE TITLE
Duplicate IP Number detection feature not working. 

### ISSUE THREAD

**Issue by dpnkr1** [coronasafe/care_fe#8262]
**CARE is taking two same ip number within the same facility**

**To Reproduce**

**Expected behavior**

**Screenshots**
![care bug](https://github.com/user-attachments/assets/b28bfd77-159e-47f1-a68d-ec5817b9bf49)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nihal467** [comment]
@dpnkr1 can you share the real-world scenario where a facility will be using same IP number for two live patient

**Comment by dpnkr1** [comment]
@nihal467 no the facility will not use two same IP number for two live patient, an IP number is unique to a single patient within the facility.

**Comment by samholics** [comment]
can we put a caution message on IP number field saying its already exists if they are repeating the IP number. like we did it on admission date.  The RealWorld scenario is nurses tend to mistakenly enter the same IP for different patients. @nihal467 @aparnacoronasafe 
<img width="535" alt="image" src="https://github.com/user-attachments/assets/5f158826-d430-4f9c-9e39-b378bde07fe5">

**Comment by Jacobjeevan** [comment]
@samholics This only applies to IP number/on Admission, and not to OP number, right?

**Comment by sainak** [comment]
@dpnkr1 we have been going back and forth adding and removing validations to the ip/op number field #7751 #7798

cc: @gigincg @aparnacoronasafe

**Comment by bodhish** [comment]
Closing the issue
