### ISSUE TITLE
NIV and IV ventilator mode & Oxygen support Modality mode have no data reflection in patient consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8264]
**Describe the bug**

In the patient consultation page, currently, there is a badge present their respiratory support is either NIV, IV, or OS but the related ventilator mode or modality mode is shown nowhere in the platform

![image](https://github.com/user-attachments/assets/10c90b45-9831-4f28-9d5e-0dc7ea4cc2a7)

**To Reproduce**

1. Go to patient consultation page
2. Click on log update and file the detailed log updated
3. post creation, go to the consultation page.

**Screenshots**
![image](https://github.com/user-attachments/assets/d98ebec3-ea95-4817-9767-bdd70fd51151)
![image](https://github.com/user-attachments/assets/6efdc02a-1022-4039-921d-e8b720a5aaca)

**Expected behavior**

- [ ] Add a table on the "ventilation tab" in patient dashboard (https://care-staging.ohc.network/facility/da95c77c-cf2f-4400-be53-6da766951552/patient/70ff1884-89ca-43fd-bc6c-2354cff9457d/consultation/9b1b3f6d-581d-46f3-8279-456596defd35/ventilator). The table to appear on top of the ventilator tab before the graphs of PIP and MAP
![Screenshot 2024-08-19 at 7 38 30 PM](https://github.com/user-attachments/assets/bfb45d42-4bfb-4f99-b2b4-322e646f5322)

- [ ] Indicate change in modality and vantilator mode/oxygen modality by adding a vertical line as marker on the time series graphs for the various parameters
![Screenshot 2024-08-19 at 7 40 20 PM](https://github.com/user-attachments/assets/042c3941-537e-40fb-b645-5215f8f0c525)

**Comment by Jacobjeevan** [comment]
@rithviknishad Mind assigning this to me? Thanks!

**Comment by Jacobjeevan** [comment]
I've added the vertical line as a marker, though it looks a bit weird when we switch to bar graph.

![Image](https://github.com/user-attachments/assets/12691cee-4b08-4cbe-8b1b-64f64d0889ab)

![Image](https://github.com/user-attachments/assets/32e79465-9cd4-4052-89e5-093cdc29bdab)

On a side note, if we adding the modality in the graphs themselves, wouldn't it make more sense to add the line markers to the points themselves, than the mid-points 🤔 @nihal467 

For ex: with the marker line, the image (in the original post) makes it seem like C-PAP started before 2:32 on 19/08/2024.

**Comment by nihal467** [comment]
> I've added the vertical line as a marker, though it looks a bit weird when we switch to bar graph.
> 
> ![Image](https://github.com/user-attachments/assets/12691cee-4b08-4cbe-8b1b-64f64d0889ab)
> 
> ![Image](https://github.com/user-attachments/assets/32e79465-9cd4-4052-89e5-093cdc29bdab)
> 
> On a side note, if we adding the modality in the graphs themselves, wouldn't it make more sense to add the line markers to the points themselves, than the mid-points 🤔 [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/57055998?s=64&amp;u=0144bda6b4f846b21d53b8ebab7d12af95ac557c&amp;v=4">@nihal467](https://github.com/nihal467)
> 
> For ex: with the marker line, the image (in the original post) makes it seem like C-PAP started before 2:32 on 19/08/2024.

@aparnacoronasafe can you comment on this

**Comment by aparnacoronasafe** [comment]
@Jacobjeevan This was discussed over slack.

Are there any specific issues to be addressed here?

I agree that the bar graph view does not look great. What are the alternatives we have?

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) This was discussed over slack.
> 
> Are there any specific issues to be addressed here?

Nothing as of now 👍 

> I agree that the bar graph view does not look great. What are the alternatives we have?

I'm checking the charts library we are using to see if there are any other alternatives; will update you 👍  @aparnacoronasafe

**Comment by Jacobjeevan** [comment]
I tried switching to Mark Area, which works for line charts but doesn't render correctly for bar charts; it seems to combine consecutive modes/modalities. I've attached the Mark Line ones below for reference.

Edit: For Mark Area, switching to bar chart converts all existing charts to bar, hence why we are seeing the issue below.

### Mark Area

[<img src="https://github.com/user-attachments/assets/3d423210-97df-4a38-ad2b-41fee581876d" width="400" />](https://github.com/user-attachments/assets/3d423210-97df-4a38-ad2b-41fee581876d)

[<img src="https://github.com/user-attachments/assets/9ac0c24f-57db-487d-8352-d4f38d10be3e" width="400" />](https://github.com/user-attachments/assets/9ac0c24f-57db-487d-8352-d4f38d10be3e)

[<img src="https://github.com/user-attachments/assets/8708d792-791a-4a97-a77d-49231e87d209" width="400" />](https://github.com/user-attachments/assets/8708d792-791a-4a97-a77d-49231e87d209)

[<img src="https://github.com/user-attachments/assets/a9e7b447-1e68-49e5-a727-b59afef20877" width="400" />](https://github.com/user-attachments/assets/a9e7b447-1e68-49e5-a727-b59afef20877)

### Mark Line

This is the one used earlier, but rendered with labels.

[<img src="https://github.com/user-attachments/assets/8cde3452-8cf1-4e62-9a87-62b5b5db2e09" width="400" />](https://github.com/user-attachments/assets/8cde3452-8cf1-4e62-9a87-62b5b5db2e09)

[<img src="https://github.com/user-attachments/assets/fce37c4b-19c0-466e-b667-cc758e368a44" width="400" />](https://github.com/user-attachments/assets/fce37c4b-19c0-466e-b667-cc758e368a44)

With different label position

[<img alt="" width="400" src="https://github.com/user-attachments/assets/e3e04213-751d-4f0c-bf20-85375f50a3d1">](https://github.com/user-attachments/assets/e3e04213-751d-4f0c-bf20-85375f50a3d1)

[<img alt="" width="400" src="https://github.com/user-attachments/assets/07bef21f-7ad1-4f36-a335-12b354b34015">](https://github.com/user-attachments/assets/07bef21f-7ad1-4f36-a335-12b354b34015)

@aparnacoronasafe Well, we could use the markArea feature and disable the switching to bar charts feature for these graphs, depends on how important/useful they are, or we can use markLine if the renders above work (can adjust the label position as needed).

**Comment by Jacobjeevan** [comment]
I managed to get it working with markLine, take a look and see if this works 🤔  We can adjust the label position as needed.

[<img alt="" width="400" src="https://github.com/user-attachments/assets/e3e04213-751d-4f0c-bf20-85375f50a3d1">](https://github.com/user-attachments/assets/e3e04213-751d-4f0c-bf20-85375f50a3d1)

[<img alt="" width="400" src="https://github.com/user-attachments/assets/07bef21f-7ad1-4f36-a335-12b354b34015">](https://github.com/user-attachments/assets/07bef21f-7ad1-4f36-a335-12b354b34015)

**Comment by aparnacoronasafe** [comment]
@Jacobjeevan i think mark area looks better. 

Let's retain the bar graph option as well? 

Also could you add (IV/NIV/O2) also against the ventilator mode/oxygen modality mentioned?

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) i think mark area looks better.
> 
> Let's retain the bar graph option as well?
> 
> Also could you add (IV/NIV/O2) also against the ventilator mode/oxygen modality mentioned?

@aparnacoronasafe Sure, we can add those.

We can keep the bar graphs, however there's some inconsistency in how it depicts the data for markArea🤔 

For example: In the line chart, NP starts at 2:45PM (which is correct), but switching to bar chart, NP shows up later (I've highlighted 2:45PM on the bar chart below). Not only that, but the time divisions between NP/SFM/HFNC isn't as clear.

[<img src="https://github.com/user-attachments/assets/5cb75c19-6cf4-4ddf-854d-f7a0d53849b4" width="400" />](https://github.com/user-attachments/assets/5cb75c19-6cf4-4ddf-854d-f7a0d53849b4)

[<img src="https://github.com/user-attachments/assets/94ce7324-9df0-488b-aaf0-df350f1a0a4e" width="400" />](https://github.com/user-attachments/assets/94ce7324-9df0-488b-aaf0-df350f1a0a4e)

**Comment by Jacobjeevan** [comment]
After discussing with team, going with the markLine since markArea presents inaccurate data when switching to bar charts. Here's how the latest looks.

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/bd14d419-df3d-44ed-9263-fd6dad94012f">

<img width="580" alt="image" src="https://github.com/user-attachments/assets/94c4978e-b718-4708-a1e1-f21fe815cc81">

<img width="580" alt="image" src="https://github.com/user-attachments/assets/674a0bbe-e434-4afc-a369-842d320870bb">

**Comment by aparnacoronasafe** [comment]
Looks good @Jacobjeevan 

However, I donot see the current ventilator mode marked in the graph. in the above eg, IV-PCV should also be marked in the right end of the graph right? Could you check?

**Comment by Jacobjeevan** [comment]
> Looks good @Jacobjeevan 
> 
> However, I donot see the current ventilator mode marked in the graph. in the above eg, IV-PCV should also be marked in the right end of the graph right? Could you check?

@aparnacoronasafe ah, good catch, I had excluded the latest datapoint to render markArea graphs; I'll get it fixed :+1:

**Comment by Jacobjeevan** [comment]
Fixed the above (render the most recent modality/mode on graph).

![Image](https://github.com/user-attachments/assets/e8a4a3ba-ecb3-4380-ab65-83e23803a2fe)
