### ISSUE TITLE
Neurological Tables having incorrect vertical heights for table values causing it to have extra whitespace at the bottom

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8265]
> Originally posted by @nihal467 in https://github.com/coronasafe/care_fe/pull/8119#issuecomment-2270501028

**Describe the bug**
Neurological Tables having incorrect vertical heights for table values causing it to have extra whitespace at the bottom

**To Reproduce**

1. Go to a patient's consultation dashboard
2. File a log update whose round type is "Detailed Update" with the Neurological Monitoring section filled.
3. See the Neuro tab in the consultation dashboard (or see [this](https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/neurological_monitoring) consultation)

**Expected behavior**
Vertical heights should be correct.

**Screenshots**
![image](https://github.com/user-attachments/assets/31e1851c-8de6-4c3f-ac24-90a953cfed49)

**Comment by 0xvish** [comment]
May I take up this issue please?

**Comment by rithviknishad** [comment]
@thevishvammoliya Any updates on this?

**Comment by 0xvish** [comment]
> @thevishvammoliya Any updates on this?

On it, had been facing some issues due to inconsistencies in the code, shall I re-develop it with other layout?

**Comment by rithviknishad** [comment]
Yup! That'd be nice! Ensure the new re-developed one has proper type-safety and also drop a UI mockup here before working on it.

**Comment by 0xvish** [comment]
I  think it can be solved by adjusting some padding and line height values, do these look good?
![image](https://github.com/user-attachments/assets/3e3cc53f-df54-43b1-97bc-c9b5fc587bbf)
![image](https://github.com/user-attachments/assets/eaba8dc5-7d79-482f-bb59-c4c621588e8d)

**Comment by rithviknishad** [comment]
Yup!
