### ISSUE TITLE
Change the ABDM error to human readable format

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8266]
**Describe the bug**

Currently, the error message in the ABDM is not user friendly

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/577f0f61-1597-4d0b-956e-b0df1d92ae74)

**Comment by khavinshankar** [comment]
Most of the ABDM errors are made human-readable in the plugs, some of it is already been tested. And also implementing v3 APIs should improve it a lot as ABDM error messages have improved a lot.
