### ISSUE TITLE
Enhancement to the prescrition print module

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8275]
follow-up : https://github.com/coronasafe/care_fe/pull/8259

**Is your feature request related to a problem? Please describe.**

- [ ] currently the print button is not properly placed, seem like the button is on one corner of the page.
- [ ] we are having multiple scroll in the page, seem a little bit odd

**Describe the solution you'd like**

- [ ] move the print button inside the white padding on prescription
- [x] #8323

![photo_2024-08-08_15-53-24](https://github.com/user-attachments/assets/700cc6d5-3675-43b7-a3e7-d424b40ddaec)

**Screenshot **

![image](https://github.com/user-attachments/assets/f7f66b6e-be51-4070-bdc2-d347f1e107fa)
![image](https://github.com/user-attachments/assets/d072f194-82b0-4477-99c8-9f4ca8606add)

**Comment by Fredrick2503** [comment]
How can I reproduce this issues?

**Comment by nihal467** [comment]
@Fredrick2503 

> How can I reproduce this issues?

1. Login to the care
2. go to the patient tab using the side bar
3. click on the patient card with active consultation
4. in the consultation page, below the diagnosis card, click on the medicine tab in the nav bar
5. on your the medicine pages, click on the edit prescription button
6. now you will be seeing the page mention related to first point 
7. now click on the print button
8. now you will be seeing the page mention related to second point

**Comment by kushalbhana** [comment]
Would love to work on it..

**Comment by Fredrick2503** [comment]
Can I be assigned to the issues as I would like to work on this issues

**Comment by nihal467** [comment]
@Fredrick2503 / @kushalbhana are you still interested in working on this issue?

**Comment by kushalbhana** [comment]
working on it...

**Comment by kushalbhana** [comment]
just let me know Do I have to modify the css of all the components in this print preview to make it responsive 
or is there any better way to do it

**Comment by rithviknishad** [comment]
@kushalbhana No, scaling the inner contents of the PrintPreview contents manually using tailwindcss modifiers could be difficult to maintain. Instead you could use the `scale-*` tailwind class (or CSS equivalent) at the `section-to-print` of the reusable generic PrintPreview component instead.

I've opened a separate issue for this with a more detailed description here: https://github.com/coronasafe/care_fe/issues/8323

Feel free to take that up

cc: @kushalbhana @Fredrick2503
