### ISSUE TITLE
Enhancement to the CARE Scribe

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8285]
Follow-up : https://github.com/coronasafe/care_fe/pull/8183#issuecomment-2274437517

**Is your feature request related to a problem? Please describe.**

- [ ] he diagnosis is not being auto-filled based on the diagnosis code
Note: Auto-fill only works if we say the name of the diagnosis cholera, not the code 1A00
- [ ] We cannot discontinue a medicine using the scribe because the scribe is unaware of the currently filled data.
- [ ] The errors are not normal user-friendly messages for example whisper failed, error creating scribe instance, something went wrong

**Describe the solution you'd like**

- [ ] diagnosis autofill should be work based on code
- [ ] scribe should be aware of currently filled data to interact with existing filled data
- [ ] make the error message normal user friendly [ @shivankacker  can you push a fix  for this  alone First, before working on the other enhancements ]

**Comment by bodhish** [comment]
@nihal467 why should we autofill based on code? Is this a user requirment?

**Comment by nihal467** [comment]
@bodhish no such requirement came from users so far, the enhancement was requested based on a hypothetical situation where user want to add a specific icd11 code itself via audio

**Comment by shivankacker** [comment]
> make the error message normal user friendly [ @shivankacker can you push a fix for this alone First, before working on the other enhancements ]

@nihal467 can you specify which error you are talking about and how I can replicate?

**Comment by nihal467** [comment]
![image](https://github.com/user-attachments/assets/2569adb7-3fbd-496c-9223-e1df078282d5)

@shivankacker  One of the error message attached above, which was shown, last week, when scribe was not able to start because level of consciousness ID was changed. The error message won't make sense to a normal user

**Comment by shivankacker** [comment]
@nihal467 I will remove the "Something went wrong..." and change "Error creating scribe instance" to "Scribe servers are down, please try again later". Does that sound good?
