### ISSUE TITLE
Modify the UI of events log switch tab

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8286]
**Describe the bug**

Currently the switch tab of events & daily road and filters button in the consultation page are utilizing two separate rows, unnecessarily 

**To Reproduce**

1. Go to the patient tab
2. click on a active consultation
3. See error

**Expected behavior**

- [ ] keep the daily round & events and filter button to a single row 
- [ ] Remove the sort-by button in the events green border to make it similar to the filter button in daily rounds
- [ ] When the sort by is active in events, make it the primary color to show sort by is active 

**Screenshots**

![image](https://github.com/user-attachments/assets/9c6d1e1d-cc6e-46d9-818b-ab7d9a4e2026)
![image](https://github.com/user-attachments/assets/0f183a07-9a9b-444e-b868-440e3a85dcff)

**Comment by JOSHIK27** [comment]
https://github.com/user-attachments/assets/42e51659-108f-4f5f-81bb-ce4e391b7ce5

I have brought them to single row by creating filter ui elements in the parent component (removed the logic related to them in child components where they were present initially) and passed the corresponding query values of both filter ui as props to components which render the result obtained from filtering. Adjusted the grid to 3 columns. Please let me know if this is what you wanted ? and happy to modify if anything @rithviknishad

**Comment by rithviknishad** [comment]
The "sort by" and "filter" is NOT a tab right? Can we keep it outside the tab switch?

**Comment by JOSHIK27** [comment]
> The "sort by" and "filter" is NOT a tab right? Can we keep it outside the tab switch?

https://github.com/user-attachments/assets/9a32ff26-1b2f-42e5-a1ed-f6ff424a4851

There is some inconsistency in the appearance of filter buttons. How do we make it better ? any inputs @rithviknishad

**Comment by rithviknishad** [comment]
We could use a Popover with 3-dot menu or filters icon for both. And keep the sort by as an option (select menu) in the popover instead.

**Comment by JOSHIK27** [comment]
> We could use a Popover with 3-dot menu or filters icon for both. And keep the sort by as an option (select menu) in the popover instead.


is this how you wanted @rithviknishad ? Let me know if any changes required.

https://github.com/user-attachments/assets/d098d94f-47b3-4176-a166-bb1a0b8dc4b3

**Comment by rithviknishad** [comment]
This seems to be nested popovers which was not what I intended.

Let's inline the filter contents to the first popover itself.

Also could you make the 3-dot menu to use to `<ButtonV2>`? The current button doesn't seem to be clickable.

<img width="602" alt="image" src="https://github.com/user-attachments/assets/64de6bdc-ad2a-4a03-b0ea-b5319a726e7c">

**Comment by JOSHIK27** [comment]
> This seems to be nested popovers which was not what I intended.
> 
> Let's inline the filter contents to the first popover itself.
> 
> Also could you make the 3-dot menu to use to `<ButtonV2>`? The current button doesn't seem to be clickable.
> 
> <img alt="image" width="602" src="https://private-user-images.githubusercontent.com/25143503/369332894-64de6bdc-ad2a-4a03-b0ea-b5319a726e7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjIyMjIsIm5iZiI6MTcyNjgyMTkyMiwicGF0aCI6Ii8yNTE0MzUwMy8zNjkzMzI4OTQtNjRkZTZiZGMtYWQyYS00YTAzLWIwZWEtYjUzMTlhNzI2ZTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA4NDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMzA1NjVjMTU3ZTA5ZDk1MTkzMjA0NjA3YTJiZWFmOGQ2YTc4MDQ2M2E2ZWM4OTExYzcyNDRlMTFlMjZmOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-29nrhAtDaonDtxa2wbiowwiq9foPvESAJSKB2nc46E">

Sure ill change. 

Update: @rithviknishad As both filter ui components are different (popover, dropdown), it was straight forward to achieve the requirement for popover botton since we are creating a popover (3 dot). Inorder to have same appearence for both i had to change core menu component (not custom dropdownmenu component) . It will affect in other places as it is imported. So, i have pass label of menu as "None" and conditionally rendered 3 dot button to maintain same appearence. 

Let me know what you think.


https://github.com/user-attachments/assets/d57a83a4-af8e-4564-afb9-06da08fb2122

**Comment by rithviknishad** [comment]
Checkout `SelectMenuFormField`. Lets use Popover for both sort by and filter. The sort by popover can contain SelectMenuFormField as it's child.

**Comment by rithviknishad** [comment]
Also let the 3-dot button's variant be "secondary", also ensure it's square. Would be difficult to click if so slim.

**Comment by rithviknishad** [comment]
Hey @JOSHIK27 

Any updates on this? Stuck somewhere?

**Comment by JOSHIK27** [comment]
> Hey @JOSHIK27
> 
> Any updates on this? Stuck somewhere?

Apologies for the delay. I could not find SelectMenuFormField anywhere in neither headless ui elements nor the codebase. Checked with headlessui documentation. Am i missing something ? Could you please direct me with this element. I'll give u the update about pr eod.

**Comment by rithviknishad** [comment]
My bad, it's `SelectFormField`

**Comment by JOSHIK27** [comment]
> My bad, it's `SelectFormField`

thank you. Will look into it

@rithviknishad if we use selectformfield inside popover panel for sortbydropdown filter, would not that be a nested one as earlier ?

Update:

Instead of using selectformfield, i rendered all the options in the popover panel as divs with exact styling as selectformfield options for consistency. Now both filters are popvers. Please let me know if anything needs to be changed

https://github.com/user-attachments/assets/999de6e5-783d-4832-8ada-a61c64bdf259

**Comment by bodhish** [comment]
@nihal467 whats the status here? Also link the PR

**Comment by nihal467** [comment]
@bodhish i think you mis tagged me, @rithviknishad @JOSHIK27 can you share the status on this issue and link the PR

**Comment by rithviknishad** [comment]
@JOSHIK27 the recording shared in the last comment looks fine to me

**Comment by JOSHIK27** [comment]
> [@JOSHIK27](https://github.com/JOSHIK27) the recording shared in the last comment looks fine to me

Sure. Will create the pr.

**Comment by JOSHIK27** [comment]
Here's the [pr](https://github.com/ohcnetwork/care_fe/pull/8825 ) 
Please let me know if any thing needs to be changed. @rithviknishad
