### ISSUE TITLE
Discharge diagnosis

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8299]
**Is your feature request related to a problem? Please describe.**
When a patient is admitted, the diagnosis is marked by the doctor usually at the time of first consultation. This is then revised multiple times through the admission. Both the diagnosis itself or the diagnosis type alone may be updated during the term of admission.

It is important to prompt the user to update the diagnosis for a final time right before discharge. 

This is important since the patient may not be completely disease-free at discharge. He may simply be free of the life-threatening condition but may still have many underlying chronic illnesses for which the doctor may have suggested some medication in the discharge prescription field. 

**Describe the solution you'd like**
For an encounter with "Admission", based on the discharge reason, make the following edits in the discharge pop-up

1. *RECOVERED*

- [ ] Add a section for 'Diagnosis at discharge'- show the latest list of diagnoses (along with type) and allow user to make changes
- [ ] reorder the form in the following way
- Reason
- date and time of discharge
- Diagnosis at discharge
- Discharge prescription
- Discharge advice

2. *REFERRAL*

- [ ] Add 'Diagnosis at discharge' below date and time of discharge - show the latest list of diagnoses (along with type) and allow user to make changes

3. *LAMA*

- [ ] Add 'Diagnosis at discharge' below date and time of discharge - show the latest list of diagnoses (along with type) and allow user to make changes

**Describe alternatives you've considered**

**Additional context**

**Comment by JOSHIK27** [comment]
I would like to work on this issue if the submission of the new field i.e 'Diagnosis at discharge' is handled by the backend api endpoint [ **/api/v1/consultation/{id}/discharge_patient/** ] @rithviknishad

**Comment by rithviknishad** [comment]
Yes @JOSHIK27 

However, there's a reusable component [`EditDiagnosesBuilder`](https://github.com/coronasafe/care_fe/blob/develop/src/Components/Diagnosis/ConsultationDiagnosisBuilder/ConsultationDiagnosisBuilder.tsx#L83). You could simply use that. 

To populate it with initial value, you could use the [`useQuery`](https://github.com/coronasafe/care_fe/blob/develop/src/Utils/request/useQuery.ts) hook with the [pre-defined API route](https://github.com/coronasafe/care_fe/blob/develop/src/Components/Diagnosis/routes.ts#L12) for fetching consultation diagnosis instead of manually calling the specified API.

Creation of new diagnosis entries and updating of existing diagnosis entries is handled automatically by the component itself. No need to write any API calls related logic for it.

**Comment by JOSHIK27** [comment]
Sure. Thanks

> Yes @JOSHIK27
> 
> However, there's a reusable component [`EditDiagnosesBuilder`](https://github.com/coronasafe/care_fe/blob/develop/src/Components/Diagnosis/ConsultationDiagnosisBuilder/ConsultationDiagnosisBuilder.tsx#L83). You could simply use that.
> 
> To populate it with initial value, you could use the [`useQuery`](https://github.com/coronasafe/care_fe/blob/develop/src/Utils/request/useQuery.ts) hook with the [pre-defined API route](https://github.com/coronasafe/care_fe/blob/develop/src/Components/Diagnosis/routes.ts#L12) for fetching consultation diagnosis instead of manually calling the specified API.
> 
> Creation of new diagnosis entries and updating of existing diagnosis entries is handled automatically handled by the component itself. No need to write any API calls related logic for it.

**Comment by JOSHIK27** [comment]
https://github.com/user-attachments/assets/b22c237a-5365-43c1-98fb-9d96937091cb

I have added the section 'Diagnosis at discharge' and changed the order as instructed above. I fetched the diagnosis from corresponding end point using useQuery hook as you told @rithviknishad. Let me know if its what you needed.

**Comment by rithviknishad** [comment]
Yup! Raise the PR

**Comment by JOSHIK27** [comment]
Here's the pr #8390 @rithviknishad
