### ISSUE TITLE
Qualification field for nurse user type

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8302]
**Is your feature request related to a problem? Please describe.**
Nurses may be of various types based on qualification. Capturing and showing this in CARE is helpful. 

**Proposed Solution**

- [ ] User creation form (https://care.coronasafe.in/users/add) when user type is selected as "Nurse" add a field for "Qualification" with short text field. (the field is available for doctor user type already)

- [ ] In edit profile form (https://care.coronasafe.in/user/profile) , add the field so that the nurse can update/edit the qualification as needed.

- [ ] Show Qualification in user list (https://care.coronasafe.in/users?page=1&limit=18&user_type=Nurse) for nurses (follow the design from doctors listing where qualification is already there)

**Comment by ayushpatil2122** [comment]
hey i want to work on this issue 
can you assign this issue to me

**Comment by gigincg** [comment]
@ayushpatil2122 Please add an explanation on how you'll be implementing a solution

**Comment by aparnacoronasafe** [comment]
@nihal467 Could you please follow up and move this ?

**Comment by AdityaJ2305** [comment]
Hey @aparnacoronasafe @gigincg, could you please assign this issue to me if it's still available?

I've almost finished the task. The payload now successfully sends the `nurse_qualification` key to the backend, and the qualification field is displaying properly in the user edit view for nurses. Until the backend updates the users list, the nurse qualification is showing as 'unknown,' similar to how it works for doctor qualifications.

Screenshots for reference:
<img width='403' alt='Screenshot 2024-09-29 at 6:17 PM' src='https://github.com/user-attachments/assets/206ea1ae-6861-4ec1-8c08-118443c87131'>
<img width='363' alt='Screenshot 2024-09-29 at 6:18 PM' src='https://github.com/user-attachments/assets/c34607de-4dcf-4277-a8fc-71a3dd0f5875'>
<img width="1102" alt="Screenshot 2024-09-29 at 6 23 39 PM" src="https://github.com/user-attachments/assets/67631e41-0efd-45b9-a02c-bb625589291e">

**Comment by rithviknishad** [comment]
We already have a qualification field named `doctor_qualification`. Should we consider renaming the field to `qualification` instead of using it?

cc: @gigincg

**Comment by AdityaJ2305** [comment]
@rithviknishad, I’m not certain if I’m allowed to comment on this, but since we’re already sending `doctor_qualification: undefined` for other user types, it might be better to update it to  `qualification` field instead of creating a new key like `nurse_qualification`. We can set the relevant values for both doctors and nurses while keeping it undefined for other user types. This approach would minimize backend changes.
<img width="844" alt="Screenshot 2024-09-30 at 11 08 13 AM" src="https://github.com/user-attachments/assets/3b79ef4d-f188-43c8-bd1c-cdacf15e9653">

**Comment by rithviknishad** [comment]
Yes, let's proceed with:

1. Rename the field in the backend to `qualification`
2. Update the FE as per the requirements mentioned in the issue.

**Comment by AdityaJ2305** [comment]
Understood! I'll update the frontend as per the issue. For the backend, I'll create a new issue to track the renaming of the field to `qualification` and handle the update accordingly. Let me know if there's anything else I should consider.

**Comment by rithviknishad** [comment]
Just confirming, would you be creating the backend PR also?

**Comment by AdityaJ2305** [comment]
I have limited experience with Django and Python, but I’m willing to create the backend PR. Any guidance from the maintainers would be appreciated!

**Comment by rithviknishad** [comment]
You can start by renaming instances of "doctor_qualification" with "qualification" in the backend repo (except for the ones that are in the existing migrations). 

And then you can run the `makemigrations` command to generate the `RenameField` DB schema migration which django generates for you automatically.

References:
- https://school.ohc.network/targets/19486
- https://docs.djangoproject.com/en/5.1/ref/django-admin/#django-admin-makemigrations

**Comment by AdityaJ2305** [comment]
Backend issue created for the same [here](https://github.com/ohcnetwork/care/issues/2513)

**Comment by rithviknishad** [comment]
Here's the backend: https://github.com/ohcnetwork/care/pull/2514
