### ISSUE TITLE
Default route for medication should be 'Oral' on Domiciliary Care

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8303]
In palliative care, 95% medicines administered are given orally, hence require an option to reduce time wastage. So default route for medications should be selected as "oral" . It should be triggered only for domiciliary care patients. Also Users should be able to select other routes if needed. 

steps to reproduce
- Create a patient and update consultation page
- Select decision after consultation as "Domiciliary Care" 
- update other details and submit the page
- Select "Medicines" from the patient dashboard page
- click on edit prescription
- add a medicine
- click on routes
currently there are several routes on the dropdown, so make "Oral" as default and the user should be able to select the other routes if needed.

**Comment by noufalrahim** [comment]
@samholics can u assign this to me..?
