### ISSUE TITLE
Treating Doctor field should not be mandatory for Domiciliary Care patients 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8304]
**Describe the problem**
Currently treating doctor field is mandatory to all type of patients for filing consultation. 

However in Domicilary care scenario there wont be a doctor assigned at first to visit the patient at home and update consultation details. usually nurses will  update these details. So the mandatory treating doctor field is restricting them to update patient details smoothly. 

1. create a patient file
2. select decision after consultation as Domiciliary Care
3. Scroll down treating doctor field

**Suggested solution**
Treating doctor field shouldn't be mandatory for Domiciliary care patients. This is, consultation forms where "Domiciliary care" is selected under decision after consultation, Treating doctor field shouldn't be mandatory.

**Comment by JOSHIK27** [comment]
Hi. Can i work on this issue @aparnacoronasafe  @samholics @rithviknishad 

[edited]
Here's the demo. Please let me know if this is what you wanted. Happy to open the pr.

https://github.com/user-attachments/assets/cc99e796-677e-44af-bb76-c3ddd403012e

**Comment by rithviknishad** [comment]
Yup, create a PR 🚀

**Comment by JOSHIK27** [comment]
> Yup, create a PR 🚀

Here's the pr https://github.com/coronasafe/care_fe/pull/8360 @rithviknishad

**Comment by JOSHIK27** [comment]
Here's the new pr #8391 @rithviknishad
