### ISSUE TITLE
Add "abdominal drain" and corrrect spelling for "Ryles tube aspiration" on Output dropdown on IO Balance

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8305]
**Describe the bug**
Add "Abdominal Drain" on Output dropdown.
Correct the spelling of Ryles tube aspiration on the dropdown. currently its mentioned as 'Rules tube aspiration"

**To Reproduce**

1. Go to logupdate
2. Click on detailed update
3. Scroll down to save and select IO balance parameter
4. goto  output
5. see error

<img width="577" alt="image" src="https://github.com/user-attachments/assets/453b8be6-82f3-48e6-a085-900f1f281d06">

**Screenshots**

**Comment by aSriram199** [comment]
i want to work on this issue

**Comment by rithviknishad** [comment]
https://github.com/coronasafe/care_fe/blob/develop/src%2FComponents%2FLogUpdate%2FSections%2FIOBalance.tsx#L9

**Comment by aSriram199** [comment]
Hello @rithviknishad,

I have created a pull request for issue #8305, https://github.com/coronasafe/care_fe/pull/8328#issue-2466280747

**Comment by rithviknishad** [comment]
@aSriram199 does existing data (records created before this PR) show the new corrected spelling in view log update details page / edit log update page?

**Comment by aSriram199** [comment]
Hello @rithviknishad, I’m not entirely sure, i think the existing data need migration
