### ISSUE TITLE
Nursing Care suggestions on Consultation page (Discussion Needed)

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8307]
**Is your feature request related to a problem? Please describe.**
The list of Nursing care is very limited in CARE. The list needs to be expanded to let nurses mark information against various other kinds of nursing care commonly provided to the patients

**Proposed Solution.**
Add more option for nursing care> Detailed Log update (https://care-staging.ohc.network/facility/da95c77c-cf2f-4400-be53-6da766951552/patient/70ff1884-89ca-43fd-bc6c-2354cff9457d/consultation/9b1b3f6d-581d-46f3-8279-456596defd35/daily_rounds/f4a24e2d-1f45-4063-87a9-eb5790710a5a/update)

Oral Care
Hair care
Bed bath
Eyecare
Perineal care
Skin care
Catheter change
Ryle’s tube change
PRE enema
Lymphedema Care
Others

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.

**Comment by SwanandBhuskute** [comment]
I would like to work on this , pls assign me @bodhish @nihal467 @rithviknishad

**Comment by SwanandBhuskute** [comment]
![Image](https://github.com/user-attachments/assets/35b6336d-30b4-4174-b511-49d460a93603)
Do we need to update the options here in the medical history?

**Comment by khavinshankar** [comment]
Already resolved by @rithviknishad
