### ISSUE TITLE
Re-design prescription Module. (Discussion needed)

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8308]
**Re-design Prescription Module.**
 
Current prescription module needs to be redesigned to be more user friendly. 

Issues with the current prescription module:

- [ ] Cannot be placed as part of a form. The action of adding a medicine through the pop up window directly saves the medicine, even if the user cancels the form. Hence this prescription adder works as a single function, but not as part of a form. 
Eg: current Doctor's progress note. Try to open Doctor's progress note, add multiple medicines. Then cancel the form. Everything else in the form is deleted, however, you will notice that the edits to prescription is saved. 

- [ ] Users complain that it takes too much time to add one medicine at a time. They prefer a tabular presentation where they can type in/ select multiple medicines, mark other details and save all together

- [ ] More forward looking requirement is the capability to have prescriptions come up as suggestions. This may be presented as a greyed-out list, against each item in list a doctor will mark "Yes/No" to accept the medication suggestion or reject it. 
**Why is this relevant?**
1) This is relevant to reconcile mediation when the patient is transferred from one ward to another. Ideally the treating doctor must be made to review the list of active prescription in the previous ward, and accept or reject to creat an updated active prescription.
2) Same feature will also be useful in Order Sets. Order sets are basically a set of instructions and doctors always add to their consultation for a type of patient. This is mostly only for ICU patients. If patient has COVID, the order set might consist of 5 medication with dosage frequency etc which the doctor can import as suggest and then accept or reject each medicine to easily fill out consultation. Such "Order sets" are extremely useful in standardising quality of care in hospitals.

**Comment by gigincg** [comment]
@aparnacoronasafe / @samholics Can you expand "This is relevant to reconcile mediation when the patient is transferred from one ward to another. Ideally the treating doctor must be made to review the list of active prescription in the previous ward, and accept or reject to creat an updated active prescription."

**Comment by aparnacoronasafe** [comment]
There must be continuity to prescription when a patient is moved from one ward to another. 

A lot of drugs given in the ICU cannot be stopped suddenly. They may need to be veined off it by reducing dosage. Also, there may be other life-saving drugs that the patient may have been taking long term.

We need to be able to enable continuity across 
1. Home medication
2. medication prescribed in various wards
3. Discharge medication

Eg: When the patient gives information that he takes Med A and Med B at home, at the time of admission, that must be added to Home medication and the doctor giving first prescription, should be able to see the list to decide whether to continue the meds in the hosp, or replace it with either similar meds or to stop it altogether. 
His first prescription at the time of admission to ICU maybe
Med A
Med B
Med C
then when the patient is downshifted from ICU to ward, all active medication must be renewed. 
Same process must happen when doctor prescribes discharge medication. He must be able to see the last list of active medication.

**Comment by aparnacoronasafe** [comment]
@gigincg is this clear?

**Comment by gigincg** [comment]
@aparnacoronasafe Need more depth on, 
1. How different is Home Medication & Discharge Medication. 
2. Does showing all prescriptions as suggestions for Discharge Medication solve the issue with Discharge Medication
3. How do you plan to differentiate between location of Prescription, the Prescription for the Patient persists across any location the Patient is at.  Can you explain the expected flow of review when a Patient is internally shifted to a different Bed.

**Comment by aparnacoronasafe** [comment]
> 1. How different is Home Medication & Discharge Medication.

Discharge medication becomes home medication if the patient is admitted again.
Home medication is any medication the patient is having otherwise at the time of admission
Discharge medication is the medication the doctor prescribes the patient to have at home after discharge.

> 2. Does showing all prescriptions as suggestions for Discharge Medication solve the issue with Discharge Medication

All active prescriptions must come as suggestion. Yes that would solved the problem.
The same must happen a admission and transfer between locations also. 

> 3. How do you plan to differentiate between location of Prescription, the Prescription for the Patient persists across any location the Patient is at.  Can you explain the expected flow of review when a Patient is internally shifted to a different Bed.

Location need not be mapped to a prescription. But its a good practice for doctor to review the prescription as the patient moved from one location to another, particularly when the patient is moved between ICU and non-ICU beds. There are some medicines that are exclusively administered at ICU, these are the medication that might require close monitoring of vitals to ensure correct dosage. Such medicines are avoided in normal wards. So doctors would want to review the medication list to replace such medication with more 'safer' ones

**Comment by gigincg** [comment]
@aparnacoronasafe I agree with the change needed when Dishcarging, but I believe we do not have enough field implementation and feedback to implement the same for Internal Shifting.

**Comment by aparnacoronasafe** [comment]
This is absolutely necessary at the time of admission too. For the doctor to see the list of home medication. 

Internal transfers, we could revisit when we have enough input from doctors. However, the discharge medicine reconciliation component may be developed keeping in mind the use cases at various times through the encounter including internal transfers.

**Comment by nihal467** [comment]
non-relevant to current develop
