### ISSUE TITLE
Add Next and Previous Scroll button for files preview

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8321]
**Is your feature request related to a problem? Please describe.**
Currently the files preview only supports one file . There is no option to move to the next file preview or previous one. Only option is  close it and open the next one. Doctors in the field find its very difficult because often they upload lot of files and each time they need to open one by one. it takes lot of their time to assess patient files.

steps to reproduce
- Open a patient file
- Click on "files" from the patient dashboard
- upload some files and open one
- see the error

**Describe the solution you'd like**

- [ ] Avail a Next button or a " > "  on the right side and Previous button or " < " on the left.

If the first file is opened the previous button shouldn't be visible and if the last file is opened the Next button shouldn't be visible.

<img width="776" alt="image" src="https://github.com/user-attachments/assets/023e4251-2710-4cd6-892b-372d51207d14">

- [ ] Also increase the font size of the file name and add "Created on date and time" in fine text below the name. This would allow doctor to have more context on what image/document he/she is looking at. The text "File preview" may be reduced the font size.

**Additional context**
This feature will helps the doctors to Scroll through different files and assess the patients easily.

**Comment by aSriram199** [comment]
i want to work on this issue @samholics

**Comment by HarshikaAdarsh** [comment]
Hey, I would like to work on this issue.

**Comment by rithviknishad** [comment]
@HarshikaAdarsh it is advised to finish other issues that are assigned before picking up new issues to be assigned.

**Comment by HarshikaAdarsh** [comment]
Understood @rithviknishad

**Comment by vivek-anand-singh** [comment]
@rithviknishad I would like to work on this . Please assign the issue to me .

**Comment by vivek-anand-singh** [comment]
Hi @rithviknishad,
I hope you're doing well! I was wondering if you could provide more details regarding the API for fetching patient files. Specifically, I'd like to know the exact endpoint for retrieving files related to a patient's shift.

**Comment by NitinPSingh** [comment]
can i take this issue?

**Comment by vivek-anand-singh** [comment]
Hi @rithviknishad,

I hope you're doing well! I just wanted to follow up on my previous message regarding the API for fetching patient files. Could you please provide more details on the specific endpoint for retrieving files related to a patient's shift?

I understand you might be busy, but your guidance would be really helpful for moving forward with the task.

**Comment by sarvesh-official** [comment]
Hi @rithviknishad ,

I would like to work on this issue. Could you please assign it to me?

**Comment by sarvesh-official** [comment]
Hi @rithviknishad , could you please review the PR at your earliest convenience? Let me know if it's good to merge, or feel free to suggest any changes. Thanks!
