### ISSUE TITLE
Add validation for max dosage in PRN prescription

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#8324]
![image](https://github.com/user-attachments/assets/30289866-5f87-4944-b9db-ce2ef90ff122)

Add frontend and backend validation to check that max dosage in 24 is greater than or equal to base dosage

backend issue: https://github.com/coronasafe/care/issues/2383

**Comment by Nithin9585** [comment]
I have created a pull request to address this issue: [#8378](https://github.com/coronasafe/care_fe/pull/8378). 

Please review the changes when you get a chance. Thank you!
