### ISSUE TITLE
Facility Notice functionality is not working properly

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8333]
**Describe the bug**

When you try to input anything to the facility notice a pop-up, it is not accepting the user input 

**To Reproduce**

1. Go to facility page
2. Click on notify button
3. try to try something

**Expected behavior**

The user should be able to type in the text 

**Screenshots**

![image](https://github.com/user-attachments/assets/7deacc9d-924a-4b3d-aa84-e6b38941ce6f)

**Comment by aSriram199** [comment]
i want to work on this @nihal467

**Comment by aSriram199** [comment]
https://github.com/coronasafe/care_fe/pull/8337 @nihal467
