### ISSUE TITLE
UX Enhancement for Middleware Override Workflow.

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8335]
**Is your feature request related to a problem? Please describe.**

Currently, when the middleware of an asset is taken from the facility configuration page or location management page, the middleware field is auto-filled as a placeholder. By hovering over the exclamation button, the user can understand from which page this middleware is pre-filled.

However, new users are raising concerns that they are finding it difficult to understand the priority-based asset middleware overrides. For example, the middleware specified in the asset configuration is given the highest priority, followed by location management, and lastly, the facility configuration 
 
![image](https://github.com/user-attachments/assets/46992429-2e5f-4c61-a4fe-a59db7ffabf0)
![image](https://github.com/user-attachments/assets/366314b7-3f86-47a2-bf01-893f9bc43e30)

**Describe the solution you'd like**

![Screenshot 2024-08-16 161325](https://github.com/user-attachments/assets/8aac7e3f-8a8a-40cb-883e-90ca89d2bfea)

- [ ] When the asset configuration is pre-filled from the location management or facility page, instead of making the user hover over the exclamation mark, add fine text below the input box, along with the pre-filled middleware placeholder, to provide details about the middleware's source.

![image](https://github.com/user-attachments/assets/7faf855c-a93a-413c-9bbc-0ebdbd6e07ed)

- [ ] Implement a similar pre-filling behavior in the placeholder and fine text for the location management edit page.
- [ ] In the location creation form, under the middleware field, add fine text indicating that if left blank, the facility middleware will be applied to assets.

![image](https://github.com/user-attachments/assets/4cbb8b4f-794f-4a42-b7a1-66152c6ec24f)

- [ ] In the location management card, display the facility configuration middleware with a "Pre-filled Facility Middleware" badge if no middleware is set for the location.

![image](https://github.com/user-attachments/assets/9d67b8f0-b417-4683-baee-4563c289d324)

- [ ] Under the facility configuration middleware field, add fine text stating that the facility middleware will be applied to all assets when asset and location middleware are Unspecified.

Note: 

- In the relevant places, Try to add the facility name or location in the fine text so users can easily understand the exact source, rather than a general fine text message.
- The attached UI is a sample mock-up for reference. Feel free to share the proper UI mock-up on the issue before starting work on it.

**Comment by nihal467** [comment]
discussion label was removed as @gigincg approved the issue

**Comment by saikiranpatil** [comment]
I am interested to solve this issue, but i am having trouble in understanding, can anyone explain how to reproduce the above, and what changes are to be added. @gigincg @nihal467

**Comment by nihal467** [comment]
@saikiranpatil are you still interested in working on this issue

**Comment by saikiranpatil** [comment]
> @saikiranpatil are you still interested in working on this issue

Yes

**Comment by saikiranpatil** [comment]
i am having trouble in understanding, can anyone explain how to reproduce the above, and what changes are to be added.

**Comment by nihal467** [comment]
Steps to Access Facility Middleware Page

1. Go to the facility tab
2. click on the view facility button on any facility card
3. once you are in the page click on the manage facility button
4. from the dropdown, click the config facility button
5. you will be seeing the below page

![image](https://github.com/user-attachments/assets/3117f03c-bfce-4f00-a90c-e4bc1fa554c9)

steps to access location middleware page

1. Follow the above step 1-3
2. then from dropdown click the location management button
3. click on the add location button on the top right corner
4. you will be seeing the below page

![image](https://github.com/user-attachments/assets/56c5a4a2-a0dc-41b2-98ce-33493a018fed)

steps to access asset middleware page

1. follow the top step 1-3
2. then from the dropdown click the view asset button
3. click on any camera asset card ( It will have a camera icon ) , case not available create a new asset
4. now click on the configuration button
5. you will be seeing the below page

![image](https://github.com/user-attachments/assets/bf630ee3-37df-4a99-8e1d-7ae0c2ea08be)

- middleware preference for a device is given for the one available on the asset configuration page, if not available there, its be taken from the location management page if not available it is also it been taken from the facility middleware page.

- the action items are mentioned under the description of solution

**Comment by ayushpatil2122** [comment]
![Image](https://github.com/user-attachments/assets/a19eaddc-0943-49ab-8e5d-4f3bfcf5c5d4)
is this looks good ?

**Comment by ayushpatil2122** [comment]
i want to work on this issue to me

**Comment by saikiranpatil** [comment]
sorry @nihal467, i was unable to complete this these days. But now i have made changes so that the page looks like this

![Image](https://github.com/user-attachments/assets/05b2f280-da46-46f8-927f-ee7bc815752f)
as you mentioned we have various cases to show messages, so I have added a new attribute `message` to `FormFeild` component to display messages.

I found this color and font weight of the message suitable, please let me know if we need any changes.

**Comment by saikiranpatil** [comment]
shall i create a PR?

**Comment by nihal467** [comment]
@saikiranpatil create a PR for review purpose

**Comment by saikiranpatil** [comment]
> * [ ]  Implement a similar pre-filling behavior in the placeholder and fine text for the location management edit page.

when the location middleware is empty, what is the use  of prefetching in edit location page. doesn't that lead to confusion. I kept it empty for now, should i make any changes in that?

**Comment by saikiranpatil** [comment]
@nihal467 i have created a PR

**Comment by nihal467** [comment]
@saikiranpatil what is the status of this issue, are you still working on this?

**Comment by AdityaJ2305** [comment]
Hey @nihal467 @rithviknishad , I would like to take up this issue

**Comment by Jacobjeevan** [comment]
@saikiranpatil Are you still working on this?

**Comment by rishabhr4** [comment]
hey @Jacobjeevan @nihal467 can i work on this issue
