### ISSUE TITLE
Instead of autofilling on scribe, show the top search results for dropdown selections as chips

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#8342]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aparnacoronasafe** [comment]
@nihal467 is this not working for me. Please test again

**Comment by nihal467** [comment]
@aparnacoronasafe 
![image](https://github.com/user-attachments/assets/3440a9f6-0e30-4e4f-92bb-797743061336)

the suggestion chips are visible, can you hard refresh once and check it once again in the staging deployment  ( https://care-staging.ohc.network )

**Comment by nihal467** [comment]
closing this issue, as the functionality is working @aparnacoronasafe will be filling separate issue, incase some diagnosis are not been fetched by scribe
