### ISSUE TITLE
PDF Preview is not working in file upload component

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8347]
**Describe the bug**

Currently, we are not able to preview uploaded pdf file in the patient consultation page or any place where the file upload component are been used

**To Reproduce**

1. Go to patient tab
2. click on any patient with live consultation 
3. click on the file using the nav bar below the diagnosis card
4. upload a pdf file
5. on successful upload, click on the preview button
6. See error

**Expected behavior**

similar to the image, the pdf file also should be having a preview.

Note : Earlier we had it, but seem like it was remove, @khavinshankar can you comment on this

**Screenshots**

![image](https://github.com/user-attachments/assets/c5145650-6f54-4881-a429-c74ed17da375)

**Comment by khavinshankar** [comment]
Initially, we were previewing pdf along with other documents using iframe, which was suggested as security concern in VAPT Security Report. So we removed it

**Comment by bodhish** [comment]
Pdf is safe to be rendered inline right 🤔
