### ISSUE TITLE
OP Consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8349]
**Is your feature request related to a problem? Please describe.**
When a consultation form is marked with OP Consultation in decision after consultation, the rest of the content of the form is customised to the OP usecase. 

Make the following changes to the form to fit the OP usecase better

**Describe the solution you'd like**
For OP Consultations alone, make the following changes:

- [ ] Investigation suggestion, make "date and time" non mandatory
- [ ] Procedure, make "date and time" non mandatory

**Comment by bodhish** [comment]
I would add a new page for OP consultation; Lets do this as part of HMIS rebuild?

**Comment by aparnacoronasafe** [comment]
ok. closing this as redundant
