### ISSUE TITLE
Words getting split in line break: events log

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8364]
**Describe the bug**
In events log in patient dashboard, where long sentences and paragraphs appear, words are getting split across lines in line break. 

![Screenshot 2024-08-20 at 4 19 45 PM](https://github.com/user-attachments/assets/135cf1dd-f675-41a2-abad-cf94b74620cd)

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1
2. Scroll down to events log and look at the second last event 
4. See error. words are split across lines

**Expected behavior**
Line break must not split words. The line must only break in between workds

**Comment by JOSHIK27** [comment]
This is how it looked before 
![image](https://github.com/user-attachments/assets/6da67635-85a3-4650-b325-f51ae1ca8d8a)
 This is how it looks after the fix 
![image](https://github.com/user-attachments/assets/99d18ec9-f226-4aee-818f-9d56aa69085e)

Achieved this by changing the "break-all" utility class to "break-words" for that specific span element. Please let me know if this what you are expecting, happy to open pr. @rithviknishad

**Comment by JOSHIK27** [comment]
Here's pr #8384 @rithviknishad
