### ISSUE TITLE
General instructions (advice): consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8365]
**Is your feature request related to a problem? Please describe.**
In consultation form (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/update) the field for General Instructions (advise) was made mandatory field as that was the field where doctor would detail out the care plan. But now we have specific fields to detail out the care plan. 

Therefore the text field may be made non-mandatory to easy data entry 

**Describe the solution you'd like**
Make General Instructions (advise) field non-mandatory

**Comment by JOSHIK27** [comment]
![image](https://github.com/user-attachments/assets/559a6ede-60d0-49ff-8a37-396af1c175b2)

Made the field General Instructions non mandatory as asked. Simply removed the required condition on text element and deleted error message handling part for general instructions field. 

This is a minor add on (deletion of few lines) to this pr #8360 @rithviknishad

**Comment by rithviknishad** [comment]
Feel free to create a separate PR @JOSHIK27 even if it's just 1-2 lines of non-conflicting change 😄
