### ISSUE TITLE
Procedures: consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8366]
**Is your feature request related to a problem? Please describe.**
Consultation form (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/update) has a section to mark procedures. 

This section specifically enables a healthcare worker to suggest procedures to be conducted on the patient. The field does not allow users to add details of a procedure already performed. 

This must be made explicitly clear on the form

**Describe the solution you'd like**
Edit the title of the section to "Procedure suggestions"

**Comment by aSriram199** [comment]
i want to work on this issue @aparnacoronasafe

**Comment by aSriram199** [comment]
Hello @rithviknishad ,

 **I would like to suggest** 

**Real Time Validation**:  As users type in a procedure, the system will perform a live check against the existing stored 
                                            procedures. If a match is found, an alert or notification will inform the user that the procedure has 
                                             already been suggested.   
                                             
                                             
**Final Validation on Form Submission**: Upon submission, the system will conduct a final check to ensure no duplicates are 
                                                                      being added. If a duplicate is detected, the user will be asked whether they would  
                                                                      like to confirm or reject it.

**Comment by bodhish** [comment]
@aparnacoronasafe please address the questions on this issue ☝️

**Comment by aparnacoronasafe** [comment]
@aSriram199 great suggestion Srikram!

This issue of possible duplicate entries is present for "Procedure" and "investigations" in the form. 

The better solution to this would be to show list all upcoming planned procedures/investigations for the patient along with details (like time etc). And if the user recommends a  procedures/investigation in the list, show a message saying "this procedures/investigation is already scheduled for the patient".
Since this is a separate effort, breaking it into a separate issue #8499 

Please feel free to take up the issue @aSriram199
