### ISSUE TITLE
Remove temprature taken at field

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#8370]
the field is not being used

**Comment by sainak** [comment]
cc: @gigincg

**Comment by ayushpatil2122** [comment]
i want to work on this issue

**Comment by gigincg** [comment]
@bodhish @aparnacoronasafe Not sure why we introduced this field. Seems irrelevant. Are we good to remove these?

**Comment by bodhish** [comment]
Yep, part of old workflow

**Comment by rithviknishad** [comment]
Closing as completed in https://github.com/ohcnetwork/care_fe/pull/7829
