### ISSUE TITLE
Hide N/A and Null values in events log on frontend

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#8376]
![image](https://github.com/user-attachments/assets/1103cffe-79d9-4ace-943e-756fdc6464b6)

**Comment by Nithin9585** [comment]
Hi @sainak, I'm interested in working on this issue. Could you please assign it to me?

**Comment by Nithin9585** [comment]
Hi @sainak ,

I've created a pull request that addresses this issue: [PR #8381](https://github.com/coronasafe/care_fe/pull/8381#issue-2477194366).
Please review it .

Thank you!

**Comment by rithviknishad** [comment]
@Nithin9585 requested changes
