### ISSUE TITLE
Default to None for daily round fields

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#8377]
Some fields are being saved as 0 in daily rounds
Tasks:

- [ ] change the defaults to None 
- [ ] update any dependent calculations that might expect an integer

**Comment by Nithin9585** [comment]
Hi @sainak, I'm interested in working on this issue. Could you please assign it to me?

**Comment by Nithin9585** [comment]
@sainak  I'm interested in working on this issue. Could you please assign it to me?

**Comment by shivankacker** [comment]
@Nithin9585 assigned this to you

**Comment by rithviknishad** [comment]
@Nithin9585 unassigning due to inactivity.

**Comment by rithviknishad** [comment]
Was completed in https://github.com/ohcnetwork/care_fe/pull/8316
Issue needs to be re-evaluated and re-tested for confirmation for closing this, so assigning to @nihal467

**Comment by nihal467** [comment]
issue is already addressed
