### ISSUE TITLE
Setup Crowdin for translations

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care_fe#8380]
Integrate Crowdin into our project to streamline and manage translations efficiently. 
This involves:
- setting up a Crowdin project
- configuring integration with our GitHub repository
- defining translation workflows
- documenting the process for future use. 

The goal is to ensure that translations are synchronized seamlessly, tested for accuracy, and easy to maintain.

**Comment by comradekingu** [comment]
Is there any reason you wouldn't use Weblate for this?
It is libre software, has no egregious terms, and it works better as a tool.

**Comment by khavinshankar** [comment]
Marking as done
