### ISSUE TITLE
Update range of diastolic blood pressure in detailed log update

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8397]
**Describe the bug**
Currently normal log update has 0-250 as the range for both systolic and diastolic blood pressure fields. However, detailed log update has range 30-180 for diastolic and 0-250 for systolic.

(Ranges confirmed with @aparnacoronasafe)

**To Reproduce**

1. From the consultation dashboard, file a normal log update with blood pressure (observe the ranges). 
2. Also file a detailed log update, and enter vitals section. Observe the ranges for the blood pressure field.

https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/daily_rounds/06b17319-7ec3-4c56-a1f0-ffbceaa7d4a5/update

**Expected behavior**
- [x] Update range of diastolic blood pressure field in detailed log update to 0-250

**Screenshots**

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/a19cdfe4-eb94-4983-9f40-604dc640ac7e">

<img width="1157" alt="image" src="https://github.com/user-attachments/assets/6cdbda27-8449-4588-b14a-ed3321fb61d4">

**Comment by rithviknishad** [comment]
@aparnacoronasafe We decided to restrict the range to a more restrictive value than allowing 0 to 250 as it's very unlikely to fill a zero in dia/sys field. Can we get a more acceptable / useful range?

cc: @gigincg

**Comment by gigincg** [comment]
@aparnacoronasafe Can we do

Systolic pressure between 50 and 250 mmHg.
Diastolic pressure between 20 and 180 mmHg.
Also, ensure that systolic pressure is always greater than diastolic pressure before submission.

**Comment by aparnacoronasafe** [comment]
We can add validation to make sure that systolic pressure is always greater than diastolic pressure

However, Systolic BP can go below 50 in heart attack patients nearing death and other extreme cases. so it is not wise to only allow values above 50. Same with diastolic BP.

I believe we need to increase the higher ceiling of both systolic and diastolic BP. 
A published in 1995 has recorded a maximum blood pressure of 370/360 mmHg.
I recommend we allow values between 0 to 400 for both systolic and diastobil BP

**Comment by rithviknishad** [comment]
@aparnacoronasafe 

Dr. @athulmanuel had mentioned the acceptable values for an EMR would be 30-300 mmHg for both systolic and diastolic and had also said that there would be scenarios where systolic or diastolic would be "non-recordable" and hence need the option to specify such instances explicitly.

**Comment by rithviknishad** [comment]
@vigneshhari 

Wanted to confirm if it'd be okay to store BP in the JSON column in the following way, or should non-recordable be stored as a separate attribute/field?

```py
# Indicates BP was not measured by the client.
bp = None

# Indicates both sys. and dia. are "Non-recordable"
bp = { 
  "systolic": None,
  "diastolic": None,
}

# Indicates sys was measured with a value and dia was "Non-recordable"
bp = { 
  "systolic": 100,
  "diastolic": None,
}
```

cc: @sainak

**Comment by aparnacoronasafe** [comment]
We need to keep the range of values more liberal. We can't look at the majority use case and choose to not acknowledge the edge cases. 

We must keep the range more open.

The issue here is the UI component - slider. Athul doc is worried that if the allowed range is too wide, the slider becomes extended where the usable (commonly used) range will be a small section within the slider.

So my recommendation is:

- [ ] We keep the allowed range of input relaxed
- [ ] Reimagine input modality. slider is not very usable. Scroll or any other modality may be considered
- [ ] Athul doc also recommended to add fields for "modality of measuring BP" and if, IVBP, then "site of measurement"- filing this as separate issue.

@gigincg please comment

**Comment by rithviknishad** [comment]
As discussed, we'll allow 30-300 mmHg (or a more frequently used range) through the slider, however, to input values beyond the range, we'll allow 0-400 mmHg through the numeric input field, and will add descriptive text to indicate "too low" or "too high" beside in the component.

Also would be adding a checkbox for marking either being "Non-recordable"

cc: @aparnacoronasafe
