### ISSUE TITLE
Add asset info pop-up for camera feed in consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8399]
**Is your feature request related to a problem? Please describe.**

Currently, we are showing the middleware and IP address of a vital monitor in the consultation page, but the camera feed doesn't have that info in the consultation page, which can be a good add-on towards the UX

**Describe the solution you'd like**

- [ ] Add the asset info pop-up similar to the vital monitor to the camera feed page to show only IP address and hostname
- [ ] make the pop-up in the vital monitor page a reusable component

**Screenshots**

![image](https://github.com/user-attachments/assets/ef9d41b9-1b1c-4c15-853a-a6a2431adc4d)
![image](https://github.com/user-attachments/assets/3df8e1a5-0e77-4bc5-861f-5778d8ed5269)

**Comment by AdityaJ2305** [comment]
@nihal467  Can you assign this issue to me ?

**Comment by Jacobjeevan** [comment]
@nihal467 Mind assigning this to me? Thanks!
