### ISSUE TITLE
Show alert/popup/warning notification when opening Care on older/unsupported browsers

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8403]
**Is your feature request related to a problem? Please describe.**
CARE may use functions that may not be available on older browsers of users. This may lead to certain pages within CARE to crash when such browser unsupported functions are invoked.

**Describe the solution you'd like**
Based on the [browserslist configured for the project](https://github.com/coronasafe/care_fe/blob/develop/package.json#L140), show a alert/popup/warning notification when users open CARE on such older/unsupported browsers.

We could use the following to achieve it:

- https://github.com/browserslist/browserslist#show-we-do-not-support-your-browser-banner
- https://github.com/browserslist/browserslist-useragent-regexp

**Additional context**
Recent issue that was caused due to older browser unsupported:

- https://github.com/coronasafe/care_fe/issues/8389
- https://github.com/coronasafe/care_fe/pull/8392

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad, can you assign this issue to me?

**Comment by AdityaJ2305** [comment]
<img width="1440" alt="Screenshot 2024-08-24 at 10 02 31 PM" src="https://github.com/user-attachments/assets/db0ad841-85df-4ff2-927d-bca1f68fc9d1">
Is the CSS for the `BrowserWarning` component okay, or should I adjust it?  
and Can I put this browserWarning comp in the ErrorPages folder in the component ?

**Comment by bytetwt** [comment]
> <img width="1440" alt="Screenshot 2024-08-24 at 10 02 31 PM" src="https://github.com/user-attachments/assets/db0ad841-85df-4ff2-927d-bca1f68fc9d1">
> 
> Is the CSS for the `BrowserWarning` component okay, or should I adjust it?  
> 
> and Can I put this browserWarning comp in the ErrorPages folder in the component ? 

In which browser did you face this issue can u plz say me ..

**Comment by AdityaJ2305** [comment]
> > <img alt="Screenshot 2024-08-24 at 10 02 31 PM" width="1440" src="https://private-user-images.githubusercontent.com/148325158/361156107-db0ad841-85df-4ff2-927d-bca1f68fc9d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzQ1MzUsIm5iZiI6MTcyNTAzNDIzNSwicGF0aCI6Ii8xNDgzMjUxNTgvMzYxMTU2MTA3LWRiMGFkODQxLTg1ZGYtNGZmMi05MjdkLWJjYTFmNjhmYzlkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxNjEwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDI0Y2IzMTc0ZTNkZDk0YTA4MjI2N2RkMDViZmEwYzEzZDM1YWY2NjU5ZjExNTUzNzdjYzUxZDY5OWYzOWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ue_sSLXb2xv4tsaGH2FY7k3MARnWl47Y0Zuw_bk1ewc">
> > Is the CSS for the `BrowserWarning` component okay, or should I adjust it?
> > and Can I put this browserWarning comp in the ErrorPages folder in the component ?
> 
> In which browser did you face this issue can u plz say me ..

You can change the default browser for testing in the inspect so it will behave like that only . I had changed to opera mini which is unsupported as per browserlist in package.json
