### ISSUE TITLE
Error while registering ABHA Address (if the same address is used elsewhere)

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8423]
**Describe the bug**
I tried generating ABHA for a patient with an Aadhaar that is already registered with ABHA and I also used an ABHA address that's already used elsewhere 

**To Reproduce**

1. Go to 'patient dashboard'
2. Click on 'Generate ABHA'
3. Add an Aadhar no. that's already used to register ABHA before. 
4. Once Aadhaar no and phone number is verified through OTP, and you reach final step of choosing an ABHA address, type in an address that is already used elsewhere.
5. The error message shows a mix of text and numbers and the ABHA address is not registered. 

**Expected behavior**

- [ ] The error message must clearly specify what the error is. "The ABHA address you have entered is already in use. Pick a unique ABHA address to proceed"
- [ ] Can a second ABHA be registered on the same Aadhaar? if not, can we have the error come up that the "An ABHA No. is already registered against this Aadhaar. Please link the existing ABHA ID to the patient rather than generating a new ABHA ID". This error must ideally come up right when the patient's Aadhaar is verified. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khavinshankar** [comment]
This issue will be fixed in #8340.
