### ISSUE TITLE
Header and footer spacing in summaries

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8430]
**Is your feature request related to a problem? Please describe.**
The format of all summaries in CARE needs to be improved. This includes
- discharge summaries
- treatment summaries
- Investigation summaries

The pages have no spacing at the header and footer.
The page breaks between sentences

**Describe the solution you'd like**

- [ ] Add spacing at the head and the foot of each page
- [ ] Do not allow page to break sentences. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Zeshanxviii** [comment]
Hi @aparnacoronasafe ,

I've reviewed the issue regarding the formatting of summaries in CARE. To better understand the problem, could you please provide a video or screenshots that illustrate the current formatting issues, particularly the lack of spacing at the header and footer, and the page breaks between sentences?

This will help ensure that the proposed solutions address the issues effectively.

Thanks!
