### ISSUE TITLE
Issue in bed occupied status

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#8436]
In location Management it has been showing that all beds are occupied but actually, they are Not Occupied.  Only a few of them are occupied.

Occupied Beds:
![image](https://github.com/user-attachments/assets/96169730-6248-4db9-b4f7-9cc2acde4c92)

Location:
![image](https://github.com/user-attachments/assets/b5ed45d7-9bf8-4807-88c0-69e5903b7634)

Unable to select bed:
![image](https://github.com/user-attachments/assets/3b9d3dbd-ab9a-4e88-a488-d7f67a09f248)

Reported by: Nagnath
cc: @nihal467

**Comment by AdityaJ2305** [comment]
Hey @khavinshankar as I have gone through BedSelect component in BedSelect.tsx. I noticed it is return empty array for the data we are fetching from backend and I am logging the raw data fetched not any filtered condition applied  so probably it is a backend issue only . Here are screenshots :

<img width="896" alt="Screenshot 2024-08-29 at 10 50 08 AM" src="https://github.com/user-attachments/assets/56c7371e-a9dd-4858-8bf5-af8e707db799">

<img width="1440" alt="Screenshot 2024-08-29 at 10 50 26 AM" src="https://github.com/user-attachments/assets/c832c3bf-6e26-47e5-b6ce-6d2654c232db">

cc: @rithviknishad

**Comment by Sulochan-khadka** [comment]
Steps to reproduce and the expected behaviour would really help in understanding the issue better.

Kindly mention if possible @khavinshankar @rithviknishad

**Comment by rithviknishad** [comment]
@Sulochan-khadka @AdityaJ2305 this was due to a race condition that was reproducible in an older version. However likely that the duplicate ConsultationBed records that were created on those days were not cleared.

@khavinshankar we can close this issue right?

cc: @sainak

**Comment by khavinshankar** [comment]
Closing this issue as completed.
