### ISSUE TITLE
Improve Setting up guide 

### ISSUE THREAD

**Issue by JOSHIK27** [coronasafe/care_fe#8438]
**Is your feature request related to a problem? Please describe.**

In addition to exisiting information in readme file, alternative way of starting dev server locally by executing  **CARE_API=http://127.0.0.1:9000/ npm run dev** from the terminal would be much simpler for beginners for connecting front-end with backend.

**Describe the solution you'd like**
Under this [section](https://github.com/ohcnetwork/care_fe?tab=readme-ov-file#-run-cypress-tests), include the other way to starting local dev server once the back-end is up and running to connect front-end and backend.

**Describe alternatives you've considered**

**Additional context**

**Comment by bodhish** [comment]
We have added support for `CARE_API` in .env.
