### ISSUE TITLE
Switch to camelCase for properties in `config.json`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8444]
Currently `config.json` follows `snake_case` for naming the properties. However, we should be following `camelCase` for naming properties in javascript/typescript.

### Action Items:

- [ ] Update schema in [`care_deploy_config`](https://github.com/ohcnetwork/care_deploy_configs/blob/main/config_schema.yaml)
- [ ] Update `config.json` and usages in [`care_fe`](https://github.com/ohcnetwork/care_fe/blob/develop/public/config.json)

**Comment by ghost** [comment]
Hey @rithviknishad , is this still valid coz I couldn't find config.json file

**Comment by rithviknishad** [comment]
Closing as config.json has been removed quite a while back.

**Comment by ghost** [comment]
Ok Sir
