### ISSUE TITLE
Opening Advanced Filters on patients page calls the ICD 11 endpoint multiple times

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#8447]
**To Reproduce**

1. Go to Patients Page
2. Enable network logs
3. Click on advanced filters
4. See multiple calls

**Expected behavior**
It should only call when the icd filter is used

**Screenshots**
![image](https://github.com/user-attachments/assets/c70ead52-4341-4831-9aa3-d34c90026251)

**Comment by rithviknishad** [comment]
Let's also add min char query like we added for Add ICD 11 diagnosis in https://github.com/ohcnetwork/care_fe/pull/8233 and disable `prefetch` there too.
