### ISSUE TITLE
Do not show clear all filters button if there is no filter applied in Discharge patients page

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#8449]
**Describe the bug**
A `clear all filters` button is shown in the discharged-patients page even when there are no filters applied. It should only show if filters have been applied.

**To Reproduce**

1. Go to patients page
2. go to the discharged tab
3. select a facility
4. see the label

**Expected behavior**
The label should only show if any filters have been applied.

**Screenshots**
![image](https://github.com/user-attachments/assets/10fc3895-0a93-4f96-b478-098b08850dae)

**Comment by Adiflickzzz** [comment]
i have solved it can u assign it to me sir ..
