### ISSUE TITLE
Make Medispeak Mic icon float/move around the screen. (Arike)

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8455]
**Describe the bug**
while filing discussion notes for a patient, the medispeak mic icon is placed above the submit button for the text box.

**To Reproduce**

1. Go to a patient file on  "arike" instance
2. Click on the discussion note
3. type some notes and click on submit icon

**Expected behavior**
the medispeak icon should be moveable across screen

**Screenshots**
<img width="314" alt="image" src="https://github.com/user-attachments/assets/81924c36-ef6e-4321-af90-9ac38ffa48b8">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bodhish** [comment]
@gigincg should we do this?

**Comment by aparnacoronasafe** [comment]
@gigincg Need this resolved ASAP. 

Issue flagged repeatedly by Arikey.

**Comment by gigincg** [comment]
@aparnacoronasafe Closing this in favour of Scribe. Arike will be switching to Scribe.
