### ISSUE TITLE
Enhancements to care config

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8470]
https://github.com/ohcnetwork/care_fe/pull/8445 Introduces `care.config.ts` for making CARE configurable from ENVs. However there are couple of enhancements that can be done:

- [ ] Perform config validation during vite build so that build fails thus preventing exceptions from being thrown during runtime if any.
- [ ] Sentry config to be optional and enable sentry only if configured.
- [ ] Plausible config to be optional and enable plausible only if configured.

**Comment by Deexit1** [comment]
@bodhish / @rithviknishad  I will be able to complete the 2nd and 3rd task e.g., optional plugins based on provided config.

**Need Clarification:**
For the first task, which kind of config validations are required for each config option ? Also, should we use any schema validation libraries like [zod](https://zod.dev/) ?

**Comment by Jacobjeevan** [comment]
Vite's community [plugins](https://github.com/vitejs/awesome-vite?tab=readme-ov-file#plugins) includes two env validation plugins, [one](https://github.com/Julien-R44/vite-plugin-validate-env) of which supports Yup/Zod etc. So, we could make use of that, or build one ourselves.

**Comment by ghost** [comment]
@Jacobjeevan , @rithviknishad can I work on this issue ?

**Comment by ghost** [comment]
@Jacobjeevan sir, I have created a PR can you review it once , I have just added validation for only 5 env , should I add more ?
