### ISSUE TITLE
Environment variables are not working in docker deployments

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#8473]
The environment variables are injected on build time, so they can't be configured on runtime.

**Comment by sainak** [comment]
cc: @bodhish @gigincg

**Comment by bodhish** [comment]
Do we need docker images going forward? Can't we build and serve ?

**Comment by sainak** [comment]
>Do we need docker images going forward? Can't we build and serve ?

I switched to building images specific to deployments.
but as @vigneshhari pointed out, we can serve the static files from s3
