### ISSUE TITLE
Add third-party Licenses

### ISSUE THREAD

**Issue by tellmeY18** [coronasafe/care_fe#8484]
- [ ] Check for any conflicts in the license for Care and its dependent packages.

Some tools -
- [ ] https://github.com/wrapp/licensecrawler
- [ ] https://github.com/mwittig/npm-license-crawler

**Comment by gigincg** [comment]
@tellmeY18 You'll be taking this up right?

**Comment by tellmeY18** [comment]
Yea I'll ✅

**Comment by bodhish** [comment]
@tellmeY18 can you link your PR here?
