### ISSUE TITLE
Log update : Round Type (Community Nurse's Log)

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8488]
**Is your feature request related to a problem? Please describe.**
CARE is being adopted by palliative care organisations. 

We need a new round type specifically for community nurses.

**Describe the solution you'd like**

Have the following fields in the form in the given order

- [ ] Measured at
- [ ] Round type
- [ ] category
- [ ] Symptoms
- [ ] Physical examination info
- [ ] Other details
_____________________________ the below section comprises of new fields to be added
- ROUTINE 
- [ ] Bowel (dropdown with options- No difficulty, Constipation, Diarrhoea)
- [ ] Bladder 
- Bladder Drainage (dropdown with options- Normal, Condom Catheter, Diaper, Intermittent catheter, Continuous indwelling catheter, Continuous suprapubic catheter, Urostomy)
- Bladder Issues (dropdown with options- No issues, Incontinence , Retention, Hesitancy)
- Whether the patient experiences Dysuria? Yes/No
- Frequency of urination (dropdown with options- Increased frequency, Normal, Decreased frequency)
- [ ] Sleep (dropdown with options- Excessive, Satisfactory, Unsatisfactory, No sleep )
- [ ] Nutrition
- Nutrition route (dropdown with options- Oral, Ryle’s tube, Gastrostomy/jejunostomy, PEG, Parenteral Tubing (fluid), Parenteral Tubing(TPN))
- If Oral, Issues (dropdown with options- No issue, Dysphagia, Odynophagia)
- Appetite (dropdown with options- Increased, Satisfactory, Reduced, No taste for food, Cannot assess)
_____________________________
- VITALS
- [ ] BP - systolic/diastolic
- [ ] Pulse
- [ ] RBS (mg/dl) (same as Blood sugar level in detailed log update)
____________________________
- PRESCRIPTION
keep the prescription section as is
__________________________
NURSING CARE
keep entire nursing care section as is
_________________________
- [ ] Action review after
- [ ] Review After

**Describe alternatives you've considered**

**Additional context**

**Comment by rithviknishad** [comment]
@aparnacoronasafe Is "Bladder Issues" multi select or single select?

**Comment by aparnacoronasafe** [comment]
@rithviknishad I made a change in question on "Bladder issue". Dysuria is taken out as a separate yes/no question. 
The dropdown for bladder issue will support only selection of one option
