### ISSUE TITLE
Prescription: By "Nurse" user type- attribution to doctor

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8492]
**Is your feature request related to a problem? Please describe.**
In India, a nurse is not allowed to issue a prescription. That is a function reserved for doctors alone. 

However, in CARE we allow nurses to add/ make edits to prescriptions.

We are allowing the nurse to do so with the assumption that she is acting under instruction from a doctor to make the said changes.

In order to improve accountability, it is important to also log in CARE, under which doctor's instruction a nurse is making edits to prescription.

**Describe the solution you'd like**
In prescription form, ONLY for "Nurse" Usertype, 

- [ ] Add an dropdown on top with text "Changes to prescription, as directed by :" Let the dorpdown show a list of doctors with home facility linkage to the respective facility.
- [ ] The above must be a mandatory field. Only after selecting the doctor must the nurse be able to make any changes to the prescription.

Please note that this is applicable only when the nurse makes changes to active medicines suggested in prescription and NOT for marking medicine administration

**Comment by bodhish** [comment]
@rithviknishad @aparnacoronasafe @gigincg Lets hold this issue and figure out a UX flow before implementing it. 
This should ideally address the following. 
- In case of an OP consult the doctor that the nurse is working with should be smart filled initially
- In case of IP the treating doctor should be the default choice 
- In case if its a referral, that doctor should come in as default choice  

Its easy add this but I would want us to think of ways with which the problem could be addressed before jumping right into a solution.

**Comment by aparnacoronasafe** [comment]
@bodhish Can we go ahead and build the feature to attribute prescription to a doctor first, and then build automations as an Add on?

For OP, once we have the OP flow built out we can automatically the the name of the OP doctor added.

**Comment by bodhish** [comment]
@aparnacoronasafe this should be signed_by_doctor. 

Can you update the context here;

**Comment by BlessedRice2004** [comment]
Hi @bodhish , can I pick this issue up? From what I've read, it seems this issue went stale because of a lack of a UX flow? I'd be down to start by creating the UX flow and going from there if that's the blocker

**Comment by nihal467** [comment]
@bodhish can you reply back

**Comment by bodhish** [comment]
This will no longer be a problem once we implement FHIR spec, lets hold this for sometime

**Comment by nihal467** [comment]
we are moved to RBAC system and not a invalid issue on the current develop
