### ISSUE TITLE
NIV & IV respiratory support badges are malfunctioning in patient list page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8495]
**Describe the bug**

When we readmit a patient without consultation in a facility, and if the patient has respiratory support of IV or NIV in his/her last consultation, the respiratory support-related badge will be shown on the patient list page along with the no consultation badge

**To Reproduce**

1. Readmit a patient without consultation who has previous consultation of respiratory support NIV or IV
2. go to the patient tab and search for that patient
3. See error

**Expected behavior**

the respiratory support badge in the patient list page should be showing the badge only if the patient is having an active consultation

**Screenshots**

![image](https://github.com/user-attachments/assets/81e41a81-2e81-4b8d-8fd9-f32a1cc33fdf)

**Comment by Jacobjeevan** [comment]
mind assigning this to me? @nihal467 

On a side note, how do I add a respiratory support for a new consultation? Where is that located in log update?

**Comment by nihal467** [comment]
@Jacobjeevan 

- click on the patient tab in the sidebar
- click on any patient card with live consultation
- once you are on the consultation , click on the log update button
- on the log update page, select the round type "Detailed Update" and click save
- now, on the critical care, click on the respiratory support section, and click on any oxygen support 
- save the form now
