### ISSUE TITLE
Procedures/Investigations- list all planned items in form, disallow duplicate entry

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8499]
**Is your feature request related to a problem? Please describe.**
When a user adds procedure/investigation suggestion in Consultation form/ progess note (log update), the user has no way to see the already planned procedure/investigation. without this the user may end up duplicating entries.

**Describe the solution you'd like**
Show list all upcoming planned procedures/investigations for the patient along with details (like time/repetative etc). 

And if the user recommends a  procedures/investigation in the list, show a message saying "this procedures/investigation is already scheduled for the patient. Please edit the existing entry".

**Describe alternatives you've considered**

**Additional context**

**Comment by JOSHIK27** [comment]
I would like to work on this issue. Before that i have few things to clear, when i try to add some random procedures and investigations in the consulation form of a patient with no exisiting consultation, i could see the procedures and investigations (values that i added previously) when i open edit consultation form. Is this the issue that you mentioned above

OR

When i fill a procedure with some random value and try to add one more procedure with same values, it is allowing users to add. Is the issue that was mentioned.

@rithviknishad

**Comment by noufalrahim** [comment]
@rithviknishad @aparnacoronasafe can u assign this to me..?

**Comment by nihal467** [comment]
@gigincg can you look into the relevance of this issue, since we are moving towards FHIR and refactoring of investigation modules

**Comment by gigincg** [comment]
@nihal467 Blocked the issue, this is better done post Questionnaires and Lab Management is shipped out. 

cc: @noufalrahim

**Comment by nihal467** [comment]
not a valid issue based on the current develop
