### ISSUE TITLE
Expanding Investigations Seed list

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8510]
**Is your feature request related to a problem? Please describe.**
CARE investigations list is very limited. Many important tests are missing in the list

**Describe the solution you'd like**

- [ ] Expand the seed data with tests highlighted here in the list : https://docs.google.com/spreadsheets/d/1hN13p-BDbb1Pkl3a8tcVdWFsFxncju2QPfeOEkKh51E/edit?usp=sharing 
- [ ] Update reference values and names of some tests as highlighted in the same list
- [ ] Add tests to more groups, as highlighted in the same list

**Describe alternatives you've considered**

**Additional context**

**Comment by xakep8** [comment]
@aparnacoronasafe could you please assign this issue to me.

**Comment by praffq** [comment]
I have a few doubt about the above changes and wanted to confirm before raising the PR.

1. `include category_id:2` mean that if it was `4` before , now updated category_id will be `4,2` 
2. `previously 2` what does this mean? and is the changes for this already made?
3. `not mentioned on Harsh mohan sheet` at row 78, what does that mean ?

@aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
@DraKen0009 

1- yes. You are correct. Keep both classes

2- replace group 2 with the new group mentioned

3- it's just for internal reference. You can ignore that. Sorry, I should have cleaned it up.

**Comment by praffq** [comment]
@aparnacoronasafe 

We currently have multiple investigation names that have the same values, which Ideally should have being unique. Here are a few I found:

 investigation name   `pH` – rows 230, 203, 209, 169, 220

Additionally, at row 154, we need a numerical value in the "min" column.

cc : @gigincg

**Comment by aparnacoronasafe** [comment]
@DraKen0009 The issue of pH coming up multiple times is resolved. It is pH of various fluied. I have corrected it my providing the fluid type in "()" against pH.

The missing min value in row 154 will be resolved shortly. getting the data

**Comment by aparnacoronasafe** [comment]
@DraKen0009 the info in row 154 is edited to all required data.

**Comment by vigneshhari** [comment]
@aparnacoronasafe do we need to update the list right away or can we wait for the next release feature to come up, that should solve this issue permanently. cc @bodhish

**Comment by bodhish** [comment]
Let's wait for the Snowmed CT integration
