### ISSUE TITLE
Patient sorting: Bed 1-N

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8511]
**Describe the bug**
CARE has option to sort patient list by the bed number they are assigned to. 

But the feature is not working as expected

**To Reproduce**

1. Go to 'patient list (live)'
2. Click on 'sort by' and select "Bed 1-N"
3. Scroll down to View the patient list
4. See error. The beds are sorted as Bed 1, 10, 11, 12...19, 2, 21, 22.....

**Expected behavior**
The sorting should be as Bed 1,2,3,4......and so on

**Comment by swayam-agrahari** [comment]
Hi @aparnacoronasafe, I would like to work on this issue. I have set up the project locally. I have a doubt, when I add a sort 1-N filter, how can I identify the bed number? 
ps: This is my first issue. I'm new to opensource
![Screenshot_10-Sep_04-18-00_6619](https://github.com/user-attachments/assets/555dc36d-3e78-4aed-bd93-1bf14b332af3)

**Comment by xakep8** [comment]
@aparnacoronasafe @rithviknishad could you please assign this issue to me.

**Comment by rithviknishad** [comment]
Hey, sure! Could you specify how this is going to be solved?

**Comment by rithviknishad** [comment]
@swayam-agrahari 
Currently it is sorting by the 'name' attribute of the bed object by the backend. Bed number is part of the name.

https://github.com/ohcnetwork/care/blob/develop/care/facility/api/viewsets/patient.py#L455

https://github.com/ohcnetwork/care/blob/develop/care/facility/models/bed.py#L20

**Comment by xakep8** [comment]
@rithviknishad I just checked the `patient.last_consultation?.current_bed?.bed_object` in the frontend is the name over here the same as the `last_consultation__current_bed__bed__name` value?

**Comment by xakep8** [comment]
@rithviknishad we could seperate the number from the name while filtering and based on the number and name we could sort the names and return the data, for the beds with same number but different names we could just let the names be sorted by the lexicographical order, while the whole list is first sorted based on bed number, this way we wouldn't need to modify the schema and the filtering will also work just fine

**Comment by xakep8** [comment]
@rithviknishad is there some other way we could do it?

**Comment by rithviknishad** [comment]
Not sure if that's the right way.

**Comment by bodhish** [comment]
Having a sort order for the best is the solution here. Bed number should be independent from sort order.  
@aparnacoronasafe how big a pain is this? I am assuming most 10 beds just have 10 beds so it maynot be a large issue here;

**Comment by aparnacoronasafe** [comment]
> Having a sort order for the best is the solution here. Bed number should be independent from sort order. @aparnacoronasafe how big a pain is this? I am assuming most 10 beds just have 10 beds so it maynot be a large issue here;

It isn't a critical issue that needs to be solved immediately. 

There are larger 10bedicus with up to 20 beds.
