### ISSUE TITLE
Unable to run dev server in windows local

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8515]
**Describe the bug**

Follow-up: https://github.com/ohcnetwork/care_fe/pull/8417
Due to the recent PR merged to check for supported browsers, we are unable to deploy the care_fe locally on a Windows PC

**To Reproduce**

1. Enter the command " npm run supported-browsers " before running " npm run dev " in a Windows PC
2. See error

**Expected behavior**

- [ ] We should be able to deploy care_fe locally on all machines
- [ ] Update the care_fe documentation to include the requirement of running supported-browser initially before deploying care_fe

**Screenshots**

![image](https://github.com/user-attachments/assets/db3bb747-cddf-44c7-b870-8521969ddc32)

**Comment by sainak** [comment]
Possible solution: convert the command to a utility script and use native javascript regex to achieve the same result

**Comment by bodhish** [comment]
@nihal467 Use WSL for running the app.
