### ISSUE TITLE
Add cache-control header for index.html

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#8516]
In the nginx conf there are no cache control headers added which causes the index.html to be cached by the browser 

to fix this add a cache-control header with ttl = 7 days for regular files and ttl = 6 hrs for index.html

**Comment by AdityaJ2305** [comment]
Hi @sainak  I would like to work on this feature. Could you assign it to me ?

**Comment by AdityaJ2305** [comment]
Work In Progress

**Comment by AdityaJ2305** [comment]
@sainak I see the backend sets Cache-Control: max-age=31536000, immutable. Should I use proxy_hide_header to change this, or is it intentional?
<img width="380" alt="Screenshot 2024-09-12 at 12 16 37 PM" src="https://github.com/user-attachments/assets/864e65dd-f352-4661-811c-d1807b1b982e">

**Comment by AdityaJ2305** [comment]
@sainak  Should I make the PR with proxy_hide_header ?

**Comment by vishwansh01** [comment]
Hi @sainak !
I just created a pull request solving this issue : [#8575 ](https://github.com/ohcnetwork/care_fe/pull/8575)

**Comment by AdityaJ2305** [comment]
Hi @sainak @rithviknishad ,
I was working on this issue and had a few questions, but noticed @vishwansh01  submitted a PR without being assigned. Could you clarify how to proceed in such cases?
Thanks!
