### ISSUE TITLE
Consistency in label prop name for `RadioFormField`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8529]
The `RadioFormField` component uses `optionDisplay` prop to render the label. However, all other CareUI components such as `SelectFormField`, `MultiSelectFormField`, `AutocompleteFormField`, 'AutocompleteMultiselectFormField`, etc. uses `optionLabel` as the prop name to for the field label.

Hence for improving consistency, let's rename the `optionDisplay` to `optionLabel` for the `RadioFormField` component.

**Screenshots**

### Usages of `optionLabel` (185 results)

<img width="480" alt="image" src="https://github.com/user-attachments/assets/1d148149-14fc-4f4f-a8e9-15efe3b0a88d">

### Usages of `optionDisplay` (28 results) that needs to be replaced with `optionLabel`

<img width="508" alt="image" src="https://github.com/user-attachments/assets/1d0f8a2a-5a9e-4279-b7ec-7e16456abbce">

**Comment by xakep8** [comment]
I would like to work on this issue could you assign this to me?
