### ISSUE TITLE
Facility cover image edit button is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8530]
**Describe the bug**

When we click anywhere in the facility name or across the row, the edit cover image pop-up keeps on opening up

**To Reproduce**

1. Go to facility tab
2. Click on view facility button
3. click on any area marked on the screenshot

**Expected behavior**

edit cover image pop-up should only appear, when we click on the respective place of the cover image

**Screenshots**

![image](https://github.com/user-attachments/assets/c84da3f6-85d6-46bb-aba7-8ffddd35573b)

**Comment by HitishRaoP** [comment]
@nihal467 can you assign this issue to me?
