### ISSUE TITLE
Remove all direct API calls from frontend to middleware

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8540]
**Describe the bug**

In the new middleware version, we can't call middleware directly from frontend

currently effected: dev-middleware only and staging middleware is working well as it is using production middleware version

**To Reproduce**

**Expected behavior**

- [ ] change all the usage in frontend to support current middleware version

**Screenshots**

**Comment by Sulochan-khadka** [comment]
Is there a way I can contribute here so that it gets merged at the earliest? If the problem were a bit more descriptive, I could have contributed.

**Comment by sainak** [comment]
hey @Sulochan-khadka I'm already working on it, you can take up other issues
