### ISSUE TITLE
Facility page view in mobile phones are breaking in some devices

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8541]
**Describe the bug**

When you open the facility tab, in the Apple 15 pro max devices, using a state-admin account, the card is stretched to the right side, it's  only happening on the first page, once you move to any other page, the problem is solved

**To Reproduce**

1. Open : https://care.ohc.network/facility
2. Go to the facility tab using state admin credentials ( user: state-admin and password: Lilo@123 )
3. view the page with iPhone 15 pro max device

Note: Search for Aloha new facility

**Expected behavior**

the card shouldn't stretch the page, it should be properly responsive based on the user's device

**Screenshots**

![image](https://github.com/user-attachments/assets/9e123f3a-aa2e-4f21-b1bd-dc773aa016f4)

**Comment by mhdsalih2000** [comment]
claim

**Comment by rithviknishad** [comment]
@mhdsalih2000 unassigned due to inactivity, feel free to pick up and create a draft PR to avoid issues from being stale

**Comment by Jash2606** [comment]
Hey @rithviknishad ,
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

This is Preview after fixing it:
![image](https://github.com/user-attachments/assets/86523a50-3a9e-4eac-a732-889b43db5d56)

**Comment by Jash2606** [comment]
Hey @rithviknishad  @bodhish , 
I had raised PR for above issue , Could you review it and let me know if any further changes required!
