### ISSUE TITLE
Updates to Log updates View

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8556]
**Is your feature request related to a problem? Please describe.**
The Log Update View page (https://care-staging.ohc.network/facility/d171b5f6-7d4e-40e8-8591-799aebc9c9ec/patient/ad6366f5-f67a-4e5f-9b23-71f5104a86b7/consultation/7a743f82-33cb-4559-8cd0-f7c2ac6b1b47/daily_rounds/b136178e-0312-4e87-9de3-25bfd52291e6) needs the following updates:

**Describe the solution you'd like**

- [ ] rename page from "consultation update" to "Log Update"
- [ ] Arrange the sections in the same order as below
![Screenshot 2024-09-17 at 3 24 26 PM](https://github.com/user-attachments/assets/f49be313-21a6-4347-b117-4947e2f911ce)
- [ ] Show "Round Type" and "Category"
- [ ] Show delta in Symptoms
- [ ] Show "Action" and "review after" if the user has selected any options therein.
- [ ] In painscale, show "description" as well
- [ ] Show Glasgow Coma Scale within a box. Show "Glasgow Coma Scale-TOTAL" on top and the full details 
(like Glasgow Eye Open: No response, 
Glasgow Verbal Response: Incomprehensible words/Moans to pain
Glasgow Motor Response: Abnormal Extension(decerebrate)) 
below it.
- [ ] In "Respiratory support" section change "Interface" to "Respiratory Support availed"

**Describe alternatives you've considered**

**Additional context**

**Comment by himanshu-sharmav** [comment]
Hi @aparnacoronasafe  can you assign this to me? I would love to work on this.

**Comment by bodhish** [comment]
@aparnacoronasafe can we discuss this ☝️

**Comment by GuntreddyHemanth** [comment]
can you assign this to me!!

**Comment by awaiskhan21** [comment]
hey @aparnacoronasafe  @rithviknishad can you assign this issue to me it is my first issue i would love to work on this

**Comment by nihal467** [comment]
non-relevant to current develop
