### ISSUE TITLE
Enhancements to Nursing tab UI

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8562]
### Steps to Reproduce:

1. Go to a consultation
2. Create a log update (ensure bed is assigned) of type "Community Nurses Log"
3. Fill routine and nursing care section
4. Once submitted, check the Nursing Tab in the consultation dashboard

<img width="1816" alt="image" src="https://github.com/user-attachments/assets/31841b16-4c23-4f7b-b509-a4cb6d6b0df3">

### Action Items

- [ ] lock the first row of the field name in routine section table
- [ ] have fixed width for time columns (2nd column and after)
- [ ] Make the Nursing Care section similar to the Routine Section by switching to a table layout (Make the component a reusable component to achieve it).
- [ ] Optional: feel free to improve the overall UI (borders or colors, etc.)

_Originally posted by @nihal467 in https://github.com/ohcnetwork/care_fe/issues/8522#issuecomment-2358037877_

**Comment by praffq** [comment]
@rithviknishad  I'll like to take this up next

**Comment by bodhish** [comment]
@ohcnetwork/doctors Can you check this out.

**Comment by bodhish** [comment]
@ohcnetwork/doctors Can you share your feedback here?

☝️ Ignore; was used for testing

**Comment by Sahil-Sinha-11** [comment]
hey @rithviknishad  I tried to insert the table, does this works or should i edit something?
<img width="1684" alt="Screenshot 2024-09-20 at 8 01 18 PM" src="https://github.com/user-attachments/assets/f2309d2b-d007-4184-870c-5d9f646cd222">

**Comment by rithviknishad** [comment]
@Sahil-Sinha-11 This works, however, it'd be appreciated if you could follow the contributing guidelines https://docs.ohc.network/docs/contributing/#how-to-contribute

This issue has already been assigned to @DraKen0009 recently.

**Comment by Sahil-Sinha-11** [comment]
Oh, I apologize @DraKen0009 @rithviknishad  . Will keep guidelines in mind (1st time contributing 😅).

**Comment by praffq** [comment]
No worries @Sahil-Sinha-11 , go ahed and make a PR. I haven't made any significant progress on this issue so not a problem.
