### ISSUE TITLE
TeleICU Hub Doctors not came up.

### ISSUE THREAD

**Issue by Jrl0** [coronasafe/care_fe#8572]
On Doctor connect module.
Not all TeleICU Doctors are present.
Doctor are linked to all facilities with hub hospital as home facility set.

1. Go to a patient 
2. Click on Doctor connect 
3. Scroll down to TeleICU Doctors 
4. See few doctors present

All doctor link to hospital with home facility as hub hospital should be listed under TeleICU Doctors.

**Comment by gigincg** [comment]
@Jrl0 This is by design, only Doctors who have access to the Spoke Hospitals are considered as Hub Doctors or TeleICU Doctors
