### ISSUE TITLE
Add Scribe support to newly added community log update fields

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8580]
**Is your feature request related to a problem? Please describe.**

Currently, the newly added fields under the routine section of the community log update fields are not working in scribe auto-filling

**Describe the solution you'd like**

Add scribe support to the routine section of the community log update

**Screenshot**

![image](https://github.com/user-attachments/assets/2e54c12e-32c2-4997-8deb-9492b7ca65a0)

**Comment by bodhish** [comment]
Scribe should auto detect fields, we shoudn't be adding fields one by one;

**Comment by SwanandBhuskute** [comment]
I would like to work on this issue, pls assign me @shivankacker @bodhish @nihal467 @rithviknishad

**Comment by shivankacker** [comment]
@SwanandBhuskute this has already been done

**Comment by SwanandBhuskute** [comment]
> [@SwanandBhuskute](https://github.com/SwanandBhuskute) this has already been done

ok, can you assign me issue 8762
