### ISSUE TITLE
Restrict Scribe from filling fields not present in the selected log update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8581]
**Describe the bug**

Currently, when i try to auto-fill a form, in the community log update, with the audio "the patient is having a temperature of 96", that time, even though the community log update, does not have the temperature field, the data;s is been filled in the temperature and when you save the community log update, the temperature is also being getting saved

**To Reproduce**

1. Go to log update and select community log update
2. give a audio mentioning patient temperature
3. submit the form
4. See the error

**Expected behavior**

- [ ] scribe should only fill form fields, which are part of the selected round type

**Screenshots**

![image](https://github.com/user-attachments/assets/2cbff9e6-57d7-4e61-b462-32bf6f55eed8)
![image](https://github.com/user-attachments/assets/14fbad94-bd6f-44c1-a638-84a3dccdba3e)

**Comment by bodhish** [comment]
This is a not a bug with Scribe; it a form validation issue;

**Comment by Jacobjeevan** [comment]
Taken care of in #8134
