### ISSUE TITLE
Increase the width of investigation view details page padding

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8583]
**Bug Description**

An unnecessary scrollbar appears on a standard laptop screen on the investigation details page.

Steps to Reproduce:

- [ ] Navigate to the "Patient" tab and select any card with an active consultation.
- [ ] Click on the "Investigation" tab and select the "Log Update Result" button.
- [ ] After creating a log, click on the "View" button on the card of the newly created log.
- [ ] Observe the error: a scrollbar appears unnecessarily.

**Expected Behavior**

 Adjust the width of the investigation details page for standard laptop screen sizes, ensuring that no horizontal scrolling is required.

**Screenshots**

![image](https://github.com/user-attachments/assets/e745d7c2-17b7-442d-9bbd-22a1ae4d108a)

**Comment by rithviknishad** [comment]
@nihal467 isn't this expected for print preview?

**Comment by rithviknishad** [comment]
We shouldn't be having scrollbars in the print preview.

But increasing the width would no longer maintain the A4 size print's width.

**Comment by syedfardeenjeelani** [comment]
hi can you please assign me this issue

**Comment by syedfardeenjeelani** [comment]
unassigning this issue because  i wont be able to work on it right now

**Comment by Jacobjeevan** [comment]
@rithviknishad Can you assign this to me?
