### ISSUE TITLE
Voice autofill Preview box is clipping out 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8587]
Preview box for the Voice Autofill is slighlty clipping out at the bottom side. It looks incomplete
(same on mobile view also)
![image](https://github.com/ohcnetwork/care_fe/assets/75214902/3e0909c6-4f05-407c-a717-c078f4e32f02)

**Comment by Utkarsh-Anandani** [comment]
Hello @samholics can i work on this issue

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad , Is it still an issue ? If yes, Could you tell the reproducing steps for this ?

**Comment by shivankacker** [comment]
Closing as no more applicable, we updated the Scribe UI entirely
