### ISSUE TITLE
ABG Log update -PCO2 decimal number entry not allowed.

### ISSUE THREAD

**Issue by Jrl0** [coronasafe/care_fe#8593]
On doing detailed log update of ABG Test.
All the other fields except Pco2  allow decimal values,Pco2 doesn't allow decimal values entry.
**To Reproduce**

1. Go to a patient dashboard 
2. Click on Log update 
3. Round type Detailed update
4. Update ARTERIAL BLOOD GASES Report.
5. All the field except Pco2 allowed decimal value entry.
6. Unable to save the data of not integer value.

**Comment by kushalbhana** [comment]
@nihal467 ig this is a backend issue. Can you assign it to me?
