### ISSUE TITLE
Bug: File are Missing in consultation page 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8595]
**Describe the bug**

The pagination is missing on the consultation page, so the users are only able to view latest 14 files.

**To Reproduce**

**Expected behavior**

Users should be able to view all files with the help of pagination

**Screenshots**

![WhatsApp Image 2024-09-23 at 17 24 58_c3a9d7ae](https://github.com/user-attachments/assets/6f52fd3b-343b-4291-aaa5-0312769371c2)

**Comment by rithviknishad** [comment]
Ack
