### ISSUE TITLE
Create a Board View for release

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8609]
**Action Item**

- [x] Add a new field called release and mark all the closed issues with the related software version
- [ ] Create an action to automate, checking all PRs being merged to the staging branch, their related issues are automatically tagged with upcoming release tag.

Below are the scenario's related to a PR

1. PR without issues linked
2. PR with multiple issues linked
3. PR with single issue linked

**Comment by tellmeY18** [comment]
@khavinshankar

**Comment by bodhish** [comment]
@tellmeY18 @nihal467 lets do this maually for somethime before automating? I would say it shoudn't be automated, from PR's that are open, the once you think that are going in should be marked here. 

One of the main advantage that we are looking at with this feature is to streamline our release plan, we should put target on the issues that we are planing to release in a week. This will also help the deveopers working on the issue get a feeler of when we are planning to deploy these.

**Comment by i0am0arunava** [comment]
> **Action Item**
> 
> * [x]  Add a new field called release and mark all the closed issues with the related software version[ ]  Create an action to automate, checking all PRs being merged to the staging branch, their related issues are automatically tagged with upcoming release tag.
> 
> Below are the scenario's related to a PR
> 
> 1. PR without issues linked
> 2. PR with multiple issues linked
> 3. PR with single issue linked

@nihal467 does this issue fall under leaderboard codebase
