### ISSUE TITLE
[Bug] Add New User - Clearing Facilities Field Causes White Screen

### ISSUE THREAD

**Issue by chakribontha** [coronasafe/care_fe#8610]
**Describe the bug**
In Add New User after selecting the Facilities field with any input and clearing it shows a blank white page.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Users in the sidebar
2. Click on User and right top you will see Add New User
3. select any input in the Facilities field and clear it using [x] inside the field
4. See the error in the console

**Expected behaviour**
even after clearing data in the Facilities input field in Add new user, it should not crash it should not show a white page. And it should only clear input which the user gives.

**Screenshots**

https://github.com/user-attachments/assets/d02bffde-3652-420e-93d8-93e3124b5e6d

**Comment by AdityaJ2305** [comment]
@chakribontha I’ve resolved the issue. Could you please assign me so I can push the PR and discuss it? Thank you!

**Comment by AdityaJ2305** [comment]
Hey , @nihal467 @chakribontha , Could you assign this issue to me so that I can push the pr ?

**Comment by nihal467** [comment]
@AdityaJ2305 since its a p1 issue, try to push the PR with 24-48 hours
