### ISSUE TITLE
Change "Ventilator Spo2" to "Spo2" On Events Module

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8611]
**Describe the bug**
When updating Spo2 values in the vital section on Brief update, Progress Note and Tele-Medicine Round Types, It shows as "Ventilator Spo2" on Events Module.
**To Reproduce**

1. Go to a patient file
2. Click on log Update and select Brief Update as round type
3. update the SPo2 field and submit, then go to events module 

**Expected behavior**

**Screenshots**
<img width="233" alt="image" src="https://github.com/user-attachments/assets/c26c5045-b2c1-4688-bda4-6c18e5b2d6a0">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jacobjeevan** [comment]
Included in #8612

**Comment by bodhish** [comment]
@Jacobjeevan assign the issue to yourself
