### ISSUE TITLE
Change the "Ventilator Interface" when Respiratory Support Selected as "Oxygen Support"

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8612]
**Describe the bug**
When selecting and updating Oxygen Support as Respiratory Support on Detailed and Progress note log updates, The updated values are showing in the events module captioned as ventilator Spo2, Ventilator Oxygen Modality, Ventilator Interface as Oxygen Support and ventilator oxygen modality oxygen flow rate. 

(* Oxygen Support is not a Ventilator Parameter But a Respiratory Support type.)
 @aparnacoronasafe pls add suggestions
- [ ]  Change the caption "Ventilator Interface" When Oxygen Support is selected.
- [ ] Change the Ventilator Spo2 to Spo2
- [ ] Chante the Ventilator Oxygen Modality to Oxygen Modality
- [ ] Change the Ventilator Oxygen Modality Oxygen Flow Rate to Oxygen Flow Rate

**To Reproduce**

1. Go to a patient file and file a Detailed log update
2. update Respiratory Support parameter by selecting Support as Oxygen Support 
3.update oxygen Modality,oxygen flow rate and Spo2

**Expected behavior**

**Screenshots**
<img width="220" alt="image" src="https://github.com/user-attachments/assets/5ddeaa21-fcb1-4502-ab5e-260fc8b2db84">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Indrajeety993648** [comment]
@rithviknishad  I would like to work on this issue  , please assign it to me

**Comment by bodhish** [comment]
@Jacobjeevan assign the issue to yourself

**Comment by Jacobjeevan** [comment]
>     * [ ] Change the Ventilator Spo2 to Spo2

https://github.com/ohcnetwork/care/pull/2397 takes care of this 👍 

>     * [ ] Change the Ventilator Oxygen Modality to Oxygen Modality
>     * [ ] Change the Ventilator Oxygen Modality Oxygen Flow Rate to Oxygen Flow Rate

Including these two in https://github.com/ohcnetwork/care_fe/issues/8264 as I need them there as well.
