### ISSUE TITLE
Camera feed overlaps with navigation tabs in patient consulatation dashboard

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#8616]
**Describe the bug**
The camera options are overlapping with other features such as files overview, feed, and vitals. When we activate the camera, we can’t directly access other options like files, ABG, and vitals because they become disabled.

Note: its replicable in windows 13 inch screens with chrome browser, at the same time, the bug is not visible in firefox browser of the same device

**To Reproduce**

1. Go to 'Patients'
2. Click on any of the patient with feed (https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/feed)
3. Go to 'Feed' tab

**Expected behavior**
Camera feed should not overlap with navigation

**Screenshots**
![image](https://github.com/user-attachments/assets/150e2b2a-d652-444f-9e4f-07aac0ff2b98)

**Comment by syedfardeenjeelani** [comment]
hello @khavinshankar , sorry but i am not able to find the feed tab can you please guide me a little more on how can i reproduce this bug.
thank you for your time!

**Comment by nihal467** [comment]
@syedfardeenjeelani 

1. Go to the critical care facility
2. open the patient card named "Gigin"
3. once you are in the patient consultation page, click on the feed button on the top right corner
4. you will see the error

**Comment by syedfardeenjeelani** [comment]
@nihal467  thank you so much for the explanation
