### ISSUE TITLE
Add tooltip for Discussion Notes Icons

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8618]
**Is your feature request related to a problem? Please describe.**
Currently there are 5 different icons are present in the discussion notes module. But the icons are displayed without any names or titles. it will makes the users unaware about these features or might not use it. 

**Describe the solution you'd like**
Please provide proper titles or names when hover above the icons. 

<img width="292" alt="image" src="https://github.com/user-attachments/assets/d5c86baf-47d3-41cf-8315-0b22b73f71c9">

- [ ] first one can be names as ~"Logs"~ "Open in full window"
- [ ] second one can be "Minimize"
- [ ] third one can be "Close"
- [ ] fourth one can be "Reply"
- [ ] Fifth one can be "Send" 

Here is an example of captioned or named icons from care itself (facility page - Adding Bed Numbers section)
![image](https://github.com/user-attachments/assets/d32a16ce-e2ee-49e4-8670-033266b479fd)
Here when u hover above the edit and delete icons it will display the names.

**Comment by syedfardeenjeelani** [comment]
can i take up this issue please @samholics ?

**Comment by GuntreddyHemanth** [comment]
Interesting! Can I give it a shot on it, please assign it to me.

**Comment by syedfardeenjeelani** [comment]
Hi @rithviknishad  @nihal467,

I kindly request you to review this PR as I had to set up the repo again after deleting the head repo due to some issues I was facing after rebasing. Unfortunately, this resulted in all my previous PRs being lost, so I had to raise them again.

Thank you for your understanding!
