### ISSUE TITLE
Actions: Extend options in dropdown

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8620]
**Is your feature request related to a problem? Please describe.**
There is an "Actions" label that can be added on patient file through consultation or log update forms. The options there are outdated. 

**Describe the solution you'd like**
Edit the options in dropdown in actions to include: 
Review needed (rename "review" to "review needed")
Plan for homecare (NOT ICU)
**Doctor's consultation**
Specialist Required
**Physiotherapy consultation** (NOT ICU)
**ISM Consultation** (NOT ICU)
**Homeo Consultation** (NOT ICU)
Specialist nurse required 
Follow up not required 
Discharge recommended

The ones marked in Bold are the new options to be added.
Remove the options
Pending
Complete
Not reachable
No Action

**Describe alternatives you've considered**

**Additional context**

**Comment by nihal467** [comment]
Already part of current develop
