### ISSUE TITLE
Community nurse log update- critical are index

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8621]
**Is your feature request related to a problem? Please describe.**
Currently, Community nurses file the log update (round type- "Community nurse log update") whenever they visit a patient at home. 

the form has various fields which are most commonly used. 

However, some of the other sections in the critical care index may also be relevant for the patient like I/O balance, etc.

**Describe the solution you'd like**
When user submits the log update (round type- "Community nurse log update"), take user to the critical care index. 
Hide ABG, dialysis and nursing Care sections from the index since these are not needed.

(Eg: look at the log update (round type- "Doctor's Progess Note") to see the suggested flow)

**Comment by Jash2606** [comment]
**Hey @rithviknishad** , I'd like to contribute to this issue. Could you please assign it to me?

**Comment by bodhish** [comment]
@aparnacoronasafe @Jacobjeevan hold this issue, we are planning to rebuild the entire section.

**Comment by ayushpatil2122** [comment]
can you assign this issue to me

**Comment by bodhish** [comment]
Closing the issue as it would be resolved with the new form builder
