### ISSUE TITLE
Show validation error message on facility cover image upload

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8625]
**Describe the bug**

When we are trying to upload a cover image (attached with this issue) to a facility, the frontend is throwing the "something went wrong" error

Note: When you capture image using the camera component in the cover image module, its working

**To Reproduce**

1. Go to the facility tab
2. click on any facility card
3. try to upload a facility cover image

**Expected behavior**

- [ ] when we upload a facility cover image, it should work properly
- [ ] Rather than "something went wrong" , proper error's should be thrown incase of failure

**Screenshots**
![87](https://github.com/user-attachments/assets/d843eb72-98f9-4b1b-ae04-9894146f2061)

![image](https://github.com/user-attachments/assets/6db1347e-f25c-4543-b7d1-436c5eec4931)

**Comment by sainak** [comment]
backend response:
```json
{"cover_image":["Image width is greater than the maximum allowed width of 1024 pixels.","Image height is greater than the maximum allowed height of 1024 pixels."]}
```

https://github.com/ohcnetwork/care/blob/11b62ee48998edad6db55fee337ff8e063bd1a0e/care/utils/models/validators.py#L339-L346

**Comment by syedfardeenjeelani** [comment]
can i work on this issue ? @sainak  @nihal467

**Comment by nihal467** [comment]
@syedfardeenjeelani Could you please prioritize pushing the fix by the end of today? We need to address this issue as soon as possible before our upcoming weekly release.

**Comment by syedfardeenjeelani** [comment]
Hey @nihal467  , I’ve completed the work on issue #8618  locally. Now, I’ll be moving on to this new issue and i will try my best  to have it wrapped up by the end of today.

**Comment by syedfardeenjeelani** [comment]
hello @nihal467  i have finished this task locally but before pushing can you please guide me a little on what excalty we have to keep in the  i18n locale files and what is  useTranslations?
