### ISSUE TITLE
Improve the Facility details page UI

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8626]
**Describe the bug**

When we add multiple facility features and link several spoke facilities to a single facility, the data on the respective facility detail page is displayed collectively. However, the layout is inefficient, with a lot of unnecessary white space, making it difficult to present the information effectively.

**To Reproduce**

1. Open any facility card
2. Click on manage facility and update the facility
3. Add multiple features, link spoke facilities to the facility, and submit the form.

**Expected behavior**

- [ ] Improve the UI layout properly to effective utilise the spaces and show all the relevant details

NOTE: Whoever is working on this issue, please ensure that the mock UI design is approved either in the Slack care_general channel or during the EOD call discussion before starting any coding work.

**Screenshots**

![image](https://github.com/user-attachments/assets/37b1df91-b512-4df2-adeb-de3dab3233df)

**Comment by bodhish** [comment]
@nihal467 this will be addressed while we work on the HMIS
