### ISSUE TITLE
Modify bed creation notification to show proper action related notification

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8627]
**Describe the bug**

When we are creating a single bed or multiple bed, all the time, the notification shown is " Bed(s) Created successfully "

**To Reproduce**

1. Open any facility card
2. Open manage facility and click on location management
3. Create a new location and click on the manage bed button
4. add a single bed only
5. see the error

**Expected behavior**

- [ ] If a single bed is created, show the notification: "Bed created successfully."
- [ ] If multiple beds are created, show the notification: "Beds created successfully."

**Screenshots**

![image](https://github.com/user-attachments/assets/1b43d73e-b3bf-4f1e-970d-0edac1de6b1f)

**Comment by AdityaJ2305** [comment]
Hey @nihal467, could you please assign me to this issue? Thanks!

**Comment by rithviknishad** [comment]
@AdityaJ2305 looks like someone already took up this issue. Feel free to check-out other issues.

**Comment by AdityaJ2305** [comment]
Hi @rithviknishad, I just saw your comment. I wanted to bring up that this has happened to me twice now—where someone else submitted a PR for an issue I was already assigned to, without being assigned themselves or checking with the maintainer first.

**Comment by rithviknishad** [comment]
No worries, we'll get your PR approved once the review changes requested are solved.

**Comment by syedfardeenjeelani** [comment]
Hi @rithviknishad ,

Apologies for the confusion! When I started working on the issue, no one was assigned to it. I wasn’t familiar with the guidelines at the time, but I’ll make sure to comment and check before taking on any issue going forward. Sorry again for any inconvenience caused, @AdityaJ2305 .

Additionally, I had  raised another PR for issue #8583 before this. Thank you for understanding!
