### ISSUE TITLE
ABDM & Events api is failing in patient consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8628]
**Describe the bug**

When we open a patient consultation page, two "something went wrong" errors are thrown in the frontend.

- /api/v1/consultation/3b58450a-b69b-4638-b5de-1228615d4dac/events/?limit=14&offset=0 is throwing 500 

- /api/v1/abdm/abha_numbers/9c835b3f-bdcf-4139-9818-a0da6f28e384/ is throwing 404

**To Reproduce**

1. Go to patient tab
2. Click on any active consultation card
3. See error

**Expected behavior**

- [ ] show proper error in the patient consultation page
- [ ] patient consultation page should work properly without firing unwanted request

**Screenshots**

![image](https://github.com/user-attachments/assets/f02f0c36-3704-4a76-a245-72714801ea9e)

**Comment by sainak** [comment]
resolved in https://github.com/ohcnetwork/care/pull/2498

**Comment by bodhish** [comment]
@nihal467 can you look into the error and mention which API failed? It would be easy to debug

**Comment by bodhish** [comment]
@nihal467 can you test and close this issue as @sainak has mentioned it fixed.

**Comment by nihal467** [comment]
the issue is solved in https://github.com/ohcnetwork/care/pull/2498
