### ISSUE TITLE
Asset Camera Configuration Page is throwing unwanted request and error

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8633]
**Describe the bug**

When you open the camera asset configuration page, and stay on that page for 5 seconds, you keep on receiving an "Object Object" error in the frontend

- /api/v1/asset/d5e008e8-2ce6-4c0a-9262-68d910601d42/operate_assets/ request is send on a loop with response 400

**To Reproduce**

1. Go to asset tab
2. Open any camera asset
3. open the configuration page, make sure that they don't have any configuration

**Expected behavior**

- [ ] unwanted requests shouldn't fire from the frontend
- [ ] all related relevant errors thrown should be users readable

**Screenshots**

![image](https://github.com/user-attachments/assets/66e7f585-5c6e-4833-9ee1-d268ff7cceb1)

**Comment by Jacobjeevan** [comment]
For preventing the requests, we can add a hostname check for this scenario (cameraAsset.hostname corresponds to the ip address field).

<img width="570" alt="image" src="https://github.com/user-attachments/assets/70770b31-0b26-4a69-9754-24f1e4fdeccd">

For (2), the error notification is coming from fireRequest (getStreamToken, calling operateAsset):

<img width="593" alt="image" src="https://github.com/user-attachments/assets/5ee407de-dc79-483b-a058-710cd9c21655">

But for this api call, backend is sending a detail object as data.

<img width="602" alt="image" src="https://github.com/user-attachments/assets/f28e813f-c029-4add-a28f-d3712c014ff0">

On a side note, I was testing with a random IP address (expecting a 500 response), however that doesn't trigger further API calls as error.response is not being returned in fireRequest. Should we not change that?

<img width="578" alt="image" src="https://github.com/user-attachments/assets/ceea61ee-9eff-4b87-bcdc-b6263ece9daa">

Resp is undefined so it won't called onError function.

<img width="466" alt="image" src="https://github.com/user-attachments/assets/f885cd1f-744b-46e5-b76f-5a8eb9163516">

@nihal467

**Comment by rithviknishad** [comment]
@Jacobjeevan fixed in #8253 as that switches to using the newer feed component in the configure page which handles errors more appropriately.
