### ISSUE TITLE
Severity Based Sort By in patient list page is malfunctioning

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8634]
**Describe the bug**

When sorting the patient list by "High severity" or "Lowest Severity," the cards are currently being sorted based on the patient category from the initial consultation form. However, the sorting should be done using the most recent patient category from the log updates, if available.

Context: The patient category is assigned during the creation of a patient consultation, but it can be updated later through the log update functionality. When sorting the patient list, the system should first check if any log updates exist for a patient. If a log update is present, the patient should be sorted based on the category in the latest log update. If no log update exists, the category from the consultation form should be used for sorting.

**To Reproduce**
Steps to reproduce the behavior

Create a patient

1. Go to patient tab and create a new patient
2. Once you successfully created a patient , in the patient dashboard click on the log update button
3. then create a new log update with different patient category mentioned from consultation
4. submit the form and return back the patient tab
5. apply the sort by based on high severity
6. See error

**Expected behavior**

- When sorting by "High severity," the order should be:
Actively dying → Critical → Moderate → Mild → Comfort Care
- For sorting by "Lowest Severity," the order should be the reverse:
Comfort Care → Mild → Moderate → Critical → Actively dying.

**Screenshots**

![image](https://github.com/user-attachments/assets/fe3fbfa7-d644-436f-b998-f506cc269652)

**Comment by bodhish** [comment]
Who need this sort?

**Comment by aparnacoronasafe** [comment]
This sorting was introduced after request from TeleICU Hubs to allow doctors to see the most severe cases on top

**Comment by bodhish** [comment]
@aparnacoronasafe we can make it a filter, sorting doesn't make sense, can you specify the use case.

**Comment by aparnacoronasafe** [comment]
I still think severity wise sorting is needed. The doctors in 1 glance would want to know how many severe patients are there and so on.

**Comment by Jacobjeevan** [comment]
What's the status with this? @bodhish @rithviknishad ?

**Comment by bodhish** [comment]
Keeping it on hold;

**Comment by rajku-dev** [comment]
I am interested to work on this issue if relevant? @Jacobjeevan @rithviknishad

**Comment by nihal467** [comment]
not a valid issue based on the current develop
