### ISSUE TITLE
Unable to see  full content of notes of prescriptions

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8643]
**Describe the bug**

When you write a PRN prescription notes for more than 3 lines, the edit prescription page will show a read more button in the note field, but when you try to click on the read more button, the medicine details collapse

**To Reproduce**

1. Go to the patient tab and click on any active consultation page
2. click on the medicine section in the nav bar
3. click on edit prescription and add a prn prescription with three lines note
4. once save, on the edit prescription page, click on the read more button
5. See an error

**Expected behavior**

read more button on the edit prescription page should work properly

**Screenshots**

![image](https://github.com/user-attachments/assets/0abfabec-9269-46ee-8103-e7c6c56d4686)

**Comment by rithviknishad** [comment]
Let's not wrap the Notes field in a `<ReadMore />` component and keep it simple like other fields. The prescription card itself is collapsible if a short version is required, and it'd be simpler to just show all details in full in the expanded view of a prescription.

**Comment by vishwansh01** [comment]
@nihal467 I would like to take this issue

**Comment by vishwansh01** [comment]
@nihal467
 I just created a pull request solving this issue:  https://github.com/ohcnetwork/care_fe/pull/8647
