### ISSUE TITLE
Switch Blood Pressure and temperature dropdown to use TextFormField with type="number" instead of a dropdown

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8644]
**Describe the bug**
Dropdown makes users click an option to confirm selection even after typing it. This makes it difficult to use at times.

**To Reproduce**

1. Attempt to create a log update for a consultation

**Expected behavior**
- Simple numeric input to be used for temperature and blood pressure fields (TextFormField with type="number") instead of a dropdown.

**Screenshots**

<img width="890" alt="image" src="https://github.com/user-attachments/assets/e922d331-c5d9-4b53-a36a-d03dfe33ddf4">

<img width="547" alt="image" src="https://github.com/user-attachments/assets/65706006-9f96-432c-9687-e9920a846d16">

**Comment by 0xkafkaa** [comment]
Hey @rithviknishad, I would like to work on this issue.

**Comment by 0xkafkaa** [comment]
Hey @rithviknishad, I am not working on this issue. Please assign it to someone else.

Regards,
0xkafkaa.

**Comment by pavanydg** [comment]
I would like to work on this. @rithviknishad can you assign this to me?

**Comment by Narendira27** [comment]
Hi @pavanydg, are you still working on this?

**Comment by pavanydg** [comment]
@Narendira27 yes

**Comment by pavanydg** [comment]
hey @rithviknishad. I am not working on this issue. Please assign to someone else.

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad , Could you please assign this issue to me? I’m working on a solution and can make a PR soon.

**Comment by syedfardeenjeelani** [comment]
@rithviknishad  i would like to work on this issue

**Comment by AdityaJ2305** [comment]
Hi @syedfardeenjeelani , I’m almost done with the solution for this issue. Could you please take on another one?

**Comment by syedfardeenjeelani** [comment]
@AdityaJ2305  no problem
