### ISSUE TITLE
Overflow text, z-index and reply functionality breaking in Notes section.

### ISSUE THREAD

**Issue by shauryag2002** [coronasafe/care_fe#8662]
## **Describe the bug**
1. Overlapping elements due to `z-index` changes.
   - The `z-index` of the "created at" in the single chat header causes overlapping issues.
   
2. After entering long text:
   - Entering a long single word breaks the UI.
   - **Example of word:** 
     `Testtttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt`
   - Clicking the reply button also causes the UI to break.
   
3. The "Edit History" for note popup breaks if the text is too large.

## **To Reproduce**

1. Go to the **Patients** tab and click `View patient notes`.
2. Enter a large single word (50 to 70 characters).
3. Observe the error where the text overflows outside the container.
4. Click the **reply** icon, and observe the error again as the text overflows.
5. Click the **View history** icon and see the UI break again due to the long text.

## **Expected behavior**
- The long text should wrap or be truncated so that it doesn’t overflow the UI.

## **Screenshots**
`z-index` issue:
![Notes_zIndex](https://github.com/user-attachments/assets/78327d22-138c-411f-a40f-9a48a5ddd78d)
Text overflow issue:
![Notes_text_overflow](https://github.com/user-attachments/assets/9ec40178-fe1a-4228-a56b-a9ff685f4336)
Reply section text overflow:
![Notes_reply_overflow](https://github.com/user-attachments/assets/95be5094-9ba1-4ae7-bb0f-1765941c22bc)
Edit history pop up text overflow:
![Notes_edit_history](https://github.com/user-attachments/assets/9fabefa0-603f-46e7-a249-4e9dd7df2f74)

**Solution Video:**

https://github.com/user-attachments/assets/98d35065-6253-4940-9710-44f7ab664ce3

## **Desktop (please complete the following information):**
- **OS**: Windows
- **Browser**: Brave
- **Version**: 1.70.119

**Comment by syedfardeenjeelani** [comment]
@shauryag2002  i would like to try to contribute in this issue can you  assign it to me

**Comment by shauryag2002** [comment]
Sorry @syedfardeenjeelani, I am working on this issue and created a Pull request for this issue.

**Comment by syedfardeenjeelani** [comment]
no problem @shauryag2002

**Comment by rithviknishad** [comment]
Closing as not relevant. Works fine without issues for the longest english dictionary word (45 chars) `pneumonoultramicroscopicsilicovolcanoconiosis`.

<img width="424" alt="image" src="https://github.com/user-attachments/assets/ec5836d2-dc2c-4810-8281-82991f9c34de">

**Comment by Sulochan-khadka** [comment]
![Image](https://github.com/user-attachments/assets/445fa9b3-1251-4152-b2aa-2bcb136687e1)
Is this solved @rithviknishad

**Comment by rithviknishad** [comment]
Nope, you can create a separate issue for that alone
