### ISSUE TITLE
Add a cypress test for verify doctor connect functionality

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8669]
- Related dummy data : https://github.com/ohcnetwork/care/pull/2536
- fixed flaky test in location management test
- added functionality test for doctor connect

**Comment by Aswinr24** [comment]
Hey would like to pick up this issue, Can I start working on it?

**Comment by nihal467** [comment]
@Aswinr24 sorry, iam already working on it, feel free to take up any open issue
