### ISSUE TITLE
Add Validation for Insurance input fields in patient registration form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8672]
**Describe the bug**

Currently, the patient registration form lacks frontend validation for the insurance fields, and the backend only validates the member ID and policy ID.

**To Reproduce**

1. Go to the patient tab
2. Click on add patients
3. scroll down and click Add insurance
4. without filling in the fields submit it
5. See an error

**Expected behavior**

- [ ] add backend validation for insurer name 
- [ ] add frontend validation for member id, policy id and insurer name

**Screenshots**

![image](https://github.com/user-attachments/assets/38635329-3597-4ee6-a122-4c021a9a2e82)

**Comment by syedfardeenjeelani** [comment]
hi @nihal467  i would like to try to work on this can you please assign it to me

**Comment by rithviknishad** [comment]
@syedfardeenjeelani as mentioned, this requires backend validation first followed by FE validation.

Would you be making the backend PR too?

**Comment by syedfardeenjeelani** [comment]
@rithviknishad  hey as of now i would be only able to make a FE validation pr please let me know if  that is okay if not then someone else can take it

**Comment by rithviknishad** [comment]
Yes it's okay, just create an issue in backend repo too

**Comment by syedfardeenjeelani** [comment]
@rithviknishad  sure thank you

**Comment by syedfardeenjeelani** [comment]
@rithviknishad   hello and @nihal467  please check the video below and let me know if would like me to do any changes 


https://github.com/user-attachments/assets/71a132d3-30a1-4e0a-bc2b-4ab256e3663d

**Comment by rithviknishad** [comment]
Use `field_required` from the i18n locale (`useTranslations`) for the required field errors. Also ensure that this error is present only for fields having the prop `required=true` set.

**Comment by syedfardeenjeelani** [comment]
@rithviknishad  we are getting the error from the validator.ts  which is something like this 
 if (
    !value.policy_id.trim() ||
    !value.subscriber_id.trim() ||
    (enable_hcx && (!value.insurer_id?.trim() || !value.insurer_name?.trim()))
  )
    return "All fields are mandatory";


so should i use field_required from the i18n locale here instead of  "All fields are mandatory"

**Comment by krVatsal** [comment]
Can i work on this issue?

**Comment by syedfardeenjeelani** [comment]
@krVatsal  hello i have already raised a pr for this feel free to take up on a different issue thank you

**Comment by syedfardeenjeelani** [comment]
@rithviknishad  please review this pr
