### ISSUE TITLE
Google Map API is failing in create facility form of deploy preview's

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8684]
**Describe the bug**

The Google map API is failing in the create facility form of netlify & Cloudflare deploy preview

**To Reproduce**

1. Go to https://a0e1bc19.care-fe.pages.dev/facility/create
2. Click on the map icon on the bottom of the page
3. See error

**Expected behavior**

the google map API should work properly in the facility create form

**Screenshots**

![image](https://github.com/user-attachments/assets/62df96b2-ba92-41a0-aa3b-71a903bd2067)

**Comment by anandaashish74711** [comment]
Hi @nihal467,

I'd like to help resolve the issue with the Google Map API in the facility creation form for the Netlify and Cloudflare deploy previews. Could you please assign this issue to me?

**Comment by bodhish** [comment]
@tellmey18 check this out

**Comment by NitinPSingh** [comment]
the issue might be the url is not added in list of allowed referrers

RefererNotAllowedMapError		
The current URL loading the Maps JavaScript API has not been added to the list of allowed referrers. Please check the referrer settings of your API key in the Cloud Console.

https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error

**Comment by tellmeY18** [comment]
Have the Origin policy and have enabled necessary APIs to fix the issue. Current deploy previews (Cloudflare Pages and Netlify) are loading the map in the create facility Form. However Mobile devices are experiencing trouble loading the resource. Another Issue was filed #8723 to find and solve the problem.
