### ISSUE TITLE
Add tooltip for Expand,Profile and Logout

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8685]
**Is your feature request related to a problem? Please describe.**
Currently there is no tooltip for the " expand,Profile and Logout" icons when we use minimized sidebar option. this makes the users accidentally click logout instead of expand icon. 
**Describe the solution you'd like**
Add tooltip for these three icons 

- [ ] Expand
- [ ] Profile
- [ ] Logout

**Describe alternatives you've considered**

![WhatsApp Image 2024-10-01 at 15 56 33_c8cd3648](https://github.com/user-attachments/assets/ae49729d-d6f2-4e79-9947-f8550fae9b9e)

**Comment by syedfardeenjeelani** [comment]
@samholics  i would like to work on this issue can you please assign it to me

**Comment by anandaashish74711** [comment]
Hi @samholics @rithviknishad ,

I hope you're doing well!I'm interested in contributing. Could you please assign it to me? 

Looking forward to your response!

**Comment by samholics** [comment]
@rithviknishad pls do the needful

**Comment by rithviknishad** [comment]
We are rebuilding the sidebar in #8680;

@anandaashish74711 feel free to branch out from the #8680's branch and create changes targeted to that branch. When raising the PR, just ensure #8680's branch is set as the base branch instead of `develop`

cc: @bodhish
