### ISSUE TITLE
Add a better search UI for patients index page

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care_fe#8691]
In the current patient page, we have 4 independet search on patient, at any point in time you can only search by one practically.
Here is an how the current UI looks.  
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/0971d608-73f8-491a-b8e9-859c14075cd6">

Let upgrade it with a smart search compoent where the user can select what to search for. 
![image](https://github.com/user-attachments/assets/91099d34-5c4c-44fd-8da0-094265bbbacd)

It should also support keyboard short cuts. 
![image](https://github.com/user-attachments/assets/8830e0fd-8322-4544-9e64-dd86863b2f2b)

The valid options would be Name | Phone Number | OP/IP number | Emergency Contact Number.

Also reduce the height of the count box to match the component.

**Comment by pavanydg** [comment]
@bodhish please assign me.

**Comment by Jash2606** [comment]
Hey @bodhish @rithviknishad ,
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by bodhish** [comment]
@Jash2606 its a UI heavy issue, would you be able to do it? 🤔

**Comment by Jash2606** [comment]
Hey @rithviknishad ,
I had created a Updated UI for search bar , Could you review it and Please let me know if any further changes required !

**Comment by i0am0arunava** [comment]
@bodhish @rithviknishad, I'd like to contribute to this issue. Could  you please assign this to me?

**Comment by i0am0arunava** [comment]
I have started to work on it.

**Comment by i0am0arunava** [comment]
@bodhish @rithviknishad @Jacobjeevan
,I have completed the work. If there are any issues , please provide feedback. Pressing Ctrl + '/' will open a palette, and users can navigate through the options using the arrow keys on the keyboard. Additionally, also I have  reduce the height of the count box to match the component. If everything looks good, please let me know before I make the pull request. Is there any other process I need to complete?
here is my work ![Image](https://github.com/user-attachments/assets/217a952d-d85a-4c1c-9a64-8c6c33bc7a49)

**Comment by bodhish** [comment]
@i0am0arunava without seeing the code its hard to give feedback; In general try to make it in sync with design

**Comment by i0am0arunava** [comment]
@bodhish @rithviknishad @Jacobjeevan,I have raised a pull request; please review it and provide feedback.

**Comment by i0am0arunava** [comment]
@bodhish ,I am sharing you a video to show part of my work ,for the last point keyboard shortcut '/' is it okay?

**Comment by i0am0arunava** [comment]
@bodhish ,I am sharing you a video to show part of my work ,for the last point keyboard shortcut '/' is it okay?

**Comment by i0am0arunava** [comment]
@bodhish @rithviknishad @Jacobjeevan, Bodhish sir fixed the issue https://github.com/ohcnetwork/care_fe/tree/filter-component.                              
what should I do next ?

**Comment by i0am0arunava** [comment]
@bodhish @rithviknishad @Jacobjeevan,I accidentally deleted the forked repo. I have cleaned up the unrelated changes and raised a new pr please review it .https://github.com/ohcnetwork/care_fe/pull/8834
