### ISSUE TITLE
Feat: Allow Users to Edit and Delete Their Own Comments in shifting and Resource

### ISSUE THREAD

**Issue by chakribontha** [coronasafe/care_fe#8701]
**Is your feature request related to a problem? Please describe.**
currently, users cannot modify or delete their comments after posting them. This limits users' control over their content, which can be frustrating if they make a mistake or want to revise their input.

**Describe the solution you'd like**
Allows users to:

- Edit their comments after posting. An "Edit" button will allow users to modify the text of their comments, and changes will be saved upon -submission.
- Delete their comments. A "Delete" button will allow users to remove their comments after confirming the action.

**Additional context**

This feature should include access control to ensure only the comment creator can see the "Edit" and "Delete" options.

Consideration of UI/UX elements such as confirmation prompts for deletions and inline editing for comment modifications.

![Image](https://github.com/user-attachments/assets/76eb7dde-e382-4aaa-9981-eec68c79fbe3)
![Image](https://github.com/user-attachments/assets/ee687520-2af3-4598-b323-9fe8ff0c9dae)
![Image](https://github.com/user-attachments/assets/aa83d94f-afc5-4b0d-92ea-7b636270964d)

**Comment by sankshaypusa** [comment]
HI @chakribontha can you assign this issue to me

**Comment by anshx112** [comment]
working..

**Comment by chakribontha** [comment]
@rithviknishad
