### ISSUE TITLE
Find a better way to import translations for each language

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#8705]
https://github.com/ohcnetwork/care_fe/pull/8692#discussion_r1786764799

Currently we are importing translations by manually importing json files into an index.ts file and then importing that file into the i18n config as a module. We should find a better way to manage this.

**Comment by GuntreddyHemanth** [comment]
Please assign to me

**Comment by shivankacker** [comment]
Closing this as we have switched to using single language files
