### ISSUE TITLE
Add Badges for Hub Hospital and Spoke hospital.

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8719]
**Is your feature request related to a problem? Please describe.**
Add Bagdes for Hub Hospital and Spoke Hospital on facility card. It will helps to identify the facilities which are Hub Hospital and which are spokes. Specially for Admin users. Also show the Hub Hospital Name on Spoke hospital facility page. 
@aparnacoronasafe

suggestions from the field are- 
- [ ] Add Hub Hospital Badge for the facility where spoke hospitals are linked.
![Image](https://github.com/user-attachments/assets/118ab88c-2872-4a5c-ae69-eecbaca7c772)

- [ ] Add Spoke Hospital Badge to the facility which is linked under a Hub facility . Users wants to see the name of the Hub hospital without going into facility page.  
- Here its difficult to show Full name of the Hub Hospital as a badge on spoke facility card. may be Add badge as "TeleICU Spoke" and avail the feature to display the name of the Hub hospital when Hover over it or Click on it. 
![Image](https://github.com/user-attachments/assets/36e0681b-5a6f-49b7-aed5-b63a51a57a2d)

- [ ]  Add the Hub hospital's Name on facility page of Spoke Hospitals , like spoke hospital listed on Hub hospital's facilty page. But doesnt need to redirect when clicking on the that facility since its a Hub facility 
![Image](https://github.com/user-attachments/assets/b53fc2aa-e274-4f41-83fa-2532a5c3e18b)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shivankacker** [comment]
As discussed on Engineering sync call on 7/10/24

- We do not need to show badges on the facility card
- Both spoke and hub hospitals need to be shown on the facility detail page
