### ISSUE TITLE
Bugs Detected After Merging PR #8737 , PR #8706, PR #8680

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#8740]
Follow-up : https://github.com/ohcnetwork/care_fe/pull/8737 , https://github.com/ohcnetwork/care_fe/pull/8706 , https://github.com/ohcnetwork/care_fe/pull/8680

**Bugs**

- [x] typo's are missing in the patient details page

![Image](https://github.com/user-attachments/assets/bb68d2da-1506-459b-9fa1-feb3cdebc8c0)

- [x] when you try to use restore button in the log update page, it won't restore any data to the form

![Image](https://github.com/user-attachments/assets/1960112a-1875-42d4-babf-6a304917f25d)

- [x] Sign out button icon is misaligned

![Image](https://github.com/user-attachments/assets/5a45bd1a-b47d-4b09-ace2-bcb1b4630bf3)

- [x] Make sure the minimum height for the content area takes up the height of the viewport across the platform

![Image](https://github.com/user-attachments/assets/12607fd1-cb40-4bf4-a692-2917d9370a2d)

- [ ] The relative time for the "Restore" button on the form is calculated based on when the user entered and exited the form. For example, if the user accessed the registration form at 1:00 PM and reloaded the page at 1:05 PM, the relative time displayed on the button should indicate "a few seconds ago." However, it currently shows "5 minutes ago" because the relative time is being calculated from the moment the user first entered the form, rather than from when the page was reloaded.

![Image](https://github.com/user-attachments/assets/7eb48c1c-07fe-4566-af48-36684e97d06f)

- [x] The breadcrumb navigation isn't functioning as expected, preventing users from returning to the immediate previous page. For instance, when a user is on the consent record page (which is part of the consultation page), clicking on the "admitted on..." breadcrumb should ideally take them back to the patient consultation page, but the now its not even clickable. This similar issue is occurring across the platform, where navigating back to the most recent previous page via breadcrumbs is consistently broken

![Image](https://github.com/user-attachments/assets/74f699da-6038-42be-a6b2-967dbb86bd35)

- [x] The Favicon is stretched. Use a 1:1 Favicon ratio

**Enhancements**

- [x] the width of the autocomplete text box and add button in Slideover such as linked facility, and linked skills, are mispositioned, increasing the text field width should fix it
![Image](https://github.com/user-attachments/assets/f7dc7243-31f9-4d7f-b974-3a2d35beb376)

- [x] the card in the location management page and the page heading is misaligned, this similar issues of padding and heading getting misalinged is observed in other pages as well such as bed management
![Image](https://github.com/user-attachments/assets/9dd95a78-14aa-42ee-bd1a-c88c4f455ac1)

- [x] Only show one loader for the entire page, rather than individual loader for each card in the facility location page 
![Image](https://github.com/user-attachments/assets/b45fe662-4134-45f1-95c4-b245998a4bba)

- [x] Remove the green bg for the collapse chevron in the sidebar. Just keep the chevron as black, and add a light gray bg on hover.

![Image](https://github.com/user-attachments/assets/12dc7bf0-1346-410d-b1c2-013305c4fa6c)

- [x] add border colour to the border of covid details section, since the separation is not properly visible 

![Image](https://github.com/user-attachments/assets/0b648ad7-e4f3-468a-b520-f817af6f2914)

**Comment by AdityaJ2305** [comment]
Can You assign me this issue please ?

**Comment by shivankacker** [comment]
@AdityaJ2305 assigned

**Comment by bodhish** [comment]
@AdityaJ2305 I will take this up

**Comment by AdityaJ2305** [comment]
@bodhish sure

**Comment by gigincg** [comment]
@nihal467 Can you double check if all of these items are a direct result of the mentioned PRs. And are not issues in Staging/Production.

**Comment by nihal467** [comment]
@gigincg moved all bugs out of this issue which are not caused by merging the mentioned three PR's
