### ISSUE TITLE
Discharged page jumps to page 1

### ISSUE THREAD

**Issue by Sulochan-khadka** [coronasafe/care_fe#8752]
**Describe the bug**
Whenever any patient details is viewed in page other than 1, on returning back, the dashboard returns to page 1, which is not an expected behaviour ; It does not happens with live patients.

**To Reproduce**

1. Go to 'patients tab'
2. Click on 'discharged' tab and click on any facility
3. Scroll down to 'page index'
4. move to any other page than 1
5. click the patient to view details
6. move back
7. see error

**Expected behavior**
The page must not jump to page 1.

**Recording**
https://github.com/user-attachments/assets/0d022933-a57f-4171-b1a2-39cc1d2173c6

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sulochan-khadka** [comment]
@nihal467 @rithviknishad let me know if this is an actual issue.

**Comment by rithviknishad** [comment]
Yes, would you be working on it?

**Comment by Sulochan-khadka** [comment]
> Yes, would you be working on it?

yeah...

**Comment by Naman-B-Parlecha** [comment]
This looks like an interesting issue can i work on this issue @rithviknishad ?

**Comment by Sulochan-khadka** [comment]
@Naman-B-Parlecha its great that this issue was able to grow interest in the organisation and contributing to its issues. However, i am about to raise a PR for this. You can have other issues to solve.

**Comment by Naman-B-Parlecha** [comment]
@Sulochan-khadka no worries man looked interested would love to see how u have solved this issue🙌
