### ISSUE TITLE
Reposition the page loader in main homepages to be placed in the center

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8762]
**Describe the bug**

Whenever we switch tab in the main pages such as facility, patient, assets, etc... the page loader is placed in the bottom of the page

**To Reproduce**

**Expected behavior**

Adjust the position of the page loader on all tab pages (e.g., patient tab, facility tab, etc.) to appear in the center of the screen. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/566d3fba-9864-4241-803a-c5c50d5e2665)

**Comment by GuntreddyHemanth** [comment]
can you assign this to me! I would love to take up this issue.

**Comment by NitinPSingh** [comment]
hi @GuntreddyHemanth , if you are not working then I can work

**Comment by syedfardeenjeelani** [comment]
@nihal467  i would like to try to work on this issue can you please assign it to me

**Comment by i0am0arunava** [comment]
@rithviknishad  @nihal, I would like to work on this ,can you please assign it to me

**Comment by SwanandBhuskute** [comment]
@rithviknishad @nihal467 I would like to work on this issue, pls assign me

**Comment by SwanandBhuskute** [comment]
I am done with the work , 
this is how it will look
![Image](https://github.com/user-attachments/assets/48c6b754-1402-471a-8543-d3e76e56f2bd)
![Image](https://github.com/user-attachments/assets/972f0860-2335-4037-981f-bea705647c46)
![Image](https://github.com/user-attachments/assets/c03ede75-2e85-426c-ba88-e306a70da12e)
![Image](https://github.com/user-attachments/assets/aba4ec5b-2d4a-4616-b1e9-ad1eec42695a)

**Comment by rithviknishad** [comment]
@SwanandBhuskute there is already a PR linked to this #8976

**Comment by nihal467** [comment]
@Suhail2701
