### ISSUE TITLE
Increase the width of medical history details Text area in patient registration form on mobile view

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8763]
**Describe the bug**

in the mobile view, the medical history details text boxes in patient registration form is not using the full width of the view port

**To Reproduce**

1. Go to patient tab
2. Click on add patients
3. switch to mobile view and select any medical history 

**Expected behavior**

increase the width of medical history details text box in mobile view to adjust with view port size

**Screenshots**

![Image](https://github.com/user-attachments/assets/67ae43fc-9a19-4efa-9982-7d31cf7505be)

**Comment by GuntreddyHemanth** [comment]
can you assign this to me! I would love to take up this issue.

**Comment by abhip161** [comment]
hey @nihal467  could you please assign this issue to me?

**Comment by abhip161** [comment]
hey @GuntreddyHemanth let me know if you are not working on this issue

**Comment by GuntreddyHemanth** [comment]
Please assign to someone I not working on it right now

**Comment by syedfardeenjeelani** [comment]
@nihal467 @rithviknishad  i would like to try to work on this issue

**Comment by krVatsal** [comment]
If this issue still persists can you assign it to me?
