### ISSUE TITLE
Replace CARE text with CARE Logo in Login Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8764]
- [ ] Replace the "CARE" text with the new Care logo on the login page

![Image](https://github.com/user-attachments/assets/d291a542-a2d6-4cb0-8b6a-24d9e50fb537)

**Comment by GuntreddyHemanth** [comment]
can you assign this to me! I would love to take up this issue.

**Comment by nihal467** [comment]
> can you assign this to me! I would love to take up this issue.

@GuntreddyHemanth it is a blocked issue, discussion going on, feel free to work on other open issues

**Comment by bodhish** [comment]
Let's not replace
