### ISSUE TITLE
Date Picker Does Not Display Correctly on Mobile Devices

### ISSUE THREAD

**Issue by shauryag2002** [coronasafe/care_fe#8772]
**Describe the bug**
The date picker component does not render correctly on mobile devices. When selecting a date, the calendar appears out of alignment, leading to a poor user experience. 

**To Reproduce**

1. Click on Patients from sidebar.
2. Now, click on any patient.
3. Click on the `Date of onset` date picker input field in small screens.
5. See responsiveness error of date picker overflowing.

**Expected behavior**
The date picker component should render correctly on mobile devices. When selecting a date, the calendar should appear aligned and fully visible within the viewport, providing a seamless user experience.

| **Before** | **After** |
|-----------------|-----------------|
| ![Before](https://github.com/user-attachments/assets/525c3021-9967-414b-acb5-d70e3d66243c) |  ![After](https://github.com/user-attachments/assets/55f8284b-6535-4b6d-8cfd-52426c5e9aa8) |

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Brave
- Version: 1.70.126

**Comment by shauryag2002** [comment]
I am working on this .

**Comment by shivankacker** [comment]
@shauryag2002 we are updating the date picker component in https://github.com/ohcnetwork/care_fe/pull/8504 
This issue will be covered by that PR. Thanks for taking the time out to contribute!
