### ISSUE TITLE
CLOCK FORMAT REQUEST

### ISSUE THREAD

**Issue by Howni** [coronasafe/care_fe#8783]
In our current CARE software the time for CLOCK format is selected as per the format from our computer system. If the clock format in our system is 12 hour or 24 hour format, the time in our CARE software will select to 12 hour our 24 hour respectively. I kindly request you to give an option of CLOCK format directly in our CARE software so that it won't be a confusion for our staff nurse to select the timing of admission of patients.
![Image](https://github.com/user-attachments/assets/0f633d54-e82c-4442-9820-b99138337e8d)
![Image](https://github.com/user-attachments/assets/d9509f47-8cf3-4670-97b8-bb486b6ce096)

**Comment by gigincg** [comment]
Closing this for now based on the discussions with the field team.
