### ISSUE TITLE
Individual Process wise Filtered Shifting CSV Generation is not working properly

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8785]
**Describe the bug**

Currently, when we click on the export button of any individual shifting process  card such as destination approved, completed, etc... , the generated .csv is not give the list of the specific process, rather it is generated the entire shifting list with all the process cumulated

**To Reproduce**

1. Go to shifting board
2. Click on export button in the destination approved card
3. See error

**Expected behavior**

when we click on export on any process card, such as destination approved, completed, etc..., it should generate .csv with data having that particular status

**Screenshots**

![Image](https://github.com/user-attachments/assets/857c2ae4-84b3-4f42-983b-937bbd626f00)

**Comment by abhip161** [comment]
hey @nihal467 can you assign  to me! I would love to take up this issue.
