### ISSUE TITLE
Text Overflow in Patient Notes

### ISSUE THREAD

**Issue by Sulochan-khadka** [coronasafe/care_fe#8794]
**Describe the bug**
Overflow of text in doctor's and nurse's discussions

**To Reproduce**

1. Go to patients tab
2. Click on a patient component which has "view patients notes" option
3. Click on "view patients notes"
4. Type a very long string 
5. See error

**Expected behavior**
No overflow

**Screenshots**
![Image](https://github.com/user-attachments/assets/f93451cb-92df-4112-a10f-c56967de4476)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rithviknishad** [comment]
Closing as irrelevant. Reason: https://github.com/ohcnetwork/care_fe/issues/8662#issuecomment-2382054338
