### ISSUE TITLE
"Created-at" section peeping out of "Doctor's discussion"

### ISSUE THREAD

**Issue by Sulochan-khadka** [coronasafe/care_fe#8795]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/da6cb1c8-8383-411f-9302-30df3c5a18ac)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bodhish** [comment]
@Sulochan-khadka please complete the issue description
