### ISSUE TITLE
Unnecessary API Call on Profile Update Without Changes

### ISSUE THREAD

**Issue by JavidSumra** [coronasafe/care_fe#8804]
**Bug Description:**

When updating the user profile without making any changes to the form fields, a "PATCH" request is still sent to the backend, even though no updates have been made.

---

**Steps to Reproduce:**

1. Navigate to "/user/profile"
2. Click on "Edit User Profile"
3. Scroll down and click the "Update" button without modifying any fields
4. Observe that a PATCH request is made to the backend despite no changes

---

**Expected Behavior:**

No API call should be triggered if there are no updates made to the form fields.

**Screenshots or Videos**

[![Watch Video](https://via.placeholder.com/150x50.png?text=Watch+Video)](https://github.com/user-attachments/assets/49d501f7-c297-47bf-9426-2fb491be9c4a)

---

**Desktop:**

- OS: Windows
- Browser: Chrome
- Version: 129.0.6668.101

---

**Additional Context:**

An extra API call is unnecessary if no data has been modified.

**Comment by JavidSumra** [comment]
I would like to take on this issue and work on it.

**Comment by rithviknishad** [comment]
Nice find @JavidSumra 

Expected behaviour:

Update button to be disabled if nothing changed
