### ISSUE TITLE
Improving UI of Patient Details page

### ISSUE THREAD

**Issue by Mahendar0701** [coronasafe/care_fe#8808]
The Patient Details page needs to be updated to follow the new design. The current layout should be changed to look like the design shown below:

![Image](https://github.com/user-attachments/assets/9c085027-f025-4bc3-9e78-237f695e40e1)

**Comment by Mahendar0701** [comment]
Hey @rithviknishad  @nihal467 can i work on this?

**Comment by bodhish** [comment]
We are planing to rebuild these pages, so I don't think we should spend time building it now

**Comment by bodhish** [comment]
We decided to move on with this pr. @Mahendar0701 assigning it to you.

**Comment by bodhish** [comment]
@Mahendar0701 suggest story point

**Comment by Mahendar0701** [comment]
@bodhish expecting 5 story points
