### ISSUE TITLE
Improvement Needed for Advanced Filter and Sort By Features in Patients Tab

### ISSUE THREAD

**Issue by Rishith25** [coronasafe/care_fe#8810]
## Description:
There is a need for clarification on the expected behavior of the Advanced Filter and Sort By functionalities in the Patients tab. Currently, clearing the advanced filter resets the sorting order, which is not the intended behavior.

## Steps to Reproduce:

Navigate to the Patients tab.
Sort the patient data by name.
Apply an Advanced Filter (e.g., filter by gender).
Clear the Advanced Filter.

## Expected Behavior:
When the Advanced Filter is cleared, the sorting order (by name) should remain unchanged. Users should be able to retain the sort order regardless of filter status.

Screenshots or Videos:

https://github.com/user-attachments/assets/936e8206-a1b4-434e-b4d9-cca999262df0

**Comment by bodhish** [comment]
The purpose of the clear button is to clear all applied filters. Its expected to clear the sort filter also.

@rithviknishad to reconfirm.

**Comment by rithviknishad** [comment]
As a user, I'd expect the behaviour to be "reset everything to original state" in mind, and hence that'd include the sort filter too.

Just checked with github issues page too 😄 
Clearing the filters also removes the applied sort ordering too.

**Comment by rithviknishad** [comment]
Should we consider renaming the clear button to something more appropriate instead? @bodhish

**Comment by bodhish** [comment]
Nah, let's get feedback from users and then decide if they complain
