### ISSUE TITLE
Bug: Active Manage Bed button in Location Management Page is greyed out

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8814]
**Describe the bug**

The manage bed button in the location management is currently greyed out, even though the button is active and clickable.

**To Reproduce**

1. Go to facility card
2. Click on view facility on any card
3. click on manage facility and click on the location management

**Expected behavior**

- [ ] The manage bed button should be similar to the rest of the buttons ("edit" and "delete" buttons) in the card

**Screenshots**

![Image](https://github.com/user-attachments/assets/8f4b8e3a-2b28-4594-b5ac-2ce5a1ab11c5)

**Comment by abhip161** [comment]
hey @nihal467  i would like to try to work on this issue

**Comment by AdityaJ2305** [comment]
Hey @abhip161, would it be alright if I took on this issue? I can submit a PR right away.

**Comment by abhip161** [comment]
@AdityaJ2305 I am working on it

**Comment by AdityaJ2305** [comment]
> [@AdityaJ2305](https://github.com/AdityaJ2305) I am working on it

ok , no problem

**Comment by abhip161** [comment]
Hey @nihal467  sir,
I've completed the task and attached a screenshot below for your review:
  ![Image](https://github.com/user-attachments/assets/61f2b020-2183-4cd1-ba79-1876be319cd7)

Could you please check and let me know if everything looks good? If it's fine, I'll proceed with creating a PR

Thank you!

**Comment by nihal467** [comment]
@abhip161 can you share which users type was used, when you took the screenshot, because I am confused why the delete button is grayed out now ?

**Comment by abhip161** [comment]
Hey @nihal467 I was logged in by doctordev  username it shows only admin can delete 
If I logged in by admin delete button will not graded

**Comment by nihal467** [comment]
@abhip161 it looks good, can you push the PR
