### ISSUE TITLE
Clear Button of Spoke Facility Dropdown in facility details update page is not working

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8815]
**Describe the bug**

When we try to use the clear button in the spoke facility dropdown in the update facility page, its not clearing the data

**To Reproduce**

1. Click on view facility button on any card
2. click on manage facility and select update details
3. select a spoke facility in the dropdown and try to use the clear button
4. see the error

**Expected behavior**

- [ ] the clear button should clear the already selected data in the input field
- [ ] align the dropdown arrow to be in the center rather than the top of the input field

**Screenshots**

![Image](https://github.com/user-attachments/assets/6fcdb2a3-4c4d-4588-a334-304a416acfa7)

![Image](https://github.com/user-attachments/assets/e2f1494b-fbbb-4321-a134-2d502fb1c3b6)

**Comment by NitinPSingh** [comment]
please assign me @nihal467
