### ISSUE TITLE
Modify Active Profile Dropdown Behavior to Redirect to Other Pages

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8816]
Follow-up : https://github.com/ohcnetwork/care_fe/pull/8789#issuecomment-2416409351

Bug Description

When the profile dropdown is open, clicking on other navigation buttons doesn't redirect to the intended page immediately. For example, if the profile dropdown is active and the user clicks on the "Assets" tab in the sidebar navigation, the first click closes the dropdown, but the user has to click again to navigate to the Assets page.

Steps to Reproduce:

1. Click on the profile name to open the dropdown menu.
2. Try clicking on the "Assets" tab in the sidebar.
3. Notice that the first click only closes the dropdown without navigating to the Assets page.

Expected Behavior 

- [ ] The profile dropdown should automatically close when the user clicks on any other button, and the intended action (e.g., navigation to a different page) should happen immediately on the first click.

**Screenshots**

![Image](https://github.com/user-attachments/assets/9b430e7a-7065-4922-b0f1-c58e552267a9)

**Comment by JavidSumra** [comment]
Hey @nihal467 Sir I would like to work on this issue
