### ISSUE TITLE
Local Body required but unavailable for some selected districts

### ISSUE THREAD

**Issue by AdityaJ2305** [coronasafe/care_fe#8819]
**Describe the bug**
While creating a Patient, many districts lack **local body**  options, but the field is still required, blocking form submission. This affects multiple districts across states, making it impossible to proceed without selecting an unavailable option.

**To Reproduce**

1. Navigate to the Patient Tab.
2.	Click on Add Patient Details.
3.	Choose any option under the Facility field.
4.	Scroll to the State field.
5.	Select a State and a District where no local body options are available.
6.	Attempt to submit the form.
7.	Observe the error.

**Expected behavior**
The form should allow submission when no local body options are available for the selected district, but require it for districts where options are available .

**Screenshots**

![Image](https://github.com/user-attachments/assets/a1940a8b-ec99-48ec-8a65-a7e2efbcd9ac)

**Additional context**
Hey @nihal @rithviknishad, could you please confirm if this is a valid issue? If so, I’d be happy to work on it.

**Comment by aparnacoronasafe** [comment]
@AdityaJ2305 you have found a valid bug. 

We already have local bodies list for all states/districts. They may not be enabled in all instances. 

The solution should be to enable the list for all states. 

The field will always stay mandatory

**Comment by AdityaJ2305** [comment]
@aparnacoronasafe, it seems this issue is a backend problem. The frontend is functioning correctly, so we can close this issue here.
