### ISSUE TITLE
Dropdown Menu Items (Sign-out / Profile) Not Responding to Click Events

### ISSUE THREAD

**Issue by abhip161** [coronasafe/care_fe#8820]
**Describe the bug**
The dropdown menu items for "Profile" and "Sign Out" are not functioning as expected. Clicking on these items does not navigate to the profile page or trigger the sign-out function.

**To Reproduce**

1. Click on "Profile":
    Select the "Profile" option from the dropdown menu.
    Expected Result: The user should be redirected to /user/profile. 

    ![Image](https://github.com/user-attachments/assets/058767f0-dbf8-40b1-a5c3-ca62439f5a25)

   Actual Result: No action is performed; the dropdown menu does not navigate
2  Click on "Sign Out":
    Select the "Sign Out" option from the dropdown menu.
    Expected Result: The sign-out function should execute and log the user out.
   Actual Result: No action is performed; the dropdown menu does not trigger the sign-out

**Screenshots**
https://github.com/user-attachments/assets/20c1a877-3303-4ab3-948a-bb1c45809921

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]
- Version [latest version]
-

**Comment by abhip161** [comment]
Hey @nihal467 @bodhish  
Could you please confirm if the dropdown menu items are functioning correctly for you? I'm experiencing an issue where clicking on the "Profile" and "Sign Out" options doesn't trigger the expected actions.

Thanks!

**Comment by i0am0arunava** [comment]
@nihal467 @bodhish ,I'd like to contribute to this issue. Could you please assign this to me?

**Comment by nihal467** [comment]
@abhip161 The dropdowns are working on my end, and the bug is not replicable. can you share your browser details, version , name , etc...

**Comment by abhip161** [comment]
Hey @nihal467 , here are my browser details:
![Image](https://github.com/user-attachments/assets/296fbcef-b607-4095-b5e8-f7d1f049e7e2)
The issue works fine on my phone, but it’s not functioning in desktop mode.

**Comment by shauryag2002** [comment]
Also in my brave browser, It is not working.
here are my browser details:
![Image](https://github.com/user-attachments/assets/05bd456f-0ed4-4463-a04e-abba33f1d032)

**Comment by sairiteshdomakuntla** [comment]
hello @abhip161 , i think i can try to work on this issue, can you please assign this to me?

**Comment by rithviknishad** [comment]
@sairiteshdomakuntla any updates on this?

**Comment by VAIBHAVSING** [comment]
hey can you assign me

**Comment by kihan2518B** [comment]
I would like to work on this issue

**Comment by kihan2518B** [comment]
This bug is not replicating in my browser

**Comment by JavidSumra** [comment]
Hey Team issue occurs when we try to click on `Profile or Signout` with Laptop Touch Panel(TrackPad)

**Comment by nithish1018** [comment]
@rithviknishad @Jacobjeevan  I was able to recreate this issue, please assign this to me

**Comment by rithviknishad** [comment]
@nithish1018 have you found the root cause (why it may not be working with trackpad) and a solution to it?

**Comment by nithish1018** [comment]
@rithviknishad Yes, I was able to fix it in my local server by making few minor changes
