### ISSUE TITLE
Profile Page: Language Change Not Reflecting in Text

### ISSUE THREAD

**Issue by JavidSumra** [coronasafe/care_fe#8828]
## **Bug Description**  
When I change the language from English to another language, the text on the profile/edit page does not update accordingly.

### **Steps to Reproduce**  
1. Go to the "user/profile" page.
2. Click on "Edit Profile."
3. Scroll down to "Language Selection" and change the language to something other than English.

### **Expected Behavior**  
The text on the page should change to the selected language.

### **Screenshots**  
![Image](https://github.com/user-attachments/assets/2224d39e-df65-48a6-86c0-e63f3effad80)

### **Desktop**  
- **OS:** Windows  
- **Browser:** Chrome  
- **Version:** 130.0.6723.59

**Comment by JavidSumra** [comment]
Hi Team, I would like to work on this issue. Could you please assign it to me?

**Comment by khavinshankar** [comment]
@JavidSumra I was not able to replicate this issue, when I select a language from the dropdown, I can see things changing. @nihal467 can you check this issue and assign @JavidSumra if it persists?

**Comment by JavidSumra** [comment]
> [@JavidSumra](https://github.com/JavidSumra) I was not able to replicate this issue, when I select a language from the dropdown, I can see things changing. [@nihal467](https://github.com/nihal467) can you check this issue and assign [@JavidSumra](https://github.com/JavidSumra) if it persists?

I've verified that the issue also persists on the deployed link. I’d like to discuss some other issue as well can we jump on a huddle over Slack? @khavinshankar

**Comment by rithviknishad** [comment]
Closing as not reproducible.

Translations for languages other than english are handled by Crowdin and need not be added by us.
