### ISSUE TITLE
Comment Overflow Issue in Shifting Section

### ISSUE THREAD

**Issue by kihan2518B** [coronasafe/care_fe#8840]
**Describe the bug**
 In the comments section of the shifting section, when a word or sentence is entered without spaces, the text overflows beyond the boundaries of the parent div and stretches across the screen width, breaking the layout. This creates a poor visual appearance and disrupts the user interface.

**To Reproduce**

1. Go to '/shifting/board'
2. Click on 'All details' of any card
3. In the comments section, type a long word or sentence without any spaces and post it.

**Expected behavior**
The text should wrap or be truncated within the boundaries of the parent div, maintaining the proper layout.

**Screenshots**
![Image](https://github.com/user-attachments/assets/b14f469c-4432-47de-8c41-e6941049b42d)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Comment by bodhish** [comment]
addressed in https://github.com/ohcnetwork/care_fe/pull/8722
