### ISSUE TITLE
Export Button Overflows Beyond Page on '/facility' View Patients Section

### ISSUE THREAD

**Issue by JavidSumra** [coronasafe/care_fe#8843]
**Bug Description**  
The "Export" button overflows beyond the page boundaries on the '/facility' page when viewing patients.

**Steps to Reproduce**  
1. Navigate to the '/facility' page.
2. Click on 'View Patients' for any hospital.
3. Scroll horizontally.
4. Observe that the "Export" button overflows from the page.

**Expected Behavior**  
The "Export" button should remain within the page boundaries and be fully visible.

**Screenshots**  
![Image](https://github.com/user-attachments/assets/7777f723-c960-40a7-bb21-ba752e575ac8)

**Environment Details**  
- **OS**: Windows
- **Browser**: Chrome
- **Version**: 130.0.6723.59

**Comment by nithish1018** [comment]
I'd like to work on this,
Please assign this to me.

**Comment by sairiteshdomakuntla** [comment]
hello @JavidSumra , i would like to work on this, can you please assign this to me?

**Comment by JavidSumra** [comment]
> hello [@JavidSumra](https://github.com/JavidSumra) , i would like to work on this, can you please assign this to me?

Hey @sairiteshdomakuntla, I'm unable to assign you this issue since I'm not a repo maintainer. I apologies!

**Comment by JavidSumra** [comment]
Hey team, is the following UI okay?
![Image](https://github.com/user-attachments/assets/d7d1a172-cb16-4de4-bbb6-a79ec309c656)
![Image](https://github.com/user-attachments/assets/ddd576f1-b2eb-4549-88e1-d3d5e45c0727)

**Comment by JavidSumra** [comment]
Hey team, is the following UI okay?
![Image](https://github.com/user-attachments/assets/251ab374-a0b6-48f5-9aa4-bcf91499cf25)
![Image](https://github.com/user-attachments/assets/90b0b755-cd21-4518-bd60-fc894e164337)

**Comment by bodhish** [comment]
@JavidSumra not a fan of it, I would trim a few words in the UX for example. 

- Add Patient Details -> Add Patient 
- Advanced Filters -> Filters 

Reduce x-padding for buttons; 

cc @gigincg
