### ISSUE TITLE
Remove the camera name and details pop-up from the camera feed component on the asset configuration page.

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8844]
**Describe the bug**

When we are on the asset configuration page, the camera feed component shows the camera name and details pop-up, which is not relevant to the page.

**To Reproduce**

1. Go to any camera asset in the assets page
2. Click on configuration
3. See error

**Expected behavior**

Remove the camera name and details pop-up from the camera feed component on the asset configuration page.

note: This behavior change should only affect the asset configuration page.

**Screenshots**

![Image](https://github.com/user-attachments/assets/c4465bd3-4bdc-4d4b-9a7c-f5c15eaa40fa)

**Comment by Rishith25** [comment]
@nihal467  Can I work on this?
