### ISSUE TITLE
Create consultation API is throwing 500 when HF ID is missing for the facility

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8848]
**Describe the bug**

When the HF ID is missing for a facility, and we attempt to create a consultation by linking the ABHA ID to the patient, a 500 error is thrown  by the backend, and The user remains on the form, but in the background, the consultation has already been created.

**To Reproduce**

1. Go to any facility without hf id
2. create a patient and new consultation with Abha linked 
3. See error

**Expected behavior**

- [ ] disable the link abha button in patient registration as well as in the consultation page if the HF id's are missing (Temporary Solution)

**Screenshots**

**Comment by therurouni** [comment]
Hii @nihal467 .I would like to work on this issue.Can u assign me this issue?
