### ISSUE TITLE
First added diagnosis is not deleting in create consultation form

### ISSUE THREAD

**Issue by Mahendar0701** [coronasafe/care_fe#8849]
**Describe the bug**
First added diagnosis is not deleting in create consultation form

**To Reproduce**

1. Go to 'Patients' and select a patient who doesn't have a consultation filed .
2. Click on 'Create consultation'.
3. Scroll down to 'Diagnosis Field' and add diagnosis.
4. Try to remove first added diagnosis.
5. See error

**Expected behavior**
The first added diagnosis should be deleted on clicking the remove button.

**Screenrecording**
https://github.com/user-attachments/assets/c19baa12-33db-4fe1-81c4-f7fd24c307ff

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mahendar0701** [comment]
@rithviknishad @nihal467 I want to work on this issue.

**Comment by rithviknishad** [comment]
Nice fine @Mahendar0701
