### ISSUE TITLE
Allow Decimal places to ABG parameters (Pco2 , Po2 and pH)

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8858]
**Describe the bug**
Need to allow two decimal places to Pco2 and Po2 parameters on ABG, currently on the input field its showing as decimal places are allowed but when you enter values with decimals and submit, its throwing the error saying decimal values are not allowed.
usually these two above mentioned parameters are with two decimal places. But for pH  it should be three decimal places.

![Image](https://github.com/user-attachments/assets/49ae0f6f-588e-4e44-b572-98f81461191d)

**To Reproduce**

1. Go to patient card
2. Click on log update and select round type as Detailed Update
3. select Arterial Blood  Gas analysis parameter
4. update the values to Pco2 , Po2 and pH fields with decimal places and submit
5. see the error

**Expected behavior**

- [ ] Allow Pco2 and Po2 fields to accept two decimal places. 
eg:) Pco2 : 29.81 

![Image](https://github.com/user-attachments/assets/907b7396-e668-4f93-862e-6846f65d3f72)

- [ ] Allow pH field to accept values with three decimal places
eg:) pH: 7.499

![Image](https://github.com/user-attachments/assets/439895fd-f971-43f0-ab6d-d7d3e1664eaa)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abhip161** [comment]
Hey @samholics @nihal467  i would like to  work on this issue

**Comment by VAIBHAVSING** [comment]
this response get from backend url patch request 
response :{"po2":["A valid integer is required."]}
please raise issue on care repo for same .I please assign me this issue for frontend
 ![Image](https://github.com/user-attachments/assets/613e64f6-cabf-4894-95d4-f464b961e251)

**Comment by bodhish** [comment]
@abhip161 I think you can combine #8859 also into a single PR;

**Comment by bodhish** [comment]
@abhip161 whats the status of this issue? 

@Jacobjeevan can you check and do the needful

**Comment by abhip161** [comment]
Hi @Jacobjeevan , I'm currently working on issue #8859. Once completed, I'll submit a single PR that covers both this issue
