### ISSUE TITLE
Add another unit of measure to Pco2 and Po2 fields on ABG analysis

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8859]
**Is your feature request related to a problem? Please describe.**
Currently there is only one unit of measurement is available to the fields "Pco2 and Po2" on Arterial Blood Gas analysis parameter on Detailed round type (mmHg). But there is another unit is also commonly used for the same, ie "kPa" . 
![Image](https://github.com/user-attachments/assets/3f85923f-7956-4d49-b003-a0648d0484b8)
![Image](https://github.com/user-attachments/assets/127cd17c-1b3d-4696-9d5d-d55933744089)

- [ ]  Add the other unit  "kPa" to the fields
- [ ] Allow switch between "mmHg to kPa" units  ( make it switchable option like Fahrenheit to Celsius on Temperature field)  this makes the users to select the unit of measure which they are using on their ABG results.
- [ ] The Normal Range for Pco2 and po2 are;
     pCO2: 5.1 to 5.6 kPa
     pO2: 10.5 to 13.5 kPa

- [ ] Min and Maximum unit range should be 0 - 20 kPa 

- [ ]  Allow two decimal places for the same (refer the related issue for more on this point https://github.com/ohcnetwork/care_fe/issues/8858)

**Comment by abhip161** [comment]
Hey @rithviknishad   i would love to work on this issue could you please assign to me

**Comment by abhip161** [comment]
hey @rithviknishad can you help me in  conversion logic
 ![Image](https://github.com/user-attachments/assets/5b2ff64c-3ed6-4f4c-9261-98fb079b4faa)

**Comment by bodhish** [comment]
@abhip161 whats the status of this issue?

**Comment by sanjayh-2022** [comment]
@Jacobjeevan  Sir if this issue is still open can I work on this issue
