### ISSUE TITLE
Active and Archive Tabs are not properly visible in Shifting Page

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#8863]
**Describe the bug**
When we open the Shifting Page in Desktop, the Tabs: **Active** & **Archive** are not properly visible, making it difficult for the user to switch between them.

**To Reproduce**
1. Go to Facility Page
2. Check Active and Archive Tabs
3. On Desktop view, we can't seamlessly switch between them

**Expected behavior**
The **Active** & **Archive tabs** should appear properly for easy switch between them. 
This can be fixed by adjusting the other elements in the same row

**Screenshots**
This is how it looks on Desktop View ( 100%):

![Image](https://github.com/user-attachments/assets/23480d97-8d2e-478a-9b7f-4145380641e5)

This is how it looks in mobile view:

![Image](https://github.com/user-attachments/assets/a009b2b9-7025-4f40-a81e-9a216d232fbc)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: Latest

**Comment by nithish1018** [comment]
I'd like to work on this issue, please assign this to me

**Comment by bodhish** [comment]
@nithish1018 which screen size are you finding the UI failing?

**Comment by nithish1018** [comment]
> [@nithish1018](https://github.com/nithish1018) which screen size are you finding the UI failing?

It's a 14-inch screen with 1080p resolution

**Comment by bodhish** [comment]
Can you share a screen recording?

**Comment by nithish1018** [comment]
> Can you share a screen recording?

Here's the screen recording:

https://github.com/user-attachments/assets/2e2bd4a6-88aa-405b-a4e8-e3901b07a29a

**Comment by bodhish** [comment]
Is the app running on full screen?

**Comment by nithish1018** [comment]
> Is the app running on full screen?

Yes, it was running on full screen
