### ISSUE TITLE
Add Spo2 on vitals section of Community Nurse log update

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8865]
**Is your feature request related to a problem? Please describe.**
Add Spo2 vital field on the community nurses log update form. Nurses from the field were forced to file another brief update because Spo2 was available there. 

Add the Spo2 field here,
![Image](https://github.com/user-attachments/assets/77ca4b1c-3a96-40fd-8c50-e586d6e96f82)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by noufalrahim** [comment]
I would like to take up the issue.. @rithviknishad can u assign this to me..

**Comment by bodhish** [comment]
@samholics please do mention the source of these issues from next time. 

Example 

Reported by Athul Dr via Aparna

**Comment by noufalrahim** [comment]
@samholics can u provide the method to reproduce the issue..?

**Comment by samholics** [comment]
> [@samholics](https://github.com/samholics) please do mention the source of these issues from next time.
> 
> Example
> 
> Reported by Athul Dr via Aparna

sure, this was reported by Nithin from Arike

**Comment by samholics** [comment]
> [@samholics](https://github.com/samholics) can u provide the method to reproduce the issue..?
 
steps to reproduce
- Login on CARE 
- Open a patient card
- Click on the Logupdate button from the patient dashboard
- Select the Round type as "Community Nurse log  update"
- Scroll down to vitals area
