### ISSUE TITLE
Add Improvement to symptom field on Mobile devices.

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#8867]
**Describe the bug**

- [ ] Calendar is clipping out and auto-zooming when you click on calendar option on the Onset Date field.
- [ ] when Going back from after selecting a symptom from the dropdown, users get confused for closing the dropdown and tend to select other symptoms accidentally. this makes entering symptoms on mobile devices difficult for field nurses.  
It's better to add the auto-collapse the dropdown after selecting one symptom. this makes users file symptoms easier and restrict from filing all the symptoms on the same Onset date. 

**To Reproduce**

1. Go to a patient file on mobile devices
2. Click on log update and go to symptoms field
https://github.com/user-attachments/assets/751a3a6e-0202-4422-82a8-224a46b4eef6

**Expected behavior**

- [ ] Calender should be pop-up on the middle part of the screen 
- [ ] symptoms dropdown should collapse after selecting one symptom

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abhip161** [comment]
hey @nihal467 I would like to work on this issue.Can u assign me this issue?

**Comment by Jacobjeevan** [comment]
(1) Is an easy fix.
(2) Collapse on multi-select isn't usual/expected behavior; we could make it single select, however that would require a bit more rework. We are going to redesign symptoms anyways, so could do it then.

**Comment by ayushpatil2122** [comment]
can anybody tell To Reproduce the same i am not able to do that please

**Comment by AdityaJ2305** [comment]
Please refer to this comment before reaching out regarding the assigned issue: [comment link](https://github.com/ohcnetwork/care_fe/pull/9300#issuecomment-2519397013). 
Thank you! 😊

**Comment by rithviknishad** [comment]
Feel free to re-open the issue based on new architecture @samholics
