### ISSUE TITLE
Show user avatar in User Autocomplete and User list page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8869]
**Is your feature request related to a problem? Please describe.**
Currently the [`UserAutocompleteFormField`](https://github.com/ohcnetwork/care_fe/blob/develop/src/Components/Common/UserAutocompleteFormField.tsx#L82) and the Users list page does not show the avatar of the user.

**Describe the solution you'd like**
- [ ] Show the avatar of the user in each of the options for [`UserAutocompleteFormField`](https://github.com/ohcnetwork/care_fe/blob/develop/src/Components/Common/UserAutocompleteFormField.tsx#L82)
- [x] Show the avatar of the users in the Users list page ([here](https://github.com/ohcnetwork/care_fe/blob/develop/src/Components/Users/ManageUsers.tsx#L192))

**Additional context**
![Image](https://github.com/user-attachments/assets/916b10d6-b628-4adc-b751-82db841b4642)

![Image](https://github.com/user-attachments/assets/1d18ddee-7489-48e6-8108-d2abb175e6c1)

**Comment by noufalrahim** [comment]
@rithviknishad can u assign this to me..

**Comment by noufalrahim** [comment]
@rithviknishad is the avatar there in the api?

**Comment by rithviknishad** [comment]
Yes as `read_profile_picture_url`

**Comment by khavinshankar** [comment]
Make sure avatar or image is added only to the user autocomplete
