### ISSUE TITLE
Infinite loading issue while updating cover photo of a Facility

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#8877]
**Describe the bug**
When attempting to edit the cover image of a facility, if an image with an improper format is selected, the save button enters an indefinite "an uploading" state. The issue persists until the modal is reopened.

**To Reproduce**

1. Go to Facilty Tab
2. Select a Facilty
3. Click on **Upload** icon
4. Try uploading an image which is not in 1:1 format
5. Click Save and observe that it goes into loading state forever even after displaying the error

**Expected behavior**
If an upload is failed, the **save** button should regain it's regular state 

**Screen Recording**

https://github.com/user-attachments/assets/dee0b83e-e620-460d-9528-dc278827c22f

**Desktop (please complete the following information):**

- OS: Windows
- Browser : Chrome
- Version: Latest

**Comment by nithish1018** [comment]
I want to work on this issue

**Comment by gigincg** [comment]
@nithish1018 Seems like a quickfix, assigning it to you
