### ISSUE TITLE
Refactor user list and user management pages

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#8878]
> [!NOTE] 
> Create wireframes for the new user list and details page before asking for the issue to be assigned

Current user list page:
![Image](https://github.com/user-attachments/assets/ef5c54fa-e5d4-460e-b810-447d7e83d626)

Required changes:

- [ ] Extract user cards as a separate component
- [ ] Clicking the user card should bring up the user detail page
- [ ] Move the action buttons like delete, manage linked facilities/skills, set working hours to the user detail page
- [ ] Add user avatars to user cards, similar to user card from personal details page of the logged-in user
![Image](https://github.com/user-attachments/assets/c4d9b5fd-99b8-4745-96aa-6b99df244fb6)

- Fix the alignment of the search bar and action buttons in desktop mode

New User detail page:

TODO: add wireframes

Required changes:

- [ ] Convert linked facility/skills management to a dropdown within the details page
![Image](https://github.com/user-attachments/assets/1b2d2f88-4ebc-4a7e-89cd-00083489de49)

**Comment by Rishith25** [comment]
@sainak Can I work on this?

**Comment by sainak** [comment]
Create wireframes for the new user list and details page before asking for the issue to be assigned

**Comment by Jacobjeevan** [comment]
@sainak I was thinking something like this 🤔 

With the cards being clickable, but we should probably add a "view user" button similar to what we have for facilities.

![Image](https://github.com/user-attachments/assets/7cd30e85-d080-4c40-8134-3eb6843c7ffc)

![Image](https://github.com/user-attachments/assets/33084007-7514-48dc-99b9-a3275bc6af8a)

**Comment by sainak** [comment]
@Jacobjeevan that looks good
some suggestions:
- we should move delete inside the details page as well, it should not be a quick action
- the online indicator after the name looks redundant 
- the details page is missing username chip
- share sketches for list view in mobile as well

**Comment by Jacobjeevan** [comment]
@sainak  I was thinking of using clickable pills for the facilities and skills, though it might not look good when there are lot of linked facilities, like with district admin.

![Image](https://github.com/user-attachments/assets/bf2ae578-2c9f-46b9-9dd7-fc552b9b358e)

Multi-select for the dropdowns

![Image](https://github.com/user-attachments/assets/0dd10d34-3479-45bc-b63f-6b8a15195efc)

Clicking on the pill would trigger a popup with manage options; open additional dialog only when replacing existing home facility, like what we have now.

![Image](https://github.com/user-attachments/assets/31db6855-e0c3-49aa-bfde-cb15ccc0536b)

**Comment by vinutv** [comment]
@Jacobjeevan Here is the design for the users page and user details page. Let me know your thoughts.
https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=1285-2299
cc @bodhish
