### ISSUE TITLE
Add Improvement to Reason Field in Resource details page

### ISSUE THREAD

**Issue by Keerthilochankumar** [coronasafe/care_fe#8880]
Describe the bug:
          On the current Resource details page the Reason data is overflowing out of the window
        ![Image](https://github.com/user-attachments/assets/fbe43620-2860-437e-bd83-645fb6814392)

To Reproduce

1. go to the Resource Tab
2. Select a Resource and click on all details

Expected behavior:
  The data inside the Reason should be within the window screen

Desktop:

-  OS: Windows

-  Browser: Chrome

-  Version: Latest

**Comment by Keerthilochankumar** [comment]
I want to work on this issue

**Comment by rithviknishad** [comment]
![Image](https://github.com/user-attachments/assets/5c0bc63a-cf7d-4fbb-be08-0b19f2038cab)

**Comment by Keerthilochankumar** [comment]
@rithviknishad  
           if there are any spaces in the text it is working fine else it is overflowing out of the window

**Comment by rithviknishad** [comment]
when testing things like these, test with the largest english dictionary word only. Users wouldn't input texts like what's shown in the first screenshot.

However the UI is still breaking in mobile view with largest english word, hence assigned.
