### ISSUE TITLE
Content overflows from the card in /users

### ISSUE THREAD

**Issue by SwanandBhuskute** [coronasafe/care_fe#8883]
When I was working on issue #7307 , I found this bug
When I added an extra user with my login, and visited /users with my login , I saw this small css bug where the name is overflowing

**To Reproduce**

1. Go to '/users'
2. Click on 2nd pagination of dev_districtadmin login (you can find it in any other login too)
3. See error (username overflows)

**Expected behavior**
Not to overflow outside the defined card

**Screenshots**
![Image](https://github.com/user-attachments/assets/4266c4fb-e636-42ef-ac5a-01e939d93728)
![Image](https://github.com/user-attachments/assets/68981e99-7cb3-45dd-94e4-590a167710e8)

**Desktop (please complete the following information):**

- OS: windows
- Browser : chrome
- Version - latest

**Additional context**
I would like to take up this if approved

**Comment by bodhish** [comment]
Add it as another item on the current PR that you are working on, let’s not have another issue to track the same

**Comment by SwanandBhuskute** [comment]
I have raised the PR for issue#7307 and issue#8883
https://github.com/ohcnetwork/care_fe/pull/8940
- now, username and password check will display like this before entering text in the field and then normal green-red behaviour will be done (7307)
- Username was overflowing from the card, so fixed it with simple css (8883)
