### ISSUE TITLE
Fix: referral letter responsiveness

### ISSUE THREAD

**Issue by modamaan** [coronasafe/care_fe#8884]
**Describe the bug**
The referral letter has a responsive issue and looks messy

**To Reproduce**

1. Go to 'shifting'
2. Click on 'all details button on any card'
3. Click on 'referral button'

**Expected behavior**
The referral letter should be responsive and clean

**Screenshots**
![Image](https://github.com/user-attachments/assets/79a4d8a5-b615-491b-99a3-a36770f3d90f)

![Image](https://github.com/user-attachments/assets/5b2b42d9-861f-4cc7-8f35-5373b2233764)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [129.0.6668.101]

**Comment by modamaan** [comment]
@gigincg i would like to work on this, can you assign it to me

**Comment by rithviknishad** [comment]
@modamaan Let's wrap the contents of this page in [`PrintPreview`](https://github.com/ohcnetwork/care_fe/blob/develop/src/CAREUI/misc/PrintPreview.tsx) component to ensure proper responsiveness for printable contents, like how it's done for all other printable contents in Care.

**Comment by bodhish** [comment]
Also while we are at it, cleaning up the preview to look better should be considered.
