### ISSUE TITLE
Add Skip button while creating the patient without creating consulation

### ISSUE THREAD

**Issue by AnveshNalimela** [coronasafe/care_fe#8900]
To improve the user experience when creating patients, you can add a "Skip" button that allows users to proceed without creating a consultation. This way, users can avoid confusion and avoid having to click "Cancel," which might imply abandoning the entire patient creation process.

![Image](https://github.com/user-attachments/assets/9f16285f-5f5d-4bd1-b865-b8c1229320f1)

and I would like to improve the Linked facilties and linked skills 

![Image](https://github.com/user-attachments/assets/d1fdd3b7-3cf0-400f-b308-2c6f863faf76)
 
![Image](https://github.com/user-attachments/assets/18e1472d-e58b-44fb-9968-af17247d8ee9)

**Comment by rithviknishad** [comment]
We shouldn't be encouraging users to skip creating a consultation after registration
