### ISSUE TITLE
Display the Linked Camera feed on the patient consultation page even when no preset is created for the selected bed

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8901]
**Describe the bug**

Currently, even though a camera is linked to a bed via the asset configuration page, the patient consultation page incorrectly displays that no asset is linked to the bed.

Note: he current validation on the consultation page checks whether the camera linked to the bed has a preset. If no preset exists, the camera feed is not shown. This logic needs to be updated because, with recent changes in the camera-to-bed relation, a camera can now be linked to a bed first, with presets being created later.

**To Reproduce**

1. Go to the asset page, open a camera asset, and link it to a bed without creating a preset.
2. Navigate to the patient tab, open any patient card, and link the patient to the bed.
3. Click on the feed button in the navigation bar of the consultation page.
4. Observe the error.

**Expected behavior**

- [ ] The linked camera should be displayed on the patient consultation page, even if a preset has not yet been created for the bed.

**Screenshots**

![Image](https://github.com/user-attachments/assets/164d4cdf-ae99-4e1c-9cf8-413e3ba039a2)

**Comment by Mahendar0701** [comment]
@nihal467 i want to work on this

**Comment by nihal467** [comment]
there is no relevance of showing a camera feed in consultation page, if there is no preset
