### ISSUE TITLE
Add a clear and cancel button in the preset pop-up of asset camera configuration page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8902]
**Describe the bug**

When trying to clear or close the pop-up on the camera asset configuration page, there is no clear or cancel option available, causing confusion for users.

**To Reproduce**

1. Go to asset tab
2. Click on any camera asset card
3. click on configuration and try to create a preset

**Expected behavior**

- [ ] Add a Cancel button adjacent to the Submit button for closing the pop-up.
- [ ] Add a Clear button within the preset input field to clear the input value.

Note: Ensure these changes align with the existing design language for consistency.

**Screenshots**

![Image](https://github.com/user-attachments/assets/a58f5be3-3d97-4bab-af8f-bed47b69651f)

**Comment by Rishith25** [comment]
@nihal467 Can I work on this? Please assign it me.

**Comment by JavidSumra** [comment]
Hey Nihal can you please assign it to me?

**Comment by Rishith25** [comment]
Hi @nihal467 I logged in as a district admin and attempted to add a preset, but I'm encountering an issue where it shows "unable to get position." Could you please guide me on how to add a preset and open the popup for the camera asset and how to reproduce the behavior you’re demonstrating.

![Image](https://github.com/user-attachments/assets/f5b8d8ac-35da-4d0e-bf7b-ccfd4406dad3)

**Comment by nihal467** [comment]
you need to configure the camera first for that, to get the camera configuration detail, look for asset named dev camera , use the same configuration for your asset

**Comment by Rishith25** [comment]
@nihal467  I logged in as district admin. I think the dev camera is deleted hence i can not find it. Can you share the camera configuration details.

![Image](https://github.com/user-attachments/assets/78220637-1de0-4d4a-a930-4a787628644e)
