### ISSUE TITLE
Support for preventing submit button when form content is not changed

### ISSUE THREAD

**Issue by kihan2518B** [coronasafe/care_fe#8918]
**Describe the bug**
When attempting to update bed or staff details in the facilities section, clicking the "Update" button sends a request to the backend even if no changes have been made to the form. This results in unnecessary API calls, potentially leading to performance issues or confusion in tracking actual updates.

**To Reproduce**

1. Go to the facilities section.
2. Select a bed or staff detail to edit.
3. Without making any changes, click on the "Update" button.
4. See a network request to update the details

**Expected behavior**
 No request should be sent if no fields are updated, and the "Update" button should remain inactive.

**Screenshots**
![Image](https://github.com/user-attachments/assets/273f5b9e-b85e-4859-92f5-ab4ad6d8da20)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Microsoft Edge

**Comment by kihan2518B** [comment]
I have got a solution for that 
solution:
Initial State Tracking:

Capture the initial values of the form fields when the form is first loaded or reset.
On-Change Comparison:

Each time a field is changed, compare the current value with the corresponding initial value for that specific field.
Field-by-Field Tracking:

Maintain a flag (like hasFormChanged) that tracks if any field has been modified compared to its initial value.
Reset Logic:

If a field is changed back to its initial value, reset its modified state, ensuring hasFormChanged becomes false if all fields return to their original values.
Efficient Comparison:

Compare individual fields rather than the entire form object (avoiding JSON.stringify), resulting in better performance and accuracy.
Edge Case Handling:

Ensure that if a field is changed but reverted back to the original value, it doesn't falsely indicate that the form has changed.

Can anyone assign me this issue?

**Comment by rithviknishad** [comment]
Let's have this feature in the [`Form`](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Form/Form.tsx#L28) component itself instead.

This way all usages of the `Form` component would get this feature enabled in one go and not just the form specified in the issue.

We could upgrade the `Form` component to have a `isDirty` state. And in the `onChange` we could set `isDirty` to true. And the submit button managed by the `Form` component could be disabled based on this `isDirty` state.

**Comment by kihan2518B** [comment]
yaa sure that would also work.
@rithviknishad can you assign this issue to me

**Comment by kihan2518B** [comment]
I had made necessary changes in the form component.
but this is applying to only patient update form as we have use [Form](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Form/Form.tsx#L28) only in [PatientRegister](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Patient/PatientRegister.tsx#L936) component.

![Image](https://github.com/user-attachments/assets/264a9efd-18c9-4bc3-94cd-d444a7b545bc)

For other components like [BedCapacity](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Facility/BedCapacity.tsx),[StaffCapacity](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Facility/StaffCapacity.tsx), etc we are not using [Form](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Form/Form.tsx#L28) component.

So for that I had a solution by manually adding isDirty state to all component.

solution:
![Image](https://github.com/user-attachments/assets/1c929402-6428-4ac7-847e-65a42162284a)

**Comment by rithviknishad** [comment]
let's switch those to use the Form component instead

**Comment by rithviknishad** [comment]
@kihan2518B can we also do the same for what's mentioned in #8982?

**Comment by kihan2518B** [comment]
Yaa sure I will make those component use the form component so that the issues are solved correspondingly

**Comment by nihal467** [comment]
Closing this issue, as the entire section of staff and bed capacity has been removed from the CARE platform
