### ISSUE TITLE
Replace Hardcoded cy.wait() with cy.intercept in the cypress files

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8925]
**Describe the bug**

Currently there are multiple places in the cypress file, we use the hardcoded cy.wait(), it's creating a lot of flaky test across the test

**Expected behavior**

- [ ] Replace the cywait() with cy.intercept (API request) or dynamic wait to ensure that flaky test are not occured

**Screenshots**

![Image](https://github.com/user-attachments/assets/dad8fda8-26b1-4482-9715-54c0e24cac7e)

**Comment by Rishith25** [comment]
@nihal467  Is this the required solution for the above issue

Example:
Before:
```.js
verifyUploadFilePresence(fileName: string) {
    cy.wait(2000);
    cy.get("#file-div").scrollIntoView();
    cy.verifyContentPresence("#file-div", [fileName]);
  }
```
After:
```.js
verifyUploadFilePresence(fileName: string) {
    // Replace cy.wait(2000) with intercepting the file upload API call
    cy.intercept('POST', '/api/upload-file').as('fileUpload'); 
    cy.wait('@fileUpload'); // Wait for the file upload request to finish
    
    cy.get("#file-div").scrollIntoView(); 
    cy.verifyContentPresence("#file-div", [fileName]);
}
```
If this is correct I would like to work on this
