### ISSUE TITLE
Create a cypress test to request a Sample Test and verify its reflection

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8926]
**Description**

Add a new cypress test for request a sample test and verify its reflection

**General Note**

Follow the Page Object Model (POM) approach. : [reference](https://github.com/ohcnetwork/care_fe/blob/develop/cypress/e2e/patient_spec/PatientLogUpdate.cy.ts)
Refer to commands.ts in the Cypress folder to understand existing reusable components.
Use proper function names for easier code review.
Since there's nothing related to shifting requests is currently present, create a new file named SampleRequest.cy.ts under the sample_test_spec folder.

**Steps to Assign a Sample Request**

- Go to the patient tab
- click on any live patient card
- On the patient consultation page, click on patient details
- click on request sample request
- submit the form.

**Make sure to verify the below things**

- Ensure the normal workflow is functional.
- Edit the request form and verify the modification are reflected properly
- Verify its visible in sample test  dashboard as well as in the patient details page

**Comment by JavidSumra** [comment]
Can you please assign this issue to me

**Comment by JavidSumra** [comment]
Hey @nihal467, can you confirm if my understanding of the test case workflow is correct?

1) Create a new patient  
2) Add a consultation  
3) Submit a sample request  
4) Verify the request is reflected  
5) Update the request form  
6) Confirm the updates are reflected

**Comment by nihal467** [comment]
@JavidSumra you don't need to create a new patient, we already have live patient present in the patient tab, once you load the dummy data,

the detailed steps you should follow will be:

1. Go to the patient tab
2. click on any patient card, with live consultation
3. once the consultation dashboard is open, click on the patient details buttons on the top right corner
4. once the new page (Patient Details Page) is loaded, scroll down to the sample test button and create a sample test request.
5. Upon, successfully submitting the sample test request, verify in the patient details page, under the sample test history section, you are able to view the request you created
6. Now, go to the sample test board, using the sidebar
7. search for your patient name and verify the card is visible
8. click on the sample test details and verify the patient details are properly visible in that page

**Comment by JavidSumra** [comment]
Hey @khavinshankar can you please assign 2 story points for this.
