### ISSUE TITLE
Patient-dashboard ui Layout issue

### ISSUE THREAD

**Issue by JkrishnaD** [coronasafe/care_fe#8927]
Patient-dashboard layout is not perfectly aligned for small and medium screens

1. Go to '/patients page'
2. Click on 'patient card'
3. Now in inspect mode observe the patient-dashboard section

- The margin and padding is not adjusted properly for these 

![Image](https://github.com/user-attachments/assets/0dd66ec7-34b7-49d3-93c7-b361bc10dc8b)
![Image](https://github.com/user-attachments/assets/455c7f2b-319a-4724-9ede-2b2eff8a2d82)

- OS: [iOS]
- Browser [Arc, safari]

**Comment by Mahendar0701** [comment]
Hey @JkrishnaD it was addressed in PR [#8856 ](https://github.com/ohcnetwork/care_fe/pull/8856)

**Comment by JkrishnaD** [comment]
@Mahendar0701  Sry! my bad i have not seen that.
