### ISSUE TITLE
Rewrite the Entire UserCreation.cy.ts file to POM Approach

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8929]
**Describe the bug**

- [ ] the usage of clickElementById(),  TypeElementById(), clearintoelementbyid, verifyelementcontainstext,  custom function doesn't add much value to the respective of reusable functions

**Expected behavior**

- [ ] replace all the custom function usage in the cypress test file  with individual proper re-usable function
- [ ] use all reusable components from commands.ts wherever applicable

Note: 

1. Rewrite the entire test file into the POM approach, with the proper function name
2. for reference check the test file: PatientDoctorConnect.cy.ts

**Screenshots**

![Image](https://github.com/user-attachments/assets/eb73e883-36ef-426c-afb0-dc461c0a9a9d)

**Comment by AnveshNalimela** [comment]
@nihal467 I would like work on this issue 
Would you assign it to me..?
