### ISSUE TITLE
Improper Session Expired Page - Image and Button Misaligned

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#8932]
**Describe the bug**
The contents present in **session-expired** page looks weird and the **Return to Login** button is misaligned

**To Reproduce**

1. Go to /session-expired route
2. You can see that the contents present in this page are not properly aligned.
**Note:** Check this in 100% view of Desktop

**Expected behavior**
The page should look clean, and the **Return to Login** button should be accessible easily

**Screenshots**

This is how it looks now:

![Image](https://github.com/user-attachments/assets/8f1a21e0-d045-4b0b-a867-97053a38f275)

![Image](https://github.com/user-attachments/assets/05e4cc4f-743f-4241-a9a7-9e1eacb6d7b7)

Suggested/Expected look:

![Image](https://github.com/user-attachments/assets/986d5f35-79f3-4f23-a65e-bba1da2da11c)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment]
@rithviknishad I'd like to work on this issue and raise an immediate PR

**Comment by rithviknishad** [comment]
Which screen size this is?

Could you add more specs. on your resolution, system zoom setting and browser zoom setting? Unable to reproduce this in any of the commonly used sizes.

**Comment by nithish1018** [comment]
> Which screen size this is?
> 
> Could you add more specs. on your resolution, system zoom setting and browser zoom setting? Unable to reproduce this in any of the commonly used sizes.

That screenshot is from 14inch 1080p screen, and the browser zoom setting is set to 100%

**Comment by rithviknishad** [comment]
And system zoom setting?

With those configurations, I cannot reproduce this even with 100% and 125% browser zoom settings.

**Comment by nithish1018** [comment]
> And system zoom setting?
> 
> With those configurations, I cannot reproduce this even with 100% and 125% browser zoom settings.

![Image](https://github.com/user-attachments/assets/6db017bd-412f-4821-8a92-8e2d08d2ec9a)

It's set to default/Recommended settings for this resolution
