### ISSUE TITLE
Infinite load issue when trying to add more beds in facility when all bed types are already selected

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#8946]
**Describe the bug**
A modal with infinite loading shows up if we try to add more beds in a facility in which all bed types were already selected

**To Reproduce**

1. Go to '/facility'
2. Click on **View Facility** on any Facility
3. If all bed types are not selected for that facility then try adding them
4. Now again click on **Add More Beds**
5. You can see that a modal with infinite load shows up

**Expected behavior**
We shouldn't allow users to click on **Add More Beds** when all bed types are already fulfilled

**Screen Recording**

https://github.com/user-attachments/assets/eb74d906-e9d4-4446-81db-1dd0225088b7

**Suggested Behavior**

https://github.com/user-attachments/assets/f190f2b7-b04e-4f05-b8f8-c683ceaa34be

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: Latest

**Comment by nithish1018** [comment]
I'd like to work on this issue

**Comment by rithviknishad** [comment]
Would be solved along with #8918
