### ISSUE TITLE
Remove Avatars from Autocomplete Field Options

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#8957]
**Describe the bug**
A recent [PR](https://github.com/ohcnetwork/care_fe/pull/8912) introduced a side effect to the AutoComplete field, adding avatars to every field.
Please restore the AutoComplete component back to it's previous state.

**To Reproduce**
Open any autocomplete field. Go to Log Update for any patient -> Update Respiratory Rate -> See bug

**Screenshots**
![Image](https://github.com/user-attachments/assets/57652e8d-4a60-408a-8eef-522021a52610)

**Comment by AdityaJ2305** [comment]
Hey @shivankacker  Can you assign it to me ?

**Comment by AdityaJ2305** [comment]
Hey @shivankacker, I pushed a PR without waiting to be assigned since it’s a `P1`  issue.
