### ISSUE TITLE
Text Area Not Visible When 'Other Type' is Selected in Sample Test Type

### ISSUE THREAD

**Issue by JavidSumra** [coronasafe/care_fe#8958]
**Bug Description**  
The text area for providing details is not visible when "Other Type" is selected in the Sample Test Type.

**To Reproduce**  
Follow these steps to replicate the issue:

1. Navigate to '/patients'.
2. Click on any live patient with a consultation.
3. Open the Patient Details section.
4. Scroll down and select "Requested Sample Test".
5. In the Sample Test Type dropdown, choose the last option, "Other Type".
6. Observe the error.

**Expected Behavior**  
The text field for additional details should appear upon selecting "Other Type".

**Screenshots**  
![Image](https://github.com/user-attachments/assets/168f0be6-ea30-4db7-b643-e2b839e3d8b7)

**Desktop Information:**  

- **OS:** Windows  
- **Browser:** Chrome  
- **Version:** 130.0.6723.70

**Comment by JavidSumra** [comment]
Can You please assign this issue to me?

**Comment by JavidSumra** [comment]
Hey @rithviknishad can you please assign 3 story points for this.

**Comment by rithviknishad** [comment]
1 is reasonable for this since its a small change. Do checkout other PRs from the [projects board](https://github.com/orgs/ohcnetwork/projects/4/views/19?query=sort%3Aupdated-desc+is%3Aopen) and request for a point relative to efforts compared to other PRs.

Here's an example of a 3 story point PR: https://github.com/ohcnetwork/care_fe/pull/8504

**Comment by JavidSumra** [comment]
Hey @rithviknishad can you please assign 2 story points.
Relevant PR #[8809](https://github.com/ohcnetwork/care_fe/pull/8809)

**Comment by rithviknishad** [comment]
Updated to 2 considering the fact that you've put efforts in hunting this hidden issue in the first place! 😄
