### ISSUE TITLE
Button position issue on phone screen

### ISSUE THREAD

**Issue by modamaan** [coronasafe/care_fe#8969]
**Describe the bug**
button postion issue on phone-sized screen
div section overflow on phone screen 

**To Reproduce**

1. Go to 'sample test on sidebar'
2. Click on 'sample test button'
3. See error

1. Go to 'patients button on sidebar'
2. Click on 'any patient details'
3. See error

**Expected behavior**
- place the button in the correct postion
- correct position of div section

**Screenshots**
![Image](https://github.com/user-attachments/assets/ae8af8a8-4cf7-4ff1-80b1-f96d53defe13)

![Image](https://github.com/user-attachments/assets/c764f8b6-ffcc-457c-a4ec-8b024250c047)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [129.0.6668.101]

**Comment by modamaan** [comment]
@Jacobjeevan i would like to correct this

**Comment by Jacobjeevan** [comment]
Combined with #8975
