### ISSUE TITLE
Div section overflow on phone screen

### ISSUE THREAD

**Issue by modamaan** [coronasafe/care_fe#8975]
**Describe the bug**
div section overflow on phone screen 

**To Reproduce**

1. Go to 'patients button on sidebar'
2. Click on 'any patient details'
3. See error

**Expected behavior**
correct position of div section

**Screenshots**
![Image](https://github.com/user-attachments/assets/c764f8b6-ffcc-457c-a4ec-8b024250c047)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [129.0.6668.101]

**Comment by modamaan** [comment]
@Jacobjeevan i would like to correct this, can you assign to me

**Comment by Jacobjeevan** [comment]
Let's combine this issue with #8969 

We don't want to create an issue for every minor spacing edit like these.
