### ISSUE TITLE
Unable to Delete Any Shifting or Resource Record

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#8980]
**Describe the bug**
The delete functionality is not working for shifting and resource records.

**To Reproduce**

1. Go to either /shifting or /resource page
2. Open any record and try to delete it
3. See error

**Expected behavior**
The Delete functionality should work as expected

**Screenshots**

![Image](https://github.com/user-attachments/assets/2fa501e5-cecb-444b-8822-aebd25182619)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by praffq** [comment]
https://github.com/ohcnetwork/care/issues/1987

Similar issue listed on care

**Comment by bodhish** [comment]
We will not support delete for records.

**Comment by JavidSumra** [comment]
So can we remove that delete button @bodhish
