### ISSUE TITLE
Bug Report: Copy to Clipboard Function Showing Age as NaN on Shifting Details Page

### ISSUE THREAD

**Issue by Rishith25** [coronasafe/care_fe#8981]
Issue Description: On the "Shifting Details" page, the "Copy to Clipboard" function is not copying the "Age" field correctly. Instead of showing the actual age, it displays "NaN."

Steps to Reproduce:

Navigate to the "Shifting Details" page.
Locate the details for a specific person (e.g., Aditya Jindal).
Click the "Copy to Clipboard" button to copy all details.
Paste the copied text into a text editor or any other application to view the output.
Observed Result: The copied text shows "Age: NaN" instead of the actual age value.

Expected Result: The "Age" field should display the correct numerical age when copied to the clipboard.

Additional Information: Could you let us know if any other details should be included in the "Copy to Clipboard" function? For example, it might be helpful to add an "Emergency Status" field to clarify if this is an urgent or non-urgent shift. Please let us know if there are other details that should also be included in the copied information.

```.txt
Name:Aditya Jindal
Age:NaN
Current facility:Aloha New
Contact Number:+917719415700
Address:House No. 172 Balvir Singh Street
Reason:Contrary to popular belief, Lorem Ipsum is not simply .......
```

**Comment by Rishith25** [comment]
@rithviknishad I would like to work on this

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad, how can I delete the patients created under my name?

**Comment by Rishith25** [comment]
@AdityaJ2305 Hey there this is related to another issue

**Comment by mnshrm** [comment]
Hi @rithviknishad, 
I found solution to this issue, can raise PR in under 10 minutes for this issue, please assign the issue to me

Regards

**Comment by rithviknishad** [comment]
@Rishith25 

> Hey there this is related to another issue

Could you reference the related issue in such situations?

**Comment by mnshrm** [comment]
Hi @rithviknishad,
I have raised PR and linked this issue, Please let me know if any discrepancies are found, Happy to contribute to OHN

Regards
