### ISSUE TITLE
Unnecessary Update Requests in Shifting and Resource Records

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#8982]
**Describe the bug**
The application is allowing users to send unnecessary **PUT** requests to the server in shifting and resource update page without any change

**To Reproduce**

1. Go to '/shifting'  or '/resource
2. Select any record and click on Update Status / Details
3. Now without making any changes click on submit

**Expected behavior**
The submit should be active only if there's any change in the record

**Screen Recording**

https://github.com/user-attachments/assets/a29fa32c-ff79-48b3-922d-52136fab651a

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment]
@rithviknishad @Jacobjeevan I want to work on this issue

**Comment by rithviknishad** [comment]
Let's solve this along with #8918

**Comment by kihan2518B** [comment]
can you assign this issue to me as I am working on issue #8918 which is similar to this
