### ISSUE TITLE
Enhance Grid Layout in "View Users Associated with Facilities" Section

### ISSUE THREAD

**Issue by AnveshNalimela** [coronasafe/care_fe#8983]
The current grid layout in the "View Users" section under facility management appears cluttered and could benefit from a more organized structure. A switch to a list-like layout may improve readability and user experience, providing a cleaner and more intuitive interface for viewing user details.

Before:
![Image](https://github.com/user-attachments/assets/f6e0820e-3296-4a32-8443-7a721a907db5)
Steps to Reproduce:

Go to Facilities.
Click on View Facility for a specific facility.
Navigate to Manage Facility.
Select View Users.
Observed Issue: The grid layout in the "View Users" section is somewhat cluttered, making it harder for users to scan through information quickly.

Proposed Enhancement: Consider changing the grid layout to a list-style view. 

Improve readability by reducing visual clutter.
Potentially allow for more user-friendly sorting and filtering options in the future.

**Comment by AnveshNalimela** [comment]
I would like work on these .

**Comment by Sulochan-khadka** [comment]
@AnveshNalimela could you suggest how do you want to improve the UI? The current layout seems fine for me.

**Comment by AnveshNalimela** [comment]
@Sulochan-khadka  The Current card for holds 5 details for each user . we could switch to list or table instead of grid with each user having indivaul card

**Comment by Jacobjeevan** [comment]
So, we are doing a redesign for the user management page (dividing it into users list and user detail pages) #8878. I'd wait for that to be completed first (could probably reuse that page with minor tweaks once it's done).
