### ISSUE TITLE
Infinite Rendering and Redirection to 'not-found' Page When Adding Patient from Non-Home Facility

### ISSUE THREAD

**Issue by JavidSumra** [coronasafe/care_fe#8988]
**Describe the bug**  
When logged in as "Doctor Dev," attempting to add a new patient from the "View Facility" section in a facility that is not the user's home facility causes an infinite rendering loop. This results in a redirection to the "not-found" page.

**To Reproduce**  
1. Go to **/facility**
2. Click on **View Facility**
3. In any facility that is not the home facility, click on **Add Details of Patient**
4. Observe the error (infinite rendering and redirection to "not-found" page)

**Expected behavior**  
The system should display a notification with an appropriate message explaining the restriction and redirect the user back to the home page instead of triggering an error.

**Video**  
[Watch Video](https://github.com/user-attachments/assets/5bf92849-d240-4a8b-8dc3-1166f430781d)

**Desktop (please complete the following information):**
- **OS**: Windows
- **Browser**: Chrome
- **Version**: 130.0.6723.92

**Comment by JavidSumra** [comment]
Can You please Assign this issue to me
cc @Jacobjeevan @rithviknishad

**Comment by JavidSumra** [comment]
Hey @rithviknishad can you please assign this issue to me.

**Comment by Jacobjeevan** [comment]
In this case, expected behavior should be different:

`PatientRegisterAuth` in `PatientRegister.tsx` determines the permissions of the page, so for roles like Doctor/Nurse etc, the button should only be visible accordingly.
