### ISSUE TITLE
Chat on Whatsapp option appears even when there's no Emergency phone number

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#8990]
**Describe the bug**
An empty phone number is being passed for **Chat on Whatsapp** feature even when there's no emergency contact number

**To Reproduce**

1. Go to '/patients'
2. Select any patient without emergency contact number
3. See error

**Expected behavior**
**Click on whatsapp should appear only if that particular number exists**

**Screenshots**
![Image](https://github.com/user-attachments/assets/5072e6f3-c912-4288-b65c-87f057d448d8)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment]
@rithviknishad @Jacobjeevan I'd like to work on this issue

**Comment by rithviknishad** [comment]
The real issue here is, how are we having patient records without emergency phone number? It is a mandatory field.

**Comment by nithish1018** [comment]
@rithviknishad  I think those patient's data was added before when the emergency phone number was not a mandatory field.

**Comment by gigincg** [comment]
Potentially Create a separate issue to migrate out old data with an empty Emergency Number
