### ISSUE TITLE
Hide the pagination component in the facility staff capacity section if there is only one page.

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8992]
**Describe the bug**

The pagination component is visible in the staff capacity section of the facility details page, even when there is only one page to display.

**To Reproduce**

Steps to reproduce the issue:

1. Go to the facility tab.
2. Click on "View Facility" and scroll down to the staff capacity section.
3. Observe the pagination component.

**Expected behavior**

- [ ] The pagination component should only be shown if there is more than one page in the staff capacity section.

**Screenshots**

![Image](https://github.com/user-attachments/assets/108d3f55-e758-4ecb-9cad-4ffd135cc844)

**Comment by mnshrm** [comment]
HI @nihal467 @rithviknishad, please assign this issue to me, I wish to work on this

Regards

**Comment by mnshrm** [comment]
Hello @rithviknishad, 
Raised PR for the issue, and also linked it, please let me know if any discrepancies are found

Thanks for the opportunity

**Comment by mnshrm** [comment]
Hi @nihal467, 
requesting a review again for my pull request as for me the fix is working fine

Regards
