### ISSUE TITLE
Add CSV Export support for Facility Specific Discharge Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8993]
**Is your feature request related to a problem? Please describe.**

There is currently no option to export the discharge patient list from the facility-specific discharge patient list page. This limits the ability to extract and analyze this information outside the platform easily.

**Describe the solution you'd like**

- [ ] Add export functionality to the facility-specific discharge patient list page.
- [ ] Ensure the export option is enabled only after a 7-day period is selected in the date-based advanced filter.

Note: The export behavior should be similar to the patient list export feature. When the user clicks on the export button, prompt them to select a 7-day period before proceeding.

![Image](https://github.com/user-attachments/assets/3255c4e1-7112-4104-8aba-2924c021894d)

**Comment by AnveshNalimela** [comment]
@nihal467 i would like to work on this issue . assign it to me.

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.

**Comment by AnveshNalimela** [comment]
Im currently working on these. these issue to be attached with backend so it is taking time
