### ISSUE TITLE
Improve the Date and Time component in the CARE

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8994]
**Describe the bug**

- [ ] Regardless of the user's system time preference, the text field displays time in 24-hour format, while the selection component defaults to a 12-hour format. This inconsistent behavior is not ideal for a component.
- [ ] It is not possible to input "01" in the minutes part of the component; the input text area always shows "1," automatically removing the "0" for single-digit entries.

**To Reproduce**

1. Go to patient consultation page
2. Click on edit consultation consultation
3. Scroll down to admission date

**Expected behavior**

- [ ] The text area and selection component for date and time should align with the user’s system time preference.
- [ ] Users should be allowed to enter "01" in the minutes part of the component. Similarly, this behavior should be allowed for all other date and hour parts as well

**Screenshots**

![Image](https://github.com/user-attachments/assets/020f8b07-8c07-4516-9f50-1cca5d6ee9db)
![Image](https://github.com/user-attachments/assets/85e3b747-a806-4c5e-80f8-addaf347e7b2)

**Comment by Keerthilochankumar** [comment]
I want to work on this issue. assign it to me.

**Comment by SwanandBhuskute** [comment]
I would like to work on this @nihal467

**Comment by bodhish** [comment]
@Keerthilochankumar are you working on this? If yes please do create a draft PR and tag it with the issue.

**Comment by Sancharisingh** [comment]
@bodhish I would like to work on this issue. Could you please assign it to me?

**Comment by Keerthilochankumar** [comment]
@bodhish  the work is done i will make pr by the night

**Comment by rithviknishad** [comment]
@Keerthilochankumar unassigned due to inactivity. @Sancharisingh do you want to take this up?

**Comment by Jeffrin2005** [comment]
@Sancharisingh, would you like to work on it? If not, I would be happy to take it on

**Comment by Sancharisingh** [comment]
@rithviknishad Yes, I would like to take this up. Please assign it to me.

**Comment by saikiranpatil** [comment]
@nihal467 i have created a PR, please review it

**Comment by AdityaJ2305** [comment]
Hey @nihal467 @rithviknishad, I would like to take up this issue

**Comment by Sancharisingh** [comment]
@AdityaJ2305 I am working on this issue.

**Comment by AdityaJ2305** [comment]
@saikiranpatil  has closed PR so I thought he is not working on it anymore

**Comment by Jacobjeevan** [comment]
@Sancharisingh Any update on this?

**Comment by rajku-dev** [comment]
> [@Sancharisingh](https://github.com/Sancharisingh) Any update on this?

@Jacobjeevan Please consider assigning this issue to me if its not being currently worked on.
