### ISSUE TITLE
Fix UI bugs with Symptoms editor and move to ModelCrudEditor component

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#8998]
![Image](https://github.com/user-attachments/assets/360a9281-794a-4cbd-920e-334c5030af1c)

- Fix the overlap in date input
- Fix the dropdown icon.
- Port over the `<EncounterSymptomsBuilder>` component to use `<ModelCrudEditor>` 
Example: https://github.com/ohcnetwork/care_fe/blob/a0e6e621260a3501e3828c3ad9f14ae7efd3d94f/src/components/Facility/SpokeFacilityEditor.tsx#L132

**Comment by Keerthilochankumar** [comment]
I want to work on this issue. assign it to me.

**Comment by SwanandBhuskute** [comment]
I would like to work on this @shivankacker

**Comment by Srayash** [comment]
hey @shivankacker  @rithviknishad I've made a PR fixing the UI issues, but I'll need some help with implementing the `move to ModelCrudEditor` part.

**Comment by shivankacker** [comment]
@Srayash sure what's the blocker?

**Comment by Srayash** [comment]
> [@Srayash](https://github.com/Srayash) sure what's the blocker?

Hi @shivankacker, I truly appreciate your willingness to help.
I'm a bit uncertain about the approach to take. If you could kindly share any insights on how to tackle this, I would be incredibly grateful for your support.

Thank you for your time and assistance!

**Comment by shivankacker** [comment]
@Srayash I have mentioned an example of the ModelCrudEditor component. It is basically a helper component to create modules where you need to create/edit/delete rows (just like symptoms editor). All you will have to do is port the existing component. If you spend some time on it you would understand how the component works.

**Comment by Srayash** [comment]
![Image](https://github.com/user-attachments/assets/37b9df1b-1bf5-4cf7-8d0c-e85f2d76b127)
these are the crud functions I defined are they okay with you?

**Comment by Srayash** [comment]
Hi @@shivankacker - I wanted to update you on my progress. I've completed part of the task but have hit some roadblocks. The ported component isn't functioning as expected yet. I'll submit a draft PR with my current work so you can review it and help guide me on completing the remaining portions and fixing the component's behavior. Thanks!

**Comment by JavidSumra** [comment]
Hey Team I would like to work on it.

**Comment by rithviknishad** [comment]
@JavidSumra @shivankacker let's skip porting over to model crud editor for now. Since fhir based form fields would end up overwriting these changes anyways.
