### ISSUE TITLE
Improve Age Validation in User Creation Form

### ISSUE THREAD

**Issue by Rishith25** [coronasafe/care_fe#9001]
**Description**:Currently, when creating a user, if the Date of Birth (DOB) entered corresponds to an age less than 15 years, the system makes an API call and returns an error with the message: "Age must be greater than 15 years."

![Image](https://github.com/user-attachments/assets/1982147f-ee82-4357-88ad-0804c9824c8b)

**Proposed Improvement:** To enhance the user experience and reduce unnecessary API calls, dynamic client-side validation should be added to the form. This validation would check if the age is at least 15 years before submitting the form, thereby providing immediate feedback to the user.

**Expected Behavior:**

The form should display an error message dynamically if the user enters a DOB indicating an age less than 15 years.
The form should prevent the API call from being made if the age criteria are not met.
**Benefits**:

Reduces API traffic.
Improves user experience with real-time feedback.

**Comment by Rishith25** [comment]
@rithviknishad I would like to work on this can you assign it to me.

**Comment by rithviknishad** [comment]
@Jacobjeevan Could you confirm and assign accordingly if it's being done along with #8878

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) Could you confirm and assign accordingly if it's being done along with [#8878](https://github.com/ohcnetwork/care_fe/issues/8878)

@rithviknishad I wasn't planning on editing this page, but since we are using most of the same fields in single user detail/management page, it just makes sense to reuse those components here 🤔

**Comment by Rishith25** [comment]
@rithviknishad should I proceed with this issue?

**Comment by rithviknishad** [comment]
@Jacobjeevan's PR would be addressing this too @Rishith25

**Comment by abhishekreddy8604** [comment]
Is this done else I can do it

**Comment by Jacobjeevan** [comment]
@abhishekreddy8604 The issue is already assigned and it's taken care of 👍
