### ISSUE TITLE
Unable to Use Switch button on Camera Capture (File Upload) 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#9002]
**Describe the bug**
When trying to upload files using camera capture on the file upload feature, the "Switch" button for switch between front camera and to rear camera is not working. it is showing an error " Switch Camera is not available". it's happening on an IOS device. (safari)
it takes multiple clicks to get this error response. 
currently, the camera opens as front camera by default 
Also even if we close the camera capture session, the system was showing the camera is still on use. I have to stop the camera use manually. 
**To Reproduce**

1. Go to CARE on an IOS device (18.1)  safari
2. select a patient card
3. Click on file upload and try to upload a file using camera capture
4. click on the switch button
5. See error
**Expected behavior**

- [ ] The switch button should be responsive on the first click
- [ ] Back camera should be opened as default
- [ ] Camera use should be stopped automatically when the camera capture session is closed 
- [ ] Delay in opening camera and capturing picture should be resolved. ( seen on android devices)

**Screenshots**
link for the video: https://drive.google.com/file/d/1bRGGN4avusAWx3fNguyvl1nBQcD0O_g3/view?usp=sharing

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone13]
- OS: [e.g. iOS18.1]
-  safari

**Additional context**

**Comment by abhistarck** [comment]
Hey @samholics  l like to work on this issue

**Comment by bodhish** [comment]
@abhistarck if you are working on the issue can you link the draft PR here?

**Comment by JavidSumra** [comment]
Hey @bodhish If no one is working on it can you assign it to me?
