### ISSUE TITLE
Infinite Loading on 'Get Tests' Button in Patient Investigation Report

### ISSUE THREAD

**Issue by JavidSumra** [coronasafe/care_fe#9009]
**Bug Description**  
The "Get Tests" button in the Investigation Report of a patient loads indefinitely.

**Steps to Reproduce**  
1. Navigate to the '/patient' page.
2. Select any patient.
3. Open the "Manage Patient" dropdown menu.
4. Choose "Investigation Summary."
5. Select any Investigation Group.
6. Click on "Get Tests."

**Expected Behavior**  
The button should either display an error or stop loading after a timeout if no data is available.

**Screenshots**  
![Screenshot](https://github.com/user-attachments/assets/633c7f43-75f0-4f03-8ce5-a58821d7c565)

**Desktop Information:**  
- **OS:** Windows  
- **Browser:** Chrome  
- **Version:** 130.0.6723.92

**Comment by JavidSumra** [comment]
Hey Team Can you please assign this issue to me

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.

**Comment by JavidSumra** [comment]
Hey @ANIR1604, I don't think this is a valid issue—it might just be a versioning issue with lodash in the build, as it doesn’t appear in the local environment. Right, @rithviknishad?

**Comment by JavidSumra** [comment]
The issue is no longer persisting.
