### ISSUE TITLE
Date and Time component restricts selecting same-day discharge date for patients due to non-proper future date validation.

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9011]
**Describe the bug**

- [ ] When discharging a patient on the same day as their admission, the discharge date selector does not allow selecting the admission date in the patient discharge pop-up.

**To Reproduce**

1. Go to the patient tab
2. Select any active patient to open their dashboard.
3. Click on Manage Patient and choose Edit Consultation.
4. Set the patient admission date to today’s date.
5. Submit the form to return to the patient dashboard.
6. Click on Manage Patient again and select Discharge from Care.
7. See error

**Expected behavior**

- [ ] The date and time component should allow selecting any date and time from the admission date up to the current date and time, supporting same-day discharges.

**Screenshots**

![Image](https://github.com/user-attachments/assets/7c53f21c-8f0e-4419-a5f5-532ee7bbb679)

**Comment by JavidSumra** [comment]
Can You please assign this issue to me

**Comment by nihal467** [comment]
@JavidSumra its a priority issue, can you push the fix by EOD

**Comment by JavidSumra** [comment]
I'll check and let you know

**Comment by nihal467** [comment]
@JavidSumra check and comment over here, then i will assign you the issue

**Comment by JavidSumra** [comment]
I need to disable the Date Component if the admit date is the same as today, correct?

**Comment by JavidSumra** [comment]
Hey @nihal467, could you clarify the expected behavior a bit more? From what I understand, if we set the admission date to today and then try to discharge the patient, it should display the time starting from today. Is that correct? If so, what exactly is the issue?

**Comment by JavidSumra** [comment]
@nihal467 I'll work on this issue

**Comment by JavidSumra** [comment]
Hey @nihal467 can you please assign 2 Story Point for this?
cc @rithviknishad

**Comment by rithviknishad** [comment]
@JavidSumra 1 story point is reasonable for small changes.
