### ISSUE TITLE
Refactor the Existing Cypress Auth Test

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9015]
**Description**

Refactor all the existing auth test in the platform to POM approach and use the reusable components

**Task - Part 1**

**Rename and Merge Files:**

- Rename the [auth_spec](cypress/e2e/auth_spec) to homepage_spec
- Rename the [auth.cy.ts](https://github.com/ohcnetwork/care_fe/blob/develop/cypress/e2e/auth_spec/auth.cy.ts) to UserLogin.cy.ts
- Combine [auth.cy.ts](https://github.com/ohcnetwork/care_fe/blob/develop/cypress/e2e/auth_spec/auth.cy.ts) and [forgotpassword.cy.ts](cypress/e2e/auth_spec/ForgotPassword.cy.ts) into UserLogin.cy.ts under separate describe blocks. This keeps tests organized and logically grouped.

**Refactor to POM**

- Import and reuse login credentials from the LoginPage.ts file. If the credentials are not present, add new ones to the LoginPage file as well, and replace any direct usage of cy.loginbyapi with calls to LoginPage.
- Add API verification with cy.intercept before clicking #user-profile-name to ensure the page is fully loaded.
- Convert lines 9 and 10 to POM and create functions for them in the UserProfilePage.ts file.
- Similarly, convert all code from lines 15 to 21 to the POM approach, adding cy.intercept for verification and moving credentials to LoginPage if they are missing.
- Use the reusable helper functions in the [commands.ts](cypress/support/commands.ts) file for the submit button , notification verification, etc... common functions
- Remove the hardcoded wait, and if necessary, replace it with cy.intercept() API verification to avoid flaky tests.
 
![Image](https://github.com/user-attachments/assets/d7448ad1-0562-4fa0-a406-a0c550c41770)

**Task - 2**

![Image](https://github.com/user-attachments/assets/6228f913-1ee8-443a-969e-ecf10d188ec4)

- Combine all the tests into one single test
- Test Follow: Click on forgot password -> Send password reset link -> Go back to the login page
- Follow all the similar approaches for writing code mentioned in the test - 1

**Comment by JavidSumra** [comment]
Can You please Assign this issue to me

**Comment by JavidSumra** [comment]
@nihal467 shall i add new page object in LoginPage.ts File or create new file for page Object?

**Comment by JavidSumra** [comment]
Hey @khavinshankar can you please assign 2 story points for this.
