### ISSUE TITLE
Add New cypress Test for language selection and link redirection

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9017]
**Description**

Add a new Cypress test to verify language selection and repository redirection functionality.

**Conditions to follow**

- Add these tests to the redirect.cy.ts file.
- Use the Page Object Model (POM) approach.
- Reuse existing functions and add necessary API verification with cy.intercept.

**Test - 1**

- After the LoginPage loads, click the "Contribute on GitHub" link and verify redirection by checking the URL and the new page content.
- Repeat the same for the "Third Party Software License" link.

**Test - 2**

- After the login page loads, switch between all five languages and verify that the login submit button text updates according to the selected language.
- Log in with any language selected other than English and verify that the sidebar items display in the chosen language

**Screenshot**

![Image](https://github.com/user-attachments/assets/f3fe927b-6187-441e-bb86-9ee3691a603b)

**Comment by AdityaJ2305** [comment]
@nihal467 I would like to work on this issue. Could you assign it to me ?

**Comment by AdityaJ2305** [comment]
Hey @nihal467, apologies, but I’d like to unassign myself from this issue.

**Comment by Kaushikgtm** [comment]
@nihal467 can you assign this to me ?

**Comment by AdityaJ2305** [comment]
@nihal467 Apologies, but I’m not working on this issue. Please assign it to @Kaushikgtm. Thanks!

**Comment by Kaushikgtm** [comment]
@nihal467 I have write code for Cypress test -1 but face some difficulty to write cypress test-2 should i raise a PR for test-1 or not ?

**Comment by nihal467** [comment]
@Kaushikgtm what is the difficulty you are facing, share the issue

**Comment by Kaushikgtm** [comment]
Hii @nihal467  The LANGUAGES and resources are managed via i18next, but I cannot figure out how to reference them correctly in the Cypress tests.  Translations like sidebar items and button text are already implemented in i18n and LanguageSelector components. However, I’m unsure how to fetch and use these dynamically in the test cases to verify language-specific UI updates.
![Image](https://github.com/user-attachments/assets/e0caf394-ee60-46fb-b9d3-19067af22686)

**Comment by Kaushikgtm** [comment]
@nihal467 there is no function in Page Object Model which Verify Language for Login and Sidebar items,  can you help ?

**Comment by Kaushikgtm** [comment]
can i raise a PR for test-1?
![Image](https://github.com/user-attachments/assets/f762be43-daf9-4182-8a79-39ab6c41ee6e)

**Comment by nihal467** [comment]
@Kaushikgtm 

- In the Test 1 code you wrote, you are not interacting with the platform at all. You are only interacting with the browser and verifying its URL. That's not what the test is about. Please read the issue carefully and write the test accordingly.

- In Test 2, if there is no page object already present, you need to create a new ID and page object to write the test.

**Comment by Kaushikgtm** [comment]
@nihal467 updated test 1 code 
![Image](https://github.com/user-attachments/assets/5637742e-b617-4952-9efc-2737c2085932)
loginpage in POM updated
![Image](https://github.com/user-attachments/assets/eefe4afd-451a-47c0-ac30-98e3a27acb82)

**Comment by nihal467** [comment]
@Kaushikgtm raise the PR for review purpose

**Comment by Kaushikgtm** [comment]
Hii @nihal467  I’m working on Test 2 to verify that the sidebar items display correctly in the selected language after switching between the five supported languages. The sidebar content is already defined in six different language files within the repository.
Should I Duplicate the sidebar mapping in the loginpage mapping file for test verification, or Reuse the existing language files directly?

**Comment by nihal467** [comment]
@Kaushikgtm dont use the existing language typo variable, declare constant's and verify using that

**Comment by rajku-dev** [comment]
Hi @Jacobjeevan , can i work on this issue?
