### ISSUE TITLE
Disallow picking out of range month or year from month/year selector in date input dropdown

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#9030]
**Describe the bug**
Using the month selector, I can go to any month in the calendar (even ones beyond the allowed range). However, once a month out of the range is selected, I am not able use the navigation button to move towards the month that is in range.

**Expected behavior**
- [ ] User should not be able to pick a month or year that is out of range in the first place from the month/year selector view.

**Screenshots**

![Image](https://github.com/user-attachments/assets/ef0812d8-4969-4d07-859b-618b47cd9849)

![Image](https://github.com/user-attachments/assets/f2ff974e-9be7-49f8-a7dd-34ce52aab12f)

**Comment by Mahendar0701** [comment]
@rithviknishad  I want to work on this. Can you please assign this to me.

**Comment by Rishith25** [comment]
@rithviknishad i would like to work on this

**Comment by Jacobjeevan** [comment]
Since Mahendar has created an issue he wants to work on, assigning this to Rishith 👍

**Comment by ayushsaini7717** [comment]
can i work on this issue.

**Comment by Jacobjeevan** [comment]
@ayushsaini7717 Issue is already assigned and being worked on. For future reference, make sure to check if there's an open PR and if there's any activity there before requesting for assignment 👍
