### ISSUE TITLE
Adding comments in the code base .

### ISSUE THREAD

**Issue by love-to-code108** [coronasafe/care_fe#9033]
**Describe the bug**
The codebase lacks comments.

**To Reproduce**

**Expected behavior**
There should be comments so that is any new contributer can easily understand whats going on where .

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by love-to-code108** [comment]
Please assign me this issue i would like to work on this .

**Comment by Jacobjeevan** [comment]
We don't explicitly need comments, good code should be readable on its own (which we are doing fine imo). If you feel a particular block of code is hard to understand, feel free to raise an issue there. Otherwise this would be too broad of an issue.

**Comment by love-to-code108** [comment]
Ok
