### ISSUE TITLE
Software Update notification badges are overlapping

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#9039]
**Describe the bug**
when trying to update software by clicking " check for update" option on profile page, Updated successfully notification comes up even before clicking on update button on the "software update is available" notification. These two overlap each other

![Image](https://github.com/user-attachments/assets/f5e6a98b-2ce7-48d2-992e-560e5c4f4de3)

link for the video: https://drive.google.com/file/d/1Df4rkPPWFk8yhRX2ddTpln6SmPIwfa8u/view?usp=sharing

**To Reproduce**

1. Go to profile
2. Click on '' check for update'
3. See error

**Expected behavior**

- [ ] show the update available notification with the update button first.
- [ ] show the notification showing software updated to a newer version after clicking on the update button on the first notification

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rohitlingarker** [comment]
I want to work on this. Can you please assign this to me.

**Comment by nithish1018** [comment]
I'd like to work on this issue, please assign it to me

**Comment by ayushpatil2122** [comment]
hey can you assign this issue to me

**Comment by SwanandBhuskute** [comment]
I would like to work on this issue, pls assign me @samholics

**Comment by bodhish** [comment]
@ayushpatil2122 if you are working on this issue please create a draft PR

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.

**Comment by Rustix69** [comment]
@rithviknishad On running the website through - npm run dev, when i go for check of updates its keeps on loading.

**Comment by rithviknishad** [comment]
https://github.com/ohcnetwork/care_fe/blob/develop/package.json#L36

You might want to try building and running instead.

**Comment by Rustix69** [comment]
@rithviknishad Please check the PR, I had resolved the issue of the notifications overlapping each other.

**Comment by Rustix69** [comment]
@rithviknishad I had solved this issue by aligning the processes one by one but its giving error in cypress tests in the file which was not edited or changed by me. I am a new contributor in you org can you please guide.

**Comment by Jacobjeevan** [comment]
@ANIR1604 Since you deleted the branch, are you still working on this? 

If so, you would need to continue on the same branch.

**Comment by Rustix69** [comment]
Ok I will raise a new PR from a New Branch.

> [@ANIR1604](https://github.com/ANIR1604) Since you deleted the branch, are you still working on this?
> 
> If so, you would need to continue on the same branch.

Ok I will raise a new PR from a New Branch.

**Comment by bodhish** [comment]
@ANIR1604 can you link the PR here?
