### ISSUE TITLE
Refactor the Facility Export existing cypress test and Add New Sidebar collapse test along with it

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9043]
**Description**

- [ ] Refactor the existing facility export by combining two existing tests and adding test for verifying sidebar collapse functionality

**General Instruction**

- Use all reusable functions from the commands.ts file and other existing tests.
- To understand if a custom function used in other existing tests exists, search using their element ID in the codebase.
- Use the POM approach; refer to the Patient_Spec folder for guidance.
- Add necessary API verifications and verify notifications and text to avoid flaky tests.
- Add the test file to FacilityHomepage.cy.ts and the related function in the facilityHome.ts file

**Task - 1: Add new test for sidebar collapse**

- Once the homepage loads, verify that all sidebar icons with their corresponding text are visible.
- Next, collapse the sidebar and confirm that only the icons are visible.
- now again expand the sidebar and verify all the sidebar icon with their corresponding text are visible

**Task - 2: Refactor the existing cypress facility export** 

![Image](https://github.com/user-attachments/assets/10be67fd-dd72-4aea-9bbf-9e9ad9082c59)

- Remove the "Verify Capacity Export Functionality" test, and incorporate those test lines into the existing "Verify Facility Export Functionality" test.
- Add API verification for the capacity export test as well.

**Comment by ghost** [comment]
@nihal467 sir can I work on this issue ?

**Comment by JavidSumra** [comment]
if no one working on this issue can you please assign it to me?

**Comment by JavidSumra** [comment]
@nihal467 I think now there is no need of task-2 right?
