### ISSUE TITLE
Search Icon is being hidden in every Search Input box

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#9057]
**Describe the bug**
The search icon is not visible on search input component in any page, but it's available in the DOM

**To Reproduce**

1. Go to any page with Search feature like, '/facility' , '/shifting'
2. You can see that Search Icon is not showing up but it's available in the **DOM** with class **l-search-alt**

**Expected behavior**
Search Icon should appear properly

**Screenshots**

Currently this is how it looks :

![Image](https://github.com/user-attachments/assets/09ed6e59-e26d-4687-9422-acfd104d1cd3)

After Fix :

![Image](https://github.com/user-attachments/assets/3c52afb5-3671-486e-8cd9-d3b433e58c63)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment]
@Jacobjeevan @rithviknishad I'd like to work on this and raise a quick PR

**Comment by nithish1018** [comment]
Hey @Jacobjeevan along with this change, should I remove the delete functionality of Shifting and Resource records as we're not supporting them as discussed/mentioned in this [issue](https://github.com/ohcnetwork/care_fe/issues/8980)?

cc: @bodhish

**Comment by Jacobjeevan** [comment]
> Hey [@Jacobjeevan](https://github.com/Jacobjeevan) along with this change, should I remove the delete functionality of Shifting and Resource records as we're not supporting them as discussed/mentioned in this [issue](https://github.com/ohcnetwork/care_fe/issues/8980)?
> 
> cc: [@bodhish](https://github.com/bodhish)

Sure, remove the buttons 👍
