### ISSUE TITLE
Release the Mic in file upload component after the use

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9058]
**Describe the bug**

Post recording the audio in the file upload component, the platform is showing the mic is still in use 

**To Reproduce**

1. Go to patient tab
2. Click on any active consultation patient
3. go to files section and record a audio
4. post recording
6. See error

**Expected behavior**

- [ ] mic should be released in file upload component after the use

**Screenshots**

![Image](https://github.com/user-attachments/assets/025bde23-406a-4b70-a2d3-24f459f6f829)

**Comment by abhip161** [comment]
Hey @nihal467 I like to work on it can you assign it to me

**Comment by Mahendar0701** [comment]
@nihal467 i want to work on this. Can you assign this to me

**Comment by rohitlingarker** [comment]
@nihal467 i want to work on this. Can you assign this to me

**Comment by khavinshankar** [comment]
@abhip161 what is the status on this issue

**Comment by JavidSumra** [comment]
Hey Team Can you please assign this issue to me?

**Comment by Jacobjeevan** [comment]
> Hey Team Can you please assign this issue to me?

Go ahead and add this in the PR you just raised #9180

**Comment by heymitali** [comment]
@nihal467 @Jacobjeevan If this issue is not yet resolved, can i work on it ?

**Comment by Jacobjeevan** [comment]
> [@nihal467](https://github.com/nihal467) [@Jacobjeevan](https://github.com/Jacobjeevan) If this issue is not yet resolved, can i work on it ?

It's resolved in a recent PR 👍 

![Image](https://github.com/user-attachments/assets/28630c42-e90d-4007-a7e0-1e15c2ff5142)
