### ISSUE TITLE
Add "Update Details" Button in view details page of community nurse and details log update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9060]
**Describe the bug**

We can't directly access the edit log update page from the view details page of the community nurse or the detail log update page.

**To Reproduce**

1. Go to the patient tab
2. Click on active consultation and click on log update
3. create a new community nurse log update
4. On successful creation, in the patient consultation page, switch to "Daily Rounds" view
5. click the view details page in the community nurse log update card
6. See error

**Expected behavior**

- [ ] add the "Update details" button, in the view details page of community and detail log update

**Screenshots**

![Image](https://github.com/user-attachments/assets/ac4a2945-f5ae-4bb2-a06f-94de3360e7ad)

![Image](https://github.com/user-attachments/assets/25acbfb0-d583-4ba9-93a0-28c208018d81)

**Comment by kihan2518B** [comment]
I want to work on this issue.

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.
