### ISSUE TITLE
Improper Error Handling while moving the Shifting Cards

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#9061]
**Describe the bug**
When we try to drag and drop certain shifting cards, an error shows up saying "**No PatientConsultation matches the given query**.", but the page will be still in loading state and we can actually scroll down and update the Shifting status as well

**To Reproduce**

1. Go to '/shifting'
2. Try to drag and drop shifting cards
3. See error

**Expected behavior**

https://rebuildearth.slack.com/archives/C01035FT0P5/p1732200285984509?thread_ts=1731335130.081059&cid=C01035FT0P5 refer this thread for expected behavior

**Screen Recording**

https://github.com/user-attachments/assets/1b55b95c-d2c3-439e-a07c-d616d7c3cf81

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment]
Please share the expected behaviour of this issue @nihal467

**Comment by nihal467** [comment]
@nithish1018 can you reply to the follow-up message https://rebuildearth.slack.com/archives/C01035FT0P5/p1731335130081059

**Comment by nithish1018** [comment]
@nihal467 I'll check the root cause and update you in that thread

**Comment by Tanuj1718** [comment]
@nihal467 @rithviknishad @bodhish Can you please assign this issue to me? We are able to place the cards in 'complete' column but for the 'Destination approved', 'Transportation arranged' and 'Transfer in progress' columns, it is showing anonymous behaviour.

**Comment by noufalrahim** [comment]
@rithviknishad is this pending1? can u assign this to me..

**Comment by nihal467** [comment]
@noufalrahim are you still interested in working on this issue

**Comment by noufalrahim** [comment]
@nihal467 yes

**Comment by sanjayh-2022** [comment]
@nihal467 Sir can I please work on this issue

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad , I would like to take up this issue

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad @Jacobjeevan, I would like to work on this issue.
