### ISSUE TITLE
Investigation Suggestion section data is not visible in mobile responsive view

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9063]
**Describe the bug**

When we try to view the investigation suggestion under the investigation tab, it is shown as no suggestion even though the data exist. 

Note: This data is properly visible in normal desktop view

**To Reproduce**

1. Go to patient tab
2. click on any active consultation and click manage patient then select edit consultation
3. scroll down to the investigation suggestion and add data then submit the form
4. in the consultation page, select the investigation in the nav bar
5. switch to mobile view
6. See error

**Expected behavior**

- [ ] investigation suggestion should be properly visible on all screen size

**Screenshots**

![Image](https://github.com/user-attachments/assets/4b8e14b3-60f0-42e1-81cd-e4b19616018d)
![Image](https://github.com/user-attachments/assets/cf39b285-6f6d-4e9a-8cd2-c22ce153e695)

**Comment by Keerthilochankumar** [comment]
I want to work on this issue.

**Comment by nihal467** [comment]
@Keerthilochankumar can you push the fix by tomorrow EOD

**Comment by Keerthilochankumar** [comment]
@nihal467 I am not sure if I could get it by Eod  so please assign it to someone else

**Comment by AdityaJ2305** [comment]
Hey @nihal467  I would like to work on this issue.  Already solved it
