### ISSUE TITLE
Update the form UI on the Consultation Update page

### ISSUE THREAD

**Issue by modamaan** [coronasafe/care_fe#9067]
**Describe the bug**
Update the form UI on the Consultation Update page

**To Reproduce**

1. Go to 'patient button on sidebar'
2. Click on 'Click on active consultation'
3.  Switch to "Daily Rounds" 
4. Click on "View Details"
5. See error

**Expected behavior**
good ui

**Screenshots**
![Image](https://github.com/user-attachments/assets/c94de335-9776-46bb-a650-7dfb96c9ad39)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [130.0.6723.117]

**Comment by modamaan** [comment]
@Jacobjeevan i would like to work on this

**Comment by Jacobjeevan** [comment]
Make sure to have descriptive titles for issues @modamaan

**Comment by rithviknishad** [comment]
Closing as this has been removed in the re-architecture branch in favour of Questionnaire.

https://github.com/ohcnetwork/care_fe/pull/9262

<img width="1822" alt="image" src="https://github.com/user-attachments/assets/869708ec-2bcc-47df-8cbc-79ac96e3f4b5" />
