### ISSUE TITLE
Warranty Card UI: Improve Responsiveness and Text Overflow Handling for Multi-Language Support

### ISSUE THREAD

**Issue by AlgoFoe** [coronasafe/care_fe#9071]
**Describe the bug**
The warranty card UI encounters issues with layout and text overflow when displayed in different languages or on smaller screens. When certain languages are selected, text length increases, causing overflow outside the container. Additionally, the layout lacks proper responsiveness, leading to overlapping or misaligned elements on smaller screens.

**To Reproduce**
1. In the assets section, select any asset.
2. Change the language to one with longer text, such as Tamil.
3. View the warranty card on various screen sizes, particularly smaller screens.
4. Notice any text overflow and layout issues.

**Expected behavior**
The warranty card should adjust  to accommodate different languages and screen sizes. Text should wrap properly, and elements should align responsively without overflow or overlapping.

**Screenshots**
![Image](https://github.com/user-attachments/assets/d37082f9-730f-40cd-b1bb-df815ff3117b)
https://github.com/user-attachments/assets/576bc706-c8b8-44a9-ab6d-4b0ad52c56fe

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: Chrome
- Version: 130

**Smartphone (please complete the following information):**
- Device: iPhone XR
- Browser: Chrome
- Version: 130

**Additional context**
Further work is needed to ensure the warranty card UI is fully responsive, with text wrap and layout adjustments for improved language support and responsiveness across different screen sizes.

**Comment by AlgoFoe** [comment]
@Jacobjeevan can u assign me this issue, so I can start working on it.

**Comment by Jacobjeevan** [comment]
@AlgoFoe Any updates with this? 

Try to salvage the existing PR/see if you can update it.

**Comment by modamaan** [comment]
@Jacobjeevan  i would like to take it up
