### ISSUE TITLE
Min,Max condition in discharge from care pop-up is not allowing user to swap calendar months

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9101]
**Describe the bug**

The calendar in the "Discharge from Care" pop-up does not allow users to navigate to previous months within the range of the patient's admission date to the current date.

**To Reproduce**

1. Go to the patient tab.
2. Click on any patient card with an active live consultation.
3. Select "Manage Patient" and choose the "Discharge from Care" option from the dropdown menu.
4. Try to change the calendar to a previous month and observe the issue.

**Expected behavior**

- [ ] The calendar should allow users to navigate back to previous months within the valid date range (from the patient's date of admission to the current date).

**Screenshots**

![Image](https://github.com/user-attachments/assets/15f0b73a-05e3-421a-b7cc-2590076ab7e4)

**Comment by AdityaJ2305** [comment]
Hey @nihal467 , Let me check if I can solve this issue

**Comment by AdityaJ2305** [comment]
@nihal I checked for a patient admitted on 10th October, and it’s allowing me to switch to October month. Could you clarify if I’m misunderstanding this issue?
[](https://github.com/user-attachments/assets/cafe8df1-22c0-4d3a-8199-f6a73c05b191)

**Comment by AdityaJ2305** [comment]
@nihal467  I checked for a patient admitted on 10th October, and it’s allowing me to switch to October month. Could you clarify if I’m misunderstanding this issue?

https://github.com/user-attachments/assets/5e32b453-5562-4784-ba42-8bcd7bf836a1

**Comment by nihal467** [comment]
@AdityaJ2305 seem like your develop is out of sync, check in care.ohc.network or update your local develop

**Comment by AdityaJ2305** [comment]
> [@AdityaJ2305](https://github.com/AdityaJ2305) seem like your develop is out of sync, check in care.ohc.network or update your local develop

No,  It’s up to date. I also double-checked with the original repo, and everything looks synced.

**Comment by ghost** [comment]
> [@AdityaJ2305](https://github.com/AdityaJ2305) seem like your develop is out of sync, check in care.ohc.network or update your local develop

I think he is correct nihal sir, because even in care.ohc.network also it looks fine to me

**Comment by nihal467** [comment]
issue seems to be resolved
