### ISSUE TITLE
Add Cypress Test to Verify Bed Capacity Badge Behavior on Facility Card

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9107]
**Describe the Test**

Verify the functionality of the occupancy badge on the facility card in the facility homepage.

**General Instruction**

- Code should follow the POM structure.
- Reuse existing custom functions and those in commands.ts where possible. Before creating a new function, check for an existing one that matches the element's ID to avoid redundancy.
- Add API request verification wherever required using cy.intercept();

**Test Worflow to be test**

1. Choose a facility (other than Dummy Facility 40) that has a location assigned but currently has no beds available.
2. Verify that the occupancy badge displays correctly, showing the facility's current status (e.g., "0 beds available").
3. Add a new patient to the facility, without consultation
4. Check that the badge on the facility card is now highlighted in red, indicating that a patient is present in the facility, but no bed is available.
5. Add a bed to the selected facility.
6. Confirm that the badge now reflects the updated bed count, displays the new count accurately, and that the red highlight is removed.

Screenshot

![Image](https://github.com/user-attachments/assets/397e098b-b2a1-4ab3-8d22-3f808635bc04)

**Comment by ghost** [comment]
@Jacobjeevan sir , Are you working on it ? If not can I try this as I have created a PR for previous issue ?

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) sir , Are you working on it ? If not can I try this as I have created a PR for previous issue ?

I'm working on this issue 👍  

Note: You don't need to refer to anyone on team by sir/madam. Just call us by our names 👍
