### ISSUE TITLE
Refactor the existing cypress test to upload cover image

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9109]
**Description**

Enhance the existing test suite to include functionality for uploading, editing, and deleting the facility cover image.

**General Instruction**

- Code should follow the POM structure.
- Reuse existing custom functions and those in commands.ts where possible. Before creating a new function, check for an existing one that matches the element's ID to avoid redundancy.
- Add API request verification wherever required using cy.intercept();
- Add the tests in the facilityManage.cy.ts file and any new page objects in the facilityManage.ts file.

**Test Workflows**

**Test 1: District Admin** 

1. Log in as a district admin and navigate to any facility.
2. Open the facility cover image pop-up, then click the Cancel button to verify it functions correctly.
3. Reopen the cover image pop-up and upload an image, verifying the API response.
4. Edit the current cover image by uploading a new one, and verify the API response.
5. Delete the existing cover image, confirming the API response.

**Test 2: Access Verification with Non-Admin User**

1. Log in as the devdoctor user.
2. Repeat the steps from Test 1 to verify functionality consistency across user roles.

**Screenshots**

![Image](https://github.com/user-attachments/assets/eeac19ad-6c63-464e-9bea-f93d852d75e9)

**Comment by ghost** [comment]
@nihal sir , can I work on this one also ?

**Comment by rohitlingarker** [comment]
@Jacobjeevan Can you assign this to me

**Comment by rohitlingarker** [comment]
@nihal467 sir, as in the issue description , to verify functionality consistency across user roles , can i define tests as such for multiple roles:

![Image](https://github.com/user-attachments/assets/3f31e2e8-f0ed-4813-9752-3253a59f5d1b)

or create a custom function in loginpage which takes user role and logs a user 

![Image](https://github.com/user-attachments/assets/8822602f-b495-44b8-b5c8-db99477cbb8d)

**Comment by JavidSumra** [comment]
Hey @rohitlingarker are you still working on this issue?

**Comment by rohitlingarker** [comment]
Yes Iam @JavidSumra

**Comment by JavidSumra** [comment]
Hey @nihal467 can you please assign this issue to me?

**Comment by sanjayh-2022** [comment]
Sir  @nihal467 can you please assign this issue to me?
I am really interested to work on this issue

**Comment by JavidSumra** [comment]
Hey @nihal467 shall i need to create a new test file under `facility_spec`?
ref https://github.com/ohcnetwork/care_fe/pull/9134#issuecomment-2488733438

**Comment by JavidSumra** [comment]
@rithviknishad Made a PR for this issue can you please assign it back to me?
