### ISSUE TITLE
Disable facility cover image if there is no image selected by the user

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9110]
**Describe the bug**

When the user clicks the "Submit" button without selecting an image, the pop-up closes unexpectedly.

**To Reproduce**

1. click on view facility button in any card
2. Click on "Edit Cover Image" to open the image selection pop-up.
3. Click the Save button without selecting an image.

**Expected behavior**

- [ ] The Save button should be disabled if the user has not selected a cover image, preventing submission until an image is chosen.

**Screenshots**

![Image](https://github.com/user-attachments/assets/3f3f1a3c-571a-4354-ba98-f69e9900d3af)

**Comment by Srayash** [comment]
Can I work on this?
