### ISSUE TITLE
UI enhancements to the login page

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#9112]
![Image](https://github.com/user-attachments/assets/d73c2c63-825b-451e-aff7-8fd5292c5d6e)

1. If the gradient icon logo does not look good on the background, use the white version of the logo.

![Image](https://github.com/user-attachments/assets/41258b6f-1e45-456d-9240-b621b47f62a5)
2. Clicking on an input fields displaces it by a pixel (due to getting a border). Fix that.
3. Add a hover state to the login button, currently it does not respond to it.

**Comment by Rishith25** [comment]
@shivankacker I want to work on this?
