### ISSUE TITLE
Page Not Found Issue After Discharging a Patient From Care

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#9114]
**Describe the bug**
When a patient is discharged from care, then the user is being redirected to **not-found** page instead of previous list of patients page

**To Reproduce**

1. Go to '/facilty'
2. Click on view patients
3. Select any patient with consulation
4. Click on manage patient and select discharge from care
5. See error

**Expected behavior**
User should be redirected to a functional page after a patient is being discharged

**Screen recording**

https://github.com/user-attachments/assets/f2bb6a76-4553-4711-9171-2c073305f42a

**Desktop:**

- OS: Windows
- Browser: Chrome
- Version: Latest

**Comment by nithish1018** [comment]
@rithviknishad @Jacobjeevan I'd like to work on this issue

**Comment by rithviknishad** [comment]
Closing as moved to https://github.com/ohcnetwork/care/issues/2597
