### ISSUE TITLE
Sample Test Details page ui updation

### ISSUE THREAD

**Issue by modamaan** [coronasafe/care_fe#9120]
**Describe the bug**
Sample Test Details page ui updation

**To Reproduce**

1. Go to 'Sample Test button on sidebar'
2. Click on 'click any Sample Details button from thre card'
3. See error

**Expected behavior**
UI that's clean and easy to read

**Screenshots**
![Image](https://github.com/user-attachments/assets/199b27c6-dfc9-4a4f-806f-4c6b76511b3b)

i would like to change like this
![Image](https://github.com/user-attachments/assets/f577d836-4534-4282-87be-3d7c99f8bf2e)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [130.0.6723.117]

**Comment by modamaan** [comment]
@Ashesh3 @Jacobjeevan i would like to work on this

**Comment by modamaan** [comment]
@Jacobjeevan   Can I make updates to the SampleDetails.tsx component

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) Can I make updates to the SampleDetails.tsx component

I don't see why not 👍
