### ISSUE TITLE
Modify the bed capacity pop-up when the dropdown options are going to exhaust

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9121]
**Describe the bug**

- [ ] When only one bed type capacity is available to select, clicking the "Save Bed Capacity" button does not close the pop-up as expected.
- [ ] When clicking the "Add Bed" button on the facility detail page for a facility that already has all bed types added, the pop-up enters an infinite loading state.

**To Reproduce**

1. Navigate to the facility details page by clicking "View Facility."
2. Add all bed types except one, and attempt to replicate the issue.
3. See error

**Expected behavior**

- [ ] After clicking the "Save Bed Capacity" button, the pop-up should close in all cases once the data is saved.
- [ ] When no bed types are available to select, the "Add Bed Capacity" button should either be disabled with a tooltip indicating no options are available or should open the pop-up correctly to display the unavailability of bed types.

**Screenshots**

![Image](https://github.com/user-attachments/assets/77912036-f46a-4b68-abe2-30f1b4822b26)
![Image](https://github.com/user-attachments/assets/f0546584-9b83-436c-9046-90dafec31c29)

**Comment by AdityaJ2305** [comment]
Hey @nihal467  I would like to work on this issue . Could you assign it to me ?
