### ISSUE TITLE
UI enhancements to Consultation Update Details Page

### ISSUE THREAD

**Issue by Sunilsubba** [coronasafe/care_fe#9124]
**Is your feature request related to a problem? Please describe.**
After a colon symbol ":," a gap is missing in the highlighted texts, and some words are misaligned. 

**Describe the solution you'd like**
Put the data in better format, which is easier for the user to quickly understand. 

""Steps to reproduce**
1. click on the provided link
2. use credentials (username: state_admin123, password: Lilo@123)

[https://care.ohc.network/facility/4b776ceb-5663-4821-9ee1-19b56b3ca005/patient/4e78fdce-5146-48fa-acb0-6591772916af/consultation/8583684c-91f0-41a9-aa55-721c7f0bbd7e/daily-rounds/3bb23d52-393b-4768-8d77-1a4801e6b971](url)

![Image](https://github.com/user-attachments/assets/7f743f94-3e33-4c5f-80c4-f844a74c2b31)

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.

**Comment by Jacobjeevan** [comment]
I'd assume we are keeping this page @rithviknishad, might as well do a slight rework right, more in line with the new designs? 🤔

**Comment by AdityaJ2305** [comment]
Hey @Jacobjeevan, I noticed there’s already an issue for this: https://github.com/ohcnetwork/care_fe/issues/9067. Should we close this issue? Also, can I close my PR for the same? Just checked that.

**Comment by Jacobjeevan** [comment]
> Hey [@Jacobjeevan](https://github.com/Jacobjeevan), I noticed there’s already an issue for this: [#9067](https://github.com/ohcnetwork/care_fe/issues/9067). Should we close this issue? Also, can I close my PR for the same? Just checked that.

Yea 👍 

Closing as duplicate.

@ANIR1604
