### ISSUE TITLE
Year Of Birth Field Validation Condition in Patient transfer form is not working as expected

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9132]
**Describe the bug**

The "Year of Birth" field in the Patient Transfer form triggers an error check with each user input. This behavior is not aligned with the expected workflow.

**To Reproduce**

1. Navigate to the Patient tab.
2. Click on Add Patient.
3. Enter +919999999999 in the Phone Number field.
4. In the transfer pop-up that appears, click the green button.
5. In the next pop-up, enter the Year of Birth.
6. Observe the validation error triggered with each keystroke.

**Expected behavior**

Validation should only occur when the input field is out of focus or after the user has completed their entry.

**Screenshots**

![Image](https://github.com/user-attachments/assets/d97d7915-5266-4955-9b1f-d0743856f81d)

**Comment by Muppasanipraneeth** [comment]
can i work on this

**Comment by AdityaJ2305** [comment]
Hey @Muppasanipraneeth, apologies for missing your comment earlier. I’ve already started working on this issue and pushed a PR for it. Feel free to take up another one.
Thanks!
