### ISSUE TITLE
Camera Preset Not Resetting to Defined Position on Re-selection

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9135]
**Describe the bug**

When selecting a preset in the camera feed on the patient consultation page, manually adjusting the camera position, and then clicking on the same preset again, the camera does not reset to the preset location as expected.

**To Reproduce**

1. Navigate to the Patient tab.
2. Search for the patient "Gigin" and click on their card.
3. Go to the Feed page and set a camera preset.
4. Manually move the camera to a different position.
5. Click on the same preset again.
6. Observe the issue.

**Expected behavior**

Clicking on the same preset should reset the camera feed to the preset's defined position.

**Screenshots**

![Image](https://github.com/user-attachments/assets/14d7be1e-c6d2-413f-9347-ec0636c63f33)

**Comment by AdityaJ2305** [comment]
Hey @nihal467 , Let me try if I can solve this issue

**Comment by AdityaJ2305** [comment]
@nihal Unable to find patient with name `Gigin` 
![Image](https://github.com/user-attachments/assets/17ee75c9-8b3a-42bb-bb42-4f7798465f2b)

**Comment by nihal467** [comment]
@AdityaJ2305 you can create a patient with camera feed to replicate the bug

**Comment by AdityaJ2305** [comment]
> [@AdityaJ2305](https://github.com/AdityaJ2305) you can create a patient with camera feed to replicate the bug

sure, but how can I find feed page on Patient dashboard ?

**Comment by AdityaJ2305** [comment]
Hey @nihal , Let someone else take up this issue I don't think I will be able to solve this issue on time as it is `P1` issue
Thanks
