### ISSUE TITLE
Patient created despite having numeric values in name

### ISSUE THREAD

**Issue by Tanuj1718** [coronasafe/care_fe#9143]
**Describe the bug**
Patient can be created despite having wrong name (numeric values in the name e.g. 1234hh)

**To Reproduce**

1. Go to [https://care.ohc.network/patients](url)
2. Click on 'Add Patient'
3. Fill the details (Put numbers in name).
4. Create Patient.

**Expected behavior**
There should not be any numeric values in the name. If it is, then the patient should not be created.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.

**Comment by Tanuj1718** [comment]
@nihal467 @rithviknishad I would like to work on this if it get approved. Please assign it to me.

**Comment by Tanuj1718** [comment]
> I would like work on this, if that's okay.

Sorry @ANIR1604 , but I am working on this issue.

**Comment by vigneshhari** [comment]
As per FHIR Spec, any string can be used as a patient name, some countries allow names with numbers to exist legally, we cannot create this validation. @rithviknishad close this issue and all related issues.

**Comment by Tanuj1718** [comment]
> As per FHIR Spec, any string can be used as a patient name, some countries allow names with numbers to exist legally, we cannot create this validation. [@rithviknishad](https://github.com/rithviknishad) close this issue and all related issues.

Thank you @vigneshhari for the clarification. Got to know a new thing.
