### ISSUE TITLE
fix the responsive ness

### ISSUE THREAD

**Issue by gurramkarthiknetha** [coronasafe/care_fe#9156]
![Image](https://github.com/user-attachments/assets/1162b180-7a38-4d0f-a3ba-e1fadb7ebc79)
![Image](https://github.com/user-attachments/assets/ab770620-1ab9-4cce-b28c-ff7b6cbdd93e)
in the above pic the header is not responsive
![Image](https://github.com/user-attachments/assets/b9780d0a-2b92-4310-b495-6a17ff64d6a4)
in the above pic the red button and green outlined button are collapsed 
and the three buttons are not good at down the 3rd button should be the center.
Like this there are many issues i want to work on this issues .
assign this issue to me i will fix.

**Comment by Jacobjeevan** [comment]
For the first two screenshots, I'm not seeing the issue there 🤔 

Can you specify what other issues you have come across? @gurramkarthiknetha

**Comment by gurramkarthiknetha** [comment]
> For the first two screenshots, I'm not seeing the issue there 🤔
> 
> Can you specify what other issues you have come across? [@gurramkarthiknetha](https://github.com/gurramkarthiknetha)

the header is not responsive the export button is missing in medium divices .
and the red button and the green outline button is collapsed.
like this the website is not perfectly responsive i want fix this issues

**Comment by Jacobjeevan** [comment]
> the header is not responsive the export button is missing in medium divices . and the red button and the green outline button is collapsed. 

Hmm, export button is visible for different widths on my end, but maybe a browser specific issue.

> like this the website is not perfectly responsive i want fix this issues

Well, this is a general statement, I was asking what specifically you have come across other than the ones mentioned above (also because we want to keep the scope small enough).

Assigning the issue anyways.

**Comment by AdityaJ2305** [comment]
Hey @Jacobjeevan, what’s the status of this issue? I noticed it has 3 closed PRs. Is it still an issue?

**Comment by Jacobjeevan** [comment]
@gurramkarthiknetha Are you still working on this? You would need to update the original PR.

**Comment by AdityaJ2305** [comment]
> Hey [@Jacobjeevan](https://github.com/Jacobjeevan), what’s the status of this issue? I noticed it has 3 closed PRs. Is it still an issue?

@Jacobjeevan, I don't think it is an issue. I can't see it in my browser

**Comment by Jacobjeevan** [comment]
@gurramkarthiknetha In what browser are you seeing this issue? Are you still working on this, since you closed the PR? If not, I can assign to Aditya.

**Comment by gurramkarthiknetha** [comment]
> [@gurramkarthiknetha](https://github.com/gurramkarthiknetha) In what browser are you seeing this issue? Are you still working on this, since you closed the PR? If not, I can assign to Aditya.

i am using chrome browser
iam working on this issue i will keep pr tonight

**Comment by AdityaJ2305** [comment]
Hey @gurramkarthiknetha , can you share the constraints you're seeing on Chrome for this view?

**Comment by gurramkarthiknetha** [comment]
> Hey [@gurramkarthiknetha](https://github.com/gurramkarthiknetha) , can you share the constraints you're seeing on Chrome for this view?

> ![Image](https://github.com/user-attachments/assets/1162b180-7a38-4d0f-a3ba-e1fadb7ebc79) ![Image](https://github.com/user-attachments/assets/ab770620-1ab9-4cce-b28c-ff7b6cbdd93e) in the above pic the header is not responsive ![Image](https://github.com/user-attachments/assets/b9780d0a-2b92-4310-b495-6a17ff64d6a4) in the above pic the red button and green outlined button are collapsed and the three buttons are not good at down the 3rd button should be the center. Like this there are many issues i want to work on this issues . assign this issue to me i will fix.

**Comment by gurramkarthiknetha** [comment]
> Hey [@gurramkarthiknetha](https://github.com/gurramkarthiknetha) , can you share the constraints you're seeing on Chrome for this view?

The issue was fixed . I think someone fixed it during that time as it wasn't responsive before.

**Comment by AdityaJ2305** [comment]
@gurramkarthiknetha , my bad I am talking about this 👇

<img width="662" alt="Image" src="https://github.com/user-attachments/assets/905e85de-6abc-4472-a441-83e94a4523fc" />

**Comment by gurramkarthiknetha** [comment]
now also some are not responsive like this buttons are upand downs
<img width="720" alt="Image" src="https://github.com/user-attachments/assets/e536c88c-85b7-490c-b0df-faa845b3026f" />

**Comment by AdityaJ2305** [comment]
> now also some are not responsive like this buttons are upand downs <img alt="Image" width="720" src="https://private-user-images.githubusercontent.com/167804249/395662696-e536c88c-85b7-490c-b0df-faa845b3026f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMTUyMzIsIm5iZiI6MTczNDExNDkzMiwicGF0aCI6Ii8xNjc4MDQyNDkvMzk1NjYyNjk2LWU1MzZjODhjLTg1YjctNDkwYy1iMGRmLWZhYTg0NWIzMDI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QxODM1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDVlNjliYmI1ZDYyY2UxN2I2YTJmZTIxOTI3MzQ5MTIwYjA3N2E3MGQwOGM1NTk2ZmE1MDA0MzQxOWE2YjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wpGMMJ_-GvmLAyiFREkwmbgN_YkdGfAEOOcpvt65gmI">

I think It would be fixed in this https://github.com/ohcnetwork/care_fe/issues/7316
cc: @Jacobjeevan

**Comment by gurramkarthiknetha** [comment]
> > now also some are not responsive like this buttons are upand downs <img alt="Image" width="720" src="https://private-user-images.githubusercontent.com/167804249/395662696-e536c88c-85b7-490c-b0df-faa845b3026f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMTUyMzIsIm5iZiI6MTczNDExNDkzMiwicGF0aCI6Ii8xNjc4MDQyNDkvMzk1NjYyNjk2LWU1MzZjODhjLTg1YjctNDkwYy1iMGRmLWZhYTg0NWIzMDI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QxODM1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDVlNjliYmI1ZDYyY2UxN2I2YTJmZTIxOTI3MzQ5MTIwYjA3N2E3MGQwOGM1NTk2ZmE1MDA0MzQxOWE2YjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wpGMMJ_-GvmLAyiFREkwmbgN_YkdGfAEOOcpvt65gmI">
> 
> I think It would be fixed in this [#7316](https://github.com/ohcnetwork/care_fe/issues/7316) cc: [@Jacobjeevan](https://github.com/Jacobjeevan)

ya ya
I think i am too late

**Comment by gurramkarthiknetha** [comment]
also <img width="808" alt="Image" src="https://github.com/user-attachments/assets/748b30bc-cb53-4127-943a-de92482456b3" />
this is not responsive the buttons in assets are ups and down

**Comment by gurramkarthiknetha** [comment]
> > now also some are not responsive like this buttons are upand downs <img alt="Image" width="720" src="https://private-user-images.githubusercontent.com/167804249/395662696-e536c88c-85b7-490c-b0df-faa845b3026f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMTUyMzIsIm5iZiI6MTczNDExNDkzMiwicGF0aCI6Ii8xNjc4MDQyNDkvMzk1NjYyNjk2LWU1MzZjODhjLTg1YjctNDkwYy1iMGRmLWZhYTg0NWIzMDI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QxODM1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDVlNjliYmI1ZDYyY2UxN2I2YTJmZTIxOTI3MzQ5MTIwYjA3N2E3MGQwOGM1NTk2ZmE1MDA0MzQxOWE2YjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wpGMMJ_-GvmLAyiFREkwmbgN_YkdGfAEOOcpvt65gmI">
> 
> I think It would be fixed in this [#7316](https://github.com/ohcnetwork/care_fe/issues/7316) cc: [@Jacobjeevan](https://github.com/Jacobjeevan)

shall i make remaining responsiveness issues

**Comment by gurramkarthiknetha** [comment]
<img width="1406" alt="Image" src="https://github.com/user-attachments/assets/9583e67d-8219-4d18-8dee-a709961747c6" />
this too

**Comment by AdityaJ2305** [comment]
Hey @Jacobjeevan , Could you please have a look into this issue ?

**Comment by Jacobjeevan** [comment]
A lot of the mentioned items of this list is currently being redesigned/reworked, so closing this.
