### ISSUE TITLE
Support to import `Assets` from JSON file

### ISSUE THREAD

**Issue by pooranjoyb** [coronasafe/care_fe#9171]
**Is your feature request related to a problem? Please describe.**
I noticed this thing in the application that we are exporting the Assets in either `json` or `csv/xlsx`, however when we wanna import the **Assets** to any particular Facility, we are just taking care of `csv/xlsx` which is a serious thing to look at otherwise it wouldn't make any sense to export the Assets in the JSON format (like that won't be used anywhere I guess).

**Describe the solution you'd like**
We should add a feature to handle `JSON` Asset Imports too. Similar to what we do for `csvs/xlsx` imports.

**Scenario where this can be used :** 
- Say some Organization has some bulk of assets that are shifted to another Organization.
- In such case the Organization should also be able to take care of the `JSON` asset import/export as well.
- This will eventually increase the flexibility of handing data for assets.

**Additional context**

![Image](https://github.com/user-attachments/assets/984812e3-859c-40fc-aa7f-4d208bfd520e)

#### Please have a look on this and let me know if I can work on this issue :) Thanks in Advance <3 @Jacobjeevan

**Comment by pooranjoyb** [comment]
@Jacobjeevan @rithviknishad any thoughts on this?

**Comment by Jacobjeevan** [comment]
@pooranjoyb Hmm, there was some discussion about adding extra functionality with JSON a while back, but was ultimately rejected as the existing functionality itself was an edge use case scenario (the feature isn't used widely). So, let's not do this for now.

**Comment by pooranjoyb** [comment]
Thanks for the clarification! Will look for more valuable contribution <3 @Jacobjeevan
