### ISSUE TITLE
Search Icon Overlay issue in Sort By Dropdown Menu

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#9174]
**Describe the bug**
The search icon is overlayed on top of dropdown menu cards

**To Reproduce**

1. Go to '/patients'
2. Click on **Sort By**
3. See error

**Expected behavior**
Search icon shouldn't overlay on top of other components.

**Screenshots**

![Image](https://github.com/user-attachments/assets/d7b41e80-4428-4afb-8bfe-e726afe2ccfa)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment]
@Jacobjeevan Can I resolve this in my existing [PR](https://github.com/ohcnetwork/care_fe/pull/9172)?

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan Can I resolve this in my existing [PR](https://github.com/ohcnetwork/care_fe/pull/9172)?

Yea 👍🏾
