### ISSUE TITLE
UI enhancement to Sample Test History

### ISSUE THREAD

**Issue by Keerthilochankumar** [coronasafe/care_fe#9175]
**Describe the bug**
   The components in the Sample Test History are too close and it is hard to differentiate them from one another due to a lack of space 

**To Reproduce**

1. Go to Sample test
2. Click on Sample Details of any Patient
3. Scroll down to Sample Test History

**Expected behavior**
    There should be some space from one test component  to other 
**Screenshots**
![Image](https://github.com/user-attachments/assets/4a9d9ac7-030e-4d62-878d-c1407eddc291)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Keerthilochankumar** [comment]
I'd like to work on this issue

**Comment by Jacobjeevan** [comment]
There's an issue/PR (#9120) open regarding modifying the Sample test details page (so far it doesn't touch with Sample test history, so you should be fine, but keep an eye out).
