### ISSUE TITLE
Upgrade SheetJS to solve vulnerability to Regular Expression Denial of Service (ReDoS).

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#9183]
Follow https://docs.sheetjs.com/docs/getting-started/installation/nodejs to switch from npm to sheetjs cdn, for the current implementation, potentially plan for moving out of sheetjs

**Comment by Tanuj1718** [comment]
@gigincg can you please explain what we are planning to do?

**Comment by gigincg** [comment]
@Tanuj1718 please read the specified link. We are hoping to solve the outdated dependency being used in Care

**Comment by noufalrahim** [comment]
@rithviknishad  Can u assign this to me
