### ISSUE TITLE
Unable to save form for patient details

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#9187]
**Describe the bug**
When trying to save patient details, I am getting "invalid name" error on the address field. Everything looks okay to me.

**To Reproduce**
- Visit https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/update
- Try to make updates
- Save
- Nothing happens, scroll up, see error.

**Expected behavior**
The patient details should be saved

**Screenshots**
![Image](https://github.com/user-attachments/assets/7beb7b7d-e73b-459a-8dd3-ce142609f77e)

**Comment by Jacobjeevan** [comment]
@shivankacker Rithvik's PR #9177 takes care of it 👍

**Comment by AdityaJ2305** [comment]
@shivankacker I would like to work on this issue. Just let me know if it is open for contribution 

cc: @Jacobjeevan

**Comment by shivankacker** [comment]
@Jacobjeevan cool, closing as duplicate
