### ISSUE TITLE
Enhance Discussion Notes Chat History with Infinite Scrolling or Better Navigation Solution

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9188]
**Describe the bug**

When scrolling from the bottom to the top of a discussion with 20 chat entries in the  any "Discussion Notes" section, the page reloads unexpectedly after reaching the 15th chat. This forces the user to start scrolling from the bottom again, disrupting the navigation experience.

**To Reproduce**

1. Navigate to the Patient tab and select any patient card.
2. Click on the Discussion Notes section.
3. Add 20 chat messages.
4. Attempt to scroll from the bottom to the top of the chat history.
5. See error

**Expected behavior**

The user should be able to smoothly scroll from the bottom to the top of the chat history without the page reloading or resetting the scroll position.

**Screenshots**

![Image](https://github.com/user-attachments/assets/357ead85-297e-47d2-b343-e22236bfd751)

**Comment by nithish1018** [comment]
Hey @nihal467 I'd like to work on this issue

**Comment by JavidSumra** [comment]
Hey @nihal467 I would like to work on this issue

**Comment by JavidSumra** [comment]
Hey @nihal467 same issue persist with Discussion Notes shall i fix that as well?

**Comment by nihal467** [comment]
Yup fix it for both @JavidSumra

**Comment by JavidSumra** [comment]
@nihal467 can you please test the PR #9190
