### ISSUE TITLE
Unnecessary API Calls in Assets Update Page

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#9189]
**Describe the bug**
In Assets update page, the form is allowing users to raise a PUT API call even when there's no change in the data, the same thing is present in in Service History update too

**To Reproduce**

1. Go to '/Assets'
2. Click on any asset
3. Select Update
4. Scroll Down and choose update without making any change
5. See Error

**Expected behavior**

Update Button should be deactived when there's no change in the data

**Screenshots**

https://github.com/user-attachments/assets/317eb18d-a5be-4a38-a74d-49e9c9b00e30

**Desktop**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment]
@Jacobjeevan I'd like to work on this issue

**Comment by Jacobjeevan** [comment]
Go ahead and see if you can convert the form in AssetCreate to use Form component (like in CreatePrescriptionForm.tsx) @nithish1018

**Comment by rajku-dev** [comment]
Hi @Jacobjeevan , I would like to work on this issue.

**Comment by Jacobjeevan** [comment]
> Hi @Jacobjeevan , I would like to work on this issue.

I see you have opened a PR, but please do not work on issues that have already been assigned to someone else.

Moreover, your PR doesn't make use of the Form component as mentioned above.

@nithish1018 how far along are you on this issue?

**Comment by nithish1018** [comment]
> > Hi [@Jacobjeevan](https://github.com/Jacobjeevan) , I would like to work on this issue.
> 
> I see you have opened a PR, but please do not work on issues that have already been assigned to someone else.
> 
> Moreover, your PR doesn't make use of the Form component as mentioned above.
> 
> [@nithish1018](https://github.com/nithish1018) how far along are you on this issue?

I haven't started working on that issue, it's ok if someone wants to take it up

**Comment by Jacobjeevan** [comment]
Ok, reassigning to @rajku-dev since there's a PR open (but please don't do this again, thanks).

**Comment by Jacobjeevan** [comment]
There's a PR open (#8956) that modified Form component to have a dirty state, so that would take care of the original issue, once we switch this page to use form component.

**Comment by rajku-dev** [comment]
> There's a PR open ([#8956](https://github.com/ohcnetwork/care_fe/pull/8956)) that modified Form component to have a dirty state, so that would take care of the original issue, once we switch this page to use form component.

I'm sorry, didn't knew about that since i am new to open source.
talking about issue, i have solved the problem but by not using Form component, but for a future safe code, I would implement wrapping the assetCreate form with Form Component.

**Comment by rajku-dev** [comment]
Hi @Jacobjeevan , I have completed wrapping the form inside `AssetCreate` Page with `Form` component, making customary changes in validators, submit handlers etc.. to fit for `Form` component, the UI is also working fine
Can I make a pull request now for review?

**Comment by Jacobjeevan** [comment]
> Hi [@Jacobjeevan](https://github.com/Jacobjeevan) , I have completed wrapping the form inside `AssetCreate` Page with `Form` component, making customary changes in validators, submit handlers etc.. to fit for `Form` component, the UI is also working fine Can I make a pull request now for review?

Yea, but make sure you are changing the existing PR request rather than opening a new one.

**Comment by rajku-dev** [comment]
@Jacobjeevan  I have updated #9192 with new commits.
Please review and let me know if further work has to be done.

https://github.com/user-attachments/assets/edd3ca22-613d-41c1-ab2d-7d60cb7c1b8d
