### ISSUE TITLE
Numeric values are not supporting on address field

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#9212]
**Describe the bug**
Numeric values are not supporting on address field. Showing validation message as "please enter valid name" 
**To Reproduce**

1. Go to patients
2. Click on add patient 
3. Fill up the registration form 
4. Enter numeric values on current address field
5. Submit the form

**Expected behavior**
Numeric values should be allowed on address field.

**Screenshots**
If applicable, add screenshots to help explain your problem.![image](https://github.com/user-attachments/assets/f2adde61-5cba-4db5-a499-086d798649cf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jacobjeevan** [comment]
#9177 solves the issue once it's merged upstream.
