### ISSUE TITLE
Update side navigation icons with new duotone design

### ISSUE THREAD

**Issue by vinutv** [coronasafe/care_fe#9216]
**Is your feature request related to a problem? Please describe.**
No issues with the current icons; this request is for a design enhancement.

**Describe the solution you’d like**
Replace the existing side navigation icons with redesigned duotone icons that align with the platform’s design system.

**Comment by vinutv** [comment]
![Image](https://github.com/user-attachments/assets/1219628e-a51a-43f5-9f2e-89e18a039dcd)

**Comment by Rengoku1926** [comment]
do you have any svg files for these logos bcz current page is having a green tone logo

**Comment by akshatsh0610** [comment]
As the theme is green and white we can use the combination of these two colors in icons.

**Comment by anaghathedesigner** [comment]
![Image](https://github.com/user-attachments/assets/8257c78d-6e72-414e-89ef-8073b638443e)
![Image](https://github.com/user-attachments/assets/b29202b3-753e-4e60-ad74-5c4bcdc43ccc)
![Image](https://github.com/user-attachments/assets/60dad7c4-34df-4d94-8ac9-dacc73594c26)
![Image](https://github.com/user-attachments/assets/30c1de7e-43d4-4ddf-9219-4a6bedd331dc)
![Image](https://github.com/user-attachments/assets/32eecf62-f7f2-4356-948c-f3919f33241b)
![Image](https://github.com/user-attachments/assets/12ac8634-448e-412c-b55d-e0b80976b96b)
![Image](https://github.com/user-attachments/assets/7a65749a-5604-4593-b9ac-44fcdb779042)
![Image](https://github.com/user-attachments/assets/27403ea1-8696-4bc0-a533-e8996708f7a4)
![Image](https://github.com/user-attachments/assets/6f8359d0-a1fd-4ef5-8b0e-14c943e12edb)
![Image](https://github.com/user-attachments/assets/76267927-26fd-4635-a6fa-8d0a639b4dcc)
![Image](https://github.com/user-attachments/assets/80247d89-12bf-4e74-8528-b1489ae5cd4c)
![Image](https://github.com/user-attachments/assets/e7c27a47-79e9-45e1-9b99-e7e464f363ef)

**Comment by vinutv** [comment]
This folder contains the duotone icons used for the side navigation links. I have updated the Ambulance, Microscope, and Notice board icons by optimising them in Adobe Illustrator to reduce the number of paths. cc @anaghathedesigner  @bodhish 
[Sidenav-Icons-svg.zip](https://github.com/user-attachments/files/17990796/Sidenav-Icons-svg.zip)

**Comment by shivankacker** [comment]
@vinutv no icon for facility
@bodhish 

![Image](https://github.com/user-attachments/assets/b08114c3-9efc-4145-a7c7-ed388b66b631)

**Comment by vinutv** [comment]
[Sidenav-Icons-svg.zip](https://github.com/user-attachments/files/17994559/Sidenav-Icons-svg.zip)
Here is the updated folder containing icons for the facility. @shivankacker
