### ISSUE TITLE
Accept Special Character Input For Patient Name in the Patient registration form 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9217]
**Describe the bug**

When creating a patient with a name containing special characters like an apostrophe ('), such as " **Sam O'Brian** ", the name is saved as "  **Sam Obrain**  ". The issue arises because the startCase and toLower provided by lodash package implemented in the frontend removes special characters during formatting.

Context: The auto-capitalization package was introduced after feedback from users who often entered names with inconsistent capitalization.

**To Reproduce**

1. Go to patient tab
2. Click on add patient details button
3. Create a patient with the name " Sam O'Brian "
4. See error in the patient details page

**Expected behavior**

- [ ] The auto-formatting logic should only trigger after detecting a space and should capitalize the next letter in the patient registration form
- [ ] Special characters, such as apostrophes ('), should be preserved as they are an integral part of many names.

**Screenshots**

![Image](https://github.com/user-attachments/assets/818acda9-5a47-4d57-801a-042251316499)
![Image](https://github.com/user-attachments/assets/6092a61d-0851-4de2-b6cb-8f45d7f8dad2)

**Comment by rithviknishad** [comment]
Possibly would be fixed along with #9116

**Comment by Jacobjeevan** [comment]
> Possibly would be fixed along with [#9116](https://github.com/ohcnetwork/care_fe/pull/9116)

It will 👍  https://github.com/ohcnetwork/care_fe/blob/e0b6526c33e0f85aadd8f95b392b937b708f0040/src/Utils/utils.ts#L556 will split by hypens, apostrophe and periods, will capitalize accordingly.

**Comment by SwanandBhuskute** [comment]
@nihal467 can you check PR #9116 , in that now we are accepting any name entered, just with autoCapitalize: "words"
this will close this issue
I made multiple names, they are all accepting 'as it is' as our requirement

**Comment by Rustix69** [comment]
Can I work on this Issue, Plz assign it to me ...

**Comment by rithviknishad** [comment]
@ANIR1604 issue is already solved in the linked PR. Feel free to take up other open issues.
