### ISSUE TITLE
Thank you message pings user two times

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#9224]
![Image](https://github.com/user-attachments/assets/2cc4a3a3-1a3f-4378-bd4c-fa081e113d09)

Should only mention once

**Comment by JavidSumra** [comment]
Can you please assign it to me?

**Comment by Jeffrin2005** [comment]
@Jacobjeevan I have a doubt regarding this issue. Is this issue present in the GitHub repository of 'care_fe'?

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) I have a doubt regarding this issue. Is this issue present in the GitHub repository of 'care_fe'?

Yes, it's one of the github workflows (thank-you.yml).

Please note that issue had already been assigned in case you are interested in working on it.
