### ISSUE TITLE
Revamp Card UI in the Facilities Tab

### ISSUE THREAD

**Issue by 71203mayank** [coronasafe/care_fe#9232]
## **Current Issues**

The current card UI in the facilities tab has the following challenges:
1. **Misaligned elements** resulting in a cluttered appearance and uneven spacing.
2. **Disjointed navigation**, as links and buttons are scattered in two different locations.
3. **Lack of responsiveness**, leading to a poor user experience on smaller screens.

![Image](https://github.com/user-attachments/assets/2c837232-a733-4464-82a8-9788b27dbafd)

![Image](https://github.com/user-attachments/assets/8399a4ac-71c5-4c49-a2ba-7519ec35d79a)

![Image](https://github.com/user-attachments/assets/d64a0b76-ada8-490e-90ff-598b85b19fc0)

## **Proposed Enhancements**

To resolve the above issues, the following improvements are suggested:
1. **Component Grouping**: Organize the card elements into four distinct components (refer to the attached image) for better readability and structure.
2. **Consistent Design**: Ensure proper alignment and spacing across all elements.
3. **Responsive Layout**: Make the cards adaptable to smaller screens for an optimized mobile experience.

![Image](https://github.com/user-attachments/assets/61b6feae-0b32-44a9-bdf6-6d12b582636d)

## **Additional Improvements**

1. Introduced **icons for address and contact details** in the hospital description section for better visual presentation.
2. Grouped all **tags at the bottom-right corner**, ensuring uniform spacing and alignment.
3. Centralized all **clickable links at the bottom-left corner**, making navigation more intuitive.
4. Incorporated **spacing adjustments and alignments** to give the card a polished and professional look.

Suggested card design for standard screens:
![Image](https://github.com/user-attachments/assets/e64f30cb-03d6-4dfa-967a-d14ec3244f5d)

Suggested card design for smaller screens (mobile):
![Image](https://github.com/user-attachments/assets/b558b44a-5f32-45f8-83e1-6d96195c5330)

**Comment by 71203mayank** [comment]
If you would like to proceed with my proposed UI design, could you kindly assign this issue to me?

**Comment by ayushpatil2122** [comment]
assign this issue to me

**Comment by nihal467** [comment]
@bodhish @vinutv can you review this issue and comment your thoughts

**Comment by bodhish** [comment]
We are planning to remove the facility listing page in favour of a public facility index, it will have a quite different ux, let's not work on this as it's functional

**Comment by 71203mayank** [comment]
ok
