### ISSUE TITLE
Repositon calender and dropdown icon in the symptoms components

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9234]
**Describe the bug**

- [ ] The calendar and dropdown icons in the Symptoms component on the Consultation page are not positioned properly.

**To Reproduce**

1. Go to the Patient tab.
2. Open any active consultation page.
3. Click on Manage Patient, then select Edit Consultation.

**Expected behavior**

- [ ] Align the dropdown icons properly in the center.
- [ ] Add spacing between the date placeholder and the icon for better clarity.

**Screenshots**

![Image](https://github.com/user-attachments/assets/8fecd5bf-1ffa-427d-b176-e1e8c6e4af58)

**Comment by DonXavierdev** [comment]
I would like to work on this.Please assign this to me.

**Comment by JavidSumra** [comment]
Hey @nihal467 I think this issue is already addressed in #8998

**Comment by nihal467** [comment]
Its a duplicate issue , closing it
