### ISSUE TITLE
Disable Edit Button for Discharge Patient in patient details page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9239]
**Describe the bug**

On the Discharged Patients page, the section-wise edit buttons on the Patient Details page are not clickable but are not grayed out, which is inconsistent with the existing design standards.

**To Reproduce**

1. Navigate to the Patient tab.
2. Switch to the Discharged tab and click on any patient card.
3. Open the Patient Details page.
4. Observe the inconsistency where the non-clickable edit buttons are not grayed out.

**Expected behavior**

The edit buttons in the sections of the Patient Details page should be grayed out to indicate they are non-clickable.

**Screenshots**

![Image](https://github.com/user-attachments/assets/7934dd9f-feb5-46aa-bb56-7e56080a67f0)

**Comment by AdityaJ2305** [comment]
Hey @nihal467 , I would like to work on this issue
