### ISSUE TITLE
Change Date of Birth to Year of Birth on Patient Details Page when DOB is Missing

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9241]
**Describe the bug**

When a patient's Date of Birth (DOB) is not provided but their age is, the system currently displays "Invalid Date" along with the age in the DOB field in the patient details page

**To Reproduce**

1. Navigate to the Patient tab and open any active consultation.
2. Go to the Patient Details page.
3. Click on Update Details and enter only the age of the patient.
4. Return to the Patient Details page.
5. Observe the "Invalid Date" error in the DOB field.

**Expected behavior**

- [ ] If only the age is available, change the Date of Birth heading to Year of Birth.
- [ ] Display the calculated year along with the age, similar to how DOB data is currently displayed.

**Screenshots**

![Image](https://github.com/user-attachments/assets/6bb0e264-9eee-4d4d-be7e-2203a4ea28ae)

**Comment by AdityaJ2305** [comment]
Hey @nihal467 , I would like to work on this issue
