### ISSUE TITLE
Add Edit Button to the Immunisation Section of Patient Details Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9243]
**Describe the bug**

- [ ] currently the immunisation section of patient details page is not having a edit button similar like the other section of the patient detail page, which is making it inconsistent

**To Reproduce**

1. Go to patient tab
2. Open any activity consultation
3. Open the patient detail page and go the immunisation section
5. See error

**Expected behavior**

- [ ] Add Edit button in immunisation section of patient details page

**Screenshots**

![Image](https://github.com/user-attachments/assets/de8b09df-254e-4c61-a1b4-e260ee3adb59)

![Image](https://github.com/user-attachments/assets/42346327-4da3-4b3a-8931-45eea5a5d469)

**Comment by DonXavierdev** [comment]
Hey @nihal467 , I would like to work on this issue
