### ISSUE TITLE
Handle the Volunteer Contact Number in the patient details page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9244]
**Describe the bug**

- [ ] The emergency contact field does not display the volunteer's primary phone number.
- [ ] When selecting the volunteer contact option in the navigation bar, both "Volunteer Contact" and "Insurance Details" appear as selected simultaneously.

**To Reproduce**

1. Go to patient details page
2. Assign a volunteer to the patient
3. See error

**Expected behavior**

- [ ] The emergency contact field should display the volunteer's primary phone number correctly.
- [ ] Selecting "Volunteer Contact" in the navigation bar should ensure only that option is highlighted, without affecting "Insurance Details."
**Screenshots**

![Image](https://github.com/user-attachments/assets/5e34db51-7174-44d7-b435-efb7328e50d4)

**Comment by Rishith25** [comment]
I want to work on this. Assign this to me

**Comment by AdityaJ2305** [comment]
Hey @Rishith25 , Have you checked if the `emergency_number`  for volunteer is coming from backend or not ?

**Comment by Rishith25** [comment]
@Jacobjeevan @nihal467 The Emergency Contact number should be fetched from backend and currently it is missing hence NO contact number is displayed 
I will raise the issue in the backend.

**Comment by nihal467** [comment]
@Rishith25 https://github.com/ohcnetwork/care/issues/2623

**Comment by bitwizard25** [comment]
@nihal467  is this issues still open

**Comment by ayushsaini7717** [comment]
@Jacobjeevan can i work on this issue.

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) can i work on this issue.

Issue is already assigned to someone else, and they have an open PR 👍

**Comment by Jacobjeevan** [comment]
@Rishith25 What's the status here? As Vignesh mentioned, you should add another serializer instead of modifying the existing one.

**Comment by Rishith25** [comment]
@Jacobjeevan I have done the changes can you look into it.
