### ISSUE TITLE
Incorrect Button Label on Patient Info Page for Live Patients

### ISSUE THREAD

**Issue by AdityaJ2305** [coronasafe/care_fe#9249]
**Describe the bug**
For live patients on the **Patient Info** page, the button labeled **"Discharge Summary"** generates a summary with discharge related data as N/A . The button's label is incorrect for live patients and should instead display **"Patient Summary."**

**To Reproduce**

1. Go to `Patient`  Tab 
2. Click on any Active Consultation Patient
3. Click on `Manage Patient` dropdown

**Expected behavior**  
- For live patients, the button should be labeled **"Patient Summary."** Clicking it should generate a relevant summary for live patients.  
- For discharged patients, the button should remain labeled **"Discharge Summary,"** and its current behaviour should be unchanged.  
![Image](https://github.com/user-attachments/assets/d8d67bf9-4f14-432f-9927-bd6b58c92df8)

**Screenshots** (Current)
![Image](https://github.com/user-attachments/assets/322299cd-2863-4c2a-a8cf-8057766fd28a)

**Desktop (please complete the following information):**

- Browser [e.g. chrome]

**Additional context**
cc : @Jacobjeevan , I would like to work on this issue

**Comment by rithviknishad** [comment]
This is intended, as it shows a preview of the discharge summary before discharging. 
But maybe I guess the right label here would be "Preview Discharge Summary" instead when encounter is still live.

cc: @bodhish

**Comment by bodhish** [comment]
This is expected; lets not work on it now
