### ISSUE TITLE
Double Notification Error on filtering the Assets by Facility

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9261]
**Describe the bug**
When filtering the Assets by Facility,  it shows a notification error  'No Facility matches the given query' twice when Facility is not matched

**To Reproduce**

1. Go to '/assets'
2. Click on 'Advanced Filters'
3. Scroll down to 'Facility' and Select any Facility from dropdown

**Expected behavior**
Notification Error should show up only once

**Demonstration**
https://github.com/user-attachments/assets/de6ec10a-f674-4b6a-98f7-7fb3fd9dc77d

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser - Chrome
- Version 131.0.6778.86 (Official Build) (64-bit)

**Comment by rajku-dev** [comment]
I want to work on this issue. @nihal467 @Jacobjeevan @rithviknishad

**Comment by Rustix69** [comment]
I would like work on this, if that's okay. I had already solved the Issue should I raise the PR ?

**Comment by Jacobjeevan** [comment]
This occurs on the test platform only due to broken data that was accumulated over time (i.e. asset list refers to a specific facility, however that facility no longer exists).

So, it's not an issue that needs to be resolved. Closing as not planned.

**Comment by rajku-dev** [comment]
> This occurs on the test platform only due to broken data that was accumulated over time (i.e. asset list refers to a specific facility, however that facility no longer exists).
> 
> So, it's not an issue that needs to be resolved. Closing as not planned.

@Jacobjeevan its alright👍
