### ISSUE TITLE
Clear button is active when no input is selected in dropdown

### ISSUE THREAD

**Issue by harshit078** [coronasafe/care_fe#9263]
**Describe the bug**

AutoComplete dropdown clear-button state remains show always even when there are no selected field.  When clicked, it opens the dropdown and when the user clicks outside it then clears out.

**To Reproduce**

1. Go to Patients
2. Click on add a patient
3. When the prompt is open, the clear button is already present even when the user hasn't selected anything.

**Expected behavior**

- The clear button state shouldn't been shown when no input field is selected.

**Screenshots**

https://github.com/user-attachments/assets/a606cfde-a606-4d6e-9b72-290a3a325d61

**Desktop (please complete the following information):**

- OS: MacOS
- Browser - Chrome

**Comment by Rustix69** [comment]
I would like work on this, if that's okay.

**Comment by ayushpatil2122** [comment]
hey @ANIR1604  are you working on this issue if not i have solved this if you need any help please let me know else let me make a pr

**Comment by Rustix69** [comment]
Yes I am working on it and I will raise the PR tonight.

**Comment by ANIR1604** [comment]
> hey [@ANIR1604](https://github.com/ANIR1604) are you working on this issue if not i have solved this if you need any help please let me know else let me make a pr

Can you help me solve the Failed Cypress Tests .

**Comment by Rustix69** [comment]
> hey [@ANIR1604](https://github.com/ANIR1604) are you working on this issue if not i have solved this if you need any help please let me know else let me make a pr

Can you help me solve the Failed Cypress Tests .

**Comment by rithviknishad** [comment]
Completed via https://github.com/ohcnetwork/care_fe/commit/113ddddd5058a0bc8c160cd0dae1c6a59f9134e9
