### ISSUE TITLE
Duplicate network requests on patient details page

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#9269]
Patient home page:
duplicate requests to policy api
![Image](https://github.com/user-attachments/assets/c92ebbd3-0401-4f77-8db2-6fb1de24109b)

Encounters page:
duplicate requests for consultations list api
patient details api is called again
![Image](https://github.com/user-attachments/assets/dbe1ee59-2a1b-4e90-a030-506c4674255d)

Notes page:
doctor notes tab initial load calls the notes api twice
![Image](https://github.com/user-attachments/assets/c46ac978-9ddc-42d8-8fd8-50bd95a565de)

**Comment by Mahendar0701** [comment]
I want to work on this. Assign this to me

**Comment by Jacobjeevan** [comment]
@Rishith25 you already have a few on your plate, let's get those merged 👍  assigning to Mahendar.
