### ISSUE TITLE
Add "View Latest Consultation" Button on the Patient Details Page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9272]
**Is your feature request related to a problem? Please describe.**

- [ ] Currently, on the patient details page, to check the live consultation, you need to click on the encounter in the nav bar.

**Steps to Replicate**

1. Go to the Patient tab.
2. Click on any live patient card.
3. In the patient consultation page, click on the Patient Details page in the top right corner.
4. View the card. The button should be implemented. 

**Expected Behavior**

- [ ] Add a "View Latest Encounter" button with the primary color and effects similar to other buttons in the card.
- [ ] This button should be visible only for live patients.

**Screenshot**

![Image](https://github.com/user-attachments/assets/26363481-89de-454a-8447-84dc4ba68775)

**Comment by JavidSumra** [comment]
Hey @nihal467 can you please assign this issue to me?

**Comment by matinshaikh31** [comment]
can i work on it

**Comment by Srayash** [comment]
@JavidSumra Can I take this up, if its okay with you?

**Comment by JavidSumra** [comment]
> @JavidSumra Can I take this up, if its okay with you?
> 

I'm working on it @Srayash

**Comment by JavidSumra** [comment]
Hey @nihal467 is that ok if will redirect user on `Edit Consultation Page` on button click?
cc : @rithviknishad

**Comment by rithviknishad** [comment]
No, let's open the consultation dashboard page instead
