### ISSUE TITLE
Patients Files Upload Page is opening for discharged patients even though the permission is denied

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#9277]
**Describe the bug**

The Patient Files View/upload page is opening for discharged patients even when the error "Permission is Denied" is being shown

**To Reproduce**

1. Go to '/patients'
2. Click on Discharged
3. Open Any patient card
4. Click on View /  update patient files
5. See error

**Expected behavior**

- [ ] the patient files of a patient is allowed to be viewed even after they are discharged, users are not allowed to upload new ones after the discharge
- [ ] patient files access need to be checked, whether the user have correct permission to enter the page and view the existing file, if not restrict the redirection by showing a error notification

**Screen recording**

https://github.com/user-attachments/assets/554faaa2-5366-416f-82f2-3b0a79d89820

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment]
@Jacobjeevan @rithviknishad I'd like to work on this issue and raise an immediate PR

**Comment by ayushpatil2122** [comment]
hey can you assign this to me 
i just want to try

**Comment by Jacobjeevan** [comment]
@nihal467 This and Assign to a volunteer is also enabled for discharged patients. Both should be disabled here, right?  🤔

**Comment by Jacobjeevan** [comment]
Patient Files is being reworked (and the current page won't be relevant for patient files), so closing this for now.
