### ISSUE TITLE
Bookmark Icon Not Functioning Correctly for Important Notifications

### ISSUE THREAD

**Issue by Jeffrin2005** [coronasafe/care_fe#9305]
**Describe the bug**

Starred icon is visible but non-functional.
 When clicking the bookmark icon to tag an important notification, it redirects to the "Log Update" section instead of marking the notification.

**To Reproduce**

1. Go to 'Notification Tab'
2. Click on the bookmark icon
3. Observe that it does not mark the notification as important and navigates to another page instead

**Expected behavior**

The bookmark icon should be marked in red when a notification is tagged as important.

**Record Clip**

https://github.com/user-attachments/assets/5a8f2dd4-9585-4ba0-a2ff-90fef7f10de5

**Desktop (please complete the following information):**

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan I would like to work on this. Could you please assign it to me?

**Comment by Jacobjeevan** [comment]
That's not a bookmark icon, but rather patient log update icon (speaking of which, we might have to update the icon there 🤔 ).

As such, clicking on it should take to patient log update page - consultation/consultation:id/log_updates/log:id/critical_care. You can navigate it to by visiting a patient consultation page (click on any patient with consultation) and checking the log updates tab for events (and click on view details).

![Image](https://github.com/user-attachments/assets/23369583-5631-4537-a723-89094c4ef084)

**Comment by Jeffrin2005** [comment]
@Jacobjeevan 

Changes Made 

* Once the User clicks the Bookmark icon it turned out to Red 
* For persisting the State, used local Storage. 

https://github.com/user-attachments/assets/938e28ed-6e33-4c5d-a873-d688b7c1a55b

**Comment by Jeffrin2005** [comment]
@Jacobjeevan Please let me know if any further changes are required before PR.

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan)
> 
> Changes Made
> 
>     * Once the User clicks the Bookmark icon it turned out to Red
> 
>     * For persisting the State, used local Storage.
> 

👇 

> That's not a bookmark icon, but rather patient log update icon (speaking of which, we might have to update the icon there 🤔 ).
> 
> As such, clicking on it should take to patient log update page - consultation/consultation:id/log_updates/log:id/critical_care. You can navigate it to by visiting a patient consultation page (click on any patient with consultation) and checking the log updates tab for events (and click on view details).
> 
> ![Image](https://github.com/user-attachments/assets/23369583-5631-4537-a723-89094c4ef084)

**Comment by Jeffrin2005** [comment]
@Jacobjeevan 
Sorry for the misunderstanding. For confirmation, after clicking the "log update" icon, it should navigate to this page, right? But when we click the log update icon for each person in notifications tab, how do we know which person's details it corresponds to?

![Image](https://github.com/user-attachments/assets/db3d1b6b-fe4c-4875-9689-4573673a7bd0)

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) Sorry for the misunderstanding. For confirmation, after clicking the "log update" icon, it should navigate to this page, right? But when we click the log update icon for each person in notifications tab, how do we know which person's details it corresponds to?
> 

No, it should navigate to the log updates detail page; clicking on the view details button (check the screenshot I attached above) takes you to the relevant page. 

I looked into it, and it's a BE issue; the URL is technically accurate, however the log update Id stored and retrieved from BE is incorrect. I went ahead and opened a Backend [PR](https://github.com/ohcnetwork/care/pull/2641) to address it.
