### ISSUE TITLE
Unnecessary API Calls and Re-Renders on Patient Page

### ISSUE THREAD

**Issue by i0am0arunava** [coronasafe/care_fe#9308]
**Describe the bug**
Unnecessary API calls and re-rendering occur when entering the first digit into the PhoneNumber field. Additionally, the Patient page causes re-rendering when the search field is initially empty, and changing options also triggers a re-render.

**To Reproduce**

1. Go to the 'Facilities' page.
2. Then go to the 'Patient' page.
3. Open the network tab.
4. Put one digit inside the PhoneNumber field, change the option, or change the country code.
5. Notice in the network tab that an unnecessary API call is being made.

**Expected behavior**
For null values or when changing options, the API call should not be made. This is not expected behavior.

**Screenshots **
one digit input inside phonenuberfield
![Image](https://github.com/user-attachments/assets/8975fe41-2ca0-474c-9c47-611b8a5acfe5)

while changing option
![Image](https://github.com/user-attachments/assets/82cc2f75-aa81-44c7-91b9-43e86538824c)

while changiong country code
![Image](https://github.com/user-attachments/assets/79509272-0b89-45b2-bb61-5143efe5e611)

**Desktop (please complete the following information):**

**Desktop (please complete the following information):**

- OS: windows
- Browser chrome
- Version - latest

**Additional context**
go to the facility page then come to patient page to reproduce the issue

**Comment by i0am0arunava** [comment]
I would like to work on this @nihal467  @rithviknishad

**Comment by rithviknishad** [comment]
Superseded by #9400
