### ISSUE TITLE
Disable assign to volunteer button for discharged patient in patient details page

### ISSUE THREAD

**Issue by Mahendar0701** [coronasafe/care_fe#9310]
**Describe the bug**
Assign volunteer button is active for discharged patient.

**To Reproduce**

1. Go to 'Patients Tab'
2. Click on 'any dicharged patient'
3. See aasign to a volunteer button

**Expected behavior**
The assign to volunteer button should be disabled for discharged patient.

**Screenshots**
![Image](https://github.com/user-attachments/assets/48f1d9af-9516-40cd-aabe-51f0952b3651)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mahendar0701** [comment]
I want to work on this. Please assign this to me.

**Comment by Rustix69** [comment]
I had solved the issue. I would like work on this, if that's okay.

**Comment by Mahendar0701** [comment]
It is addressed in PR #9278
