### ISSUE TITLE
Update search UI in discharge patients page

### ISSUE THREAD

**Issue by Mahendar0701** [coronasafe/care_fe#9312]
**Is your feature request related to a problem? Please describe.**
Update search UI for Discharge Patients page like it was it was implemented in patients index page.

**Describe the solution you'd like**
Replace existing search UI in discharge patients page with smart search UI

Before
![Image](https://github.com/user-attachments/assets/fe037ba7-1c96-499e-a819-00b00096c483)

After
![Image](https://github.com/user-attachments/assets/35106220-a5c5-4114-8709-f15c58ef6220)

**Comment by Mahendar0701** [comment]
@Jacobjeevan @rithviknishad I want to work on this. Please assign this to me

**Comment by ayushsaini7717** [comment]
@Jacobjeevan can you assign this issue to me.

**Comment by Mahendar0701** [comment]
Hey @ayushsaini7717  It is already assigned to me. You can look for other issues.
