### ISSUE TITLE
Incorrect notification message on updating/assigning volunteer to a patient

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9316]
**Describe the bug**
- When assigning Volunteer to a patient (even for the first time), Notification says 'Volunteer unassigned successfuly' which is inappropriate.
- There is no option to unassign a volunteer 
- There is also a option to Assign volunteer to dead patients which seems inappropriate.
- Also there is typo in notification message i.e 'successfuly'

**To Reproduce**

1. Go to '/patients'
2. Click on any patient
3. Scroll down to 'Assign to a Volunteer' under Actions
4. Choose a Volunteer 
5. See Error

**Expected behavior**
- When assigning volunteer for the first time message should be 'Volunteer assigned successfully'.
- When updating the volunteer message should be 'Volunteer updated successfully'
- Also there should be a option (like a button) to unassign the current Volunteer and give appropriate notification message like 'Volunteer unassigned successfully'.

**Screenshots**
https://github.com/user-attachments/assets/f97f25bf-c4ad-46d1-9e53-e089f4b8ef65

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser - Chrome
- Version 131.0.6778.86 (Official Build) (64-bit)

**Additional context**

**Comment by rajku-dev** [comment]
I want to work on this issue @Jacobjeevan @rithviknishad @nihal467

**Comment by nithish1018** [comment]
> There is also a option to Assign volunteer to dead patients which seems inappropriate.

This will be fixed in #9278
