### ISSUE TITLE
bug: Wrong link in the login page

### ISSUE THREAD

**Issue by Tanuj1718** [coronasafe/care_fe#9321]
**Describe the bug**
Link in the authentication page is giving a 404 page.

**To Reproduce**

1. Go to [https://care.ohc.network/](url)
2. Click on 'Digital Public Goods' icon
3. You will reach to the 404 page

**Expected behavior**
Correct link should be https://www.digitalpublicgoods.net/r/care

https://github.com/user-attachments/assets/64d22f3e-cd02-4264-9ad3-bdd8f04ea1dc

**Desktop :**

- OS: MacOS
- Browser Chrome

**Comment by Tanuj1718** [comment]
@rithviknishad @bodhish  I would like to correct the URL if it gets approved. Please assign it to me.

**Comment by rithviknishad** [comment]
Thanks for finding that issue out!

Here's the URL: https://www.digitalpublicgoods.net/r/care

**Comment by Tanuj1718** [comment]
> Thanks for finding that issue out!
> 
> Here's the URL: https://www.digitalpublicgoods.net/r/care

Thank you for the correct URL. Will generate a PR soon.
