### ISSUE TITLE
Fix allergies count in Patient details page

### ISSUE THREAD

**Issue by Rishith25** [coronasafe/care_fe#9328]
*Describe the bug*
Currently allergies count in patient card is showing incorrect count.

*To Reproduce*

1. Go to 'any patient details page'
2. Observe allergies count in patient card

*Expected behavior*
It should show count of allergies instead of length

*Screenshots*
![Image](https://github.com/user-attachments/assets/788547d9-9053-4a49-8f4b-fc80fd2a8ba0)

*Desktop (please complete the following information):*

*Smartphone (please complete the following information):*

*Additional context*
Add any other context about the problem here.

**Comment by Rishith25** [comment]
I want to work on this. Please assign it to me. Solution is ready

**Comment by AdityaJ2305** [comment]
@rithviknishad , I think we can close this issue as per Bodhish's [comment ](https://github.com/ohcnetwork/care_fe/pull/9329#issuecomment-2528116101)

**Comment by rithviknishad** [comment]
We should still be solving for the current situation until that comes. Showing length of the allergy string is not right for current users.

**Comment by AdityaJ2305** [comment]
Got it, can we move ahead with some regex ? for `space` `,` `and`

**Comment by rithviknishad** [comment]
Hiding that badge, or Showing "Has Allergies" for now should be enough for now if there's a non-whitespace value.
