### ISSUE TITLE
Infinite Scrolling on Resource Page

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9334]
**Describe the bug**
On Resources page there is repeated rendering of resource cards, although the counted is a finite number

**To Reproduce**

1. Go to '/resource/board'
2. Scroll down
3. See error

**Expected behavior**
This repeated rendering needs to be fixed

**Screenshots**
https://github.com/user-attachments/assets/f7435dcd-431d-42cd-8e10-01a563f2835b

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser - Chrome
- Version 131.0.6778.86 (Official Build) (64-bit)

**Additional context**

**Comment by rajku-dev** [comment]
I would like to fix this @rithviknishad @Jacobjeevan @nihal467

**Comment by rithviknishad** [comment]
@rajku-dev already solved in #9267
