### ISSUE TITLE
Infinite Rendering of PhoneNumber Field on Removing Country Code

### ISSUE THREAD

**Issue by JavidSumra** [coronasafe/care_fe#9336]
**Description:**  
The `PhoneNumber` field component enters an infinite render loop when the country code (e.g., "91") is removed. This causes a console error and negatively impacts performance.

**Steps to Reproduce:**  

1. Navigate to the `/patient` page.  
2. Click on the search bar.  
3. Remove the country code (e.g., "91").  
4. Observe the error in the browser console and infinite rendering behavior.  

**Expected Behavior:**  
The `PhoneNumber` field component should not render infinitely when the country code is removed. It should handle the input change gracefully without performance issues.  

**Desktop (please complete the following information):**  
- **OS:** Ubuntu  
- **Browser:** Firefox  
- **Version:** 133.0 (64-bit)

**Comment by JavidSumra** [comment]
can you please assign this issue to me?

**Comment by sanjayh-2022** [comment]
I would like work on this issue can you please assign this to me.
