### ISSUE TITLE
Enhancement: Update the button layout in Assets Page

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#9349]
**Is your feature request related to a problem? Please describe.**
Update the button layout in Asset page, place all buttons in a same row while preserving the present mobile view

**Describe the solution you'd like**

Present :

![Image](https://github.com/user-attachments/assets/2db91526-e764-4b8e-a581-a5e284bb6118)

Suggested :

![Image](https://github.com/user-attachments/assets/4ea4036a-ff85-4a79-a5d8-8d4c68c354fb)

Preserving the mobile view:

![Image](https://github.com/user-attachments/assets/52ee2178-c148-4abc-a235-c5e40ada84e7)

**Comment by nithish1018** [comment]
@rithviknishad @Jacobjeevan I'd like to work on this if this suggestion is valid

**Comment by Jacobjeevan** [comment]
Hmm, switch to using SearchByMultipleFields for Asset Search, like we just added for facilities and patients. The 3 buttons can go on top, next to import/export.

**Comment by Jacobjeevan** [comment]
@rithviknishad At this point, we could create a common banner component that takes (optional) count and search fields params to display CountBlock and SearchByMultipleFields, no?

We are reusing the same layout for Facilities and Patients (and I'd imagine we want to extend it to Assets, Sample Test, Shifting, Resources and Users).

**Comment by Jacobjeevan** [comment]
@nithish1018 Reassigning to @manmeetnagii since an PR is open. 

I've mentioned it in the PR, but please refrain from opening PRs for issues that are assigned to someone else in the future, thanks.

**Comment by AdityaJ2305** [comment]
Hey @Jacobjeevan , I’ve created a pull request for it. Could you assign it to me and review it?

**Comment by rithviknishad** [comment]
no longer relevant in new architecture
