### ISSUE TITLE
Infinite Loading of dropdown and clear icons in Search for Facility dialouge box

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#9351]
**Describe the bug**
The loading state keeps flickering from true to false continuously in Search for Facility Dialogue Box

**To Reproduce**

1. Go to '/Assets'
2. Click on Create New Asset
3. Observe the input field of Search for Facility Dialogue Box

**Expected behavior**
The icons shouldn't keep flickering and clear icon should appear only if a facility is selected

**Screen Recording**

https://github.com/user-attachments/assets/22cc3593-fb90-4b51-bdc2-4db1e09187d4

Expected Behaviour:

https://github.com/user-attachments/assets/58cec3fe-31b3-4ebd-9ebe-2334d9daa344

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment]
@Jacobjeevan @rithviknishad I'd like to work on this issue and raise an immediate PR

**Comment by Jacobjeevan** [comment]
Infinite loading doesn't seem to be an issue on the latest for local.

#9264 addresses the clear button issue.

**Comment by nithish1018** [comment]
Got it @Jacobjeevan

**Comment by nithish1018** [comment]
@Jacobjeevan I'm on latest codebase too, but somehow I'm facing that infinite load issue 🤔

**Comment by sanjayh-2022** [comment]
@nithish1018 Sir can I work on this issue

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) I'm on latest codebase too, but somehow I'm facing that infinite load issue 🤔

My bad, I hadn't fetched to latest; looks like it's due to changes in AutoCompleteAsync, so @manmeetnagii 's PR addresses the issue.
