### ISSUE TITLE
Enhancement of shift patient tab in patient details page

### ISSUE THREAD

**Issue by Mahendar0701** [coronasafe/care_fe#9355]
Proposed designs of Shift patient tab

![Image](https://github.com/user-attachments/assets/deaeb3e4-1321-444b-a1fe-7540b86b3101)
![Image](https://github.com/user-attachments/assets/a18f223a-8ea8-4ae4-bee1-ff5b0b950696)
![Image](https://github.com/user-attachments/assets/f6979034-ead5-4973-9c29-36ab9bb3c289)

**Comment by Mahendar0701** [comment]
I am working on it . Please assign this to me

**Comment by vivekrajuv18** [comment]
Hi, Please find the figma link and detailed user flow document attached below .

Figma link - https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=3648-1593&t=pZjRwk1pfxANKJTe-1

Pdf : [Shift_patient.pdf](https://github.com/user-attachments/files/18094408/Shift_patient.pdf)

**Comment by Mahendar0701** [comment]
Hi @vivekrajuv18 i will be updating both shift patient tab in patient details page and also list view in shifting tab as both are using same component. Is there a design available for the board view as well?

**Comment by vivekrajuv18** [comment]
Board view ? > Hi @vivekrajuv18 i will be updating both shift patient tab in patient details page and also list view in shifting tab as both are using same component. Is there a design available for the board view as well?

**Comment by vivekrajuv18** [comment]
> Hi @vivekrajuv18 i will be updating both shift patient tab in patient details page and also list view in shifting tab as both are using same component. Is there a design available for the board view as well?

Board view ?

**Comment by Mahendar0701** [comment]
> > Hi [@vivekrajuv18](https://github.com/vivekrajuv18) i will be updating both shift patient tab in patient details page and also list view in shifting tab as both are using same component. Is there a design available for the board view as well?
> 
> Board view ?

Yes board view in Shifting Tab. Is there any design available? Or let it be same.

![Image](https://github.com/user-attachments/assets/0cc4a127-f364-40d2-82f9-a13d8d38ec1b)

**Comment by vivekrajuv18** [comment]
> > > Hi [@vivekrajuv18](https://github.com/vivekrajuv18) i will be updating both shift patient tab in patient details page and also list view in shifting tab as both are using same component. Is there a design available for the board view as well?
> > 
> > Board view ?
> 
> Yes board view in Shifting Tab. Is there any design available? Or let it be same.
> 
> ![Image](https://github.com/user-attachments/assets/0cc4a127-f364-40d2-82f9-a13d8d38ec1b)
> 

Let it be the same for now
