### ISSUE TITLE
Too many API calls made by Facility Select in Add Patient

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#9356]
**To Reproduce**

1. Go to 'Patients' tab
2. Click on 'Add Patient'
3. The facility search dropdown is making recursive API calls

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/a5545b5e-8018-4d8f-9191-65fc07451998)

**Comment by noufalrahim** [comment]
@nihal467 @rithviknishad  @khavinshankar can i do this..

**Comment by Jacobjeevan** [comment]
It's from AutoCompleteAsync; #9351 mentions issue with Facility Select in Assets, which is due to this.

PR #9354 addresses it 👍
