### ISSUE TITLE
Form data lost on pressing Enter during patient registration

### ISSUE THREAD

**Issue by aravindm4** [coronasafe/care_fe#9363]
**Describe the bug**
When filling out the patient registration form, if the user accidentally presses the “Enter” key, the page reloads, and all previously entered data is lost. This behavior can lead to frustration and data loss for users, especially in cases where the form is long.

Steps to Reproduce:
1. Navigate to the patient registration form.
2. Start entering data in the form fields.
3. Press the “Enter” key while filling out the form.
4. Observe that the page reloads, and all data entered is lost.

Expected Behavior:

Pressing the “Enter” key should not cause the page to reload. Ideally:
1. If the “Enter” key is pressed inside a form field, it should trigger submit button. If required fields are not filled, highlight all the empty required fields within the form.
2. The form data should be retained until explicitly submitted.

**Comment by noufalrahim** [comment]
@aravindm4 @nihal467 @rithviknishad Can u assign this to me..?

**Comment by Jacobjeevan** [comment]
@aravindm4 Shivank is redesigning the entire flow for patient registration, so we might have to wait on this 🤔  #9361

**Comment by aravindm4** [comment]
@Jacobjeevan The redesign would simply replace the Form here with the new one. That shouldn't block the current form from working properly.
