### ISSUE TITLE
Redirect Profile Page to User Details, Remove Profile Component

### ISSUE THREAD

**Issue by Jacobjeevan** [coronasafe/care_fe#9364]
User management redesign added a user details page. Most of the elements on this page are similar to what we have in profile page, i.e. logged in user would have options to edit their profile (including password change). 

Ensure all the components from profile are moved into this page for logged in user and remove the profile component.

**Comment by sanjayh-2022** [comment]
@Jacobjeevan Can I work on this issue?

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) Can I work on this issue?

Issue is already assigned 👍
