### ISSUE TITLE
Disable the Add More Bed Types option in Facility Page When All Bed Types are fulfilled

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#9365]
**Is your feature request related to a problem? Please describe.**

Right now, the **Add More Bed Types** button opens a modal to add more bed types even when all types are filled. It's better to disable it and show a tool tip saying "All types are already filled"

![Image](https://github.com/user-attachments/assets/a483c28a-fbf3-4955-8442-79f40a168d6e)

**Describe the solution you'd like**

Disable the button if all types are filled and show a tool tip on hover for user

**Comment by nithish1018** [comment]
@Jacobjeevan @rithviknishad I'd like to work on this and raise a quick PR

**Comment by Jacobjeevan** [comment]
#8956 is reworking the bed and staff capacity logic to make use of Form components; as part of that, this is also being implemented 👍

**Comment by nithish1018** [comment]
Fixed in #8956
