### ISSUE TITLE
List facility details in the user facilites page

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care_fe#9367]
![Image](https://github.com/user-attachments/assets/144561d0-2213-4c23-ac1d-981294b76211)

Currently we are only showing the name of the facility, it would have been nice if we could have shown the facility name and location.

**Comment by Mahendar0701** [comment]
I want to work on this can you assign this to me

**Comment by Jacobjeevan** [comment]
@Mahendar0701 Since you are already working on a major piece (shift patient details page), let's have someone else take this up 👍

**Comment by sanjayh-2022** [comment]
@Jacobjeevan I want to work on this issue please?

**Comment by AdityaJ2305** [comment]
Hey @sanjayh-2022, I’ve solved this issue. Would it be okay if I pushed a PR for it?

**Comment by AdityaJ2305** [comment]
Hey @sanjayh-2022, I’ve solved this issue. Would it be okay if I pushed a PR for it?

**Comment by sanjayh-2022** [comment]
@Jacobjeevan Can you please  ellaborate on where can i find the above page that you put up? Because I am not able find the add facility on facilities page.

**Comment by AdityaJ2305** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) Can you please ellaborate on where can i find the below page that you put up? Because I am not able find the add facility on facilities page.
> 
> ![](https://private-user-images.githubusercontent.com/14979190/394618396-144561d0-2213-4c23-ac1d-981294b76211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTEzODEsIm5iZiI6MTczMzkxMTA4MSwicGF0aCI6Ii8xNDk3OTE5MC8zOTQ2MTgzOTYtMTQ0NTYxZDAtMjIxMy00YzIzLWFjMWQtOTgxMjk0Yjc2MjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA5NTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYmNkYzlhMDZkZjUxYmE2OTE2YTY0NWY1MjlkYWJhZmY2NjEwOTUyYTQyMzMzZDQ5NTNlNjZkM2IxMDk5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3BD5M970_YQT8xtcfDwyltMQR5MgawGshtFhqSnbp1k)

Image is not rendered @sanjayh-2022

**Comment by AdityaJ2305** [comment]
Hey @Jacobjeevan , we are not getting `address` for already linked facilities of the user
```
userListFacility: {
    path: "/api/v1/users/{username}/get_facilities/",
    method: "GET",
    TRes: Type<PaginatedResponse<FacilityModel>>(),
  },
```

**Comment by sanjayh-2022** [comment]
@AdityaJ2305 its updated can you see it now?

**Comment by AdityaJ2305** [comment]
> [@AdityaJ2305](https://github.com/AdityaJ2305) its updated can you see it now?

No , Are you talking about this ? 

![Image](https://github.com/user-attachments/assets/b8d1e8ad-c434-416b-9fcc-6946901867d0)

**Comment by sanjayh-2022** [comment]
@AdityaJ2305 yes

**Comment by AdityaJ2305** [comment]
1. Go to `Users` in sidebar
2. Clicked on any user 
3. Click on the `Linked Facilities` in tab bar

**Comment by sanjayh-2022** [comment]
@AdityaJ2305 Thankyou

**Comment by AdityaJ2305** [comment]
> Hey [@Jacobjeevan](https://github.com/Jacobjeevan) , we are not getting `address` for already linked facilities of the user
> 
> ```
> userListFacility: {
>     path: "/api/v1/users/{username}/get_facilities/",
>     method: "GET",
>     TRes: Type<PaginatedResponse<FacilityModel>>(),
>   },
> ```

Hey @Jacobjeevan, Can you confirm this one

**Comment by Jacobjeevan** [comment]
> > Hey [@Jacobjeevan](https://github.com/Jacobjeevan) , we are not getting `address` for already linked facilities of the user
> > ```
> > userListFacility: {
> >     path: "/api/v1/users/{username}/get_facilities/",
> >     method: "GET",
> >     TRes: Type<PaginatedResponse<FacilityModel>>(),
> >   },
> > ```
> 
> Hey [@Jacobjeevan](https://github.com/Jacobjeevan), Can you confirm this one

You can make use of information in district/state objects (show those rather than full address).

**Comment by Jacobjeevan** [comment]
Reassigning to @AdityaJ2305 since a PR is open.

Please refrain from opening PRs for issues that are assigned to someone else 👍

**Comment by AdityaJ2305** [comment]
> Reassigning to [@AdityaJ2305](https://github.com/AdityaJ2305) since a PR is open.
> 
> Please refrain from opening PRs for issues that are assigned to someone else 👍

Hey @Jacobjeevan, any updates on this?
