### ISSUE TITLE
Implement Dropdown for Hidden Breadcrumb Paths Across the Platform

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9369]
Follow-up : https://github.com/ohcnetwork/care_fe/pull/8860#issuecomment-2428084413

**Current Behavior**

The breadcrumb navigation displays the entire path in a single line, which consumes excessive space and negatively impacts the user experience, especially on screens of varying sizes.

**Expected Behavior**

Display only the current page in the breadcrumb by default. Move the additional path segments (non-current pages) into a dropdown menu to optimize space utilization and enhance user experience across all screen sizes.

**Screenshot**

![Image](https://github.com/user-attachments/assets/344f45f8-0158-41b6-a64d-3b84eaaa0a12)

CC: @bodhish

**Comment by nihal467** [comment]
@modamaan it's a follow-up issue from your closed PR, are you still working on this ?

**Comment by AdityaJ2305** [comment]
@nihal467 Just a follow up question, do `Home` and `Back` should also be in dropdown just `Nalimela Anvesh` should be visible ?

**Comment by rithviknishad** [comment]
back should always be visible

**Comment by modamaan** [comment]
@nihal467 I would like continue
