### ISSUE TITLE
Minor Changes in Shifitng and Resource Page

### ISSUE THREAD

**Issue by AnveshNalimela** [coronasafe/care_fe#9381]
![Image](https://github.com/user-attachments/assets/373f4ed9-3685-48dc-9bf6-bd77cddc9e2c)

![Image](https://github.com/user-attachments/assets/2e7489dc-10d8-4b4a-b697-de996739b84f)

In List and Board  viewof Shifiting and Resource having difference in search bar length and size of button . The space from the top was different in both pages.
 I think i would put some better and consistent spacing and Change of alingment accordingly

**Comment by sanjayh-2022** [comment]
@AnveshNalimela I want to work on this issue?

**Comment by AnveshNalimela** [comment]
@sanjayh-2022 Im will be working on issue once it get assigned

**Comment by AnveshNalimela** [comment]
@rithviknishad I would like to work on these issue

**Comment by VeerChaurasia** [comment]
@rithviknishad can i take this one ?
