### ISSUE TITLE
Switch to using shadcn's Sonner for in-app toast notifications

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#9394]
Currently, notifications are dispatched via functions exported from [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js).

Since we are slowly moving towards using shadcn's UI components, let's switch to using shadcn's sonner for notifications.

https://ui.shadcn.com/docs/components/sonner

Here's an example of the Toaster component added to the `App.tsx` file (to ensure colours are as expected).

https://github.com/ohcnetwork/care_fe/blob/e48d37c6867675412f2f8ff6d9f635f2dc3c7ad7/src/App.tsx#L38-L45

Here's the full attempt diff for reference: https://github.com/ohcnetwork/care_fe/pull/9350/files

### Action Items

- [ ] Install [Sonner](https://ui.shadcn.com/docs/components/sonner) from shadcn-ui.
- [ ] Remove existing shadcn's Toaster to avoid conflicts with Sonner. Sonner support positioning without needing to write custom CSS. (i.e.: [toast.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toast.tsx), [toaster.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toaster.tsx), [useToast](https://github.com/ohcnetwork/care_fe/blob/develop/src/hooks/useToast.ts))
- [ ] Update functions in [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js) functions to instead trigger the `toast` of sonner instead of from `pnotify` library.
- [ ] Uninstall `pnotify` and related packages.
- [ ] Add development docs on: https://github.com/ohcnetwork/docs/tree/master/docs/care/development.

**Comment by nilay-v3rma** [comment]
May I work on this issue?

**Comment by rithviknishad** [comment]
@nilay-v3rma could you open a draft PR once you start working on it?

**Comment by nilay-v3rma** [comment]
@rithviknishad sure i'll raise it asap

**Comment by nilay-v3rma** [comment]
@rithviknishad I have raised the PR

**Comment by NikhilA8606** [comment]
> Currently, notifications are dispatched via functions exported from [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js).
> 
> Since we are slowly moving towards using shadcn's UI components, let's switch to using shadcn's sonner for notifications.
> 
> https://ui.shadcn.com/docs/components/sonner
> 
> Here's an example of the Toaster component added to the `App.tsx` file (to ensure colours are as expected).
> 
> [care_fe/src/App.tsx](https://github.com/ohcnetwork/care_fe/blob/e48d37c6867675412f2f8ff6d9f635f2dc3c7ad7/src/App.tsx#L38-L45)
> 
> Lines 38 to 45 in [e48d37c](/ohcnetwork/care_fe/commit/e48d37c6867675412f2f8ff6d9f635f2dc3c7ad7)
> 
>  <Toaster 
>    position="top-right" 
>    theme="light" 
>    richColors 
>    // Voluntarily passing empty object as a workaround for `richColors` 
>    // to work. Refer: https://github.com/shadcn-ui/ui/issues/2234. 
>    toastOptions={{}} 
>  /> 
> Here's the full attempt diff for reference: https://github.com/ohcnetwork/care_fe/pull/9350/files
> 
> ### Action Items
> * [ ]  Install [Sonner](https://ui.shadcn.com/docs/components/sonner) from shadcn-ui.[ ]  Remove existing shadcn's Toaster to avoid conflicts with Sonner. Sonner support positioning without needing to write custom CSS. (i.e.: [toast.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toast.tsx), [toaster.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toaster.tsx), [useToast](https://github.com/ohcnetwork/care_fe/blob/develop/src/hooks/useToast.ts))[ ]  Update functions in [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js) functions to instead trigger the `toast` of sonner instead of from `pnotify` library.[ ]  Uninstall `pnotify` and related packages.[ ]  Add development docs on: https://github.com/ohcnetwork/docs/tree/master/docs/care/development.



> Currently, notifications are dispatched via functions exported from [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js).
> 
> Since we are slowly moving towards using shadcn's UI components, let's switch to using shadcn's sonner for notifications.
> 
> https://ui.shadcn.com/docs/components/sonner
> 
> Here's an example of the Toaster component added to the `App.tsx` file (to ensure colours are as expected).
> 
> [care_fe/src/App.tsx](https://github.com/ohcnetwork/care_fe/blob/e48d37c6867675412f2f8ff6d9f635f2dc3c7ad7/src/App.tsx#L38-L45)
> 
> Lines 38 to 45 in [e48d37c](/ohcnetwork/care_fe/commit/e48d37c6867675412f2f8ff6d9f635f2dc3c7ad7)
> 
>  <Toaster 
>    position="top-right" 
>    theme="light" 
>    richColors 
>    // Voluntarily passing empty object as a workaround for `richColors` 
>    // to work. Refer: https://github.com/shadcn-ui/ui/issues/2234. 
>    toastOptions={{}} 
>  /> 
> Here's the full attempt diff for reference: https://github.com/ohcnetwork/care_fe/pull/9350/files
> 
> ### Action Items
> * [ ]  Install [Sonner](https://ui.shadcn.com/docs/components/sonner) from shadcn-ui.[ ]  Remove existing shadcn's Toaster to avoid conflicts with Sonner. Sonner support positioning without needing to write custom CSS. (i.e.: [toast.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toast.tsx), [toaster.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toaster.tsx), [useToast](https://github.com/ohcnetwork/care_fe/blob/develop/src/hooks/useToast.ts))[ ]  Update functions in [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js) functions to instead trigger the `toast` of sonner instead of from `pnotify` library.[ ]  Uninstall `pnotify` and related packages.[ ]  Add development docs on: https://github.com/ohcnetwork/docs/tree/master/docs/care/development

> Currently, notifications are dispatched via functions exported from [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js).
> 
> Since we are slowly moving towards using shadcn's UI components, let's switch to using shadcn's sonner for notifications.
> 
> https://ui.shadcn.com/docs/components/sonner
> 
> Here's an example of the Toaster component added to the `App.tsx` file (to ensure colours are as expected).
> 
> [care_fe/src/App.tsx](https://github.com/ohcnetwork/care_fe/blob/e48d37c6867675412f2f8ff6d9f635f2dc3c7ad7/src/App.tsx#L38-L45)
> 
> Lines 38 to 45 in [e48d37c](/ohcnetwork/care_fe/commit/e48d37c6867675412f2f8ff6d9f635f2dc3c7ad7)
> 
>  <Toaster 
>    position="top-right" 
>    theme="light" 
>    richColors 
>    // Voluntarily passing empty object as a workaround for `richColors` 
>    // to work. Refer: https://github.com/shadcn-ui/ui/issues/2234. 
>    toastOptions={{}} 
>  /> 
> Here's the full attempt diff for reference: https://github.com/ohcnetwork/care_fe/pull/9350/files
> 
> ### Action Items
> * [ ]  Install [Sonner](https://ui.shadcn.com/docs/components/sonner) from shadcn-ui.[ ]  Remove existing shadcn's Toaster to avoid conflicts with Sonner. Sonner support positioning without needing to write custom CSS. (i.e.: [toast.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toast.tsx), [toaster.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toaster.tsx), [useToast](https://github.com/ohcnetwork/care_fe/blob/develop/src/hooks/useToast.ts))[ ]  Update functions in [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js) functions to instead trigger the `toast` of sonner instead of from `pnotify` library.[ ]  Uninstall `pnotify` and related packages.[ ]  Add development docs on: https://github.com/ohcnetwork/docs/tree/master/docs/care/development.

@rithviknishad  Can you please assign this work to me

> Currently, notifications are dispatched via functions exported from [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js).
> 
> Since we are slowly moving towards using shadcn's UI components, let's switch to using shadcn's sonner for notifications.
> 
> https://ui.shadcn.com/docs/components/sonner
> 
> Here's an example of the Toaster component added to the `App.tsx` file (to ensure colours are as expected).
> 
> [care_fe/src/App.tsx](https://github.com/ohcnetwork/care_fe/blob/e48d37c6867675412f2f8ff6d9f635f2dc3c7ad7/src/App.tsx#L38-L45)
> 
> Lines 38 to 45 in [e48d37c](/ohcnetwork/care_fe/commit/e48d37c6867675412f2f8ff6d9f635f2dc3c7ad7)
> 
>  <Toaster 
>    position="top-right" 
>    theme="light" 
>    richColors 
>    // Voluntarily passing empty object as a workaround for `richColors` 
>    // to work. Refer: https://github.com/shadcn-ui/ui/issues/2234. 
>    toastOptions={{}} 
>  /> 
> Here's the full attempt diff for reference: https://github.com/ohcnetwork/care_fe/pull/9350/files
> 
> ### Action Items
> * [ ]  Install [Sonner](https://ui.shadcn.com/docs/components/sonner) from shadcn-ui.[ ]  Remove existing shadcn's Toaster to avoid conflicts with Sonner. Sonner support positioning without needing to write custom CSS. (i.e.: [toast.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toast.tsx), [toaster.tsx](https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/toaster.tsx), [useToast](https://github.com/ohcnetwork/care_fe/blob/develop/src/hooks/useToast.ts))[ ]  Update functions in [Notifications.js](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/Notifications.js) functions to instead trigger the `toast` of sonner instead of from `pnotify` library.[ ]  Uninstall `pnotify` and related packages.[ ]  Add development docs on: https://github.com/ohcnetwork/docs/tree/master/docs/care/development.

@rithviknishad  I would to like to solve this, Could you please assign this task to me?

**Comment by rithviknishad** [comment]
https://github.com/ohcnetwork/care_fe/pull/9262
