### ISSUE TITLE
Alignment Issue in Timestamps for "Created" and "Last Modified" Sections in Patient Dashboard

### ISSUE THREAD

**Issue by ashwinpraveengo** [coronasafe/care_fe#9397]
**Describe the bug**
There is a visual alignment issue in the "Created" and "Last Modified" sections in patient dashboard

**To Reproduce**
Navigate to the section of the application where "Created" and "Last Modified" timestamps in Patient dashboard

**Expected behavior**
The timestamps and icons should be properly aligned vertically for both "Created" and "Last Modified" sections to ensure a clean user interface.

**Screenshots**
![Image](https://github.com/user-attachments/assets/88e5171c-d19a-4fe3-b4ee-246f7cfb5dab)

**Comment by ashwinpraveengo** [comment]
@rithviknishad  I would like to work on this issue

**Comment by AdityaJ2305** [comment]
Hey @ashwinpraveengo, I have solved it. Should I go ahead and push the PR ?
