### ISSUE TITLE
Search bar loses focus after screen rebuild in Users section

### ISSUE THREAD

**Issue by navaneeth0041** [coronasafe/care_fe#9398]
**Describe the bug**
In the Users section, the search bar loses focus during screen rebuilds after typing, requiring users to manually reclick the search bar to continue typing.

**To Reproduce**

1. Go to Users section
2. Click on the search bar
3. Start typing any search term
4.The search bar loses focus after screen rebuild
5.Need to click the search bar again to continue typing

**Expected behavior**
The search bar should maintain focus throughout the typing process and subsequent screen rebuilds, allowing users to type continuously without having to reclick the search bar, similar to how it works in other sections of the application.

**Screenshots**
https://github.com/user-attachments/assets/b3fcc715-d2b2-4c31-a961-9f3dcf97196b

**Desktop :**

- OS: Linux (Arch)
- Browser: Chrome

**Additional context**
This issue is specific to the Users section. The search functionality works as expected (maintains focus) in all other sections of the application where search is implemented.

**Comment by navaneeth0041** [comment]
@rithviknishad I would like to work on this issue.

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad @Jacobjeevan  I would like to take up this issue

**Comment by rithviknishad** [comment]
no longer relevant in new architecture
