### ISSUE TITLE
Improve Facility & Phone number Search Field Reset and Dynamic Shortcut Hints for new search component

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9401]
**Describe the bug**

**Issue 1:**
When closing the badge related to the facility search, while the badge is removed and the applied filter is reset on the page, the input data in the search field is not being cleared as expected.

Similar issue is being experience for phone number search in the patient tab

**Issue 2:**
The newly refactored search component is missing the following keyboard shortcuts, which were available in the previous version:

Ctrl+K: Shortcut to focus on the search field.
Esc: Shortcut to clear the search field.
For reference to the old component behavior, visit the previous deployment: [Old Deployment](https://f5958847.care-fe.pages.dev/facility).

**To Reproduce**

1. Go to facility tab
2. search for a facility
3. close the related badge

**Expected behavior**

- [ ] Reset Input on Badge Removal: Closing the badge associated with a facility search should also reset the input field in the search box to ensure consistency in the UI.
- [ ] Reintroduce Keyboard Shortcuts: Ctrl+K for Focusing the Field:
- The shortcut should focus the cursor on the search field.
- The field should display a Ctrl+K hint when it is empty, to inform users of the shortcut functionality.
- [ ] Esc for Clearing the Field:
- If the search field contains data, pressing Esc should clear the input.
- The field should display an Esc hint when it is not empty, indicating that the user can use this shortcut to reset it.
- [ ] Similar behavior should be implemented for the User Tab search field, where the shortcut hints are dynamic. Currently, only Ctrl+K is displayed statically.

**Screenshots**

![Image](https://github.com/user-attachments/assets/5e0f9d5c-8b87-4494-afa6-7e7d6b90eb50)
![Image](https://github.com/user-attachments/assets/02829a2d-401f-4844-80d8-fe2dfd6008c2)

**Comment by noufalrahim** [comment]
@nihal467 can i assign this to me..?

**Comment by saikiranpatil** [comment]
@nihal467 can I work on this?

**Comment by Sulochan-khadka** [comment]
@nihal467 all the things are working fine i think. The shortcuts are doing as stated except the new feature that a display hint must be given to use the shortcut. Also the closing badge is working just fine.
Attaching the recording of it.
https://github.com/user-attachments/assets/37d4d499-25d8-403c-a17d-392a6a8c8e7e

**Comment by nihal467** [comment]
@Sulochan-khadka the issue still persist, check the develop preview : care.ohc.network

**Comment by shauryag2002** [comment]
Hi @noufalrahim, I noticed you're interested in this issue. If there's anything blocking or if you need any assistance, I’d be happy to help!
If you cannot take this forward, @nihal467, could you kindly assign it to me? I’m ready to work on it.

**Comment by noufalrahim** [comment]
I am currently working on this

**Comment by AdityaJ2305** [comment]
@nihal467, I’d like to take up this issue if @noufalrahim isn’t working on it.
