### ISSUE TITLE
Auto label failures

### ISSUE THREAD

**Issue by kihan2518B** [coronasafe/care_fe#9411]
![Image](https://github.com/user-attachments/assets/bb63d04a-1960-45b3-84e8-2ba282c81dc1)

**Comment by Rustix69** [comment]
I would like to work on this.

**Comment by Shanshah123** [comment]
i would like to work on this issue

**Comment by Rustix69** [comment]
@rithviknishad In this Issue should I fix the Auto label file or the PR thats causing this issue ?
