### ISSUE TITLE
Discrepancy in Occupancy data on Facility Card

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9412]
**Describe the bug**
- Occupancy data reflected on Facility card is not matching with that Facility's Total Beds data.
<img src="https://github.com/user-attachments/assets/44a3c055-6b3a-4682-9ffb-7a8ca15e0c75" width=360 />
<img src="https://github.com/user-attachments/assets/ea528fec-0bca-4b2d-9a2d-186df279eb53" width=360/>

- Total beds should not be zero if occupied beds are non zero
- There is not a single source of truth for Live Patients in a Facility and Total beds occupied in that Facility
- Total beds can't be less than occupied beds
<img src="https://github.com/user-attachments/assets/b31ca381-6dc5-41a1-ae5b-c770af6ddb6d" width=300/>

**To Reproduce**

1. Go to '/facility'
2. See Occupancy data on any Facility Card
3. Click on that Facility and compare with total beds occupied data

**Expected behavior**
Single source of truth for Total Live Patients and Total Beds occupied for a facility

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser - Chrome
- Version 131.0.6778.86 (Official Build) (64-bit)

**Comment by rajku-dev** [comment]
I want to work on this issue @rithviknishad @Jacobjeevan

**Comment by Jacobjeevan** [comment]
Those two denote two different things; I can see why it's confusing though. The total beds in facility card correspond to beds under local management (accessible under manage facility), rather than the bed capacity.
