### ISSUE TITLE
Text Too Close to Edge in Sample Test History

### ISSUE THREAD

**Issue by Jeffrin2005** [coronasafe/care_fe#9416]
**Describe the bug**
The text in the Sample Test History is too close to the edge of the box

**To Reproduce**

1. Go to Sample Test
2. Click on Sample Details of any patients 
3. Scroll down to Sample Test History
4. Text is very close to the edge of the box.

**Expected behavior**
The text should have enough padding around it to make it easily readable.

**Screenshots**
![Image](https://github.com/user-attachments/assets/54663133-fe4d-4656-83be-18bc72cfd211)

**Desktop (please complete the following information):**

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan I would like to work on this. Could you please assign it to me?

**Comment by bodhish** [comment]
Closing it in favour of servie request feature
