### ISSUE TITLE
Enhancement Request: Improve Visibility of the 'Completed' Tag in Shifting and Resource Section

### ISSUE THREAD

**Issue by ashwinpraveengo** [coronasafe/care_fe#9417]
**What aspect of the feature would you like to improve? Please describe.**
The "Completed" tag in the Shifting and Resource section currently lacks visual emphasis, making it less noticeable. A clearer distinction would improve usability and enhance the user experience.

**Describe the solution you'd like**
Update the "Completed" tag in the Shifting and Resource section to use green text or a green background. This change would visually signify completion more effectively, aligning with standard UI design practices.

**Describe alternatives you've considered**
- Adding an icon, such as a checkmark, alongside the "Completed" tag for better visibility.

**Current Design**
![Image](https://github.com/user-attachments/assets/dd9aa297-88f3-4277-ae05-da3b4ec94a27)

**Additional Context"
This enhancement would provide users with a more intuitive way to identify completed items.

**Comment by ashwinpraveengo** [comment]
@Jacobjeevan @bodhish  @Rishith25 I would like to work on this issue. Could you please assign this issue to me?....

**Comment by bodhish** [comment]
@ashwinpraveengo I don't its a useful change, for each user the important tab is differen. 
CC: @Jacobjeevan
