### ISSUE TITLE
Negative Numbers in Triage Form

### ISSUE THREAD

**Issue by Jeffrin2005** [coronasafe/care_fe#9429]
**Describe the bug**
Digits must be 0 or higher

**To Reproduce**

1. Go to Facilities tab
2. Click on any facilities
3. Scroll down to "Corona Triage"
4. Click "Add Triage"
5. it allows negative values

**Expected behavior**
The input digits should be 0 or higher, disallowing negative numbers.

**Screenshots**
![Image](https://github.com/user-attachments/assets/f50ab393-cf92-48d6-b8e0-e9e857654e2a)

**Desktop **

**Comment by noufalrahim** [comment]
@rithviknishad @Jacobjeevan 
Can I work on this..?

**Comment by Rustix69** [comment]
@rithviknishad @Jacobjeevan I had debugged the issue and set the codebase. Can I work on this issue if it is ok ?

**Comment by bodhish** [comment]
We have cleaned it up in https://github.com/ohcnetwork/care_fe/pull/9436
