### ISSUE TITLE
DateInput and Actions button not optimised for mobile viewports

### ISSUE THREAD

**Issue by harshit078** [coronasafe/care_fe#9431]
**Describe the bug**
- Actions button in Patients page not optimised for mobile viewports
- Date Picker dropdown overflows for mobile viewports making it difficult to select date.

**To Reproduce**

1. Go to 'Patients
2. Click on any Patient Detail
3. Scroll down to Actions

**Current behavior**
<img width="408" alt="Image" src="https://github.com/user-attachments/assets/3c9769ff-e5a3-4317-b466-b6e0304efd25" />

<img width="429" alt="Image" src="https://github.com/user-attachments/assets/3abc4c81-12cc-43ae-8682-8380ac6205d1" />

**Expected behavior**

- The Action button should be optimised for mobile viewports

<img width="431" alt="Image" src="https://github.com/user-attachments/assets/6347c290-ec54-4eee-851a-8f0ff1fb9174" />

- The date picker should open the dropdown to its alternate position when mobile viewports
<img width="426" alt="Image" src="https://github.com/user-attachments/assets/f1cb24b7-07dd-4f3d-aed8-13b8240b75cf" />

- Device: Chrome Dev tools
- Browser: Chrome
- Version Latest

**Comment by Rustix69** [comment]
Can I work on this Issue, If its Okay ?
