### ISSUE TITLE
Issue with New Under Development Workflow

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9435]
## Minor Issues

![Image](https://github.com/user-attachments/assets/ee9a338d-caaf-4d32-9b01-ff610c454366)

- [ ] the facility details card in the facility specific public page is clipping in in the mobile devices

![Image](https://github.com/user-attachments/assets/37180537-1333-4b18-a8c4-6f948d4ebb53)

- [ ] Currently, the doctor appointment APIs are not available in the public page. In case of any issues, show a proper error message instead of 'Something went wrong.

## Enhancement

![Image](https://github.com/user-attachments/assets/e0c44aad-c519-4c5b-8795-edabb3e023b9)

- [ ] the dropdown and the field size are of different width, keep it consistent

## Question

![Image](https://github.com/user-attachments/assets/c28288c5-793b-4d9e-a092-3362903f6c2f)

- [ ] OTP services are not working,

**Comment by srijantrpth** [comment]
Hi @nihal467 , If you have not started working on this issue. Kindly assign me the issue. Thanks

**Comment by nihal467** [comment]
closing this issue, will be creating a new one later
