### ISSUE TITLE
Inconsistency in title during creation of Resouce Request

### ISSUE THREAD

**Issue by Tanuj1718** [coronasafe/care_fe#9440]
**Describe the bug**
During creation of resource request, there is a text area provided for the 'Reason of Request'. But it is has given the title 'Description of Request'.
During creation of resource request and updation of resource request, it has title 'Description of Request' while after creation, it has title 'Reason'. This is creating inconsistency and confusion.

**To Reproduce**

1. Go to facilities tab.
2. Click on any facility
3. Click on Manage Facility and then in Resource Request
4. See the title 'Description of Resource'
5. Create it and then see it is replaced by 'Reason'
**Expected behavior**
The title during creation should be 'Reason of Resource' instead of 'Description of Resource'.

**Screenshots**
<img width="765" alt="Image" src="https://github.com/user-attachments/assets/c351c8e0-1f2c-4600-ae2b-494a904d6f63" />
<img width="793" alt="Image" src="https://github.com/user-attachments/assets/3f36e2e8-d261-4928-be15-261ab4e21b71" />

**Desktop:**

- OS: MacOS
- Browser Chrome

**Comment by Tanuj1718** [comment]
@bodhish @rithviknishad Would like to work on this if it gets approved. Please assign it to me after approving.

**Comment by srijantrpth** [comment]
Hi @Jacobjeevan, Kindly merge the PR linked to close the issue. Thanks.
