### ISSUE TITLE
Date picker icon overlapping

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9443]
**Describe the bug**
Date Picker icon is overlapping with the input text in 'Create consultation' (possibly more) forms.

**To Reproduce**

1. Go to '/patients'
2. 'Add consultation' or 'Update consultation' for any patient
3. Scroll down to Symptoms -> Date of 

**Expected behavior**
icon should not overlap with the text in that field

**Screenshots**
Create consultation
<img width="555" alt="Image" src="https://github.com/user-attachments/assets/fbd82608-ce4e-4beb-9289-189ed959ef14" />

Log Update
<img width="555" alt="Image" src="https://github.com/user-attachments/assets/3883f412-eb8d-47e7-8871-ea99e8824505" />

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser - Chrome
- Version 131.0.6778.86 (Official Build) (64-bit)

**Comment by rajku-dev** [comment]
I want to fix this issue. @Jacobjeevan @rithviknishad @nihal467

**Comment by Jacobjeevan** [comment]
#8998 addresses this.
