### ISSUE TITLE
Add Copy Confirmation for Doctor's Phone Number

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9444]
**Is your feature request related to a problem? Please describe.**

Currently, when a user copies a Doctor's phone number to the clipboard on Doctor Connect, there is no visual confirmation or feedback indicating the action was successful. This may cause confusion as the user is unsure if the copy action worked.

<img src="https://github.com/user-attachments/assets/2b78d178-619e-4284-a417-62cc312f333e" width=400/>

**Describe the solution you'd like**
Add a success notification to confirm that the Doctor's phone number has been successfully copied to the clipboard.

**Comment by rajku-dev** [comment]
I would like to work on this if applicable @rithviknishad @Jacobjeevan @nihal467

**Comment by srijantrpth** [comment]
Hi,  I have started working on this issue. I will raise the PR Today. Thanks

**Comment by rajku-dev** [comment]
> Hi, I have started working on this issue. I will raise the PR Today. Thanks

Let me do it @srijantrpth
Please look over other open issues or find new issues on you own, get them approved and work on them

**Comment by srijantrpth** [comment]
Hi, Sure Go ahead!
