### ISSUE TITLE
Bug in Log Lab Results Multi-Selector

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9445]
**Describe the bug**
- When more than one test items are selected in 'Log Lab Results' , tags and selection summary doesn't update properly, it's either blank or shows '1 item(s) selected'
- User need to click twice to show '1 item(s) selected' except for the first time

https://github.com/user-attachments/assets/bbcf8ff1-26e2-4f96-95a9-c8a0cde6c87d

**Expected behavior**
Proper update of Tags and selection summary on selection of items from multi selector dropdown

**Comment by rajku-dev** [comment]
If not being addressed in other issues, I would like to work on this @Jacobjeevan @rithviknishad

**Comment by rithviknishad** [comment]
@khavinshankar and @yash-learner 

this is being re-written right?
