### ISSUE TITLE
Unnecessary Space Allocation for Staff Entries with Zero Count

### ISSUE THREAD

**Issue by Jeffrin2005** [coronasafe/care_fe#9450]
**Describe the bug**
When attempting to add staff members with zero current staff, the system allocates space unnecessarily and displaying

**To Reproduce**

1. Go to Facilities tab
2. Click on any facilities
3. Scroll down to "Staff Capacity"
4. Click "Add Staff Types" and allocate 0 staff and it is displaying 0 staff

**Expected behavior**
A message should be displayed before adding staff with zero current staff to prevent unnecessary space allocation

**Screenshots**
![Image](https://github.com/user-attachments/assets/d5fbbf59-82b0-4025-8c65-14e8ea65235f)

**Desktop:**

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Can I work on this issue ?

**Comment by nihal467** [comment]
the entire section is removed from CARE, update your branch :)
