### ISSUE TITLE
Modify queryRequest to support custom headers

### ISSUE THREAD

**Issue by Jacobjeevan** [coronasafe/care_fe#9457]
We recently added OTP based flow as an alternative for scheduling appointments, however this requires setting token in the headers (currently done through fetch request rather than queryRequest).

queryRequest (src/Utils/request/query.ts) currently doesn't support custom headers; add logic to do so.

**Comment by srijantrpth** [comment]
Hi @Jacobjeevan , Kindly assign me this issue so that I can start working on it. Thanks
