### ISSUE TITLE
Overlapping in text and icons

### ISSUE THREAD

**Issue by Tanuj1718** [coronasafe/care_fe#9461]
**Describe the bug**
Icons and text in the shifting page are overlapping and looking messy.

**To Reproduce**

1. Go to ['https://care.ohc.network/shifting/list'](url)
2. See in status column.

**Expected behavior**
Text should not be overlap with the icons. We can improve it using text wrap for status column. Also we have to move tags like 'emergency' to below the current status.

**Screenshots**

<img width="715" alt="Image" src="https://github.com/user-attachments/assets/1cf01f1c-d522-4680-a545-bd1fe82564bf" />

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome

**Comment by Tanuj1718** [comment]
@bodhish @rithviknishad  I would like to take this issue, please assign it to me.

**Comment by Jacobjeevan** [comment]
You can open a single PR for this and #9462.

**Comment by Utkarsh-Anandani** [comment]
Can I do it @Jacobjeevan both the issues single PR.

**Comment by Tanuj1718** [comment]
> Can I do it @Jacobjeevan both the issues single PR.

I am working on it.
