### ISSUE TITLE
Add padding for clear visibility of text

### ISSUE THREAD

**Issue by Tanuj1718** [coronasafe/care_fe#9462]
**Describe the bug**
Button required padding to make text more visible. 

**To Reproduce**

1. Go to [https://care.ohc.network/shifting/list](url)
2. See the Action column.
3. See the 'Transfer to Receiving facility' button.

**Expected behavior**
There should be enough padding in the button so that the text look more visible and clear.

**Screenshots**

<img width="225" alt="Image" src="https://github.com/user-attachments/assets/4a33f073-7d14-40c2-b83b-de0f35ffac98" />

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome

**Comment by Tanuj1718** [comment]
@rithviknishad  @bodhish @sainak  Please assign it to me.

**Comment by Jacobjeevan** [comment]
Combine with #9461
