### ISSUE TITLE
The assets configuration page lacks mobile responsiveness

### ISSUE THREAD

**Issue by modamaan** [coronasafe/care_fe#9465]
**Describe the bug**
The bug is that the assets configuration page is not mobile-responsive, causing layout issues on smaller screens.

**To Reproduce**

1. Go to 'Assents button on sidebar'
2. Click on 'Configure button'
3. See error

**Expected behavior**
I expected the assets configuration page to adapt seamlessly to smaller screen sizes, ensuring all elements are displayed correctly and remain fully functional on mobile devices.

**Screenshots**
![Image](https://github.com/user-attachments/assets/e9e995d9-c54c-4d77-ba20-b64606521502)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [130.0.6723.117]

**Additional context**

**Comment by modamaan** [comment]
@Jacobjeevan  i would like to work on this

**Comment by rithviknishad** [comment]
Let's also switch all the elements to use shadcn's components such as buttons and other input elements.
