### ISSUE TITLE
Repeated Notifications for Invalid Facility Query

### ISSUE THREAD

**Issue by Jeffrin2005** [coronasafe/care_fe#9468]
**Describe the bug**
Selecting an invalid facility sometimes triggers the "_No Facility matches the given query_" error **twice**. Even after closing the notification and retrying, the error still pops up repeatedly.

**To Reproduce**

1. Go to Assets tab
2. Click on "Advanced Filters"
3. Click on an invalid facility.
4. The error notification appearing twice.
5. Close the notification and try selecting an invalid facility again, the error notification still reappears unnecessarily

**Expected behavior**
The error notification should appear only once for each invalid query.

**Screenshots**

https://github.com/user-attachments/assets/eaa2744f-f6b5-4ce8-92b2-642532647066

**Desktop (please complete the following information):**

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Can i work on this issue?

**Comment by Jacobjeevan** [comment]
This occurs only on the test platform due to data accumulated over time (broken data where asset refers to a particular facility but it no longer exists).

So, it's not an issue that needs to be resolved. Closing as not planned.
