### ISSUE TITLE
Incorrect type declaration for QueryOptions in the TanStack Query request function.

### ISSUE THREAD

**Issue by UdaySagar-Git** [coronasafe/care_fe#9470]
**Describe the bug**
https://github.com/ohcnetwork/care_fe/blob/69527b8bc33a69a15b0c706218d905e9ec07e296/src/Utils/request/types.ts#L38-L45
ideally queryParams type shouldn't be restricted to the values of string

**Expected behavior**
It should be of type string | number | boolean | null | undefined, which is already declared as QueryParamValue in the same page

```
export interface QueryOptions<TBody = unknown> {
  pathParams?: Record<string, string>;
  queryParams?: QueryParams;
  body?: TBody;
  silent?: boolean;
  signal?: AbortSignal;
  headers?: HeadersInit;
}
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rithviknishad** [comment]
Completed in https://github.com/ohcnetwork/care_fe/pull/9463
