### ISSUE TITLE
Enhancement of Users Addition Form

### ISSUE THREAD

**Issue by srijantrpth** [coronasafe/care_fe#9476]
**Is your feature request related to a problem? Please describe.**

I was testing out the feature of adding a new user and assigning facilities to it which can be improved by displaying the values in the input box as well along with the selection options which could also prevent some accidental selections if there are any. Currently, the selected facilities are being shown below the Facilities Input Box which gets hidden during selection making.

**Describe the solution you'd like**
We can display the facilities selected as comma separated values in the same input box along with the tick marks

**Additional context**
https://github.com/user-attachments/assets/c2c40131-6e4d-48c8-ba6f-577c6ebcfb01

**Comment by srijantrpth** [comment]
Hi @Jacobjeevan @rithviknishad , Let me know your thoughts on this enhancement feature. I'll start working on it once you approve the issue.

**Comment by Jacobjeevan** [comment]
🤔  This isn't necessary since selected items are highlighted during selection anyways (and when selection drop down isn't triggered, the selected choices will be displayed underneath, so would be redundant).
