### ISSUE TITLE
Log Updates Container Overflow

### ISSUE THREAD

**Issue by Keerthilochankumar** [coronasafe/care_fe#9489]
**Describe the bug**
The log update container is not properly constrained within the boundaries of the main container

**To Reproduce**

1. Go to Patients
2. Click on  any Patient
3. Scroll down and change the Events to  log update

**Expected behavior**

Log Update Container should always reside inside Main Page Boundaries

**Screenshots**
![Image](https://github.com/user-attachments/assets/b16cd4e8-b07c-4d9a-8e54-2a49822fffa3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Keerthilochankumar** [comment]
Please assign this to me

**Comment by rithviknishad** [comment]
This has been changed in one of the actively developed branch: https://github.com/ohcnetwork/care_fe/pull/9262 deployed on https://care.do.ohc.network/

Try that out and create issue if present there.

<img width="911" alt="Image" src="https://github.com/user-attachments/assets/5eea651d-35ee-4afe-80f4-6ee7c0718c8a" />
