### ISSUE TITLE
Refactor Clipboard Operations to Utilize new copyToClipboard Utility

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9494]
**Is your feature request related to a problem? Please describe.**
- Enhance consistency in UI/UX.
- Improve the behavior of the clipboard icon to reflect proper state changes.
- Ensure Success/Error Notifications are handled efficiently and provide clear feedback.

**Describe the solution you'd like**
- Required in components like `AssetWarrantyCard` , `ShiftDetails` , `SBOMViewer` etc

**Describe alternatives you've considered**

**Additional context**

**Comment by rajku-dev** [comment]
I would like to work on this update if applicable @rithviknishad @Jacobjeevan @nihal467 
Thanks

**Comment by nihal467** [comment]
not a requirement based on the current develop
