### ISSUE TITLE
Categories a patient according to 'Mobility status', which does't change often

### ISSUE THREAD

**Issue by athulmanuel** [coronasafe/care_fe#9497]
All Patients to be classified into 4 categories according to mobility while registering 

Category 1 - Bed bound (any person who cannot get up from bed without someone's help)
Category 2 - Home bound ( any person who is not bed bound but cannot get out of home without someone's help)
Category 3 - Independently mobile with illness (any person who is not bed bound or home bound with illness) 
Category 4 - Independently mobile and active without illness

@bodhish @vigneshhari @gigincg 

- Backend: https://github.com/ohcnetwork/care/pull/2672

**Comment by athulmanuel** [comment]
can we add the mobility status issue Status: Open.
#9497  to this field area while we carry out this issue 

This would help in registration and picking up the patient by each type of user. EG: bed bound patients needs to be looked after by community home care nurse but home bound and ambulatory with illness will be looked after by MLSP in the JAK( sub centre)  @bodhish @vigneshhari

**Comment by athulmanuel** [comment]
Can we have is just as a tag - 'generalised mobility status' while  a patient is being registered.  this can be removed once the encounter is made.  
Justification - we have classified that all bed bound patient needs to be visited and given care by the Community nurse team and those who are home bound and mobile with other illness needs to be registered with the MLSP sitting at JAK which covers 3-4 wards.  For this to be segregated, we need to tag this on registration. This can change after the first encounter after the assessment by the nurse. this happens because its a new categorisation started1 year back. one the communtiy learns then the tagging will be more accurate.  @bodhish @vigneshhari @gigincg

**Comment by bodhish** [comment]
@sainak can we add an enum `Mobility status` to the patient? Options are 
- Bed bound (any person who cannot get up from bed without someone's help)
- Home bound ( any person who is not bed bound but cannot get out of home without someone's help)
- Independently mobile with illness (any person who is not bed bound or home bound with illness)
- Independently mobile and active without illness

The descriptive keys can be part of the FE
