### ISSUE TITLE
Disable Submit Button on Edit Profile Page When No Changes Are Made

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9501]
**Describe the bug**

On the user information edit profile page, when clicking the Submit button without making any changes to the form across multiple sections, a form update request is still triggered.

**To Reproduce**

1. Go to users page
2. Click on details button and hit edit button on all the section
3. without making any change click the submit button

**Expected behavior**

The Submit button on the user information page in edit mode should be disabled unless changes have been made to the form.

**Screenshots**

![Image](https://github.com/user-attachments/assets/1908d72e-453e-4782-bcc8-ca73179911ed)

**Comment by Jeffrin2005** [comment]
@nihal467 @rithviknishad I would like to work on this issue. could you assign it to me ?
