### ISSUE TITLE
Linked Facilities for Newly Created Users Not Persisting or Rendering in the Linked Facility Section

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9502]
**Describe the bug**

When creating a user with a linked facility and designating one as the home facility, the facility does not appear in the linked facility section on the user's details page. Additionally, when logging into the platform with the newly created user's credentials, the facility section is also missing.

**To Reproduce**

1. Navigate to the User tab.
2. Create a new nurse user, specifying a linked facility and marking one as the home facility.
3. Open the details page for the newly created user.
4. Navigate to the Linked Facility section.
5. Observe the issue.

**Expected behavior**

- [ ] All linked facilities specified during user creation should be stored correctly
- [ ] The linked facilities should be visible in the Linked Facility section on the user's details page.
- [ ] The user should have access to the designated facilities when logged into the platform.

**Screenshots**

![Image](https://github.com/user-attachments/assets/76b69e25-d22d-4be2-992c-be156447cfa3)

**Comment by khavinshankar** [comment]
Acknowledged
