### ISSUE TITLE
Presets to secondary camera feed is not responding

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#9506]
**Describe the bug**

- [ ] The presets for accessing the camera feed of the secondary camera are not responding. Even though the camera name is changing, the visual is stuck to the first selected camera preset. if you refresh the page it will direct to the selected preset view
- [ ] Even though we delete all the presets, the three presets are still coming up on the feed view . (patient view,monitor view and Face view) 
In some cases we couldn't even find the above presets on camera configuration page but still its showing up on the feed.
https://github.com/user-attachments/assets/619ea526-0a49-4d33-b89c-c915cf7a81c9

**To Reproduce**

1. Go to any patient linked with Multiple cameras ( multiple cameras for single bed)
2. Click on presets on the camera feed
3. See error

**Expected behavior**

- [ ] The linked camera feed should be visible when you select the presets for each cameras
- [ ] Presets should be cleared when those are deleted on camera configuration page

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rishith25** [comment]
I would like to work on this please assign it to me.

**Comment by Rustix69** [comment]
I have done the similar issue in a previous PR. Can I work on this ?

**Comment by Jacobjeevan** [comment]
2nd one should be fixed by [2650](https://github.com/ohcnetwork/care/pull/2650) on the backend, should go alive in the next release.

@samholics Are you seeing this on care.ohc.network?

**Comment by samholics** [comment]
> 2nd one should be fixed by [2650](https://github.com/ohcnetwork/care/pull/2650) on the backend, should go alive in the next release.
> 
> [@samholics](https://github.com/samholics) Are you seeing this on care.ohc.network?

No  on production.

**Comment by Rishith25** [comment]
@Jacobjeevan @samholics 
It is working fine in care.ohc.network.
For production how could i address Can you please guide me

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) [@samholics](https://github.com/samholics) It is working fine in care.ohc.network. For production how could i address Can you please guide me

You have tested (1) as well?

(2) is fixed, yes. You don't need to do anything there. It will be pushed to production in the next release.

**Comment by Rishith25** [comment]
Yes

**Comment by samholics** [comment]
@Rishith25 which facility and which patient you tested it? Was that patient bed linked with multiple cameras?

**Comment by Rishith25** [comment]
> [@Rishith25](https://github.com/Rishith25) which facility and which patient you tested it? Was that patient bed linked with multiple cameras?

https://github.com/user-attachments/assets/eda77052-139f-4e87-b161-bff72ebf139d

**Comment by Jacobjeevan** [comment]
> > [@Rishith25](https://github.com/Rishith25) which facility and which patient you tested it? Was that patient bed linked with multiple cameras?
> 
> Recording.2024-12-20.114306.mp4

That isn't a patient linked with multiple cameras. I don't know if we have such an example on staging; you are welcome to check. I'll see if we can get another one added.

**Comment by samholics** [comment]
@Rishith25 
in care, we can link multiple cameras to a patient, and those camera presets also come here on the top section. 
<img width="896" alt="Image" src="https://github.com/user-attachments/assets/c1b426e2-4db1-40b5-8bf5-951d62e7f21a" />

But when you try to access those presets from the secondary camera, its not responding. the camera name changes but the visual is not changing.  
also here on the patient tyou tested its only linked with one camera. 

https://drive.google.com/file/d/1sEr7r_VKTdAZ6JlN0MtseBpSM9offdda/view?usp=sharing

**Comment by nihal467** [comment]
not a requirement based on the current develop
