### ISSUE TITLE
Allergy must be mandatory

### ISSUE THREAD

**Issue by athulmanuel** [coronasafe/care_fe#9508]
<img width="568" alt="Image" src="https://github.com/user-attachments/assets/40b7c20d-1f5c-4162-b754-a31e8b43d9a2" />

this has to be linked to the the clinical scenario as edits might happen during the clinical round

**Comment by jeevjacobgeorge** [comment]
which page

**Comment by bodhish** [comment]
This is not part of the patient reg page, it will be cleaned up
