### ISSUE TITLE
landing page after entering demographic data

### ISSUE THREAD

**Issue by athulmanuel** [coronasafe/care_fe#9510]
<img width="1396" alt="Image" src="https://github.com/user-attachments/assets/367cc77e-fe67-4c24-99e7-883d7738e540" />

Can't we go directly to the patient dashboard after this and then click the form to be filled so that the nurse  or anyone who enters the form has an overview of what has been entered by themselves.?

This should be coming to the place were we can select which form to be filled right ? or should it be a mandatory form across all encounters ?, if so , we have to build that

**Comment by bodhish** [comment]
Resolved.
