### ISSUE TITLE
Add support for adding a description facility

### ISSUE THREAD

**Issue by bodhish** [coronasafe/care_fe#9523]
Add a text filed to facility to capture long form text related to the facility. 
It should support markdown text and should be used with public facility show pages. 

- Backend: https://github.com/ohcnetwork/care/pull/2672

**Comment by sainak** [comment]
completed in https://github.com/ohcnetwork/care_fe/pull/9262/commits/46bf5eddd512a12c1bafbdfb61ddcf2144870e5b
