### ISSUE TITLE
Text is overlapping on the user management page

### ISSUE THREAD

**Issue by modamaan** [coronasafe/care_fe#9532]
**Describe the bug**
Text overflows in the user management card details, and text overlaps on mobile screens

**To Reproduce**

1. Go to 'Users on sidebar'
2. switch to mobile size
3. See error

**Expected behavior**
The text within the user management card should fit properly inside the container without overflowing and overlapping. On mobile screens, the text should wrap appropriately to maintain a responsive and visually consistent layout.

**Screenshots**

problem 1
![Image](https://github.com/user-attachments/assets/28323f73-1a14-4810-82d1-d70bd16f24c7)

problem 2
![Image](https://github.com/user-attachments/assets/4c9867c0-217f-4491-b294-82fe587f680d)

problem 3
![Image](https://github.com/user-attachments/assets/c1f3442d-d42e-4c98-862f-f1716d4900fe)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [131.0.6778.205]

**Comment by modamaan** [comment]
@Jacobjeevan  i would like to take it up

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) i would like to take it up

Use tooltip (shadcn) for long names.

**Comment by Sulochan-khadka** [comment]
@modamaan for Problem 3 that you stated, it has another issue of alignment. the name column should be set such that , other attributes do not go into horizontal scroll. Instead , for long names, make elipsis and tooltip as @Jacobjeevan stated.

**Comment by piyushyadav0191** [comment]
@Jacobjeevan The issue was opened 10 hours ago, so I created a PR for the fix you mentioned. Could you please review it?
#9541

**Comment by rithviknishad** [comment]
@piyushyadav0191 I'd recommend getting the issue assigned before working on issues next time.

**Comment by rithviknishad** [comment]
This page is gone
