### ISSUE TITLE
Patient page button alignments.

### ISSUE THREAD

**Issue by Sulochan-khadka** [coronasafe/care_fe#9539]
**Describe the bug**
There are some misalignment of buttons as per screen size

**To Reproduce**

1. Go to Patients Tab
2. check responsive screen

**Expected behavior**
Buttons should be a bit more aligned.

**Screenshots**
<img width="550" alt="Image" src="https://github.com/user-attachments/assets/4176e029-9ce7-4049-b43c-5cc4cb9fd0fb" />
<img width="493" alt="Image" src="https://github.com/user-attachments/assets/97559b33-eda9-4e38-a956-d0cbf96ccf10" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sulochan-khadka** [comment]
@rithviknishad @nihal467 suggest some UI improvements for better alignment of buttons.

I think this is fine:
<img width="601" alt="Image" src="https://github.com/user-attachments/assets/a704caae-ce94-4f63-96a4-562e70df99f7" />

**Comment by rithviknishad** [comment]
Not relevant once #9400 is merged
