### ISSUE TITLE
Inconsistent action buttons styling in patient details page

### ISSUE THREAD

**Issue by Rishith25** [coronasafe/care_fe#9543]
The action buttons styling is inconsistent in patient details page

![Image](https://github.com/user-attachments/assets/d1331109-baa2-4bfc-9ab3-21ffae10a1a8)

**Comment by Rishith25** [comment]
@Jacobjeevan I want to work on this please assign it to me

**Comment by rithviknishad** [comment]
Already solved in form-field-v1 branch

<img width="1279" alt="Image" src="https://github.com/user-attachments/assets/198ddb60-7995-4304-bbc0-b42e10d55c9d" />
