### ISSUE TITLE
Add markdown editor for editing facility description

### ISSUE THREAD

**Issue by sainak** [coronasafe/care_fe#9549]
add [mdxeditor](https://mdxeditor.dev) in care to allow editing markdown for facility description field

keep it as adynamic import so it's only loaded when user wants to edit the description 

create a pr for `form-field-v1` branch

ref: https://github.com/ohcnetwork/care_fe/issues/9523

**Comment by srijantrpth** [comment]
Hi @sainak , Let me know if I can work on this issue.

**Comment by rajku-dev** [comment]
I would like to carry this task out @sainak

**Comment by Jacobjeevan** [comment]
@srijantrpth @rajku-dev Core team only for now for form-field-v1 branch 👍
