### ISSUE TITLE
No Notice Available Icon Misaligned in Mobile View

### ISSUE THREAD

**Issue by navaneeth0041** [coronasafe/care_fe#9559]
**Describe the bug**
The "No Notice Available" icon and text are improperly aligned when viewing the Notice Board section in mobile view.

**To Reproduce**

1. Go to Notice Board section
2. View in mobile screen (either on mobile device or using browser dev tools)
3. Observe the misaligned "No Notice Available" icon and text

**Expected behavior**
The "No Notice Available" icon and text should be properly centered and aligned in mobile view, matching the desktop layout.

**Screenshots**
![Image](https://github.com/user-attachments/assets/292c1801-caf6-4495-b836-358d2541235f)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser Chrome

**Additional context**
Issue only occurs in mobile viewport. Desktop view displays proper alignment.

**Comment by navaneeth0041** [comment]
@Jacobjeevan @bodhish Please check on this and if finds relevant I would like to work on this.

**Comment by rithviknishad** [comment]
@AnveshNalimela let's do this along with #9343 redesign
