### ISSUE TITLE
Scrollbar Visibility and UI/UX Enhancements in Users Information Screen in Mobile

### ISSUE THREAD

**Issue by ashwinpraveengo** [coronasafe/care_fe#9560]
**Describe the bug**
The scrollbar appears directly below the "User Information" section in Mobile View, creating an overlapping effect with the content. This impacts the layout and makes the interface look cluttered.

**To Reproduce**
- Go to the user section.
- Click on more information.
- Observe the scrollbar directly below the section, overlapping with the content.

**Expected behavior**
The scrollbar should not overlap with the "User Information" section. It should be aligned properly, without affecting the content layout.

**Screenshots**
![Image](https://github.com/user-attachments/assets/da2a80f2-c098-4e49-95e8-7e51c9960793)

**Additional context**
- File Size Indicator: The file size limit ("1MB max") in the "Change Avatar" section could be made clearer, such as using red text or better formatting for improved clarity.
- Active Tab Highlighting: The active tab's green underline is too subtle. Enhancing the visibility by bolding or highlighting the active tab text would improve the user experience.
- Instead of displaying "unknown"  in field where the value is not provided, it would be better to leave it blank.

**Comment by AdityaJ2305** [comment]
Hey @ashwinpraveengo , I would like to work on this issue

**Comment by ashwinpraveengo** [comment]
@Jacobjeevan  @bodhish 
Sir, I would like to work on this issue if it is considered relevant. Additionally, if the additional context is deemed useful, I am happy to work on that as well.

**Comment by Jacobjeevan** [comment]
The styling is in line with what we have elsewhere (green underline and the subtle text). Same goes for displaying unknown as the value. Thanks for the suggestions though.

**Comment by ashwinpraveengo** [comment]
But that horizontal scroll bar and green line is creating a overlap?
