### ISSUE TITLE
Modal Not Closing After Selecting a Facility for Discharge Patient

### ISSUE THREAD

**Issue by AdityaJ2305** [coronasafe/care_fe#9564]
**Describe the bug**
The modal does not close when a facility is selected for a discharge patient in `Care.do`

**To Reproduce**

1. Go to `Patient` section
2. Click on 'Discharged' tab
3. Modal will open to select facility and select any facility
4. On Selecting `facility` click on `Select`
5. See the error 

**Expected behavior**
The modal should close automatically after a facility is selected.

**Screenshots**
https://github.com/user-attachments/assets/beeeb274-caf9-48e5-9af1-7a28f0af4dee

**Comment by manmeetnagii** [comment]
@Jacobjeevan please assign this to me

**Comment by AdityaJ2305** [comment]
@manmeetnagii, this is for the care.do release and is specifically for core team members 😊.

**Comment by rithviknishad** [comment]
we no longer have discharged patients tab :)
