### ISSUE TITLE
Add Confirmation for Exporting

### ISSUE THREAD

**Issue by srijantrpth** [coronasafe/care_fe#9568]
**Is your feature request related to a problem? Please describe.**
This feature can be added when Facilities & Shifting Data is exported. Right now, we have a export button active which exports the data but doesn't gives the confirmation after the data is downloaded on Client side which will make it clear for the user that file is downloaded and not lead to duplicate downloads of a single file. 

https://github.com/user-attachments/assets/a31f94b3-e2a5-48df-a461-2fae1f6c21ac

**Describe the solution you'd like**
We can display a simple message confirmation that **Exporting Started** or **Download Successful** just like we have it for our other functionalities such as Volunteer Assignment like this:

![Image](https://github.com/user-attachments/assets/2c8af3bd-b812-498d-9825-e7fe079b9a74)

**Comment by srijantrpth** [comment]
Hi @Jacobjeevan , Let me know if I can work on this.

**Comment by vidipsingh** [comment]
Hi @srijantrpth @Jacobjeevan,

I’d like to work on this issue if you're open to it. Adding a download confirmation would improve the user experience and prevent duplicate downloads. Let me know if I can proceed.

**Comment by srijantrpth** [comment]
> Hi @srijantrpth @Jacobjeevan,
> 
> I’d like to work on this issue if you're open to it. Adding a download confirmation would improve the user experience and prevent duplicate downloads. Let me know if I can proceed.

Hi @vidipsingh, I am already working on this issue. Kindly look for other open issues or find a one on your own from the develop branch. Thank you

**Comment by vidipsingh** [comment]
Sure, no problem! Thanks for letting me know.

**Comment by srijantrpth** [comment]
Hi @rithviknishad , Please review the issue and let me know if I can add this feature

**Comment by Jacobjeevan** [comment]
I don't think this is necessary as the browser itself notifies whether download is triggered or not.
