### ISSUE TITLE
Incorrect online status for authenticated account's profile

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#9570]
**Describe the bug**
Online status for the authenticated account is showing last online 9 minutes ago after staying logged in for a while when I myself have the tab opened 😅 

**To Reproduce**

1. Open my profile page

**Expected behavior**
For authenticated accounts, always show online. 

**Screenshots**
<img width="1885" alt="Image" src="https://github.com/user-attachments/assets/11587a59-531f-4d2d-a3fa-882db63f5284" />

**Comment by Jeffrin2005** [comment]
@rithviknishad Can I work on this issue ?

**Comment by noufalrahim** [comment]
@rithviknishad can i work on this..

**Comment by abhimanyurajeesh** [comment]
@rithviknishad I guess I can help you with this! Can I work on this?

**Comment by Utkarsh-Anandani** [comment]
@rithviknishad can you assign the issue to me?

**Comment by NikhilA8606** [comment]
@rithviknishad Could you please assign the issue to me?

**Comment by rithviknishad** [comment]
@abhimanyurajeesh 

Do make sure you get the issue assigned before working on it. This is so that we avoid duplicate efforts. Ignoring for now since it's a minor change and first time contribution.
