### ISSUE TITLE
Misaligned Options in Patient Actions Section

### ISSUE THREAD

**Issue by Jeffrin2005** [coronasafe/care_fe#9571]
**Describe the bug**
Alignment of options like 'Investigations Summary' and 'View/Update Patient Files' , 'Reassign volunteer' , 'Disable Transfer' is not proper.

**To Reproduce**

1. Go to Patients tab
2. Click on any patients
3. Observe the misalignment of options like "Investigations Summary," "View/Update Patient Files",..

**Expected behavior**
The options should be properly aligned

**Screenshot**
![Image](https://github.com/user-attachments/assets/c888eb03-4f51-489c-9acc-7ce2587e034c)

**Desktop:**

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan  Can I work on this issue ?

**Comment by Jacobjeevan** [comment]
> [@rithviknishad](https://github.com/rithviknishad) [@Jacobjeevan](https://github.com/Jacobjeevan) Can I work on this issue ?

Already fixed in `form-field-v1` 👍
