### ISSUE TITLE
Display Facility Cover Image in Mobile View on the Facility Tab

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9577]
**Describe the bug**

When we open the facility homepage on a mobile device, the cover image is not visible.

**To Reproduce**

1. Go to the facility homepage.
2. See error

**Expected behavior**

The cover image should be visible in mobile view.

**Screenshots**

![Image](https://github.com/user-attachments/assets/da15615c-aab6-464d-aa7c-9efbeb3f5e5a)

**Comment by AdityaJ2305** [comment]
Hey @nihal467 , I would like to work on it
