### ISSUE TITLE
Issue in uploading images

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9582]
**Describe the bug**
The image dimensions requirement often prevent users from uploading the cover photo, leading to failed uploads in approximately 90% of cases. The required dimensions are a minimum of 400px in width and height, with a maximum of 1024px for both. Even a slight deviation from these limits frequently results in a poor user experience.

ux with normal photos from internet

https://github.com/user-attachments/assets/c2589424-7267-45d1-8301-72a2400bd676

**To Reproduce**

1. Go to '/facility'
2. Click on 'cover photo of any facility'
3. Click on Edit -> Upload an image
4. Choose an image and see if error occurs

**Expected behavior**
If an image is within the 1MB size limit but does not fit the required dimensions, it should be resized (stretched or shrunk) to match the required dimensions before upload, ensuring a smoother user experience

Proposed Solution 

https://github.com/user-attachments/assets/aeb11053-36e6-41aa-a509-8fde120b2047

**Desktop (please complete the following information):**

- Windows 11
- Google Chrome
- Version 131.0.6778.205 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rajku-dev** [comment]
I would like to work on this issue. @Jacobjeevan @rithviknishad @bodhish

**Comment by kabenari** [comment]
@Jacobjeevan  @gigincg @athulmanuel  would like to work on this issue

**Comment by rithviknishad** [comment]
This is expected behaviour.
