### ISSUE TITLE
CSS Misalignment for Authorized Buttons in Patient Details

### ISSUE THREAD

**Issue by JavidSumra** [coronasafe/care_fe#9586]
### Bug Description  
The CSS for authorized buttons is not consistent with other buttons.  

### Steps to Reproduce  
1. Navigate to the **Patients** section.  
2. Select any patient from the list.  
3. Observe the CSS misalignment in the buttons.  

### Expected Behavior  
The authorized button's CSS should align with the styling of other buttons.  

### Screenshots  
![Image](https://github.com/user-attachments/assets/f8c63264-14a2-43c7-ba4e-d5a74a5184fc)  

### Environment Details  
- **Operating System**: Ubuntu  
- **Browser**: Firefox  
- **Version**: 133.0.3 (64-bit)

**Comment by JavidSumra** [comment]
Hey @Jacobjeevan can you please assign this issue to me?
cc @rithviknishad

**Comment by Jacobjeevan** [comment]
This is already addressed in `form-field-v1`. This is the 3rd issue for the same problem, maybe I should keep this one open 😅

**Comment by 07Akashh** [comment]
Hey, @Jacobjeevan  can you please assign this issue to me?
I have solved this issue 
cc @rithviknishad 

<img width="293" alt="Image" src="https://github.com/user-attachments/assets/0071d183-bf6f-41f0-aa9f-0548cfa8c4fa" />

**Comment by Jacobjeevan** [comment]
> Hey, [@Jacobjeevan](https://github.com/Jacobjeevan) can you please assign this issue to me? I have solved this issue cc [@rithviknishad](https://github.com/rithviknishad)

Pleas check the labels before you request assignment :) Issue is already solved.
