### ISSUE TITLE
Restrict Comments: District Admin Only

### ISSUE THREAD

**Issue by Jeffrin2005** [coronasafe/care_fe#9587]
**Is your feature request related to a problem? Please describe.**
Currently, multiple user roles (Staff Developers, Doctor Developers, etc.) can comments in the system, which poses a risk because irrelevant comments.

**Describe the solution you'd like**

Implement restricted comment management permissions where:
- Only District Admins should have the ability to delete or edit comments
- Other roles (Staff Developers, Doctor Developers) should only have read and create permissions for comments

As you can see in the picture, many irrelevant comments are present.

![Image](https://github.com/user-attachments/assets/28374dbc-4daa-4ef2-9e99-066aa8a30ebf)

**Comment by rajku-dev** [comment]
Can i work on this issue?

**Comment by rajku-dev** [comment]
Can i work on this issue?

**Comment by rithviknishad** [comment]
in production there's no irrelevant comments like these
