### ISSUE TITLE
Bug: Patient Registration & Doctor Notes is not supporting multi-lines

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9592]
**Describe the bug**

- [ ] The patient registration form is not allowing users to enter multiple lines in the current address field.
- [ ] The doctor notes field is not reflecting multiple lines when users type in the doctor notes text area.
- [ ] the cards in patient details page for allow transfer and assign volunteer is broken

**To Reproduce**

1. Go to the patient tab
2. Click on Create patient
3. Enter the address in multiple lines

**Expected behavior**

- [ ] The patient registration form for the current address should allow multiple line entries.
- [ ] The doctor notes field should display the text in multiple lines, as entered.
- [ ] keep the card design consistent for allow transfer and assign volunteer

**Screenshots**

![Image](https://github.com/user-attachments/assets/635959ce-95e0-46d5-bdb9-3f637bc2dede)
![Image](https://github.com/user-attachments/assets/c0ce7bda-84c8-43a3-8e82-be19e37dc757)

**Comment by AdityaJ2305** [comment]
Hey @nihal467 , I would like to solve this issue

**Comment by AdityaJ2305** [comment]
@nihal467, I noticed it is working as you in the `Current Address` field, you can type multiple lines, as the cursor automatically moves to the next line when you reach the end of the input box.

**Comment by nihal467** [comment]
@AdityaJ2305 we should allow user to break the line whenever they want

**Comment by AdityaJ2305** [comment]
Got it! I’ve fixed the PatientNoteCard issue. Now, I’ll proceed to resolve the it . 😊

Edit: Ready for review

**Comment by AdityaJ2305** [comment]
The third issue has already been fixed in the January release branch. Since the same issue was opened multiple times, @Jacobjeevan opened it to prevent future occurrences of the same issue with `Done` tag (https://github.com/ohcnetwork/care_fe/issues/9586).

**Comment by Sulochan-khadka** [comment]
Is this still not merged? Let me know if i can raise a PR for this... @nihal467 @rithviknishad
