### ISSUE TITLE
Clear Button Fails to Clear Fields

### ISSUE THREAD

**Issue by Jeffrin2005** [coronasafe/care_fe#9597]
**Describe the bug**

The clear button is not clearing the fields.
when clicking clear button, it returns back to the page.

**To Reproduce**

1. Go to any tabs 
2. Click on "Advanced Filters"
3. Clear button is not clearing the input fields

**Expected behavior**
The clear button should clear all the text fields without returning back to the page.

**Record Clip**
https://github.com/user-attachments/assets/86d237fb-1fc3-40e2-b028-5ba63426915f

**Desktop:**

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan If this error is valid, Can I work on this issue?

**Comment by AdityaJ2305** [comment]
@Jeffrin2005  Clearing the input after applying the filter makes it work correctly.

**Comment by Jeffrin2005** [comment]
@AdityaJ2305 Hi, I've noticed that the fields only clear when all options are selected. However, when not all options are selected, the fields are not clearing properly

**Comment by AdityaJ2305** [comment]
the filters aren’t clearing even if all options are selected. They only clear if you apply them first and then click “clear.”
