### ISSUE TITLE
User Unable to Edit All Fields

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9598]
**Describe the bug**
A user on the `/users` page cannot edit personal information fields such as `Username` and `User Type`, even though these fields are visible in the corresponding view card.

**To Reproduce**

1. Go to '/users'
2. Click on `More details` for any user
3. Scroll down to 'Personal Information'
4. Click on Edit
5. See error

**Expected behavior**
To ensure consistency, the user should be able to edit all fields.

**Screenshots**

https://github.com/user-attachments/assets/e6004329-fe1d-4a3b-9f5d-6273c0543251

**Desktop (please complete the following information):**

- Windows 11
- Google Chrome
- Version 131.0.6778.205 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rajku-dev** [comment]
I would like to work on this issue. @Jacobjeevan @rithviknishad

**Comment by Jacobjeevan** [comment]
Expected behavior 👍
