### ISSUE TITLE
Redundant Spacing in Users List View

### ISSUE THREAD

**Issue by rajku-dev** [coronasafe/care_fe#9599]
**Describe the bug**
In the List View for all users on the `/users` page, there is unnecessary spacing in the `Name` column. Horizontal scrolling is required to view the remaining columns, such as `Status`, `Role`, `Home Facility`, `District` and `More Details` link. Some of these columns could easily fit into the extra space.

**To Reproduce**

1. Go to '/users'
2. Click on 'List'

**Expected behavior**
Proper Alignment for all columns on list view of users, 

**Screenshots**

https://github.com/user-attachments/assets/df419e13-5892-4325-867e-e54d6b21e9d6

**Desktop (please complete the following information):**

- Windows 11
- Google Chrome
- Version 131.0.6778.205 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rajku-dev** [comment]
I would like to fix this. Please assign me this issue.
@Jacobjeevan @rithviknishad

**Comment by Jacobjeevan** [comment]
Fixed in [staging](https://care-staging.ohc.network/users).

**Comment by rajku-dev** [comment]
> Fixed in [staging](https://care-staging.ohc.network/users).

Oh! another branch for Care 😄
