### ISSUE TITLE
Add ButtonV2 features in Shadcn Button Component

### ISSUE THREAD

**Issue by saikiranpatil** [coronasafe/care_fe#9603]
**Is your feature request related to a problem? Please describe.**
migrating from `ButtonV2` to shadcn `Button` requires us to use various things various purposes. For example:

- `AuthorizeButton` for authorization
- `onClick={()=>navigate(url)}` for links
- shadcn `Tooltip` component for toolptip

even AuthorizeButton does not support features like variants, refs, className and others.

**Describe the solution you'd like**
Modify the shadcn button components to handle all the above functions in single place just like `ButtonV2`. This would improve the developer experience and cleaner code.

@ohcnetwork/care-fe-code-reviewers

**Comment by rajku-dev** [comment]
I would like to work on this update.

**Comment by saikiranpatil** [comment]
@ohcnetwork/care-fe-code-reviewers
if this issue is valid, assign me

**Comment by Jacobjeevan** [comment]
No, we aren't modifying Shadcn components. You don't need to map exact 1:1 to the existing code - point is to get the same functionality, that could be achieved in other ways.
