### ISSUE TITLE
state update issue while uploading or removing the profile avatar

### ISSUE THREAD

**Issue by i0am0arunava** [coronasafe/care_fe#9604]
**Describe the bug**
On the profile page, when we upload or remove an avatar by clicking the button, the state should update immediately, allowing us to see the result without reloading the page. However, currently, the profile is updated, but we have to manually reload the page to view the changes. This is not the expected behavior.

**To Reproduce**

1. Go to profile
2. Click on delete or upload button in change avatar
3. See , the profile avatar is not updated and I have to reload to get the result

**Expected behavior**
After uploading or removing the profile avatar, the state should be updated automatically without needing to reload the page. 

**Screenshots**

here I have removed the avatar but still it is showing in the icon and I have to reload the page manually to see the result ,state update issue ...

![Image](https://github.com/user-attachments/assets/13641ff1-9f83-4acf-88b9-9f7066ac9559)

**Desktop (please complete the following information):**

- Version [latest]

**Comment by i0am0arunava** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to profile
> 2. Click on delete or upload button in change avatar
> 3. See , the profile avatar is not updated and I have to reload to get the result
> 
> **Expected behavior** If no one is currently working on the issue of updating the state after uploading or removing the profile avatar, it would be a good idea to create a GitHub issue for it.
> 
> Here's a short name for the issue and the expected behavior descriptio n:
> 
> ### Issue Title
> "Profile Avatar State Update"
> 
> ### Expected Behavior
> After uploading or removing the profile avatar, the state should be updated automatically without needing to reload the page.
> 
> **Screenshots** ![Image](https://github.com/user-attachments/assets/e30b71d9-6015-42e9-93d4-f8e1b781f470)
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [latest]

**Comment by i0am0arunava** [comment]
@rithviknishad @nihal467 ,can I work on this?

**Comment by bodhish** [comment]
Can you clean up the issue description?

**Comment by i0am0arunava** [comment]
> Can you clean up the issue description?

done

**Comment by i0am0arunava** [comment]
@bodhish ,can you assign this to me?

**Comment by devxspectre** [comment]
@bodhish assign

**Comment by i0am0arunava** [comment]
will be  fixed later by core team , so I am closing it
