### ISSUE TITLE
Eye Icon Design Mismatch in Password Fields

### ISSUE THREAD

**Issue by Jeffrin2005** [coronasafe/care_fe#9606]
**Describe the bug**
The eye icon used for toggling password visibility looks and behaves differently

**To Reproduce**

1. Navigate to login screen (can be seen on multiple pages)
2. Look for the password input field
3. Notice the eye icon on the right side of the password field

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/96d7dc45-885f-4061-bc38-9be2b8e38a1e)
![Image](https://github.com/user-attachments/assets/f10a62db-6dee-46e0-88de-574a569749f5)
![Image](https://github.com/user-attachments/assets/33092e75-77e5-4b02-a1ea-908e570c028e)

**Desktop:**

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Can I work on this issue ?

**Comment by ashwinpraveengo** [comment]
@rithviknishad @Jacobjeevan Can i Work on this issue

**Comment by Jacobjeevan** [comment]
> [@rithviknishad](https://github.com/rithviknishad) [@Jacobjeevan](https://github.com/Jacobjeevan) Can I work on this issue ?

Login page was also reworked in `form-field-v1`. We aren't displaying the eye icon right now (maybe we will add it in the future), but closing this.
