### ISSUE TITLE
Add "view latest consultation" or "Download Latest Discharge Summary" button on discharged patient

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#9610]
**Is your feature request related to a problem? Please describe.**
Currently, users are facing issues with accessing and downloading discharge summaries. previously, the default page opened for discharged patients was the patient dashboard/consultation page itself. now users have to click on encounter from patient details page and then go to discharge summary. 
its better to avail "View latest consultation" or "Download latest discharge summary" button on discharged patients details page.

**Describe the solution you'd like**

- [ ] Add View latest consultation on discharged patients details page or,
- [ ] Add Download latest discharge summary button

Reported by Hub engineers on tech review calls
**Describe alternatives you've considered**

**Additional context**

**Comment by vaibhavgarg25** [comment]
Can I work on this issue? @samholics

**Comment by rajku-dev** [comment]
I would like to work on this feature

**Comment by vidipsingh** [comment]
Hi @samholics, can I take on this issue?

**Comment by rithviknishad** [comment]
Will revisit the issue once rearchitecturing is done
