### ISSUE TITLE
Add new Nursing Care procedures

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#9612]
**Is your feature request related to a problem? Please describe.**
Add new Nursing Care procedures to the Nursing care dropdown list - requested by arike . confirmed nd discussed with dr athul.

Shower Bath
Nail Care
Nasal Care
Uro condom Care
Urobag Change
Catheter Removal
 Bladder wash
 RT check
 Oral Feeding
 Infusions
 IVF Injection - infertility
 Cannula Removal
 Cannula Insertion
 Death Care
 Death Declaration
 Suturing
 Suture Removal

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rithviknishad** [comment]
Solved with FHIR forms
