### ISSUE TITLE
Using Shadcn Date Time Component

### ISSUE THREAD

**Issue by saikiranpatil** [coronasafe/care_fe#9618]
**Is your feature request related to a problem? Please describe.**
Issues similar as described in #8994 

- [ ] Regardless of the user's system time preference, the text field displays time in 24-hour format, while the selection component defaults to a 12-hour format. This inconsistent behavior is not ideal for a component.
- [ ] It is not possible to input "01" in the minutes part of the component; the input text area always shows "1," automatically removing the "0" for single-digit entries.

**Describe the solution you'd like**
As most of the components are migrating to shadcn, we could utlize [Shadcn Date Time Picker](https://time.rdsx.dev/) Code and modify it as per our requirement. This would solve most of the date time component bugs.

**Comment by saikiranpatil** [comment]
@ohcnetwork/care-fe-code-reviewers 
if this issue is valid, assign this to me

**Comment by rajku-dev** [comment]
@saikiranpatil did you tried rendering shadcn `Calendar`? Its css is little broken in my case.
![Image](https://github.com/user-attachments/assets/688dbcda-edde-4ed0-b94f-6769e0672653)

**Comment by saikiranpatil** [comment]
> [@saikiranpatil](https://github.com/saikiranpatil) did you tried rendering shadcn `Calendar`? Its css is little broken in my case.

not sure from where you are trying this from

**Comment by rajku-dev** [comment]
https://ui.shadcn.com/docs/components/calendar
datepicker you mentioned in issue description uses the same Calendar component from ShadCN UI

**Comment by rajku-dev** [comment]
https://ui.shadcn.com/docs/components/calendar
datepicker you mentioned in issue description uses the same Calendar component from ShadCN UI
> > [@saikiranpatil](https://github.com/saikiranpatil) did you tried rendering shadcn `Calendar`? Its css is little broken in my case.
> 
> not sure from where you are trying this from
> 
>

**Comment by rithviknishad** [comment]
We already have these, which is sufficient.

<img width="912" alt="Image" src="https://github.com/user-attachments/assets/a25a0164-76c7-4424-8a6e-cffb93d72401" />
